### ISSUE TITLE
Ethereum Classic EIP-2124 fork id management is broken.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [hyperledger/besu#1002]
https://github.com/hyperledger/besu/pull/979 and https://github.com/hyperledger/besu/pull/981 pull requests broke fork id management on Ethereum Classic.
The problem seems to be located in `ForkIdManager.getLatestForkId` method. A quick test showed using `legacyForkAndHashList` instead of `forkAndHashList` makes it work. Should verify the impact on ETH.

**Comment by gitr0n1n** [comment]
@edwardmack @GregTheGreek is this going to be resolved in the next release?

**Comment by abdelhamidbakhta** [comment]
> @edwardmack @GregTheGreek is this going to be resolved in the next release?

Yes.
