### ISSUE TITLE
web3_clientVersion return vnull version

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#1010]
### Description

If you call the `web3_clientVersion` JSON RPC method you have `vnull` version returned.

````
curl --location --request POST 'http://127.0.0.1:9000' \
--header 'Content-Type: text/plain' \
--data-raw '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}'
````

````
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "besu/vnull/osx-x86_64/adoptopenjdk-java-13"
}
````

### Acceptance Criteria
* Get the current version of Besu

### Steps to Reproduce (Bug)
1. call the `web3_clientVersion` JSON RPC method

**Expected behavior:** Get the current version of Besu

**Actual behavior:** vnull is returned

**Frequency:** 100% (tested on goerli)

### Versions (Add all that apply)
* Software version: [`Besu - 1.4.7-SNAPSHOT`]
* Java version: [`openjdk version "13.0.2" 2020-01-14`]

**Comment by shemnon** [comment]
How does this happen?  From a downloaded jar version?  From a `gradlew installdist` execution, from the IDE?  I never see it in a fully build production version.

**Comment by matkt** [comment]
> How does this happen? From a downloaded jar version? From a `gradlew installdist` execution, from the IDE? I never see it in a fully build production version.


I can reproduce it everytime but only if I start Besu from Intellij

**Comment by vmichalik** [comment]
@matkt is this still an issue for you?

**Comment by non-fungible-nelson** [comment]
no longer reproducible
