### ISSUE TITLE
Investigate JSON RPC streaming

### ISSUE THREAD

**Issue by abdelhamidbakhta** [hyperledger/besu#1036]
Instead of creating a jackson object for an entire array of results and then serializing it, huge queries like range-based `eth_getLogs` would benefit from being able to be streamed.

We would need to manually write the beginning of the json array and the interspersing separators. We would create jackson objects for each result that would rely on the jackson serialization. 

Maybe we can do something like this in reverse?
https://www.nurkiewicz.com/2017/09/streaming-large-json-file-with-jackson.html

**Comment by RatanRSur** [comment]
would help with #944

**Comment by macfarla** [comment]
Fixed in #3076
