### ISSUE TITLE
rejectIncomingConnectionFromDisallowedPeer timed out in unit tests

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#1052]
In org.hyperledger.besu.ethereum.p2p.network.P2PNetworkTest the rejectIncomingConnectionFromDisallowedPeer unit test timed out during a master build.

[build 20226](https://app.circleci.com/pipelines/github/hyperledger/besu/4330/workflows/62225074-7a02-47a9-a6c5-d86fd2e56eff/jobs/20226)

**Comment by RatanRSur** [comment]
Couldn't reproduce.
