### ISSUE TITLE
Don't abbreviate words on the stack or memory for debug_traceTransaction.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [hyperledger/besu#1066]
### Description

- Put the full 32-byte words in the JSON response
- Remove leading `0x`

**Comment by davemec** [comment]
This ticket brings the besu code into compliance with other clients. The following was reported from the Truffle team and has been fixed with this PR.

> In Geth, words on the stack or in memory are always given as a full 32 bytes.  Whereas Besu abbreviates them.  So e.g. in Besu you'd see "0x1", whereas in Geth you'd see "0000000000000000000000000000000000000000000000000000000000000001"
