### ISSUE TITLE
Check enclaveKey matches privateFrom 

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#1069]
When calling one of the following functions on the OnChainPrivacyGroupManagementInterface 

- function addParticipants(bytes32 enclaveKey, bytes32[] calldata participants) external returns (bool);
- function removeParticipant(bytes32 enclaveKey, bytes32 account) external returns (bool);
- function getParticipants(bytes32 enclaveKey) external view returns (bytes32[] memory);
- function canUpgrade(bytes32 enclaveKey) external view returns (bool);

before executing the private transaction we need to check that the first parameter (enclaveKey) is the same as the privateFrom.

**Comment by MadelineMurray** [comment]
No longer needed
