### ISSUE TITLE
Add alternate names for whitelist JSON RPC endpoints which use allowlist instead

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#1090]
Moving towards more inclusive language. Endpoints:
perm_addAccountsToWhitelist
perm_getAccountsWhitelist
perm_removeAccountsFromWhitelist

perm_addNodesToWhitelist
perm_getNodesWhitelist
perm_removeNodesFromWhitelist

also update corresponding variable names throughout code

**Comment by arash009** [comment]
To confirm:

- Add an alternative option with names that include "allowlist" instead of "whitelist"
- Current options remain but will be marked as "deprecated"
- Changelog updated
- Breaking change warning added to changelog for 1.6

**Comment by sambacha** [comment]
so just to confirm this will, in essence, be a `private hidden:true` cli option correct?  

ensuring a transition period should users not know of this change would be helpful.

thanks!

**Comment by arash009** [comment]
@macfarla can confirm how it will be implemented, but this should go through a deprecation period (at least 1 major release, so v1.6) where the original option will still be available before being removed in a future release.

**Comment by macfarla** [comment]
As per the changelog, the "allowlist" versions of CLI, JSON-RPC and config file key values have already been added and the "whitelist" versions deprecated. "whitelist" will be removed, as a breaking change, in future (likely 1.6) 

Specifically for the CLI option - it's not hidden, it's just an alternate name for the same CLI option. So at this stage they can be used interchangeably.

https://github.com/hyperledger/besu/blob/master/CHANGELOG.md#15
