### ISSUE TITLE
testCreateFindDeleteFindPrivacyGroup failed in integrationTests

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#1099]
in org.hyperledger.besu.enclave.EnclaveTest the testCreateFindDeleteFindPrivacyGroup unit test failed (after restart it was ok)
Build : https://app.circleci.com/pipelines/github/hyperledger/besu/4497/workflows/4c54d68d-e1ef-4ac8-8053-3a94d1c780ea/jobs/21125/tests

**Comment by RatanRSur** [comment]
@jframe I assigned you because you're the most active person on the git blame and I just needed someone to pay attention to it :) Feel free to pass it on if you need.

**Comment by macfarla** [comment]
Have run the full integration tests and this test repeatedly locally without any failures. Need to see if this test has failed recently in CI

**Comment by macfarla** [comment]
This test has not failed in CI since build 21125. Closing this issue since we cannot reproduce.

**Comment by macfarla** [comment]
Failed again https://app.circleci.com/pipelines/github/hyperledger/besu/4989/workflows/42fb8865-c4d8-4f4d-9524-26c62e6d62d6/jobs/23842

**Comment by macfarla** [comment]
It fails here: EnclaveTest:153

    PrivacyGroup[] findPrivacyGroupResponse = enclave.findPrivacyGroup(publicKeys);

    assertThat(findPrivacyGroupResponse.length).isEqualTo(1);
