### ISSUE TITLE
Allow IBFT2 to specify an explicit mining beneficiary and block reward

### ISSUE THREAD

**Issue by rain-on** [hyperledger/besu#1119]
Currently IBFT2 is hardcoded to provide the following behaviour:
* 0-Eth block reward
* Transaction Fees paid to the coinbase specified in the block header (aka the block proposer)

It is proposed that this be changed such that the block reward, and mining beneficiary be specified in the genesis file, and be unmodifiable for the life of the network.

This will require:
* Adding 2 fields to the IBFT2 section of the genesis file
* Using these values during Ibft Protocol Schedule creation to modify each ProtocolSpec

As an aside, the BlockProcessor will need to be updated to pay mining rewards to the address specified by the MiningBeneficiaryCalculator, rather than the explicit coinbase.

**Comment by bgravenorst** [comment]
Documented here:
https://besu.hyperledger.org/en/latest/HowTo/Configure/Consensus-Protocols/IBFT/
