### ISSUE TITLE
Use 'Transitions' in the genesis file to change Mining Beneficiary and/or Block reward in IBFT2

### ISSUE THREAD

**Issue by rain-on** [hyperledger/besu#1120]
Assumes network-level block reward and mining beneficiary has already been complete for IBFT2.
===

Extend the transitions section of the Genesis file to allow the mining beneficiary and/or the block reward to be changed at any block.

This will mean the "Transitions" will need to be applied to an existing ProtocolSchedule by:
* Inserting a new milestone at the specified block (but otherwise identical to the preceding milestone), and * modify the existing behaviour of all latter milestones with the change specified in the transition.

**Comment by vmichalik** [comment]
Closed by #1977
