### ISSUE TITLE
check blake test on besu

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#1129]
I have this test failing on besu:
```
./retesteth -t GeneralStateTests/stTimeConsuming -- --all --clients "besu" --singletest "CALLBlake2f_MaxRounds"
```

**Comment by shemnon** [comment]
Is it timeout related?  If so it's a low priority to fix.  If it's an incorrect answer that's a different story.

We are still using the java code for blake and the maxRounds test is brutal... 4 billion rounds whereas the typical call is *12*.  That's enough gas to fill 320 block.

**Comment by shemnon** [comment]
You will also note that nimbus, ehtereum-js, trinity, and EOS disable the test because it takes too long to run.

**Comment by winsvega** [comment]
Confirm. low cpu power makes it impossible to run in a reasonable time. 

However this logs look like there are error happening:
https://pastebin.com/3GzVmrHm

**Comment by shemnon** [comment]
If a RPC call goes over a minute vertx gets itchy and complains loudly in the log.  These log entries are expected and consistent in a timeout situation.

**Comment by winsvega** [comment]
Ok. Then this test passes 
It also took unreasonable amount of time on aleth to pass this test even with 4Ghz
(Took around 10 minutes)
