### ISSUE TITLE
Over 1000 Exprired Eth Transaction Messages

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#1138]
I haven't nailed down exactly under what circumstances this occurs but we're seeing this `WARN`:
`1000 expired transaction messages have been skipped.`

### Versions
* Software version: `1.4.2`
* Cloud VM, type, size: Amazon Web Services i3-large

**Comment by shemnon** [comment]
This is what happens when we max out the CPU with other tasks.  Two things:

* i3.large has only 2 cores.  use a bigger box
* 1.4.2 did not have native EC curve crypto.  Use a more recent build and performance will improve.

My recommendation is close won't fix.
