### ISSUE TITLE
Fix hive consensus tests

### ISSUE THREAD

**Issue by davemec** [hyperledger/besu#1151]
Currently we fail 2 consensus tests [Sample Run](https://hivetests.ethdevops.io/?suite=1592288449-77bdbbf2aaf65840b86f91c5b95a18bf.json)

- CALLBlake2f_MaxRounds_d0g0v0_Istanbul
- sstore_combinations_initial00_d133g0v0_Istanbul

**Comment by non-fungible-nelson** [comment]
Closed as stale and fixed in latest hive
