### ISSUE TITLE
Missing results from eth_getLogs request

### ISSUE THREAD

**Issue by ajsutton** [hyperledger/besu#1153]
### Description
When requesting logs from the Altona deposit contract, Besu misses logs from a number of blocks.  I've reproduced this with two completely separate Besu instances.

With a Besu sync'd to Görli run:
```
curl --fail -H "Content-Type: application/json" -d "{\"id\": 1, \"method\": \"eth_getLogs\", \"params\": [{\"topics\":[\"0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5\"],\"fromBlock\":\"0x2c9d91\",\"toBlock\":\"0x2ccf3d\",     \"address\":[\"0x16e82d77882a663454ef92806b7deca1d394810f\"]}]}" http://localhost:8545 | jq '.result[].blockNumber'
```

This lists all the blocks that deposit event logs were found in.  When compared to the same request made against Infura a number of blocks are missing including 0x2ca58d, 0x2ca5ef and more.  I've listed the two outputs I get at https://gist.github.com/ajsutton/290b3307be7d5f9e353ee77b606ecd75

### Versions (Add all that apply)
* Software version: besu/v1.5.0-RC1/linux-x86_64/corretto-java-11
* Java version: 
```
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
```

**Comment by abdelhamidbakhta** [comment]
Hey @ajsutton i pushed a tentative fix and tried manually, it seems to work well.
Could you please test again with Besu instead of Infura ?

**Comment by timbeiko** [comment]
Got a :+1: from Adrian that they're back running on Besu and it seems to be working. Will close and we can reopen if this issue ever shows up again.

**Comment by ajsutton** [comment]
Reopening this one as it happened again with a freshly sync'd besu 1.5.1 node on Görli using the Medalla contract. 
One example of a missing deposit is:
```
curl --fail -H "Content-Type: application/json" -d "{\"id\": 1, \"method\": \"eth_getLogs\", \"params\": [{\"topics\":[\"0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5\"],\"fromBlock\":\"0x2FF3FC\",\"toBlock\":\"0x2FF3FC\",     \"address\":[\"0x07b39F4fDE4A38bACe212b546dAc87C58DfE3fDC\"]}]}" http://localhost:8545 | jq '.result[].blockNumber'
```

In all there were 43 events missed between blocks 3086571 and 3155624.

**Comment by schroedingerscode** [comment]
@ajsutton Let's talk through this so I better understand how the node was set up. It'd be even better if the node that you used in the `curl` above is still running and I could grab its log caches.

I ran the same eth_getLogs call on a v1.5.1 node I've had running since 29 July, and I got the following result, which seems to agree with Görli Etherscan.

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "logIndex": "0x0",
      "removed": false,
      "blockNumber": "0x2ff3fc",
      "blockHash": "0xe7e15f383daed994c6db4bd8fe103bd26f455ca1816bd4d9824d0d11043a0ba7",
      "transactionHash": "0xb85bf44d3d2a732e788ba523840f38960b601ba285911c7de09b016a540d8a50",
      "transactionIndex": "0x1",
      "address": "0x07b39f4fde4a38bace212b546dac87c58dfe3fdc",
      "data": "0x00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003091a5a8b7b579dc6752ec8bcc8824439430c8e67598736ba1c25d84be5f48e557a05a9b93cfb60c8e49fe5ca5d5ef0f3100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000f025443e81869360513f5aa7806fb348f7442316393ed35aa880cfce2d3415000000000000000000000000000000000000000000000000000000000000000800405973070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060b4e56d6dbd5f91fab790781ef9b0e4324a6eaf91b548c49f3c6d2fc7e049f0bb46d00085696cb2a5544324c43699fd09003d4b767fd90b4867bb38212d2434d309c80482b3bae9231e1fd9477aa0639b9d00af3662a6720db1d660bd596733710000000000000000000000000000000000000000000000000000000000000008e23d000000000000000000000000000000000000000000000000000000000000",
      "topics": [
        "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
      ]
    }
  ]
}
```

https://goerli.etherscan.io/tx/0xb85bf44d3d2a732e788ba523840f38960b601ba285911c7de09b016a540d8a50

**Comment by ajsutton** [comment]
I've put the list of deposits found from a node pointed at Infura (good-deposits.yaml) and one pointed at Besu (bad-deposits.yaml) at https://github.com/ajsutton/eth2-states/tree/master/medalla-genesis

If you search for "errors" in the bad deposits that's the first deposit after one that was missed (a diff of the two files shows what's missing well too).

**Comment by ajsutton** [comment]
This appears to still be an issue even with #1351 merged.

Running `v1.5.5-dev-65bb27c4` it went back and reindexed existing data which fixed the previous missing logs but after a while it missed a new log:

```
curl --fail -H "Content-Type: application/json" -d "{\"id\": 1, \"method\": \"eth_getLogs\", \"params\": [{\"topics\":[\"0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5\"],\"fromBlock\":\"0x33A3A7\",\"toBlock\":\"0x33A3A7\",     \"address\":[\"0x07b39F4fDE4A38bACe212b546dAc87C58DfE3fDC\"]}]}" http://10.0.1.165:8545 | jq '.result[].blockNumber'
```

That returns nothing on my test box (ec2-18-222-223-242.us-east-2.compute.amazonaws.com) and matches the log on Infura.  The block is https://goerli.etherscan.io/block/3384231
