### ISSUE TITLE
lastSeenAndFirstDiscoveredTimestampsUpdatedOnMessage failed in unit tests

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#1157]
In `org.hyperledger.besu.ethereum.p2p.discovery.PeerDiscoveryTimestampsTest` the `lastSeenAndFirstDiscoveredTimestampsUpdatedOnMessage` unit test failed during a build.

build https://app.circleci.com/pipelines/github/hyperledger/besu/4624/workflows/f5ae06e4-9d52-4d1a-ba21-ec87d7737ba4/jobs/21807

From ticket https://github.com/hyperledger/besu/issues/1163 : `If I run it n>1 times locally in IntelliJ, the first run succeeds and subsequent ones fail ~80%, but running n=1 at a time it works (locally).`

**Comment by macfarla** [comment]
failed again https://app.circleci.com/pipelines/github/hyperledger/besu/4700/workflows/436cb5b1-7cc2-48d9-8f2f-e9bbade83fea/jobs/22248/steps

**Comment by macfarla** [comment]
https://app.circleci.com/pipelines/github/hyperledger/besu/4706/workflows/2a6548ea-d8e1-4302-ab79-c293222eba7f/jobs/22265/steps
