### ISSUE TITLE
Personal support

### ISSUE THREAD

**Issue by noahsalvadordenjo** [hyperledger/besu#1158]
Hi i would like to use besu with the personal rpc, unfortunately this is currently not supported. Will this be supported in the future?

**Comment by MadelineMurray** [comment]
hi @noahsalvadordenjo - Besu deliberately doesn't support key management inside the client. Documentation around this is here - https://besu.hyperledger.org/en/stable/HowTo/Send-Transactions/Account-Management/ 

If what you're trying to achieve isn't covered there, could you provide some more details about what you're trying to achieve with the personal rpc?

**Comment by noahsalvadordenjo** [comment]
```
web3.eth.personal.newAccount('Password')
````
,
```
web3.eth.personal.unlockAccount(address, password, duration)
```
and
```
web3.eth.sendTransaction(from, to, value, gas)
```

**Comment by MadelineMurray** [comment]
Those methods won't be added to Besu because they'd require key management to be done inside the client.  

EthSigner is a PegaSys product for transaction signing that could be used instead - https://docs.ethsigner.pegasys.tech/en/stable/

**Comment by MadelineMurray** [comment]
@noahsalvadordenjo - I'm closing this one based on the above.  Let us know if you've got any further questions about EthSigner or what's covered in the docs on account management.
