### ISSUE TITLE
Test 25M Gas Blocks on EIP-1559 Private Network

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#1167]
One of the biggest risks in EIP-1559 is whether the network can handle larger blocks, even for a short duration. To begin de-risking this part of the work, we should set up a private 1559 network running geth and Besu where we fill blocks with transactions for a long amount of time and quantify the performance/stability impact of this on the nodes. 

Specifically, we should:
* Have >1 mining node on the network
* Have 4-5 total nodes, ideally in different AWS regions 
* Automate the sending of a large amount of transaction to nodes on the network (both legacy and 1559-style)
* Keep metrics on the node and evaluate what happens when blocks are consistently at a 25M gas

Idea: 
* We shorten the transition period in the EIP from 800 000 blocks to 8000 blocks, run a clique network with 1559 enabled on block 1, and let the network run ~10,000 blocks, ideally with most of them full.

**Comment by abdelhamidbakhta** [comment]
https://github.com/PegaSysEng/eip1559-tx-sender

**Comment by abdelhamidbakhta** [comment]
Binance ERC20 token https://etherscan.io/address/0xB8c77482e45F1F44dE1745F52C74426C631bDD52#code

**Comment by matkt** [comment]
EIP 1559 Configuration

Geth (Genesis 100 accounts provisionned + 3 node keys)
Besu (Genesis 100 accounts provisionned + 3 node keys) - Besu - Node 1 is the signer


[https://app.zenhub.com/files/206414745/9bfa431b-6638-4bad-abee-cdb691e21a39/download](https://app.zenhub.com/files/206414745/9bfa431b-6638-4bad-abee-cdb691e21a39/download)
