### ISSUE TITLE
Privacy API method priv_getPrivacyPrecompileAddress is not onchain privacy group 'aware'

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu#1194]
### Description
As a user, I want to be able to get the address of the privacy precompile contract so that I can create 'valid' privacy marker transactions. 

### Acceptance Criteria
* priv_getPrivacyPrecompileAddress JSON-RPC API method returns the value of the precompile address used with the configured privacy group management mechanism. 

### Steps to Reproduce (Bug)
1. Enable on-chain privacy groups
2. Call priv_getPrivacyPrecompileAddress

**Expected behavior:** [What you expect to happen]

When on chain privacy groups are enabled this method should return the address of the on-chain precompile contract.

**Actual behavior:** [What actually happens]

Get the address of the off-chain privacy group pre-compile contract.

**Frequency:** [What percentage of the time does it occur?]

Always

### Versions (Add all that apply)
* Software version: 1.5.0-RC2

### Additional Information

The assumption is that off-chain and on-chain privacy groups are mutually exclusive. If this assumption is invalid then a new API method will need to be added.

**Comment by macfarla** [comment]
The fix for #469 should resolve this issue, do let us know if there's still an issue!
