### ISSUE TITLE
Why are snapshots stored in Bintray and JCenter

### ISSUE THREAD

**Issue by hemanthsridhar** [hyperledger/besu#1195]
Hi,

I see that there are SNAPSHOT versions of besu library being stored in Bintray and JCenter. 

**HOW** was it created?
Bintray UI does not allow SNAPSHOT versions to be created.

<img width="907" alt="Screenshot 2020-07-06 at 1 59 11 PM" src="https://user-images.githubusercontent.com/13584014/86575062-4f04c880-bf94-11ea-92a2-39b61a9af098.png">

**WHY** was it created?
SNAPSHOT versions are not supposed to be present in the release repository. 

<img width="657" alt="Screenshot 2020-07-06 at 2 24 45 PM" src="https://user-images.githubusercontent.com/13584014/86575212-87a4a200-bf94-11ea-9ec1-acb7381f7168.png">

<img width="378" alt="Screenshot 2020-07-06 at 2 26 25 PM" src="https://user-images.githubusercontent.com/13584014/86575319-b3278c80-bf94-11ea-9d12-7c2f4d496da3.png">

**Comment by vmichalik** [comment]
I believe these were published using Artifactory and not the Bintray UI. Generally speaking the besu-contributors channel over on chat.hyperledger.org is best for questions like these! Closing for now.
