### ISSUE TITLE
Add tests for TransactionLogBloomCacher

### ISSUE THREAD

**Issue by davemec** [hyperledger/besu#1226]
### Description
Technical Debt - there are no tests for the TransactionLogBloomCacher class.

### Acceptance Criteria
* unit tests added

**Comment by matkt** [comment]
This ticket is no longer relevant. Tests are now present to test this class 

https://github.com/hyperledger/besu/blob/e230a445bb457bbac27bf4c384da449ccbd3f043/ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/cache/TransactionLogBloomCacherTest.java
