### ISSUE TITLE
State backup and Restore

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#1230]
Umbrella issue for State Backup and restore, which itself is a sub issue of [Bonsai Tries (#1229)](1229)

Instead of fast syncing all the trie branches from a peer a set of files will be produced so that a node, in a disconnected state, can import and reconstruct the blockchain without having to replay from zero.  Headers, Bodies, and Receipts will be exported and the leaf nodes of the account trie and storage tries at a specified block are exported.  Clients write the block history into their database and then import the state and reconstruct the trie branches from the supplied leaf data.

**Comment by non-fungible-nelson** [comment]
Closed as subsumed by snapshots and stale.
