### ISSUE TITLE
JSON-RPC method net_version should return network ID instead of chain ID

### ISSUE THREAD

**Issue by sammy1991106** [hyperledger/besu#1300]
### Description
As documented at Ethereum wiki https://eth.wiki/json-rpc/API, JSON-RPC method net_version should return network ID instead of chain ID. For Ethereum Classic, the Chain ID is 61 and network ID is 1. Core-Geth, Multi-Geth, OpenEthereum all returns 1 for the RPC call. However, Hyperledger Besu returns 61 which is the Chain ID instead of the network ID.  

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
Core-Geth: 
```
>>> curl -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://core-geth/rpc
{"jsonrpc":"2.0","id":67,"result":"1"}
```

Multi-Geth:
```
>>> curl -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://multi-geth/rpc
{"jsonrpc":"2.0","id":67,"result":"1"}
```

OpenEthereum: 
```
>>> curl -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://parity/rpc
{"jsonrpc":"2.0","result":"1","id":67}
```

And Hyperledger Besu: 
```
>>> curl -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://hyperledger-besu/rpc
{
  "jsonrpc" : "2.0",
  "id" : 67,
  "result" : "61"
}
```

**Expected behavior:** [What you expect to happen]
`net_version` returns 1 instead of 61 for network Ethereum Classic

**Actual behavior:** [What actually happens]
`net_version` returns 61 for network Ethereum Classic, which is the chain ID

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`] 1.5.1
* Java version: [`java -version`] 11
* OS Name & Version: [`cat /etc/*release`] openjdk:11-jre-slim-buster
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Additional Information
https://github.com/hyperledger/besu/blob/732cfcccc919f80db4150ccc4767f6b7fed63fa5/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/NetVersion.java It should be pretty straight forward to fix. Just make this class store/return networkId instead of chainId.

**Comment by timbeiko** [comment]
@edwardmack given this is an ETC issue, could you please have a look? Thank you!

**Comment by GregTheGreek** [comment]
@timbeiko Do you mind also cc'ing myself in the future :)

**Comment by timbeiko** [comment]
Will do @GregTheGreek !
