### ISSUE TITLE
Allow sub commands access to options and functionality that are currently private within BesuCommand

### ISSUE THREAD

**Issue by brianmcgee** [hyperledger/besu#1306]
### Description 

As someone writing plugins with their own sub commands, I would like access to much of the private properties and functionality within `BesuCommand`.

Extending the Besu cli functionality with sub commands is possible by providing a mixin via the `PicoCLIOptions` service on registration. However when those sub commands execute, they do not have access to things such as the base cli options `dataPath`, `network` and so on that are specified in `BesuCommand` but which are currently private. In addition, the run method for `BesuCommand` performs some useful initialisation using internal builders and other state. 

Ideally there would be some way for sub commands to re-use the base initialisation code and common cli options as well as use services they have registered via their own plugin. 

I can understand why the cli options are currently private since they are required to be mutable in order to function properly with PicoCli. Perhaps they can be exposed in a read-only fashion via a service within the plugin context. 

If this were to be the case, then the plugin context would need to be initialised before a sub command executes. Which would require some way of re-using `BesuCommand` to perform this initialisation before continuing with the execution of the sub command run method.

If an approach is agreed upon I would happy to implement it as this is currently a blocker for me.

**Comment by brianmcgee** [comment]
In the draft PR I've added the `BesuConfiguration` service to the plugin context during the prepare plugins phase, instead of later as part of the run method of `BesuCommand`. 

In addition I made the plugin context public. This means you can now access the plugin context through the user object available in the top most parent command that you can access via the command spec property. 

I've tested this with a local snapshot version:

```kotlin
@Command(
  name = "replication",
  subcommands = [
    ReplicationRestoreCommand::class,
    ReplicationExportCommand::class
  ],
  description = ["Replication of your Besu key/value storage for incremental backup and read only replicas."]
)
class ReplicationSubCommand : Runnable {

  @Spec
  private lateinit var spec: CommandSpec

  val besuCommand: BesuCommand by lazy {
    spec.parent().userObject() as BesuCommand
  }

  val pluginContext: BesuContext by lazy { besuCommand.context }

  val storageService: StorageService by lazy {
    pluginContext
      .getService(StorageService::class.java)
      .orElseThrow { IllegalStateException("Storage service not found in plugin context") }
  }

  val besuConfig: BesuConfiguration by lazy {
    pluginContext
      .getService(BesuConfiguration::class.java)
      .orElseThrow { IllegalStateException("Besu configuration not found in plugin context") }
  }
  ...
}

```

In addition I modified the `StorageService` to be able to return the configured key value storage factory. 

I feel that having the `BesuConfiguration` and configured storage factory available for sub commands is useful, but admittedly 
this is heavily skewed towards my own use case at the moment.

Additional changes I think would be worthwhile are adding a `EthConfiguration` service, which makes available the genesis config and network id. Both are useful pieces of information, but again I recognize this is skewed towards my own use cases.

As for the other config options/config currently private within `BesuCommand`, on further inspection there isn't much else that I believe would be useful to expose.

**Comment by shemnon** [comment]
I think it can be configured without the need for the CLI interceptor.  Will #1358 address the issue?  (It just contains the `BesuConfigurationService` changes)

**Comment by brianmcgee** [comment]
Earlier initialisation of the `BesuConfigurationService` would definitely help. I also saw that Pico cli has been updated to 4.5.0 which I think brings in some other possibilities. I'll wait for #1358 to be merged and then have a play around, see what edge cases remain.

**Comment by timbeiko** [comment]
FYI @brianmcgee #1358 has been merged 😄

**Comment by vmichalik** [comment]
Hey @brianmcgee, appreciate it is almost a year later, but just wanted to see if the above thread resolved your issue? If so please go ahead and close the issue :-)

**Comment by vmichalik** [comment]
please go ahead and reopen or create a new ticket if you have further issues!
