### ISSUE TITLE
Expose more internals via the plugin context

### ISSUE THREAD

**Issue by brianmcgee** [hyperledger/besu#1307]
### Description

As a plugin writer, I would like access to more internal services and state such as protocol schedules, `Blockchain` and the `WorldStateArchive`.

Having internal read-only access to the `Blockchain` and `WorldStateArchive` is immensely useful when initialising and maintaining additional indexes or custom tracing for example as we are doing in our plugin Exflo.

Currently it is only possible to achieve this by intercepting the instances of the key value storage being created and then initialising an entirely separate instance of the `Blockchain` and `WorldStateArchive`. I think we may use some questionable reflection in parts as well which is not ideal. 

I don't have a comprehensive list of the internals I think would be useful to expose, but in general I would advocate for a default approach whereby anything new added internally is accessible via the plugin context in an immutable or read-only form unless there are very real security or technical issues with doing so.

**Comment by siladu** [comment]
Closing this as out of date. Some of this has already been done, and we can do the rest on demand.
