### ISSUE TITLE
Feature request: Signed response to eth_call

### ISSUE THREAD

**Issue by pooja239** [hyperledger/besu#1365]
### Description
Currently, Hyperledger Besu does not have the feature using which we can get signed response from the Besu nodes. Other permissioned network like corda and fabric provides this facility in which we can explicitly request for a signed response from the nodes. Having a signature for response, helps the client to validate that the response has come from a valid node. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** A new API such as eth_Signedcall() which gives the (query response + signature)

**Actual behavior:** New feature

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`] all
* Java version: [`java -version`] all
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`] all
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by MadelineMurray** [comment]
hi @pooja239 - Besu implements TLS to secure communication between the client and the node.  The Besu documentation covers this here - https://besu.hyperledger.org/en/stable/Concepts/TLS/ 

Is there a reason TLS can't be used to ensure the response is received from a valid node?

**Comment by pinges** [comment]
If we were to implement this, this could be a standard that we could use for signing: JSON Web Signature (JWS) (https://tools.ietf.org/html/rfc7515#page-7)

**Comment by pooja239** [comment]
> hi @pooja239 - Besu implements TLS to secure communication between the client and the node. The Besu documentation covers this here - https://besu.hyperledger.org/en/stable/Concepts/TLS/
> 
> Is there a reason TLS can't be used to ensure the response is received from a valid node?

TLS is to provide secured communication between node and client. The node signature would help to validate the response outside the network.

**Comment by pooja239** [comment]
> If we were to implement this, this could be a standard that we could use for signing: JSON Web Signature (JWS) (https://tools.ietf.org/html/rfc7515#page-7)
> Apache 2 implementation from google: https://github.com/google/JWS

**Comment by MadelineMurray** [comment]
@pooja239 - is there a specific use-base or business need you are trying to support?  

Unfortunately this feature is not on the roadmap in the short term, but if you (or anyone else) wanted to contribute an implementation, we'd be happy to help you get started.

**Comment by MadelineMurray** [comment]
Reach out to us on [RocketChat](https://chat.hyperledger.org/channel/besu) if you've got any questions about this issue or would like any help from our engineers to get a PR started.
