### ISSUE TITLE
Pre-deployed contract constructor code not executing correctly

### ISSUE THREAD

**Issue by fmfmartins** [hyperledger/besu#1377]
### Description
I'd like to pre-deploy a smart contract running its constructor code through a custom genesis file.

### Steps to Reproduce (Bug)

Take for instance: 

```
pragma solidity ^0.5.0;

contract Redirect {
    
    address public owner;
    address payable public pool;
    
    constructor () public{
        owner = msg.sender;
         pool = 0x56221D506e1b9F72b7Bf13261C2942A907E169BE;
    }

    event Received(address, uint);
    
    function () external payable {
        pool.transfer(msg.value);
        emit Received(msg.sender, msg.value);
    }
}
```

When I compile that contract through truffle and get its `bytecode` so that I add it to the genesis file 

```json
"0x9100b22bf20BD404798BBAd355208B87D8437932": {
      "balance": "0",
      "comment": "redirect with constructor",
      "code": "0x608060405234801561001057600080fd5b50600080546001600160a01b03199081163317909155600180549091167356221d506e1b9f72b7bf13261c2942a907e169be179055610125806100546000396000f3fe60806040526004361060265760003560e01c806316f0115b14609b5780638da5cb5b1460c9575b6001546040516001600160a01b03909116903480156108fc02916000818181858888f19350505050158015605e573d6000803e3d6000fd5b506040805133815234602082015281517f88a5966d370b9919b20f3e2c13ff65706f196a4e32cc2c12bf57088f88525874929181900390910190a1005b34801560a657600080fd5b5060ad60db565b604080516001600160a01b039092168252519081900360200190f35b34801560d457600080fd5b5060ad60ea565b6001546001600160a01b031681565b6000546001600160a01b03168156fea165627a7a723058209938f95efe5d2aae06b4783f556f4129b0b231ac90ff78c2a98e6279d6b664200029"
}
```

Then interact with it using `truffle console`..

**Expected behavior:** [What you expect to happen]

```node
truffle(development)> let p = await Redirect.at('0x9100b22bf20BD404798BBAd355208B87D8437932')
truffle(development)> await p.pool()
'0x56221D506e1b9F72b7Bf13261C2942A907E169BE'
```

**Actual behavior:** [What actually happens]

```node
truffle(development)> let p = await Redirect.at('0x9100b22bf20BD404798BBAd355208B87D8437932')
truffle(development)> await p.pool()
'0x60003560E01c806316F0115b14609b5780638dA5'
```

### Versions (Add all that apply)

Truffle v5.1.14-nodeLTS.0 (core: 5.1.13)
Solidity - 0.5.7 (solc-js)
Node v12.18.3
Web3.js v1.2.1

### Additional Information

If I deploy the contract through a regular migration, I get the expected result.

Docker-compose:

```yaml
  besu:
    image: hyperledger/besu:latest
    command:
      --data-path=/tmp/tmpDatdir
      --genesis-file="/home/besu/genesis.json"
      --host-allowlist="*"
      --miner-coinbase=0x0000000000000000000000000000000000000000
      --miner-enabled
      --min-gas-price=0
      --revert-reason-enabled
      --rpc-http-api=ETH,NET,WEB3,TRACE,TXPOOL,MINER,DEBUG
      --rpc-http-cors-origins="all"
      --rpc-http-enabled
    ports:
      - 8545:8545
    volumes:
      - ./.docker/besu/genesis.json:/home/besu/genesis.json
```

**Comment by shemnon** [comment]
genesis blocks do not run pre-deployment code, it's not something that can be done well.

One alternative would be to capture the state that resulted from the contract initialization and adding that state as part of the genesis.json.  Our `alloc` statement accepts a `storage` item that is key-value from memory to values.  Here is an example: https://github.com/hyperledger/besu/blob/f64fbad08e66af4d7427bad04bd15df4499200a2/ethereum/evmtool/src/test/benchmarks/evmtool-genesis.json#L74 as well as https://github.com/hyperledger/besu/blob/d6a2394e2d4313f46b47e3ad60566e69ca8e20a4/ethereum/permissioning/src/test/resources/TransactionSmartContractPermissioningControllerTest/preseededSmartPermissioning.json

**Comment by fmfmartins** [comment]
The alternative that you provided seems to have worked.
Thank you.

**Comment by vaigay** [comment]
> genesis blocks do not run pre-deployment code, it's not something that can be done well.
> 
> One alternative would be to capture the state that resulted from the contract initialization and adding that state as part of the genesis.json. Our `alloc` statement accepts a `storage` item that is key-value from memory to values. Here is an example:
> 
> https://github.com/hyperledger/besu/blob/f64fbad08e66af4d7427bad04bd15df4499200a2/ethereum/evmtool/src/test/benchmarks/evmtool-genesis.json#L74
> 
> as well as https://github.com/hyperledger/besu/blob/d6a2394e2d4313f46b47e3ad60566e69ca8e20a4/ethereum/permissioning/src/test/resources/TransactionSmartContractPermissioningControllerTest/preseededSmartPermissioning.json

Can you show me how to get hash key of each key-value in storage? Thank you very much

**Comment by cauta** [comment]
@vaigay how can we compute the hash key? Did you find a way?
