### ISSUE TITLE
Add JSON RPC call to get miner reward and address

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#1408]
### Description

In a conversation with @richardpringle and @sammy1991106, they mentioned it would be useful to them if Besu had a JSON-RPC call that returned information about a certain block's mining reward and coinbase address. If possible, we should probably return additional mining-related data (e.g. the extra-data, difficulty and total difficulty).

**Comment by davemec** [comment]
Endpoint will return the following:
- block reward
- static block reward
- transaction fees
- uncle inclusion reward
- uncle rewards
- coinbase address
- extra-data
- difficulty
- total difficulty

**Comment by timbeiko** [comment]
@richardpringle @sammy1991106 the endpoint is now merged into master. Would love feedback from you on it when you have the time to give it a try 😄

**Comment by richardpringle** [comment]
@sammy1991106 have you had a chance to test this out yet?

**Comment by timbeiko** [comment]
@richardpringle we found some issues calculating the gas refund on mainnet that didn't appear as part of our initial testing on Goerli, so we're reverting the change for now. We should have a fix out in the next couple days!
