### ISSUE TITLE
Support setting difficulty when PoW mining for miners over stratum connections

### ISSUE THREAD

**Issue by muhmad-f-k** [hyperledger/besu#1415]
Hi.
Possibel to add diff when miner connect to stratum. Just at first Connection then get normal diff from the chain.

thank you.

**Comment by atoulme** [comment]
Not sure I understand what you’d like. Do you have a link to a spec or behavior?

**Comment by frode88** [comment]
@atoulme Thank you for fast answer. Well it will make it esay for people who want to rent hashrate and solo mine on their own node. 
So when miner connect to the node so at first connection the diff set to 0. So if you want to mine with NH you will be disconnected. Im not sure if you can use Extranonce to set diff at first connection or something. Thank you again

Pool difficulty too low (provided=0, minimum=0.9)... Error

**Comment by frode88** [comment]
Before first job (work) is provided, pool MUST set difficulty by sending:

{ 
  "id": null, 
  "method": "mining.set_difficulty", 
  "params": [
    0.5
  ]
}\n

First item of params array is difficulty in double data type. Conversion
between difficulty and target is done the same way as with Bitcoin; 
difficulty of 1 is transformed to target being in HEX:
00000000ffff0000000000000000000000000000000000000000000000000000

If pool does not set difficulty before first job, then miner can assume
difficulty 1 was being set.

When difficulty is changed, miner starts using new difficulty for every
NEXT job that arrives

**Comment by atoulme** [comment]
This sounds like something the community should help support, it's kinda hard to test and debug.

For now, I'd recommend you use Besu, add a pool software, and your miner connected to the pool software. eth-proxy, open-ethereum-pool come to mind.

**Comment by frode88** [comment]
@atoulme Set Diff only at first Connection. Just started at school with computer science. We learn to code in java. Gonna play with code and see:) Thank you anyway:)

**Comment by non-fungible-nelson** [comment]
@diega - is this something we should look to support? Or am I OK to close?

**Comment by muhmad-f-k** [comment]
No need anymore.
