### ISSUE TITLE
500 Internal error returned on eth_estimateGas

### ISSUE THREAD

**Issue by jimy74** [hyperledger/besu#1445]
### Description
As a JSON-RPC client of a besu node, I want to run a gas estimation so that I can detect that a transaction that try to to send ether to a non-payable contract (fallback) should fail. This allows me to detect if a smart contract have a payable fallback. 

### Steps to Reproduce (Bug)
1. Sync a node in fast mode with rinkeby, with the config : 
BESU_HOST_WHITELIST="*"
BESU_RPC_HTTP_ENABLED="true"
BESU_RPC_HTTP_API="ADMIN,WEB3,ETH,NET,TRACE"
BESU_RPC_HTTP_CORS_ORIGINS="*"
BESU_SYNC_MODE="FAST"
BESU_NETWORK="rinkeby"
BESU_MIN_GAS_PRICE="1000000000"

2. Have some Ether on the sender address (1 ETH should be more than enough), with the one on example it is already the case.

3. Run the call : 

```
curl --data '{"method":"eth_estimateGas","params":[{"from": "0xdf46E254BB7484A80763767c09E4B42FEDaC07E1", "to": "0x52A7B377A666be31582532E567DF9e253e433A9d", "data": "0x", "gasLimit": 300000, "value": 100}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://<myBesuUrl>:<myBesuPort>
```

**Expected behavior:** [What you expect to happen]

```
curl --data '{"method":"eth_estimateGas","params":[{"from": "0xdf46E254BB7484A80763767c09E4B42FEDaC07E1", "to": "0x52A7B377A666be31582532E567DF9e253e433A9d", "gasLimit": 300000, "value": "0x100"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://<myGethUrl>:<myGethPort>
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted"}}
```
As you can see, the same request on a Geth node returns an understandable error informing that the contract have reverted.

**Actual behavior:**

```
curl --data '{"method":"eth_estimateGas","params":[{"from": "0xdf46E254BB7484A80763767c09E4B42FEDaC07E1", "to": "0x52A7B377A666be31582532E567DF9e253e433A9d", "data": "0x", "gasLimit": 300000, "value": 100}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://<myBesuUrl>:<myBesuPort>
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "error" : {
    "code" : -32603,
    "message" : "Internal error"
  }
}%
```

Same with the value passed in hexadecimal : 
```
curl --data '{"method":"eth_estimateGas","params":[{"from": "0xdf46E254BB7484A80763767c09E4B42FEDaC07E1", "to": "0x52A7B377A666be31582532E567DF9e253e433A9d", "gasLimit": 300000, "value": "0x64"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://<myBesuUrl>:<myBesuPort>
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "error" : {
    "code" : -32603,
    "message" : "Internal error"
  }
}%
```                                                                

**Frequency:** 100% of times we run the json-rpc query it return this Internal Error.

### Versions (Add all that apply)
* Software version: besu/v1.5.5/linux-x86_64/oracle_openjdk-java-11
* Java version: oracle_openjdk-java-11
* OS Name & Version:

* Kernel Version: 5.4.49+
* Docker Version: 19.03.9
* Cloud VM, type, size: GCP Cloud VM: n2-highmem-4
* Operating System: Container-Optimized OS from Google

### Additional Information

I believe the node should reply like geth, at least to say it has an error and it was reverted, without a revert message as I'm in FAST mode anyway and in this case there is no message potentially as it is reverted cause the method is not payable.
Here it fails with a 500 error mean that there is a potential problem in the implementation.

If it's really a bug as it looks like, can someone fix it? Otherwise, can someone tell me what I'm doing wrong?

Rather than that, the erro code -32603 is shared between internsl errors and timeout errors, but here with the additional message it seems to be a internal error, maybe worth a sub ticket for that but it's not my concern here.

**Comment by matkt** [comment]
The bug is fixed. Thank you
The method will return `Execution reverted` instead of an internal error
