### ISSUE TITLE
evmtool: --version does not work

### ISSUE THREAD

**Issue by MariusVanDerWijden** [hyperledger/besu#1471]
### Description
I want to get the version of the evmtool by providing the `--version` flag

### Acceptance Criteria
* `-V` and `--version` returns the current version of the evmtool (or the current commit)

### Steps to Reproduce (Bug)
`~/ethereum/besu/ethereum/evmtool/build/install/evmtool/bin/evm -V`
`~/ethereum/besu/ethereum/evmtool/build/install/evmtool/bin/evm -version`

**Expected behavior:** 
Output version

**Actual behavior:** 
Does nothing

### Versions (Add all that apply)
* Software version: current master

**Comment by timbeiko** [comment]
Thanks for flagging! We should also check if other subcommands have the same issue.

**Comment by shemnon** [comment]
Fix will be in docker develop shortly, will be part of 20.10.1 next week.

```
dannos-mbp:besu dannoferrin$ build/install/besu/bin/evm state-test -V
Hyperledger Besu EvmTool
besu/v20.10.1-dev-4ff73342/osx-x86_64/oracle_openjdk-java-14
```
