### ISSUE TITLE
Eliminate Thread Waste in MarkSweepPruner

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#1489]
Instead of `join`ing on the mark tasks to be created. The code should be transformed to be non-blocking. Any exceptions that are propagates through `CompletableFuture`s can be handled in `Pruner.java` where we currently catch exceptions and log.

**Comment by non-fungible-nelson** [comment]
Closing for bonsai defaults. Can re-open dependent upon forest use-cases
