### ISSUE TITLE
1.4.6 and 1.5.0 ForkId Incompatibility

### ISSUE THREAD

**Issue by jorgesanjose** [hyperledger/besu#1533]
I have a network with 2 peers with different versions, 1.4.6 one and 1.5.0 the other.
A fix for private network forkIds was introduced between 1.4.5 and 1.5.0 which made them incompatible with one another.

```sh

2020-11-04 15:56:15.385+01:00 | nioEventLoopGroup-3-1 | DEBUG | EthProtocolManager | Disconnecting from peer with matching network id (2018), but non-matching fork id: ForkId(hash=0x925b4351, next=0)
```
```sh
11-04 15:56:15.385+01:00 | nioEventLoopGroup-3-1 | DEBUG | AbstractPeerConnection | Disconnecting (0x10 SUBPROTOCOL_TRIGGERED) from PeerInfo{version=5, clientId='besu/v1.5.0/linux-x86_64/oracle-java-15', capabilities=[eth/62, eth/63, eth/64, IBF/1], port=30303, nodeId=0x2594301886259d7b58a56d00ec91aa426d19b14b27ad913b3038b8f308ae7f911ca4c41a8fc0ea23e935a6ff1f73c4a1c6311247ef51fa69dd6bc9881cab1126}
```
![Node-2_2](https://user-images.githubusercontent.com/47521746/98134163-c2750300-1ebe-11eb-8529-43d493980dd0.png)
![Node-1](https://user-images.githubusercontent.com/47521746/98134172-c3a63000-1ebe-11eb-9aa2-acd91af0e05f.png)
![Node-1_2](https://user-images.githubusercontent.com/47521746/98134175-c43ec680-1ebe-11eb-9b09-8926e350ad6c.png)
![Node-1_3](https://user-images.githubusercontent.com/47521746/98134176-c43ec680-1ebe-11eb-8177-5db04cc67de8.png)
![Node-1_4](https://user-images.githubusercontent.com/47521746/98134179-c4d75d00-1ebe-11eb-98d3-77dec01d587a.png)
![Node-2_1](https://user-images.githubusercontent.com/47521746/98134180-c4d75d00-1ebe-11eb-8586-f070a1a80764.png)
![Node-2_3](https://user-images.githubusercontent.com/47521746/98134181-c56ff380-1ebe-11eb-896b-b1d45dabd0ad.png)

**Comment by timbeiko** [comment]
This seems related to https://github.com/hyperledger/besu/issues/1534

**Comment by JaimeGomezGarcia** [comment]
Yes, #1534 was reported by a consortium colleague on rocketchat, but it is the same issue as this one.
We have also tested this on an internal network.

**Comment by timbeiko** [comment]
@jorgesanjose @JaimeGomezGarcia this should be fixed by https://github.com/hyperledger/besu/issues/1541, which will be part of today's 20.10.1 release. Please reopen if you still see issues. Thank you!
