### ISSUE TITLE
"blockHash" parameter for the filter used by "eth_newFilter" should be camel cased

### ISSUE THREAD

**Issue by ilkecan** [hyperledger/besu#1540]
Currently, Besu expects "blockhash" (lower cased) as a parameter but it should be "blockHash" (camel cased) to be [EIP-234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md) complaint. 
https://github.com/hyperledger/besu/blob/67191aac76533b8dce73aeda10100bb250f56601/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/FilterParameter.java#L52

For example, this request returns `400 Bad Request` with message "Invalid params":
```
{
  "method": "eth_getLogs",
  "params": [{
    "blockHash": "0x7844f51cd4899fbea6b31373f11a30de2bb99d2df59c2b774684f2e04455b839",
    "address": "0xd7ede5868287411d3e197719dd5f98b74871b3fd",
    "topics":["0x8cbec4f9f4b9f9a2a9f96d2f1ba00d16b99b8c0962c1396768bb32b5eddd8e73"]
  }],
  "id":48,
  "jsonrpc":"2.0"
}
```
And the same request with the "blockHash" replaced with "blockhash" returns `200 OK`.

```
besu --version
besu/v20.10.0/linux-x86_64/oracle_openjdk-java-11
```

**Comment by macfarla** [comment]
Forthcoming release of jackson 2.12 will enable setting of "case insensitive" on the property which would make this a one line change

See https://github.com/FasterXML/jackson-databind/issues/1886

RC was released yesterday https://github.com/FasterXML/jackson-databind/releases/tag/jackson-databind-2.12.0-rc2

**Comment by macfarla** [comment]
Moving to blocked and hoping that Jackson 2.12 fixes the problem soon

**Comment by macfarla** [comment]
This annotation is not going to be supported at property level (only class level). So need to solve another way.

**Comment by macfarla** [comment]
`@JsonAlias` is what I've been looking for!
