### ISSUE TITLE
Incorrect Gas price

### ISSUE THREAD

**Issue by wetryingtodorock** [hyperledger/besu#1546]
### Description

We use the Besu node, and during the process we understood that the gas price is calculated wrongly.
The OpenEthereum’s value is changing from block to block, but for Besu it is the same.
Method that we use: `eth_gasPrice`
Can you please check, if everything works correct?

Request:
```
{
    "id": "blockNumber",
    "jsonrpc": "2.0",
    "method": "eth_gasPrice",
    "params": []
}
```
Response(OpenEthereum):
```
Response:
{
    "jsonrpc": "2.0",
    "result": "0xcce416600",
    "id": "blockNumber"
}
```
Response(Besu):
```
Response
{
    "jsonrpc": "2.0",
    "id": "blockNumber",
    "result": "0x3e8"
}

```

**Comment by timbeiko** [comment]
@wetryingtodorock thanks for raising this! Indeed, [the JSON RPC spec](https://eth.wiki/json-rpc/API#eth_gasPrice) is quite vague about this call: 
> Returns the current price per gas in wei.

We currently interpret that as returning the minimum gas price allowed on the network (set by the [`min-gas-price` flag](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#min-gas-price)). It seems that OE and Geth use the median/average gas price over a range of previous blocks, which produces some ok but not great estimates 
(see[ this Geth issue](https://github.com/ethereum/go-ethereum/issues/15825), for example). 

Is this what you would like to see from the endpoint? If you have any specific requirements, we'd love to hear them and are open to adapting the endpoint.

**Comment by wetryingtodorock** [comment]
@timbeiko  thanks for the answer!
Probably OpenEthereum and Geth do not always effectively make an estimate, but some of our users expect exactly the same response when calling a method, as in the OpenEthereum client.
Since we are considering Besu as an alternative to OpenEthereum and Geth for our users, we would be happy to expect this in future Besu releases.

**Comment by shemnon** [comment]
The best documentation I've found on what OE does is this comment - https://github.com/openethereum/parity-ethereum/issues/1265#issue-159997710

**Comment by shemnon** [comment]
In the event of zero transactions in the last 100 blocks we should fall back to our current behavior (return the CLI set value)

**Comment by sammy1991106** [comment]
Would love to see Hyperledger does exactly what Geth and OpenEthereum do too. Extra config parameters specifying the X-percentile of the last Y blocks would be nice.

**Comment by shemnon** [comment]
@sammy1991106 should the defaults be OE values (100 blocks, 50%), or Geth's documented defualts (20 blocks, 60%)?

**Comment by sammy1991106** [comment]
@shemnon Personally, I'd prefer the default to be 100 blocks and 50% if pulling 100 blocks of data wouldn't affect the performance (basically the more blocks are considered the better?). Another thing to note is that on chains such as Ethereum Classic, a lot of blocks are empty. So maybe it would make sense to only consider the last X blocks that actually have some transactions in there?

**Comment by timbeiko** [comment]
I think 100 and 50% make sense as defaults FWIW. A lot of people are coming from OE, so keeping the same ones will result in similar behaviour which is nice. These estimates are not as reliable as 3rd party estimates, so their use is somewhat limited anyways. 

Agreed that empty blocks should be part of the calculation and if the last 100 blocks are empty, then reverting to the minimum makes sense.

**Comment by shemnon** [comment]
If there are a lot of empty blocks I don't think transaction inclusion will be a big issue.  

The downside of too much of a windows is (a) performance and (b) it hides local spikes.  I think 100 blocks (~20 minutes) is about as far back as one would want to go for an on-chain oracle.  Like Tim said 3rd parties are the best because they take into consideration the entire mempool.

**Comment by timbeiko** [comment]
@wetryingtodorock this should be fixed by @shemnon's PR above. We'll be releasing a new version of Besu today which will contain the new behaviour. I'll close this issue for now, but please reopen if needed. Thanks again for flagging this!
