### ISSUE TITLE
Error "Invalid Request" when Performing JSON-RPC Batching Over WebSocket

### ISSUE THREAD

**Issue by sammy1991106** [hyperledger/besu#1564]
### Description
JSON-RPC batching over WebSocket doesn't work as over HTTP currently. Debugging with `wscat`, the following is what I get.

```
> {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}
< {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x3290dd"}
> [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}] 
< {"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid Request"}}
```

However, the same JSON-RPC batching request works perfectly fine over HTTP.

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. `wscat -c ws://<JSON-RPC-ws-endpoint:port>`
2. `[{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}]`

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: 1.5.5
* Java version: 11
* OS Name & Version: openjdk:11-jre-slim-buster
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by macfarla** [comment]
tested using wscat

```
wscat -c ws://localhost:8546
Connected (press CTRL+C to quit)
>
< {"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid Request"}}
> {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}
< {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x23"}
> [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}, {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"admin_peers","params":[]}]
< [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x23"},{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":[]}]
>  [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}, {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"admin_sdfpeers","params":[]}]
< [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x23"},{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","error":{"code":-32601,"message":"Method not found"}}]
```

**Comment by macfarla** [comment]
Re docs - I couldn't find any docs for batching of requests for HTTP either. So maybe we need to add something about this for HTTP and Websockets.

**Comment by sammy1991106** [comment]
@macfarla I just tried `v20.10.1` and am still getting the same error as I reported. My configuration of the node is

**Comment by macfarla** [comment]
Hi @sammy1991106 This change didn't quite make it into 20.10.1. You can test with latest master, or wait for 20.10.2 :)

**Comment by sammy1991106** [comment]
@macfarla I can confirm the issue no longer exists in 20.10.2. Feel free to close this and thanks for fixing it. :)
