### ISSUE TITLE
Feature Request: add total difficulty and other "current" peer info to `admin_peers` RPC

### ISSUE THREAD

**Issue by ryanschneider** [hyperledger/besu#1580]
### Description

As an operator of a `besu` node, I want to see what block my peers are synced to so that I know that I'm connected to quality peers (and am receiving the blocks correctly).

I think it would be useful for the `admin_peers` RPC to return some "current" state of peers in addition to the "static" state of peers.

For example, in `geth`, each peer entry returned by `admin_peers` also includes a `protocols` section which includes data about the current `eth`:

```
[
  ...,
  {
     ...
     protocols: {
      eth: {
        difficulty: 1.8776698526694168e+22,
        head: "0x1dadd5a337feec81c4c73af022df4825191aaa23037d3f2d25bbc3a80c44c956",
        version: 65
      }
    }
  }
]
```

This data can be used to:

- Determine the "quality" of ones peers.  For example an external process could use this data in conjunction with `admin_removePeer` to disconnect from peers that appear "stalled" at a single difficulty for an extended period of time.
- Help diagnose that _my_ client is operating correctly.  For example, if my peers continue to report increasing difficulties but my local node seems stuck at the same block number this may indicate an issue with block propagation or that my node is on a different fork than most of my peers.

I know the `admin` namespace is not standardized in any real way, so fully understand `besu` not including this data, and I'm of course open to this data being returned via a different RPC or a slightly different version than `geth` or other nodes (for example, I'd actually _prefer_ if `besu` returned the total difficulty as a hex string rather than a JSON number).

The tricky part, IMO, is that `admin_peers` currently returns an array of `PeerInfo` data defined here: https://github.com/hyperledger/besu/blob/ccefada736850eee6db58d1503f079482ff254a0/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/PeerInfo.java#L38

I'm not familiar enough with the code to know if there's another data source that includes data like the peer's current total difficulty, if that data is available it would need to be folded into the `List<PeerResult>` response generated here:  https://github.com/hyperledger/besu/blob/ccefada736850eee6db58d1503f079482ff254a0/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminPeers.java#L46

### Acceptance Criteria

In my opinion any RPC that allowed one to view the state of peers would be acceptable.

### Steps to Reproduce (Bug)
1. Issue an `admin_peers` RPC to a `besu` node
2.Note that each peer entry does not include "current" data about the peer such as the eth/65 total difficulty.

**Expected behavior:** [What you expect to happen]

Either add the `protocol` data to `admin_peers` or provide another means to inspect the current state of `besu` peers.

**Actual behavior:** [What actually happens]

Currently there's no way to query the state of `besu` peers.

**Frequency:** [What percentage of the time does it occur?]

Always

### Versions (Add all that apply)

Current master, though I suspect all previous versions as well.

**Comment by shemnon** [comment]
Here's a sample peer from the new endpoint:
```
        {
            "version": "0x5",
            "name": "Geth/v1.9.24-stable-cc05b050/linux-amd64/go1.15.5",
            "caps": [
                "eth/63",
                "eth/64",
                "eth/65"
            ],
            "network": {
                "localAddress": "10.0.2.18:46958",
                "remoteAddress": "116.255.13.69:30303"
            },
            "port": "0x0",
            "id": "0x465719d28b6defe69eb5e3d16d4786788fdb13bbf9630692e51aeb6baac39d85829ed62b7d2510f19949631b1b9596a4c13a2740c4eeeb374620e4db6eecf976",
            "protocols": {
                "eth": {
                    "difficulty": "0x403d1d5ac261b926509",
                    "head": "0xcdc4fd3720fe60ba4a7235bc4a0d72f9d411a58d4b0a7d7efebce251780cd83c",
                    "version": 64
                }
            }
        },
```

The new section is "protocols"is a map where "eth" is the only expected entry.  The three parameters are self reported by the peer.  
* "difficulty" is the reported total difficulty of the peer (the sum of each difficulty field of all prior blocks).  Ours is in hex so we don't lose data like Geth's float version.  
* "head" is the hash of the head that peer is using, 
* "version" is the version of the protocol we are communicating with for the peer (may not be the highest level).  In theory the map key plus this version "{key}/{version}" should be a member of the "caps" array.

This is new in 20.10.2.

**Comment by ryanschneider** [comment]
Awesome thanks @shemnon this is perfect!  I would definitely consider this feature request completed.  I'll let you all close the issue though since not sure what your process is and don't want to interfere.

**Comment by shemnon** [comment]
We have it open to update the docs.  We have some sample RPCs that will need an update.

**Comment by MadelineMurray** [comment]
Raised https://github.com/hyperledger/besu-docs/issues/562 to doc.

**Comment by shemnon** [comment]
With that doc issue I'll close this out.
