### ISSUE TITLE
Add support for GraalVM AOT

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#1587]
In order to get more efficient compilation on Besu, we should add support for GraalVM AOT. 

When doing so, we should:
1. Make sure all the native libraries work. To do so, we may need to move besu-native to SWIG imports instead of JNA. 
1. Make sure all the needed annotations are pre-queried. Lots of picocli and jackson annotations that need to be reflected at runtime.
1. Wire GraalVM into the build.

This would also help with hive test execution, see: https://github.com/ethereum/hive/pull/404

**Comment by shemnon** [comment]
We will want a step zero de-risking - make sure all third party libraries native integrations will work.  JNA and JNR are known issues.
