### ISSUE TITLE
Remove ellipsis from block hash logs

### ISSUE THREAD

**Issue by atoulme** [hyperledger/besu#1594]
### Description
As an operator, I want full block hashes so that I can grep for them in logs and display them in Splunk dashboards. 

### Steps to Reproduce (Bug)
1. Run a sync
2. Grep for FullImportBlockStep
3. See that log lines look like "Import reached block 3787200 (0xa147..ad3d), 29.996 Mg/s, Peers: 25"

**Expected behavior:**
Should see full block hash in parens

**Actual behavior:**
Only see the beginning and end of the hash, making it useless to match block hashes.

### Versions (Add all that apply)
* Software version: 20.10.1

**Comment by BogdanStirbat** [comment]
Hi!

I've added a pull request, https://github.com/hyperledger/besu/pull/2105 .
