### ISSUE TITLE
besu.bat have missing "

### ISSUE THREAD

**Issue by cheul123a** [hyperledger/besu#1606]
https://dl.bintray.com/hyperledger-org/besu-repo/besu-20.10.1.zip
i downloaded besu from above link.

there is missing " on besu.bat so i coulden't execute.

```
@rem Execute besu
if Defined TRACING (TRACING_AGENT="-javaagent:" %APP_HOME%\agent\opentelemetry-javaagent-0.8.0-all.jar")
```
should be
```
@rem Execute besu
if Defined TRACING (TRACING_AGENT="-javaagent:" "%APP_HOME%\agent\opentelemetry-javaagent-0.8.0-all.jar")
```

**Comment by atoulme** [comment]
Thank you for your bug report. I am looking into this.
