### ISSUE TITLE
besu is failing stPrecompile tests on Berlin

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#1611]
Besu develop is different to geth develop
![Screenshot_20201125-140905](https://user-images.githubusercontent.com/4492341/100232550-c8438e80-2f28-11eb-89bf-aa4c5962a6a0.png)

**Comment by shemnon** [comment]
Besu has integrated EIP-2565 for the modExp repricing,  Were these tests run agains the original gas calculations?

**Comment by winsvega** [comment]
Hmm, looks like it does. Let me double check.
https://github.com/ethereum/go-ethereum/pull/21607

**Comment by winsvega** [comment]
The change comes together with other eips (2718/2930) in geth. And it cannot be activated separately. Therefore the test was generated without this eip.

Looks like the besu client is right.
