### ISSUE TITLE
benchmarking besu - optimal hardware specs

### ISSUE THREAD

**Issue by AndreiD** [hyperledger/besu#1627]
Greetings,

We've run some benchmarks for besu (besu/v20.10.1/linux-x86_64/openjdk-java-11)  on the following hardware:

4 nodes (each one a separate VM), ubuntu 18.04, 2 seconds block interval, ~infinite gas limit, IBFT2.0

4 x 32 core CPU (CPU optimized VM), 256GB, NVME SSD 7500 to 15000 IOPS, 3Gbps internal network, accelerated networking on
and
4 x   4 core core CPU(CPU optimized VM) , 64GB, P50 - 7500 IOPS, 250 Mbps, 3Gbps internal network, accelerated networking off

and the results are similar, about 1900 TPS, while the hardware difference is huge

Theoretically  TPS = (GAS Limit ) / (TxGas * BlockTime)

so we were wondering what is the limiting factor and how we can optimise our tests to get more TPS

is there a testing procedure that we can follow to get accurate benchmarking results ?

**Comment by shemnon** [comment]
Transaction processing is still single threaded.  Each TX can be influenced entirely by each previous tx.  There are internal discussions on how to parallelize that step but haven't been implemented yet.

**Comment by shemnon** [comment]
also, is your test harness public?

**Comment by AndreiD** [comment]
thanks for the response. what do you mean by test harness ?

**Comment by shemnon** [comment]
The code you are running to (a) set up the System Under Test (the nodes) if automated, and (b) the code that runs the transactions and loads them into the sytem.  and possibly (c) gathers the stats and reports for the test.

**Comment by AndreiD** [comment]
I'll have to ask if I can show the code but, in short I do the following:

- install manually binary in 4 VMs following your tutorial
- transfer the ETH to 10k accounts by a simple script
- from as many RPC nodes as possible (I think I tested with 4 separate VMs) I transfer eth between the accounts.
this is not optimized like, auto incrementing the nonce, it's just how you would do it in a real program. I'm thinking for it to be more "real" I should send just the signed transactions.... maybe I'll do that in the next version of the test program.
- I look in the blockchain explorer how many blocks were included

The idea is to have as many RPC nodes as possible, because if you ...try too hard.. you would get some TCP errrors address not found. So some auto devops tool like terraform, ansible, chef etc. should be used to create the VMs and destroy them after.... but I didn't reach that part yet.
