### ISSUE TITLE
Add DNS Discovery as a CLI Flag

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#1631]
### Description
As a node operator, I want to be able to set the DNS Discovery URL via CLI so that I can use DNS Discovery URLs for networks other than the pre-configured named mainnet networks. 

### Acceptance Criteria
* DNS discovery URL is set via command line flag, such as `--discovery-dns` and the node uses it.  For a stand alone test a manually configured testnet should be used instead of the `--network` flag and DNS discovery URL is echoed in the info log

**Comment by RichardH92** [comment]
Hi @shemnon , is anyone working on this issue? If not, I can take a stab at it. Thanks!

**Comment by timbeiko** [comment]
@RichardH92 go ahead - I'll assign the issue to you 😄

**Comment by RatanRSur** [comment]
@RichardH92 Hey Richard! How are you doing on this?

**Comment by RichardH92** [comment]
@RatanRSur Hey! Sorry, I haven't made much progress on this to be frank. I would like to contribute to besu, but unfortunately haven't had much time lately. If this is a pressing issue, plz feel free to reassign to someone else.
