### ISSUE TITLE
Add option to configure discovery in genesis json

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#1632]
### Description
As an administrator, I want to be able add bootnodes and dns discovery to the config json files so that all critical chain information can be setup in one file.

Currently if you have a custom network with custom bootnodes or DNS discovery you need to add that information to the CLI or the config.toml that proxies the CLI.  This feature would move that into the shared json file so that only node specific information (such as RPC ports) must be configured via CLI.  The cli flags should continue to work as well. 

### Acceptance Criteria
The new json section should look something like this, or highly similar

```
{
  "config": {
    // ...
    "discovery" : {
      "bootnodes": [
        "enode://...@0.1.2.3:4567",
        "enode://...@0.1.2.9:8765"
      ],
      "dns": "enrtree://ABASETHIRTYTWOSTRING@besu.your.corp.net"
    },
    // ...
  },
  // ...
}
```

`bootnodes` and `dns` are both optional, which means we may have an empty `discovery` object, which should not produce any errors even if it looks weird.  But if they put anything other than an object in the `discovery` field, such as a string, errors are fine.

**Comment by atoulme** [comment]
An important discussion point here is that the EthProtocolManager checks the hash of the genesis file when performing a status exchange, and will disconnect if the genesis hashes don't match (https://github.com/hyperledger/besu/blob/master/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java#L332) 

In effect, it makes it impossible to amend the genesis file after the fact, especially if you need to fix the DNS entry or the bootnodes list.

Does it make sense in that case to move this type of config inside genesis? Is there a way to be smart about this?

**Comment by shemnon** [comment]
That's the hash of the genesis block.  Which only includes _some_ of the data in the genesis.json file.  None of it is discovery focused.  Basically only stuff that would go into a block header contributes to that hash.  Everything in the `"config"` block is not part of the genesis hash, otherwise we would never be able to hard-fork.

**Comment by atoulme** [comment]
D'oh, you're right of course. Would you have CLI and config file take precedence on the genesis configuration?

**Comment by shemnon** [comment]
yes.  There is precedent for that as "--override-genesis-config" can override fork block ids.  CLI is an escape hatch for defaults that need to be overridden, like say if a fork is cancelled on short notice or a discovery DNS goes offline.
