### ISSUE TITLE
awaitPeerCount failure in shouldNotAddValidatorWhenInsufficientVotes - org.hyperledger.besu.tests.acceptance.clique.CliqueProposeRpcAcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#1646]
This test has failed twice this week
`shouldNotAddValidatorWhenInsufficientVotes - org.hyperledger.besu.tests.acceptance.clique.CliqueProposeRpcAcceptanceTest`
https://app.circleci.com/pipelines/github/hyperledger/besu/6310/workflows/58cd086d-c65e-4a5f-96c0-15372fd3581c/jobs/30505
And again:
https://app.circleci.com/pipelines/github/hyperledger/besu/6350/workflows/eedef371-6a79-4c26-af8b-f648e7deb57b/jobs/30753

**Comment by rain-on** [comment]
few thoughts:
1. ProcessBesuNodeRunner:418 should probalby have a return inside the conditional
2. ProcessBesuNodeRunner:425 - probably add the ProcId to the kill-request
3. Use a custom fork-join pool (with a thread per node) for the parallel-stream when starting nodes - and put a log line RIGHT at the top of each ‘start node’ lambda
4. When we decide we do (or don’t) have enough peers when starting up - dump the peer list (via the Json Peers API) from each node - so we know who the node THINKS its connected to

**Comment by macfarla** [comment]
@rain-on I did 1 and 2. Re 4 -not sure it's straightforward to dump the peer list because awaitPeerCount is an assert. Re 3 - the bootnode gets started first, separately, so that would explain why the pid for miner1 was lower.
