### ISSUE TITLE
Besu java profiling

### ISSUE THREAD

**Issue by cyrilnavessamuel** [hyperledger/besu#1650]
My Question is a general query:

Hello All, Please would like to know for hyperledger besu , how can I use java profiling with the binary. 

I referred to the documents @ https://besu.hyperledger.org/en/stable/HowTo/Troubleshoot/Java-Flight-Recording/, 
please can you explain the steps. I tried to add the options but I get error like below

![image](https://user-images.githubusercontent.com/8938494/100860089-58855480-3490-11eb-8a6b-320559a50cea.png)

**Comment by timbeiko** [comment]
Hey @cyrilnavessamuel, 

It seems our docs are not fully up to date about this, sorry!

You need to set profiling via environment variables, e.g.:

```
export BESU_OPTS=-XX:StartFlightRecording=disk=true,delay=15s,dumponexit=true, \
filename=/tmp/recording.jfr, maxsize=1024m,maxage=1d, \
settings=profile,path-to-gc-roots=true
```

This is assuming you are running it from a shell script. Somehow BESU_OPTS needs to be set to the jfr flags. Docker compose has one way, systemctl has a different way.

**Comment by cyrilnavessamuel** [comment]
Thanks Tim, It works fine
