### ISSUE TITLE
Cannot create private network following tutorial in documentation

### ISSUE THREAD

**Issue by ifs-medardegue** [hyperledger/besu#1663]
### Description
As a Developer, I want to create private network with Clique consensus on Mac OS Catalina v10.15.7 

### Acceptance Criteria
* After creating the first signer node, all my other nodes can start successfully and are connected

### Steps to Reproduce (Bug)
1. Install latest Besu binary distribution using brew [as described in online documentation](https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Installation-Options/Install-Binaries/)
2. Follow Tutorial available on [Hyperledger Besu documentation](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-Private-Clique-Network/)
3. On step 5 of the tutorial, run the command to start Node-2

**Expected behavior:** Node-2 should start when specifying different rpc http port with  --rpc-http-port=8546

**Actual behavior:** I get the following error: "Port number '8546' has been specified multiple times. Please review the supplied configuration."

**Frequency:** Always

### Versions (Add all that apply)
* Software version: 20.10.2
* Java version: openjdk version "11.0.9.1" 2020-11-04
* OS Name & Version: MacOS Cataline 10.15.7
* Kernel Version: Darwin Kernel Version 19.6.0

### Additional Information

I removed the --rpc-http-port option to confirm that Node-2 could still not start because Node-1 already use the default node and the error message was different. So it's not an issue related to already used port.

**Comment by AndreiD** [comment]
there's a small bug in the tutorial. actually there's a combination of 2 bugs.
the port 8546 is the default port for websocket on eth. but even if you don't specify it, besu seems to use it.

in any case, on the node2, 3,4 just use something like 8556,8557,8558 when you specify the ports.

**Comment by macfarla** [comment]
Thanks for this @ifs-medardegue ! The changes you've got will fix the tutorial (and it makes sense to avoid the WebSockets default port in the tutorial). I've also created #1665 because besu should still start with that configuration.

**Comment by ifs-medardegue** [comment]
Thank you @AndreiD it's fixed.
