### ISSUE TITLE
RPC HTTP unable to use port 8546

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#1665]
besu --network=dev --rpc-http-enabled --rpc-http-port=8546

### Acceptance Criteria
* RPC HTTP should be able to use WS default port if not in use - maybe just with a warning message indicating we don't recommend using the WS port for HTTP

### Steps to Reproduce (Bug)
1. `besu --network=dev --rpc-http-enabled --rpc-http-port=8546`

**Expected behavior:** expect Besu to start with WebSockets disabled and HTTP RPC running on port 8546

**Actual behavior:** 
2020-12-04 09:07:18,414 main INFO Registered Log4j as the java.util.logging.LogManager.
2020-12-04 09:07:19.182+10:00 | main | INFO  | AbstractAltBnPrecompiledContract | Using LibEthPairings native alt bn128
2020-12-04 09:07:19.691+10:00 | main | INFO  | SECP256K1 | Using native secp256k1
2020-12-04 09:07:19.694+10:00 | main | INFO  | Besu | Starting Besu version: besu/v20.10.3-dev-1fa032d2/osx-x86_64/oracle_openjdk-java-14
Port number '8546' has been specified multiple times. Please review the supplied configuration.

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
Same behavior with both:
openjdk 11.0.2 2019-01-15
openjdk 14 2020-03-17

**Comment by MadelineMurray** [comment]
@timbeiko - have raised the priority of this because we've had 3 users hit this over the last couple of days.

**Comment by victorwiebe** [comment]
Please provide fix, this is effecting me as new user. Thanks

**Comment by MadelineMurray** [comment]
@victorwiebe - See fix provided in hyperledger/besu#1665 which is now into Besu master.
Building from source using the master branch or using the latest Docker image docker pull hyperledger/besu:develop will provide the fixed version until the next release.
