### ISSUE TITLE
TX was submitted but not mined/validated on besu IBFT2 network

### ISSUE THREAD

**Issue by emclab** [hyperledger/besu#1670]
### Description
TX submitted to IBFT2 network stays in tx pool and was not mined/validated.

### Acceptance Criteria
* [Criteria 1]
A TX shall be mined into block

### Steps to Reproduce (Bug)
1. [Step 1]. Install `ethersjs` 5.0
2. [Step 2]. submit tx for contract deploy
3. [Step ...]. Check blockNumber and tx pool

**Expected behavior:** [What you expect to happen]
A TX shall be mined into block
**Actual behavior:** [What actually happens]
A tx for contract deployment was not mined into block.

**Frequency:** [What percentage of the time does it occur?]
never mined so far.

### Versions (Add all that apply)
* Software version: [`besu --version`]: 20.10.2/1.5.0
* Java version: [`java -version`]: 15
* OS Name & Version: [`cat /etc/*release`]: ubuntu 20.04 for Besu node. Win10 for dapp
* dapp: React Native 0.63.2
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Additional Information
The besu IBFT2 network is running with 4 nodes: here is the genesis.json:

     {
    "config": {
      "chainId": 1981,
      "muirglacierblock": 0,
      "ibft2": {
        "blockperiodseconds": 2,
        "epochlength": 30000,
        "requesttimeoutseconds": 4
      }
    },
    "nonce": "0x0",
    "timestamp": "0x58ee40ba",
    "extraData": "0xf83ea00000000000000000000000000000000000000000000000000000000000000000d594c2ab482b506de56>
    "gasLimit": "0x1fffffffffffff",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "contractSizeLimit":2147483647,
    "alloc": {}
     }

Here is the `config.toml` for bootnode:

    # Valid TOML config file
    data-path="./data" # Path

    # Network
    bootnodes=    ["enode://923f4bb2cc2e456ebe88afb5f2d8c6a84d5758b99840fc34d2fcf9df7e3a1204fed83524a50cf37533bee9a058@127.0.0.1:30303",
        "enode://0fdbb968c6082e5fb0de13cd8379961d5be7b24d4ff7f4eb378c738ca4cff4f13f3fb021883848fd783de1b592a101382c048@127.0.0.1:30304",
        "enode://534825b93db8b4220204d3c11ca5570373e2af0b4cf2a4c392b6e4ffdfc8e6185e2d20b9832998c7ce63e8c6ffaa7662f8c18@127.0.0.1:30305,
        "enode://2741de7be2482ceb7d11a2c140d64bf8b448445718e74b556585d42d8554958ea97a868ff0c77d9b15fe30d7fa691c69a89    38@127.0.0.1:30306]

    p2p-port=30303
    max-peers=42

    rpc-http-host=["0.0.0.0"]
    rpc-http-port=8545
    rpc-http-enabled=true
    rpc-http-api=["ETH", "NET","WEB3","ADMIN","TXPOOL","IBFT", "EEA","DEBUG"]

    rpc-ws-host=["0.0.0.0"]
    rpc-ws-port=8546
    rpc-ws-enabled=true

    #Metrics for monitoring
    metrics-port=9545
    metrics-push-port=9001  

    min-gas-price=0

    logging="DEBUG"

    #allow all
    host-allowlist=["*"]
    rpc-http-cors-origins=["*"]

    # Chain
    genesis-file="./genesis.json" # Path to the custom genesis file
    node-private-key-file="./key"

    # Mining
    miner-enabled=false
    miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

Here is output of besu API method on boot/RPC node:

    1. $ curl -X POST --data '{"jsonrpc":"2.0","method":txpool_besuTransactions","params":[], "id":1}' http://127.0.0.1:8545
    {
      "jsonrpc" : "2.0",
      "id" : 1,
      "result" : [ {
       "hash" : "0x7841f5a1da323acb5ea6c6d8d3f9de68445a3b2e55a75c225789c9102a2ea1b6",
      "isReceivedFromLocalSource" : true,
       "addedToPoolAt" : "2020-12-06T04:18:57.499299941Z"
      } ]
    }

    2. $curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount",      "params":[], "id":1}'   http://127.0.0.1:8545
    {
      "jsonrpc" : "2.0",
      "id" : 1,
      "result" : "0x3"
    }

    3. $  curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber", "params":[], "id":1}' http://127.0.0.1:8545
       {
         "jsonrpc" : "2.0",
         "id" : 1,
         "result" : "0x0"
       }

**Comment by rain-on** [comment]
Hey @emclab,
Just saw this - and my first thought is that the extradata in the genesis file looks a little off - i.e. I _think_ it might contain a single validator? Not sure.
Can you confirm the addresses of your validators - and then also confirm that your validators are peered.

You can check your validator list using https://besu.hyperledger.org/en/stable/Reference/API-Methods/#ibft_getvalidatorsbyblocknumber

Then the list of peers for each node can be found using https://besu.hyperledger.org/en/stable/Reference/API-Methods/#admin_peers

My gut feel is that the address(es) of your validators in the genesis file aren't aligned with the node-keys of your nodes.
If you look at your validator's log file - you should see some information regarding blocks getting mined - if not, then its definitely a validator communication problem.

**Comment by rain-on** [comment]
Ignore the extradata comment - just realised the line got truncated, sorry!

**Comment by emclab** [comment]
@rain-on, here is the return of `curl`

      $curl -X POST --data '{"jsonrpc":"2.0","method":"ibft_getValidatorsByBlockNumber","params":["latest"], "id":1}'     http://127.0.0.1:8545
      {
        "jsonrpc" : "2.0",
        "id" : 1,
        "result" : [ "0xc2ab482b506de561668e07f04547232a72897daf" ]
       }

Shall we see 3 validators listed?

**Comment by emclab** [comment]
Here is the `config.toml` for all 4 nodes (sorry the format is off. The long string may be truncated):

      Node1
       
      # Valid TOML config file
data-path="./data" # Path

# Network
#bootnodes=["enode://923f4bb2cc2e456ebe88afb5f2d8c6a84d5758b99840fc34d2fcf9df7e3a1204fed83524a50cf37533bee9a055d916c1634932a7f7129a10b0e43e>
#"enode://0fdbb968c6082e5fb0de13cd8379961d5be7b24d4ff7f4eb378c738ca4cff4f13f3fb021883848fd783de1b592a101382c0401663a7c90313493a13da6a7b9c0@>
#"enode://534825b93db8b4220204d3c11ca5570373e2af0b4cf2a4c392b6e4ffdfc8e6185e2d20b9832998c7ce63e8c6ffaa7662f8c1dbed1fff882cde0e33d75ffa8859@>
#"enode://2741de7be2482ceb7d11a2c140d64bf8b448445718e74b556585d42d8554958ea97a868ff0c77d9b15fe30d7fa691c69a8933216f69077d5e49661387f3bac6b@>

p2p-port=30303
max-peers=42

#rpc-http-host="192.168.1.70"
#"192.168.1.70"
rpc-http-host=["0.0.0.0"]
rpc-http-port=8545
rpc-http-enabled=true
rpc-http-api=["ETH", "NET","WEB3","ADMIN","TXPOOL","IBFT", "EEA","DEBUG"]


rpc-ws-host=["0.0.0.0"]
rpc-ws-port=8546
rpc-ws-enabled=true

#Metrics for monitoring
metrics-port=9545
metrics-push-port=9001

min-gas-price=0

logging="DEBUG"

    #allow all
host-allowlist=["*"]
rpc-http-cors-origins=["*"]

    # Chain
genesis-file="./genesis.json" # Path to the custom genesis file
node-private-key-file="./key"

    # Mining
miner-enabled=false
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

     

      Node2


data-path="./data" # Path

# Network
bootnodes=["enode://923f4bb2cc2e456ebe88afb5f2d8c6a84d5758b99840fc34d2fcf9df7e3a1204fed83524a50cf37533bee9a055d916c1634932a7f7129a10b0e43e5>
#"enode://0fdbb968c6082e5fb0de13cd8379961d5be7b24d4ff7f4eb378c738ca4cff4f13f3fb021883848fd783de1b592a101382c0401663a7c90313493a13da6a7b9c0@>
#"enode://534825b93db8b4220204d3c11ca5570373e2af0b4cf2a4c392b6e4ffdfc8e6185e2d20b9832998c7ce63e8c6ffaa7662f8c1dbed1fff882cde0e33d75ffa8859@>
#"enode://2741de7be2482ceb7d11a2c140d64bf8b448445718e74b556585d42d8554958ea97a868ff0c77d9b15fe30d7fa691c69a8933216f69077d5e49661387f3bac6b@>

#p2p-host="192.168.1.69"
p2p-port=30304
max-peers=42

rpc-http-enabled=true
rpc-http-host=["0.0.0.0"]
rpc-http-api=["ETH", "NET","WEB3","ADMIN","TXPOOL","IBFT", "EEA","DEBUG"]
host-allowlist=["*"]
rpc-http-cors-origins=["*"]
rpc-http-port=8550

#rpc-ws-host="192.168.1.69"
#rpc-ws-port=8546

#Metrics for monitoring
metrics-port=9546
metrics-push-port =9002

min-gas-price=0

# Chain
genesis-file="./genesis.json" # Path to the custom genesis file
node-private-key-file="./key"
# Mining
miner-enabled=false
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

      node3:

      
# Valid TOML config file
data-path="./data" # Path

# Network
bootnodes=["enode://923f4bb2cc2e456ebe88afb5f2d8c6a84d5758b99840fc34d2fcf9df7e3a1204fed83524a50cf37533bee9a055d916c1634932a7f7129a10b0e43e5>
#"enode://0fdbb968c6082e5fb0de13cd8379961d5be7b24d4ff7f4eb378c738ca4cff4f13f3fb021883848fd783de1b592a101382c0401663a7c90313493a13da6a7b9c0@>
#"enode://534825b93db8b4220204d3c11ca5570373e2af0b4cf2a4c392b6e4ffdfc8e6185e2d20b9832998c7ce63e8c6ffaa7662f8c1dbed1fff882cde0e33d75ffa8859@>
#"enode://2741de7be2482ceb7d11a2c140d64bf8b448445718e74b556585d42d8554958ea97a868ff0c77d9b15fe30d7fa691c69a8933216f69077d5e49661387f3bac6b@>


#p2p-host="192.168.1.68"
p2p-port=30305
max-peers=42

#rpc-http-host="192.168.1.68"
#rpc-http-port=8545

#rpc-ws-host="192.168.1.68"
#rpc-ws-port=8546

#Metrics for monitoring
metrics-port=9547
metrics-push-port =9003

min-gas-price=0

# Chain
genesis-file="./genesis.json" # Path to the custom genesis file
node-private-key-file="./key"

# Mining
miner-enabled=false
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"


      Node4:

      
      data-path="./data" # Path

# Network
bootnodes=["enode://923f4bb2cc2e456ebe88afb5f2d8c6a84d5758b99840fc34d2fcf9df7e3a1204fed83524a50cf37533bee9a055d916c1634932a7f7129a10b0e43e5>
#"enode://0fdbb968c6082e5fb0de13cd8379961d5be7b24d4ff7f4eb378c738ca4cff4f13f3fb021883848fd783de1b592a101382c0401663a7c90313493a13da6a7b9c0@>
#"enode://534825b93db8b4220204d3c11ca5570373e2af0b4cf2a4c392b6e4ffdfc8e6185e2d20b9832998c7ce63e8c6ffaa7662f8c1dbed1fff882cde0e33d75ffa8859@>
#"enode://2741de7be2482ceb7d11a2c140d64bf8b448445718e74b556585d42d8554958ea97a868ff0c77d9b15fe30d7fa691c69a8933216f69077d5e49661387f3bac6b@>


#p2p-host="192.168.1.67"
p2p-port=30306
max-peers=42

#rpc-http-host="192.168.1.67"
#rpc-http-port=8545

#rpc-ws-host="192.168.1.67"
#rpc-ws-port=8546

#Metrics for monitoring
metrics-port=9548
metrics-push-port =9004

min-gas-price=0

# Chain
genesis-file="./genesis.json" # Path to the custom genesis file
node-private-key-file="./key"

# Mining
miner-enabled=false
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

**Comment by emclab** [comment]
Here is the output of `admin_peers`:

       curl -X POST --data '{"jsonrpc":"2.0","method":"admin_peers","params":[],"id":1}' http://127.0.0.1:8545
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : [ {
    "version" : "0x5",
    "name" : "besu/v20.10.2/linux-x86_64/oracle-java-15",
    "caps" : [ "eth/62", "eth/63", "eth/64", "IBF/1" ],
    "network" : {
      "localAddress" : "127.0.0.1:30303",
      "remoteAddress" : "127.0.0.1:44258"
    },
    "port" : "0x7661",
    "id" : "0x534825b93db8b4220204d3c11ca5570373e2af0b4cf2a4c392b6e4ffdfc8e6185e2d20b9832998c7ce63e8c6ffaa7662f8c1dbed1fff882cde0e33d75ffa8859",
    "protocols" : {
      "eth" : {
        "difficulty" : "0x1",
        "head" : "0x436adb519c68f498b7cdb5649dcd51ee58be077fc8175e9db98471b2433ff88c",
        "version" : 64
      }
    }
  }, {
    "version" : "0x5",
    "name" : "besu/v20.10.2/linux-x86_64/oracle-java-15",
    "caps" : [ "eth/62", "eth/63", "eth/64", "IBF/1" ],
    "network" : {
      "localAddress" : "127.0.0.1:30303",
      "remoteAddress" : "127.0.0.1:44264"
    },
    "port" : "0x7660",
    "id" : "0x0fdbb968c6082e5fb0de13cd8379961d5be7b24d4ff7f4eb378c738ca4cff4f13f3fb021883848fd783de1b592a101382c0401663a7c90313493a13da6a7b9c0",
    "protocols" : {
      "eth" : {
        "difficulty" : "0x1",
        "head" : "0x436adb519c68f498b7cdb5649dcd51ee58be077fc8175e9db98471b2433ff88c",
        "version" : 64
      }
    }
  }, {
    "version" : "0x5",
    "name" : "besu/v20.10.2/linux-x86_64/oracle-java-15",
    "caps" : [ "eth/62", "eth/63", "eth/64", "IBF/1" ],
    "network" : {
      "localAddress" : "127.0.0.1:30303",
      "remoteAddress" : "127.0.0.1:44272"
    },
    "port" : "0x7662",
    "id" : "0x2741de7be2482ceb7d11a2c140d64bf8b448445718e74b556585d42d8554958ea97a868ff0c77d9b15fe30d7fa691c69a8933216f69077d5e49661387f3bac6b",
    "protocols" : {
      "eth" : {
        "difficulty" : "0x1",
        "head" : "0x436adb519c68f498b7cdb5649dcd51ee58be077fc8175e9db98471b2433ff88c",
        "version" : 64
      }
    }
  } ]

**Comment by rain-on** [comment]
Ok, so the call to ibft_getValidatorsAtBlockNumber (latest) seems to imply you only have a single validator in your highest block (Assumingly genesis).
Which means the extradata field in your genesis file is potentially incorrect.
If your goal was to have your bootnodes also be your validators, then your extradata field in the genesis file needs to appear:
0xf87ea00000000000000000000000000000000000000000000000000000000000000000f85494014dd8b0e3cb7b976bd410794157f6789940456f941d024882b1481e3d9db5773fa5238396dab00bdc94a426050c72985d29389690a3070f37b1a08a390a94b834e916f5ff60cb73a16355979e1170dba59351808400000000c0

Also - it would appear that the reported validator (c2....) isn't the address of any of the bootnodes - so I'm SUSPECTING that no nodes with the corresponding key are currently running - and thus no blocks are being mined (which is why transactions are not being added to the world state).

**Comment by emclab** [comment]
Yes, there is only one validator. I found out that there was something wrong with key generation (besu operator). But somehow besu node did not send out any message/error to dapp
