### ISSUE TITLE
Readiness check weirdness

### ISSUE THREAD

**Issue by e-nikolov** [hyperledger/besu#1677]
### Description

I am running a besu node for the ropsten test-net and the readiness checks kept randomly cycling between UP and DOWN every few seconds. I checked the container logs and it wasn't actually syncing and was throwing exceptions about being out of memory, but not crashing. I checked the last block synced and it was from about 40 hours before that. I was confused about why the readiness checks sometimes showed as UP even though the node was nowhere near being synced.

I checked the code of the readiness check in the github repo:
https://github.com/hyperledger/besu/blob/8b6f8b6e2f8f498af71523580eb0d6e6779d06c7/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/health/ReadinessCheck.java

https://github.com/hyperledger/besu/blob/bbcc438244b9966e95ee693150323208c42a87f6/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/DefaultSynchronizer.java

```
  public boolean isHealthy(final HealthService.ParamSource params) {
    LOG.debug("Invoking readiness check.");
    if (p2pNetwork.isP2pEnabled()) {
      final int peerCount = p2pNetwork.getPeerCount();
      if (!hasMinimumPeers(params, peerCount)) {
        return false;
      }
    }
    return synchronizer
        .getSyncStatus()
        .map(syncStatus -> isInSync(syncStatus, params))
        .orElse(true);
  }

```
```
  public Optional<SyncStatus> getSyncStatus() {
    if (!running.get()) {
      return Optional.empty();
    }
    return syncState.syncStatus();
  }
```

I noticed that if the synchronizer isn't running, an Optional.empty() is returned by the getSyncStatus() function, and the health check has .orElse(true). Does that mean that if the synchronizer is temporarily down the readiness check will return "UP" as long as there are enough peers connected?.

### Versions (Add all that apply)
* Software version: [`besu --version`]
docker image hyperledger/besu:1.4.4

**Comment by mark-terry** [comment]
@e-nikolov I've taken a look and your analysis seems pretty correct - if the synchronizer is down / not running *and* you've got the minimum required peers connected, it reports as healthy. From the description you've provided, it sounds like you may have encountered an edge case where the synchronizer is starting and running out of memory, causing the readiness check value to cycle as the synchronizer starts and stops.

The memory exceptions sound like an environment / configuration issue. Were you able to resolve this?

**Comment by e-nikolov** [comment]
I manually killed the kubernetes pod which caused it to get recreated and it's been running fine since. But I would expect that the node crashes on its own if it has insufficient memory rather than remaining in this broken state.

**Comment by e-nikolov** [comment]
@lucassaldanha Why was this issue closed? As far as I can tell the reported behaviour is still happening.

**Comment by mark-terry** [comment]
@e-nikolov This ticket was closed because we've tried, but haven't been able to replicate the state that produced the reported behaviour.

Please create another issue if you encounter the reported behaviour again. If you're able to provide replication steps, that'd be very helpful.
