### ISSUE TITLE
Issue with Besu keeping files open when sender does not actively close them

### ISSUE THREAD

**Issue by pegartillo95** [hyperledger/besu#1687]
**Besu client 20.10.1 accepts indiscriminately all incoming HTTP RPC connections, making JVM eventually collapse, if the connections are not closed by the invokers. Details below:**

##### Setup used for the test.
Client info:
- OS of the machine running the client: Ubuntu 18.04
- Client used to send the transactions: Artillery version 1.6.1
- Our client sending the transactions consist on a Artillery client on which we have a prebuilt json transaction. For each new sent transaction Artillery only needs to update the nonce and sign the new transaction.

Server info:
- OS of all the machines running the besu nodes: RedHat 7
- Version of all Besu Nodes: 20.10.1

Network info:
- Consensus Protocol: IBFT2
- Block time: 5 seconds.
- Topology of the network: 4 validators, 2 boot nodes and 1 regular node (this is the one to which we are sending the transactions)

### Test step by step
I'll explain now our testing procedure at the same time trying to show you some of the results we got.
The purpose we had when we found this issue was to stress test our private Besu network.
First we started sending transactions at a speed or about 250 txs/second, and we realized that suddenly after around 15 seconds the node was suddenly dying. So we started decreasing the number of txs/second little by little and we saw that it didn't matter how many txs/seconds we were sending the node will always crash after having processed around 3600 txs.
The number was always close to that amount it doesn’t matter if we sent 1 txs/second or 200 txs/second.

After that we realized that this was probably happening because of the number of open files that besu was keeping alive, which was continuously increasing during the test.
Here you can see some of our results for the number of open files we were getting in the case of sending only 1 tx/second, the metrics are taken from the machine running the regular node.
```
After roughly 15 minutes:
--------------------------------------
$ sudo lsof | grep java | wc -l
5206

$ sudo lsof | grep besu | wc -l
79494
--------------------------------------


After roughly 25 minutes:
--------------------------------------
$ sudo lsof | grep java | wc -l
8323

$ sudo lsof | grep besu | wc -l
151516
---------------------------------------


After roughly 35 minutes:
--------------------------------------
$ sudo lsof | grep java | wc -l
11946

$ sudo lsof | grep besu | wc -l
234714
--------------------------------------


At the point of having received around 3600, just before crashing
--------------------------------------
$ sudo lsof | grep java | wc -l
13803

$ sudo lsof | grep besu | wc -l
278623
--------------------------------------
```
As you can see the number of open files increases continuously as time passes, up to a point that it cannot be handled by the machine and suddenly stops working.

On the next snippet you can see the “Too many open files error” from the point of view of of the logs from the besu node. From that point on the node completely crashes, stopping to answer any request and it needs to be manually restarted.
```
2020-12-04 13:58:11.136+00:00 | EthScheduler-Workers-1 | INFO  | PersistBlockTask | Imported #19,168 / 26 tx / 0 om / 546,000 (0.0%) gas / (0xae19fafef14c15747ca848337270148c7c387b196e4b808bd8f082dfceba1d2c) in 0.008s. Peers: 2
2020-12-04 13:58:16.174+00:00 | EthScheduler-Workers-2 | INFO  | PersistBlockTask | Imported #19,169 / 24 tx / 0 om / 504,000 (0.0%) gas / (0x98876562c6b0f35c1f9170f23cf274d5ba3511d62770d5ffaee26a3e1c574c02) in 0.008s. Peers: 2
2020-12-04 13:58:21.136+00:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #19,170 / 26 tx / 0 om / 546,000 (0.0%) gas / (0xf500341efd03375da6a96b17f00aaf26fb020ef1878d192c8eb5f9c2c5b3d1f6) in 0.007s. Peers: 2
2020-12-04 13:58:26.183+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #19,171 / 24 tx / 0 om / 504,000 (0.0%) gas / (0x0f1d0a01ae9f9051a970f30752398fa4caa9a7a2b3723068648e9451abc3c9ff) in 0.008s. Peers: 2
2020-12-04 13:58:28.958+00:00 | vert.x-acceptor-thread-0 | WARN  | DefaultChannelPipeline | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. Too many open files
2020-12-04 13:58:29.959+00:00 | vert.x-acceptor-thread-0 | WARN  | DefaultChannelPipeline | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. Too many open files
```

Then we started to check what was happening on the client side and we realized that as we weren’t specifying Artillery to have a maximum number of virtual concurrent connections, it was opening one connection per http request and keeping them all open until the whole testing process had finished.

Finally we found a way of specifying Artillery to not to have more than a fixed number of concurrent connections at the same time (by setting the config.http.pool parameter). With this change it doesn’t matter at which speed we send the transactions, the amount of open concurrent open files handled by besu stays on a fixed number instead of increasing infinitely, and due to that it works perfectly.
This is how the number of open files evolves after this change on Artillery.
```
After roughly 15 minutes:
--------------------------------------
$ sudo lsof | grep java | wc -l
2532
$ sudo lsof | grep besu | wc -l
17965
------------------------------

After roughly 25 minutes:
--------------------------------------
$ sudo lsof | grep java | wc -l
2532
$ sudo lsof | grep besu | wc -l
17965
------------------------------

After roughly 35 minutes:
--------------------------------------
$ sudo lsof | grep java | wc -l
2532
$ sudo lsof | grep besu | wc -l
17965
------------------------------


After roughly 45 minutes:
--------------------------------------
$ sudo lsof | grep java | wc -l
2532
$ sudo lsof | grep besu | wc -l
17965
------------------------------
```
As you can see it keeps completely stable during the whole test compared to the results before the change.

If you feel like there’s any point where you would like to have some more info on how we performed the test just feel free to ask, we are happy to collaborate because we think this is a critical issue that should be fixed. It allows for an easy way to DoS any Besu node just by using a client that does not actively close connections, because Besu does not close them unless the client does.

**Comment by shemnon** [comment]
Do you have a list of the HTTP headers that artillery is using?  Specifically I want to know if `keep-alive` is part of the set, i.e. if vert.x is keeping the connection open at the request of the client or if it's failing to explicitly close it.

**Comment by shemnon** [comment]
Also, is the artillery code publicly available or can it be made available?

**Comment by shemnon** [comment]
Also, what is the state of all of those sockets?  ESTABLISHED, CLOSED, CLOSE_WAIT?  Is artiliery relying onserver side closing? (not a good thing if so... https://stackoverflow.com/questions/3757289/when-is-tcp-option-so-linger-0-required).

**Comment by pegartillo95** [comment]
> Do you have a list of the HTTP headers that artillery is using? Specifically I want to know if `keep-alive` is part of the set, i.e. if vert.x is keeping the connection open at the request of the client or if it's failing to explicitly close it.

Here you have the set of headers that Artillery is using.
```
{ date: 'Fri, 11 Dec 2020 09:21:38 GMT',
  'content-type': 'application/json',
  'content-length': '103',
  connection: 'keep-alive',
  vary: 'Origin' }
```
As you can see keep-alive is one of them as you were suspecting

**Comment by pegartillo95** [comment]
> Also, is the artillery code publicly available or can it be made available?

Sure, this is the repo we are using: https://github.com/san-lab/ethereumArtilleryTest
As you can see there are several tests, among them the one we were using the one called "ethereumTestBasic.yml". 
The transaction that is used on that test consist on a sending of a small amount of Wei from one account to another.

**Comment by shemnon** [comment]
It's the keep-alive header being sent and then not re-using the http connection that's causing the problem.  Not sure that there is anything we _should_ do to address this.  All we really can do is disrespect keep-alive or trim it to a useless timeframe like 1 second.

**Comment by shemnon** [comment]
The problem with expiring the session is that it is a server close, which leads to either CLOSE_WAIT or setting SO_LINGER which is considered bad practice.  Refusing the session still leaves the port in CLOSE_WAIT too as it would again be a server initiated close.

**Comment by JaimeGomezGarcia** [comment]
Hi @shemnon 
Sorry for not having put attention on this since before Christmas.
We have made some further tests I'd like to comment. IMO this is an open target for a DoS to the node as you can easily crash it.
1. We have workarounded this by setting an envoy proxy in the middle. It is able to manage the offending requests and establishes a controlled number of TCP sessions to Besu.
2.From a TCP state machine perspective there are a couple of options:

A) From LISTEN you can send a RST to reject connections when your active connection pool is over some threshold. This can also be achieved using iptables on host config. This approach would also enable the DoS but would avoid besu from crashing.

B) From ESTABLISHED you can server-close inactive sessions which would lead you to FIN_WAIT_1 (and not to CLOSE_WAIT as you mentioned). From here, timing out those sessions if the other end does not participate in the closing handshake is a task for the TCP stack of the OS.

Jaime

**Comment by macfarla** [comment]
@pegartillo95 and @JaimeGomezGarcia this should now be fixed in master. You can use `--rpc-http-max-active-connections` to set a max. Default is 80. Are you able to test this out with your setup?

**Comment by JaimeGomezGarcia** [comment]
@macfarla Thanks for addressing this. It would take some time for us to check this as we would need to do some setups and are currently focused on another thing. But we'll follow up as soon as we can.
