### ISSUE TITLE
No message sent when RPC node rejects call

### ISSUE THREAD

**Issue by emclab** [hyperledger/besu#1689]
### Description
Without `rpc-http-host=["0.0.0.0"]`, the RPC node rejects calls from dapp. In my case the dapp was just waiting and waiting. A error message from RPC node will help developer/user to quickly identify the problem. Also in situation of in sufficient validator, no message is sent from RPC nodes as well.

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. Use config.toml without whitelist for rpc-http-host.
2. [Step 2]. Deploy a contract from etherjs (`contract.deployTransaction`). Web3 may do as well
3. [Step ...]. Check the console log to see if there is any message returned. There shouldn't be any.

**Expected behavior:** [What you expect to happen]
Send out error message when RPC node rejects a call because the host is not on whitelist.
**Actual behavior:** [What actually happens]
No any message sent
**Frequency:** [What percentage of the time does it occur?]
always
### Versions (Add all that apply)
* Software version: [`besu --version`]:1.5.0/20.10.2. IBFT2
* Java version: [`java -version`]:15
* OS Name & Version: [`cat /etc/*release`] Win10
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by emclab** [comment]
Also in doc it states that checking the number of peers to confirm [IBFT2 network is working.](https://besu.hyperledger.org/en/1.3.6/Tutorials/Private-Network/Create-IBFT-Network/#10-confirm-private-network-is-working) . However in practice number of peers does not guarantee the IBFT2 network is fully functioning, especially in case of insufficient number of validators. Adding a check of  validators may make sense here.

**Comment by shemnon** [comment]
the second comment needs to be separate issue.

**Comment by shemnon** [comment]
If the fix is `rpc-http-host=["0.0.0.0"]` then I don't think that there is anything that Besu can do.  Besu will only be listening to 127.0.0.1 and the operating system will not forward any packets to besu.

Changing the default `rpc-http-host` to anything but `127.0.0.1` is not an option because of our secure by default policy on network ports.

**Comment by MadelineMurray** [comment]
Thanks for taking the time to raise @emclab - I've created a couple of docs issues to make these points clearer (see above).

**Comment by vmichalik** [comment]
Hi @emclab, I believe that hyperledger/besu-docs#582 and hyperledger/besu-docs#583 cover this, please close if you agree!

**Comment by macfarla** [comment]
Closing as this has been addressed!
