### ISSUE TITLE
Ledger live account creation issue on Besu

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu#1731]
This is an anonymous comment received from Iran on the feedback form on Besu doc site about the RPC API page: https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/Using-JSON-RPC-API/

> in Ledger Live when i add ETH accounts i get HTTP API 503 error

I guess it happens when connecting Ledger live directly to a local node. This needs to be reproduced first.

But if not obvious, as the comment is anonymous, feel free to close the issue.

**Comment by MadelineMurray** [comment]
This could be a be an issue on the ledger live side as well - https://www.ledger.com/start

**Comment by NicolasMassart** [comment]
This has absolutely nothing to do with Besu as Ledger Live doesn't enable connection to a custom node. Closing this.
