### ISSUE TITLE
Two honest IBFT2 validators add two different blocks with the same height to their respective blockchains.

### ISSUE THREAD

**Issue by saltiniroberto** [hyperledger/besu#1734]
### Possible Actual Behaviour of an IBFT2 validator
Let _v_ be an IBFT2 validator. The following sequence of events may occur:
1. _v_ receives a valid `<PROPOSAL, h, r, B>` message
2. _v_ sends a valid `<PREPARE, h, r, hash(B)>` message
3. _v_ stores locally a valid `<COMMIT, h, r, commitSeal(B), hash(B)>` message 
4. _v_ receives, from other 2 validators, 2 valid `<COMMIT, h, r, commitSeal(B), hash(B)>` messages and adds them to the event queue.
5. The thread handling round timers (controlled by `IbftExecutors::timerExecutor`) is awakened by the expiry of the round timer for the current round (_r_) which causes a `RoundExpiry` event for the current round (_r_) to be put in the queue after the events for the 2 `COMMIT` messages sent at the point above.
6. The thread executing the IBFT state machine (controlled by `IbftExecutors::ibftProcessorExecutor`) is scheduled and the two `COMMIT` message events are dequeued. Since the quorum for a network of 4 validators is 3 and the node has stored locally 3 valid `COMMIT` messages sent by 3 different validators (which includes the one stored at point 3), it adds block `B` to its local blockchain. This will cause a `NewChainHead` event to be added to the queue of events, but after the `RoundExpiry` event
7. The `RoundExpiry` event is dequeued and as a consequence of this, a `<ROUND-CHANGE, h, r+1, latest`PREPARE`dCertificate>` message for round _r+1_ is sent

### Possible Actual Behaviour of a Network of IBFT2 validators
The possible actual behaviour is exemplified on a network of 4 IBFT2 validators

**Assumptions**
- Network with 4 validators, _v1_, _v2_, _v3_ and _v4_
- quorum = 3
- _v1_ is malicious

**Scenario**
1. _v1_ multicasts a `<PROPOSAL, h, 0, B>` message
2. _v3_ and _v4_ receive the `PROPOSAL` message sent by _v1_. _v2_ will not receive it.
3. Each of the _v3_ and _v4_ nodes responds with a `<PREPARE, h, 0, hash(B)>` message and stores a `<COMMIT, h, 0, commitSeal(B), hash(B)>` message locally
4. Only _v3_ receives the `PREPARE` messages sent at the point above. Since _v3_ has received a valid `PROPOSAL` message and 2 valid `PREPARE` messages for block `B`, it sends a `<COMMIT, h, 0, commitSeal(B), hash(B)>` message.  
Only _v3_ is prepared on round 0.
6. _v1_, who is malicious, alse sends a `<COMMIT, h, 0, commitSeal(B), hash(B)>` message.
7. Only _v4_ receives the `COMMIT` messages sent at points 4 and 5 and adds them to its event queue. 
8. The thread handling the round timers for _v4_ is awakened by the expiry of the round timer for round 0 which causes a `RoundExpiry` event for the current round (_r_) to be put in the queue after the events for the 2 `COMMIT` messages added to the queue at the point above.
9. The thread executing the IBFT state machine on _v4_ is scheduled and the `COMMIT` messages are dequeued before the `RoundExpiry` event. Since _v4_ has received 1 `PROPOSAL` and 3 valid `<COMMIT, h, 0, commitSeal(B), hash(B)>` messages (one of which is the one that it stored locally when it received a valid `PROPOSAL` message at point 3), it adds block `B` to its local blockchain.
10. _v4_ deques the `RoundExpiry` event for round 0 and therefore it multicasts a `<ROUND-CHANGE, h, r+1, empty>` with an empty prepared certificate as it did not prepare (_v4_ never received the `PREPARE` message sent by _v3_ at point 3).
11. Also the round timer for node _v2_ expires and therefore _v2_ multicasts a `<ROUND-CHANGE, r, h, r+1, empty>` message with an empty prepared certificate as _v2_ never received any message for round 0.
12. _v1_, who is malicious, also multicasts a `<ROUND-CHANGE, h, r+1, empty>` message with an empty prepared certificate.
13. _v2_, who is the proposer for round 1, receives the `ROUND-CHANGE` messages sent by _v1_, _v2_ and _v4_.
14. Since all the `ROUND-CHANGE` messages sent by _v1_, _v2_ and _v4_ have an empty prepared certificate, _v2_ does not have any preferred block to propose and it multicasts a `<PROPOSAL, h, 0, B2>` with `B2` different from `B`. 
15. _v1_ and _v2_ respond with a `<PREPARE, h, 1, hash(B2)>` message.
16. _v1_, _v2_ and _v3_ receive 2 valid `PREPARE` messages for round 1 and block `B2` and therefore they send a `<COMMIT, h, 1, commitSeal(B2), hash(B2)>` message.
17. _v2_ receives all the `COMMIT` messages sent at the point above and therefore it adds block `B2` to its blockchain at height _h_.
18. _v4_ and _v2_ end up with two different blocks for the same height _h_, `B` and `B2` respectively, on their respective blockchains.

### Expected Behaviour of a Network of IBFT2 Validators
It should never happen that in a network of 4 IBFT2 validators, out of which only one is malicious, two honest nodes add two different blocks with the same height to their respective blockchains.

## How was this bug discovered
This bug was discovered as part of the formal specification and verification of an alternative BFT consensus protocol based on IBFT2.

**Comment by saltiniroberto** [comment]
Fixed by #1575

**Comment by sambacha** [comment]
Is there a link to the formal specification and verification for IBFT2 you are referencing or is it just the whitepaper that was published.
