### ISSUE TITLE
Bonsai tries : ClassCastException when pruning is enabled

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#1738]
### Description

There is a cast exception when pruning is enabled. 

```
class org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive cannot be cast to class org.hyperledger.besu.ethereum.worldstate.DefaultWorldStateArchive (org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive and org.hyperledger.besu.ethereum.worldstate.DefaultWorldStateArchive are in unnamed module of loader 'app')
```

The error seems to be related to this line https://github.com/hyperledger/besu/blob/5241747ba4a62e08953b9584ae03732196b69795/besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java#L259

### Acceptance Criteria
* Besu start to sync without crashing 

### Steps to Reproduce (Bug)
1. Run besu with this otions 
```
--logging="INFO" --network=goerli --data-path=/goerli-bonsai --fast-sync-min-peers=2 --sync-mode=FAST --discovery-enabled=true --pruning-enabled=true --Xdata-storage-format=BONSAI
```

### Versions (Add all that apply)
* Software version: Master (5241747ba4a62e08953b9584ae03732196b69795)

**Comment by shemnon** [comment]
Pruning doesn't work with the Bonsai storage format.  We should detect this in BesuCommand and fail when these two conflicting options are requested.
