### ISSUE TITLE
How can I enable gas fee on the ibft private network 

### ISSUE THREAD

**Issue by eu09** [hyperledger/besu#1740]
Is possible to enable the price fee on the IBFT private network. ? Here with my sample genesis-file . 

{
  "config" : {
    "chainId" : 2018,
    "muirglacierblock" : 0,
    "ibft2" : {
      "blockperiodseconds" : 2,
      "epochlength" : 30000,
      "requesttimeoutseconds" : 4,
      "blockreward": "5000000000000000",
      "miningbeneficiary": "00929a35ab4a3426407b5c812b5b5c227aab691b"
    }
  },
  "nonce" : "0x0",
  "timestamp" : "0x58ee40ba",
  "gasLimit" : "0x47b760",
  "difficulty" : "0x1",
  "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase" : "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "00929a35ab4a3426407b5c812b5b5c227aab691b" : {
      "balance" : "0xad78ebc5ac6200000"
    },
    "0793cb40a11cc6301ae516dab378d9831fb46192" : {
      "balance" : "90000000000000000000000000"
    },
    "42af34d9c040d3605cdd53b759175f71c48c5348" : {
      "balance" : "90000000000000000000000000"
    }
  },
  "extraData" : ""
}

**Comment by MadelineMurray** [comment]
hi @eu09 - we've got a number of team members out on leave this week so might be next week before you see an answer.

**Comment by MadelineMurray** [comment]
The `--min-gas-price` command line option specifies if a gas fee is required.  Leaving it at the default (1000 Wei) or setting to a specific value will enable a gas fee on an IBFT 2.0 network.

**Comment by rain-on** [comment]
Hey @eu09,
The real issue with enabling a gas-fee on an IBFT2 network, is the _creation_ and distribution of Eth, such that users of the network can apply a non-zero gas price to their transactions.

So, all accounts can be given an allocation up front via the genesis file, but, how do you "top them up" over time?
The answer is to enable mining rewards in the network such that a specific account will be paid a fixed sum per block (along with transaction fees).
The maintainer of this account is then responsible for distributing this generated Eth to all users of the network in whatever way they see fit - i.e. this account becomes the "central bank" of the network.

To enable mining rewards you need to add:
* miningbeneficiary (hex address), and
* blockreward (in wei)
to your genesis file (on all nodes - i.e. everyone must agree that someone will get paid, or else blocks will be invalid).

Then, when starting your validators, add the min-gas-price to set an appropriate gas-price for the network (i.e. a non-zero value) - this then will ensure that all nodes must supply an acceptable gasPrice to their transactions for their transactions to be mined, and therefore pay the subsequent Eth.

**Comment by vmichalik** [comment]
Hi @eu09, I believe the above answers your issue, so closing this for now - please feel free to reopen if you have any further questions!
