### ISSUE TITLE
Take NO_COLOR env var in account for output color config 

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu#1756]
### Description
As a user, I want the NO_COLOR env var standard to be used so that output is colored according to my global choice.

Currently, if Besu detects it's running on a compatible console, [color will be on by default](https://github.com/hyperledger/besu/pull/1026/files#diff-74d67833f6aeb15201c396d66174a5a81eba997dc4c6346bcb6754fd0d01324fR86).

[NO_COLOR standard](https://no-color.org/) requires that software with color on by default checks for the NO_COLOR env var to match the user choice. 

### Acceptance Criteria
* If the NO_COLOR env var is defined, output will not contain ANSI colors even if the user did not define the `color-enabled` option in Besu (see https://github.com/hyperledger/besu-docs/pull/587) 

### Steps to Reproduce (Bug)
1. export a NO_COLOR env var in a color compatible terminal
2. run Besu in this terminal
3. Notice that Besu output has color despite the NO_COLOR env var.

**Expected behavior:** [What you expect to happen]

> All command-line software which outputs text with ANSI color added should check for the presence of a NO_COLOR environment variable that, when present (regardless of its value), prevents the addition of ANSI color.

Source: https://no-color.org/

**Actual behavior:** [What actually happens]

NO_COLOR environment variable is not taken in account

**Frequency:** [What percentage of the time does it occur?]

Always, feature not implemented.

### Versions (Add all that apply)

all

### Additional Information

https://no-color.org/

**Comment by RatanRSur** [comment]
For anyone seeing this, we're looking into adding it. In the meantime `BESU_COLOR_ENABLED=false` is a workaround.
