### ISSUE TITLE
Hybrid miningbeneficiary in IBFT2

### ISSUE THREAD

**Issue by jlochman** [hyperledger/besu#1759]
In IBFT 2.0 genesis file, there is `miningbeneficiary` field. 

```
{
  "config": {
    "ibft2": {
      "miningbeneficiary": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
    },
  },
}
```

If this field is omitted, then a block reward goes to a validator that proposes the block.
If this field is set, then there is only one single `miningbeneficiary` who always receives the full block reward.

My question is: Is it possible to configure mining reward to be split between validator that proposes the block and the one single `miningbeneficiary`. Let's say the reward is split 80:20?

**Comment by arash009** [comment]
There isn't a way to enable this at the moment directly in Besu, but you can achieve this by setting the `miningbeneficiary` to be a smart contract address that can then disperse the rewards based on whatever logic is most appropriate for the use case. The smart contract can obtain the validator that proposed the block using the Besu APIs and split the funds 80:20

**Comment by arash009** [comment]
I may have been wrong in my assumption that you can set a contract address as the `miningbeneficiary`. Let us know if you get it working, but it might be that you can only define a wallet address.
