### ISSUE TITLE
Deploying private contract with constructor parameters doesn't work

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#1760]
### Description
Regarding deploying the contract (with constructor parameters) to privacy group. Getting the transaction receipt, but it’s failing to deploy. (And the same contract works fine without privacy group.) Any help on this would be appreciated.

### Acceptance Criteria
* Deployment should succeed in the same way it succeeds when deploying it as a public contract

### Steps to Reproduce (Bug)
1. Run the attached script to create a private contract
2. The receipt shows that deployment fails

**Expected behavior:** [What you expect to happen]
- Successful deployment

**Actual behavior:** [What actually happens]
- Getting the transaction receipt, but it’s failing to deploy

**Frequency:** [What percentage of the time does it occur?]
- Everytime

### Versions (Add all that apply)
N/A

### Additional Information
[script_and_output.zip](https://github.com/hyperledger/besu/files/5784156/script_and_output.zip)
- Attached the script being used (script.js)
- Attached output of script execution (output.js)

### Assessment
- Probability: Probable - smart contracts with constructor parameters are commonly used
- Severity: Moderate - the specific contract won't work, but it won't break privacy as a whole
- Assessment: P3

**Comment by lucassaldanha** [comment]
Slack thread: https://consensys.slack.com/archives/CQ6B7535E/p1609708342151700

**Comment by lucassaldanha** [comment]
From Kantesha:

> The issue seems to be with the size of the binary (size of the contract). I tried removing part by part, after removing half of the code, it deployed successfully. Now the question is how can we deploy the whole contract.

> I haven’t set any size limit in genesis file. And I think there’s a 24576 byte limit for contract size. I tried increasing this, but still it failed. The size of the token contract is less than the 24576 (build/contracts/ERC1400HoldableToken.json: 21204.5). Is it the encoding which is increasing the size?

**Comment by macfarla** [comment]
This is the contract in question:
https://github.com/ConsenSys/UniversalToken/blob/master/contracts/tokens/ERC1400HoldableToken.sol

**Comment by macfarla** [comment]
To deploy as a public contract, they used truffle.
https://github.com/ConsenSys/UniversalToken/blob/master/migrations/5_erc1400_holdable.js

Looking at the truffle deployment, there is a lot of other supporting contracts that get deployed. If I delete all the other migration scripts and just run migrations/5_erc1400_holdable.js I hit a revert
5_erc1400_holdable.js
=====================
   Replacing 'ERC1400HoldableToken'
   --------------------------------
   > transaction hash:    0xd8bd320b9ae5c21b80890523d792d58a3676890087bc68f0a6da831a19040bec
   > ERC1400HoldableToken token deployment without extension: Success --> 0xf204a4Ef082f5c04bB89F7D5E6568B796096735a
Error:  *** Deployment Failed ***
"ERC1400HoldableToken" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.
And if I add back in migrations/2_erc1820_registry.js it does not hit the revert.
Hence this means you need to deploy the registry contract for the token to work.

**Comment by macfarla** [comment]
The steps required to deploy the ERC1400HoldableToken are described in a private repo.
Kanthesha is working on getting his local environment setup so that he can test out the deployment locally.

**Comment by macfarla** [comment]
@sally.macfarlane Sorry! I thought I already updated you. With this https://github.com/lucassaldanha/besu-local-nodes setup. It is working fine. thanks
