### ISSUE TITLE
Upgrading Besu Instructions

### ISSUE THREAD

**Issue by twhay** [hyperledger/besu#1764]
### Description
As an Besu User, I want there to be a brief line added to https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Installation-Options/Install-Binaries/ so that a user upgrading from a prior version of Besu is reminded to install Command line tools (xcode-select --install) if they have upgraded their version of MacOS between installs of Besu. 

### Acceptance Criteria
* A brief note on https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Installation-Options/Install-Binaries/ notifying users that have upgraded to a newer version of MacOS and have not ensured command line tools are reinstalled, upon running
`brew upgrade hyperledger/besu/besu`
you may be prompted to reinstall command line tools 
`xcode-select --install`

### Steps to Reproduce (Bug)
1. Go to https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Installation-Options/Install-Binaries/
2. `brew upgrade hyperledger/besu/besu`

**Expected behavior:** [What you expect to happen]
Besu to upgrade from 1.2.4 to 20.10.3

**Actual behavior:** [What actually happens]
Error: The following formula cannot be installed from bottle and must be
built from source.
  besu
Install the Command Line Tools:
  xcode-select --install

**Frequency:** Only after upgrading a computer from MacOS 10 to MacOS 11. During the upgrade, it appears that command line tools did not remain installed, causing the Besu upgrade to fail. 

### Versions (Add all that apply)
* Software version: Besu to upgrade from 1.2.4 to 20.10.3
* Java version: Java 15
* OS Name & Version: MacOS Big Sur v11.1
* Kernel Version: Not relevant
* Virtual Machine software & version: Not relevant
* Docker Version: Not relevant
* Cloud VM, type, size: Not relevant

### Additional Information
As many Mac users have upgraded or are upgrading to MacOS 11, I'd like to see a brief note made to say if you have upgraded to a newer version of MacOS and have not ensure command line tools are reinstalled, upon your running of 
`brew upgrade hyperledger/besu/besu`
you may be prompted to reinstall command line tools 
`xcode-select --install`

**Comment by MadelineMurray** [comment]
Issue moved to [hyperledger/besu-docs #596](https://github.com/hyperledger/besu-docs/issues/596) via [**ZenHub**](https://www.zenhub.com/)
