### ISSUE TITLE
Retrieving a transaction's publicKey

### ISSUE THREAD

**Issue by kss-espeo** [hyperledger/besu#1802]
Hi!

I am developing an application that used Parity node as its integration point with Ethereum Classic. However, after Thanos hardfork it has become deprecated, so now I'm considering to use HL Besu node. For context - my application pulls data from the blockchain in order to do anti-money-laundering analysis on it.

I need to be able to retrieve a `publicKey` of a transaction. In Parity, `publicKey` was a part of response of `eth_getTransactionByHash` . In HL Besu it is not. 

In theory, I should be able to extract `publicKey` from the transaction signature, but in order to do that I would need to first construct  an `unsigned raw transaction` . It would be possible to do this if `eth_getTransactionByHash` returned transactions `raw` data, but it does not. An alternative way to do that would be just recreating a raw transaction from scratch - however `eth_getTransactionByHash` result is missing one field necessary to do that, namely transaction's `gasLimit` .

My question is:

Is there another way to retrieve a public key of a transaction using HL Besu interface?
If not - is there a way to retrieve transaction's `raw` or `gasLimit` so that I can construct an unsigned raw transaction myself?
If an answer to both questions is "no" - would it be possible to implement that?

**Comment by MadelineMurray** [comment]
hi @kss-espeo - following up on an answer to this.

**Comment by shemnon** [comment]
(a) The gasLimit is the `gas` field in the transaction result.  So all the fields are present.
(b) the GraphQL endpoint has the sender and receiver address.

Also, san you post a sample parity request/response?  If we add it I want to make sure we get all additional fields parity does.

**Comment by shemnon** [comment]
Other than `publicKey` and `raw`, which new fields add value?

One I see value in are `chainId`, even though it can be calculated from v. 

I don't think `condition`,`creates`, and `standardV` add much value.

```
{
    "jsonrpc": "2.0",
    "result": {
        "blockHash": "0x937d8b7cbd5a59632819c9c1786add67fb99dd333b6109cebdde9035645bee73",
        "blockNumber": "0x18ddcb",
        "chainId": "0x5",
        "condition": null,
        "creates": null,
        "from": "0x21d7acbcaea5dd43e28c41b37a1296d6aaa4d912",
        "gas": "0x4c4b40",
        "gasPrice": "0x77359400",
        "hash": "0xbe06ecee8be176ea39944b53d11298d20feb847528c79b99c9a96d10b3c15cd0",
        "input": "0xf2f038770000000000000000000000000000000000000000000000000000000000009f255a5951b5b857fd5bfeb11ceaf62ae64785912532e725d7942418013c5a6e9633",
        "nonce": "0x17bd",
        "publicKey": "0x84432ffb6548942e646aebab21956e80758379a0a38a2996c28ac22683a97ca4a91aaed949b0ab661299a6e477e3c74c9cbd51d0e43532fe9917bb0a40f4df76",
        "r": "0xf82f36b229c58f50133af4af83c2000159d1e04f805a35277365dac619e560d6",
        "raw": "0xf8ab8217bd8477359400834c4b4094b0346ba3d87d6e2915bfb121eb4e5042953eae4080b844f2f038770000000000000000000000000000000000000000000000000000000000009f255a5951b5b857fd5bfeb11ceaf62ae64785912532e725d7942418013c5a6e96332ea0f82f36b229c58f50133af4af83c2000159d1e04f805a35277365dac619e560d6a034768159648d1efcff66fb39d8ba1b58e3cbd522a344cfb219fe2af007ae9218",
        "s": "0x34768159648d1efcff66fb39d8ba1b58e3cbd522a344cfb219fe2af007ae9218",
        "standardV": "0x1",
        "to": "0xb0346ba3d87d6e2915bfb121eb4e5042953eae40",
        "transactionIndex": "0x4",
        "v": "0x2e",
        "value": "0x0"
    },
    "id": 1
}
```

**Comment by kss-espeo** [comment]
Cool, I thought `gas` is gas spent, and not the limit. It's a little misleading IMO, but it seems to be the same for other nodes so I guess that's the standard name. In such case I should have enough information to be able to derive `publicKey` from the signature data. Thanks!

As for usefulness of missing Parity params - I agree with @shemnon - mostly `raw` and `publicKey` are useful. `chainId` would be nice. `condition` and `creates` seem to be only useful in specific cases that I do not have experience with.

**Comment by kss-espeo** [comment]
Request:
```
{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionByHash",
    "params": [
        "0xf69056cec90aaeb8e6dc0e5a39651bea913613631c94cefe78b1f66acb51eb73"
    ],
    "id": 1
}
```
HL Besu response:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0x9a1ac989ae7a94eeda90227e1455afe20d5b8be26ed527304bd2b241413e31ae",
        "blockNumber": "0x87a23",
        "from": "0x2a65aca4d5fc5b5c859090a6c34d164135398226",
        "gas": "0x15f90",
        "gasPrice": "0xba43b7400",
        "hash": "0xf69056cec90aaeb8e6dc0e5a39651bea913613631c94cefe78b1f66acb51eb73",
        "input": "0x",
        "nonce": "0x7aef",
        "to": "0xdca73e49c84ea80a22eae8925d4590bfadd1fc50",
        "transactionIndex": "0x1",
        "value": "0x12e34f6ededc5400",
        "v": "0x1c",
        "r": "0x748997c0d3f360ebbe04e5e9c895ad8f72ebdb4ecbf75a40a7e1b99c66a9b290",
        "s": "0x2a3baccc365f3800c10070992fbd0eb351a3d23e2ef3a6bd0780ee0607b1eb18"
    }
}
```
Parity response:
```
{
    "jsonrpc": "2.0",
    "result": {
        "blockHash": "0x9a1ac989ae7a94eeda90227e1455afe20d5b8be26ed527304bd2b241413e31ae",
        "blockNumber": "0x87a23",
        "chainId": null,
        "condition": null,
        "creates": null,
        "from": "0x2a65aca4d5fc5b5c859090a6c34d164135398226",
        "gas": "0x15f90",
        "gasPrice": "0xba43b7400",
        "hash": "0xf69056cec90aaeb8e6dc0e5a39651bea913613631c94cefe78b1f66acb51eb73",
        "input": "0x",
        "nonce": "0x7aef",
        "publicKey": "0x4c3eb5e19c71d8245eaaaba21ef8f94a70e9250848d10ade086f893a7a33a06d7063590e9e6ca88f918d7704840d903298fe802b6047fa7f6d09603eba690c39",
        "r": "0x748997c0d3f360ebbe04e5e9c895ad8f72ebdb4ecbf75a40a7e1b99c66a9b290",
        "raw": "0xf86f827aef850ba43b740083015f9094dca73e49c84ea80a22eae8925d4590bfadd1fc508812e34f6ededc5400801ca0748997c0d3f360ebbe04e5e9c895ad8f72ebdb4ecbf75a40a7e1b99c66a9b290a02a3baccc365f3800c10070992fbd0eb351a3d23e2ef3a6bd0780ee0607b1eb18",
        "s": "0x2a3baccc365f3800c10070992fbd0eb351a3d23e2ef3a6bd0780ee0607b1eb18",
        "standardV": "0x1",
        "to": "0xdca73e49c84ea80a22eae8925d4590bfadd1fc50",
        "transactionIndex": "0x1",
        "v": "0x1c",
        "value": "0x12e34f6ededc5400"
    },
    "id": 1
}
```

**Comment by shemnon** [comment]
gas spent is always on the receipt, as it is a function of the transaction and the world state, hence the block.

I'll add `chainId`, `publicKey`, and `raw`.  We will get these int he whole `eth_getTransaction*` series.

**Comment by kss-espeo** [comment]
Thanks @shemnon . Is it too early to ask for a rough timeline on this?

**Comment by kss-espeo** [comment]
Ok, I think this is in `21.1.0-RC1` . Closing.

Thanks!
