### ISSUE TITLE
Support compressing API responses via the accept-encoding header

### ISSUE THREAD

**Issue by egalano** [hyperledger/besu#1881]
### Description
As an API user, I want support for the `accept-encoding:gzip` header so that sizable payloads like full block data, eth_call output and othe requests benefit from the compressibility of the API responses. Other client implementations support this feature and we benefit from the reduced bandwidth overhead with minimal CPU impact.

### Acceptance Criteria
* Respond to a JSON-RPC request with an `accept-encoding:gzip` header with a gzip compressed response and corresponding `content-encoding:gzip` header set so that the client knows to handle a compressed payload in the response.

**Comment by timbeiko** [comment]
Being addressed by https://github.com/hyperledger/besu/pull/1884
