### ISSUE TITLE
Postman rendered docs shows GET in the CURL example for a POST

### ISSUE THREAD

**Issue by shanejonas** [hyperledger/besu#1912]
### Description
Postman rendered docs shows GET in the CURL example for a POST

### Steps to Reproduce (Bug)
1.  https://api.besu.hyperledger.org/
2. scroll to `admin_logsRepairCache`
3. says POST but there is a GET in the CURL

**Expected behavior:** [What you expect to happen]
Should only be POST

### Additional Information
![image](https://user-images.githubusercontent.com/364566/107856565-ce396500-6ddd-11eb-939d-21f0be0f04f1.png)

**Comment by NicolasMassart** [comment]
Fixed
