### ISSUE TITLE
Github <> Slack integration

### ISSUE THREAD

**Issue by lukerQuant** [hyperledger/besu#1914]
### Description
As a company working with Besu, I would like slack integration so that changes in the Besu repo immediately produce slack notifications (in other companies slack). 

### Acceptance Criteria
Add the slack app to this repo (https://slack.github.com/)

### Additional Information
I understand that email notifications can be used, but in my opinion slack notifications provides easier team organisation.

**Comment by atoulme** [comment]
Closing per the discussion at https://github.com/bitcoin/bitcoin/issues/21184
