### ISSUE TITLE
Detach allow list data from permissioning contract 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#1919]
When the permissioning smart contract is upgraded, the allow list entries must be reloaded into the upgraded contract.  Detaching the data in a way that allows the contract to be upgraded without losing the data would be a better user experience.

**Comment by vmichalik** [comment]
Detaching the data will help to pave the way for #431

**Comment by vmichalik** [comment]
this is a decent explanation of the advantages of keeping storage in a separate contract https://fravoll.github.io/solidity-patterns/eternal_storage.html

h/t @macfarla
