### ISSUE TITLE
Update ENR record when passing milestone blocks

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#1931]
The ENR record as currently constituted has a field holding the fork id of the node.  This fork ID should change when we roll over to the new fork.

We should broadcast the forkID of of the best _known_ block and when that crosses the barrier accept that fork id.  We will also need to write the forkid to the persistent storage when needed.

So probably a listener on the blockchain object, that has a reference to the protocol schedule and whatever class holds the ENR.  When we detect a change in the listener from observed values we fire off an event to the object calculating the ENR to rebuild it.

**Comment by shemnon** [comment]
Re-opening as the ENR did not update after the goerli fork.  Perhaps it wasn't pushed down to the p2p layer?


```
dannos-mbp:~ dannoferrin$ devp2p enrdump  `devp2p -verbosity 1 discv4 requestenr enode://6ff032786b390dda567836c446b78f30e5544fc96d4f32d338e7b4537e7418bdff9b7c5843664e618f974205c5039e64ef250d3b4d1683f89968d5a245a693b0@127.0.0.1:30303`
Node ID: 65fc3954d0600096009ecb0e16c6846f0fda51c48bac02cfe4aec173540edb99
URLv4:   enode://6ff032786b390dda567836c446b78f30e5544fc96d4f32d338e7b4537e7418bdff9b7c5843664e618f974205c5039e64ef250d3b4d1683f89968d5a245a693b0@76.25.183.38:30303
Record has sequence number 3 and 6 key/value pairs.
  "eth"       cac984c25efa5c83441064
  "id"        "v4"
  "ip"        76.25.183.38
  "secp256k1" a1026ff032786b390dda567836c446b78f30e5544fc96d4f32d338e7b4537e7418bd
  "tcp"       30303
  "udp"       30303
```

**Comment by shemnon** [comment]
The key is the 'eth' field.  The future fork block should be null and the "eth" entry should have become `"eth"       c7c684757a1c4780`

**Comment by RatanRSur** [comment]
Ok, will take a look.

**Comment by RatanRSur** [comment]
Where do I get this `devp2p` executable you're using?

**Comment by shemnon** [comment]
geth.  `brew install ethereum`
