### ISSUE TITLE
Nonce of private transaction not incrementing when private transaction reverts

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#1942]
[Raised in RocketChat](https://chat.hyperledger.org/channel/besu?msg=3gsQR3svKFEp5gq4i):

Hi community,
We have noticed that if a private tx reverts (e.g, when a require condition fails), then the private nonce is not incremented. On the other hand, the public nonce, that of the privacy marker tx, do increment. So my question is: ¿is there any way to change this behaviour, allowing the private nonce to increment? We have found this situation problematic when leading with concurrent private tx, because if tx n fails, then n+1, n+2, etc will also fail.
Thank you very much in advance community! 

- [x] Confirm behaviour is inconsistent with public transaction behaviour 
- [ ] Document current behaviour as a known issue
- [ ] (longer term) If yes, fix.  Fix will require a CLI option or preferably something better (something in the database possibly) to not break backwards compatibility.  -> this might be support for forks in privacy - and this is also a way to deprecate privacy methods in future

**Comment by vmichalik** [comment]
@pinges what is this blocked by? or does it just need to be re-prioritised?

**Comment by vmichalik** [comment]
Need to determine if this would break existing users' workflows

**Comment by sirano11** [comment]
Hi, @vmichalik @pinges 
Can you tell me if this behavior is intended or not? If this is a bug, can you tell me if there are any plans to fix it?

**Comment by non-fungible-nelson** [comment]
@macfarla - stale? can i close?

**Comment by macfarla** [comment]
@antonydenyer any update on your draft PR?

**Comment by antonydenyer** [comment]
Yes, still in progress. Couple things to consider around 'transitions/forks' with existing networks.
