### ISSUE TITLE
graphql: conditions for exceptions

### ISSUE THREAD

**Issue by renaynay** [hyperledger/besu#1946]
Opening this issue to discuss when an error should be returned for graphql request. Geth only returns errors if the execution of the graphql request fails, but still returns 200 if the request was valid, but the information queried for doesn't exist. For example, [this test case](https://github.com/ethereum/hive/blob/master/simulators/ethereum/graphql/testcases/10_eth_getBalance_invalidAccountLatest.json) attempts to query for the balance of an invalid account address. Geth returns a 0 balance because geth assumes every address exists on ethereum, just with a 0 balance, so geth returns: 

```
{
     "data": {
       "block": {
         "account": {
           "balance": "0x0"
         }
       }
     }
 }
```
with a 200 status code. 

Geth and Besu shouldn't really return two different responses for such a query. Would it be possible to remove the account does not exist exception in Besu? 

cc @atoulme

**Comment by atoulme** [comment]
That sounds like a simple fix I can look after.
