### ISSUE TITLE
Run GoQuorum privacy ATs (basic mode only) with Besu node in GoQuorum mode

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#1956]
- [ ] Run GoQuorum privacy ATs (basic mode only) with Besu node in GoQuorum mode.
- [ ] Fix any issues identified by running the GoQuorum privacy ATs (basic mode only) -> may require separate issues to be raised
- [ ] Have a Besu node in GoQuorum mode running the GoQuorum privacy ATs (basic mode only) as part of GoQuorum's CI workflow

**Comment by ricardolyn** [comment]
PR with Terraform resources for Besu + Tessera + EthSigner network: https://github.com/ConsenSys/quorum-acceptance-tests/pull/86

**Comment by ricardolyn** [comment]
@MadelineMurray when you mention Basic tests, what you had in mind? as some basic tests from GoQ AT are more specific for GoQ itself (like raft, etc).

**Comment by ricardolyn** [comment]
cc @pinges @macfarla @mark-terry

**Comment by macfarla** [comment]
@ricardolyn Basic mode means don't use the privacy enhancements (counter party protection & private state validation)

**Comment by ricardolyn** [comment]
ok, thanks. as in the context of the GoQ AT, they have actually a name for `basic` tests and includes other features that won't be supported by Besu (like RAFT). it might be good to review what is actually implemented and check which ones don't make sense for Besu.

**Comment by ricardolyn** [comment]
PR for Besu with Quorum Acceptance Tests - https://github.com/hyperledger/besu/pull/2122
