### ISSUE TITLE
besu incorrectly reports transaction receipt via graphql

### ISSUE THREAD

**Issue by renaynay** [hyperledger/besu#1958]
The following [testcase](https://github.com/ethereum/hive/blob/master/simulators/ethereum/graphql/testcases/33_eth_getTransactionReceipt.json) in Hive expects a null value for the `createdContract` field in the response, but geth reports the following for this testcase: 

```
      "createdContract": {
        "address": "0x6295ee1b4f6dd65047762f924ecd367c17eabf8f"
      },
```

Indeed, when initializing a geth node with the given genesis file for the graphql test suite and importing the given blocks, geth reports the above address for the `createdContract` field.

Could this potentially be a bug in Besu?

**Comment by atoulme** [comment]
Confirmed, it's a bug. Taking this one.
