### ISSUE TITLE
An API that enables point-to-point communication between two dapp nodes

### ISSUE THREAD

**Issue by rampatra** [hyperledger/besu#1964]
### Description
_This issue/ticket was inspired by a discussion on the official hyperledger rocket chat._

An API of some sorts that allows different application nodes to communicate with each other off-chain. The messaging is between the app nodes and not besu nodes (although the messages can travel via besu nodes if needed).

The messages can be simple with json payloads for example. It may or may not be encrypted. Point-to-point. Http/tcp would be fine as the messages won't be continuous like chat but a one-off.

For example, let's say, I have 2 application nodes named, **x** and **y** connected to 2 separate besu nodes. I just want to make a simple http/tcp call from "x" saying send message "abc" to "y" and that should be it. I shouldn't care about node discovery and the address conversion from "y" to its IP address etc. should be handled by the API.

As Besu already does some sort of private messaging via Orion to support its Private Transaction feature, I was wondering if I could use the same API or extend it for my usecase.

**Comment by RatanRSur** [comment]
Closing for now because, at first glance, I don't think this functionality should sit at the level of a blockchain client. If you can explain more about your use case, I can reopen it if it makes sense.
