### ISSUE TITLE
Disable sending of non eip155 replay protected tx by default

### ISSUE THREAD

**Issue by renaynay** [hyperledger/besu#1975]
Geth recently implemented this change here: https://github.com/ethereum/go-ethereum/pull/22339. It would be nice if Besu would also disable sending of non EIP155 transactions by default (see reasoning in linked PR).

**Comment by atoulme** [comment]
Thanks Rene for the report. I believe this is a straightforward change and should be implemented by Besu as well. We can adopt a flag like Geth did to allow non EIP155 transactions, but by default they should be forbidden.
