### ISSUE TITLE
Ensure we have an updated Berlin-compatible release 

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#1982]
On AllCoreDevs today, it was agreed to remove EIP-2315 from the Berlin network upgrade and keep all the fork blocks as-is. 

We should re-release Besu with the updated set of EIPs, and update the release notes from the previous release making it clear the blocks there are invalid and that it should not be used.

**Comment by winsvega** [comment]
I heard that besu is going to implement transition tool protocol for test generation.
If so I can use that to watch tests on http://retesteth.ethdevops.io/

is test RPC still supported by besu?
