### ISSUE TITLE
Transactions don’t leave the mempool

### ISSUE THREAD

**Issue by wetryingtodorock** [hyperledger/besu#1993]
Hey there!

We detected that sometimes transactions hang in the mempool for quite a long time, often they do not leave at all. We set the commission slightly higher than the recommended one.

**Comment by atoulme** [comment]
Can you clarify, are you running a private or public node? What type of consensus? Do you have gas enabled?

**Comment by wetryingtodorock** [comment]
Here are our settings 

```
BESU_NETWORK=mainnet
BESU_SYNC_MODE=FAST
BESU_PRUNING_BLOCKS_RETAINED=2000000
BESU_RPC_HTTP_ENABLED=true
BESU_RPC_HTTP_API=ETH,NET,WEB3,TRACE,TXPOOL
BESU_RPC_WS_ENABLED=true
BESU_RPC_WS_API=ETH,NET,WEB3,TRACE,TXPOOL
BESU_HOST_ALLOWLIST=*
BESU_TX_POOL_RETENTION_HOURS=13
BESU_TX_POOL_MAX_SIZE=16000
BESU_TX_POOL_HASHES_MAX_SIZE=16000
```

**Comment by RatanRSur** [comment]
possibly related to #1891

**Comment by RatanRSur** [comment]
What's the output of `curl -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"txpool_besuTransactions\", \"id\":1}" localhost:8545` ?

**Comment by wetryingtodorock** [comment]
Here are some of them, or you want us to send you all transactions?

{```

  "jsonrpc" : "2.0",
  "id" : "blockNumber",
  "result" : [ {
    "hash" : "0x373a2a94bb993ec04d6b1bd6f8dc18ba69da94567ae8922e449a9879c6a1724e",
    "isReceivedFromLocalSource" : false,
    "addedToPoolAt" : "2021-03-10T09:03:27.235134Z"
  }, {
    "hash" : "0xd9f66f6e2710fadee8b5003fe0cf631edf7dcf79206ef2386e0a85bc13fabec4",
    "isReceivedFromLocalSource" : false,
    "addedToPoolAt" : "2021-03-10T14:02:15.231748Z"
  }, {
    "hash" : "0x6e06afe8aafa16a1a4e538fd2ca4975472031505cc5e12dcdae041855c86175f",
    "isReceivedFromLocalSource" : false,
    "addedToPoolAt" : "2021-03-10T02:16:37.623539Z"
  }, {
    "hash" : "0xfb5025e30a62249e726f3328700e984a2ab1407705c172c11d7792b30d2e9476",
    "isReceivedFromLocalSource" : false,
    "addedToPoolAt" : "2021-03-10T12:49:30.908772Z"
  }, {
    "hash" : "0x23fff80b68d7f422252e46f9f5a5cac34e19bb5b1788756eacd5a993fa99830f",
    "isReceivedFromLocalSource" : false,
    "addedToPoolAt" : "2021-03-10T13:28:35.655951Z"
  }, {
    "hash" : "0xc9802512660f3d3a25b1c7f95ba0eca9ded2ff50a9fc0b3fac8630b6f26063c9",
    "isReceivedFromLocalSource" : false,
    "addedToPoolAt" : "2021-03-10T05:35:46.596460Z"
  },
```

**Comment by RatanRSur** [comment]
If possible, yes, all of them. I'll need to sort them by the time they were added to the pool.

**Comment by wetryingtodorock** [comment]
[txs.txt](https://github.com/hyperledger/besu/files/6116474/txs.txt)

**Comment by wetryingtodorock** [comment]
@RatanRSur 
Also, currently, we have a problem with this transaction: `0x1223005d1348adb030fa4e8b4a1cdade3e321ba758c02b503409cfc8fb83997b`
It is in our mempool, but it’s not broadcasted.

**Comment by RatanRSur** [comment]
@abdelhamidbakhta to provide stress test tool

**Comment by abdelhamidbakhta** [comment]
https://github.com/ConsenSys/eip1559-tx-sender

**Comment by sajz** [comment]
we have made changes in the tx pool, can you let us know if you still have this problem with the most recent version.

**Comment by vmichalik** [comment]
cc @wetryingtodorock can you confirm if the latest updates have solved your issue?

**Comment by vmichalik** [comment]
Hey @wetryingtodorock, closing this issue for now but please reopen if you see it reappear!
