### ISSUE TITLE
Optional flag to prevent evmtool from shutting down

### ISSUE THREAD

**Issue by MariusVanDerWijden** [hyperledger/besu#1995]
In https://github.com/hyperledger/besu/issues/1470 an optional mode was introduced that allowed us to pipe in multiple tests over the stdin pipe. 
Currently a lot of time during fuzzing is spent on setting up the JRE.
Having an optional flag (--keep or --pipemode or something) would enable us to spin up a besu instance and send state tests to it. This would greatly reduce the overhead of fuzzing.

**Comment by jflo** [comment]
Where can i find details on how this fuzzing happens, and how it interacts with besu via the command line?

**Comment by MariusVanDerWijden** [comment]
This already works :see_no_evil: There was a tiny bug that was fixed some time ago

**Comment by MariusVanDerWijden** [comment]
Re fuzzing: This is how we interact with besu: https://github.com/holiman/goevmlab/blob/master/evms/besubatcher.go
