### ISSUE TITLE
Flaky Test - PrivDebugGetStateRootOnchainGroupAcceptanceTest.blockParamShouldBeApplied

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#2068]
This test has failed twice this week. This is the latest one:

https://app.circleci.com/pipelines/github/hyperledger/besu/7942/workflows/4b1602b0-a19f-430a-aa73-b20b7e1f7d1b/jobs/40011

**Comment by macfarla** [comment]
happened again yesterday

**Comment by macfarla** [comment]
So running this test locally it is failing 20-30% of the time
