### ISSUE TITLE
Investigate a nicer mechanism for the privacy mode flags

### ISSUE THREAD

**Issue by mark-terry** [hyperledger/besu#2070]
### Description
The way we enable different privacy modes could be improved.

- [x] Define the current flags and their compatibility to enable this discussion
- [x] check with Antony and Lucas whether their work involves any privacy related CLI options
- [ ] come up with a proposal for consolidating the current options
- [ ] estimate of how much work is involved - is it limited to the PrivacyParameters object
- [ ] are any of the modes compatible with each other (do we need to be able to select multiple options)

### Acceptance Criteria
An improved privacy mode selection option that correctly enables the selected mode.

**Comment by vmichalik** [comment]
--privacy-mode="dual-state" or --privacy-mode="groups" might be nice

**Comment by macfarla** [comment]
MVP is to rename the --goquorum-compatibility-enabled - can we decide on a name that is client agnostic
