### ISSUE TITLE
web3j version update

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2098]
The version of web3j that the ATs use is old. However updating it to latest (4.8.4) broke some ATs:

https://app.circleci.com/pipelines/github/hyperledger/besu/8042/workflows/f87fc4e8-7e94-4cdd-b16f-641c2b737bb3/jobs/40545 

I tried 4.6.0 and the rlp test passed but the other 3 still fail with the same errors. This requires some investigation.
https://github.com/web3j/web3j/releases

**Comment by vmichalik** [comment]
It doesn't look like these are still failing - did we fix the problem?

**Comment by macfarla** [comment]
maybe it needs to line up with web3js quorum?

**Comment by antonydenyer** [comment]
Hopefully updated correctly https://github.com/hyperledger/besu/pull/2616 the tests were failing because the behaviour has changed in web3j to throw a `TransactionException` when `(!receipt.isStatusOK())`
