### ISSUE TITLE
Investigate the need for transaction boundary marking in tracing.

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#2124]
Our recent bug in tracing had to do with there not being transaction boundaries marked in the debug-style traces, while we had them in the trace-style traces. Investigate if there's a more elegant way to use the `updater`s so we don't have to do this.

**Comment by non-fungible-nelson** [comment]
@daniellehrner - stale in latest tracer? Can we close?

**Comment by daniellehrner** [comment]
> @daniellehrner - stale in latest tracer? Can we close?

Yes, I think we can close this one.
