### ISSUE TITLE
Ropsten consensus issue (bonsai trie) on block 10 065 036

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#2157]
There is a consensus issue on block 10 065 036

World State Root does not match expected value, header 0x24ba83bdd61899b202536747143e416024d6f370811277e879c8887c2dd813d9 calculated 0x9b25038b5d0d61f9d0bcd3dddf70b3739534e8be1fbb95d4abcfb2a9004a75bd
	at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.persist(BonsaiPersistedWorldState.java:252)
	at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:208)
	at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:44)
	at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:75)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:150)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:108)
	at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:45)
	at org.hyperledger.besu.chainimport.RlpBlockImporter.evaluateBlock(RlpBlockImporter.java:212)
	at org.hyperledger.besu.chainimport.RlpBlockImporter.lambda$importBlockchain$3(RlpBlockImporter.java:150)
	at java.base/java.util.concurrent.CompletableFuture.biRun(CompletableFuture.java:1375)
	

there doesn't seem to be a problem by looking at the diff file (SSTORE and CALL seems to be a known tracing bugs)
[diff.txt](https://github.com/hyperledger/besu/files/6336686/diff.txt)

I also checked the storageRoot and the codeHash of each account updated in the block and every thing seems to be fine
[account-updated.txt](https://github.com/hyperledger/besu/files/6336767/account-updated.txt)

**Comment by shemnon** [comment]
What about the last segment in the diff, the top charges 2800 more gas before stopping, exactly on 0 gas at the last evm operation.  Is the top/left forest mode?

```
412504,412509c412504,412509
< {"pc":9895,"op":85,"gas":"0xb61","gasCost":"0x64","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xa"],"returnData":null,"depth":1,"refund":0,"opName":"SSTORE","error":""}
< {"pc":9896,"op":80,"gas":"0xafd","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
< {"pc":9897,"op":80,"gas":"0xafb","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
< {"pc":9898,"op":86,"gas":"0xaf9","gasCost":"0x8","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04"],"returnData":null,"depth":1,"refund":0,"opName":"JUMP","error":""}
< {"pc":3332,"op":91,"gas":"0xaf1","gasCost":"0x1","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"JUMPDEST","error":""}
< {"pc":3333,"op":0,"gas":"0xaf0","gasCost":"0x0","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"STOP","error":""}
---
> {"pc":9895,"op":85,"gas":"0xb61","gasCost":"0xb54","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xa"],"returnData":null,"depth":1,"refund":0,"opName":"SSTORE","error":""}
> {"pc":9896,"op":80,"gas":"0xd","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
> {"pc":9897,"op":80,"gas":"0xb","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
> {"pc":9898,"op":86,"gas":"0x9","gasCost":"0x8","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04"],"returnData":null,"depth":1,"refund":0,"opName":"JUMP","error":""}
> {"pc":3332,"op":91,"gas":"0x1","gasCost":"0x1","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"JUMPDEST","error":""}
> {"pc":3333,"op":0,"gas":"0x0","gasCost":"0x0","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"STOP","error":""}
```

**Comment by matkt** [comment]
> What about the last segment in the diff, the top charges 2800 more gas before stopping, exactly on 0 gas at the last evm operation. Is the top/left forest mode?
> 
> ```
> 412504,412509c412504,412509
> < {"pc":9895,"op":85,"gas":"0xb61","gasCost":"0x64","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xa"],"returnData":null,"depth":1,"refund":0,"opName":"SSTORE","error":""}
> < {"pc":9896,"op":80,"gas":"0xafd","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
> < {"pc":9897,"op":80,"gas":"0xafb","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
> < {"pc":9898,"op":86,"gas":"0xaf9","gasCost":"0x8","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04"],"returnData":null,"depth":1,"refund":0,"opName":"JUMP","error":""}
> < {"pc":3332,"op":91,"gas":"0xaf1","gasCost":"0x1","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"JUMPDEST","error":""}
> < {"pc":3333,"op":0,"gas":"0xaf0","gasCost":"0x0","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"STOP","error":""}
> ---
> > {"pc":9895,"op":85,"gas":"0xb61","gasCost":"0xb54","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xa"],"returnData":null,"depth":1,"refund":0,"opName":"SSTORE","error":""}
> > {"pc":9896,"op":80,"gas":"0xd","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
> > {"pc":9897,"op":80,"gas":"0xb","gasCost":"0x2","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04","0xfb4384bc0b9246adb3897a059ac02bb79bbf00a1"],"returnData":null,"depth":1,"refund":0,"opName":"POP","error":""}
> > {"pc":9898,"op":86,"gas":"0x9","gasCost":"0x8","memory":"0x","memSize":96,"stack":["0xd4d883bd","0xd04"],"returnData":null,"depth":1,"refund":0,"opName":"JUMP","error":""}
> > {"pc":3332,"op":91,"gas":"0x1","gasCost":"0x1","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"JUMPDEST","error":""}
> > {"pc":3333,"op":0,"gas":"0x0","gasCost":"0x0","memory":"0x","memSize":96,"stack":["0xd4d883bd"],"returnData":null,"depth":1,"refund":0,"opName":"STOP","error":""}
> ```

The top it's the bonsai node.

I tried to investigate this part but I realized that the difference comes from the fact that in bonsai the original is at 0x during the sstore and not in forest. I have that you said it was a known bug so I did not dig this part
