### ISSUE TITLE
Investigate the performance regression issue

### ISSUE THREAD

**Issue by abdelhamidbakhta** [hyperledger/besu#2173]
### Description

We did some ethspam benchmark. The result looks the same with or without Bonsai. Bonsai it doesn’t seem to impact performance. What is disturbing is that the performance even in forest seems no good comparing the last ones realized on version 1.5.0

We may have to investigate this

- Result with 1.5.0

https://www.hyperledger.org/blog/2020/08/06/hyperledger-besu-1-5-performance-enhancements 

- Result with 21.1.5-SNAPSHOT

>AWS : i3.xlarge (4CPU)
>
>JVM  : 
>
>openjdk version "11.0.10" 2021-01-19 LTS
>OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
>OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

With Bonsai trie (100k)

>Endpoints:
>
>0. "http://localhost:8545"
>
>   Requests:   3773.12 per second
>   Timing:     0.0011s avg, 0.0004s min, 0.1626s max
>               0.0026s standard deviation
>
>   Percentiles:
>     25% in 0.0008s
>     50% in 0.0009s
>     75% in 0.0011s
>     90% in 0.0014s
>     95% in 0.0017s
>     99% in 0.0030s

>   Errors: 0.00%

>** Summary for 1 endpoints:
>   Completed:  100000 results with 100000 total requests
>   Timing:     1.060129ms request avg, 26.870479187s total run time
>   Errors:     0 (0.00%)
>   Mismatched: 0

With Forest (100k) :

>Endpoints:
>
>0. "http://localhost:8545"
>
>   Requests:   3648.84 per second
>   Timing:     0.0011s avg, 0.0004s min, 0.0293s max
>               0.0007s standard deviation
>
>   Percentiles:
>     25% in 0.0008s
>     50% in 0.0010s
>     75% in 0.0012s
>     90% in 0.0016s
>     95% in 0.0019s
>     99% in 0.0032s
>
>   Errors: 0.00%

>** Summary for 1 endpoints:
>   Completed:  100000 results with 100000 total requests
>   Timing:     1.096239ms request avg, 27.782420814s total run time
>   Errors:     0 (0.00%)
>   Mismatched: 0

**Comment by matt-nelson-csi** [comment]
Closing as stale.
