### ISSUE TITLE
Unit tests fail if system language is not English

### ISSUE THREAD

**Issue by daniel-iobuilders** [hyperledger/besu#2190]
### Description
The tests `BesuCommandTest.privEnclaveKeyFileDoesNotExist` and `NetworkingServiceLifecycleTest.startDiscoveryPortInUse` fail if the system language of the operating system is another language than English. In `BesuCommandTest.privEnclaveKeyFileDoesNotExist` the test looks like this:

```
@Test
public void privEnclaveKeyFileDoesNotExist() {
  parseCommand("--privacy-enabled=true", "--privacy-public-key-file", "/non/existent/file");

  assertThat(commandOutput.toString()).isEmpty();
  assertThat(commandErrorOutput.toString()).startsWith("Problem with privacy-public-key-file");
  assertThat(commandErrorOutput.toString()).contains("No such file");
}
```

The last assertion is the one that is failing. `No such file` is the error message coming directly from `IOException` when the file is not found. But the error messages of the exceptions thrown by the Java library are translated according to the system language. For example when the system language is set to Spanish the error looks like this:

```
Problem with privacy-public-key-file: /non/existent/file (No existe el archivo o el directorio)
```

In this case `No such file` is not part of the output string and the assertion fails.

 `NetworkingServiceLifecycleTest.startDiscoveryPortInUse`  fails for the same reason:
 
 ```
catch (final Exception e) {
          assertThat(e).hasCauseExactlyInstanceOf(PeerDiscoveryServiceException.class);
          assertThat(e)
              .hasMessageStartingWith(
                  "org.hyperledger.besu.ethereum.p2p.discovery."
                      + "PeerDiscoveryServiceException: Failed to bind Ethereum UDP discovery listener to 0.0.0.0:");

          assumeThat(System.getProperty("user.language")).isEqualTo("en");
          assertThat(e).hasMessageContaining("Address already in use");
        } 
```

Here again the last assertion fails, because it comes directly from an exception thrown by the Java library.

### Expected behavior
The tests should either be successful or be skipped.

### Possible solution
The tests could be skipped using [AssertJ Assume](https://assertj.github.io/doc/#assertj-core-assumptions) and testing if the system language is English or not. Like that they would not fail for developers with another system language. But they would still be executed in the CI / CD pipeline, to verify that the tested behavior has not been changed.

### Steps to Reproduce (Bug)
1. Checkout `master` branch
2. Change system language to any other than English
3. Execute `./gradlew build`

**Comment by geekcharming** [comment]
I would like to work on this issue

**Comment by jflo** [comment]
Is the localized message from the OS, or from the underlying JRE? @daniel-iobuilders was this test run with an internationalized JRE by any chance?

**Comment by daniel-iobuilders** [comment]
The setup was:
OS: Ubuntu 20.04
JDK: [openjdk-11](https://packages.ubuntu.com/focal/openjdk-11-jdk)

I looked for it, but I cannot find the information if this version of Java is internationalized or not.

**Comment by macfarla** [comment]
👋  Hi @geekcharming are you still interested in working on this?
