### ISSUE TITLE
Flaky test : containerTests

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#2194]
Flaky tests with containerTests:
- contractShouldBeDeployedOnlyToBesuNode
- contractShouldBeDeployedToBothNodes
https://app.circleci.com/pipelines/github/hyperledger/besu/8463/workflows/012a2d1a-589c-4b3e-a4f2-1595b1fa9e2f/jobs/43122

**Comment by macfarla** [comment]
PR to remove the container-test build step: https://github.com/hyperledger/besu/pull/2196
