### ISSUE TITLE
Unable to build on `openjdk:jdk-slim-buster`

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#2195]
### Description

Building on `openjdk:jdk-slim-buster` fails with error `General error during semantic analysis: Unsupported class file major version 60`, see more logs below. This is identical to `openjdk:16-jdk-slim-buster`.

Building on `openjdk:14-jdk-slim-buster` succeeds, as does building on `openjdk:15-jdk-slim-buster`.

Tested on `master` as of 04-27-2021

```
Welcome to Gradle 6.8.3!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Settings file '/usr/src/besu/settings.gradle'

* What went wrong:
Could not compile settings file '/usr/src/besu/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60

  java.lang.IllegalArgumentException: Unsupported class file major version 60
```

**Comment by atoulme** [comment]
JDK 16 is not supported, try JDK 14 instead.

**Comment by meowsbits** [comment]
It would be nice to have this in the [Build From Source docs](https://wiki.hyperledger.org/display/BESU/Building+from+source).
