### ISSUE TITLE
Docker hub `latest` not updated

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#2212]
I am getting a lot of https://github.com/hyperledger/besu/issues/2142 on the node we run, off docker, even after updating the docker image. 
However, it seems that `hyperledger/besu:latest` has not been pushed along with the others, being `12` days while some are only `4` days old.  

![Screenshot_2021-05-03 hyperledger besu Tags](https://user-images.githubusercontent.com/142290/116848759-97f5cf80-abed-11eb-8a8d-01155daccc09.png)

**Comment by yorickdowne** [comment]
`latest` is the last release. 21.1.5 in this case, 12 days ago. The other two images are dev snapshots off  the `master` code branch. Looks like it's working as designed.

**Comment by ajsutton** [comment]
I suspect the confusion here is that there is `latest` besu and `openjdk-latest` referring to the jvm.  So `develop-openjdk-latest` is the `develop` version of besu (tip of master branch) running on the latest release of openjdk (`openjdk-latest`).

It looks like this particular fix hasn't made it into a release yet.

**Comment by holiman** [comment]
I see - yes, that did confuse me. I would have assumed `stable` to be the latest release, and `latest` to be the most recent commit on `master`. Thanks, guess I'm closing this then
