### ISSUE TITLE
Wrong chainId

### ISSUE THREAD

**Issue by Iffay3020** [hyperledger/besu#2246]
### Description
Want to deploy smart contracts with truffle in my hyperledger besu Blockchain
But I don't know why I get the message when I'm trying to migrate my contract "Wrong chainId"

### Steps to Reproduce (Bug)
1. Create a Blockchain as described here: https://besu.hyperledger.org/en/stable/Tutorials/Examples/Private-Network-Example/
2. Install Truffle on my computer with npm
3. Migrate my smart contract to my Blockchain Network as described here: https://besu.hyperledger.org/en/stable/HowTo/Develop-Dapps/Truffle/ 

**Expected behavior:**
Smart contract should migrate to the blockchain 

**Actual behavior:**
initial migration fails
Starting migrations...

> Network name:    'besuWallet'
> Network id:      1337
> Block gas limit: 16234336 (0xf7b760)

1_initial_migration.js

   Deploying 'Migrations'
  

Error:  *** Deployment Failed ***

"Migrations" -- Wrong chainId.

    at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:365:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration._deploy ....
Truffle v5.3.4 (core: 5.3.4)
Node v14.16.1

**Frequency:** 
each time I try to migrate

**Comment by joshuafernandes** [comment]
Hi @Iffay3020 ,
Could you try the migrate with v1.2.6 of the hdwallet-provider please and see how that goes? ChainId of 1337 is fine

I've locked the quorum-dev-quickstart to the version above while I raise a ticket with Truffle to look into this.
https://github.com/ConsenSys/quorum-dev-quickstart/pull/62/files#diff-a9a380a627b408eb13216f7d813d99cdd45d8000debc25cf524e751b2df4832fL15

Cheers
Josh

**Comment by vmichalik** [comment]
Seems like this is fixed in the latest truffle releases per our testing, so I'm going to close this for now but please reopen or create a new issue if you experience further problems @Iffay3020
