### ISSUE TITLE
Unable to read genesis file for GoQuorum options

### ISSUE THREAD

**Issue by brothereum** [hyperledger/besu#2316]
### Description
When I run the code in linux
`besu --data-path=data --genesis-file=../cliqueGenesis.json --network-id 108801 --rpc-http-enabled --rpc-http-api=ETH,NET,CLIQUE --host-allowlist="*" --rpc-http-cors-origins="all"`
it shows the error

```
Unable to read genesis file for GoQuorum options

To display full help:
besu [COMMAND] --help
```

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. Extract besu from latest binary release tar.gz
2. put in to the PATH
3. Generate cliqueGenesis.json as shown in [Link](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-Private-Clique-Network/)
4. Run for node-1

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`] `besu/v21.1.6/linux-x86_64/oracle-java-16`
* Java version: [`java -version`] ```
 java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
* OS Name & Version: [`cat /etc/*release`]
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
* Kernel Version: [`uname -a`] `Linux node-linux 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Additional Information

**Comment by vmichalik** [comment]
Thanks @brothereum - taking a look

**Comment by macfarla** [comment]
ok I just did a test and you get this error if the specified genesis file does not exist.

we should fix this message in besu (different msg if file doesn't exist) - but in the meantime the workaround is to check that they specified genesis file exists

**Comment by macfarla** [comment]
```
besu --genesis-file=xyz.json
Unable to read genesis file for GoQuorum options

To display full help:
besu [COMMAND] --help
```

**Comment by macfarla** [comment]
This error should be fixed now in master @brothereum - thanks for reporting!

**Comment by brothereum** [comment]
@vmichalik @macfarla thank you, i will try installing from main branch
