### ISSUE TITLE
Allowlist/Rejectlist of IPs on stratum port

### ISSUE THREAD

**Issue by atoulme** [hyperledger/besu#2326]
### Description
As an operator, I want to maintain IP ranges that I explicitly allow or reject from participating in connecting to the stratum port.

### Acceptance Criteria
* A series of configuration entries, CLI flags and environment variables, using the approach taken by Besu to manage its configuration, allows operators to enter allowlist and rejectlist ranges of validated IPs into Besu.
* The values are used to block or accept miners.

**Comment by non-fungible-nelson** [comment]
@diega @atoulme  - still needed in PoW?

**Comment by diega** [comment]
This is not a requirement that we currently have, but I think this is a nice feature and probably a fair candidate for `good-first-issue`. I would keep this open even unnasigned.

**Comment by non-fungible-nelson** [comment]
Ok to re-open if someone picks up the work.
