### ISSUE TITLE
Stratum miner rewards

### ISSUE THREAD

**Issue by atoulme** [hyperledger/besu#2331]
### Description
As an operator, I want to keep tabs on which miners sent me solutions, so I may reward them.

### Acceptance Criteria
* Implement an optional configuration flag to allow to register miners with a persistent store.
* The persistent store should record miners identities taken after their username as their address.
* The persistent store should track solutions sent by miners over time.
* Besu should be able to calculate according to 2 different schemes:
** Pay-per-share: every time a miner sends a valid share, it is added to the rewards.
** Pay-per-block: every time a block is submitted and becomes part of the canonical chain thanks to a solution provided by a miner, they get a reward. A smaller reward goes to solutions associated with ommers.

**Comment by macfarla** [comment]
PoW is now deprecated so we won't be adding features to it
