### ISSUE TITLE
Make transaction pool size configurable

### ISSUE THREAD

**Issue by sajz** [hyperledger/besu#2348]
@garyschulte to add details

**Comment by jflo** [comment]
Current list of things that are configurable about the Transaction [can be found here](https://github.com/hyperledger/besu/blob/d4a330b81e5ad63a4b220a4f2c4f0e82682af104/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolConfiguration.java#L26), and it seems max size (in transactions) is already configurable with a default of 4K.

I'm guessing we're actually talking about a worker pool or something else?

**Comment by jflo** [comment]
--tx-pool-max-size and --tx-pool-hashes-max-size both exist and are honored via the command line and environment vars. I'll check the documentation to make sure it is captured correctly.

**Comment by jflo** [comment]
documentation and command line help both show how to set these values:

https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#tx-pool-max-size
