### ISSUE TITLE
Hash of proto-block header to block-on-chain mapping

### ISSUE THREAD

**Issue by wpwrak** [hyperledger/besu#2358]
### Description
As a miner, I want to be able to easily identify what happened with blocks I mined so that I can see what the pool is doing with them.

I mentioned this on the ETC discord, and Antoine Toulme suggested I put it on the besu issue tracker.

The general problem is as follows: a miner only sees the header-hash of the proto-block (nonce set to 0) but has no easy way to map this header-hash (let's call it the "miner's hash") to the block that may end up in the chain. The miner may also not be able to tell whether it has actually found a block or not.

To map the miner's hash to a block, the miner would have to retrieve the headers of likely candidates, calculate the corresponding miner's hash for each, until it either finds a match with the miner's hashes for which it has submitted possible solutions, or until it runs out of candidate blocks (which would mean that the block's nonce was either not good enough or that the block didn't make it to he chain for some other reason).

A more direct lookup would be nice, e.g., in the form of chain explorers offering to find blocks by their miner's hash.  I'm not sure how chain explorers are generally organized, and whether support for such a feature may be inside the scope of clients, like besu.

Being able to map miner's hashes (which the miner would have to record) to blocks would allow to track what the pool is doing with the miner's hash power, e.g., whether it is using it for objectionable activities, like running attacks against the chain/coin.

**Comment by vmichalik** [comment]
@atoulme FYI as you weren't tagged in-text!

**Comment by atoulme** [comment]
1. You could potentially use the mix hash of the block that you compute when you send the solution to see if your block makes it. You can also check block bodies to see if your mix hash is the mix hash of a block ommer.

2. If you're mining directly against the client, you might want to be able to see if the client's computed blocks become part of the canonical chain. I think that's better than adopting a solution where the miner is not trusting the client. In that case, when Besu computes a block and sends it to the network, how do we know if it becomes part of the canonical chain?

One way to do the job is to grep Besu logs for this type of log line:
```
2021-07-28 14:49:07.073-07:00 | pool-7-thread-1 | INFO  | BlockMiner | Produced #11 / 0 tx / 0 om / 0 (0.0%) gas / (0x96d26ee96f4b9766b96c6f6a9d3aa5bb14e64c3a8d164b1a0611376ebd0cd8ff) in 2.049s
```
Catch the block hash and test it against the canonical chain after a number of confirmations. This should provide you with assurance that your block was indeed accepted by the chain.

So to do this job, you will need to follow the chain entirely and index all block headers and ommer block headers. You will also need to keep track of mix hashes you compute when sending solutions. I hope that helps.

**Comment by non-fungible-nelson** [comment]
@diega @atoulme - still needed?

**Comment by atoulme** [comment]
@wpwrak, did my explanation earlier help? Do you still need this enhancement?

**Comment by macfarla** [comment]
PoW is now deprecated so we won't be adding features to it
