### ISSUE TITLE
DoS vulnerability found

### ISSUE THREAD

**Issue by mous314anony** [hyperledger/besu#2378]
I have a general question: If someone found a security bug/vulnerability on besu, should s/he report it publicly here?

**Comment by RatanRSur** [comment]
Good question, you can send it to me first on keybase: @nonveumann

**Comment by vmichalik** [comment]
In general you should follow the steps indicated in the docs here: https://besu.hyperledger.org/en/stable/Reference/Responsible-Disclosure/

**Comment by RatanRSur** [comment]
Oh, I didn't know we had that, thanks @vmichalik !
