### ISSUE TITLE
What if I find a mapping between a module under the directory "ethereum" and a Maven reference (that is, group, artifact, version)?

### ISSUE THREAD

**Issue by fenghaoming** [hyperledger/besu#2395]
The code in this project is very good in terms of modularization. I am using the module trie in my project through the convenience referenced by Maven:
        <dependency>
            <groupId>org.hyperledger.besu.internal</groupId>
            <artifactId>trie</artifactId>
            <version>20.10.4</version>
        </dependency>
        
If I want to use other modules, how should I write the POM?

What if I find a mapping between a module under the directory "ethereum" and a Maven reference (that is, group, artifact, version)?

Thank you very much!

**Comment by atoulme** [comment]
You can look here for other libraries: https://mvnrepository.com/artifact/org.hyperledger.besu.internal

That said, I have no clue what is fit for reuse in them. Like the name says, these are internal libraries.

**Comment by fenghaoming** [comment]
> You can look here for other libraries: https://mvnrepository.com/artifact/org.hyperledger.besu.internal
> 
> That said, I have no clue what is fit for reuse in them. Like the name says, these are internal libraries.

Thank you for your answer. Again, on what basis are groups and artifacts determined in pom.xml?

**Comment by atoulme** [comment]
I think you’re looking for this: https://github.com/hyperledger/besu/blob/a75301b6a97f01c7d3480f293e32bbb0d1250c70/build.gradle#L355

**Comment by RatanRSur** [comment]
Closing this here because I think a better place for this conversation would be on rocketchat in the #besu-contributers channel
