### ISSUE TITLE
General State Tests

### ISSUE THREAD

**Issue by sajz** [hyperledger/besu#2408]
Executes a single transaction in a defined environment, state transition

[GeneralStateTests](https://github.com/ethereum/tests/tree/develop/GeneralStateTests) 

Success criteria:
* 100% passing with Besu state test runner 
* 100% passing with Retesteth state test runner

**Comment by garyschulte** [comment]
* Besu test runner is passing all state tests for all forks

* Retesteth test runner needs to be updated to reflect the correct block field `baseFeePerGas` rather than `baseFee`
  * **if we revert besu BlockResult** to `baseFee` we pass all tests
