### ISSUE TITLE
Forbid transactions from externally owned accounts that have contract code deployed

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#2425]
Fixes latent security vulnerability where collision could be found between contract and EOA, allowing surreptitious fund stealing.

**Comment by matt-nelson-csi** [comment]
Geth has implemented this - need to prioritize at some point post-Merge

**Comment by non-fungible-nelson** [comment]
Need to implement as [EIP-3607](https://eips.ethereum.org/EIPS/eip-3607). Tagging again.

**Comment by non-fungible-nelson** [comment]
implemented via #2676
