### ISSUE TITLE
Switching Consensus Protocols

### ISSUE THREAD

**Issue by Viserius** [hyperledger/besu#2437]
### Description
As a user, I want to be able to switch consensus protocols so that when I build my use case around Besu using one protocol, and more efficient or robust consensus protocols are being developed, I am not locked in and can take advantage of new developments.

### Acceptance Criteria
* After a network has been created, initialized and used for some time, it should be able to change the consensus protocol to a different implementation.

### Additional Information
This is similar to the problem Ethereum has with hard forks when a new breaking update comes out (such as the Berlin update). They solve this issue by announcing the block at which the new features are enabled. Perhaps, a similar solution could work for Besu. Namely, we could announce that at block X, the consensus protocol to be used will be Clique/IBFT2 etc. Then, resyncs should still work up until that block using the old protocol, after which you switch over to the new block. Perhaps easier said than done, but maybe this could be something for future investigation.

**Comment by vmichalik** [comment]
Hi Viserius, this is something we're looking into right now as we're adding QBFT in 21.7.0, so it will absolutely be on the roadmap for the next few months. Thank you for the suggestion!

**Comment by lucassaldanha** [comment]
Hi! We have started working on IBFT2 to QBFT migration. You can keep track of the work on this ticket: https://github.com/hyperledger/besu/issues/2991

**Comment by SimowTopos** [comment]
Hi @lucassaldanha , can you please reopen this as it doesn't work due to a down casting from BftContext to QbftContext issue. Thanks a lot
