### ISSUE TITLE
Disable DNS Discovery on private custom networks by default

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu#2446]
### Description
As a private network admin, I want Besu to run with my private network config without the default DNS discovery config and have it disabled by default so that I don't have to disable it manually in options. It should only be activated by default for public networks (mainnet and testnet).
Having DNS discovery service disabled by default when DNS entrees list is empty could be enough. DEV network already has an empty list by default.
See https://github.com/hyperledger/besu/blob/9a43227587ca403cdf772874214f4514fecdd1ef/besu/src/main/java/org/hyperledger/besu/cli/config/EthNetworkConfig.java#L179

May be related to #1632

Currently, DNS Discovery can be disabled manually so this issue is not critical. But it would help.

### Acceptance Criteria
* When I run a private custom network, if I don't pass any DNS entries related option, DNS discovery should not start.

### Steps to Reproduce (Bug)
1. Start Besu with a custom genesis file.

**Expected behavior:** [What you expect to happen]

DNS discovery should not start

**Actual behavior:** [What actually happens]

DNS discovery starts and fires DNS requests to ethdisco.net ( see https://github.com/hyperledger/besu/blob/9a43227587ca403cdf772874214f4514fecdd1ef/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/DiscoveryConfiguration.java#L33 )

**Frequency:** [What percentage of the time does it occur?]

100%

### Versions (Add all that apply)
* Software version: [`besu --version`] at least 21.1.7 but probably affects all versions since DNS Discovery was added.
* Java version: [`java -version`] Not architecture specific.
* OS Name & Version: [`cat /etc/*release`] Not architecture specific.
* Kernel Version: [`uname -a`] Not architecture specific.
* Virtual Machine software & version: [`vmware -v`] Not architecture specific.
* Docker Version: [`docker version`] Not architecture specific.
* Cloud VM, type, size: [Amazon Web Services I3-large] Not architecture specific.

### Additional Information

This issue is raised after Consensys Quorum a customer question: https://consensys.zendesk.com/agent/tickets/209587

**Comment by frankisawesome** [comment]
Unable to reproduce and we have a test asserting the correct behaviour (BesuCommandTest.java:941), this should've been resolved already.
