### ISSUE TITLE
Fix docker scan vulnerabilities

### ISSUE THREAD

**Issue by jmcruz1983** [hyperledger/besu#2451]
Checking the [Dockerfile](https://github.com/hyperledger/besu/blob/master/docker/openjdk-11/Dockerfile) seems that base image `openjdk:11.0.7-jre-slim-buster` is bringing some vulnerabilities flagged by some image scanning tools like snyk or harbor.

To get list of vulnerabilities you can run following command:

```
 docker scan -f docker/openjdk-11/Dockerfile hyperledger/besu:develop-openjdk-11 --severity high
```

Producing following output:
```
Tested 91 dependencies for known issues, found 21 issues.

Base Image                      Vulnerabilities  Severity
openjdk:11.0.7-jre-slim-buster  77               21 high, 13 medium, 43 low
```

In addition some alternative base images are recommended:

```
Recommendations for base image upgrade:

Alternative image types
Base Image                         Vulnerabilities  Severity
openjdk:16-ea-29-jdk-oraclelinux8  0                0 high, 0 medium, 0 low
openjdk:17-ea-6-jdk                0                0 high, 0 medium, 0 low
openjdk:16-ea-oracle               0                0 high, 0 medium, 0 low
openjdk:16-ea-15-jdk-oraclelinux8  0                0 high, 0 medium, 0 low
```

It is not critical but some private docker registry won't allow to pull such images with high severity vulnerabilities.

**Comment by vmichalik** [comment]
Closed by #2452
