### ISSUE TITLE
BESU_CONFIG_FILE environment variable does not work

### ISSUE THREAD

**Issue by soulman-is-good** [hyperledger/besu#2455]
### Description
[Docs says](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#config-file) that as a user I should be able to specify configuration file via environment variable `BESU_CONFIG_FILE`, but looks like I can't: https://github.com/hyperledger/besu/blob/master/besu/src/main/java/org/hyperledger/besu/cli/util/ConfigOptionSearchAndRunHandler.java#L64

I had PR to update docs, but it was closed.
https://github.com/hyperledger/besu-docs/pull/740

### Acceptance Criteria
* Either docs updated
* Or Code updated

### Steps to Reproduce (Bug)
1. Download any version of besu
2. Create basic config.toml file, let's say with rpc enabled on non default port (e.g. 8555 - make sure it's free)
3. Run `BESU_CONFIG_FILE=/path/to/config.toml besu`
4. Check the logs, it should not state anywhere that RPC server is running
5. Try `BESU_CONFIG_FILE=/path/to/config.toml besu --rpc-http-enabled`
6. Make sure that port didn't change from default `8545`
7. Exit the running besu process
8. Try running `besu --config-file=/path/to/config.toml`
9. Make sure rpc server started on specified port (e.g. 8555)

**Expected behavior:** Config file can be specified from environment variable as docs says

**Actual behavior:** Can't specify path to config file via environment variable `BESU_CONFIG_FILE` as the docs says.

**Frequency:** 100% of time. It's misdocumented feature IMHO.

### Versions (Add all that apply)
* Software version: any
* Java version: openjdk 11.0.2
* OS Name & Version: Debian Linux 9
* Kernel Version: 3.10.0
* Virtual Machine software & version: -
* Docker Version: 1.13.1
* Cloud VM, type, size: -

**Comment by RatanRSur** [comment]
Hey @soulman-is-good ! Thanks for reporting. This should be supported; we'll triage your issue. In the meantime, is using the command line flag a possible workaround? If not, what's your use-case that you need to use the env var?

**Comment by soulman-is-good** [comment]
Hi @RatanRSur , thanks for picking it up.
It is ok for us to use command line argument as a workaround for now.

**Comment by antonydenyer** [comment]
This is the likely culprit. 

https://github.com/hyperledger/besu/blob/main/besu/src/main/java/org/hyperledger/besu/cli/util/ConfigOptionSearchAndRunHandler.java#L61

You can see that Besu only looks to `--config-file` it needs to also look at the environment variable `BESU_CONFIG_FILE`
