### ISSUE TITLE
Cannot connect to the Rinkeby Testnet using docker command

### ISSUE THREAD

**Issue by asharoo1** [hyperledger/besu#2460]
### Description
I'm unable to connect a node onto the rinkeby testnet using the following command:
`sudo docker run -p 30303:30303 --mount type=bind,source=/home/ubuntu/rinkbeyvol/besu/rinkeby,target=/var/lib/besu hyperledger/besu:latest --network=rinkeby --data-path=/var/lib/besu`

### Error Log
![image](https://user-images.githubusercontent.com/84122970/122881759-20c0fa00-d359-11eb-9122-2a6ccbec0629.png)

### Versions (Add all that apply)

* Docker Version: [` 20.10.2`]

**Comment by vmichalik** [comment]
Hi @asharoo1, thanks for raising the issue! What version of Besu are you running?
Also, could you let us know which Java version you're using too?

**Comment by garyschulte** [comment]
Hi @asharoo1 , the error you posted isn't actually a terminal error.  It looks like it is critical, but it is something that happens often due to a variety of sources such as networks scanners.  In the latest release [21.7.0-RC2](https://github.com/hyperledger/besu/releases/tag/21.7.0-RC2) we have dropped the log level for this to `DEBUG`, and dropped the stack trace to `TRACE`.  

Try this version and let us know if you still are still having trouble syncing.

**Comment by asharoo1** [comment]
Hello, @garyschulte I'm using docker for running the node and I've not installed the besu.
However, when I'm running the below-mentioned command for running a node on Ethereum MainNet it's working fine and all the blocks are getting imported.
**But on running a node on rinkeyby testnet I get the above mentioned error**

The command for running a node on Ethereum MainNet using docker:

```
sudo docker run -p 30303:30303 --mount type=bind,source=/home/ubuntu/rinkbeyvol/besu/rinkeby,target=/var/lib/besu \
hyperledger/besu:latest \
--network=rinkeby \
--data-path=/var/lib/besu
```

**Comment by vmichalik** [comment]
Hi @asharoo1 to clarify, what @garyschulte was explaining was that the error you're seeing above shouldn't stop your node from syncing if you let it run. Could you try with the latest version now and leave it to see if it syncs?

**Comment by asharoo1** [comment]
Hello, @vmichalik I've not installed besu as I'm running through the docker image.
However, I'll start the node again and keeps onto sync, and see if it syncs

**Comment by garyschulte** [comment]
if you are using `hyperledger/besu:21.7` for your image, you will get the latest RC2 which has those logging improvements
