### ISSUE TITLE
Enable unauthenticated access to specific API methods

### ISSUE THREAD

**Issue by arodriguezbonmati** [hyperledger/besu#2474]
### Description
Currently, enabling authentication forces all API Methods to be authenticated. It would be nice that enabling authentication for specific API methods, like ADMIN, was a feature. For example, calls to the more harmless methods like NET or ETH should not need authentication, however, calls to ADMIN methods should be authenticated.

**Comment by vmichalik** [comment]
Thanks for the issue - this makes a lot of sense. We'll let you know when we get it scheduled against the roadmap.

**Comment by frankisawesome** [comment]
Game plan here is probably adding a new CLI option '--rpc-http-api-no-auth' only when auth is enabled and allow some methods to be unauthed. Since we only allow method categories like 'ETH' 'DEBUG' etc on '--rpc-http-api' I think it makes sense to keep the granularity consistent.
