### ISSUE TITLE
org.hyperledger.besu.ethereum.trie.MerkleTrieException: Invalid RLP value for hash 0x...: leaf has null value

### ISSUE THREAD

**Issue by fenghaoming** [hyperledger/besu#2488]
I used module trie of version 20.10.4
```
        <dependency>
            <groupId>org.hyperledger.besu.internal</groupId>
            <artifactId>trie</artifactId>
            <version>20.10.4</version>
            <exclusions>
                <exclusion>
                    <groupId>org.hyperledger.besu</groupId>
                    <artifactId>secp256k1</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hyperledger.besu.internal</groupId>
                    <artifactId>kvstore</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

My code is written like this:
[DemoBesuTrie.java.txt](https://github.com/hyperledger/besu/files/6738804/DemoBesuTrie.java.txt)

And then I get the exception:
[nohup.out.txt](https://github.com/hyperledger/besu/files/6738806/nohup.out.txt)

Please help me, thank you!

**Comment by fenghaoming** [comment]
I used module trie of version 20.10.4
```
        <dependency>
            <groupId>org.hyperledger.besu.internal</groupId>
            <artifactId>trie</artifactId>
            <version>20.10.4</version>
            <exclusions>
                <exclusion>
                    <groupId>org.hyperledger.besu</groupId>
                    <artifactId>secp256k1</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hyperledger.besu.internal</groupId>
                    <artifactId>kvstore</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```


My code is written like this:
[DemoBesuTrie.java.txt](https://github.com/hyperledger/besu/files/6738804/DemoBesuTrie.java.txt)



And then I get the exception:
[nohup.out.txt](https://github.com/hyperledger/besu/files/6738806/nohup.out.txt)


Please help me, thank you!

**Comment by fenghaoming** [comment]
It seems that after inserting length of 0 Bytes to StoredMerklePatriciaTrie, the exception will be thrown when call "StoredMerklePatriciaTrie.get(K key)". But in “StoredMerklePatriciaTrie.put(K key, V value)” only did "not null" check, didn't do the length check? I don't know if I understand wrong.

**Comment by vmichalik** [comment]
Thanks for raising @fenghaoming, we'll look into this!

**Comment by garyschulte** [comment]
Can you distill this down to a minimal amount of code to reproduce the error?  This looks like a big chunk of autogenerated code.

**Comment by fenghaoming** [comment]
> Can you distill this down to a minimal amount of code to reproduce the error? This looks like a big chunk of autogenerated code.

OK. 
[DemoBesuTrieSimple.java.txt](https://github.com/hyperledger/besu/files/6774078/DemoBesuTrieSimple.java.txt)

**Comment by matt-nelson-csi** [comment]
Close as stale
