### ISSUE TITLE
Gas estimation failed

### ISSUE THREAD

**Issue by Millmonster** [hyperledger/besu#2494]
When I try to transfer the tokens to my wallet is says this

<img width="506" alt="Screen Shot 2021-06-30 at 12 43 34 PM" src="https://user-images.githubusercontent.com/86579113/124177250-f5878a80-da7d-11eb-976c-4ac064f18c1d.png">

How do I fix this?

I am on pragma solidity >=0.5.17;

**Comment by matkt** [comment]
Hi, can you tell us more ?  The version of Besu you are using, on which network (mainnet, goerli, etc) ? The contract you call if possible as well as the method called etc. This will help us understand your issue

**Comment by sajz** [comment]
Closing this as the issue was opened 5 months ago and no additional information was shared.
