### ISSUE TITLE
Erroneous PING and PONG encoding of enr sequence number

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#2496]
The besu client does not properly encode the enr sequence number in PONG responses. 

See https://github.com/hyperledger/besu/blob/e230a445bb457bbac27bf4c384da449ccbd3f043/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketData.java#L72 

Essentially, the enr sequence is written as `writeBytes( seqAsAUint64.toBytes());`

Example Pong
```
&Pong{
            To:         Endpoint{net.ParseIP("127.0.0.1").To4(), 3322, 5544},
            ReplyTok:   common.HexToHash("0x0000000000000000000000000000000000000000000000000000000000001234").Bytes(),
            Expiration: 1136239445,
            ENRSeq:     0,
        },
```
( it's UDP 3322, TCP 5544)

Besu encodes the example above as `0xf83bcb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a355880000000000000000`. 
```
rlpdump -hex f83bcb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a355880000000000000000
[
  [
    7f000001,
    0cfa,
    15a8,
  ],
  0000000000000000000000000000000000000000000000000000000000001234,
  43b9a355,
  0000000000000000,
]
```

If the sequence number is `1`, it's encoded as `0xf83bcb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a355880000000000000001`

```
 rlpdump -hex f83bcb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a355880000000000000001
[
  [
    7f000001,
    0cfa,
    15a8,
  ],
  0000000000000000000000000000000000000000000000000000000000001234,
  43b9a355,
  0000000000000001,
]
```
So apparently the ENR sequence number is encoded as `8` bytes, not as an RLP integer. 

This was not an _obvious_ problem until geth implemented a change in how packets are decoded, in https://github.com/ethereum/go-ethereum/commit/3e6f46caec51d82aef363632517eb5842eef6db6 . Before this change: 

- Any 'junk' at the end would be ignored. Thus, the `0000000000000001` element was silently discarded, the enr sequence number was always `0`, when decoding a PONG from besu. 
- Geth would output `f3cb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a35580` for the zero-case

```
rlpdump -hex f3cb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a35580
[
  [
    7f000001,
    0cfa,
    15a8,
  ],
  0000000000000000000000000000000000000000000000000000000000001234,
  43b9a355,
  "",
]
```
- Geth would output the following for the `1`-case

```
rlpdump -hex f3cb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a35501
[
  [
    7f000001,
    0cfa,
    15a8,
  ],
  0000000000000000000000000000000000000000000000000000000000001234,
  43b9a355,
  01,
]
```

Now, however, geth willl reject the 'junk' at the end. 
On output, geth willl output the following for the `0`-case
```
 rlpdump -hex f2cb847f000001820cfa8215a8a000000000000000000000000000000000000000000000000000000000000012348443b9a355
[
  [
    7f000001,
    0cfa,
    15a8,
  ],
  0000000000000000000000000000000000000000000000000000000000001234,
  43b9a355,
]
```

This issue was found in hive

![Screenshot_2021-07-02 https hivetests ethdevops io](https://user-images.githubusercontent.com/142290/124309405-f518ed80-db6a-11eb-8404-44eab4c7c275.png)

Unfortunately, the test-framework also contained another false positive, which caused the 'legit' error from not always being shown (the false positive being ` PONG 'to' endpoint mismatch: got {IP:172.17.0.7 UDP:44025 TCP:44025}, want {IP:172.17.0.7 UDP:44025 TCP:0}`). 

I think the fix would be to just use `writeLongScalar` to write the ENR sequence number. 

cc @fjl @garyschulte 

Related geth-pr with some encoding examples: https://github.com/ethereum/go-ethereum/pull/23155 
Related hive logs: https://hivetests.ethdevops.io/?page=v-pills-results-tab&suite=1625138437-05d8c3c144ebe42dbca73551d1d2f73a.json

**Comment by holiman** [comment]
The same problem is present in PING aswell: https://github.com/hyperledger/besu/blob/e230a445bb457bbac27bf4c384da449ccbd3f043/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketData.java

**Comment by jflo** [comment]
Add correct handling of IP address being optional.
Add correct dispatch of PONG using an array instead of a scalar, to match incoming PING
