### ISSUE TITLE
[BUG] [21.7.0-RC2] Invalid checkpoint headers.  Headers downloaded between #10557393 and #10557593 do not connect at #10557394: Invalid block at #10557394

### ISSUE THREAD

**Issue by manbobo2002** [hyperledger/besu#2498]
### Description
As an [Actor], I want [feature] so that [why]. 
`
Jul 05 03:56:23 besu-1 besu[6764]: 2021-07-05 03:56:23.456+00:00 | nioEventLoopGroup-3-8 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xcaeeca687eaac6f0cb... at block 10557393
Jul 05 03:56:24 besu-1 besu[6764]: 2021-07-05 03:56:24.876+00:00 | EthScheduler-Services-143 (validateHeadersJoin) | WARN  | PipelineChainDownloader | Invalid block detected.  Disconnecting from sync target. Invalid checkpoint headers.  Headers downloaded between #10557393 (0xc648bec151098c162a787b1e0e27cd70010b765ff5bb42137910b67172a82a21) and #10557593 (0x2171f70eb70e2590cc926561fb4fb4fedc02ae8e8dcc1fea215f9a878c49b458) do not connect at #10557394 (0x99bef2d9edaa3a189e9eb02c2697fcba1cf9cea98eda8e9ad45fc80f91bec8d6): Invalid block at #10557394 (0x99bef2d9edaa3a189e9eb02c2697fcba1cf9cea98eda8e9ad45fc80f91bec8d6)
Jul 05 03:56:24 besu-1 besu[6764]: 2021-07-05 03:56:24.877+00:00 | EthScheduler-Services-143 (validateHeadersJoin) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.
Jul 05 03:56:24 besu-1 besu[6764]: java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Invalid checkpoint headers.  Headers downloaded between #10557393 (0xc648bec151098c162a787b1e0e27cd70010b765ff5bb42137910b67172a82a21) and #10557593 (0x2171f70eb70e2590cc926561fb4fb4fedc02ae8e8dcc1fea215f9a878c49b458) do not connect at #10557394 (0x99bef2d9edaa3a189e9eb02c2697fcba1cf9cea98eda8e9ad45fc80f91bec8d6): Invalid block at #10557394 (0x99bef2d9edaa3a189e9eb02c2697fcba1cf9cea98eda8e9ad45fc80f91bec8d6)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
Jul 05 03:56:24 besu-1 besu[6764]:         at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
Jul 05 03:56:24 besu-1 besu[6764]:         at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jul 05 03:56:24 besu-1 besu[6764]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jul 05 03:56:24 besu-1 besu[6764]: Caused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Invalid checkpoint headers.  Headers downloaded between #10557393 (0xc648bec151098c162a787b1e0e27cd70010b765ff5bb42137910b67172a82a21) and #10557593 (0x2171f70eb70e2590cc926561fb4fb4fedc02ae8e8dcc1fea215f9a878c49b458) do not connect at #10557394 (0x99bef2d9edaa3a189e9eb02c2697fcba1cf9cea98eda8e9ad45fc80f91bec8d6): Invalid block at #10557394 (0x99bef2d9edaa3a189e9eb02c2697fcba1cf9cea98eda8e9ad45fc80f91bec8d6)
Jul 05 03:56:24 besu-1 besu[6764]:         at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:68)
Jul 05 03:56:24 besu-1 besu[6764]:         at org.hyperledger.besu.ethereum.eth.sync.CheckpointHeaderValidationStep.apply(CheckpointHeaderValidationStep.java:27)
Jul 05 03:56:24 besu-1 besu[6764]:         at org.hyperledger.besu.services.pipeline.FlatMapProcessor.processNextInput(FlatMapProcessor.java:32)
Jul 05 03:56:24 besu-1 besu[6764]:         at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)
Jul 05 03:56:24 besu-1 besu[6764]:         at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
Jul 05 03:56:24 besu-1 besu[6764]:         ... 5 more
`

### Acceptance Criteria
Should work normal

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]
should not stuck in some blocks
**Actual behavior:** [What actually happens]
stuck in ETH block_no: 10557393
**Frequency:** [What percentage of the time does it occur?]
Starting from 3-Jul-2021 05:00 (UTC+8)

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]
`
$ besu --version
besu/v21.7.0-RC2/linux-x86_64/openjdk-java-11
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode, sharing)
$ cat /etc/*release
ID="ec2"
VERSION="20200928-407"
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

**Comment by vmichalik** [comment]
Hi @manbobo, investigating this. Thanks for raising an issue!

**Comment by vmichalik** [comment]
A PR to fix this is in review! #2499

**Comment by matkt** [comment]
We just fixed the issue on master. Thanks for your ticket
