### ISSUE TITLE
Account authority control

### ISSUE THREAD

**Issue by Duanraudon** [hyperledger/besu#2515]
![image](https://user-images.githubusercontent.com/34836995/125018174-26cc1000-e0a7-11eb-9b1e-b7e4b462e284.png)
![image](https://user-images.githubusercontent.com/34836995/125018217-3f3c2a80-e0a7-11eb-9626-350d9448d152.png)
![image](https://user-images.githubusercontent.com/34836995/125018325-727eb980-e0a7-11eb-891a-63e79b14893f.png)

I configured the account authority management list, why doesn't it work?

**Comment by vmichalik** [comment]
Hey @Duanraudon, looking into this! Thanks for raising an issue

**Comment by macfarla** [comment]
Hi @Duanraudon I can't reproduce this issue locally (it works for me). Is it possible you are pointing to a different toml file? Or are there any errors in Besu startup logs?

**Comment by Duanraudon** [comment]
> Hi @Duanraudon I can't reproduce this issue locally (it works for me). Is it possible you are pointing to a different toml file? Or are there any errors in Besu startup logs?
I have solved this problem. When besu was started, an error was reported that there was no permission to write to the permissions_config.toml file, so I added permissions to the local permissions_config.toml to solve this error.

**Comment by vmichalik** [comment]
ok, thanks for the update @Duanraudon! closing this for now
