### ISSUE TITLE
Contract deployment failed when implemented chainid opcode

### ISSUE THREAD

**Issue by suraneti** [hyperledger/besu#2516]
### Description
As a developer, I want to deploy successfully.

### Acceptance Criteria
* Deployment successful.

### Steps to Reproduce (Bug)
1. Implement chained opcode in contract.
``` solidity
       constructor() {
              uint256 chainId;
              assembly {
                  chainId := chainid()
              }
       }
```

2. Deploy through hardhat

**Expected behavior:** Deployment successful.

**Actual behavior:** Deployment failed.

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: `besu-21.1.3`
* Java version: `java-openjdk11`
* OS Name & Version: `Amazon Linux 2.0.20210617.0`

**Comment by matkt** [comment]
thanks for your ticket I will investigate this

**Comment by matkt** [comment]
I tried to deploy te same transaction with remix and it's fine. Could you try with the last version of Besu ? And if you still have the issue could you tell me the issue you have with hardhat

**Comment by suraneti** [comment]
@matkt I found the issue, in genesis.json file not included Istanbul upgrade, I thought besu started with the latest ethereum protocol.

**Comment by matkt** [comment]
no there is not this kind of feature on Besu.

**Comment by eu09** [comment]
If besu didnt have a feature for upgrade the consensus protocol by vote , so what is the method u can suggest to upgrade the genesis.json without reset the blockchain data ?

**Comment by puneet166** [comment]
The same issue i am facing. 
contract deployment through remix is successful happen but when trying to interact with the deployed contract facing the same issue.
@matkt
