### ISSUE TITLE
Clean TransactionReplacementByPriceRule

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#2560]
For example this method : 

```java
private Wei priceOf(final Transaction transaction, final Optional<Long> baseFee) {
   final TransactionPriceCalculator transactionPriceCalculator =
       transaction.getType().equals(TransactionType.EIP1559)
           ? EIP1559_CALCULATOR
           : FRONTIER_CALCULATOR;
   return transactionPriceCalculator.price(transaction, baseFee);
 } 
```
The 'EIP1559_CALCULATOR' manage non EIP1559 transaction so this check is useless. But in order to have something that work before London we need to have different **TransactionReplacementByPriceRule** behavior for PRE and POST London

Maybe getting the valid TransactionPriceCalculator thanks to the protocolSpec in order to not have **if else** condition **
    protocolSchedule.getByBlockNumber().getTransactionPriceCalculator()**

**Comment by garyschulte** [comment]
addressed in https://github.com/hyperledger/besu/pull/2545
