### ISSUE TITLE
Clean EIP1559BlockHeaderGasPriceValidationRule

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#2564]
we have a useless condition (we must be sure that this condition is really useless). Why I think this condition is useless ? because this class is only called on a EIP1559 block

```java 
public boolean validate(final BlockHeader header, final BlockHeader parent) {
    try {
      if (!eip1559.isEIP1559(header.getNumber())) {
        return true;
      }
...
```

**Comment by garyschulte** [comment]
resolved by https://github.com/hyperledger/besu/pull/2658
