### ISSUE TITLE
Clean MainnetBlockBodyValidator

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#2565]
In this class we can find this code 

```java
private boolean validateTransactionGasPrice(final Block block) {
  if (maybeEip1559.isEmpty()) {
    return true;
  }
  final EIP1559 eip1559 = maybeEip1559.get();
  if (!eip1559.isEIP1559(block.getHeader().getNumber())) {
    return true;
  }
```

In order to remove this **if condition** we can have two implementation for **Pre and Post London** 

We already have **.blockBodyValidatorBuilder(MainnetBlockBodyValidator::new)** in the **MainnetProtocolSpecs**

We can have **LondonMainnetBlockBodyValidator** extend **FrontierMainnetBlockBodyValidator** with  different list of checks

Step :
1 - Rename MainnetBlockBodyValidator to FrontierMainnetBlockBodyValidator
2- Create a LondonMainnetBlockBodyValidator class with new EIP1559 checks

**Comment by garyschulte** [comment]
@matkt what do you think of deferring to protocolschedule feemarket type?
 
https://github.com/hyperledger/besu/blob/650b5a01b10ab1e09f0fd8f06b9b4e2ddc46271e/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockBodyValidator.java#L266-L295

do you think we still want/need a separate MainnetBlockBodyValidator for london?

**Comment by matkt** [comment]
> @matkt what do you think of deferring to protocolschedule feemarket type?
> 
> https://github.com/hyperledger/besu/blob/650b5a01b10ab1e09f0fd8f06b9b4e2ddc46271e/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockBodyValidator.java#L266-L295
> 
> do you think we still want/need a separate MainnetBlockBodyValidator for london?

I think it's fine like that
