### ISSUE TITLE
Update the FeeMarket class

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#2566]
We need to keep the FeeMarket class . (maybe use the FeeMarket interface and rename FeeMarketConfig to LondonFeeMarket)

Instead of having the object EIP1559 (which will be deleted) we pass the object Optional < FeeMarket>. And use the ProtocolSpec to retrieve the feeMarket instead of passing everytime the EIP1559 object.

For more consistency we must look at the classes that we can put directly in this one
- TransactionPriceCalculator
- TargetingGasLimitCalculator

**Comment by garyschulte** [comment]
resolved https://github.com/hyperledger/besu/pull/2658
