### ISSUE TITLE
Besu Permissioning with smart contracts to allow DNS for p2p

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#2571]
### Description
As a user I would like DNS entries to permit p2p connections when using the Besu permissioning contracts.

### Acceptance Criteria
* DNS entries can be added to permit p2p connections
* Sufficient testing has been added to ensure this feature works 

### Additional Information
Currently Besu code only handles IP addresses as entries in the permissioning contracts to check that a connection on the p2p network are permitted or not. 
See NodeSmartContractPermissioningController

**Comment by macfarla** [comment]
to be backwards compatible, need to ask the permissioning contracts is the IP allowed, and is the DNS allowed

**Comment by alberto-hernandez** [comment]
The V2 of Smartarcontracts are compatible with IPS ands DNS. It change the signature to receive a string as parameter.

**Comment by macfarla** [comment]
@alberto-hernandez you are right - the contracts allow DNS entries - but currently Besu only checks peer IPs against the contracts which may contain DNS entries

**Comment by alberto-hernandez** [comment]
@macfarla, you are right. Even if Besu is consistent with DNS enable option activated, a decision should be may because the entries in the SC could be mixed with DNS and IPs.
