### ISSUE TITLE
misleading warning on startup: --min-gas-price ignored

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2579]
The following warning is being reported: "--min-gas-price ignored because none of --miner-enabled or isQuorum (in genesis file) was defined." 

Using the quickstart. 

### Description
As an [Actor], I want [feature] so that [why]. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by drinkcoffee** [comment]
This is very confusing when some other issue is causing the quick start to not work (in my case it was because of networking issues). Zero gas cost transactions are still accepted. As such, what is being shown in the error message is very misleading

**Comment by drinkcoffee** [comment]
Thank you for fixing this @macfarla !
