### ISSUE TITLE
Test qbft transaction based voting to support transitions for add/remove without voting workaround

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#2589]
Test workaround for Qbft transaction based voting to support transitions for add/remove without voting.

Basic strategy
* Add transition to move to block header based voting
* Restart network
* Fix/deploy new contract
* Add transition to move to new contract based voting
* Restart network to use new contract

**Comment by siladu** [comment]
Instead of changing code, we could test out and document a workaround, then see there's any value for users to have a better mechanism in the future.

To discuss with @vmichalik
