### ISSUE TITLE
Spike to scope incorporating MEV RPC support

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2597]
spike to determine the level of effort to support flashbots v0.3 RPC and/or eden:
  https://docs.flashbots.net/flashbots-auction/miners/mev-geth-spec/v03

* determine impacts on PGA transaction selection
* LoE to manage and incorporate bundle pool
  * bundle validation and selection
* LoE to support bundle simulation
* considerations about endpoint security, mev-relay

resources:
https://docs.flashbots.net/

https://docs.edennetwork.io/
https://edennetwork.io/EDEN_Network___Whitepaper___2021_07.pdf

**Comment by garyschulte** [comment]
After conversations with flashbots, it seems we would be better served to skip the implementation of 0.3/0.4 api bundles and instead engage with flashbots to implement the forthcoming post-merge API which does away with bundles entirely.

**Comment by matt-nelson-csi** [comment]
MEV is no longer being completed at the execution layer.
