### ISSUE TITLE
Create chainId limit/validation

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2601]
### Description

trezor has/had a 32 bit chain id limit, and therefore has difficulty interacting with chain that have a chain id >32 bit.  Trezor is working on supporting 64 bit chain id's at present.  Devops on palm has asked for besu to implement a constraint on chain Id so that id does not exceed 64 bit.  In light of conversation, this should probably be a warning rather than an explicit constraint

### Acceptance Criteria
* warning when chain id exceeds 64 bit

**Comment by jflo** [comment]
The EVM opcode (CHAINID) allows to return a value for chainid up to 256bits.

**Comment by garyschulte** [comment]
Good point, it seems like a warning might be more appropriate.  

I think the issue here is that hardware wallets, specifically trezor were not able to work with the palm chain id.  a 256 bit chain id is a bit absurd really.  I doubt anybody would have the patience to type in a chain id in excess of 64 bits.  $0.02.

**Comment by atoulme** [comment]
Please don't link to private resources. Please provide context. No idea who Josh is.

**Comment by shemnon** [comment]
There are chains that use more than 64 bits, so a warning instead of a block would preserve compatibility.

**Comment by atoulme** [comment]
@drinkcoffee is working on cross chain operations with the EEA and has devised new ways to present chain IDs. See also https://github.com/ChainAgnostic/CAIPs/pull/49

**Comment by shemnon** [comment]
The limit on that standard (32 digits) limits the space to 109/110 bits.  The ideas I've seen are to take some common string "Acme Widget Chain 2021", hash it, and that's the chainid.  You would want 256 for some hash algorithms.  64 is a bit short for a hash.

**Comment by shemnon** [comment]
@garyschulte @jflo to unstick the trezor wallet addresses perhaps Besu could be configured to accept multiple ChainIDs.  The evm opcode only reports one but multiple are accepted in protected transactions.  Not sure how to advertise it to the evm, but the json rpcs could add an extra field listing an array of all accepted ChainIDs.

**Comment by avanideshpande** [comment]
Interested in contributing to this issue.

**Comment by jflo** [comment]
I think there might be a bit more going on than emitting the warning, removing good first issue label.

**Comment by drinkcoffee** [comment]
It would be good if the chain id was 256 bits. My reasoning is:
* This allows ephemeral blockchain ids to be generated on the fly randomly, without having to worry about collisions. 
* Additionally, as @atoulme pointed out, the Enterprise Ethereum Alliance is in the midst of standardising a 256 bit chain id to be used for crosschain.

**Comment by matt-nelson-csi** [comment]
Close as current 256 bit value is fine, warning can be handled client side.
