### ISSUE TITLE
Geth node discarding too far away blocks

### ISSUE THREAD

**Issue by baptiste-marchand** [hyperledger/besu#2627]
A Geth node in a 6 Besu nodes Clique network randomnly desynchronize from the head block.
![Screenshot from 2021-08-12 18-44-22](https://user-images.githubusercontent.com/75846779/129237687-0543a850-854d-429d-b90c-18be7a435bbb.png)

**Comment by vmichalik** [comment]
This is unusual - we have a long-lived testnet in Goerli with Besu and Geth nodes running Clique together!
Can you share your versions and config for Besu and for Geth?

**Comment by baptiste-marchand** [comment]
It was a compatibility problem between the latest Geth and Best versions. It is now solved, thanks.
