### ISSUE TITLE
Improve warning on invalid JDK version

### ISSUE THREAD

**Issue by vmichalik** [hyperledger/besu#2639]
Currently the errors thrown by trying to build Besu with an invalid JDK version are not descriptive enough to diagnose easily. We should look into improving these if possible.

Addresses #2617

**Comment by vmichalik** [comment]
In particular, errors caused by trying to use Java 17 ->

https://docs.gradle.org/current/userguide/compatibility.html
A Java version between 8 and 16 is required to execute Gradle. Java 17 and later versions are not yet supported.

**Comment by non-fungible-nelson** [comment]
@usmansaleem - relevant logging still? Close or keep around as a good first issue.

**Comment by macfarla** [comment]
fixed
