### ISSUE TITLE
Upgrade Besu from Java 11 to Java 17

### ISSUE THREAD

**Issue by vmichalik** [hyperledger/besu#2643]
Move Besu code build requirements from Java 11 to Java 17
- CircleCI 
- GitHub
- Gradle
- Docker

**Comment by vmichalik** [comment]
Blocked by compatibility, h/t @atoulme

https://docs.gradle.org/current/userguide/compatibility.html
A Java version between 8 and 16 is required to execute Gradle. Java 17 and later versions are not yet supported.

**Comment by non-fungible-nelson** [comment]
@usmansaleem - ok to close?

**Comment by usmansaleem** [comment]
@non-fungible-nelson Yes, this ticket is good to close. The work is being tracked under https://github.com/hyperledger/besu/issues/3320
