### ISSUE TITLE
bls12-381 tests failing tests with besu-native > 0.3.0

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#2668]
### Description
When upgrading besu-native to 0.4.x, we noticed that there were a lot of unit tests failures. All related to bls12.

We need to run a regression to identify where this was introduced. Version 0.3.0 of besu-native is the latest version that is stable for bls12.

There was a 0.3.1 release that was never used by Besu. I suspect the issues could be related to these changes (https://github.com/hyperledger/besu-native/commit/ceab94f24d9d0919831976823b4ff4e3f9d841f6).

This CircleCI job execution shows the failures: https://app.circleci.com/pipelines/github/hyperledger/besu/10199/workflows/ff23bf6f-bfef-421e-8d6e-ecf36ce80b0c/jobs/54381

### Steps to Reproduce (Bug)
1. Update version.gradle `org.hyperledger.besu:bls12-381:0.3.0` to `org.hyperledger.besu:bls12-381:0.4.0` (or greater)
2. Run `./gradlew build`

**Comment by daniellehrner** [comment]
I will take over this issue
