### ISSUE TITLE
Update JavaDoc so we can build with Java 16+

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#2681]
Currently Hypedlerger Besu won't fully build when using Java 16 as the JVM that is running the gradle build. One reason is that some of javadoc rules in have changed.

There are two main items that are hitting us
* Not all public classes have comments. Fixing these can be tedious, but it appears our warning setting lets us get away with it.
* Some places we use out-of-order &lt;H3&gt; headings and the javadoc linter really hates that.

If we can get away without adding javadoc on all public methods that would be great.  If we do have to do thousands of javadocs we should consider the bare-minimum needed, without blatently saying "TODO" on all of them. This can be fixed possibly with CLI flags in the build?

The other lint options should be fixed.  The heading order ones in particular.  But if there are syntax and reference bugs those should be fixed.

**Comment by joyita07** [comment]
Can I work on this?

**Comment by macfarla** [comment]
👋 Hi @joyita07 are you still interested in working on this?
