### ISSUE TITLE
Error when starting IBFT2.0 network and 4 nodes didn't sync up 

### ISSUE THREAD

**Issue by emclab** [hyperledger/besu#2687]
### Description
Upgraded to 21.7.2 from 21.1 and restart 4 nodes (one boot node). There is an error complaining ANTLR version mismatch on boot node and it never sync up. The node get start with command systemctl start/restart node1.service ... node4.service. After quite a few times trying to reboot and restart nodes, then the nodes start to sync up. Since I was using the same command to start the node again and again and have no idea why it worked last time. The system is running on ubuntu 20.04. The slow sync up issue happened on 21.1 and it seems have something to do with the service. 

`ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.82021-08-26 05:53:25.550+08:00 | main | INFO | AbstractAltBnPrecompiledContract | Using LibEthPairings native alt bn128`

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. systemctl start/restart node.service
2. check log
3. [Step ...]

**Expected behavior:** [What you expect to happen]
nodes sync up and running

**Actual behavior:** [What actually happens]
Error in log and hard to sync up

**Frequency:** [What percentage of the time does it occur?]
often if restart the node

### Versions (Add all that apply)
* Software version: [`besu --version`] 21.7.2
* Java version: [`java -version`] openjdk 14
* OS Name & Version: [`cat /etc/*release`] ubuntu 20.04
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large] 8GB instance

**Comment by vmichalik** [comment]
Hey @emclab, we'll look into this, thanks for raising an issue!

**Comment by garyschulte** [comment]
I suspect the ANTLR warning is a red herring, and the sync problem is related to failing to find peers #2662.

**Comment by dtourassis** [comment]
@garyschulte That's my take on this as well. Got 8 nodes fully synced using 21.7.2 and still get the ANTLR warning when booting up.
@emclab Try running besu with --logging=ALL and check for any new errors.

**Comment by macfarla** [comment]
Hi @emclab I realise it's been a while but we have made some improvements in peering and syncing. And we are also beginning a holistic assessment of peering behavior including any outstanding issues. So we're hoping that it's either fixed already, or that you're able to give us some more info if you're still having related issues?
