### ISSUE TITLE
Support setting a fixed BASEFEE value

### ISSUE THREAD

**Issue by atoulme** [hyperledger/besu#2691]
### Description
Support setting a fixed base fee instead of using the EIP-1559 mechanism, returned by the BASEFEE opcode. It can be set to zero or a value such as 1.

### Acceptance Criteria
* Basefee can be configured on hard fork.
* Optionally, it can be overridden with a configuration flag.

See Mystique hard fork info: https://github.com/ethereumclassic/ECIPs/issues/432

**Comment by shemnon** [comment]
Should this be extended to a general configuration to disable the basefee adjustment in block creation?  If basefee stays at zero by protocol configuration then it will wire through automatically.

**Comment by vmichalik** [comment]
we're definitely interested to get something in place to easily set basefee to remain at zero as well

**Comment by vmichalik** [comment]
also might make sense to use transitions if that's possible!

**Comment by garyschulte** [comment]
Would it not make more sense to just not enable the basefee market and have the basefee opcode return zero when there is not a basefee market present?  I don't see the point of enabling the fee market with a static base fee.

**Comment by diega** [comment]
ETC's [Mystique](https://ecips.ethereumclassic.org/ECIPs/ecip-1104) upgrade didn't include [EIP-3198](https://eips.ethereum.org/EIPS/eip-3198) after all. We can safely close this issue now
