### ISSUE TITLE
Support deactivating p2p 

### ISSUE THREAD

**Issue by atoulme** [hyperledger/besu#2706]
### Description
As a Besu user, I want to be able to run Besu while deactivating the peer-to-peer network capabilities of Besu.

### Acceptance Criteria
* There is a config flag to turn off p2p networking. It is enabled by default.

**Comment by macfarla** [comment]
there is a config flag to turn off p2p networking. https://besu.hyperledger.org/en/stable/public-networks/reference/cli/options/?h=p2p#p2p-enabled

p2p-enabled is true by default. I don't think it makes sense to do the opposite
