### ISSUE TITLE
Besu doesn't reset connection with RocksDB

### ISSUE THREAD

**Issue by b-rohit** [hyperledger/besu#2710]
### Description
I run a besu node on Kubernetes cluster with persistent volume(pv). The data folder is stored in the pv. When the pod is deleted and created again besu gives following error.

`org.rocksdb.RocksDBException: While lock file: /opt/besu/data/database/LOCK: No locks available`

### Steps to Reproduce (Bug)
1.  start besu node in pod with pv
2. delete pod 
3. start pod again.

**Expected behavior:** [What you expect to happen]
The besu should be able to reset db connection.
**Actual behavior:** [What actually happens]
The besu is not able to connect to db
**Frequency:** [What percentage of the time does it occur?]
everytime.
### Versions (Add all that apply)
* docker image: hyperledger/besu:1.4.3

### Additional info
I thought it has to do with LOCK file. I delete the LOCK file before starting besu, still it doesn't solve the problem.

**Comment by vmichalik** [comment]
Hey @b-rohit, thanks for raising an issue! We'll look into this shortly
