### ISSUE TITLE
Unexpected FROM value in private transaction receipt when transaction gas is not zero.

### ISSUE THREAD

**Issue by mark-terry** [hyperledger/besu#2722]
### Description
An unexpected `from` value is present on the *private* transaction receipt when the `gas` value in the transaction is not zero. When `gas` is omitted the expected `from` value is present on the private transaction receipt.

### Acceptance Criteria
`from` value on the private transaction receipt should match the `from` on the private transaction. This value is not expected to change with the `gasLimit`.

### Steps to Reproduce (Bug)
1. Run Besu (v20.10.4) with the following config:
```
      /opt/besu/bin/besu public-key export --to=/tmp/bootnode_pubkey;
      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --genesis-file=/config/genesis.json \
      --node-private-key-file=/opt/besu/keys/key \
      --min-gas-price=0 \
      --privacy-enabled \
      --privacy-url=$${ORION_CLIENTURL} \
      --privacy-public-key-file=/config/orion/orion.pub \
      --privacy-onchain-groups-enabled=false \
      --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
      --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
```

2. Send a transaction with `gas` set to a value (eg. 900000).
3. Retrieve the private transaction receipt.
4. Send a transaction with `gas` omitted.
5. Retrieve the private transaction receipt.

**Expected behavior:** [What you expect to happen]
The `from` value on both receipts should be the same.

**Actual behavior:** [What actually happens]
The `from` value on the transaction without gas has the expected value, the `from` value on the transaction with gas has an unexpected value.

**Comment by ggarri** [comment]
To follow up with this topic I wrote a Go script to generate two signed raw data of the same EEA transaction, with and without gas set, in the way we do in Orchestrate. I hope this helps to reproduce the issue described above

https://github.com/ggarri/eea_signer_example

cc @taccatisid @pinges

**Comment by MadelineMurray** [comment]
Check with @taccatisid if there's additional context from when they looked at this issue.

**Comment by non-fungible-nelson** [comment]
@macfarla - status or close?
