### ISSUE TITLE
PeerDiscoveryTimestampsTest.lastContactedTimestampUpdatedOnOutboundMessage() is flakey

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#2742]
### Acceptance Criteria
* Test passes consistently and repeatably.

### Steps to Reproduce (Bug)
1. Example failure can be found [here](https://app.circleci.com/pipelines/github/hyperledger/besu/10510/workflows/4de566cc-7861-467d-9488-758a7fdcc749/jobs/56455).

**Expected behavior:** 
Test always pass.

**Actual behavior:** 
Test sometimes fails when it runs "too fast" and the compared to timestamp is on the same millisecond.

**Frequency:** 
Multiple times a week in the course of CI.

**Comment by jflo** [comment]
It might help to avoid using the wall clock, and instead try the `org.hyperledger.besu.testutil.TestClock` as a test fixture.

**Comment by catcs** [comment]
I can work on this issue.
