### ISSUE TITLE
Sync never finishes

### ISSUE THREAD

**Issue by petehall73** [hyperledger/besu#2753]
### Description
A new node will not complete sync.  
The following is an extract from the logs.  I started the node a few weeks ago and it seemed to import all of the blocks but then dropped into a state where the logs only showed 'Downloaded <x number of > world state nodes. At least <another increasing number>.  I restarted the node on Friday to capture the logs.  After a short period I saw this in the logs:

Sep 10 07:04:16 OHGtxpoolEUS01 besu[6904]: 2021-09-10 07:04:16.651+00:00 | nioEventLoopGroup-3-4 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x012f5d89b0481df885... at block 13171439
Sep 10 07:04:18 OHGtxpoolEUS01 besu[6904]: 2021-09-10 07:04:18.662+00:00 | EthScheduler-Services-10 (importBlock) | INFO  | PipelineChainDownloader | Chain download complete
Sep 10 07:08:45 OHGtxpoolEUS01 besu[6904]: 2021-09-10 07:08:45.561+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 100000 world state nodes. At least 1499124 nodes remaining.

It then only shows increasing number of world state nodes as shown here, some 3 days later:
besu[6904]: 2021-09-13 08:56:09.807+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 204500000 world state nodes. At least 40443713

These entries never stop.

 
### Acceptance Criteria
A fully sync'd node on mainnet.

**Expected behavior:** I would expect to see blocks being imported from mainnet as per a normally sync'd node.

**Actual behavior:** See above

**Frequency:** I looked at issue 2156 and restarted the node a number of times but I'm still seeing this issue.

### Versions (Add all that apply)
* Software version: besu/v21.7.3/linux-x86_64/openjdk-java-11
* Java version: openjdk version "11.0.11" 2021-04-20
* OS Name & Version: 18.04.5 LTS
* Kernel Version: 5.4.0-1055-azure #57~18.04.1-Ubuntu SMP Fri Jul 16 19:40:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: N/A
* Cloud VM, type, size: Azure Standard_D4s_v3

### Additional Information
I have restarted this node several times but end up in the same position, with the number of downloaded world state nodes forever increasing, the number of 'at least increasing' and the sync never completing.

**Comment by vmichalik** [comment]
Hey @petehall73, sorry to hear you're having problems! We'll investigate this shortly. What options are you running Besu with?

**Comment by vmichalik** [comment]
Just in case this solves your problem, the default sync mode is FULL for Besu, which takes a very long time. You might be looking for fast sync which usually completes in 2-3 days, see docs here https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#sync-mode

**Comment by petehall73** [comment]
Hi @vmichalik,

Thanks for the reply.  Interesting point about fast versus full.  I am using a config file but in it I specified mainnet with the network flag.  If the default is fast when connecting to ethereum mainnet when not specifying the chain, would it use full if I did use the network flag even when specifying mainnet?

The options I have are:

data-path="/data"

# NETWORK
# network = "mainnet" - this was originally uncommented.

# JSONRPC API
rpc-http-enabled=true
rpc-http-port="8590"
rpc-http-api=["ADMIN","ETH","NET","CLIQUE","WEB3","TXPOOL"]
rpc-http-host="x.x.x.x"
host-allowlist=["*"]
rpc-http-cors-origins=["all"]
revert-reason-enabled=true

Regards
Pete

**Comment by macfarla** [comment]
besu definitely should do fast sync with network="mainnet" on cmd line or in config file.

**Comment by macfarla** [comment]
Specs look perfectly fine and no reason to fail. I'd suggest checking disk space and set the log level to debug or trace perhaps and restarting

**Comment by adean-consensys** [comment]
I'm experiencing this as well.  The fast sync appears to complete with reasonably good speed and now we're in a state where it may take months to complete:

Using Besu version `21.7.2` Docker image in Kubernetes, provided 2 CPUs and 10Gi of memory

Fast Sync ends, Full Sync begins:

```
2021-10-29 17:30:23.026+00:00 | EthScheduler-Services-32 (importBlock) | INFO  | FastImportBlocksStep | Completed importing chain segment 13107201 to 13107400, Peers: 26
2021-10-29 17:30:25.216+00:00 | EthScheduler-Services-32 (importBlock) | INFO  | FastImportBlocksStep | Completed importing chain segment 13107401 to 13107500, Peers: 26
2021-10-29 17:30:25.216+00:00 | EthScheduler-Services-32 (importBlock) | INFO  | PipelineChainDownloader | Chain download complete
2021-10-29 17:35:28.895+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 254000000 world state nodes. At least 32296960 nodes remaining.
2021-10-29 17:41:00.407+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 254100000 world state nodes. At least 32307134 nodes remaining.
```

Blocks level off right at the same time as these log messages

![image](https://user-images.githubusercontent.com/83668448/141011994-85c73c28-c000-4e95-a0a0-184b3b3adcc0.png)

CPU holding steady but not as active as before:

![image](https://user-images.githubusercontent.com/83668448/141012117-61c19310-7d8a-46b5-9b73-1e977838b2ac.png)

**Comment by macfarla** [comment]
there is a lot of state to download. It's a bit confusing because we expect fast sync to increase block numbers until it’s close to head, then stall in terms of block numbers - it needs to download the world state before it can continue. On our canary nodes the "stall" period is 5 days + at current mainnet size.

There are metrics around fast sync eg `besu_synchronizer_fast_sync_pivot_block_current`, `besu_synchronizer_world_state_completed_requests_total` and `besu_synchronizer_world_state_pending_requests_current`

If you can add these metrics to your dash, you can see progress of the "download state" step even while "block number" seems stuck.

**Comment by petehall73** [comment]
Glad it's not just me.  Unfortunately I 've not been able to find a solution
________________________________

**Comment by frankisawesome** [comment]
@petehall73 according to Sally's comment above, the world state download should finish in a few days, was that the case for you?

Proposed solution here would be to add some additional logging when the world state download is happening so it's more intuitive that Besu is not just 'stuck'

**Comment by petehall73** [comment]
Hi Frank,

It did not and in the end I had to move away from Besu as my client.

Regards
Pete

________________________________
