### ISSUE TITLE
Add headings to Besu help

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2757]
This can be done with PicoCLI headings https://picocli.info/quick-guide.html#_section_headings

See related ticket about formatting of the help output
https://github.com/hyperledger/besu/issues/541

### Description
As a developer, I want help grouped sensibly so that it's easy to find what I'm looking for.

Suggested groupings:
GraphQL
JSON-RPC HTTP 
JSON-RPC WebSockets
Metrics
Miner
Privacy
Permissions
Tx pool
(everything else can remain ungrouped)

### Acceptance Criteria
* Besu help has headings for related CLI options

### Steps to Reproduce (Bug)
1. besu --help

**Comment by kathleewong** [comment]
Can I work on this issue?

**Comment by scliou1** [comment]
Can I work on this issue too?  I would like to work together since I'm fairly new to GitHub

**Comment by alyssa00** [comment]
I would like to work on this issue as well.

**Comment by apatel395** [comment]
Can I also work on this

**Comment by azhang919** [comment]
Can I be added onto this issue as well? I helped the previous team members with their code, and we want to make a PR!

**Comment by macfarla** [comment]
👋 Hi @apatel395 @azhang919 @kathleewong @scliou1 are you still interested in working on this?

**Comment by sandrawangyx** [comment]
Hi, I can work on this issue if no other contributor is working on it. 
I can also be assigned other issues.
