### ISSUE TITLE
Ability to validate besu config file / command line

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2759]
### Description
As a developer, I want to be able to validate my besu config file (or command line) so that I can make sure it is valid without starting besu. 

I think it makes sense to do this as a besu subcommand.

### Acceptance Criteria
* `besu validate-config --config-file=besu.conf`
* `besu validate-config --unknown-option`
Above commands would print out any pico CLI exceptions, but not start besu

**Expected behavior:** [What you expect to happen]
I would like to see any errors, or a "success" message, without needing to start besu

**Actual behavior:** [What actually happens]
Currently I need to start besu with the given config file / command line and if it's valid (besu starts) I kill besu.

**Comment by ms2597** [comment]
i will work on this
