### ISSUE TITLE
subcommands do not support --version flag

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2762]
### Description
As a besu dev, I want subcommands to support -V and --version so that I can see version info even when using subcommands. 

### Acceptance Criteria
* version info displays even using subcommand

### Steps to Reproduce (Bug)
1. `besu blocks -V`

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
```
➜  besu git:(typo) besu blocks import -V
➜  besu git:(typo) besu blocks  -V
➜  besu git:(typo) besu  -V
besu/v21.7.3-dev-2aaa4e53/osx-x86_64/oracle_openjdk-java-11
```
**Frequency:** [What percentage of the time does it occur?]
100%

**Comment by mrupk** [comment]
I would like to work on this issue.

**Comment by macfarla** [comment]
👋 Hi @mrupk are you still interested in working on this?

**Comment by svzdvd** [comment]
I'm working on this issue...

**Comment by macfarla** [comment]
@svzdvd yay! Shout out in Discord if you get stuck! And don't forget to signoff every commit - you can setup git to do it automatically - https://wiki.hyperledger.org/display/BESU/DCO
