### ISSUE TITLE
No sync target, no peers available

### ISSUE THREAD

**Issue by Rookie198** [hyperledger/besu#2765]
### Description
New node can't sync to existing validators (TESTNET)

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. Installed Besu (with prerequisites), it runs ok, help command works ok
2. Follow exactly the steps on https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-testnet#3-install-a-eth1-node

**Expected behavior:** [What you expect to happen]
Besu node should start and start syncing nodes from known validators. I will then send my enode data to the existing validators, so they can add my node as a new validator in the network, upon approval.

**Actual behavior:** [What actually happens]
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.549+08:00 | EthScheduler-Timer-0 | INFO  | FastSyncTargetManager | No sync target, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
Sep 15 10:59:56 retes-VirtualBox besu[8685]: 2021-09-15 10:59:56.566+08:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Additional Information

Why is my node not syncing to the existing validator set and downloading blocks? Help?

**Comment by atoulme** [comment]
Please provide version and update to latest release - see #2781
