### ISSUE TITLE
Clean up deprecation warnings

### ISSUE THREAD

**Issue by antonydenyer** [hyperledger/besu#2766]
### Description
Some methods used by Besu are being deprecated and need to be migrated.

There are some easy wins that have simple method name changes e.g. 

https://github.com/hyperledger/besu/blob/main/nat/src/main/java/org/hyperledger/besu/nat/upnp/OkHttpStreamClient.java#L53
https://github.com/hyperledger/besu/blob/main/besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java#L1922

### Steps to Reproduce 
1. Temporarily add `'-Xlint:deprecation'` to `options.compilerArgs` in the project you want to clean up.
2. rebuild and look for warnings!

**Comment by natashashams** [comment]
available to work on still?

**Comment by natashashams** [comment]
@jflo can I take this up (from vGHC)?

**Comment by macfarla** [comment]
👋  Hi @natashashams are you still interested in working on this?

**Comment by sandrawangyx** [comment]
Hi @macfarla is anyone working on this issue atm? I am happy to help out with other issues.

**Comment by macfarla** [comment]
@sandrawangyx would love your help on this one, thanks! Have assigned you.

**Comment by sandrawangyx** [comment]
Thanks @macfarla, I've created a PR for it. It seems like it's going to be a big PR. (https://github.com/hyperledger/besu/pull/3511)
Before I proceed any further, can I get a brief review from the maintainers? just want to make sure that I am on the right track since this is my first contribution to besu.

**Comment by macfarla** [comment]
Added some comments @sandrawangyx - looks pretty good so far!

**Comment by antonydenyer** [comment]
There are a lot of warnings for different things! 
I'd recommend separate prs for each deprecation/concern e.g internal renames, okhttp etc rather than one large pr.

**Comment by sandrawangyx** [comment]
another PR is (https://github.com/hyperledger/besu/pull/3536)
