### ISSUE TITLE
Link for Release 21.7.4 download returns 404

### ISSUE THREAD

**Issue by dani-lp** [hyperledger/besu#2778]
The download link for the [21.7.4 release](https://github.com/hyperledger/besu/releases/tag/21.7.4) returns a [404 error](https://hyperledger.jfrog.io/native/besu-binaries/besu/21.7.4/besu-21.7.4.zip). The link should be 'https://hyperledger.jfrog.io/ui/native/besu-binaries/besu/21.7.4/besu-21.7.4.zip'

**Comment by jflo** [comment]
Thank you, this has been corrected.
