### ISSUE TITLE
Update basefee implementation to use Uint256 rather than long

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2785]
Besu's implementation of EIP1559 is using a long instead of Uint256 for baseFee.  This is not likely to be a problem in the near future since baseFee would have to be in excess of 9 eth to cause an overflow, but we should match the types in the spec.

Acceptance criteria:
* update implementation and tests to use Uint256 baseFee

**Comment by fab-10** [comment]
@garyschulte should not we use `Wei` instead of `UInt256` since it is a fee?
