### ISSUE TITLE
--config-file does not resolve ~ for home directory

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2786]
### Description
As a besu dev, I want --config-file CLI option to resolve ~ to my home directory so that I don't have to do it manually. 

### Acceptance Criteria
`besu git:(fix-BESU_CONFIG_FILE) besu --config-file=~/path/to/besu.conf`
should resolve the ~ to user's home directory

### Steps to Reproduce (Bug)
`besu git:(fix-BESU_CONFIG_FILE) besu --config-file=~/path/to/besu.conf`

**Expected behavior:** [What you expect to happen]
`besu git:(fix-BESU_CONFIG_FILE) besu --config-file=~/path/to/besu.conf`
should resolve the ~ to user's home directory

**Actual behavior:** [What actually happens]
```
➜  besu git:(fix-BESU_CONFIG_FILE) besu --config-file=~/workspace/besu-local-nodes/config/besu/besu1.conf
Unable to read TOML configuration, file not found.

To display full help:
besu [COMMAND] --help
➜  besu git:(fix-BESU_CONFIG_FILE) ll ~/workspace/besu-local-nodes/config/besu/besu1.conf
-rw-r--r--  1 sallymacfarlane  staff   1.4K 21 Sep 10:55 /Users/sallymacfarlane/workspace/besu-local-nodes/config/besu/besu1.conf
```

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
besu/v21.10.0-RC1-dev-2abc7074/osx-x86_64/oracle_openjdk-java-11
* Java version: [`java -version`]
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
* OS Name & Version: [`cat /etc/*release`]
MacOS 11.6
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by ajsutton** [comment]
The expansion of `~` is done by the shell and it explicitly doesn't expand it when it's in the middle of a CLI arg.  You can just use `--config-file ~/workspace/...` and it will be expanded - the `=` is not necessary and not recommended for exactly this reason.

While some software does re-implement parts of the shell expansion logic, I wouldn't recommend it as it's significantly difficult to get right and can create other unexpected issues when the value was escaped on the command line and then expanded incorrectly by the software.  ie `--config-file \~foo.xml` should use `~foo.xml` as the filename and not expand the `~` but that's impossible to get right within the program.

**Comment by macfarla** [comment]
ok that makes sense
