### ISSUE TITLE
Change returnData value from null to "0x" in traces

### ISSUE THREAD

**Issue by baptiste-marchand** [hyperledger/besu#2799]
### Description
The returnData values from Geth and Besu are different in case of null value.
To simplify trace debugging, having the same conventions would be better.

### Steps to Reproduce
1. Call the "debug_standardTraceBlockToFile" JSON RPC API method on block containing transactions
2. Open the given trace

**Expected behavior:** "returnData":"0x"

**Actual behavior:** "returnData":null

**Frequency:** Everytime

### Versions (Add all that apply)
* Software version: 21.7.4

**Comment by atoulme** [comment]
Why did you close the issue?

**Comment by baptiste-marchand** [comment]
> Why did you close the issue?
Bad handling... I'm doing a PR for this issue

**Comment by shemnon** [comment]
This appears to have been fixed, prior to PR#2790 when the EVM package was moved.
