### ISSUE TITLE
Improve the way gas is estimated via the API eth_estimateGas

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#2808]
If the network has a pretty low volume of txs atm, if someone publish a tx with a very high gasPrice (70 gwei, which is more appropriate for mainnet, whereas our pricing should look more like .0001 gwei as we have a low volume of txs) and if it's the only tx in the sample used by estimateGas() this API call will end up return the 70 gwei as the estimated price, which is too high.

**Comment by matkt** [comment]
I want to say no for 1559 transactions.

**Comment by matt-nelson-csi** [comment]
Closing as stale for post-1559 world. Can re-open if significant need elsewhere.
