### ISSUE TITLE
Move errorprone checks into its own repository

### ISSUE THREAD

**Issue by usmansaleem** [hyperledger/besu#2855]
### Description
Move errorprone checks into its own repository so that it can be published as a library and can be imported by Besu gradle build script.

### Acceptance Criteria
* https://github.com/hyperledger/besu-errorprone-checks
* errorprone checks code is moved into its own repository
* errorprone checks is imported as library

**Comment by siladu** [comment]
Not planning to do this. Repo will be archived.
