### ISSUE TITLE
Merge: Implement backwards sync

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2912]
### Description
When besu is running as an execution client, the normal 'forward' sync process should stop at terminal-total-difficulty.  However, post-merge besu needs to do a 'backwards sync' and fetch blocks backward from a given block hash until we reach a common ancestor.

Specs are still a moving target on this but this behavior is specified :
* https://github.com/fjl/p2p-drafts/blob/master/merge-sync/merge-sync.md#definitions
* https://github.com/ethereum/execution-apis/blob/main/src/engine/interop/specification.md#engine_executepayload
* https://notes.ethereum.org/@djrtwo/BJxKBaqNF

### Acceptance Criteria
* forward sync until TTD
* backward sync upon executePayload for an unknown header 
* conformance to final sync spec

**Comment by gezero** [comment]
I would like to work on this one.
