### ISSUE TITLE
Merge: Transition Integration Tests

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2915]
### Description
Transition at TTD to the merge consensus mechanism is a critical point and is likely to be encounter edge and adversarial cases.  Besu needs comprehensive coverage of the transition and reorg cases as it relates to TTD. 

For more detail see:

https://eips.ethereum.org/EIPS/eip-3675#terminal-total-difficulty-vs-block-number

### Acceptance Criteria
minimally, integration test cases for
* nominal transition at TTD
* reorg post-TTD but pre-first finalized block / call to engine_forkChoiceUpdated
* attempted post-TTD reorg, post first finalized block

**Comment by garyschulte** [comment]
we could/should leverage kurtosis, but will need to add besu as a supported execution client: 
https://github.com/kurtosis-tech/eth2-merge-kurtosis-module

**Comment by garyschulte** [comment]
https://github.com/parithosh/nightly-kurtosis-test/blob/main/.github/workflows/kurtosis.yml

**Comment by matt-nelson-csi** [comment]
Close in favor of hive
