### ISSUE TITLE
Full sync extremely slow

### ISSUE THREAD

**Issue by adean-consensys** [hyperledger/besu#2932]
### Description
Mainnet full sync is taking multiple weeks - running besu:21.7.2 in an Azure AKS Cluster with 10Gi of memory and 2 CPU cores and 3TB storage dedicated to chain data
25 peers

**Expected behavior:**
Sync to occur within a reasonable amount of time

**Actual behavior:**
Processing about 200 blocks per 40 minutes

### Versions (Add all that apply)
* Software version: `21.7.2`
* Java version: `openjdk version "11.0.11" 2021-04-20`
* OS Name & Version: Docker?
* Kernel Version: `Linux besu-node-0 5.4.0-1059-azure #62~18.04.1-Ubuntu SMP Tue Sep 14 17:53:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Virtual Machine software & version: `Ubuntu 18.04.6 LTS`
* Docker Version: [`containerd://1.4.9+azure`]
* Cloud VM, type, size: [`Azure AKS Standard_D4as_v4`]

### Additional Information

![image](https://user-images.githubusercontent.com/83668448/138122123-a3e82655-a9af-4523-915d-b8cc4b4f4360.png)

![image](https://user-images.githubusercontent.com/83668448/138123507-39c51ef8-2bda-47e6-8e47-0807d2e85e4c.png)

Logs:
```
2021-10-20 12:33:55.784+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13425400 (0xcc2f5263fcf689e9d102d5806ca369476088d68114af9461c507877ff9b1d01e), 1.714 Mg/s, Peers: 25
2021-10-20 12:59:01.764+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13425600 (0xefc9cf23d7fc3226f6f485a7d5921ea57aaa76ee6431ab62f8c78a84be71db72), 2.024 Mg/s, Peers: 25
2021-10-20 13:32:37.342+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13425800 (0xc61bb21c79877516c7824f60854b061d5c261a7154a5ff9991c080782050f4fd), 1.524 Mg/s, Peers: 25
2021-10-20 14:07:40.270+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13426000 (0xe8028f2e7ffdd28677f3e149304a422ea81559bb7d006536f497c8fcf4367f1d), 1.465 Mg/s, Peers: 25
2021-10-20 14:44:26.835+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13426200 (0xa1433c5cc63e8fea55d83efa5f75df38cc5fc27e57aa4ae6d9090602aa8d67eb), 1.402 Mg/s, Peers: 25
```

I've checked metrics, the process is not using much the CPU at all, using about 60% of the memory limit (~6Gi) and storage utilization is very low (see charts).  How can we expedite this sync?

**Comment by adean-consensys** [comment]
Appears that the disk type has some bearing on the speed for which the sync occurs, once we completed the `PipelineChainDownloader` phase, it went into a world state download stage where it got really far behind in syncing.  We restarted the pod and we're syncing again but very slowly, averaging over 4s per block

```
2021-10-29 17:30:25.216+00:00 | EthScheduler-Services-32 (importBlock) | INFO  | FastImportBlocksStep | Completed importing chain segment 13107401 to 13107500, Peers: 26
2021-10-29 17:30:25.216+00:00 | EthScheduler-Services-32 (importBlock) | INFO  | PipelineChainDownloader | Chain download complete
2021-10-29 17:35:28.895+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 254000000 world state nodes. At least 32296960 nodes remaining.
```

![image](https://user-images.githubusercontent.com/83668448/139689121-0c73f81d-2a61-49e8-ba28-18036fedaf48.png)

We're essentially back at the stage we were with the old instance on the slow HDD, CPU util isn't maxed out and there's plenty of memory.  What else can we do to kickstart this thing back into processing quickly?

**Comment by macfarla** [comment]
there is a lot of state to download. It's a bit confusing because we expect fast sync to increase block numbers until it’s close to head, then stall in terms of block numbers - it needs to download the world state before it can continue. On our canary nodes the "stall" period is 5 days + at current mainnet size.

There are metrics around fast sync eg `besu_synchronizer_fast_sync_pivot_block_current`, `besu_synchronizer_world_state_completed_requests_total` and `besu_synchronizer_world_state_pending_requests_current`

If you can add these metrics to your dash, you can see progress of the "download state" step even while "block number" seems stuck.

**Comment by macfarla** [comment]
^ above comment from me relates to `fast sync` whereas this issue is related to `full sync`

**Comment by macfarla** [comment]
Peers stays constant at 25
Average block time is about 6.5 seconds
When it was in fast sync it was in the millisecond range, shot up afterwards
It’s catching up, it’s just really slow.  12 hours ago it was at 327,359 behind and currently it is at 323,504
Is that expected speed for a full sync?

**Comment by adean-consensys** [comment]
Block time chart (not sure what happened mid-10/29 through end-of 10/31, maybe didn't report a value?

![image](https://user-images.githubusercontent.com/83668448/141487197-6c128450-022c-41ac-bf9b-1e2939de004e.png)

**Comment by adean-consensys** [comment]
Checking if there had been any progress on finding out the cause.  Block time average is still 10 seconds, and we're still 218,641 blocks behind.

**Comment by garyschulte** [comment]
is the SSD gettinfg close to full?  the long period of no blocks processing looks a lot like either a rocksdb compaction or heavy SSD garbage collection.  The write performance of SSD drops off significantly when it approaches full.

[ssd performance](https://web.archive.org/web/20210816151518/https://www.seagate.com/tech-insights/lies-damn-lies-and-ssd-benchmark-master-ti/)

how full is the disk?

**Comment by adean-consensys** [comment]
Disk is reporting 37% full, CPU time is averaging under around .6, so it's not doing a whole lot.  How much space do we need to be mindful of for a full besu node?

Prometheus reports around 1k R/W IOPS, 30MB/s read throughput, 250k write throughput.  I assume it should be writing a heckuva lot more if there's still 200k blocks to go?

**Comment by macfarla** [comment]
Other thoughts from @garyschulte 
what is the max number of open files?  mainnet nodes usually have many thousands of rocksdb segments.
when running on a i/o bandwidth constrained machine I have found tweaking these params help:
```
Xplugin-rocksdb-max-background-compactions=1
Xplugin-rocksdb-max-open-files=8192
Xplugin-rocksdb-cache-capacity=67108864
```
I tuned the number of max open files in accordance to the number of rocksdb segments, bumped up the ulimit for max open files, bumped up the cache capacity, and limited the number of concurrent compactions.

if you are experiencing io constraints - those configs helped a lot on a raspi bonsai node.

**Comment by jmcruz1983** [comment]
Any update here?

**Comment by garyschulteog** [comment]
We identified some optimizations in fast sync that makes fast sync retain much more of its world state download progress after a re-pivot.  This fix is in the nightly already and should make it into a release version soon:

https://github.com/hyperledger/besu/pull/3202

**Comment by macfarla** [comment]
Hi @jmcruz1983 @adean-consensys - realise it's been a while but we have made some improvements in peering and syncing (22.1.0 had the fast sync optimisation mentioned above #3202 ). Additionally we are beginning a holistic assessment of peering behavior including any outstanding issues. So we're hoping that either those changes have it fixed already, or that you're able to give us some more info if you're still having related issues?
