### ISSUE TITLE
remove deprecated field: privateTransaction.hash 

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2937]
This field has been deprecated for some time:
  // Caches the hash used to uniquely identify the transaction.
  // This field will be removed in 1.5.0
  @Deprecated(since = "1.4.3")
  protected volatile Hash hash;
- [ ] confirm it can safely be removed
- [ ] changelog entry

**Comment by mohitsaxenaknoldus** [comment]
@macfarla PR: https://github.com/hyperledger/besu/pull/3110

**Comment by macfarla** [comment]
This one is complete!
