### ISSUE TITLE
Use MockitoJUnitRunner for more test classes

### ISSUE THREAD

**Issue by taccatisid** [hyperledger/besu#2951]
### Description
Convert as many test classes as possible to `@RunWith(MockitoJUnitRunner.class)` instead of the default JUnit runner.

This will expose mocked function calls that are not called by the given tests. This mocks should either be deleted (when only mocked in a single test), or prefixed with `lenient()` if the same mock is shared in multiple tests of which only some use it.

This issue should be timeboxed; hard cases should be moved to separate issues.

If tests are identified as ineffective because they do not call a critical mock, this should be flagged (or fixed if easy).

### Acceptance Criteria
* As many test as possible run using `MockitoJUnitRunner`
* Tests classes that do not use `MockitoJUnitRunner` should be marked as such (so that it is easier later on to deal with them)
* Newly failing tests are fixed

**Comment by TheSwarnim** [comment]
Hi @macfarla, please assign this issue to me. I want to work into it.

**Comment by macfarla** [comment]
@TheSwarnim please review PR #3311 which fixes some classes. But there are more to find!

**Comment by TheSwarnim** [comment]
Thanks @macfare for this

**Comment by TheSwarnim** [comment]
Hi @macfarla, can you tell me how can I check that test classes were running after changing. I'm using vscode and not able to run any test before or after completing changes

**Comment by macfarla** [comment]
if you use IntelliJ you can run the exact test in your IDE before and after (recommend!)
however, there is a way to do this on the command line with gradle 
https://docs.gradle.org/current/userguide/java_testing.html#test_filtering
