### ISSUE TITLE
Change blockperiodseconds in Genesis

### ISSUE THREAD

**Issue by damianlluch** [hyperledger/besu#2952]
Hi, to change the block generation time of a project that is already started, I should just stop the nodes and change the blockperiodseconds value in the genesis file and run the nodes again, right? 
thanks

**Comment by sambacha** [comment]
Doesn't quorum use nanoseconds? Wouldn't you have to specify this in the appropriate measurement? Its raft based consensus isn't it. This is the whole reason why there is a separate web3 package for qbft.

**Comment by jframe** [comment]
Both Besu and Quorum use seconds to define the block period. For Besu see https://besu.hyperledger.org/en/latest/HowTo/Configure/Consensus-Protocols/IBFT/#block-time and for Quorum https://docs.goquorum.consensys.net/en/stable/Reference/CLI-Syntax/#istanbulblockperiod.

Besu doesn't currently support a raft based consensus mechanism. Both IBFT2 and QBFT are byzantine fault tolerant style consensus mechanisms.

**Comment by damianlluch** [comment]
We changed the value in genesis and it worked.

**Comment by sambacha** [comment]
> Both Besu and Quorum use seconds to define the block period. For Besu see [besu.hyperledger.org/en/latest/HowTo/Configure/Consensus-Protocols/IBFT/#block-time](https://besu.hyperledger.org/en/latest/HowTo/Configure/Consensus-Protocols/IBFT/#block-time) and for Quorum [docs.goquorum.consensys.net/en/stable/Reference/CLI-Syntax/#istanbulblockperiod](https://docs.goquorum.consensys.net/en/stable/Reference/CLI-Syntax/#istanbulblockperiod).
> 
> Besu doesn't currently support a raft based consensus mechanism. Both IBFT2 and QBFT are byzantine fault tolerant style consensus mechanisms.

Quorum has RAFT consensus which is what I am referring to which does not use seconds, it uses nano seconds. That is a separate issue from changing the fixed blocksPerSeconds, which would invalidate the chain pre-hardfork
