### ISSUE TITLE
Performance testing for onchain privacy groups

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#2959]
Use current quorum-performance (artillery) results as a baseline. Less interested in specific TPS number, more interested in if any particular parameters affect performance (eg does adding a new group member slow things down considerably). 

- [ ] Sending a simple contract to a single user (self)

Performance test scenario: 
- [x] Recommend sending to multiple users - create a group with 2,3,5 members
- [ ] Sending a sequence of transactions (includes check group membership)
- [x] Adding a user to the group after eg 10, 100, 1000 tx

Caliper is not the right tool for this.

**Comment by pinges** [comment]
Document with the results: https://docs.google.com/document/d/1rghb-1602Fvzljx1PlvSb69qqTn7nmX6eV14FN13iFg/edit#
PR for the tools: https://github.com/ConsenSys/quorum-performance/pull/3

**Comment by macfarla** [comment]
TODO: Review Possible improvements and decide whether/what makes sense to implement
Only send the current world state, not all the transactions
Send historic transactions/state in chunks
Ensure that no part of the process causes a time out 
New members pull historic transactions
Add functionality in Tessera to send historic transactions
Enable a Besu node added to a privacy group to continue importing blocks and catch up with the privacy group once “current state” has been created

**Comment by macfarla** [comment]
for review by product team.
