### ISSUE TITLE
Remove code duplication TODO in OnchainPrivacyPrecompiledContract

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#2961]
Remove code duplication TODO in OnchainPrivacyPrecompiledContract

Search for any others and remove.

**Comment by anipaul2** [comment]
Hey, I'm a beginner. Can you please tell me how to get started with these?

**Comment by MadelineMurray** [comment]
hi @anipaul2 - are you still interested in picking this one up?

**Comment by macfarla** [comment]
Hi @anipaul2 sorry I missed your comment here. There is some info on this wiki page about how to get started https://wiki.hyperledger.org/display/BESU/First+contribution - and then join the conversation over in Besu chat if you get stuck https://chat.hyperledger.org/channel/besu :)

**Comment by anipaul2** [comment]
> 

Yeah I'm interested

**Comment by anipaul2** [comment]
> Hi @anipaul2 sorry I missed your comment here. There is some info on this wiki page about how to get started https://wiki.hyperledger.org/display/BESU/First+contribution - and then join the conversation over in Besu chat if you get stuck https://chat.hyperledger.org/channel/besu :)

Thanks @macfarla I'll look into it.
