### ISSUE TITLE
Update Circle-CI executor images

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2963]
### Description
The executors we are using for building besu will be end-of-life on Dec 31, 2021:

https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

~~It seems the latest java convenience image is based on Java-14, so we will need to ensure we are still targeting/building compatible images.  At this time we are still targeting the Java 11 LTS release for the default besu JVM~~

#### Update:
Let's decouple this update from JVM upgrades and just upgrade the container images we use for circle-ci in `besu` and `besu-native`.
The latest cimg for openjdk-11 is `docker pull cimg/openjdk:11.0.12`. 

### Acceptance Criteria
~~* Update to the latest convenience images (cimg/openjdk:14.0)~~
* Ensure builds are compatible with java 11 LTS 
* besu and besu-native circle-ci pipelines should use the SAME cimg to ensure libc compatibility

**Comment by MadelineMurray** [comment]
@garyschulte - is this still needed or has this been fixed?

**Comment by macfarla** [comment]
fixed with issue #2992
