### ISSUE TITLE
change "privacyGroupId" from being a base64 encoded String to a proper class

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#2987]
Using a PrivacyGroupId class has many benefits, one being that as a developer I don't have to remember that the Id is base64 encoded.

**Comment by pinges** [comment]
I was contacted by Matthew Burnes (github: MatthewBurnes) who said that he would like to have a go at it! 
I was not able to assign it to Matthew, so I assigned it to myself instead.

**Comment by macfarla** [comment]
👋 Hi @MatthewBurnes are you still interested in working on this?

**Comment by macfarla** [comment]
closing no longer relevant
