### ISSUE TITLE
Get rid of MutlitenancyPrivacyController

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#2990]
Currently, when multi-tenancy is enabled, the MultitenancyPrivacyController is wrapping the actual PrivacyController to add the checks whether a user is allowed to have access to data from a certain privacy group. This approach has the following problems:

1. When an RPC call needs to access more than one "protected" data the check whether the user should be allowed to access to data from that privacy group is done multiple time. E.g. EeaSendRawTransaction would do the check when validating the private transaction and when creating the pmt payload.

This could be fixed by having group membership checked when  an RPC method is called, instead of when the data is accessed.

**Comment by macfarla** [comment]
We think this is the same as https://github.com/hyperledger/besu/issues/1383

**Comment by frankisawesome** [comment]
Might be a good one for me as a learning opportunity? After my current tickets @pinges ?

**Comment by non-fungible-nelson** [comment]
@macfarla - closing for #1383 - can reopen if this is incorrect.
