### ISSUE TITLE
Improve logging in GetBlockFromPeersTask

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#3010]
### Description
Two canary nodes on different networks (rinkeby, mainnet) both became "stuck" at a particular block.  Logs did not indicate the reason for the failure, but both nodes had a full complement of peers and were unable to download the correct block, and effectively halted.

In both cases, the failures were transient and the nodes were able to proceed normally after a restart.  One node restarted with a required-block parameter, but the other a simple restart was able to remedy.

Discussion led us to believe there is a failure happening in the async networking code that is not getting logged; logging the exception would likely reveal the true source of the problem.

### Acceptance Criteria
* add exceptional completion error logging in DownloadBlockFromPeersTask

### Versions (Add all that apply)
* Software version: 21.10.0-RC4
* Java version: openjdk 11.0.11 2021-04-20 LTS

**Comment by garyschulte** [comment]
relevant log info from rinkeby: 

> {"timestamp":"2021-11-04T15:07:09,868","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #9,585,194 / 29 tx / 0 om / 11,057,880 (36.9
%) gas / (0x7789f1baa15dbee83fd1513f4a19c240b53c8c72f82d7dc848a2270ffb196c0e) in 0.665s. Peers: 21","throwable":""}
{"timestamp":"2021-11-04T15:07:24,055","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0xd66f801978210f15c1....","throwable":""}
{"timestamp":"2021-11-04T15:07:24,158","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0xf2e87b4ef6ebed0c78....","throwable":""}
{"timestamp":"2021-11-04T15:07:24,159","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x57d97b97927ea8a223....","throwable":""}
{"timestamp":"2021-11-04T15:07:24,243","level":"INFO","thread":"nioEventLoopGroup-3-9","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x6d6a2ca92b9b35aca4....","throwable":""}
{"timestamp":"2021-11-04T15:07:24,353","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f 3001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0xf2068a3999fa502981....","throwable":""}
{"timestamp":"2021-11-04T15:07:24,447","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f 3001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x2a1264b8714d4e737f....","throwable":""}
{"timestamp":"2021-11-04T15:07:25,407","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0xf0713e6e2eb05ff948....","throwable":""}
{"timestamp":"2021-11-04T15:07:25,431","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #9,585,195 / 58 tx / 0 om / 29,933,014 (100. 0%) gas / (0xff59f3eb3bc6a5319fa622b979eb878ca1ad8cb4456cafcd662fb3632f88db76) in 1.052s. Peers: 20","throwable":""}
{"timestamp":"2021-11-04T15:07:25,599","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x16f43c318a7462739a....","throwable":""}
{"timestamp":"2021-11-04T15:07:25,971","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x4789223bf221f75451....","throwable":""}
{"timestamp":"2021-11-04T15:07:26,080","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x24ec5694e15a213cd9....","throwable":""}
{"timestamp":"2021-11-04T15:07:26,093","level":"INFO","thread":"nioEventLoopGroup-3-7","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x7e597a4083ee7ea841....","throwable":""}
{"timestamp":"2021-11-04T15:07:26,105","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f 3001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x2ea8af844a162c3220....","throwable":""}
{"timestamp":"2021-11-04T15:07:26,220","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x41b9ed83530e9acc11....","throwable":""}
{"timestamp":"2021-11-04T15:07:26,313","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x1a59668dec6a6c0f2d....","throwable":""}
{"timestamp":"2021-11-04T15:07:26,410","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"GetBlockFromPeerTask","message":"Failed to download block 0xcf1493b886fc680b81020f3 001553f40c6e7e3690c3b184d8f5e2280a6c05ab9 from peer Peer 0x43af36b53d004ad59e....","throwable":""}
{"timestamp":"2021-11-04T15:07:40,271","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"GetBlockFromPeerTask","message":"Failed to download block 0x28bebf436d736af09902fbe 81c645e50b5d90d161e56ae675f744d76abc7cdd1 from peer Peer 0xd66f801978210f15c1....","throwable":""}
{"timestamp":"2021-11-04T15:07:40,455","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BlockPropagationManager","message":"Saving announced block 9585196 (0x28bebf436d736 af09902fbe81c645e50b5d90d161e56ae675f744d76abc7cdd1) for future import","throwable":""}
{"timestamp":"2021-11-04T15:07:54,203","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"GetBlockFromPeerTask","message":"Failed to download block 0xae4ef40ad993940b7c404b3 7fd70ac4f84dbbc6f271ece20dc18a6bcad67db06 from peer Peer 0xf2e87b4ef6ebed0c78....","throwable":""}
{"timestamp":"2021-11-04T15:07:54,204","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"GetBlockFromPeerTask","message":"Failed to download block 0xae4ef40ad993940b7c404b3 7fd70ac4f84dbbc6f271ece20dc18a6bcad67db06 from peer Peer 0x57d97b97927ea8a223....","throwable":""}

**Comment by macfarla** [comment]
mainnet-large was stuck here
```
{"timestamp":"2021-11-04T13:17:20,027","level":"INFO","thread":"EthScheduler-Workers-0","class":"PersistBlockTask","message":"Imported #13,550,419 / 175 tx / 0 om / 12,339,143 (4
1.1%) gas / (0xdcbaafcd1e0b3c4f696014de8812da078dac23540889f93239a37b5f4024b979) in 7.142s. Peers: 50","throwable":""}
{"timestamp":"2021-11-04T13:17:20,027","level":"INFO","thread":"EthScheduler-Workers-0","class":"BlockPropagationManager","message":"Imported 1 pending blocks","throwable":""}
{"timestamp":"2021-11-04T13:17:24,683","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0x45f92c8d8a7a4f1844....","throwable":""}
{"timestamp":"2021-11-04T13:17:24,762","level":"INFO","thread":"nioEventLoopGroup-3-9","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xb8b64fc59405c01ca8....","throwable":""}
{"timestamp":"2021-11-04T13:17:24,888","level":"INFO","thread":"nioEventLoopGroup-3-7","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xfc8d10a54cd1234b37....","throwable":""}
{"timestamp":"2021-11-04T13:17:25,083","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xaeea4de4744b8bc9be....","throwable":""}
{"timestamp":"2021-11-04T13:17:25,442","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 13550421 (0xc47f757383d
2a9ac8743e2f55f2f075687369c022a422b8c16e51f97ade54b52) for future import","throwable":""}
{"timestamp":"2021-11-04T13:17:26,272","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 13550422 (0xc0aeef7e70e
b13cc2fd449a4ecf6f6dc4e5e14afcfe0536d9719a14adbcbf8e3) for future import","throwable":""}
{"timestamp":"2021-11-04T13:17:30,083","level":"INFO","thread":"EthScheduler-Timer-0","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d136
a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xc9774f6bbd4ff18c6f....","throwable":""}
{"timestamp":"2021-11-04T13:17:30,783","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 13550423 (0x2cb1c799e31
769404a27211e4ed49c0346869ad501faef4731151e216e97b30e) for future import","throwable":""}
```

**Comment by garyschulte** [comment]
relevant logs from mainnet node @13550420
```
{"timestamp":"2021-11-04T13:17:20,027","level":"INFO","thread":"EthScheduler-Workers-0","class":"PersistBlockTask","message":"Imported #13,550,419 / 175 tx / 0 om / 12,339,143 (4
1.1%) gas / (0xdcbaafcd1e0b3c4f696014de8812da078dac23540889f93239a37b5f4024b979) in 7.142s. Peers: 50","throwable":""}
{"timestamp":"2021-11-04T13:17:20,027","level":"INFO","thread":"EthScheduler-Workers-0","class":"BlockPropagationManager","message":"Imported 1 pending blocks","throwable":""}
{"timestamp":"2021-11-04T13:17:24,683","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0x45f92c8d8a7a4f1844....","throwable":""}
{"timestamp":"2021-11-04T13:17:24,762","level":"INFO","thread":"nioEventLoopGroup-3-9","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xb8b64fc59405c01ca8....","throwable":""}
{"timestamp":"2021-11-04T13:17:24,888","level":"INFO","thread":"nioEventLoopGroup-3-7","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xfc8d10a54cd1234b37....","throwable":""}
{"timestamp":"2021-11-04T13:17:25,083","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d13
6a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xaeea4de4744b8bc9be....","throwable":""}
{"timestamp":"2021-11-04T13:17:25,442","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 13550421 (0xc47f757383d
2a9ac8743e2f55f2f075687369c022a422b8c16e51f97ade54b52) for future import","throwable":""}
{"timestamp":"2021-11-04T13:17:26,272","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 13550422 (0xc0aeef7e70e
b13cc2fd449a4ecf6f6dc4e5e14afcfe0536d9719a14adbcbf8e3) for future import","throwable":""}
{"timestamp":"2021-11-04T13:17:30,083","level":"INFO","thread":"EthScheduler-Timer-0","class":"GetBlockFromPeerTask","message":"Failed to download block 0x0f0a2dd944d2c5afda4d136
a66941aaf72bef05d57d41bdfbb970c583e6b50a7 from peer Peer 0xc9774f6bbd4ff18c6f....","throwable":""}
{"timestamp":"2021-11-04T13:17:30,783","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 13550423 (0x2cb1c799e31
769404a27211e4ed49c0346869ad501faef4731151e216e97b30e) for future import","throwable":""}
```

**Comment by macfarla** [comment]
TeamRevenant - timebox investigation into this: half a day. Can we reproduce it.

**Comment by pinges** [comment]
Mainnet Block Number is 13550420, Block Hash 0x0f0a2dd944d2c5afda4d136a66941aaf72bef05d57d41bdfbb970c583e6b50a7
