### ISSUE TITLE
Threadlock

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#3013]
when I run besu first time it works. 
when I run besu second time it threadlocks

LOG: http://retesteth.ethdevops.io/web/logs/besu-11-06-21-1636198018
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

**Comment by MadelineMurray** [comment]
Thanks for raising @winsvega - we'll look at in our current sprint.

**Comment by macfarla** [comment]
This is an issue with SecureRandom blocking. Are you running in docker (less entropy available on virtual machines)? 
If you can use /dev/urandom (non-blocking) rather than /dev/random (blocking) that should prevent this error.

**Comment by pinges** [comment]
There is a system property (java.security.egd) and a security property (securerandom.source) that can be used to change the behaviour in terms of entropy. As far as I remember it depends on which jdk you are using and maybe even which security provider you are using on what these properties do.

**Comment by winsvega** [comment]
> This is an issue with SecureRandom blocking. Are you running in docker (less entropy available on virtual machines)? 
> If you can use /dev/urandom (non-blocking) rather than /dev/random (blocking) that should prevent this error. 
> 

No docker. I build besu locally.
How do I tell it to use dev/urandom ?

**Comment by matkt** [comment]
you can check on this website there are more informations https://www.baeldung.com/java-security-egd

**Comment by taccatisid** [comment]
https://github.com/hyperledger/besu-docs/pull/867 documents this issue and how to fix it from the user side.

https://github.com/hyperledger/besu-native/pull/51 fixes the need for blocking randomness in the secp256 curve context--the code that lead to the thread block observed in this ticket. We might however block in other code locations.
