### ISSUE TITLE
Retrieve ENR via API

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#3050]
### Description
Currently there is no easy way to recover the [ENR (Ethereum Node Record)](https://eips.ethereum.org/EIPS/eip-778) of a Besu node. It can only be recovered in the log output, right after the start.

It would be convenient to retrieve it via API. One potential use case would be to retrieve the ENR of a node and check if it is included in [discv4-dns-lists](https://github.com/ethereum/discv4-dns-lists) of the EF automatically for regular checks.

Option 1: Extending the `admin_nodeInfo` RPC call:
Even though there does not exist any specification, it is at least implemented by [geth](https://geth.ethereum.org/docs/rpc/ns-admin#admin_nodeinfo)  and [Nethermind](https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/admin#admin_nodeinfo) as well. Some libraries like [web3j](https://javadoc.io/doc/org.web3j/core/latest/org/web3j/protocol/core/methods/response/admin/AdminNodeInfo.html) and [web3.py](https://web3py.readthedocs.io/en/v4.0.0/web3.admin.html#web3.admin.nodeInfo) support it as well. Extending it should be coordinated with the other clients. A proposal has been posted on the json-rpc-api channel on the Eth R&D Discord channel.

Option 2: Creating a new RPC endpoint:
This would not be needed to be coordinated with other clients and would avoid potential bugs with existing tools when they receive an unexpected field in the response of an `admin_nodeInfo` call. The downside would be of course that it would only supported by Besu.
We were thinking to call it `admin_enrInfo`, to use a similar naming pattern as `admin_nodeInfo`.

### Acceptance Criteria
* Retrieve ENR via API

**Comment by matt-nelson-csi** [comment]
Hey @daniellehrner - where did this end up with regard to #3051?

**Comment by daniellehrner** [comment]
Closing it, because there seems to be no need anymore for it.
