### ISSUE TITLE
on

### ISSUE THREAD

**Issue by diamantisk** [hyperledger/besu#3072]
### Description
As an [Actor], I want [feature] so that [why]. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by MadelineMurray** [comment]
hi @diamantisk - did you mean to include details in this issue?  Or raised mistakenly?

**Comment by sajz** [comment]
I'll go ahead and close this one. @diamantisk feel free to raise a new issue if need be.
