### ISSUE TITLE
RLP subcommand to decode BFT RLP extra data

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#3074]
A subcommand to Besu similar to the rlp encode but decoding to display the data in the rlp extra data. This would be very useful for displaying the details of an existing extra data to confirm it has the correct validators.

**Acceptance Critieria**
* Add rlp decode command that will output the contents of the BFT encoded RLP extra data
* Must support decoding of IBFT legacy, IBFT2 and QBFT extra data formats

**Comment by matthew1001** [comment]
I think this can be closed as PR https://github.com/hyperledger/besu/pull/6895 has merged
