### ISSUE TITLE
Replace enclave in Unit Tests with mock

### ISSUE THREAD

**Issue by mark-terry** [hyperledger/besu#3083]
### Description
The Unit Tests are currently instantiating the whole Enclave (Orion / Tessera) when it is likely more suitable to use a mock in these cases.

### Acceptance Criteria
Enclaves replaced with mock in Unit Tests

**Comment by irenejoeunpark** [comment]
Hi @mark-terry, Can I work on this issue?

**Comment by macfarla** [comment]
Hi @irenejoeunpark we have actually just started work on this one in our team. Excited to have you find an issue to start on though - how about this one https://github.com/hyperledger/besu/issues/1273
