### ISSUE TITLE
Merklee threes in Besu

### ISSUE THREAD

**Issue by damianlluch** [hyperledger/besu#3084]
Hi, we have a problem with our Besu nodes, they run out of space after a while, they consume a lot of disk space. I have read somewhere that with the use of Merklee Trees it is possible to solve this issue. I have not found anything in the documentation about this issue, is it possible with Hyperledger Besu to work with this technology?

Thanks

**Comment by one-three-three-seven** [comment]
Hi, I think what you are searching is the `--Xdata-storage-format=BONSAI` argument. That's still an experimental feature and not recommended for production. You can find experimental/unstable features by usign the `--Xhelp` flag.

https://consensys.net/blog/news/bonsai-tries-a-big-update-for-small-state-storage-in-hyperledger-besu/

**Comment by sajz** [comment]
@damianlluch does this answer your question?
