### ISSUE TITLE
Update exsiting genesis file on the private network for compatible istanbulForkBlock and berlinForkBlock and londonForkBlock 

### ISSUE THREAD

**Issue by eu09** [hyperledger/besu#3091]
Because I found on my private chain it can't compatible the opcode for  selfbalance  , so  how can we update the contents on my existing genesis for compatible istanbulForkBlock and berlinForkBlock and londonForkBlock by "transitions" ? 

My existing  genesis file
{
  "config" : {
    "chainId" : 2021,
    "constantinoplefixblock" : 0,
    "contractSizeLimit": 2147483647,
    "ibft2" : {
      "blockperiodseconds" : 2,
      "epochlength" : 30000,
      "requesttimeoutseconds" : 10,
      "blockreward": "5000000000000000",
      "miningbeneficiary": "0xe0275e0cf831d5a74089e1a66c810b57891c2d85"
    }
  },
  "nonce" : "0x0",
  "timestamp" : "0x58ee40ba",
  "gasLimit" : "0x1fffffffffffff",
  "difficulty" : "0x1",
  "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase" : "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "01a6d1dd2171a45e6a3d3dc52952b40be413fa93" : {
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "0xad78ebc5ac6200000"
    },
    "4f0d0ed3755381f703f385a2c2ec5508e0b7e5da" : {
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "80000000000000000000000"
    },
    "5c28178b275657c0b71f1513a239705605988bd4" : {
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "90000000000000000000000"
    }
  },
  "extraData" : "0xf8d2a00000000000000000000000000000000000000000000000000000000000000000f8a8944f0d0ed3755381f703f385a2c2ec5508e0b7e5da94bf48277a2700bbd5c107f4a8317fe960bf25e02494fc638101f646aef1fc921478bce1f35e9071bf7b949c4893a042a3968448d4f074f65a1b13216121ec9471313d00ea729de47e1c288d9e39e8af990f3e5c9401a6d1dd2171a45e6a3d3dc52952b40be413fa93945c28178b275657c0b71f1513a239705605988bd49486cc50976da37da2e83092e695d0cc9133153b2f808400000000c0"
}

Can I using transitions to update the my genesis block as following input 

{
  "config" : {
    "chainId" : 2021,
    "constantinoplefixblock" : 0,
    
    "contractSizeLimit": 2147483647,
    "ibft2" : {
      "blockperiodseconds" : 2,
      "epochlength" : 30000,
      "requesttimeoutseconds" : 10,
      "blockreward": "5000000000000000",
      "miningbeneficiary": "0xe0275e0cf831d5a74089e1a66c810b57891c2d85"
    },
    "transitions" : {
      "config": [
      {
        "block": 9701480,
        "istanbulForkBlock": "0x9701480"
       "berlinForkBlock" : "0x9701481"
       "londonForkBlock" : "0x9701482"
      }
      ]
   }
  },
  "nonce" : "0x0",
  "timestamp" : "0x58ee40ba",
  "gasLimit" : "0x1fffffffffffff",
  "difficulty" : "0x1",
  "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase" : "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "01a6d1dd2171a45e6a3d3dc52952b40be413fa93" : {
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "0xad78ebc5ac6200000"
    },
    "4f0d0ed3755381f703f385a2c2ec5508e0b7e5da" : {
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "80000000000000000000000"
    },
    "5c28178b275657c0b71f1513a239705605988bd4" : {
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "90000000000000000000000"
    }
  },
  "extraData" : "0xf8d2a00000000000000000000000000000000000000000000000000000000000000000f8a8944f0d0ed3755381f703f385a2c2ec5508e0b7e5da94bf48277a2700bbd5c107f4a8317fe960bf25e02494fc638101f646aef1fc921478bce1f35e9071bf7b949c4893a042a3968448d4f074f65a1b13216121ec9471313d00ea729de47e1c288d9e39e8af990f3e5c9401a6d1dd2171a45e6a3d3dc52952b40be413fa93945c28178b275657c0b71f1513a239705605988bd49486cc50976da37da2e83092e695d0cc9133153b2f808400000000c0"
}

**Comment by jframe** [comment]
Transitions are only used to modify configuration on the consensus mechanism for IBFT, IBFT2 or QBFT. They cannot be used to change the network protocol.

To change network protocol you need to add the milestone blocks to the config section https://besu.hyperledger.org/en/latest/Reference/Config-Items/#milestone-blocks

This page has more details on how to upgrade the protocol for a private network https://besu.hyperledger.org/en/latest/HowTo/Upgrade/Upgrade-Protocol/

**Comment by eu09** [comment]
But we are using a private network , and the last block no is 9702187 , so we just add following content to update the protocol  ? 

    "istanbulForkBlock" : 9702188,
    "berlinForkBlock" : 9702190,
    "londonForkBlock" : 9702195,

**Comment by jframe** [comment]
That looks correct. You just need to ensure that this is for a future block and that all nodes are restarted to get this config before the block is reached.

**Comment by eu09** [comment]
But we still encode a problem when call selfbalance . Here is the contract we using .

pragma solidity =0.6.6;

contract ChainID {
    function get() external pure returns (uint256) {
        uint256 chainID;
        assembly {
            chainID := chainid()
        }
        return chainID;
    }

    function getWithGas() external returns (uint256) {
        uint256 chainID;
        assembly {
            chainID := chainid()
        }
        return chainID;
    }

    function bal() external view returns (uint256) {
        return address(this).balance;
    }

    function balWithGas() external returns (uint256) {
        return address(this).balance;
    }
}

The Output 
34/35) JUMPDEST
  PC = 109 = 0x6d

4978594 gas remaining

ChainID.sol:

22:     }
23:
24:     function balWithGas() external returns (uint256) {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

debug(dev:0x38bb825b...)>

Stack:
  00000000000000000000000000000000000000000000000000000000224312f5 (1 from top)
  0000000000000000000000000000000000000000000000000000000000000051 (top)

(35/35) SELFBALANCE
  PC = 110 = 0x6e

4978593 gas remaining

ChainID.sol:

23:
24:     function balWithGas() external returns (uint256) {
25:         return address(this).balance;
                   ^^^^^^^^^^^^^^^^^^^^^

debug(dev:0x38bb825b...)>

Transaction halted with a RUNTIME ERROR.

There was no revert message.  This may be due to an in intentional halting expression, such as assert(), revert(), or require(), or could be due to an unintentional exception such as out-of-gas exceptions.
Please inspect your transaction parameters and contract code to determine the meaning of this error.

**Comment by eu09** [comment]
I found the root case for above issue , because I mistyped the protocol name as above 

"istanbulForkBlock" : 9702188,
"berlinForkBlock" : 9702190,
"londonForkBlock" : 9702195, 

it should be 
   "istanbulBlock" : 9702188,
    "berlinBlock" : 9702190,
    "londonBlock" : 9702195
