### ISSUE TITLE
Validate that blockperiodseconds is set to a positive integer

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#3093]
0 or decimal values should yield an error on startup.

blockperiodseconds is configured in the genesis file, e.g.
https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/IBFT/#genesis-file
https://besu.hyperledger.org/en/21.10.2/Tutorials/Private-Network/Create-IBFT-Network/

**Comment by lucassaldanha** [comment]
@georgep9 is looking into this ticket.
