### ISSUE TITLE
After upgrade the protocol to london and Arrowglacier on our "private chain" then i popup a error message when it reach defined milestone

### ISSUE THREAD

**Issue by eu09** [hyperledger/besu#3096]
We are using IBFT2 on private chain , but wanna upgrade our protocol to archive london and Arrowglacier standard , then it report below error message , so I asking how to setup basefee on IBFT2 ? 

 {"timestamp":"2021-11-22T20:59:18,002","container":"f92fb662a9ac","level":"INFO","thread":"pool-9-thread-1","class":"GasLimitRangeAndDeltaValidationRule","message":"Invalid block header: basefee should not be present in a block without a base fee market","throwable":""}
today at 04:59  {"timestamp":"2021-11-22T20:59:18,003","container":"f92fb662a9ac","level":"INFO","thread":"pool-9-thread-1","class":"MessageValidator","message":"Invalid Proposal message, block did not pass validation.","throwable":""}
today at 04:59  {"timestamp":"2021-11-22T20:59:26,239","container":"f92fb662a9ac","level":"INFO","thread":"pool-9-thread-1","class":"GasLimitRangeAndDeltaValidationRule","message":"Invalid block header: basefee should not be present in a block without a base fee market","throwable":""}
today at 04:59  {"timestamp":"2021-11-22T20:59:26,239","container":"f92fb662a9ac","level":"INFO","thread":"pool-9-thread-1","class":"MessageValidator","message":"Invalid Proposal message, block did not pass validation.","throwable":""}
today at 04:59  {"timestamp":"2021-11-22T20:59:46,311","container":"f92fb662a9ac","level":"INFO","thread":"pool-9-thread-1","class":"GasLimitRangeAndDeltaValidationRule","message":"Invalid block header: basefee should not be present in a block without a base fee market","throwable":""}
today at 04:59  {"timestamp":"2021-11-22T20:59:46,311","container":"f92fb662a9ac","level":"INFO","thread":"pool-9-thread-1","class":"MessageValidator","message":"Invalid Proposal message, block did not pass validation.","throwable":""}

**Comment by siladu** [comment]
Hi @eu09, thanks for the report :)

We have an open issue which should fix this for you: https://github.com/hyperledger/besu/issues/2714
It is on our backlog so a fix is coming, although I can't give an exact timescale at this point.

In the meantime, you can configure IBFT to use an earlier milestone, e.g. `muirglacierblock` as shown here: https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/IBFT/#genesis-file

PR contributions are also very welcome :)
