### ISSUE TITLE
Bft mining beneficiary to be configurable using transitions

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#3115]
Make the mining beneficiary configurable using the transitions mechanism.

**Acceptance Criteria**
- Mining beneficiary can be changed at a specific block for IBFT2
- Mining beneficiary can be changed at a specific block for QBFT

**Comment by jframe** [comment]
Some questions to consider
* Do all validator nodes have to have the same mining beneficiary defined in the BFT config?
* Can the existing coinbase settings and RPCs be used manage this instead of adding a transition for this property?

**Comment by nithronium** [comment]
> * Do all validator nodes have to have the same mining beneficiary defined in the BFT config?

I believe every validator should have the same mining beneficiary defined, else they would create a block where the reward is paid to themselves which would create consensus problems.

**Comment by ryanjjones10** [comment]
test
