### ISSUE TITLE
Change payloadId of engine_forkchoiceUpdatedV1 API to fixed 8 bytes

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#3125]
InterOp testing between Teku and Besu as uncovered an problem with the response of the engine_forkchoiceUpdatedV1 API call. The payloadId needs always to be 8 bytes long, right now it is trimmed.

Originally reported in Teku: https://github.com/ConsenSys/teku/issues/4700

**Comment by garyschulte** [comment]
fixed by #3127
