### ISSUE TITLE
Logging improvements to diagnose Rinkeby deadlock

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#3134]
Logging improvements: Caveman debugging is often a superior technique when trying to suss out concurrency issues. We should prepare a build for running on rinkeby that offers:

1. Thread names included in logging output. Pretty sure this is already done.
2. More descriptive names for threads if possible. Would be helpful to identify block handling threads from peer handling threads as just an example.
3. Analysis on what packages are likely to contribute to the concurrency problem, and make sure they are turned up to DEBUG or TRACE on any nodes we are monitoring for the problem.
4. Addition of more logging statements directly in the code. Of most interest would be anything we think would notify a parked thread.

**Comment by fab-10** [comment]
We can close this, since the Rinkeby issue is now solved, it was not due to a deadlock, but to some block sync issues, and improved logs were added to solve those issues
