### ISSUE TITLE
Invalid block header

### ISSUE THREAD

**Issue by tiagocmachado** [hyperledger/besu#3174]
### Description
I'm try to sync from scratch eth mainnet but getting the following issue, all the sync went fine until now

### START COMMAND
./besu/bin/besu --network=mainnet --sync-mode=FAST --pruning-enabled=true --metrics-enabled --rpc-http-enabled

### ERROR

> Dec 14 17:40:53 node-1 besu[2582654]: 2021-12-14 17:40:53.134+01:00 | EthScheduler-Services-5 (importBlock) | INFO  | CalculatedDifficultyValidationRule | Invalid block header: difficulty 11875615030204850 does not equal expected difficulty 11875889639676338
Dec 14 17:40:53 node-1 besu[2582654]: 2021-12-14 17:40:53.141+01:00 | EthScheduler-Services-5 (importBlock) | WARN  | PipelineChainDownloader | Invalid block detected.  Disconnecting from sync target. Failed to import block: Invalid block at #13773000 (0x594e4880f077ff9cf01500976d8c0b47cc8d3c77995860353e222a334b8060ad)
Dec 14 17:40:53 node-1 besu[2582654]: 2021-12-14 17:40:53.141+01:00 | EthScheduler-Services-5 (importBlock) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.
Dec 14 17:40:53 node-1 besu[2582654]: java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #13773000 (0x594e4880f077ff9cf01500976d8c0b47cc8d3c77995860353e222a334b8060ad)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
Dec 14 17:40:53 node-1 besu[2582654]:         at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
Dec 14 17:40:53 node-1 besu[2582654]:         at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Dec 14 17:40:53 node-1 besu[2582654]:         at java.base/java.lang.Thread.run(Thread.java:829)
Dec 14 17:40:53 node-1 besu[2582654]: Caused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #13773000 (0x594e4880f077ff9cf01500976d8c0b47cc8d3c77995860353e222a334b8060ad)
Dec 14 17:40:53 node-1 besu[2582654]:         at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:55)
Dec 14 17:40:53 node-1 besu[2582654]:         at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)
Dec 14 17:40:53 node-1 besu[2582654]:         at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
Dec 14 17:40:53 node-1 besu[2582654]:         at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
Dec 14 17:40:53 node-1 besu[2582654]:         ... 5 more

### Versions
* Software version: 21.10.3
* Java version: 11.0.11
* OS Name & Version: ubuntu 20.04

**Comment by matkt** [comment]
Hello thanks for you ticket. Do you have the hash of the pivot block ?

**Comment by tiagocmachado** [comment]
@matkt the pivot block wash 13772986
But the issue is on the glacier arrow fork block

**Comment by matkt** [comment]
thank you. do you have the hash instead of the block number. this is to see if your pivot block was on the canonical chain.

**Comment by tiagocmachado** [comment]
@matkt how can I get the hash? I have the same issue on different nodes. None of them can surpass this block

**Comment by tiagocmachado** [comment]
@matkt This just happened today

`Dec 27 07:21:07 node-1 besu[624]: 2021-12-27 07:21:07.391+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 1017000000 world state nodes. At least 31136 nodes remaining.
Dec 27 07:21:53 node-1 besu[624]: 2021-12-27 07:21:53.294+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | DefaultSynchronizer | Fast sync completed successfully with pivot block 13772986
Dec 27 07:21:53 node-1 besu[624]: 2021-12-27 07:21:53.313+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | FullSyncDownloader | Starting full sync.
Dec 27 07:21:53 node-1 besu[624]: 2021-12-27 07:21:53.316+00:00 | StatePruning-0 | INFO  | Pruner | Starting Pruner.
Dec 27 07:21:53 node-1 besu[624]: 2021-12-27 07:21:53.353+00:00 | EthScheduler-Services-7 (requestCompleteTask) | INFO  | WorldDownloadState | Finished downloading world state from peers
Dec 27 07:21:53 node-1 besu[624]: 2021-12-27 07:21:53.820+00:00 | nioEventLoopGroup-3-7 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x30bf0f746a98cfe53f... at block 13772986
Dec 27 07:23:21 node-1 besu[624]: 2021-12-27 07:23:21.584+00:00 | EthScheduler-Services-23 (importBlock) | INFO  | Pruner | Begin marking used nodes for pruning. Block number: 13772987 State root: 0xa6caebcee8ba58332d297dd6cb4fc434570917a241f0c82097517fb76ede6e2d
Dec 27 07:23:43 node-1 besu[624]: 2021-12-27 07:23:43.283+00:00 | EthScheduler-Services-23 (importBlock) | INFO  | CalculatedDifficultyValidationRule | Invalid block header: difficulty 11875615030204850 does not equal expected difficulty 11875889639676338
Dec 27 07:23:43 node-1 besu[624]: 2021-12-27 07:23:43.300+00:00 | EthScheduler-Services-23 (importBlock) | WARN  | PipelineChainDownloader | Invalid block detected.  Disconnecting from sync target. Failed to import block: Invalid block at #13773000 (0x594e4880f077ff9cf01500976d8c0b47cc8d3c77995860353e222a334b8060ad)
Dec 27 07:23:43 node-1 besu[624]: 2021-12-27 07:23:43.302+00:00 | EthScheduler-Services-23 (importBlock) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.
Dec 27 07:23:43 node-1 besu[624]: java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #13773000 (0x594e4880f077ff9cf01500976d8c0b47cc8d3c77995860353e222a334b8060ad)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
Dec 27 07:23:43 node-1 besu[624]:         at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
Dec 27 07:23:43 node-1 besu[624]:         at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Dec 27 07:23:43 node-1 besu[624]:         at java.base/java.lang.Thread.run(Thread.java:829)
Dec 27 07:23:43 node-1 besu[624]: Caused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #13773000 (0x594e4880f077ff9cf01500976d8c0b47cc8d3c77995860353e222a334b8060ad)
Dec 27 07:23:43 node-1 besu[624]:         at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:55)
Dec 27 07:23:43 node-1 besu[624]:         at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)
Dec 27 07:23:43 node-1 besu[624]:         at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
Dec 27 07:23:43 node-1 besu[624]:         at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
Dec 27 07:23:43 node-1 besu[624]:         ... 5 more
Dec 27 07:23:45 node-1 besu[624]: 2021-12-27 07:23:45.809+00:00 | nioEventLoopGroup-3-1 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x74a3dfb8df04c01258... at block 13772999
Dec 27 07:24:07 node-1 besu[624]: 2021-12-27 07:24:07.305+00:00 | EthScheduler-Services-24 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13773000 (0x50b0cf3bbcdd84c5c77ca88c30fc32c28bb18f4fd6ef3a9b5db1bd2a3ce27600), - Mg/s, Peers: 25` As far as it looks it is related to Arrow Glacier Block

**Comment by matkt** [comment]
the hash of the pivot block should be in a log like that 
```
{"timestamp":"2021-12-29T09:33:57,615","level":"INFO","thread":"EthScheduler-Timer-0","class":"PivotBlockConfirmer","message":"Confirm pivot block 6106209 with at least 5 peers.","throwable":""}
{"timestamp":"2021-12-29T09:33:57,727","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"PivotBlockConfirmer","message":"Received 2 confirmation(s) for pivot block header 6106209: 0x04106a14844bcc4479dd851524facf6c19c29e19c2dd1adeeb9babf80ecf01c3","throwable":""}
{"timestamp":"2021-12-29T09:33:57,727","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"PivotBlockConfirmer","message":"Received 3 confirmation(s) for pivot block header 6106209: 0x04106a14844bcc4479dd851524facf6c19c29e19c2dd1adeeb9babf80ecf01c3","throwable":""}
{"timestamp":"2021-12-29T09:33:57,727","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"PivotBlockConfirmer","message":"Received 1 confirmation(s) for pivot block header 6106209: 0x04106a14844bcc4479dd851524facf6c19c29e19c2dd1adeeb9babf80ecf01c3","throwable":""}
{"timestamp":"2021-12-29T09:33:57,731","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"PivotBlockConfirmer","message":"Confirmed pivot block at 6106209: 0x04106a14844bcc4479dd851524facf6c19c29e19c2dd1adeeb9babf80ecf01c3","throwable":""}
{"timestamp":"2021-12-29T09:33:57,733","level":"INFO","thread":"nioEventLoopGroup-3-7","class":"PivotBlockConfirmer","message":"Received 4 confirmation(s) for pivot block header 6106209: 0x04106a14844bcc4479dd851524facf6c19c29e19c2dd1adeeb9babf80ecf01c3","
```

indeed there was a fork in December to update the difficulty bomb. So it's related to that but our Canary nodes work very well.
I would like to have the hash to be sure that you are not on a bad chain with not up to date peers
