### ISSUE TITLE
TLS client authentication fails due to `certificate unknown`

### ISSUE THREAD

**Issue by arnegebert** [hyperledger/besu#3190]
### Description
When configuring TLS Client authentication, the TLS handshake always terminates with 'certificate unknown' even if the certificate is configured in the "knownClients" file. 

### Details

I am attempting to configure TLS for the connection between my Dapp and Besu. Configuring server authentication (Besu authenticates to my Dapp) worked but I am unable to set up client authentication (my Dapp authenticates to Besu) due to the connection terminating with `unknown certificate`. 

To activate server TLS authentication, I additionally added the following CLI options to my `besu` invocation: 
```
  --rpc-http-tls-enabled \
  --rpc-http-tls-keystore-file=tls/besu_store.p12 \
  --rpc-http-tls-keystore-password-file=tls/password.txt \
```
Which works. 

To add client TLS authentication, I furthermore added:
```
  --rpc-http-tls-client-auth-enabled \
  --rpc-http-tls-known-clients-file=tls/knownClients.txt \
```

where `knownClients.txt` contains the following line: 
```
CantonBesuDemo 34:C7:30:1D:7C:A9:87:E7:CD:5A:88:A2:55:F0:BE:A1:9C:4A:39:2A:7C:9C:6D:1C:B3:FA:8B:BA:86:AB:54:05
```

The common name and SHA256 fingerprint were obtained through inspection via `keytool` as described [in the docs](https://besu.hyperledger.org/en/stable/HowTo/Configure/TLS/Configure-TLS/#create-the-known-clients-file). 

However, with client authentication enabled, the connection always terminates with `javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown`. I also see the following error in the Besu `TRACE` logs:  
```
 javax.net.ssl.SSLHandshakeException: Certificate for CantonBesuDemo (CN=CantonBesuDemo, O=Digital Asset, ST=Some-State, C=AU) has unknown fingerprint 34c7301d7ca987e7cd5a88a255f0bea19c4a392a7c9c6d1cb3fa8bba86ab5405                               ┤
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source
[... omitted ...]
```

Note that this is the same fingerprint I configured in `knownClients.txt`. I also attempted to connect to Besu via the `openssl s_client` just in case I had a bug in the HTTP client configuration of my Dapp. For my setup, this was the following command: 
```
openssl s_client -connect localhost:8550 -status -key canton_key.pem -cert canton_cert.pem 
```
Sadly, this leads to the same result: this succeeds with only server authentication but fails with client authentication enabled (concretely: `140676117705152:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1528:SSL alert number 46`).

I am aware that a bug in the TLS setup is unlikely but I just don't see where my setup could be misconfigured. Let me know if you need any more details. 

**Frequency:** Always

### Versions (Add all that apply)
* Besu version: 21.10.3
* Java version: openjdk 11.0.11 2021-04-20
* OS Name & Version: Ubuntu 18.04 LTS
* Kernel Version: Linux arne-Precision-5540 5.4.0-90-generic # 101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Docker Version:  20.10.11

### Additional Information
I am running Besu locally using the latest Docker containers. 

Changing `knownClients.txt` to 
```
BesuCantonDemo 34c7301d7ca987e7cd5a88a255f0bea19c4a392a7c9c6d1cb3fa8bba86ab5405
```
did not fix the issue.

**Comment by usmansaleem** [comment]
@arnegebert I am unable to reproduce the issue in my local testing. https://github.com/usmansaleem/besu_tls_setup . The only thing I notice is CN is in mixed case, try using all lower case for CN and see if it works i.e. `CantonBesuDemo` should be `cantonbesudemo`.

**Comment by arnegebert** [comment]
Argh.... that seems to be it! Thank you very much @usmansaleem, this fixes my issue!

**Comment by usmansaleem** [comment]
Glad it sorted out. Apologies for delayed response due to end of year holidays.

**Comment by arnegebert** [comment]
> Glad it sorted out. Apologies for delayed response due to end of year holidays.

No worries and thanks again. But I would suggest adding this to the documentation as (IMHO) it's counterintuitive and the error message is somewhat misleading too.

**Comment by usmansaleem** [comment]
> No worries and thanks again. But I would suggest adding this to the documentation as (IMHO) it's counterintuitive and the error message is somewhat misleading too.
Yes, will add a doco warning about it. Have already submitted a patch to the upstream library where this bug originated from. https://github.com/apache/incubator-tuweni/pull/353

**Comment by arnegebert** [comment]
> > No worries and thanks again. But I would suggest adding this to the documentation as (IMHO) it's counterintuitive and the error message is somewhat misleading too.
> 
> Yes, will add a doco warning about it. Have already submitted a patch to the upstream library where this bug originated from. [apache/incubator-tuweni#353](https://github.com/apache/incubator-tuweni/pull/353)

You are a GOAT!

**Comment by cryptohazard** [comment]
I ran into that propblem for a week and couldn't understand why.
I just found this issue and realize I didn't really notice the `common name` in the doc 😅.
