### ISSUE TITLE
eth_feeHistory does not return transaction effective priority fee per gas history

### ISSUE THREAD

**Issue by JustNotHelpful** [hyperledger/besu#3201]
### Description
As an user, I want to be able to see the priority fee history on Mainnnet to estimate current gas prices and track trends over time. The current implementation only provides the basefee history.

### Acceptance Criteria
* A call to eth_feeHistory should return the basefee history and the priority / reward fee history

### Steps to Reproduce (Bug)
1. Execute the below command whilst connected to the node via SSH (can also be ran remotely):
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_feeHistory","params":[2,"latest"],"id":1}' http://127.0.0.1:8545

**Expected behavior:**

I would expect a mainnet node to return results as per https://github.com/ethereum/execution-specs/pull/212/commits/45d49bf403e0a5ec356e4940cf15800d0a59a661

{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : {
    "oldestBlock" : "0xd316fb",
    "baseFeePerGas" : [ "0x896dc065a", "0x9a975fe20", "0xa28748cc8" ],
    "gasUsedRatio" : [ 0.9995342762406927, 0.705371128050491 ],
    "reward" : (as per spec)
  }

**Actual behavior:** [What actually happens]
Sample from querying my mainnet node earlier today. There is no priority fee history, which is not credible for mainnet.

{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : {
    "oldestBlock" : "0xd316fb",
    "baseFeePerGas" : [ "0x896dc065a", "0x9a975fe20", "0xa28748cc8" ],
    "gasUsedRatio" : [ 0.9995342762406927, 0.705371128050491 ]
  }

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: 21.10.4
* Java version: Not sure (using docker).
* OS Name & Version: Ubuntu 20.04.3 LTS
* Kernel Version: Linux ****** 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Docker Version: 20.10.7

**Comment by fab-10** [comment]
Hi @JustNotHelpful, I have checked this, and Besu actually calculates and returns the reward field, but only if in the request you specify the `rewardPercentiles` parameter like that:

```
curl -X POST -H'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_feeHistory","params":[2,"latest",[50,100]],"id":1}' http://127.0.0.1:8545
```

and the response is:

```
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : {
    "oldestBlock" : "0x5c7db8",
    "baseFeePerGas" : [ "0x7", "0x7", "0x7" ],
    "gasUsedRatio" : [ 0.06381766666666666, 0.041748801037546496 ],
    "reward" : [ [ "0x4d7c6d02", "0x4d7c6d02" ], [ "0x4d7c6d02", "0x59682f00" ] ]
  }
}
```

Does this solve your issue?

**Comment by JustNotHelpful** [comment]
Yes it does - thank you for your assistance.
