### ISSUE TITLE
On an IBFT2 network with an R1 or K1 curve and TLS, restarting a node causes it not to join the sync process again & has issues with peering

### ISSUE THREAD

**Issue by joshuafernandes** [hyperledger/besu#3207]
### Description
As a node operator I'd like to perform maintenance/updates on existing nodes which would restart the node and triggers this behaviour

### Acceptance Criteria
Restarting a node doesn't cause it to be non functional anymore ie it will resume peering and continue to import blocks

### Steps to Reproduce (Bug)
See attached zip files
1. Extract zip file
2. Start the network up as normal with ./run.sh
3. Give it a few mins for blocks to be created.
3. Run `docker stop quorum-test-network-member1_1`. Run a `docker ps` to find the name of the container 
4. Wait about a minute for it to stop
5. Run  `docker start quorum-test-network-member1_1` and follow the logs and metrics

Logs show  saving blocks and peer counts of 0, instead of importing blocks and peer count of 7 or so
```{"timestamp":"2021-12-20T03:51:04,905","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:06,042","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"BlockPropagationManager","message":"Saving announced block 39 (0x172f1574ce35ded0212bdc30a7541c909c59100738ef5efa0777bdcbde818671) for future import","throwable":""}
{"timestamp":"2021-12-20T03:51:13,201","container":"e4bc41321089","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
{"timestamp":"2021-12-20T03:51:13,778","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:15,877","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:16,319","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-7","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:16,419","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:17,060","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-9","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:18,203","container":"e4bc41321089","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
{"timestamp":"2021-12-20T03:51:23,204","container":"e4bc41321089","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
{"timestamp":"2021-12-20T03:51:28,204","container":"e4bc41321089","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
{"timestamp":"2021-12-20T03:51:33,205","container":"e4bc41321089","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
{"timestamp":"2021-12-20T03:51:34,908","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:37,111","container":"e4bc41321089","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:51:38,206","container":"e4bc41321089","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}

```

**Expected behavior:** [What you expect to happen]
I expect that the peer count goes back to normal and blocks are imported as normal

**Actual behavior:** [What actually happens]
Peer count =0 and blocks aren't imported, but says `saving accounced block ...`

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: [`besu --version`] 21.10.2
* Java version: [`java -version`] jdk11
* OS Name & Version: [`cat /etc/*release`] ubuntu 20.04 lts
* Kernel Version: [`uname -a`] 5.11
* Virtual Machine software & version: [`vmware -v`] n/a
* Docker Version: [`docker version`] 20.10.11
* Cloud VM, type, size: [Amazon Web Services I3-large] n/a

### Additional Information
Same behaviour for R1 and K1 curves with TLS

Behaviour also noted on K8S

[quorum-test-network-k1.tar.gz](https://github.com/hyperledger/besu/files/7742486/quorum-test-network-k1.tar.gz)
[quorum-test-network-R1.tar.gz](https://github.com/hyperledger/besu/files/7742487/quorum-test-network-R1.tar.gz)

**Comment by lucassaldanha** [comment]
We have confirmed that this is related to https://github.com/hyperledger/besu/issues/3254. Please follow #3254 for tracking this bug.
