### ISSUE TITLE
Not supported rocksDBException on AWS

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#3220]
### Description

{"timestamp":"2021-12-31T10:44:39,631","level":"INFO","thread":"main","class":"ProtocolScheduleBuilder","message":"Protocol schedule created with milestones: [Petersburg: 0, Istanbul: 1561651, Berlin: 4460644, London: 5062605]","throwable":""}
org.rocksdb.RocksDBException: NotSupported

To display full help:
besu [COMMAND] --help
2021-12-31 10:44:51,219 main INFO Registered Log4j as the java.util.logging.LogManager.
ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.9.2

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: ed9d64d9cb8d1b4a82d5379ef513adaafae91806
* Java version: [`java -version`]
* OS Name & Version: 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)

* Kernel Version: [`uname -a`]
Linux ip-10-0-1-196.us-east-2.compute.internal 4.14.232-177.418.amzn2.x86_64 # 1 SMP Tue Jun 15 20:57:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by garyschulte** [comment]
@matkt is there any more detail on this to help reproduce it?  I bumped rocksdbjni back to 6.27.3 again and haven't been able to reproduce it on an ec2 instance.  What was the JVM?  was there an existing db?  using bonsai or forest?

**Comment by matkt** [comment]
> @matkt is there any more detail on this to help reproduce it? I bumped rocksdbjni back to 6.27.3 again and haven't been able to reproduce it on an ec2 instance. What was the JVM? was there an existing db? using bonsai or forest?

I think it was not an empty DB. Maybe it can help to reproduce

**Comment by garyschulte** [comment]
Was this bonsai?  I have been unable to reproduce this.  I have tried:

* starting from empty with a build using 6.27.3
* starting goerli fast-sync on 22.1.0-RC3, and restarting with a 6.27.3 build
* syncing goerli completely with 22.1.0-RC3, and then restarting with a 6.27.3 build

all those were forest mode though.

**Comment by matkt** [comment]
Yes it was bonsai but not sure there is a difference. If you cannot reproduce I'm fine to repush this version

**Comment by garyschulte** [comment]
We might as well wait until the M1-friendly version of rocksdbjni is published.  I was just circling back to this issue to try to resolve what ever might block getting onto the latest release
🍻
