### ISSUE TITLE
Optional empty not handled: fastSyncState.getPivotBlockHeader().get();

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3227]
Sonar is reporting a possible bug that looks worth fixing https://sonarcloud.io/project/issues?id=hyperledger_besu&open=AX3clLLkTSMTbb40goXd&resolved=false&sinceLeakPeriod=true&types=BUG

fastSyncState.getPivotBlockHeader().get();

We probably just want to log a message and exit if pivot block not present

**Comment by TheSwarnim** [comment]
@macfarla, I'm new here and want to work on this issue, please assign it to me.

**Comment by macfarla** [comment]
Assigned to you @TheSwarnim!
