### ISSUE TITLE
security vulnerabilities identified in Nexus IQ

### ISSUE THREAD

**Issue by mgriffin75** [hyperledger/besu#3229]
My Enterprise is at a heightened security awareness with the log4j vulnerabilities as are most. We scanned 21.10.5 in Nexus IQ, the scan results are below. We cannot proceed with security vulnerabilities seven or higher. When can these be remediated? When do you plan to update log4j to 2.17.1? Threat of 10
com.fasterxml.jackson.core : jackson-databind : 2.12.4
com.google.code.gson : gson : 2.8.6
com.squareup.okhttp: okhttp: 2.7.5
com.squareup.okhttp3 : okhttp:4.9.1
io.kubernetes : client-java : 5.0.0
io.netty: netty-all : 4.1.66. Final
io.netty: netty-all: 4.1.66. Final
io.netty: netty-codec : 4.1.65.Final
io.netty: netty-codec : 4.1.65.Final
io.netty: netty-codec : 4.1.65. Final

Threat of 7
com.squareup.okhttp: okhttp: 2.7.5
commons-codec : commons-codec : 1.13
io.grpc: grpc-core: 1.39.0
io.kubernetes: client-java : 5.0.0
io.netty: netty-all : 4.1.66.Final
io.netty: netty-codec-http: 4.1.65.Final
io.netty: netty-handler : 4.1.65.Final
commons-codec: commons-codec: 1.13
io.grpc: grpc-core : 1.39.0
io.kubernetes : client-java:5.0.0
io.netty: netty-all : 4.1.66.Final
io.netty: netty-codec-http : 4.1.65.Final
io.netty: netty-handler: 4.1.65.Final
io.vertx: vertx-web : 3.9.8
org.apache.logging.log4j : log4j-core : 2.17.0
org.bouncycastle : bcprov-ext-jdk15on: 1.61
org.bouncycastle : bcprov-jdk15on: 1.69

**Comment by macfarla** [comment]
@mgriffin75 Release 21.10.6 completed just now: this updates log4j to 2.17.1 https://github.com/hyperledger/besu/releases/tag/21.10.6

**Comment by mgriffin75** [comment]
@macfarla thank you for the update, new release resolves the log4j vulnerability.  However we are unable to move forward in our Enterprise due to the security vulnerabilities (above that are 7 and higher) identified in Nexus IQ.  Any ideas on when these will be addressed?  Thanks for your help

**Comment by macfarla** [comment]
I'm taking a look at this list @mgriffin75 - but I have some questions - are you sure these vulnerabilities are all from scanning besu 21.10.5? Are they transitive dependencies? Are you able to provide any more context from the report you are looking at?
for example our netty dependency is already at 4.1.72.Final https://github.com/hyperledger/besu/blob/c25483c29f04bbc49149617acf3c6021369962fa/gradle/versions.gradle#L70
we recently upgraded vertx so it's at 4.2.1
https://github.com/hyperledger/besu/blob/c25483c29f04bbc49149617acf3c6021369962fa/gradle/versions.gradle#L96

**Comment by macfarla** [comment]
Actually that is on main branch. 21.10.5 (and 21.10.6) do have some slightly older versions of netty and vertx... Also I see kubernetes 5.0.0 can be updated. I will keep looking through the list.

**Comment by mgriffin75** [comment]
We ran the scan on Monday on 21.10.5.  We also compared it to 21.10.3 it was the same.  I've noted transitive and direct dependencies what I could, I don't have direct access to the report but I can get if you need more info let me know, thanks

Threat of 10
T com.fasterxml.jackson.core : jackson-databind : 2.12.4
T com.google.code.gson : gson : 2.8.6
T com.squareup.okhttp: okhttp: 2.7.5
T com.squareup.okhttp3 : okhttp:4.9.1
D io.kubernetes : client-java : 5.0.0
D io.netty: netty-all : 4.1.66. Final
T io.netty: netty-codec : 4.1.65.Final

Threat of 7
T commons-codec : commons-codec : 1.13
T io.grpc: grpc-core: 1.39.0
io.kubernetes: client-java : 5.0.0
io.netty: netty-all : 4.1.66.Final
io.netty: netty-codec-http: 4.1.65.Final
io.netty: netty-handler : 4.1.65.Final
T commons-codec: commons-codec: 1.13
io.grpc: grpc-core : 1.39.0
io.kubernetes : client-java:5.0.0
io.netty: netty-all : 4.1.66.Final
T io.netty: netty-codec-http : 4.1.65.Final
Tio.netty: netty-handler: 4.1.65.Final
D io.vertx: vertx-web : 3.9.8
T org.apache.logging.log4j : log4j-core : 2.17.0
org.bouncycastle : bcprov-ext-jdk15on: 1.61
org.bouncycastle : bcprov-ext-jdk15on: 1.61
org.bouncycastle : bcprov-ext-jdk15on: 1.61
org.bouncycastle : bcprov-ext-jdk15on: 1.61
org.bouncycastle : bcprov-jdk15on: 1.69

**Comment by macfarla** [comment]
This one - looks like we might have a transitive dependency on a different version of okhttp - because I can only find okhttp3 in besu
```
T com.squareup.okhttp: okhttp: 2.7.5
T com.squareup.okhttp3 : okhttp:4.9.1
```

**Comment by mgriffin75** [comment]
moving forward will you implement  Nexus IQ or something similar to identify any security violations?

**Comment by macfarla** [comment]
kubernetes dependency is now at 6.0.1 but does not totally solve the vulnerability. https://mvnrepository.com/artifact/io.kubernetes/client-java
other dependencies have been updated however the kubernetes dependency upgrade is going to be a bit more involved because there are (more) breaking changes. going from 6.0.1 to 7.0.0 there are package renames and more.

**Comment by macfarla** [comment]
> moving forward will you implement Nexus IQ or something similar to identify any security violations?

We are investigating options for this.

**Comment by macfarla** [comment]
And okhttp 2.7.5 is via kubernetes:client-java

Output of ./gradlew -q dependencies ::

|    |    |    |    |    |    |    |    |    +--- io.kubernetes:client-java -> 6.0.1
|    |    |    |    |    |    |    |    |    |    +--- io.kubernetes:client-java-api:6.0.1
|    |    |    |    |    |    |    |    |    |    |    +--- io.sundr:builder-annotations:0.18.0
|    |    |    |    |    |    |    |    |    |    |    |    +--- io.sundr:sundr-core:0.18.0
|    |    |    |    |    |    |    |    |    |    |    |    +--- io.sundr:sundr-codegen:0.18.0
|    |    |    |    |    |    |    |    |    |    |    |    \--- io.sundr:resourcecify-annotations:0.18.0
|    |    |    |    |    |    |    |    |    |    |    +--- io.swagger:swagger-annotations:1.5.22
|    |    |    |    |    |    |    |    |    |    |    +--- com.squareup.okhttp:okhttp:2.7.5
|    |    |    |    |    |    |    |    |    |    |    |    \--- com.squareup.okio:okio:1.6.0 -> 2.8.0 (*)
|    |    |    |    |    |    |    |    |    |    |    +--- com.squareup.okhttp:logging-interceptor:2.7.5
|    |    |    |    |    |    |    |    |    |    |    |    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    |    |    |    |    |    |    |    |    |    |    +--- com.google.code.gson:gson:2.8.0 -> 2.8.9
|    |    |    |    |    |    |    |    |    |    |    +--- joda-time:joda-time:2.9.3
|    |    |    |    |    |    |    |    |    |    |    +--- org.joda:joda-convert:1.2
|    |    |    |    |    |    |    |    |    |    |    \--- org.apache.commons:commons-lang3:3.7
|    |    |    |    |    |    |    |    |    |    +--- io.kubernetes:client-java-proto:6.0.1
|    |    |    |    |    |    |    |    |    |    |    \--- com.google.protobuf:protobuf-java:3.4.0 -> 3.17.2
|    |    |    |    |    |    |    |    |    |    +--- org.yaml:snakeyaml:1.19 -> 1.26
|    |    |    |    |    |    |    |    |    |    +--- commons-codec:commons-codec:1.11 -> 1.15
|    |    |    |    |    |    |    |    |    |    +--- org.apache.commons:commons-compress:1.18 -> 1.21
|    |    |    |    |    |    |    |    |    |    +--- org.apache.commons:commons-lang3:3.7
|    |    |    |    |    |    |    |    |    |    +--- com.squareup.okhttp:okhttp-ws:2.7.5
|    |    |    |    |    |    |    |    |    |    |    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    |    |    |    |    |    |    |    |    |    +--- com.google.guava:guava:25.1-jre -> 31.0.1-jre (*)
|    |    |    |    |    |    |    |    |    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.32
|    |    |    |    |    |    |    |    |    |    +--- org.bouncycastle:bcprov-ext-jdk15on:1.61
|    |    |    |    |    |    |    |    |    |    +--- org.bouncycastle:bcpkix-jdk15on:1.61 -> 1.70 (*)
|    |    |    |    |    |    |    |    |    |    \--- com.google.protobuf:protobuf-java:3.4.0 -> 3.17.2

**Comment by mgriffin75** [comment]
will these changes be in the next release?  If so what is the target date?

**Comment by mgriffin75** [comment]
can you let us know when you're ready and we can perform another scan on the branch that contains these changes, thanks!

**Comment by mgriffin75** [comment]
for okhttp 2.7.5 is not sufficient seems okhttp is replaced by okhttp3 and a secure version is 4.9.3.  I'll work on providing a list of versions that are secure. for io.kubernetes:client-java  it would be 14.0.0

**Comment by macfarla** [comment]
We are working on updating and resolving the individual dependencies. 

As far as the next release, what is your preference: RC (release candidate) or do you need a stable release?
Next RC would be 22.1.0-RC3 (this could be completed this week)
If a stable release is required - we can do release 21.10.7 which would just have the dependency updates (no new features). (this could be completed this week)

The stable release for 22.1.0 won’t be finalised for at least another week or two, since it includes in-progress feature work which still needs to be completed, tested and verified on our canary nodes.

**Comment by mgriffin75** [comment]
Thank you for the update.  Would prefer to go with a stable release (21.10.7) as the dependencies are preventing us from going to QA and above this would allowing testing beforehand.  When your team is close would you like us to scan the release?   I now have the ability to look at the dependencies versions that are security complaint and provide a list.  Let me know if there is anything we can do to help.

**Comment by macfarla** [comment]
Thanks @mgriffin75 that would be helpful - I'll get back to you!

**Comment by mgriffin75** [comment]
can you let me the release candidate you're working from. This way I can get a scan and let you know the progress.

**Comment by mgriffin75** [comment]
com.fasterxml.jackson.core : jackson-databind 2.13.1 
com.google.code.gson : gson 2.8.9 
io.netty : netty-all : 4.1.72
Final io.netty:netty-codec:4.1.72
Final commons-codec: commons-codec:20041127.091804 
io.grpc:grpc-core:1.37.1 (all higher versions have vulnerabilities) 
io.vertx:vertx-web:4.1.8 
org.bouncycastle:bcprov-ext-jdk15on:1.70 
org.bouncycastle:bcprov-jdk15on:1.70 
com.squareup.okhttp: okhttp : 2.7.5 (replaced by okhttp3)
com.squareup.okhttp3:okhttp:4.9.3 
io.kubernetes:client-java:14.0.0 (most likely resolve okhttp as it's transitive)

**Comment by macfarla** [comment]
I'm working on this PR branch https://github.com/hyperledger/besu/pull/3265

**Comment by macfarla** [comment]
kubernetes:client-java:14 should also resolve bouncycastle

**Comment by macfarla** [comment]
Updated snapshot https://hyperledger.jfrog.io/ui/native/besu-binaries/besu/21.10.7-SNAPSHOT/

**Comment by macfarla** [comment]
Release complete https://hyperledger.jfrog.io/ui/native/besu-binaries/besu/21.10.7/ @mgriffin75 let us know if there are further issues!

**Comment by lucassaldanha** [comment]
@mgriffin75 Ethsigner 21.10.9 has been released and it contains all fixes for libraries similar to Besu.
