### ISSUE TITLE
update existing miningbeneficiary wallet address to smart contract address on IBFT2

### ISSUE THREAD

**Issue by eu09** [hyperledger/besu#3237]
Is possible update the miningbeneficiary address to smart contract by using transitions on genesis block  json ? 

 "transitions": {
       "ibft2": [
       {
         "block": FutureBlockNumber,
         "miningbeneficiary":  Newsmartcontract address
       }
       ]
     }
  },

**Comment by jframe** [comment]
This isn't possible at the moment. But we do have a ticket to add this functionality for IBFT2 and QBFT https://github.com/hyperledger/besu/issues/3115
