### ISSUE TITLE
Implement post-TTD full sync strategy

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#3268]
### Description
Currently besu leverages the typical basic forward sync strategies for the merge.  Meaning we use full-sync, fast-sync and snap-sync and will sync up to the latest head block from our peers.  However post-merge, when besu syncs a new instance it should stop at the terminal-total-difficulty block and await direction from a consensus client regarding what target to forward-sync to.

Handing the concurrent sync of execution and consensus clients is still an evolving topic, but to mitigate attacks and zombie mining that might happen post-merge, we can and should implement a different post-TTD sync strategy.  

Implementing this strategy has an added benefit of making bonsai tries more viable for the merge, as we will not have to do an expensive rewind operation to get back to TTD once we start processing forkchoiceUpdated calls from the consensus client.  

### Acceptance Criteria

* incorporatea configured terminal block number and block hash as an initial sync target,
** in the absence of TTD block number/hash, continue to use heaviest chain criteria for which chain to sync
* stop initial sync at terminal difficulty, and mark the chain as sync'd until otherwise directed by consensus client
* taking direction from consensus engine via forkchoiceUpdated for the chain and head to forward sync up to

**Comment by ajsutton** [comment]
Given the way fast and snap sync work, it may make sense to not start sync at all if peers are advertising a total difficulty in excess of TTD until the CL client sends the first `forkChoiceUpdated` notification which would identify the chain to sync.  If you sync'd the TTD block you'd likely download a very old world state and then either have to full sync from there or discard it and start a new fast/snap sync from where the CL starts from.

If the CL is doing a full sync of the beacon chain, that first notice will be for the TTD block  and the CL would then execute each block past that, but when the CL is using checkpoint sync it's starting sync will be close to the chain head which may be very significantly past the TTD block and the CL will not execute any blocks prior to the checkpoint state it starts with.

**Comment by garyschulte** [comment]
marking this issue as complete after changing the acceptance criteria and breaking it down into #3506, #3507, #3512, #3513
