### ISSUE TITLE
Besu on Goerli struggles to find peers

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#3290]
### Description

Besu `/v21.10.8/linux-x86_64/openjdk-java-11` in Docker, with default `--nat-method` and with `--nat-method=DOCKER`, struggles to find peers. 30303 tcp/udp is open, tested with yougetsignal.

```
execution_1           | 2022-01-17 16:41:59.195+01:00 | EthScheduler-Services-10 (importBlock) | INFO  | FastImportBlocksStep | Completed importing chain segment 4383001 to 4383200, Peers: 1
execution_1           | 2022-01-17 16:41:59.290+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.291+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.292+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.292+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.293+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.293+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.293+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.294+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.296+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.296+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.297+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:41:59.297+01:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 1
execution_1           | 2022-01-17 16:42:01.710+01:00 | nioEventLoopGroup-3-3 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xa03f4447809bb24a62... at block 4383200
execution_1           | 2022-01-17 16:42:10.080+01:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
execution_1           | 2022-01-17 16:42:10.083+01:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
```

It does not recover from this, at least not during the time I observed it, maybe half an hour.

**Frequency:** Consistently this morning, though Besu had peers the previous day when it was first started.

**Comment by yorickdowne** [comment]
This resolved by clearing the DB and starting over. Curious. Will monitor this new sync attempt.

**Comment by yorickdowne** [comment]
Debug gives me a clue.

Peering with Geth fails.

```
execution_1  | 2022-01-17 17:46:12.416+01:00 | nioEventLoopGroup-3-4 | DEBUG | EthProtocolManager | Disconnect - Outbound - 0x10 SUBPROTOCOL_TRIGGERED - PeerInfo{version=5, clientId='Geth/v1.10.14-stable-11a3a350/linux-amd64/go1.17.5', capabilities=[eth/66, snap/1], port=0, nodeId=0x3057ff59534df145961b0261d84e9f9c6e3268b77f73f464ed5b3ff95ab331668e7533e28e118504f95b77356bc08eb9e8dd42b48bb94b5a80c51d44a676acbb} - 13 peers left
```

Inbound peering works generally: `Inbound connection established`

Inbound "too many peers" - is that by Besu?

```
Disconnect - Inbound - 0x04 TOO_MANY_PEERS - PeerInfo{version=5, clientId='besu/PegaSys/v21.10.2/linux-x86_64/corretto-java-11', capabilities=[eth/63, eth/64, eth/65, eth/66], port=30303, nodeId=0xb5948a2d3e9d486c4d75bf32713221c2bd6cf86463302339299bd227dc2e276cd5a1c7ca4f43a0e9122fe9af884efed563bd2a1fd28661f3b5f5ad7bf1de5949} - 0 peers left
```

**Comment by macfarla** [comment]
Seems to be showing besu disconnecting with "too many peers" reason even when that leaves it with 0 peers
`Disconnect - Inbound - 0x04 TOO_MANY_PEERS - PeerInfo{version=5, clientId='besu/PegaSys/v21.10.2/linux-x86_64/corretto-java-11', capabilities=[eth/63, eth/64, eth/65, eth/66], port=30303, nodeId=0xb5948a2d3e9d486c4d75bf32713221c2bd6cf86463302339299bd227dc2e276cd5a1c7ca4f43a0e9122fe9af884efed563bd2a1fd28661f3b5f5ad7bf1de5949} - 0 peers left`

**Comment by frankisawesome** [comment]
What's the best approach to replicate this @yorickdowne ? I'm thinking if you can isolate some of the peers that you think should be connecting but are throwing errors, we can use the node addresses as static nodes and see if we can replicate the errors that way?

**Comment by yorickdowne** [comment]
> What's the best approach to replicate this @yorickdowne ? I'm thinking if you can isolate some of the peers that you think should be connecting but are throwing errors, we can use the node addresses as static nodes and see if we can replicate the errors that way?

That's an interesting idea. I'd need some help from you guys to understand which of these disconnects are spurious. Is "too many peers" on the Besu side or remote side? If Besu, then that's something to look at.

How about subprotocol triggered? What is that, why does it connect to a peer then disconnect? Geth 1.10.14 seems a perfectly suitable peer to me - if you say to me that one should work, I can grep for it and we can make a short-list of a few of those.

**Comment by yorickdowne** [comment]
After trying a fresh sync, back to the same spot: `execution_1  | 2022-01-18 16:55:29.105+01:00 | nioEventLoopGroup-3-9 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 4`

Here's two peers with that too many peers message
```
execution_1  | 2022-01-18 16:57:02.217+01:00 | nioEventLoopGroup-3-7 | DEBUG | DeFramer | Peer enode://6b83a6d38da08610afaa55f04d51cf6cf6aed58b07cb69c4fd0f0ef05deab2ae7ff9fce64af6d61d1b78b0f9f0bee192c0f24e15f084e92f3386fb61bf226a44@13.212.206.198:30303 disconnected before sending HELLO.  Reason: 0x04 TOO_MANY_PEERS
execution_1  | 2022-01-18 16:57:02.217+01:00 | nioEventLoopGroup-3-7 | DEBUG | RlpxAgent | Failed to connect to peer 0x6b83a6d38da08610afaa55f04d51cf6cf6aed58b07cb69c4fd0f0ef05deab2ae7ff9fce64af6d61d1b78b0f9f0bee192c0f24e15f084e92f3386fb61bf226a44: org.hyperledger.besu.ethereum.p2p.network.exceptions.PeerDisconnectedException: Peer disconnected for reason: 0x04 TOO_MANY_PEERS
execution_1  | 2022-01-18 16:57:02.652+01:00 | nioEventLoopGroup-3-2 | DEBUG | HandshakeHandlerOutbound | Wrote initial crypto handshake message to /159.138.233.243:30303.
execution_1  | 2022-01-18 16:57:02.880+01:00 | nioEventLoopGroup-3-2 | DEBUG | DeFramer | Peer enode://9cb643adadd5b46efce8562224515bee14c79b481f1df74412f7259c94e159671c645a4535601ad10f8d664de750da07e7e2c9cb2421e434d03a33cf2693b757@159.138.233.243:30303 disconnected before sending HELLO.  Reason: 0x04 TOO_MANY_PEERS
execution_1  | 2022-01-18 16:57:02.880+01:00 | nioEventLoopGroup-3-2 | DEBUG | RlpxAgent | Failed to connect to peer 0x9cb643adadd5b46efce8562224515bee14c79b481f1df74412f7259c94e159671c645a4535601ad10f8d664de750da07e7e2c9cb2421e434d03a33cf2693b757: org.hyperledger.besu.ethereum.p2p.network.exceptions.PeerDisconnectedException: Peer disconnected for reason: 0x04 TOO_MANY_PEERS
```

Reproduction could be as simple as cloning an eth-docker with `COMPOSE_FILE=besu.yml:ec-shared.yml` in `.env`, then `./ethd up` and let it sync Goerli and observe. Log level can be set in `.env` as well.

**Comment by yorickdowne** [comment]
So thinking about that subprotocol thing. `Protocol schedule created with milestones: [Petersburg: 0, Istanbul: 1561651, Berlin: 4460644, London: 5062605]` ... Arrow Glacier somewhat obviously doesn't exist in Goerli, and, would it maybe be advertised anyway by Geth? With a block of 0? And could that cause issues?

**Comment by yorickdowne** [comment]
Peering seems somewhat independent of maxpeers. Tried it with default 25 and then with a bumped 100. Even with maxpeers 100 I see 1-7 peers while catching up with chain, and a steady flow of 0x04 TOO_MANY_PEERS.

**Comment by ajsutton** [comment]
`0x04 TOO_MANY_PEERS` is being sent to Besu by the remote node.  Basically all the other nodes on Görli are already at their max peers and have formed a pretty stable network so it's hard for new clients to actually find peers.  Ensuring ports are open may help but my experience is that Görli can be quite difficult to find peers in general.

I'm not sure what's causing the `SUBPROTOCOL_TRIGGERED` messages though.

**Comment by yorickdowne** [comment]
Thanks for chiming in. So 0x04 is expected, but that Besu can't keep peers at all after initial sync, that's not expected.

**Comment by ajsutton** [comment]
Yeah, I would expect that once you can connect to a useful peer you should be able to hold onto them. You may find some peers connect and fairly quickly disconnect - that tends to happen if they're actually on a different chain or for some other reason are found to not be useful.

**Comment by macfarla** [comment]
Re the `SUBPROCOL_TRIGGERED` disconnect - looking at the code there's a few different reasons. If you enable DEBUG logging you should see the actual reason in the logs. eg `matching network id ({}), but non-matching genesis hash`

https://github.com/hyperledger/besu/blob/97bad4a7b76e1728ad6b392763ebc419d953d2f8/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java#L350

**Comment by yorickdowne** [comment]
Right, I see a bunch of "mismatched network ID", which is legitimate. Stepping back, the issue is that Besu has 0 peers on Goerli after sync, and this is, as far as I can tell, not just a "well it's Goerli" problem: Geth on the same machine has peers.

Going through all 0x10 manually is extremely tedious. Let me see whether I can whip up something that counts disconnect reasons.

**Comment by yorickdowne** [comment]
Okay, I can go through the logs and get all peers where I see a 0x10 disconnect, but no `has mismatched` or `has matching` line, so ones where there's not much information as to why 0x10. Which might mean in that case, the reason code was received from the other end?

Not sure where to go from here.

This issue of not having Goerli peers after initial sync completes is quite reproduceable here. Have you been able to reproduce it?

**Comment by matkt** [comment]
just to find out. Do you have logs on startup (dns error) that are displayed in the console ?

**Comment by yorickdowne** [comment]
This is an example of a peer with 0x10 triggered but no indication as to why, which suggests it may have come from the remote end. Any way to dig further?

```
execution_1  | 2022-01-20 17:39:12.093+01:00 | nioEventLoopGroup-3-10 | DEBUG | RlpxAgent | Outbound connection established to peer: 0x6aea9a11e3da24058605f4edeb581dab349f553d651854faecd20d1d9e41b5660737c9bd9c19b421c7ada9db34565ee7f48c3f7fcdb30be16ba41c40bec3b4d3
execution_1  | 2022-01-20 17:39:12.094+01:00 | nioEventLoopGroup-3-10 | DEBUG | EthProtocolManager | Sending status message to Peer 0x6aea9a11e3da240586....
execution_1  | 2022-01-20 17:39:12.515+01:00 | nioEventLoopGroup-3-10 | DEBUG | EthProtocolManager | Disconnect - Inbound - 0x10 SUBPROTOCOL_TRIGGERED - PeerInfo{version=5, clientId='Geth/v1.6.0-EthoProtocol--NewHorizon-2728a9b7-20211212/linux-amd64/go1.16.11', capabilities=[eth/65, eth/66, snap/1], port=0, nodeId=0x6aea9a11e3da24058605f4edeb581dab349f553d651854faecd20d1d9e41b5660737c9bd9c19b421c7ada9db34565ee7f48c3f7fcdb30be16ba41c40bec3b4d3} - 3 peers left
```

@matkt , restarted Besu to check. I do not see a DNS error. Grepping for DNS, case-insensitive:
`execution_1  | 2022-01-20 17:55:51.384+01:00 | main | DEBUG | DefaultDnsServerAddressStreamProvider | Default DNS servers: [/127.0.0.11:53] (sun.net.dns.ResolverConfiguration)`

Will attach startup log, going as far as the first few peer negotiations
[startuplog.txt](https://github.com/hyperledger/besu/files/7907131/startuplog.txt)
.

**Comment by yorickdowne** [comment]
High-level again, the pattern is:

- Besu finds peers on startup and syncs to chainhead
- Besu cannot keep peers once at chainhead
- Besu falls behind because of this
- Rinse/Repeat on restart of Besu

**Comment by garyschulte** [comment]
To echo @matkt - are you seeing any DNS errors on startup?  

One of the avenues Besus uses to find peers is to recursively query the dns TXT record for the network you are attempting to join, e.g. for goerli enrtree://...@all.goerli.ethdisco.net.  For details see: 
https://eips.ethereum.org/EIPS/eip-1459
https://github.com/ethereum/discv4-dns-lists

Without this, besu has to rely on discv4 discovery to sift through every p2p node in the DHT, and connect to each to find goerli nodes amongst them.  That can be a very slow and unreliable process when you are not on mainnet (most nodes are ethereum mainnet).

The first place I would look when diagnosing peering issues would be with DNS.  Figure out what your upstream dns server is and make sure it support TCP based dns lookups, and is not rate-limiting your lookups.

**Comment by yorickdowne** [comment]
Interesting, thank you.

**Comment by yorickdowne** [comment]
Closing this issue. I tried it on a host with the exact same DNS but more CPU, and it could get and hold peers just fine. I'll chalk this up to "Besu needs more compute than Geth, and if you starve it, nothing good happens".

Thank you for working through it with me. If nothing else, this boosted my confidence in Besu. Now to track down the sync snafu on main ...
