### ISSUE TITLE
Crash on "merge" branch 

### ISSUE THREAD

**Issue by luisnaranjo733** [hyperledger/besu#3310]
### Description
As an Ethereum user, I want to run Besu on Kintsugi to help so that I can help test the merge.
Specifically, I'm drafting a write-up to help people run Besu-Teku at home against Kintsugi. My goal is to promote the Besu-Teku combo, because I think it's underrated and its success can help improve Ethereum client diversity.

Besu immediately crashes on launch.
Details here
https://gist.github.com/luisnaranjo733/81f4d5396d3f93352f93f0c3e16b9f49

### Acceptance Criteria
Besu should run normally against the merge testnets

### Steps to Reproduce (Bug)
1. Clone and build Besu on the "merge" branch
2. Run it with the flags listed [here](https://gist.github.com/luisnaranjo733/81f4d5396d3f93352f93f0c3e16b9f49) (copied from the [official merge testnet documentation](https://hackmd.io/dFzKxB3ISWO8juUqPpJFfw))

**Expected behavior:** Besu should run

**Actual behavior:** Besu crashes - something about a missing coinbase transaction and mining (which I'm not trying to do)

**Frequency:** 100%

### Versions (Add all that apply)
All of these details are in this [Github gist](https://gist.github.com/luisnaranjo733/81f4d5396d3f93352f93f0c3e16b9f49)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by SeaMonkey82** [comment]
User was including `MINER` in the `--rpc-http-api` flags, so besu wanted `--miner-coinbase` and `--miner-enabled` as well and was crashing without them.

**Comment by SeaMonkey82** [comment]
Update:  I just tried a fresh instance of besu and it refused to launch without `--miner-coinbase`, but if I include it while omitting `--miner-enabled` it just generates a warning and proceeds.

`WARN  | Besu | --miner-coinbase has been ignored because --miner-enabled was not defined on the command line.`

**Comment by luisnaranjo733** [comment]
Can confirm that adding this flag showed the same warning, and then besu just started chugging along

```--miner-coinbase=0x0000000000000000000000000000000000000000```

Thanks @SeaMonkey82!

**Comment by macfarla** [comment]
Great that you found the solution!
