### ISSUE TITLE
Besu Ignores `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED` Being Set to `false`

### ISSUE THREAD

**Issue by ItayPodhajcer** [hyperledger/besu#3332]
### Description
As we were deploying a private permissioned blockchain network, at some point we noticed that nodes were failing to start the sync process due to not finding any peers to connect to.
Turns out they were getting the `TOO_MANY_PEERS` response from the bootnodes, who already had the max connected peers reached (the default 25 peers).

We decided to try and turn off that limit using the `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED` environment variable set to `false`, only to discover that it was being ignored having the max limit still enforced by the nodes.

As a workaround, we increased the max allowed peers which seems to have solved the inability of nodes to connect, but it means we'll need to keep adjusting that value as more nodes are added to the network, which is not ideal, as it requires a restart of the node.

### Acceptance Criteria
Besu should respect `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED` when it is set to `false`.

### Steps to Reproduce (Bug)
1. Deploy private permissioned network with a total of 25 (default max) nodes (with `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED` set to `false`)
2. Deploy an additional node to the network
3. Node should fail to connect to other peers

**Expected behavior:** Besu should respect `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED` when it is set to `false`.

**Actual behavior:** Besu ignores the value of `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED`.

**Frequency:** Always

### Versions (Add all that apply)
* Software version: `21.10.6`

**Comment by macfarla** [comment]
@ItayPodhajcer the `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED` is different to max_peers is to do with managing the percentage of total P2P connections that can be remotely initiated. This is useful if you're connecting to mainnet or public testnet but less useful for your private network use case. 
More info here - https://besu.hyperledger.org/en/stable/HowTo/Find-and-Connect/Managing-Peers/#limit-remote-connections

You can't totally disable the max_peers, the default value is 25. But if your nodes can only connect to each other (ie not open to public mainnet/testnets) then it should be fine to make that 50? 

Also consider - do you need all of your nodes to connect to all other nodes? Or maybe 25 peers is enough? The p2p and tx propagation protocols can handle it if not all nodes are 100% directly connected.

Another option in private networks is to disable discovery and use static nodes instead

**Comment by ItayPodhajcer** [comment]
Ah, it's a relatively new change to that page:
https://github.com/hyperledger/besu-docs/commit/6839e9df4ccfeed710911c1fc38a020499dd10f2

Before that update, it used to read:

======================================================

**Limiting remote connections**

In private and permissioned networks with a level of trust between peers, enabling the
[remote connection limits](../../Reference/CLI/CLI-Syntax.md#remote-connections-limit-enabled)
is unnecessary and might adversely affect the speed at which nodes can join the network.
Limiting remote connections may cause a clique of nodes to form when the number of nodes in the network is slightly
higher than [`--max-peers`](../../Reference/CLI/CLI-Syntax.md#max-peers).
The nodes in this clique are all connected to each other and cannot accept more connections.

In public networks, enabling the remote connections limit is necessary to prevent eclipse attacks, especially when
using [`--sync-mode`](../../Reference/CLI/CLI-Syntax.md#sync-mode) and
[`--fast-sync-min-peers`](../../Reference/CLI/CLI-Syntax.md#fast-sync-min-peers).

======================================================

That's why we thought setting `BESU_REMOTE_CONNECTIONS_LIMIT_ENABLED` will disable that the max peers limit completely.

We ended up increasing the max peers count.

Thanks for your response!

**Comment by macfarla** [comment]
Great, thanks for your reply! I will close this ticket.
