### ISSUE TITLE
besu --Xlauncher     "invalid default option for rpc-http-apis"

### ISSUE THREAD

**Issue by isavelli** [hyperledger/besu#3338]
When I run "besu --Xlauncher", I get the following error: 

### Steps to Reproduce (Bug)
iacopo@LAPTOP-4HE1CDFS:~$ besu --Xlauncher-force
? Which Ethereum network would you like to use ? dev
? Which synchronization mode? fast
? Do you want to enable pruning? no
? What is the data directory ? /tmp
? Do you want to enable the JSON-RPC HTTP service ? yes
? Do you want to configure the JSON-RPC options now ? yes
? What is the JSON RPC HTTP host address ? 127.0.0.1
? What is the JSON RPC HTTP port ? 8545
2022-01-27 19:37:54.093+01:00 | main | WARN  | Besu | **Unable to run the launcher invalid default option for rpc-http-apis**

* Software version: 
besu/v21.10.9/linux-x86_64/openjdk-java-17

* Java version: [`java -version`]
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

* OS Name & Version:
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

* Kernel Version: 
Linux LAPTOP-4HE1CDFS 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by macfarla** [comment]
I can reproduce this behaviour on my local machine.

**Comment by matkt** [comment]
Hi, thanks for your ticket. I just merged a PR to fix this issue
