### ISSUE TITLE
Max number of peers not enforced correctly

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#3361]
### Description
It happens that Besu (without static peer configured) reports in the log a number of peers greather than the max allowed, for example the following log reports the number of peers to be consistently > 25 for hours:
```
{"timestamp":"2022-02-02T05:56:49,701","level":"DEBUG","thread":"EthScheduler-Timer-0","class":"WaitForPeerTask","message":"Waiting for new peer connection. 27 peers currently connected.","throwable":""}
{"timestamp":"2022-02-02T05:57:03,334","level":"DEBUG","thread":"EthScheduler-Services-716 (importBlock)","class":"WaitForPeerTask","message":"Waiting for new peer connection. 27 peers currently connected.","throwable":""}
{"timestamp":"2022-02-02T05:58:05,120","level":"DEBUG","thread":"EthScheduler-Services-721 (importBlock)","class":"WaitForPeerTask","message":"Waiting for new peer connection. 27 peers currently connected.","throwable":""}
[...]
{"timestamp":"2022-02-02T07:03:48,917","level":"DEBUG","thread":"nioEventLoopGroup-3-4","class":"WaitForPeerTask","message":"Finished waiting for peer connection.","throwable":""}
{"timestamp":"2022-02-02T07:03:53,440","level":"DEBUG","thread":"EthScheduler-Services-791 (importBlock)","class":"WaitForPeerTask","message":"Waiting for new peer connection. 27 peers currently connected.","throwable":""}
{"timestamp":"2022-02-02T07:03:58,440","level":"DEBUG","thread":"EthScheduler-Timer-0","class":"WaitForPeerTask","message":"Waiting for new peer connection. 27 peers currently connected.","throwable":""}
{"timestamp":"2022-02-02T07:04:03,440","level":"DEBUG","thread":"EthScheduler-Timer-0","class":"WaitForPeerTask","message":"Waiting for new peer connection. 26 peers currently connected.","throwable":""}
```
and calling `admin_peers` during at that time, actually returns 27 peers, see the response [peers-over-quota-20220202-0605.txt](https://github.com/hyperledger/besu/files/7985753/peers-over-quota-20220202-0605.txt)

**but at the same time, there is a discrepancy since the exported metric `ethereum_peer_count` returns 25 peers connected**
indeed the graph of this metrics never goes over 25
![image](https://user-images.githubusercontent.com/91944855/152141183-043c0d48-4bea-489a-801c-e239bd118371.png)
this metric is exported by the `RlpxAgent` that could not track all the connections correctly

**Expected behavior:** [What you expect to happen]
Max number of connected peer is enforced

**Actual behavior:** [What actually happens]
some times the number of connected peer reported in the logs goes over the max configured

### Versions (Add all that apply)
* Software version: 22.1.0-RC4-SNAPSHOT
* Java version: Java11

**Comment by iamhsk** [comment]
Hi @fab-10, we are looking into this as part of #2689. Closing it since it's a duplicate
