### ISSUE TITLE
change gradle license check plugin

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3366]
## Proposal to change besu from 
  id 'com.github.hierynomus.license' version '0.16.1-fix'
to
  id 'com.github.jk1.dependency-license-report' version '2.0'

## Acceptance Criteria
* No regression on the Gradle checkLicenses task - build will still fail if dependencies use unapproved licenses
* downloadLicenses task takes no more than 1 minute

## Background
This is now used by other consensys open source projects including: Teku, EthSigner, Web3Signer, Signers. 
https://github.com/jk1/Gradle-License-Report

example config:
this file matches the format besu already uses:
https://github.com/ConsenSys/teku/blob/master/gradle/check-licenses.gradle
this one may be new:
https://github.com/ConsenSys/teku/blob/master/gradle/license-report-config/allowed-licenses.json

**Comment by macfarla** [comment]
0.16.1 is still latest version of hierynomous https://github.com/hierynomus/license-gradle-plugin/tags
we are using a "fix" version https://github.com/hyperledger/besu/issues/3094

**Comment by shemnon** [comment]
Are there any advantages above a more active maintainer? (honestly, that is already enough to switch).

Are there any features we might lose?  Or would we even notice?

Will the build still fail with dependencies that use unapproved licenses?  That is the main feature we need.

**Comment by macfarla** [comment]
thanks @shemnon - added acceptance criteria to cover that

**Comment by non-fungible-nelson** [comment]
@macfarla - status or close? I know we had some gradle changes recently

**Comment by macfarla** [comment]
no status change. the only reason to change is we're having to use a custom build of the hieronymous tool. it works but it's a bit messy

**Comment by macfarla** [comment]
closing - it ain't broke. can revisit in the future
