### ISSUE TITLE
Getting the most up to date EVM version without EIP1559

### ISSUE THREAD

**Issue by soragXYZ** [hyperledger/besu#3374]
Hi!

I have a private network with a gasPrice null, with the EVM version being set to Berlin

I want to update it, in order to have the most up-to-date version of the EVM, but here comes my issue:

The London update contains the EIP1559 which introduce a small burn for each transaction, but with a private network with a gasPrice null it is an issue because it becomes impossible to perform a single transaction if the issuer of the transaction doesn't have funds

So my question is: how can I update my genesis.json to the latest EVM version (arrowGlacier at the time of writing) but without the EIP1559 ?

Thanks

**Comment by daniellehrner** [comment]
I would recommend you to use IBFT2 and configure the network to run with 0 gas. EIP1599 will not take effect if you do that.

IBFT2: https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/IBFT/
Free gas networks: https://besu.hyperledger.org/en/stable/HowTo/Configure/FreeGas/

**Comment by soragXYZ** [comment]
Hi @daniellehrner thanks for the reply

That's what I did, I'm using IBFT2 with a gasPrice null but it doesn't work, I can't sign a transaction if I don't have funds because for each transaction there is this small fee introduced by the EIP1559

Is it possible to share a working genesis.json configuration ?

**Comment by ccamaleon5** [comment]
Hello, we have the same problem. A network with IBFT 2.0 consensus and 0 gas price cannot be run on the London version of Ethereum, this is due to EIP 1559. Thus, for a network with 0 gas price, the baseFee parameter of the block header should be configurable. What do we need to do to run a network with a gas price 0?

**Comment by siladu** [comment]
Hi @soragXYZ and @ccamaleon5 I believe this PR should fix this issue: https://github.com/hyperledger/besu/pull/4003

It's available on the main branch and hopefully it'll make it into the next release. 
In addition to the code in the PR, you must also include `"baseFeePerGas": "0x0"` at the top level of the genesis file.
We will update the documentation to reflect this.

Please reopen or create a new issue if the problem persists even with this code.

**Comment by siladu** [comment]
The fix has been released: https://github.com/hyperledger/besu/releases/tag/22.7.0-RC1
