### ISSUE TITLE
No existing database found , map segment errors

### ISSUE THREAD

**Issue by PriyatamNayak** [hyperledger/besu#3377]
When am starting the 1st node , am getting java map segment errors
EERORS:

![image](https://user-images.githubusercontent.com/40819788/152626940-dfdb0c6c-6ae9-43ec-a125-f992b28fd0b6.png)

**Comment by PriyatamNayak** [comment]
![image](https://user-images.githubusercontent.com/40819788/152626924-34e959fe-fd23-4cca-aec7-440986c8289e.png)

**Comment by PriyatamNayak** [comment]
anyone can help??

**Comment by MadelineMurray** [comment]
hi @PriyatamNayak - what configuration are you starting with?  Is this occurring all the time or with a specific set of options?

**Comment by MadelineMurray** [comment]
Does the user you're running Besu as have access to the `/tmp` directory referenced in the first error log line?

**Comment by PriyatamNayak** [comment]
@MadelineMurray  yes the user has access to /tmp directory

besu --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --sync-mode=FAST --logging=DEBUG

**Comment by PriyatamNayak** [comment]
> hi @PriyatamNayak - what configuration are you starting with? Is this occurring all the time or with a specific set of options?

it is happening all time when am using database as rockdb

**Comment by PriyatamNayak** [comment]
[motdusrb@x01tmotdapp2a IBFT-Network]$ cat ibftConfigFile.json
{
    "genesis": {
        "config": {
            "chainId": 2018,
            "muirglacierblock": 0,
            "ibft2": {
                "blockperiodseconds": 2,
                "epochlength": 30000,
                "requesttimeoutseconds": 4
            }
        },
        "nonce": "0x0",
        "timestamp": "0x58ee40ba",
        "gasLimit": "0x47b760",
        "difficulty": "0x1",
        "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {
            "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
                "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
                "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
                "balance": "0xad78ebc5ac6200000"
            },
            "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
                "privateKey": "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
                "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
                "balance": "90000000000000000000000"
            },
            "f17f52151EbEF6C7334FAD080c5704D77216b732": {
                "privateKey": "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
                "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
                "balance": "90000000000000000000000"
            }
        }
    },
    "blockchain": {
        "nodes": {
          "generate": true,
            "count": 4
        }
    }
}

**Comment by macfarla** [comment]
unsatisfied link error - indicates a native lib problem of some flavor. What operating system are you using?

**Comment by PriyatamNayak** [comment]
@garyschulte 

4.18.0-193.70.1.el8_2.x86_64 #1 SMP Mon Nov                                                                              15 00:34:11 EST 2021 x86_64 x86_64 x86_64 GNU/Linux


Note: have already tried with openjdk11, got the same issue

**Comment by PriyatamNayak** [comment]
@garyschulte 
yes tried with latest besu version , still no luck
am getting same error

**Comment by macfarla** [comment]
@PriyatamNayak - can you give us some more specifics on your environment:
What version of besu are you using?
What JVM?
Is it a cloud vm, WSL, or an on-prem server? Details about the OS and hardware will help us figure out what the trouble might be.

**Comment by MadelineMurray** [comment]
Closing this one.  If you're still having issues, could you please let us know what the answers are to the latest questions and reopen this issue.  Thanks.
