### ISSUE TITLE
Change ChainID on genesis block , and then got a problem when startup  

### ISSUE THREAD

**Issue by eu09** [hyperledger/besu#3394]
Hi 

In our network we have 31 nodes , the besu version is v21.10.4 with IBFT2 
Because we make change on the chain id from 1001 to 1008 , when I start the besu , some of nodes of them encounter following issue ,  then it print out following message 
class":"MainnetTransactionProcessor","message":"Invalid transaction: transaction was meant for chain id 1001 and not this chain id 1008","throwable":""}

BUT some of them it can start without regarding problems after chainid get changed . Can u suggest me how to deal with this issue ? 

Detail Log : 
today at 16:28:40 {"timestamp":"2022-02-09T08:28:40,006","container":"ip-15-0-7-199","level":"INFO","thread":"EthScheduler-Services-5 (importBlock)","class":"FullImportBlockStep","message":"Import reached block 200 (0x17e5c8b6a299de2e1d1879b33421f086326309793eac547a64eaf4489eb5f800), - Mg/s, Peers: 3","throwable":""}
today at 16:28:41 {"timestamp":"2022-02-09T08:28:41,104","container":"ip-15-0-7-199","level":"WARN","thread":"EthScheduler-Services-5 (importBlock)","class":"MainnetTransactionProcessor","message":"Invalid transaction: transaction was meant for chain id 1001 and not this chain id 1008","throwable":""}

today at 16:28:41 {"timestamp":"2022-02-09T08:28:41,106","container":"ip-15-0-7-199","level":"INFO","thread":"EthScheduler-Services-5 (importBlock)","class":"AbstractBlockProcessor","message":"Block processing error: transaction invalid 'WRONG_CHAIN_ID'. Block 0x2dcb92967ff75e0ef8e83a543a852492c0b5896c0f37a86d1c1bf675161a6e61 Transaction 0x1aa8acee21f5ea78c181035c39892a45e94838d537b8c87714d0257c52794566","throwable":""}

today at 16:28:41 {"timestamp":"2022-02-09T08:28:41,160","container":"ip-15-0-7-199","level":"WARN","thread":"EthScheduler-Services-5 (importBlock)","class":"PipelineChainDownloader","message":"Invalid block detected.  Disconnecting from sync target. Failed to import block: Invalid block at #347 (0x2dcb92967ff75e0ef8e83a543a852492c0b5896c0f37a86d1c1bf675161a6e61)","throwable":""}

today at 16:28:41 {"timestamp":"2022-02-09T08:28:41,177","container":"ip-15-0-7-199","level":"WARN","thread":"EthScheduler-Services-5 (importBlock)","class":"PipelineChainDownloader","message":"Chain download failed. Restarting after short delay.","throwable":" java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #347 (0x2dcb92967ff75e0ef8e83a543a852492c0b5896c0f37a86d1c1bf675161a6e61)\n\tat java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)\n\tat java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)\n\tat java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)\n\tat org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)\n\tat org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #347 (0x2dcb92967ff75e0ef8e83a543a852492c0b5896c0f37a86d1c1bf675161a6e61)\n\tat org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:55)\n\tat org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)\n\tat org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)\n\tat org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)\n\t... 5 more\n"}

**Comment by macfarla** [comment]
If you change your chain id, you essentially need to start a new chain (from block zero ie you lose all existing data). To peer with each other, nodes need to have matching genesis block (ie genesis file) which includes the chain id. If you have some nodes running on chain id 1001 and some running on 1008, you're essentially running to chains that can't talk to each other.
To fix this, 
* stop all your nodes, 
* make the change to the chain id in the genesis file, 
* make sure all nodes have the same genesis file - copy the file to all locations or share it however you do
* you will need to either delete the data directory or point to a new location (again, for all nodes)
* now you can start your nodes

**Comment by macfarla** [comment]
let us know if you have further issues

**Comment by puneet166** [comment]
But , if i do some modifications in genesis file. 
question is i want to do some modifications without losing existing data. what's steps i need to follow for this senorio?

do hard fork?

**Comment by puneet166** [comment]
@macfarla

**Comment by macfarla** [comment]
some config items in the genesis can be changed but most changes to the genesis require a new chain. What specifically is your use case?
