### ISSUE TITLE
time to run a single test is too long

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3449]
When I run a single test in my IDE, it takes 30s or more. Even when running the same test again with no code changes.

We would like to get build time <10s

**Comment by ajsutton** [comment]
IntelliJ defaults to running individual tests via gradle which is significantly slower but you can tell it to run them itself instead:
![Screen Shot 2022-02-17 at 1 23 13 pm](https://user-images.githubusercontent.com/72675/154398832-6f19a89f-c316-4de8-b5b4-162f9b778539.png)

Speeding up the processing of the gradle build file is still a good idea for other builds though.

**Comment by non-fungible-nelson** [comment]
@macfarla - status or close?
