### ISSUE TITLE
initial sync creates too much logging

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3450]
### Description
As a sysadmin/dev, I want to reduce the amount of logging on full/fast sync (at default logging level) so that I don't exceed my company's logging limits. 

### Acceptance Criteria
At default logging level (INFO):
* fast sync < 5,000 messages per hour 
* full sync < 5,000 messages per hour

### Steps to Reproduce (Bug)
start a new full sync or fast sync node

**Expected behavior:** [What you expect to happen]
<5,000 messages per hour

**Actual behavior:** [What actually happens]
>11,000 log messages per hour

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: [`besu --version`]
22.1.0
* Java version: [`java -version`]
* openjdk version "11.0.11" 2021-04-20 LTS
* OS Name & Version: [`cat /etc/*release`]
* NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
* Kernel Version: [`uname -a`]
amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud VM, type, size: [Amazon Web Services I3-large]
makes no difference

**Comment by frankisawesome** [comment]
Might be good to specify whether the count includes trace logs?

**Comment by macfarla** [comment]
<img width="1195" alt="Screen Shot 2022-02-17 at 8 02 37 pm" src="https://user-images.githubusercontent.com/2627919/154452916-61b60e8d-df62-44f6-9de0-a2958becb555.png">

**Comment by macfarla** [comment]
^ some of those are teku logs but the vast majority is besu
