### ISSUE TITLE
make spotless a separate CI step

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3456]
make spotless a separate CI step ala teku https://app.circleci.com/jobs/github/ConsenSys/teku/109621?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
Currently it's under assemble - moving it to a separate step would make it instantly visible that that's the problem

**Comment by siladu** [comment]
Related to this, is there a reason why spotless doesn't break `assemble` locally? This would minimise the chance of committing a spotless violation
