### ISSUE TITLE
Sync issues and many "1000 expired transaction messages have been skipped" warning

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#3524]
### Description
It seems there is a correlation when Besu is not able to stay in sync on mainnet and the presence of many warnings in the log, stating that `"1000 expired transaction messages have been skipped.`

for example this graph, shows that Besu if frequently some blocks behind
![image](https://user-images.githubusercontent.com/91944855/156734463-31527558-eed2-428f-bee3-e17e2a513897.png)
and at the same time the log if full of warnings:
```
{"timestamp":"2022-03-04T09:14:34,355","level":"WARN","thread":"EthScheduler-Transactions-1","class":"TransactionsMessageProcessor","message":"1000 expired transaction messages have been skipped.","throwable":""}
{"timestamp":"2022-03-04T09:14:35,411","level":"WARN","thread":"EthScheduler-Transactions-1","class":"TransactionsMessageProcessor","message":"1000 expired transaction messages have been skipped.","throwable":""}
{"timestamp":"2022-03-04T09:14:35,688","level":"WARN","thread":"EthScheduler-Transactions-0","class":"PendingTransactionsMessageProcessor","message":"1000 expired transaction messages have been skipped.","throwable":""}
{"timestamp":"2022-03-04T09:14:36,161","level":"WARN","thread":"EthScheduler-Transactions-0","class":"TransactionsMessageProcessor","message":"1000 expired transaction messages have been skipped.","throwable":""}
{"timestamp":"2022-03-04T09:14:36,938","level":"WARN","thread":"EthScheduler-Transactions-0","class":"TransactionsMessageProcessor","message":"1000 expired transaction messages have been skipped.","throwable":""}
{"timestamp":"2022-03-04T09:14:37,638","level":"WARN","thread":"EthScheduler-Transactions-1","class":"TransactionsMessageProcessor","message":"1000 expired transaction messages have been skipped.","throwable":""}
```

at the same time the `transactions` executor, has a very long queue
![image](https://user-images.githubusercontent.com/91944855/156734816-9dffea8d-7862-4737-b4d5-f348569f41ba.png)
and this could be a symptom, that Besu is queuing too much and is not able to process in time these messages.

If queuing too much is the issues, then a limit on the queue or other strategy to discard some messages should be implemented

### Versions (Add all that apply)
* Software version: 22.1.0
* Java version: Java11
* Cloud VM, type, size: Amazon t3.xlarge with EBS gp3

**Comment by ajsutton** [comment]
Those warnings are the strategy to discard messages if Besu is unable to keep up with the rate of incoming transactions messages.  So I'd suggest this is a side effect of Besu not being able to keep up.  The big question is, why can't Besu keep up? It may be that there's a spike in the number of transactions messages which then consumes too much CPU causing the whole node to fall behind or there could be something like lock contention causing both block import and transaction processing to fall behind.
