### ISSUE TITLE
Add support for Mac M1 processor/Multi-Platform builds

### ISSUE THREAD

**Issue by lunoon** [hyperledger/besu#3540]
### Description
As a developer/user I want to use the Docker image to develop and test.  
However there is currently no support for the M1 processor yet and the current workaround is to use —platform=linux/amd64 flag in Docker.

### Acceptance Criteria
* Support of the docker image with ARM processors such as M1 with Multi-Platform builds.

### Versions (Add all that apply)
* Software version: [`besu --version`] all
* Java version: [`java -version`] all
* OS Name & Version: [`cat /etc/*release`] MacOS 12.2
* Kernel Version: [`uname -a`] Darwin 21.3.0
* Docker Version: [`docker version`] all

**Comment by macfarla** [comment]
We are working on getting this working. https://github.com/hyperledger/besu/pull/3481
