### ISSUE TITLE
Test loading large number of keys from AWS secrets manager

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#3542]
Test Web3Signer with large number keys to see if there are any performance issues.

**Tasks**
* Create 10,000 keys in AWS secrets manager
* Time how long it takes for Web3Signer to load all the keys
* Monitor resource usage as it is loading the keys i.e. CPU, memory, threads

**Comment by usmansaleem** [comment]
Closing due to opened in incorrect project
