### ISSUE TITLE
amount of gas returned from eth_estimateGas API is so large for the transactions that are going to fail

### ISSUE THREAD

**Issue by GowthamParamasivam** [hyperledger/besu#3576]
As a besu user, we have a private network, we have smart contracts deployed in the network, while interacting with the contracts, there may be transactions that will fail due to some constraints, but for these transactions, the return value from the [eth_estimateGas](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_estimategas) api is so large than the same transaction that will success. 

For example, consider onlyOwner function is called from another address than the owner in that case the eth_estimateGas api is large than the same transaction is done from the owner's address.

### **Steps to reproduce the bug**
1. Deploy a smart contract with a function with any validation.
2. Initiate a transaction with failed validation.
3. The gas limit shown on the wallet apps is too large than the success scenario.

**Expected behavior:**
The eth_estimateGas api, after stimulating the transaction should return the gas limit needed for the transaction.

**Actual behavior:**
The eth_estimateGas api returns a gas limit value too large for the transaction.

### Versions (Add all that apply)
* Software version: besu/v22.1.1/linux-x86_64/oracle_openjdk-java-16
* Java version: openjdk 16 2021-03-16
* OS Name & Version: Ubuntu 20.04.3 LTS
* Kernel Version: Linux ip-10-0-100-135 5.11.0-1022-aws 23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud VM, type, size: [Amazon Web Services t2-large]

### Additional Information
The transactions is initialized through remix ide and blockscout explorer. In other clients like geth we are not facing this issue.

**Comment by frankisawesome** [comment]
Hey @GowthamParamasivam are you able to package the contracts into a repo so we can replicate the issue?

**Comment by GowthamParamasivam** [comment]
Hi @frankisawesome , I have a very basic solidity contract, just to add a number with a condition the number should be greater than 10. You can find the [repo here](https://github.com/GowthamParamasivam/besu-issue-3576). 

gas estimate for simple addition that will fail 
![image](https://user-images.githubusercontent.com/43418883/158292079-9cf2f614-6cbb-4f68-b694-2d6a04622eda.png)

**Comment by GowthamParamasivam** [comment]
Seems like the issue is with the metamask wallet app and not on the besu side, there are few [issues](https://github.com/MetaMask/metamask-extension/issues/10276) opened on the metamask side related to this. So I am closing this issue.
