### ISSUE TITLE
Peering improvements

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3581]
### Problem Statements
1. Besu node connects and disconnects with same peer; Having duplicate peers (addressed by #2689)
2. Other peers are disconnecting with Besu nodes (addressed by #3980)
3. Peers list are not filling up (addressed by #3897 and #3982)
5. There's a risk of malicious actors connecting as peers (addressed by #3981)
6. Number of peers exceeding the max number specified (not really an issue)

### Goal
Node operators can quickly start syncing/importing blocks by having 
Besu find "good" peers fast and consistently have good ones.
 
### How Will We Know We Are Successful?
Compare the **time to complete a snap sync** before and after a set of improvements we make in peering 

Baseline metrics: #3853

### How Are We Defining Good Peers?
- Provides correct world state data fast
- Has a matching pivot block
- Has fast response time
- Delivers the data we ask for
- Has "heaviest" chain 
- Gets and gossips new blocks early

**Comment by non-fungible-nelson** [comment]
should we close this ? we can keep the remaining items in the icebox

**Comment by macfarla** [comment]
ok
