### ISSUE TITLE
Peering behavior - baseline

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3598]
### Description
As a Besu dev, I want to establish a baseline for peering behavior so that when we make changes to peering code, we know whether we are making it better. 

### Acceptance Criteria
eg Release 22.1.2 is a good opportunity to observe the behaviour of new nodes as they start up - eg how long it takes a new besu node to sync goerli. - make a doc to paint a picture of what normal looks like for each testnet/mainnet. Screenshots if helpful
Example of what may be helpful to track:
* Time to sync from scratch (where appropriate)
* Time for an existing node to catch up
* Time to gain N peers

**Comment by macfarla** [comment]
This log means the P2P agent started
2022-03-29 08:31:27.174+10:00 | vert.x-eventloop-thread-2 | INFO | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0:0:0:0:0:0:0:0:30303
And then once sufficient useful peers are obtained, full sync starts with something like this
2022-03-29 09:08:26.831+10:00 | nioEventLoopGroup-3-3 | INFO | SyncTargetManager | Found common ancestor with peer Peer 0x0b7150c1adbaec3bc6... at block 0
fast sync is a bit different
once it has (minimum) 5 peers
2022-03-29 09:22:10.702+10:00 | EthScheduler-Timer-0 | INFO  | FastSyncActions | Selecting block number 5062554 as fast sync pivot block.
Then it waits for 5 confirmations of pivot block which can take a while and obviously depends on quality of peers
2022-03-29 09:37:16.549+10:00 | nioEventLoopGroup-3-5 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 5062554: 0xd4e574268148d0544f7a74402fe80dde2cfc8cf2ca5901f60d373eeb243b18d5
then can download world state
2022-03-29 09:37:16.558+10:00 | nioEventLoopGroup-3-5 | INFO  | FastWorldStateDownloader | Begin downloading world state from peers for block 5062554 (0xd4e574268148d0544f7a74402fe80dde2cfc8cf2ca5901f60d373eeb243b18d5). State root 0x7ca542145e6c33e8aea6142133d1d195fb02ef38a63ff3450a8011a00ef2c953

**Comment by macfarla** [comment]
Is the "time to sync from scratch" a good thing to measure, since on a network like goerli, the number of blocks is always increasing, the amount of time expected will also increase - it's a moving target.

**Comment by ahamlat** [comment]
If we focus on Fast sync as our use case, I understand that we have 3 checkpoints :

- P2P peer discovery agent start
- Selecting fast sync pivot block
- Confirming pivot block (the same as step 2)

Do you agree with this ?
I noticed the same thing regarding the number of blocks, I think the difference is negligible regarding the total number of blocks, but still important to mention it. For my first baseline on Fast Sync, I display the number of imports (each import = 200 blocks) to keep an eye on it

**Comment by macfarla** [comment]
Yes and the third step "Confirming the pivot block" will be highly dependent on gaining "good" peers quickly

**Comment by ahamlat** [comment]
I noticed two behaviours during baseline calculation, either peering is very fast (less than 12 s), either peering is much slower (> 5 minutes). I guess this related with the quality of peers.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/5099602/160746407-920b02f1-f8fd-4a39-b319-3dd4686a0d5e.png">

**Comment by ahamlat** [comment]
This calculation is done on Goerli fast sync nodes, started with the same parameters on i3.xlarge AWS instance (ohio), besu version 22.1.1

**Comment by macfarla** [comment]
@ahamlat how can we generate these numbers - eg if we spin up a new node off a branch to test some new code?

**Comment by ahamlat** [comment]
@macfarla for the moment, this is done manually by using logs timestamps but it can be automated. I use this kind of requests to display all the timestamps : ("Selecting block number" or  "Confirmed pivot block" or "P2P peer discovery agent started and listening")

**Comment by frankisawesome** [comment]
I think it's useful to look at the time elapsed between the 'Selecting block number xx as fast sync pivot block' so we get a better understanding of how long a complete pivot download takes
