### ISSUE TITLE
Unhandled exception error with no details

### ISSUE THREAD

**Issue by frankisawesome** [hyperledger/besu#3603]
I've noticed some logs like this:
2022-03-17 23:32:34.706+00:00 | vert.x-eventloop-thread-2 | ERROR | RoutingContext | Unhandled exception in router

There's no error details and can be confusing to node operators (is it critical or not? how do we solve it?)

Unclear how to replicate at this stage we might wanna look in where the exception is logged instead.

**Comment by Sidahmed-ben** [comment]
Hello @frankisawesome  , I'm interested by the issue  can you assign it to me please  😀

**Comment by frankisawesome** [comment]
done, let me know if you need anything @Sidahmed-ben

**Comment by Sidahmed-ben** [comment]
@frankisawesome , okay thank you.

**Comment by alancwoo** [comment]
I'm noticing this as well, seems to relate to the immediately preceding: `vert.x-eventloop-thread-1 | WARN  | JsonRpcService | Rejecting new connection from 127.0.0.1:52526. Max 80 active connections limit reached.`

I'm getting this message quite regularly, twice a minute or so. I'm using Nimbus as a CL.

Besu `22.7.2` and Nimbus `22.9.0`
