### ISSUE TITLE
Update Vert.x 4.2.3 -> 4.2.6 -> 4.2.7

### ISSUE THREAD

**Issue by mark-terry** [hyperledger/besu#3605]
Vert.x updates are available. Latest is 4.2.6, Besu is using 4.2.3.

This was attempted earlier and _possibly_ caused flakey tests: https://github.com/hyperledger/besu/issues/3555

**Comment by macfarla** [comment]
latest is 4.2.7. CI has run > 5 times with 4.2.6/4.2.7 with zero flakiness.
