### ISSUE TITLE
Migrate Backwards sync to use the common pipeline mechanic

### ISSUE THREAD

**Issue by gezero** [hyperledger/besu#3613]
### Description
As a Besu developer, I want backwards sync to use the pipeline mechanism so that it is easier for me to maintain the code. 
This is a follow-up work raised during the [PR ](https://github.com/hyperledger/besu/pull/3532)

**Comment by non-fungible-nelson** [comment]
PoS network - full sync will require a full BWS.

**Comment by non-fungible-nelson** [comment]
Check #3826 as well

**Comment by siladu** [comment]
@non-fungible-nelson We'd like to close this, to be replaced by whatever solution sync workstream comes up with.

**Comment by non-fungible-nelson** [comment]
as long as we can mitigate the headaches of BWS and are tracking somewhere
