### ISSUE TITLE
merge: Refactor backward sync to use pipeline

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#3614]
### Description
The initial version of batched backward sync from #3532 does not implement the pipeline chain download model.  This issue exists to unblock merging the existing implementation and track the refactor of the backward sync into the pipeline chain download model that full, fast and snap sync use.

### Acceptance Criteria
* refactor of backward sync to fit pipeline chain download model

**Comment by non-fungible-nelson** [comment]
@fab-10 - was this altered with BWS changes in 22.10.x series?

**Comment by fab-10** [comment]
no, this has not changed

**Comment by non-fungible-nelson** [comment]
Leaving open for now

**Comment by non-fungible-nelson** [comment]
closing duplicated
