### ISSUE TITLE
JVM memory can't be tuned via BESU_OPTS parameters

### ISSUE THREAD

**Issue by CaixiangFan** [hyperledger/besu#3618]
### Description
I am trying to improve the Besu performance (TPS, latency) through making better use of the available RAM resources. By default, JVM can only use up to 25% of RAM available to the Docker container. I wanted to make it to be 60% or higher by setting the BESU_OPTS parameters. But, it doesn't work.

### Steps to Reproduce (Bug)
1. Configure a private Besu network on 4 VM instances each one with 8vCPU-30gbRAM. Use Docker to run a node on each VM, connecting via host network.
2. Run Docker container on each node in a bash file by setting the environment parameter of BESU_OPTS as following:
`export HOSTNAME=$(hostname)docker run -d --rm \
    --name $HOSTNAME \
    --net host \
    -v ${PWD}/data:/opt/besu/data \
    -v ${PWD}/genesis.json:/config/genesis.json \
    -v ${PWD}/config.toml:/config/config.toml \
    -e BESU_OPTS='-Xms16G -Xmx24G' \
    hyperledger/besu:latest \
    --config-file=/config/config.toml`

3. Check the JVM info in Docker container.
`docker exec -it $(docker ps --format '{{.Names}}' | grep besu) java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"`

**Expected behavior:** 
Expected the MaxHeapSize to be around 24gb.

**Actual behavior:** 
The MaxHeapSize is around 7.8gb, 25% of the total RAM of the VM.
   `size_t MaxHeapSize                              = 7891582976                                {product} {ergonomic}
 uint64_t MaxRAM                                   = 137438953472                           {pd product} {default}
    uintx MaxRAMFraction                           = 4                                         {product} {default}
   double MaxRAMPercentage                         = 25.000000                                 {product} {default}
   size_t ShenandoahSoftMaxHeapSize                = 0                                      {manageable} {default}`

**Frequency:** [What percentage of the time does it occur?]
Always.

### Versions (Add all that apply)
* Software version: [`besu --version`] 21.10/22.1/latest
* Java version: [`java -version`] openjdk 11.0.11
* OS Name & Version: [`cat /etc/*release`] Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-104-generic x86_64)
* Docker Version: [`docker version`]. 20.10.8

I also tried to export the BESU_OPTS as an environmental variable, and use JAVA_OPTIONS instead. 
None of them works as expected. 
Any suggestions would be much appreciated. Thank you.

**Comment by shemnon** [comment]
Step 3 shows the memory to a plain old java call whereas BESU_OPTS is used in the besu shell script.  Hence any settings to BESU_OPTS are not applied.

Try adding `-XshowSettings:vm` into the BESU_OPTS and java will show the memory settings prior to execution in step 2.  If you do not want memory settings in every startup you can alter step 3 to include `java $BESU_OPTS -XX:+PrintFlagsFinal -version` as the java command.

**Comment by CaixiangFan** [comment]
Thanks a lot, shemnon!
