### ISSUE TITLE
Feature: RPC and WS Engine API on unified port

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#3619]
### Description

For drop-in replacement of Geth, it'd be useful if both the RPC and WS endpoints for the engine API were on the same port, namely 8551.

Currently RPC is on 8550 and WS on 8551:

```
execution_1             | 2022-03-21 19:40:11.328+00:00 | vert.x-eventloop-thread-1 | INFO  | JsonRpcHttpService | JSON-RPC service started and listening on 0.0.0.0:8550
execution_1             | 2022-03-21 19:40:11.330+00:00 | main | INFO  | WebSocketService | Starting Websocket service on 0.0.0.0:8546
execution_1             | 2022-03-21 19:40:11.337+00:00 | vert.x-eventloop-thread-1 | INFO  | WebSocketService | Websocket service started and listening on 0.0.0.0:8546
execution_1             | 2022-03-21 19:40:11.338+00:00 | main | INFO  | WebSocketService | Starting Websocket service on 0.0.0.0:8551
execution_1             | 2022-03-21 19:40:11.340+00:00 | vert.x-eventloop-thread-1 | INFO  | WebSocketService | Websocket service started and listening on 0.0.0.0:8551
```

Geth, Erigon and Nethermind have a combined RPC/WS endpoint defaulting to 8551.

**Comment by yorickdowne** [comment]
I could work around it with `--engine-rpc-http-port=8551 --engine-rpc-ws-port=8551` - any concerns about doing so?

**Comment by frankisawesome** [comment]
How does this work? (I think using just --engine-rpc-http-port=8551 is enough if you want them to be on the same port) but wouldn't this create issues? I've seen error responses like this
```
2022-03-21 16:04:55.378 ERROR - Execution Client is offline
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 400; Websocket endpoint can't handle HTTP requests
```

**Comment by yorickdowne** [comment]
So the "correct" way of doing WS is to have a lone, single port, and then either you do get `Connection: Upgrade`, which means it's now a Websocket connection, or you don't, in which case it remains an RPC connection.
