### ISSUE TITLE
[SPIKE] Peer Reputation: Score-based rep

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3659]
- [ ] modify existing timeout and "useless response" from N strikes to a score decrement

Based on Teku reputation management and “score based” peers. Use this approach but keep the same current functionality.

Comment on this ticket with benchmarking results

Timeboxed to 1 week

**Comment by mark-terry** [comment]
Closing as impact of changes was inconclusive. Other changes to peering behaviour may warrant revisiting reputation scoring at a later date.
