### ISSUE TITLE
Measure peering metrics for a cluster of besu and geth nodes running on goerli

### ISSUE THREAD

**Issue by frankisawesome** [hyperledger/besu#3668]
Use docker-compose to set up a network of besu/geth nodes, measure the peering performance of both (number of peers over time, disconnect reasons etc) to better understand what could be improved.

**Comment by macfarla** [comment]
this can be achieved right now by enabling DEBUG logging on a particular besu node. eg enable this for an hour or so and then turn back to INFO

**Comment by frankisawesome** [comment]
Turn on DEBUG for peering in Besu:
```
curl -X POST --data '{"jsonrpc":"2.0", "method":"admin_changeLogLevel", "params":["DEBUG", ["org.hyperledger.besu.ethereum.p2p"]], "id":1}' http://127.0.0.1:8545
```
