### ISSUE TITLE
LGTM failing OOM

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3670]
LGTM is consistently failing on besu builds with OOM error 
https://lgtm.com/projects/g/hyperledger/besu/logs/rev/pr-d6dd4712c9a1ee478aa5da254e222a6317120b2d/lang:java/stage:Build%20merge_f872a9a4e6f86569e1470ac2191efefa70217cd7

Can we allocate more memory for java heap to complete analysis?
 
https://lgtm.com/logs/232a1c40db7e0d13be74d61f159204faf206bd65/lang:java

Can we exclude languages we don't use? eg python

**Comment by diega** [comment]
Closed by #3709
