### ISSUE TITLE
Peer list is not consistent tested with small network

### ISSUE THREAD

**Issue by helderjnpinto** [hyperledger/besu#3673]
### Description

As a blockchain client validador or not i want a list of a peers of my network not in duplicated and more consistent.

### Acceptance Criteria
- In small network (we talk about 4 validators) only of validators should by a consistent count between all peers
- Not have duplicated nodes (like filter by enode public key and ip)

### Steps to Reproduce (Bug)
- I made a setup local with multiple clients using docker-compose below i will put my findings.

In the following tests i made with same group of validators that is composed by: 
1 bootnode + validator IBFT 2.0
3 validators IBFT 2.0

#### Test 1 - Testing only a small group of validators

![Peers-testing-besu drawio (4 valid)](https://user-images.githubusercontent.com/12281088/161228489-45edcc09-b76e-46bf-b4d3-f5edb5d3d5af.png)

![e5a63673898f226ce8f5a56de2fc2293](https://user-images.githubusercontent.com/12281088/161228686-3b42de9a-38b0-492e-9c82-c030a8a69c4a.png)

This result some times give the same amount of peers should be 4 on each of them that i think it is correct i suppose.
working dockers more than 30 min.

#### Test 2 - Testing only a small group of validators + clients

![f4c4304b0b834365b0a84c12a1833771](https://user-images.githubusercontent.com/12281088/161229910-f532cd6b-86d3-4800-afa4-1f887c8d950d.png)

![6fc776bcc1fa4c27baafb65e333cc532](https://user-images.githubusercontent.com/12281088/161230007-ded0bf00-5cfe-44cd-85a2-444826b0b059.png)

Some result as test 1 the peers count never is equal working time > 1h.

#### Test 3 - Testing validators + clients with other parameters
![5832ed7b68d74e8eadc89c3e0dc0cd77](https://user-images.githubusercontent.com/12281088/161230506-1ac56cc2-fab0-4e77-860d-8fc2d0c02446.png)

![195f4023bda3419893c3a5de7ffb4ea7](https://user-images.githubusercontent.com/12281088/161230870-32afafb8-698f-41cf-89bc-36aa29cc14f1.png)

some of the peers have duplicated peer enode but network property have different ports (at first time i thought maybe is a docker-compose thing) but when i checked my aws network i also have duplicate enodes and this exists in different pods.

![c8b3e24761a94493a29dedb21f0d66cd](https://user-images.githubusercontent.com/12281088/161231186-6ab25674-c5d3-44f3-9d18-a9397ef76ca8.png)

### Additional Information (Add any of the following or anything else that may be relevant)

* Besu version is 21 (this bug is present in older versions) I tested this to try solve the other issue  #2011 
* Linux l480 5.13.0-39-generic 20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - i5, 16 GB RAM.

**Comment by frankisawesome** [comment]
Thanks for the detailed report - this is a known issue that's currently in our backlog, we had a draft PR up but other priorities came up so it's pending further work, we'll use this issue and report back once progress is made.

Feel free to look at the draft pr in the meantime https://github.com/hyperledger/besu/pull/3383

**Comment by macfarla** [comment]
For clarity @helderjnpinto we are closing this issue as a duplicate - this will be addressed as part of the work for https://github.com/hyperledger/besu/issues/2689
