### ISSUE TITLE
Besu reports payload as valid from newPayload but invalid from forkChoiceUpdated

### ISSUE THREAD

**Issue by ajsutton** [hyperledger/besu#3677]
### Description
When running the `BellatrixMergeTransitionAcceptanceTest` in Teku (with besu 22.1.3 current develop), the actual transition block is accepted by `newPayload` with a VALID response but then is INVALID when set as the chain head via `forkChoiceUpdated`. The same execution payload can't be both valid and invalid.

newPayload call:
```json
{"jsonrpc":"2.0","method":"engine_newPayloadV1","params":[{"parentHash":"0xccd88cdf13f0970314d4a99daada6f6019faf5c91739417d6d20caceeec63288","feeRecipient":"0xfe3b557e8fb62b89f4916b721be55ceb828dbd73","stateRoot":"0x9b06a788c91be3a261a7a9b0d6866530edb4884c6f0f806c1af14957e3bff5e7","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","prevRandao":"0x20687643f94afae7c01eae4198f4a32430789c21a37e604b80d60e21eec73a00","blockNumber":"0x65","gasLimit":"0x1ffffffffffbff","gasUsed":"0x0","timestamp":"0x624a3adb","extraData":"0x","baseFeePerGas":"0x1","blockHash":"0xf0aa7e775de96cb5e9093161c3be1e93bec2e22b4884612ed5d63c002150402e","transactions":[]}],"id":389}
```
```json
{
"jsonrpc" : "2.0",
"id" : 389,
"result" : {
"status" : "VALID",
"latestValidHash" : "0xf0aa7e775de96cb5e9093161c3be1e93bec2e22b4884612ed5d63c002150402e",
"validationError" : null
}
}
```

Then forkChoiceUpdated call:
```json
{"jsonrpc":"2.0","method":"engine_forkchoiceUpdatedV1","params":[{"headBlockHash":"0xf0aa7e775de96cb5e9093161c3be1e93bec2e22b4884612ed5d63c002150402e","safeBlockHash":"0xf0aa7e775de96cb5e9093161c3be1e93bec2e22b4884612ed5d63c002150402e","finalizedBlockHash":"0x0000000000000000000000000000000000000000000000000000000000000000"},{"timestamp":"0x624a3ae1","prevRandao":"0xad601acc23b20b2f23e775d23922f0096a7d184deb470ceea049ebc5f8f38103","suggestedFeeRecipient":"0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"}],"id":396}
```

```json
{
"jsonrpc" : "2.0",
"id" : 393,
"result" : {
"payloadStatus" : {
"status" : "INVALID",
"latestValidHash" : "0xf0aa7e775de96cb5e9093161c3be1e93bec2e22b4884612ed5d63c002150402e",
"validationError" : "new head timestamp not greater than parent"
},
"payloadId" : null
}
}
```

Note that the `latestValidHash` is set to the requested head block suggesting it is in fact valid.

**Comment by jflo** [comment]
Turns out forkChoice was the correct one. We also updated the logic around `latestValidHash` around the same time timestamp validation was made consistent across those calls:

https://github.com/hyperledger/besu/blob/277c3e44d21c384725fabfa5a5a9d72c73cd2435/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java#L145-L152

Does this test in question maybe not update timestamps on next blocks it sent?

**Comment by ajsutton** [comment]
Yeah I just realised that when mining with a really low fixed difficulty, besu will create blocks in the future (up to a limit of something like 15 seconds).  That doesn't work too well with the merge because the terminal block then winds up being from after the start of the current slot and this check fails. Would have resolved itself if newPayload had returned INVALID as the beacon block would have been entirely rejected and a new merge block created but the inconsistent response meant things got stuck with an invalid block as head.

**Comment by ajsutton** [comment]
Yeah we put a check into Teku to delay accepting a terminal block until it's timestamp isn't in the future which solves that issue - I don't think besu is wrong to be mining "future" blocks and it is something that could be done by miners on mainnet (though fairly unlikely).

Was there a PR to fix the newPayload result recently? We were getting inconsistent results on the latest develop version as of 2 days ago and I don't see anything that has changed since.

> Does this test in question maybe not update timestamps on next blocks it sent?

Because Teku gets a VALID response from newPayload, it rejects the INVALID response from fcu because a block can't go from being valid to invalid so we keep trying to build on that block and the system is then stuck.

**Comment by ajsutton** [comment]
I can confirm this is still a problem with the latest `develop` build:
besu/v22.4.0-RC2-dev-92de455a/linux-x86_64/openjdk-java-11

I get VALID from `engine_newPayloadV1` but then INVALID from `engine_forkChoiceUpdated` for the same block.

**Comment by ajsutton** [comment]
It turns out I do still have the logs and looking more closely now I think this is actually the issue that Enrico found and fixed in teku where the payloadAttributes we're sending with fcu are invalid.  That's causing Besu to incorrectly tell us the block is invalid - Geth returns a JSON-RPC error in that case not INVALID.

```
{"jsonrpc":"2.0","method":"engine_newPayloadV1","params":[{"parentHash":"0x68051baceaacdeabb
c6d384cdaf320e44981b2ef39252f953744d0befe7866c7","feeRecipient":"0xfe3b557e8fb62b89f4916b721be55ceb828dbd73","stateRoot":"0xbb0c7d8f66efcecf9c677129818ea89bbf21ac97f20bbb89bf27fa212ccac132","receiptsRoot":"0x
56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","prevRandao":"0x77aae49450097
576268604d0fd4c08d2d72caee9048c4070873e1b9976ab2c8d","blockNumber":"0x65","gasLimit":"0x1ffffffffffbff","gasUsed":"0x0","timestamp":"0x624d0d3b","extraData":"0x","baseFeePerGas":"0x1","blockHa
sh":"0xac33ef90c62cdf7cc47808ad3803988ffdb1a05e43e91172e3780bb10993a6e2","transactions":[]}],"id":346}


{
"jsonrpc" : "2.0",
"id" : 346,
"result" : {
"status" : "VALID",
"latestValidHash" : "0xac33ef90c62cdf7cc47808ad3803988ffdb1a05e43e91172e3780bb10993a6e2",
"validationError" : null
}
}




{"jsonrpc":"2.0","method":"engine_forkchoiceUpdatedV1","params":[{"headBlockHash":"0xac33ef90c62cdf7cc47808ad3803988ffdb1a05e43e91172e3780bb10993a6e2","safeBlockHash":"0xac33ef90c62cdf7cc47808ad3803988ffdb1a05e43e91172e3780bb10993a6e2","finalizedBlockHash":"0x0000000000000000000000000000000000000000000000000000000000000000"},{"timestamp":"0x624d0d41","prevRandao":"0x89f0d85b01335f671851c45495ad7ec75cf94bf53a455b6ef5de14eb1f24695b","suggestedFeeRecipient":"0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"}],"id":349}


{
"jsonrpc" : "2.0",
"id" : 349,
"result" : {
"payloadStatus" : {
"status" : "INVALID",
"latestValidHash" : "0xac33ef90c62cdf7cc47808ad3803988ffdb1a05e43e91172e3780bb10993a6e2",
"validationError" : "new head timestamp not greater than parent"
},
"payloadId" : null
}
}
```

**Comment by jflo** [comment]
Ah yes. This behavior is currently underspecified.  Which one is correct is currently being discussed.

**Comment by jflo** [comment]
Rough consensus indicates that this should return a JSON-RPC error instead of an INVALID result. Reasoning being there is nothing wrong with the block in this case, just the parameter.
