### ISSUE TITLE
Remove jetbrains specific NotNull annotations

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3680]
Remove the jetbrains specific @NotNull annotations. There are javax annotations that could be used instead. 
eg 
org.jetbrains.annotations.NotNull
replace with
javax.annotation.Nonnull

**Comment by shemnon** [comment]
I would prefer not to use Sonar specific annotations, and instead rely on javax annotations.  I don't think there are any in the sonar namespaces.  I have a fairly dim view of Sonar at the moment and don't think we should put any in-code tie-ins to sonar.

**Comment by macfarla** [comment]
Thanks @shemnon - updated the issue - does that make sense?
