### ISSUE TITLE
Besu on Windows starting too long, only after reading 200GB of data

### ISSUE THREAD

**Issue by kirillp** [hyperledger/besu#3682]
I use the latest  Besu version 
Besu starting too long, only after reading 200GB of data

### Acceptance Criteria
Besu to start fast (<2 min)

### Steps to Reproduce (Bug)
1 Start Besu on windows, wait it to finish sync, 
2 press Ctrl-C, wait Besu exit
3 Start it again

**Expected behavior:** Besu to start fast (<2 min)

**Actual behavior:** besu starts for **hours**

**Frequency:**  always

* Software version: besu/v22.1.3/windows-x86_64/oracle_openjdk-java-17

* Java version: 
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

* OS Name & Version: 

Edition	Windows 10 Pro
Version	21H2
OS build	19044.1620

* Besu setup info - 
    command line options:   --data-path D:/main-data --data-storage-format="BONSAI" --rpc-http-enabled

* System info - 

Processor	Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz   3.00 GHz
Installed RAM	16.0 GB (15.9 GB usable)

VisualVM profile of start is attached

![image](https://user-images.githubusercontent.com/4068190/161510884-d5afda08-3230-47db-8cc1-266a3e5243de.png)

And it looks like it does this job more then once
<img width="842" alt="image" src="https://user-images.githubusercontent.com/4068190/161512572-66605735-55e3-4b8b-a2b3-81fce79087da.png">

**Comment by kirillp** [comment]
this is a part of logfile containing the delays

> 2022-04-04 11:19:47.291+03:00 | main | INFO  | AbstractAltBnPrecompiledContract | Native alt bn128 not available
> 2022-04-04 11:19:47.304+03:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Frontier: 0, Homestead: 1150000, DaoRecoveryInit: 1920000, DaoRecoveryTransition: 1920001, Homestead: 1920010, TangerineWhistle: 2463000, SpuriousDragon: 2675000, Byzantium: 4370000, Petersburg: 7280000, Istanbul: 9069000, MuirGlacier: 9200000, Berlin: 12244000, London: 12965000, ArrowGlacier: 13773000]
> 2022-04-04 11:53:53.241+03:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
> 2022-04-04 11:53:53.838+03:00 | main | INFO  | Runner | Starting external services ...

**Comment by macfarla** [comment]
We don't have a lot of users running on Windows so we have some questions. 
Are you running Besu and Teku on the same machine? 
The logfile extract you attached is incomplete  - are you able to supply the complete log file?

**Comment by kirillp** [comment]
> Are you running Besu and Teku on the same machine?

Yes, but this does not matter for Besu behavior. 
It starts independently slow, With Teku runing or without.
Teku (already synced) does not provide any significant load to CPU\DISK\NET

> The logfile extract you attached is incomplete - are you able to supply the complete log file?
here it is attached
[besu.zip](https://github.com/hyperledger/besu/files/8415771/besu.zip)

**Comment by garyschulte** [comment]
Hi @kirillp , any word on whether this fixed the extremely slow startup behavior you were seeing for besu?  

FYI, there is a PR for the segfault issue you raised on discord: https://github.com/hyperledger/besu/issues/3722

**Comment by kirillp** [comment]
hi, I have not started it successfully yet
I have tried 3-4 times and all times it crashed 
Also It reduced the size of main-data from 620G to 475G

**Comment by garyschulte** [comment]
Can you post machine and OS specifics?  Version of windows, memory size,
disk, etc.

I'm haven't had any luck reproducing the segfault yet.

TIA

**Comment by kirillp** [comment]
I also can not repeat the crash with 100%, it happens quite rarely

My setup is exactly as in the 1st post:

Edition Windows 10 Pro
Version 21H2
OS build 19044.1620
Processor Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz 3.00 GHz
Installed RAM 16.0 GB (15.9 GB usable)

Java version:
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

**Comment by macfarla** [comment]
@kirillp Is this still happening for you?

**Comment by kirillp** [comment]
Fixed

**Comment by macfarla** [comment]
Yay! Thanks
