### ISSUE TITLE
request Besu to store client logfiles on disk

### ISSUE THREAD

**Issue by kirillp** [hyperledger/besu#3691]
In order to easy maintain nodes, see event history and investigate issues
It would be nice if Besu can store logfiles (with exceptions if any) in a folder in parallel to console out, like Teku does.

**Comment by sharad-develop** [comment]
To create a log file in parallel all you need to do is add file appender to example log4j config provided at : https://besu.hyperledger.org/en/stable/HowTo/Monitor/Logging/
To the above add an appender:

<File name="FILEOUT" fileName="your_log_filename.log" append="false">
      <PatternLayout>
        <Pattern>%d{yyyyMMdd HH:mm:ss} %-5p [%t] %C{2} %F%L - %m%n</Pattern>
      </PatternLayout>
</File>

**Comment by macfarla** [comment]
@non-fungible-nelson - teku does this a bit nicer than besu - do we want to add this feature in besu?

**Comment by non-fungible-nelson** [comment]
How much is the work? Seems like a good dev-ex snack when we have time. @macfarla

**Comment by macfarla** [comment]
yeah prob a snack. re-opened as I closed this by mistake

**Comment by macfarla** [comment]
prefer to handle this with log4j config ie outside of besu
