### ISSUE TITLE
Nonce must be 64-bit

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#3702]
### Description
The nonce in the [Ethereum yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf) is defined as a 64 bit value (see page 5 bottom). In the current implementation we use `long` for the nonce. The maximum positive value of `long` is `2^63 − 1` which means it is less than the specified `2^64`. We need to use `BigInteger` instead of `long` to fix this.

This issue was discovered by the latest version of the reference tests. The valid nonce in this test causes an overflow in our current implementation: https://github.com/ethereum/tests/blob/develop/src/TransactionTestsFiller/ttNonce/TransactionWithHighNonce64Minus2Filler.json

**Comment by shemnon** [comment]
BigInteger will slow work down.  I propose instead we use unsigned math for the nonce field, several JVM methods exist for these operations.
