### ISSUE TITLE
When syncing on FAST mode gas is not 0

### ISSUE THREAD

**Issue by daragao** [hyperledger/besu#3717]
### Description
I am running 4 nodes in FULL sync mode (1 bootnode + 3 validators), using IBFT 2.0. I have setup the gas to be 0 (as described in the documentation)
When I connect a node (non-validator) in FAST sync mode, and query the gas price using `eth_gasPrice` from that node, I get the value `0x3e8`, if I query the validators or bootnode I get `0x0`.

### Steps to Reproduce (Bug)
1. Run 3 nodes validator nodes on FULL sync mode, with IBFT 2.0
2. Run 1 bootnode
3. Run 1 non validator node in FAST sync mode, and connect to bootnode
4. Query `eth_gasPrice` from validator node
5. Query `eth_gasPrice` from non validator node

**Expected behavior:**
Expected query to validator node, or non validator node to return `0x0`, that is not the case.

**Actual behavior:**
When I query the non validator node I get value `0x3e8`, if I query the validators or bootnode I get `0x0`.

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: 22.1.3
* Java version: 11
* OS Name & Version: ubuntu 20.04.2
* Kernel Version: 5.13.0-1021-aws x86_64
* Cloud VM, type, size: t3-large

**Comment by siladu** [comment]
Hi @daragao 

> _I have setup the gas to be 0 (as described in the documentation)_

Have you also set `--min-gas-price=0` on the new non-validator node?

This needs to be set on _every_ node in a free gas network, see https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#min-gas-price
> In a free gas network, ensure the minimum gas price is set to zero for every node.

**Comment by siladu** [comment]
> _When I connect a node (non-validator) in FAST sync mode_

If you connect a non-validator node in FULL sync mode, do you get `0x0` or `0x3e8`?

**Comment by siladu** [comment]
If you're still having trouble, it would be useful if you could post the full set of CLI options and config.toml you are running the node with.
Also, the genesis file you're using would be helpful so we can attempt to recreate your issue.

Even better, if you can point us to a repo containing your setup :)

**Comment by daragao** [comment]
I misunderstood the effect of the `--min-gas-price` flag. I assumed that the flag would affect the gas price for every node in the network. It does not, it sets the minimum gas price for transactions received by that node.

**Comment by siladu** [comment]
Thanks for responding @daragao and glad to hear you're sorted now :)
