### ISSUE TITLE
Re-pivoting a fast sync across TTD fails

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#3724]
### Description
- This issue was discovered on the lighthouse/besu pair testing mainnet-shadowfork-1
    - Started a fastsync before ttd first pivot was at 14563240 (pre-merge)
    - During the fast sync, Besu re-pivoted to a new block three times (14563804, 14565117, 14567386) each being past TTD.  It incorrectly failed to apply postmerge rules to 14564208, the first block after TTD.
    - World state however was unaffected, and the world state is now ahead of the blockchain import. Any backwards syncs trigger from engine_forkChoiceUpdated would proceed back to the TTD, and then immediately re-try to import 14564208. Now the correct import rules would be applied, the block would be structurally valid, however we don't have the worldstate the block requires, and so the block cannot be executed.

Import rules being applied during fast sync need to be merge aware just like everywhere else. Should probably revisit full sync and snap-sync code as well to make sure the validation logic is re-used across all of them.

**Comment by mkalinin** [comment]
Why a pre-pivot block (the most recent pivot is far beyond the 14564208 block) would need to be executed during fast sync?

**Comment by jflo** [comment]
It wouldn't, the problem is 14564208 (ttd+1) was a post-pivot block at first, prior to the later re-pivots.
