### ISSUE TITLE
Backwards Sync should fail when syncing bellow an existing finalized block

### ISSUE THREAD

**Issue by gezero** [hyperledger/besu#3730]
### Description
As a consensus layer, I want Besu to fail when syncing a chain that does not reach the finalized block I announced so that potential problems can be caught early. 

### Acceptance Criteria
* Backwards Sync syncs correctly when chain is descending from the finalized block
* Backwards Sync throws an exception when the chain is not descending from the current finalized block.

**Actual behaviour:** 

Currently, BWS syncs even when under the finalized block and stops only when reaching a node that is already known.

**Comment by non-fungible-nelson** [comment]
@fab-10 - is this fixed with BWS fixes in 22.10 series?

**Comment by fab-10** [comment]
this is no more relevant, since the requirement has changed and an EL client must just follow what the CL says regardless of the finalized block.
