### ISSUE TITLE
Besu fails to start when storage-mode doesn't match existing database

### ISSUE THREAD

**Issue by ajsutton** [hyperledger/besu#3743]
### Description
If I sync besu using FOREST storage format, then specify `--data-storage-format=BONSAI` without deleting the database, besu fails to start with a very cryptic message:

```
{"timestamp":"2022-04-20T08:50:34,880","level":"INFO","thread":"main","class":"ProtocolScheduleBuilder","message":"Protocol schedule created with milestones: [Frontier: 0, Homestead: 1150000, DaoRecoveryInit: 19200
00, DaoRecoveryTransition: 1920001, Homestead: 1920010, TangerineWhistle: 2463000, SpuriousDragon: 2675000, Byzantium: 4370000, Petersburg: 7280000, Istanbul: 9069000, MuirGlacier: 9200000, Berlin: 12244000, London
: 12965000, ArrowGlacier: 13773000]","throwable":""}
Cannot read field "nativeHandle_" because "<parameter1>" is null

To display full help:
besu [COMMAND] --help
```

Besu should at least provide a meaningful error message that the existing database doesn't match.  Ideally it would continue using the existing database (possibly logging a warning). When a new database is created it would use the specified format.

**Comment by sharad-develop** [comment]
Unhandled nullpointer exception in RocksDB implementation causes Besu to crash  when trying to create world state block hash BonsaiPersistedWorldState.
The reason is some of the rock db columnhandles are not created. We can add warning messages in SegmentedKeyValueStorageAdapter or BonsaiWorldStateKeyValueStorage.
Let me know, I can take this up.

**Comment by non-fungible-nelson** [comment]
@sharad-develop - this could be a great issue to take up!

**Comment by meldsun0** [comment]
@ajsutton is this still active? If so I can take it.

**Comment by non-fungible-nelson** [comment]
This is addressed by https://github.com/hyperledger/besu/pull/6513. Closing. 

@meldsun0 if you are looking for issues to pick up, check out the label "Good First Issues" or "Snack" for some good ones that we have been looking for help on!
