### ISSUE TITLE
Improve logging of snap sync progress

### ISSUE THREAD

**Issue by ajsutton** [hyperledger/besu#3744]
### Description
Currently snap sync just logs a lot of:
```
SnapWorldDownloadState | Retrieved 804128239 world state nodes
```

which is overly noisy in the logs and doesn't tell me anything useful.  One of the advantages of snap sync over fast sync is that you should be able to provide a reasonable estimate of the percentage of world state download you've completed.  Ideally we'd log a message every 5-10 seconds or so that shows the current percentage complete (and possibly how many state nodes were downloaded in that time but it's not particularly interesting for the user).

**Comment by matkt** [comment]
Thank you. Yes it is something planned but not yet implemented

**Comment by matkt** [comment]
Started to work on better logs
