### ISSUE TITLE
Besu can not finish sync with bonsai and fast-sync

### ISSUE THREAD

**Issue by kirillp** [hyperledger/besu#3762]
I'm using the latest Besu  (master) on WIndows with OpenJDK 17.0.2
> Starting Besu version: besu/v22.4.0-RC2-dev-c0dafd67/windows-x86_64/oracle_openjdk-java-17

Command line is the following
> %JAVA_HOME%/bin/java -cp lib/* org.hyperledger.besu.Besu --data-path D:/main-data --data-storage-format="BONSAI" --rpc-http-enabled

The problem is that Besu can not finish sync for many many days
After start it may print once that 
> FastSyncDownloader | Re-pivoting to newer block.

And after that it will print 
> Found common ancestor with peer Peer A,B,C ... PeerReputation 99, validated? true, disconnected? false at block N

and N never changes.
Besu can print many many of such messages (30k times, 50k times) and the sync process does not advance unless I restart Besu

example log files
[besu.26-apr.log.zip](https://github.com/hyperledger/besu/files/8561968/besu.26-apr.log.zip)
[besu.25-apr.log.zip](https://github.com/hyperledger/besu/files/8561969/besu.25-apr.log.zip)

**Comment by jakrypto** [comment]
I have the same issue with Linux on v22.4.0-RC1 but since v22.1.3 bonsai active.

`executio           | 2022-04-27 00:56:14.109+00:00 | EthScheduler-Services-21 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 278100000 world state nodes. At least 30849 nodes remaining.
execution        | 2022-04-27 00:56:14.165+00:00 | nioEventLoopGroup-3-6 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x3XXXXXXX... at block 14661221
....
`

**Comment by kirillp** [comment]
It finally finished for me, so we can close it (minor performance)

> 2022-04-27 06:18:18.245+03:00 | EthScheduler-Services-10 (requestCompleteTask) | INFO  | FastWorldDownloadState | Finished downloading world state from peers
> 2022-04-27 06:18:21.416+03:00 | EthScheduler-Services-0 (importBlock) | INFO  | PipelineChainDownloader | PipelineChain download complete
> 2022-04-27 06:18:21.526+03:00 | EthScheduler-Services-0 (importBlock) | INFO  | DefaultSynchronizer | Fast sync completed successfully with pivot block 14661652
> 2022-04-27 06:18:21.541+03:00 | EthScheduler-Services-0 (importBlock) | INFO  | FullSyncDownloader | Starting full sync.
>

**Comment by florolf1** [comment]
I have exactly the same problem.  The message 
`SyncTargetManager | Found common ancestor with peer Peer 0x6247f423086bbbdc30... at block 6822809`
has been coming up for a good 20 hours now.
How did you fix the problem or did you just wait longer?

**Comment by jakrypto** [comment]
I haven't found a solution and needed to switch the client.
