### ISSUE TITLE
Metric for number of open RPC connections

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3781]
### Description
As a Besu system admin, I want to monitor current number of RPC connections so that I know when it's reaching capacity. 

### Acceptance Criteria
* Metric for number of open HTTP RPC connections
* Also for WebSocket RPC connections

**Comment by sharad-develop** [comment]
@macfarla I can take this up. 
But what is the intention here ? JsonHttpService is already logging when a connection is closed and opened.
JsonRpcHttpService | Opened connection from 127.0.0.1:59854. Total of active connections: 3/80
JsonRpcHttpService | Connection closed from 127.0.0.1:59854. Total of active connections: 2/80

**Comment by macfarla** [comment]
It is being logged but this ticket is about creating a metric to track it so it can be viewed on the dashboard

**Comment by sharad-develop** [comment]
@macfarla please assign this to me

**Comment by macfarla** [comment]
Awesome! Assigned you @sharad-develop. Some helpful resources here https://wiki.hyperledger.org/display/BESU/How+to+Contribute And if you have questions, find us in discord https://discord.gg/hyperledger

**Comment by sharad-develop** [comment]
@macfarla PR is ready for view. 
I am not sure why it complains on DCO, I seemed to have followed the specification
