### ISSUE TITLE
Improve DNS use from Ethstats

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#3792]
Besu needs DNS/IP:Port whereas others allow for just DNS and let the reverse proxy route them to the correct port. My reverse proxy forwards the traffic to the new ethstats server, but Besu doesn't like that since it tries to send traffic to the port 3000 of the specified DNS server (doesn't touch the reverse proxy then). 

So I can switch to IP:Port of the new server, but I'd say this is a QoL thing that should be fixed. 

### Acceptance Criteria
* Besu continues reporting to an Ethstats server that has changed it's ip/port under it's DNS entry.

### Steps to Reproduce (Bug)
1. Change the IP of a reverse proxy between Besu and Ethstats

**Expected behavior:** Reporting continues

**Actual behavior:** Reporting stops, error message in logs saying:

` Failed to reach the ethstats server finishConnect(..) failed: Connection refused: ethstats.mainnetshadowfork3.ethdevops.io/164.92.169.47:3000`

**Comment by usmansaleem** [comment]
networkaddress.cache.ttl

**Comment by usmansaleem** [comment]
@jflo hey Justin, can you ping me either on Discord or slack, I would like to chat about this ticket. One possible solution is to add system property networkaddress.cache.ttl=60 in Besu startup script. The other is to re-verify if the IP address of reverse proxy host is changing more often or the IP address of ethstats is changing more often?

**Comment by usmansaleem** [comment]
The other option is to modify the ethstats connecting code and set https://vertx.io/docs/apidocs/io/vertx/core/dns/AddressResolverOptions.html#setCacheMaxTimeToLive-int-.

**Comment by usmansaleem** [comment]
@non-fungible-nelson hey Matt, can you ping me regarding above issue, I want to get some further clarification from the user regarding the above issue and whether it is already sorted out or not. Cheers, Uzi.

**Comment by non-fungible-nelson** [comment]
@jflo might know this - based on the mainnet shadow fork logs, this is likely also with the EF. @usmansaleem did you connect with @parithosh on the improvements?

**Comment by parithosh** [comment]
@siladu gave me an image to test out and that showed no ethstats issues, I'm honestly not sure which branch or fix he gave me to try, but perhaps he can chime in

**Comment by usmansaleem** [comment]
@parithosh That was probably cut againt the main branch that contained the ethstats related enhancements. Next Besu release should also contain these fixes. I am going to close this ticket, in case you face any issues, feel free to re-open this issue or create a new one. Thanks, /uzi
