### ISSUE TITLE
Initial sync stuck at block 14750504

### ISSUE THREAD

**Issue by ronaldjmaas** [hyperledger/besu#3833]
### Description
Besu fails to sync the Ethereum mainnet chain.

### Acceptance Criteria
Besu successfully syncs with the Ethereum mainnet chain.

### Steps to Reproduce (Bug)
1. Install OpenJDK 17.3
2. Install Hyperledger Besu
3. Create empty data directory: /mnt/ethereum/besu@/main/ 
4. Create Systemd service file
5. Start Besu using Systemd

**Expected behavior:** [What you expect to happen]
Besu successfully syncs with the Ethereum mainnet chain.

**Actual behavior:** [What actually happens]
Besu get stuck at block 14750504 and does not progress. It keeps throwing exceptions like:
java.lang.RuntimeException: World State Root does not match expected value
org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #14750504
See attached stack trace for more detail

**Frequency:** [What percentage of the time does it occur?]
I tried stopping and starting Besu several times. But Besu did progress past block 14750504

### Versions (Add all that apply)
* Software version: [`besu --version`]
besu/v22.4.0/linux-aarch_64/openjdk-java-17
* Java version: [`java -version`]
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Debian-1deb11u1, mixed mode, sharing)
* OS Name & Version: [`cat /etc/*release`]
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
* Kernel Version: [`uname -a`]
Linux xgene1 5.10.0-13-arm64 #1 SMP Debian 5.10.106-1 (2022-03-17) aarch64 GNU/Linux
* Virtual Machine software & version: [`vmware -v`]
n/a
* Docker Version: [`docker version`]
n/a
* Cloud VM, type, size: [Amazon Web Services I3-large]
home based 64-bit ARM server

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
n/a
* Repo with minimal set of deployable/reproducible contract code - please provide a link
n/a
* Please include specifics on how you are deploying/calling the contract 
n/a
* Have you reproduced the issue on other eth clients
Geth synced successfully

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options (see attached)
* System info - memory, CPU
8 core X-Gene1 ARM64 CPU, 64 GB ECC memory, 2 TB Samsung SSD driver
* Systemd service file and stack trace attached
* ulimit open files increased to 65536
* Debian has latest kernel + all lates updates
[besu.service.txt](https://github.com/hyperledger/besu/files/8683979/besu.service.txt)
[stacktrace.txt](https://github.com/hyperledger/besu/files/8683981/stacktrace.txt)

**Comment by ronaldjmaas** [comment]
Thanks in advance

**Comment by ronaldjmaas** [comment]
Closed by accident

**Comment by ronaldjmaas** [comment]
22.4.0

**Comment by matkt** [comment]
Could you say me if you are using fastsync or snapsync ?

**Comment by ronaldjmaas** [comment]
Fast sync

**Comment by Nabsku** [comment]
Had the same issue, just with block 14802763. Using BONSAI and fast sync.

**Comment by ronaldjmaas** [comment]
Besu 22.4.2 successfully synced starting from scratch using fast sync
