### ISSUE TITLE
[Spike] Investigate SnapSync

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#3846]
### Questions to investigate:

- How does snapsync work?
- How many peers are we using?
- How “busy” are we doing that? Could we use more peers?
- While we are downloading, are we still looking for more/better peers to do that?
- Does pivot block occur in snapsync?

Timebox: 3 days 

### Desired outcome:

- Set up 30min-45min session with the team share out your findings on how snapsync work

**Comment by macfarla** [comment]
Pivot block selection is exactly the same as fast sync. only the tasks are different.

**Comment by macfarla** [comment]
SnapWorldStateDownloadProcess sets up the pipelines

**Comment by macfarla** [comment]
https://docs.nethermind.io/nethermind/ethereum-client/sync-modes#snap-sync-vs-other-sync-modes

**Comment by macfarla** [comment]
Snap protocol https://github.com/ethereum/devp2p/blob/master/caps/snap.md

**Comment by macfarla** [comment]
SnapProtocolManager - Adds "snap" to list of capabilities
PivotSelectorFromPeers - same as used by Fast Sync. No difference.
DynamicPivotBlockManager - only used by snap sync - as part of the "heal" process - filling in the gaps
