### ISSUE TITLE
Nimbus complains of eth_subscribe missing method when using websockets

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#3854]
Nimbus encounters this error when trying to use Besu as an EL client.

```WRN 2022-05-17 20:30:30.819-04:00 Eth1 chain monitoring failure, restarting  topics="eth1" err="subscribeForBlockHeaders(p.web3, blockHeaderHandler, errorHandler) failed 3 times. Last error: {\"code\":-32604,\"message\":\"Method not enabled\"}"```

**Comment by SeaMonkey82** [comment]
Changing nimbus to use http instead of ws alleviates this issue.  It is re-enabled in the current `kiln-dev-auth` branch.
