### ISSUE TITLE
Add subcommand to print configuration and status info

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#3864]
### Description
As an Besu user, I want to have a command to print my current setup info so that I can easily add these info in my issue report or communicate the to the devs for throubleshooting. 

### Acceptance Criteria
User can just this something like that: `besu status print` and get something like that:
```
* Software version: 22.4.0
* Command line: besu --network xyz --enable-rpc....
* Java version: openjdk-11
* OS Name & Version: Ubuntu 22.04
* Kernel Version: 5.10.4
* Virtual Machine software & version: Docker
* Head block: 23445 (0xea54093..)
* besu memory
* system memory
* etc...
```

**Comment by AbhinavMir** [comment]
Is this still open for PR consideration? Seems to be an easy fix, can do it this week.

**Comment by fab-10** [comment]
> Is this still open for PR consideration? Seems to be an easy fix, can do it this week.

Please sync with @daniellehrner that is working on https://github.com/hyperledger/besu/pull/4451

**Comment by non-fungible-nelson** [comment]
closed for config printer
