### ISSUE TITLE
JSON-RPC: Besu does not follow the standard API for eth_getTransactionByHash

### ISSUE THREAD

**Issue by Neurone** [hyperledger/besu#3868]
### Description
As a developer, I want to call `eth_getTransactionByHash` so that I can get all transaction attributes defined by the standard API.

Currently, Besu does not return correctly the `blockNumber`, `blockHash` and `transactionIndex` fields when responding for pending transactions.

This causes some clients to fail during normal operations (i.e. [Deploy SmartContract to local Hyperledger-Besu network using Brownie](https://ethereum.stackexchange.com/questions/127948/deploy-smartcontract-to-local-hyperledger-besu-network-using-brownie)).

### Acceptance Criteria
* Send a request for a pending tx
* Result JSON contains all mandatory fields specified by the API

### Steps to Reproduce (Bug)
1. Send a request for a pending tx:
`curl -X POST --data '{"jsonrpc": "2.0", "method": "eth_getTransactionByHash", "params": ["0xfe6f9abeacbe186f6ee5edd811228e0710631c3569ee8bd45ca67c46146c762c"], "id": 6}' localhost:8545`
2. Result does not contain `blockNumber`, `blockHash` or `transactionIndex` field: 
```json
{
  "jsonrpc" : "2.0",
  "id" : 6,
  "result" : {
    "from" : "0x627306090abab3a6e1400e9345bc60c78a8bef57",
    "gas" : "0x5208",
    "gasPrice" : "0x2540be400",
    "hash" : "0xfe6f9abeacbe186f6ee5edd811228e0710631c3569ee8bd45ca67c46146c762c",
    "input" : "0x",
    "nonce" : "0x32",
    "to" : "0xf12b5dd4ead5f743c6baa640b0216200e89b60da",
    "value" : "0x2",
    "v" : "0xa96",
    "r" : "0x325fd22b695b5f8e54cab34ae558373a9a15229a6cf8614d60fa7bcdc1493abf",
    "s" : "0xf1c739e11f356c7a59e8b37e36f91c423ce0298bfd089780415c60ed2652f3c",
    "chainId" : "0x539",
    "publicKey" : "0xaf80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d7434c380f0aa4c500e220aa1a9d068514b1ff4d5019e624e7ba1efe82b340a59",
    "raw" : "0xf866328502540be40082520894f12b5dd4ead5f743c6baa640b0216200e89b60da0280820a96a0325fd22b695b5f8e54cab34ae558373a9a15229a6cf8614d60fa7bcdc1493abfa00f1c739e11f356c7a59e8b37e36f91c423ce0298bfd089780415c60ed2652f3c"
  }
}
```

**Expected behavior:**
Besu should include the following fields in the response:

> blockHash: DATA, 32 Bytes - hash of the block where this transaction was in. null when its pending.
> blockNumber: QUANTITY - block number where this transaction was in. null when its pending.
> transactionIndex: QUANTITY - integer of the transactions index position in the block. null when its pending.

As stated in the [official schema](https://github.com/ethereum/execution-apis/blob/4ce0ff08fa298fe963a066bc54615dbe4b4faf37/src/schemas/transaction.json#L275), they are mandatory fields, so they should be set to `null` if they are without value.

Returned JSON should look like this:

```json
{
  "jsonrpc" : "2.0",
  "id" : 6,
  "result" : {
    "blockHash": null,
    "blockNumber": null,
    "from" : "0x627306090abab3a6e1400e9345bc60c78a8bef57",
    "gas" : "0x5208",
    "gasPrice" : "0x2540be400",
    "hash" : "0xfe6f9abeacbe186f6ee5edd811228e0710631c3569ee8bd45ca67c46146c762c",
    "input" : "0x",
    "nonce" : "0x32",
    "to" : "0xf12b5dd4ead5f743c6baa640b0216200e89b60da",
    "transactionIndex": null,
    "value" : "0x2",
    "v" : "0xa96",
    "r" : "0x325fd22b695b5f8e54cab34ae558373a9a15229a6cf8614d60fa7bcdc1493abf",
    "s" : "0xf1c739e11f356c7a59e8b37e36f91c423ce0298bfd089780415c60ed2652f3c",
    "chainId" : "0x539",
    "publicKey" : "0xaf80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d7434c380f0aa4c500e220aa1a9d068514b1ff4d5019e624e7ba1efe82b340a59",
    "raw" : "0xf866328502540be40082520894f12b5dd4ead5f743c6baa640b0216200e89b60da0280820a96a0325fd22b695b5f8e54cab34ae558373a9a15229a6cf8614d60fa7bcdc1493abfa00f1c739e11f356c7a59e8b37e36f91c423ce0298bfd089780415c60ed2652f3c"
  }
}
```

**Actual behavior:**
Result does not contain `blockNumber`, `blockHash` or `transactionIndex` field

**Frequency:**
100%

### Versions
* Software version: `besu/v22.4.1-dev-3835cb72/linux-x86_64/openjdk-java-17`

**Comment by sharad-develop** [comment]
This will affect - txpool_besuPendingTransactions too, as  eth_getTransactionByHash and txpool_besuPendingTransactions share the same result type - TransactionPendingResult. Do we want to apply the changes to txpool_besuPendingTransactions too or create a new result type ?

**Comment by sharad-develop** [comment]
@Neurone I can this up, if you assign this to me

**Comment by Neurone** [comment]
> @Neurone I can take this up, if you assign this to me

@sharad-develop I'm not part of the Besu team so I cannot assign tasks to others :) but I think you can start working on this with a draft PR and reference this issue in the description, so others can see that there's a WIP.

**Comment by Sky0711** [comment]
This issue has been solved? HyperLeger-Besu will now work with a brownie?

**Comment by macfarla** [comment]
> This issue has been solved? HyperLeger-Besu will now work with a brownie? (When will be able to get and test the new changes?)

@Sky0711 this is in the latest release https://github.com/hyperledger/besu/releases/tag/22.4.2 - let us know how you go!
