### ISSUE TITLE
`eth_estimateGas` doesn't support fields `nonce`, `type`, `accessList`

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#3873]
```
2022-05-19 13:30:32.925-07:00 | vert.x-worker-thread-17 | DEBUG | JsonCallParameter | unknown property - accessList with value - [] and type - class java.util.ArrayList caught during serialization
2022-05-19 13:30:32.932-07:00 | vert.x-worker-thread-17 | DEBUG | JsonCallParameter | unknown property - nonce with value - 0x0 and type - class java.lang.String caught during serialization
2022-05-19 13:30:32.934-07:00 | vert.x-worker-thread-17 | DEBUG | JsonCallParameter | unknown property - type with value - 0x02 and type - class java.lang.String caught during serialization
```

I got a little ways into adding the support but realized it would take longer than I have time for given my other tasks. I'm seeing this when using `forge` to deploy contracts.

**Comment by sharad-develop** [comment]
@RatanRSur  why do you want to add nonce ?
"The spec https://eth.wiki/json-rpc/API doesn't specify anything about nonce. however, other platforms like go-ethereum/GoQuorum ignore if that argument is sent." See - https://github.com/hyperledger/besu/issues/2125

**Comment by RatanRSur** [comment]
Purely for `forge` compatibility. If `eth_estimateGas` could just ignore fields like `nonce`, that would be great

**Comment by non-fungible-nelson** [comment]
@macfarla - did we clean this up as part of our RPC accuracy work?

**Comment by macfarla** [comment]
fixed in https://github.com/hyperledger/besu/pull/2690

**Comment by n3xt-kyle** [comment]
For anyone that finds this thread we found a workaround/solution... We had a similar issue that only occurred during load testing, even relatively love number of calls,

We're using `viem` and there are some params you can pass to the client to disable batching at the transport layer, or utilize `multicall` at the eth client level:

at the http client -- https://viem.sh/docs/clients/transports/http#http-transport
```
const httpClientOptions = (httpUrl: string) => {
   return {
     chain: mynetwork,
-    transport: http(httpUrl, { retryCount: 10, retryDelay: 1_000 }),
+    transport: http(httpUrl, { retryCount: 10, retryDelay: 1_000, batch: false }),
```

or with `multicall` -- https://viem.sh/docs/clients/public#optimization
```
@@ -2936,6 +2936,7 @@ const httpClientOptions = (httpUrl: string) => {
   return {
     chain: mynetwork,
     transport: http(httpUrl, { retryCount: 10, retryDelay: 1_000 }),
+    batch: { multicall: true },
 ```
