### ISSUE TITLE
warn user if specified sync-mode does not match expected values

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3884]
For example, this command starts a fast sync 
`besu --sync-mode="bogus"`
as does this
`besu --sync-mode="-XSNAP"`

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue. Would you guide me a bit more on what needs to be done?

**Comment by macfarla** [comment]
The help text in BesuCommand tells exactly what the options are.
```
      --sync-mode=<MODE>     Synchronization mode, possible values are FULL,
                               FAST, X_SNAP (default: FAST if a --network is
                               supplied and privacy isn't enabled. FULL
                               otherwise.)
```
If something else is specified, I would like a warning message similar to what you get if you specify a network name that's not in the list eg:
```
besu --network=bogus
Invalid value for option '--network': expected one of [MAINNET, RINKEBY, ROPSTEN, SEPOLIA, GOERLI, KILN, DEV, CLASSIC, KOTTI, MORDOR, ECIP1049_DEV, ASTOR] (case-insensitive) but was 'bogus'
```
So something like:
"Invalid value for option '--sync-mode': expected one of ... but was '...'"

**Comment by gfukushima** [comment]
Hi @macfarla I've added a PR for this issue. (https://github.com/hyperledger/besu/pull/4017) 
This is my first contribution to the project. 
Please let me know if I've missed anything.
