### ISSUE TITLE
Investigate why peer list is not filling 

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#3897]
Root cause analysis of why peer list is not filling and propose a potential solution on resolving it

### Desired Outocme

- Report detailing what, when, why list is not filling
- Create future tasks/issues to resolve the issues identified by this work

**Comment by mark-terry** [comment]
**Investigation outcomes:**
- Produced some baseline measurements for future use
- Identified some behaviours / issues that may be improved by #2689
- Created ticket #4054 that may improve new node network participation
