### ISSUE TITLE
Improve Error Reporting when tracing under Bonsai

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#3899]
### Description
As an user who is tracing a block, I want a better error message when I am exceeding the layer limit of a bonsai storage node. Current behavior just returns null.

### Acceptance Criteria
* Sensible error message returned when trying to trace.

### Steps to Reproduce (Bug)
1. run any standardBlockTrace debug method for a block older than the layer limit (512?) and observe the cryptic results.

**Comment by macfarla** [comment]
I believe this has been improved
