### ISSUE TITLE
With sync-mode=X_SNAP actual balance isn't showing up.

### ISSUE THREAD

**Issue by jcodic** [hyperledger/besu#3902]
### Description
Get balance returns NULL when mainnet synched using --sync-mode="X_SNAP".

### Steps to Reproduce (Bug)
Ethereum mainnet synched with --sync-mode="X_SNAP".

Command executed:
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xbe0eb53f46cd790cd13851d5eff43d12404d33e8", "latest"],"id":53}' http://127.0.0.1:8545

Result:
{
  "jsonrpc" : "2.0",
  "id" : 53,
  "result" : null
}

When mainnet was synched with --sync-mode=FAST everything worked well with result showed actual balance.

### Versions (Add all that apply)
Latest version 22.4.1 on Centos 8 JVM 16

**Comment by matkt** [comment]
do you have the same error with another address?

**Comment by matkt** [comment]
I can't reproduce this behavior on my node

**Comment by matkt** [comment]
do you have some logs ?

**Comment by matkt** [comment]
okay we can reproduce the issue. I will investigate

**Comment by matkt** [comment]
Can you provide me with the logs of your node while you are making the call ?

**Comment by jcodic** [comment]
Resynced today, and everything works! Closing issue.
