### ISSUE TITLE
Performance profiling of simple Besu eth_call

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#3926]
### Desired Outcome
Do performance profiling across different types of eth_call. Consider for:
- simple eth_call for ERC20 balanceOf

**Tasks**
- [ ] Evaluate tools
- [ ] Enable performance capture. Can use java flight recording using https://besu.hyperledger.org/en/latest/HowTo/Troubleshoot/Java-Flight-Recording/. Might need to increase the stack depth.
- [ ] Analyse performance result. Try and determine where the bottlenecks are

### Notes 
Possible profiling tools
- Java Flight Recorder
- Yourkit
- [Async Profiler](https://github.com/jvm-profiling-tools/async-profiler)

**Comment by siladu** [comment]
This was completed in another issue.
