### ISSUE TITLE
Stop the block synchronization after the first finalized block 

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#3943]
### Description
The Merge spec says that an execution should behave like this after the switch to PoS:

> Beginning with receiving the finalized block next to the FIRST_FINALIZED_BLOCK, the networking stack MUST remove the handlers corresponding to the following messages:
> 
> NewBlockHashes (0x01)
> NewBlock (0x07)
> Peers that keep sending these messages after the handlers have been removed SHOULD be disconnected.
> 

currently Besu stop any block synchronization task when the TTD is reached, so it is not following the spec, and doing so is not able to easily recognize if a peer is still on PoW after TTD has been reached, and disconnect those peers.

### Acceptance Criteria

Keep processing and sending 
* NewBlockHashes (0x01)
* NewBlock (0x07)
messages until the first finalized block is received from the CL

### Versions (Add all that apply)
* Software version: besu-22.4.3-SNAPSHOT

**Comment by jflo** [comment]
PR 3944 has been reverted, re-opening issue.
