### ISSUE TITLE
[IBFT - 2.0] Deploying a Besu testnet, blocks are not produced

### ISSUE THREAD

**Issue by dottscarlato** [hyperledger/besu#3952]
Hi there,

I am trying to run a QBFT private network, following this [guide](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/#create-a-private-network-using-the-ibft-proof-of-authority-consensus-protocol).

Given that the `bin/besu` directory (as indicated [here](https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Installation-Options/Install-Binaries/#linux-unix)) is not present in recent versions, I am using the `21.10.4` version.

I performed these steps:

```
# we should use an older version to find where the binary is:

mkidr IBFT2.0/

cd IBFT2.0/

wget https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/21.10.4/besu-21.10.4.tar.gz
tar -xvzf besu-21.10.4.tar.gz besu-21.10.4/

cd besu-21.10.4/
bin/besu --help

mkdir IBFT-Network/
mkdir IBFT-Network/Node-1/
mkdir IBFT-Network/Node-1/data
mkdir IBFT-Network/Node-2/
mkdir IBFT-Network/Node-2/data
mkdir IBFT-Network/Node-3/
mkdir IBFT-Network/Node-3/data
mkdir IBFT-Network/Node-4/
mkdir IBFT-Network/Node-4/data

cd IBFT-Network/
touch IBFTConfigFile.json

# https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/#2-create-a-configuration-file

../bin/besu operator generate-blockchain-config --config-file=IBFTConfigFile.json --to=networkFiles --private-key-file-name=key
cp networkFiles/genesis.json .


mv networkFiles/keys/0x0*/key* Node-1/data/
mv networkFiles/keys/0x6a*/key* Node-2/data/
mv networkFiles/keys/0xd*/key* Node-3/data/
mv networkFiles/keys/0xf*/key* Node-4/data/

# cd /home/michelescarlato/quorum-test-network/network
#./stop.sh
cd
cd IBFT2.0/besu-21.10.4/IBFT-Network/Node-1

../../bin/besu --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all"

# in another shell

cd
cd IBFT2.0/besu-21.10.4/IBFT-Network/Node-2

../../bin/besu --data-path=data --genesis-file=../genesis.json --bootnodes=enode://f508e5633773fdd193d1acf1dde5418beebe830bf8ea2b8760935e0ad2b7cde193fadafb61ed863c67d7857c492dc667cd3eb3d3cfa9611acdcae4b1098f8f1d@127.0.0.1:30303 --p2p-port=30304 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8546

# in another shell

cd IBFT2.0/besu-21.10.4/IBFT-Network/Node-3

../../bin/besu --data-path=data --genesis-file=../genesis.json --bootnodes=enode://f508e5633773fdd193d1acf1dde5418beebe830bf8ea2b8760935e0ad2b7cde193fadafb61ed863c67d7857c492dc667cd3eb3d3cfa9611acdcae4b1098f8f1d@127.0.0.1:30303 --p2p-port=30305 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8547

# in another shell

cd IBFT2.0/besu-21.10.4/IBFT-Network/Node-4

../../bin/besu --data-path=data --genesis-file=../genesis.json --bootnodes=enode://f508e5633773fdd193d1acf1dde5418beebe830bf8ea2b8760935e0ad2b7cde193fadafb61ed863c67d7857c492dc667cd3eb3d3cfa9611acdcae4b1098f8f1d@127.0.0.1:30303 --p2p-port=30306 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8548
```

On node4, as occurred in #3946, I got a `GasLimitRAngeAndDeltaValidationRule` INFO message:

```
2022-06-09 18:18:16.464+02:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 3
2022-06-09 18:18:21.466+02:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 3
2022-06-09 18:18:26.198+02:00 | pool-8-thread-1 | INFO  | GasLimitRangeAndDeltaValidationRule | Invalid block header: basefee should not be present in a block without a base fee market
2022-06-09 18:18:26.200+02:00 | pool-8-thread-1 | INFO  | MessageValidator | Invalid Proposal message, block did not pass validation.
2022-06-09 18:18:26.467+02:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 3
2022-06-09 18:18:31.469+02:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 3
2022-06-09 18:18:36.471+02:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 3

```

Am I doing something wrong?

**Comment by siladu** [comment]
Hi @dottscarlato, is there a reason you are using an older version?

This looks to be related to London fork support which was only added in version 22.1.0.

We would encourage you to use the latest version of besu to avoid bugs, current latest is https://github.com/hyperledger/besu/releases/tag/22.4.2

**Comment by dottscarlato** [comment]
@siladu , thanks for your prompt response.

I had to use the version 22.10.4, because following this [guide](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/#create-a-private-network-using-the-ibft-proof-of-authority-consensus-protocol), and specifically installing besu as a requirement ([here](https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Installation-Options/Install-Binaries/#install-from-packaged-binaries)), in latest versions the command `bin/besu` has been moved somewhere else.

**Comment by siladu** [comment]
Hi @dottscarlato. That guide should work with the latest version of besu as well. 

I downloaded the binaries for both 21.10.4 and the latest stable version, https://github.com/hyperledger/besu/releases/tag/22.4.2

Both had a working `bin/besu` binary in the same location.

Are you able to try again downloading using one of these links:
https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/22.4.2/besu-22.4.2.zip
https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/22.4.2/besu-22.4.2.tar.gz

I'm wondering if perhaps you downloaded the source code instead of the binary? (source code link is under the binaries, in the assets section)

**Comment by dottscarlato** [comment]
@siladu you are completely right.

I was cloning the entire GitHub repo (and I was trying to compile it with `gradle` but unsuccessfully ).

Now downloading the binaries I could find the `bin/besu` executable.

Sorry for the misunderstanding, and thanks for your clear explanation.

**Comment by Dmdv** [comment]
Same issue with Besu besu/v23.7.1/osx-aarch_64/oracle-java-20

**Comment by siladu** [comment]
Hi @Dmdv - this issue was related to an old version of besu. If you're having issues with the latest version, please can you start a new issue or ask for some help on the Hyperledger Besu Discord please?

**Comment by akashsangwan3009** [comment]
Same issue with Besu besu/v24.7.1/linux-x86_64/oracle-java-21

Any help ?
