### ISSUE TITLE
Identify Bottlenecks for Archive Node Sync 

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#3968]
### Context
For some node operators, it's been taking almost 6 months to sync an archive node. We believe this is taking way too long and would like to investigate the root cause of this slowness so that we can improve the sync time.

### Desired outcome
- Set up an archive node with metrics, logs, performance profiling so that we can monitor and identify anomalies in syncing speed
- Identify root cause for slow syncing 
- Propose potential solutions to improving sync time

**Comment by macfarla** [comment]
bonsai archive is tasked in different tickets now
