### ISSUE TITLE
Peer reputation scoring

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#3982]
### Desired Outcome
- Propose a reputation scoring system to the team, incorporate feedback, and implement the reputation scoring system
- After implementing the scoring system, compare the snapsync completion time to the baseline metric captured in #3853. 
- Measure how much of a positive or negative improvements we have made after the change in the scoring system 
- We'd like to optimize the scoring system for post-merge where PoS kicks in not the current PoW 

### Behaviors we want to reward
- Fast response
- Completeness of data
- Delivers lots of data (high throughput)

### Behaviors we want to punish
- Peer takes very long time to deliver data or times out 
- Peer sends same data repeatedly
- Peer does not have data that we require 

### Note
- Mark this as an experimental feature

**Comment by macfarla** [comment]
we have finer grained issues that capture this now
