### ISSUE TITLE
Only berlin fork works when deploying ERC1400 on a zero gas network

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#3991]
### Description

A report from Discord:

> I'm currently looking into upgrading my free gas besu chain from 22.1.1 to the latest 22.4.2. When I start the upgraded network however, I am getting  "Gas price below configured minimum gas price" reverts when I try to send transactions to the chain. This didn't happen on 22.1.1, and I'm using the same genesis and config files where block gas limit is set to max and the min-gas-price=0.

> I'm currently using the "arrowglacierblock" in my network, as I need it to be able to deploy an ERC1820 contract as a foundation for deploying ERC1400 contracts.

* can you try adding this line to the genesis file "baseFeePerGas": "0x0"?

> I've tried using "baseFeePerGas" with the arrow glacier fork but that still didn't work. Older forks like byzantium and constantinople did not allow me to deploy ERC1400 contracts
> Finally, I tried using the berlin fork which is one update before london and that seems to have solved both issues. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
* System info - memory, CPU

**Comment by siladu** [comment]
It's possible that the contracts being deployed require Berlin and later to get the necessary opcodes, but there's a bug in the london (or later) fork.

**Comment by siladu** [comment]
This could be relevant https://github.com/ConsenSys/UniversalToken/issues/130

**Comment by jrusselg** [comment]
Hi all, this is the issue that I faced. Dropping the genesis and config files I'm using here.

Config
data-path="IBFT_nodes/node-e/data"
genesis-file="IBFT_nodes/genesis.json"
rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT"]
rpc-ws-enabled=true
rpc-ws-api=["ETH","NET","IBFT"]
host-allowlist=["*"]
rpc-http-cors-origins=["*"]
sync-mode="FULL"
#fast-sync-min-peers=1

#miner-enabled=false
#miner-coinbase="0x0000000000000000000000000000000000000000"

bootnodes=["enode://9d6f59b02f3a937b6da5a562442db915393679b70d3f36c0606c9e970d0df09009c397e6091763ca9380bc66a9b02e3035537fc4a192f16356abb4056bfc9816@127.0.0.1:30305"]


# Change ports for each node, can go in ascending order
p2p-port=30309
rpc-http-port=8549
rpc-ws-port=8750
engine-rpc-port=8649

min-gas-price=0


Genesis
{
  "config" : {
    "chainId" : 1337,
    "berlinblock" : 0,
    "contractSizeLimit" : 2147483647,
    "ibft2" : {
      "blockperiodseconds" : 2,
      "epochlength" : 30000,
      "requesttimeoutseconds" : 4
    }
  },
  "nonce" : "0x0",
  "timestamp" : "0x58ee40ba",
  "gasLimit" : "0x1fffffffffffff",
  "difficulty" : "0x1",
  "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase" : "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24" : {
"code" : "0x608060405234801561001057600080fd5b50600436106100a5576000357c010000000000000000000000000000000000000000000000000000000090048063a41e7d5111610078578063a41e7d51146101d4578063aabbb8ca1461020a578063b705676514610236578063f712f3e814610280576100a5565b806329965a1d146100aa5780633d584063146100e25780635df8122f1461012457806365ba36c114610152575b600080fd5b6100e0600480360360608110156100c057600080fd5b50600160a060020a038135811691602081013591604090910135166102b6565b005b610108600480360360208110156100f857600080fd5b5035600160a060020a0316610570565b60408051600160a060020a039092168252519081900360200190f35b6100e06004803603604081101561013a57600080fd5b50600160a060020a03813581169160200135166105bc565b6101c26004803603602081101561016857600080fd5b81019060208101813564010000000081111561018357600080fd5b82018360208201111561019557600080fd5b803590602001918460018302840111640100000000831117156101b757600080fd5b5090925090506106b3565b60408051918252519081900360200190f35b6100e0600480360360408110156101ea57600080fd5b508035600160a060020a03169060200135600160e060020a0319166106ee565b6101086004803603604081101561022057600080fd5b50600160a060020a038135169060200135610778565b61026c6004803603604081101561024c57600080fd5b508035600160a060020a03169060200135600160e060020a0319166107ef565b604080519115158252519081900360200190f35b61026c6004803603604081101561029657600080fd5b508035600160a060020a03169060200135600160e060020a0319166108aa565b6000600160a060020a038416156102cd57836102cf565b335b9050336102db82610570565b600160a060020a031614610339576040805160e560020a62461bcd02815260206004820152600f60248201527f4e6f7420746865206d616e616765720000000000000000000000000000000000604482015290519081900360640190fd5b6103428361092a565b15610397576040805160e560020a62461bcd02815260206004820152601a60248201527f4d757374206e6f7420626520616e204552433136352068617368000000000000604482015290519081900360640190fd5b600160a060020a038216158015906103b85750600160a060020a0382163314155b156104ff5760405160200180807f455243313832305f4143434550545f4d4147494300000000000000000000000081525060140190506040516020818303038152906040528051906020012082600160a060020a031663249cb3fa85846040518363ffffffff167c01000000000000000000000000000000000000000000000000000000000281526004018083815260200182600160a060020a0316600160a060020a031681526020019250505060206040518083038186803b15801561047e57600080fd5b505afa158015610492573d6000803e3d6000fd5b505050506040513d60208110156104a857600080fd5b5051146104ff576040805160e560020a62461bcd02815260206004820181905260248201527f446f6573206e6f7420696d706c656d656e742074686520696e74657266616365604482015290519081900360640190fd5b600160a060020a03818116600081815260208181526040808320888452909152808220805473ffffffffffffffffffffffffffffffffffffffff19169487169485179055518692917f93baa6efbd2244243bfee6ce4cfdd1d04fc4c0e9a786abd3a41313bd352db15391a450505050565b600160a060020a03818116600090815260016020526040812054909116151561059a5750806105b7565b50600160a060020a03808216600090815260016020526040902054165b919050565b336105c683610570565b600160a060020a031614610624576040805160e560020a62461bcd02815260206004820152600f60248201527f4e6f7420746865206d616e616765720000000000000000000000000000000000604482015290519081900360640190fd5b81600160a060020a031681600160a060020a0316146106435780610646565b60005b600160a060020a03838116600081815260016020526040808220805473ffffffffffffffffffffffffffffffffffffffff19169585169590951790945592519184169290917f605c2dbf762e5f7d60a546d42e7205dcb1b011ebc62a61736a57c9089d3a43509190a35050565b600082826040516020018083838082843780830192505050925050506040516020818303038152906040528051906020012090505b92915050565b6106f882826107ef565b610703576000610705565b815b600160a060020a03928316600081815260208181526040808320600160e060020a031996909616808452958252808320805473ffffffffffffffffffffffffffffffffffffffff19169590971694909417909555908152600284528181209281529190925220805460ff19166001179055565b600080600160a060020a038416156107905783610792565b335b905061079d8361092a565b156107c357826107ad82826108aa565b6107b85760006107ba565b815b925050506106e8565b600160a060020a0390811660009081526020818152604080832086845290915290205416905092915050565b6000808061081d857f01ffc9a70000000000000000000000000000000000000000000000000000000061094c565b909250905081158061082d575080155b1561083d576000925050506106e8565b61084f85600160e060020a031961094c565b909250905081158061086057508015155b15610870576000925050506106e8565b61087a858561094c565b909250905060018214801561088f5750806001145b1561089f576001925050506106e8565b506000949350505050565b600160a060020a0382166000908152600260209081526040808320600160e060020a03198516845290915281205460ff1615156108f2576108eb83836107ef565b90506106e8565b50600160a060020a03808316600081815260208181526040808320600160e060020a0319871684529091529020549091161492915050565b7bffffffffffffffffffffffffffffffffffffffffffffffffffffffff161590565b6040517f01ffc9a7000000000000000000000000000000000000000000000000000000008082526004820183905260009182919060208160248189617530fa90519096909550935050505056fea165627a7a72305820377f4a2d4301ede9949f163f319021a6e9c687c292a5e2b2c4734c126b524e6c0029"
}
  },
  "extraData" : "0xf893a00000000000000000000000000000000000000000000000000000000000000000f86994a9593ff4ad56c9b4ca95bf44a7d6b55171fbbce394bb0f961dd94654dcd8a4ae9e750d959b55adb8a7945ab017999407c91978eed7b53b923b2f0ac3757394cc1cfc338cadccf045810994630472e7821600a99456142f618331a4e96bdb4d09fc5a70e2b2d7b1d2808400000000c0"
}

**Comment by jrusselg** [comment]
Issue is resolved when using "berlinblock" instead of "arrowglacierblock" or anything earlier like byzantium or constantinople.

**Comment by siladu** [comment]
Hi @jrusselg I've been testing deploying these contracts with besu.

I used https://github.com/ConsenSys/UniversalToken as the ERC1400 implementation.

I can confirm that the solidity contract code needs to be compiled against the `istanbul` or later evm version in order to get the opcode support.

On most recent versions of besu, setting any of `istanbulBlock`, `muirGlacierBlock`, or `berlinBlock` in the genesis should work with a free gas network (you may need to match the compiled evm version of the contract with the hard fork).
 
If you want to use any later hard forks with a free gas network: `londonBlock`, `arrowGlacierBlock` or `grayGlacierBlock` (none of which are required for private networks), then you need a fix that has just been released in https://github.com/hyperledger/besu/releases/tag/22.7.0-RC1

In addition, you'll need to set to `baseFeePerGas` to zero in the genesis, like so:
```
{
  "config": {
    ...
    "arrowGlacierBlock": 0,
    ...
  },
  "baseFeePerGas": "0x0",
  "nonce": "0x0",
  ...
}
```

Closing this issue. Please reopen if you experience further problems with this.
