### ISSUE TITLE
Migrate hyperledger besu node in private network

### ISSUE THREAD

**Issue by Neoblock8** [hyperledger/besu#3998]
Hi,

Already Running local network besu in a server.More than 1Lakh of blocks and 1000's of transactions are produced.
Can i migrate the old server node into new server?

**Comment by daniellehrner** [comment]
As long as you copy the database and your configuration is the same as well, there should not be a problem.

**Comment by daniellehrner** [comment]
> Hi @daniellehrner,
> 
> Running one masternode and 3 validator node with masternode enode setup.
> 
> Can i copy masternode database and validator node database to the new server?

With masternode do you mean a bootnode?

And all the nodes are running one separate servers, don't they? You have to copy them one by one, each on a separate new server.
