### ISSUE TITLE
Implement liveness check

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#4007]
Besu offers a [liveness RPC endpoint](https://besu.hyperledger.org/en/latest/HowTo/Interact/APIs/Using-JSON-RPC-API/#liveness). But the endpoint does not do any check and just returns that is is `UP` no matter what: [source code of the check](https://github.com/hyperledger/besu/blob/ed1329cf848a9d7858d039a55add810da3c428b5/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/health/LivenessCheck.java#L24).

We need to define what a proper liveness check looks like and implement it.

**Comment by ajsutton** [comment]
That's typically all a liveness endpoint does.  Something context dependent such as reporting if the node is in sync or not is usually a separate health check endpoint. Both are useful in different situations (ie you want a docker container to consider itself started once the liveness check passes - it would time out long before the node finishes syncing and the health check returns OK).

**Comment by daniellehrner** [comment]
We [discussed this a while ago among the developers](https://wiki.hyperledger.org/display/BESU/2022-07-05+Contributor+Call) and the reason why we always return `UP`is that there is no metric to tell if a Besu node needs a restart or not. Every issue could potentially just be temporary or an external factor, like bad peers or problems with the CL client. A restart would not fix that.
  
We have updated the documentation of the endpoint to make this behavior clear: https://besu.hyperledger.org/en/stable/public-networks/how-to/use-besu-api/json-rpc/?h=liveness#liveness
