### ISSUE TITLE
Sync failure in besu node

### ISSUE THREAD

**Issue by Neoblock8** [hyperledger/besu#4015]
Hi,

I have an syncing issue while connecting with validator node.

**Commands:**
**Node1:**
besu --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT,WEB3,ADMIN,MINER,DEBUG,TRACE,TXPOOL --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8545 --rpc-http-host=0.0.0.0 --rpc-http-max-active-connections=100000

**Node2:**
besu --data-path=data --genesis-file=../genesis.json --bootnodes=<enode_of_node1>@ip:port --p2p-port=30306 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT,WEB3,ADMIN,MINER,DEBUG,TRACE,TXPOOL --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8556 --rpc-http-host=0.0.0.0  --rpc-http-max-active-connections=100000

![image](https://user-images.githubusercontent.com/81068101/175773706-c22fa9f2-e4e0-41bb-97ff-bf46d873bf75.png)

**Comment by matkt** [comment]
what is the version of Besu you are using during this test ?

**Comment by matt-nelson-csi** [comment]
This does not appear to be a fatal error. Have you experienced this when trying a re-sync? Or on the latest images?
