### ISSUE TITLE
trace_transaction returns internal error for fast synced node with pruning

### ISSUE THREAD

**Issue by AdamRylski** [hyperledger/besu#4028]
### Description
I would like to fetch traces for transactions with method `trace_transaction` for each transaction in block. I'm good with the latest blocks only (like 2-3 days retention in case of emergency), so I wanted to use fast-synced node with `pruning` option.
### Acceptance Criteria
* Node is returning traces for blocks in pruning range (latest X blocks)
### Steps to Reproduce (Bug)
1. Set up a node with version specified below and config specified below
2. Wait for node to sync with the network
3. Query the node with `trace_transaction` for a transaction from the block in pruning range, example payload (I'm using postman)
```
{
	"jsonrpc":"2.0",
	"method":"trace_transaction",
	"params":[
		"0xf12eaef052804d23bb0655b0cc44e97813433c2209b9aa5ee1341de1448ca800"
	],
	"id":1
}
```
Note:
At the time of writing, our node was on block `15039675`
while the mainnet was on block                      `15039785`
which gives us 110 block difference (prune set to 10k). The transaction is from block `15039675`

**Expected behavior:** I should receive traces for this transaction, according to description of [trace_transaction](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#trace_transaction)
> Your node must be an archive node (that is, synchronized without pruning or fast sync) or the requested transaction must be contained in a block within the number of [blocks retained](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#pruning-blocks-retained) with [pruning enabled](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#pruning-enabled) (by default, 1024).

**Actual behavior:** Node is returning internal error
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32603,
        "message": "Internal error"
    }
}
```
Given the amount of lines the node is logging, I'll post only errors:
```
Jun 28 09:50:38 besu-hl-eth-02 besu-eth[13735]: 2022-06-28 09:50:38.827+00:00 | BesuCommand-Shutdown-Hook | ERROR | Pruner | Failed to shutdown Pruner executor service.
Jun 28 09:50:38 besu-hl-eth-02 besu-eth[13735]: 2022-06-28 09:50:38.853+00:00 | EthScheduler-Services-147 (importBlock) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
Jun 28 10:33:14 besu-hl-eth-02 besu-eth[24406]: 2022-06-28 10:33:14.392+00:00 | Timer-0 | ERROR | Besu | Uncaught exception in thread "Timer-0"
Jun 28 10:33:22 besu-hl-eth-02 besu-eth[24406]: 2022-06-28 10:33:22.348+00:00 | BesuCommand-Shutdown-Hook | ERROR | Pruner | Failed to shutdown Pruner executor service.
Jun 28 10:41:39 besu-hl-eth-02 besu-eth[25483]: ERROR StatusLogger Reconfiguration failed: No configuration found for '5ffd2b27' at 'null' in 'null'
Jun 28 10:41:39 besu-hl-eth-02 besu-eth[25483]: ERROR StatusLogger Reconfiguration failed: No configuration found for '5ffd2b27' at 'null' in 'null'
Jun 28 10:57:17 besu-hl-eth-02 besu-eth[25483]: 10:57:17.814 [BesuCommand-Shutdown-Hook] ERROR org.hyperledger.besu.ethereum.worldstate.Pruner - Failed to shutdown Pruner executor service.
Jun 28 10:57:34 besu-hl-eth-02 besu-eth[25779]: ERROR StatusLogger Reconfiguration failed: No configuration found for '5ffd2b27' at 'null' in 'null'
Jun 28 10:57:35 besu-hl-eth-02 besu-eth[25779]: ERROR StatusLogger Reconfiguration failed: No configuration found for '5ffd2b27' at 'null' in 'null'
Jun 28 11:09:24 besu-hl-eth-02 besu-eth[25779]: 11:09:24.120 [BesuCommand-Shutdown-Hook] ERROR org.hyperledger.besu.ethereum.worldstate.Pruner - Failed to shutdown Pruner executor service.
Jun 28 11:13:50 besu-hl-eth-02 besu-eth[26335]: 2022-06-28 11:13:50.550+00:00 | Timer-0 | ERROR | Besu | Uncaught exception in thread "Timer-0"
Jun 28 11:13:54 besu-hl-eth-02 besu-eth[26335]: 2022-06-28 11:13:54.712+00:00 | BesuCommand-Shutdown-Hook | ERROR | Pruner | Failed to shutdown Pruner executor service.
Jun 28 11:15:40 besu-hl-eth-02 besu-eth[26618]: 2022-06-28 11:15:40.300+00:00 | BesuCommand-Shutdown-Hook | ERROR | Pruner | Failed to shutdown Pruner executor service.
```
**Frequency:** Happens for every transaction, does not matter in which block the transaction was included.
### Versions (Add all that apply)
* Software version:
```
besu/v22.4.3/linux-x86_64/openjdk-java-11
```
* Java version:
```
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```
* OS Name & Version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel Version:
```
Linux besu-hl-eth-02 5.4.0-90-generic #101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
````
* Virtual Machine software & version: N/A
* Docker Version: N/A
* Cloud VM, type, size: Hosted VM, 6 cores, 16GB ram
### Additional Information
* Besu is set up as a service with a following script
```
[Install]
Description=Besu Enterprise Ethereum java client
WantedBy=multi-user.target
After=syslog.target network.target
[Service]
User=besu-eth
Type=simple
Environment='JAVA_OPTS="-Xmx16G"'
ExecStart=/opt/besu/bin/besu --config-file /etc/besu-eth/config.toml
Restart=always
RestartSec=60
PermissionsStartOnly=true
PIDFile=/run/besu-eth/bitcoind.pid
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=besu-eth
LimitNOFILE=32768
CPUAccounting=yes
MemoryAccounting=yes
ProtectSystem=full
PrivateDevices=true
NoNewPrivileges=true
PrivateTmp=true
SuccessExitStatus=143
```
* I'm using the following config file placed in: `/etc/besu-eth/config.toml`
```
# data
data-path="/data/besu-eth/db-fast"
network="MAINNET"
min-gas-price=1000
sync-mode="FAST"
host-allowlist=["*"]
# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ETH","NET","TRACE","WEB3"]
rpc-http-cors-origins=["*"]
# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545
pruning-enabled=true
pruning-blocks-retained=10000
# logging
logging="INFO"
```

**Comment by AdamRylski** [comment]
I've found similar case here https://github.com/hyperledger/besu/issues/2628, but we are already using the latest version

**Comment by AdamRylski** [comment]
We've updated to https://github.com/hyperledger/besu/releases/tag/22.7.0-RC1, but it didn't help. Node is syncing in leaps and returns an internal server error when querying for traces

**Comment by Gabriel-Trintinalia** [comment]
Hi, I was not able to replicate this issue. Just synced a node and I am able to retrieve the trace for a block within the prune window. I tested with the latest besu version. Would you be able to check if the issue is still happening?
