### ISSUE TITLE
"World State Root does not match expected value" & InvalidBlockException

### ISSUE THREAD

**Issue by 3cl1ps** [hyperledger/besu#4029]
Hey, i got many errors :
World State Root does not match expected value, header
InvalidBlockException: Failed to import block: Invalid block at

while synchronizing, should delete everything and restart ?

full log at https://termbin.com/wqfq

### Steps to Reproduce (Bug)
I'm running besu on ubuntu 5.13.0-44 as a service.

exec command is :
/data3/besu/bin/besu --data-path /data3/ --data-storage-format=BONSAI --p2p-port=30350 --rpc-http-enabled=true --rpc-http-port=8590

### Versions (Add all that apply)
* Software version: besu/v22.4.3/linux-x86_64/openjdk-java-11
* Java version: openjdk version "11.0.15" 2022-04-19
* OS Name & Version: Ubuntu 20.04.4 LTS
* Kernel Version: 5.13.0-44

**Comment by 3cl1ps** [comment]
resolved by itself, maybe after restarting.

**Comment by daniellehrner** [comment]
I'll close the issue for now. Please fell free to re-open it, should it happen again.
