### ISSUE TITLE
Can I implement ERC token standards for private network on Hyperledger Besu?

### ISSUE THREAD

**Issue by isahaq65** [hyperledger/besu#4047]
I am newbie at Hyperledger Besu. I wanna implement ERC-721 token standards for asset tokenization on private network using hyperledger Besu. Is it possible or not? If possible , how can I implement or any suggestion?

**Comment by daniellehrner** [comment]
Besu is an Ethereum client. Any smart contract that is compatible with Ethereum can be executed no matter if is a public or a private network. So yes, you can use ERC-721 token in a private network without problems.

As this is not a issue with Besu itself, I will close it. If you have any further questions, please don't hesitate to reach out on Discord: https://discord.com/channels/905194001349627914/938504958909747250
