### ISSUE TITLE
Implement mechanism that encourages new node participation in stable networks

### ISSUE THREAD

**Issue by mark-terry** [hyperledger/besu#4054]
### Description
Stable networks present a challenge for initial peering. On Goerli (for example) Besu may experience slow sync rates and take many hours to fill its peer table; while receiving a large volume of P2P responses indicating the remote peer's peertable is full.

One approach to resolve this issue might be to implement a mechanism where Besu reserves part of its peertable capacity for new nodes that are attempting to join the network and begin syncing.

**Comment by macfarla** [comment]
PR LFR https://github.com/hyperledger/besu/pull/4200
