### ISSUE TITLE
Big memory consumption on RocketPool nodes

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#4057]
### Description
Some users from RocketPool with nodes less than 16 GiB are facing some memory issues. Besu node is then killed by OOM killer until next time, Besu reaches some threshold and killed again.
Below a screenshot from one of the users

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/5099602/177377215-e3b5e7f2-91be-4d55-b89b-a5570ac4a81f.png">

**Expected behavior:** [What you expect to happen]
Besu should stay at stable usage of resident memory.

**Actual behavior:** [What actually happens]
See screenshot above.

### Versions (Add all that apply)
Ubuntu Server 20.04 LTS
16gb RAM
i7-8650U Processor (8M Cache, up to 4.20 GHz)
Samsung 860 EVO SSD 2TB - M.2 SATA

**Comment by shemnon** [comment]
Can we get the CLI flags and redacted config settings (redacting identity and keys, but keeping other config items) for those instances?

**Comment by garyschulte** [comment]
Resolved for rocketpool (docker) users by #4126
