### ISSUE TITLE
Generate block when there is at least one transacton

### ISSUE THREAD

**Issue by henry-ngv** [hyperledger/besu#4074]
### Description
Blocks are generated after specific time even there is no transaction at all. This could lead to redundant storage space.

### Enhancement 
Generate block when there is at least one transaction.

**Comment by daniellehrner** [comment]
I think there is already an issue for that (at least for QBFT): https://github.com/hyperledger/besu/issues/3810

If the other issue covers your needs, please let me know. Then I will close this own, to not have duplicated issues.

**Comment by henry-ngv** [comment]
Yeap. The issue has already existed. Feel free to close this issue.

**Comment by daniellehrner** [comment]
Closing because of duplicate
