### ISSUE TITLE
Investigate Connect/Disconnect Events Ordering 

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#4091]
This may help identifying the problems with #2689 

Per @mbaxter's comment:
There could be a race condition wrt how connect and disconnect events are dispatched.  For example, say we’re in the process of handling a new connection and in another thread, we receive a disconnect message from the newly connected peer.  Is it possible we’re dispatching the disconnect event before the connection event?  This would cause stale, disconnected peers to persist in the EthPeers collection.  If this is actually the issue, it should be possible to rework disconnect events so that they are only dispatched after the connection event is dispatched.

**Comment by macfarla** [comment]
it broke some ATs but it works locally with my 3 nodes setup trying this one out in goerli https://github.com/hyperledger/besu/pull/4100

**Comment by macfarla** [comment]
Locally - RC2 locally with besu-local-nodes setup (3 x besu, one is a bootnode for the other 2) - I still get the stale disconnected duplicate every time (on the bootnode)

`2022-07-21 11:23:55.746+10:00 | nioEventLoopGroup-3-4 | DEBUG | EthProtocolManager | Disconnect - Outbound - 0x05 ALREADY_CONNECTED - PeerInfo{version=5, clientId='besu/v22.7.0-dev-1ff3967d/osx-x86_64/openjdk-java-11', capabilities=[eth/63, eth/64, eth/65, eth/66, snap/1], port=50505, nodeId=0xdcb9390953aec5dde1d60dd556c36827053ca9adaefd1b03f531592fea43824bae2919743f620bb8a9b6c2b9a54439771d4f9a74d261b74af7a10c2dd9f13c97} - 2 peers left
2022-07-21 11:23:55.746+10:00 | nioEventLoopGroup-3-4 | TRACE | EthProtocolManager | 2 EthPeers {
Peer 0x3548c87b9920ff16aa... PeerReputation 100, validated? true, disconnected? true,
Peer 0x3548c87b9920ff16aa... PeerReputation 101, validated? true, disconnected? false}
2022-07-21 11:23:55.746+10:00 | nioEventLoopGroup-3-4 | TRACE | RlpxAgent | 2 ConnectionsById {
RemotelyInitiatedRlpxConnection initiatedAt:1658366625488 to 0x3548c87b9920ff16aa4bdcf01c85f25117a29ae1574d759bad48cc9463d8e9f7c3c1d1e9fb0d28e73898951f90e02714abb770fd6d22e90371882a45658800e9 disconnected? false,
RemotelyInitiatedRlpxConnection initiatedAt:1658366635743 to 0xdcb9390953aec5dde1d60dd556c36827053ca9adaefd1b03f531592fea43824bae2919743f620bb8a9b6c2b9a54439771d4f9a74d261b74af7a10c2dd9f13c97 disconnected? false}
2022-07-21 11:23:55.747+10:00 | nioEventLoopGroup-3-4 | DEBUG | EthProtocolManager | Sending status message to Peer 0xdcb9390953aec5dde1... PeerReputation 100, validated? true, disconnected? false.
2022-07-21 11:23:55.748+10:00 | nioEventLoopGroup-3-4 | TRACE | EthProtocolManager | 3 EthPeers {
Peer 0x3548c87b9920ff16aa... PeerReputation 100, validated? true, disconnected? true,
Peer 0xdcb9390953aec5dde1... PeerReputation 100, validated? true, disconnected? false,
Peer 0x3548c87b9920ff16aa... PeerReputation 101, validated? true, disconnected? false}`

**Comment by macfarla** [comment]
goerli with RC2
~ 300 unique incidences of stale peers after 3 hours
```
sallymacfarlane@goerli-dev-sally-eth-peers-80369e81:~$ grep "validated? true, disconnected? true" /var/log/besu/besu.log > tmp.txt
sallymacfarlane@goerli-dev-sally-eth-peers-80369e81:~$ cat tmp.txt | wc -l
265857
sallymacfarlane@goerli-dev-sally-eth-peers-80369e81:~$ cat tmp.txt | sort | uniq > sorted.txt
sallymacfarlane@goerli-dev-sally-eth-peers-80369e81:~$ cat sorted.txt | wc -l
```

**Comment by macfarla** [comment]
goerli with 4100
~ 100 unique incidences of stale peers after 18 hours

```
sallymacfarlane@goerli-dev-sally-4001:~$ grep "validated? true, disconnected? true" /var/log/besu/besu.log > tmp.txt
sallymacfarlane@goerli-dev-sally-4001:~$ cat tmp.txt | wc -l
142
sallymacfarlane@goerli-dev-sally-4001:~$ cat sorted.txt | wc -l
138
```

It's about 70/30 stale peers and responses
```
Peer 670289121 0xe19fa955c58ef2fe73... PeerReputation 100, validated? true, disconnected? true,
 96 Peer 69032829 0xcdcb2d4a61bfdb943e... PeerReputation 100, validated? true, disconnected? true,
 97 Peer 692187735 0x99dcf2c3e56534e259... PeerReputation 100, validated? true, disconnected? true,
 98 Peer 730465720 0x851d38b40c90c0d1e3... PeerReputation 100, validated? true, disconnected? true,
 99 Peer 730475202 0xc4c9fed80520ff6778... PeerReputation 100, validated? true, disconnected? true,
100 Peer 75217378 0xd6518f4f318a172158... PeerReputation 100, validated? true, disconnected? true,
101 Peer 792382767 0x65a8545b97b8331d54... PeerReputation 100, validated? true, disconnected? true,
102 Peer 798963790 0xa11be9a634a0fcfdc6... PeerReputation 100, validated? true, disconnected? true,
103 Peer 833205436 0xe205b1c859ae321051... PeerReputation 100, validated? true, disconnected? true,
104 Peer 929481047 0xc1f109416ce13d4df4... PeerReputation 100, validated? true, disconnected? true,
105 {"@timestamp":"2022-07-20T06:55:48,493","level":"DEBUG","thread":"nioEventLoopGroup-3-7","class":"EthPeer","message":"Received useless response for headers from peer Peer 1322450591 0xbd527c4969165bec48... PeerReputati    on 100, validated? true, disconnected? true","throwable":""}
106 {"@timestamp":"2022-07-20T06:55:51,846","level":"DEBUG","thread":"nioEventLoopGroup-3-1","class":"EthPeer","message":"Received useless response for headers from peer Peer 333858630 0x5e9c0eb5e496d6bd78... PeerReputatio    n 100, validated? true, disconnected? true","throwable":""}
107 {"@timestamp":"2022-07-20T06:56:07,293","level":"DEBUG","thread":"nioEventLoopGroup-3-8","class":"EthPeer","message":"Received useless response for headers from peer Peer 1845761819 0xc94e917ff178d4d0b5... PeerReputati    on 100, validated? true, disconnected? true","throwable":""}
```

**Comment by macfarla** [comment]
^ in both cases on goerli I can see the stale peers in the logs but they don't persist. They do eventually get removed.

**Comment by macfarla** [comment]
Closing this one - conclusion is that there isn't a problem on mainnet/goerli
