### ISSUE TITLE
blockscout-postgresql -> Failed Binding PVC

### ISSUE THREAD

**Issue by S-Kia** [hyperledger/besu#4101]
### Description
i would like to deploy hyperledger besu on cloud container engine in huawei cloud (likely deploy on k8s)

### Acceptance Criteria
run hyperledger besu on cloud

### Versions (Add all that apply)
- Clone the Quorum-Kubernetes
- running Kubernetes cluster
- Install Kubectl
- Install Helm3 

### Steps to Reproduce (Bug)
1. follow this page "https://besu.hyperledger.org/en/stable/Tutorials/Kubernetes/Deploy-Charts/#3-deploy-the-monitoring-chart"
2. every thing is running until step 10, that is deploy blockscout-postgresql, it doesn't work.

**Expected behavior:** can running blockscout and use to monitoring the blockchain.

**Actual behavior:** failed binding pvc
**Frequency:** always

Run >> kubectl describe -n besu pvc data-blockscout-postgresql-0

-----------------------------------------------------------------------------------------------
Name:          data-blockscout-postgresql-0
Namespace:     besu
StorageClass:
Status:        Pending
Volume:
Labels:        app.kubernetes.io/instance=blockscout
               app.kubernetes.io/name=postgresql
               role=primary
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       blockscout-postgresql-0
Events:
  Type    Reason         Age                    From                         Message

  Normal  FailedBinding  3m54s (x242 over 64m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

 -----------------------------------------------------------------------------------------------
>> i try to edit parameter to create PV, bound PVC and set storage class that show not valid.
please guild me to solve that problem. thank you very much

**Comment by non-fungible-nelson** [comment]
@joshuafernandes - can you take a look and status or close this?

**Comment by S-Kia** [comment]
I already solve this problem.

Thank you very much
