### ISSUE TITLE
Increase default maximum size for p2p messages

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#4119]
I have noticed that we are disconnecting peers that are responding to our requests on the p2p protocol during syncing because they are sending messages larger than the current max size of 10 MB.
This PR increases the default maximum size to 20 MB to make sure that we are not disconnecting useful peers.
This maximum size can be set using the experimental CLI argument "--Xeth-max-message-size"

**Comment by ajsutton** [comment]
May be worth checking what the max size is for other clients as increasing the size here could open DoS vectors.  The other way to avoid this would be to reduce the size of block ranges we request.  And in either case we should ensure the size of responses to our block requests is well below whatever maximum size we set as block sizes are likely to grow in the future which could re-introduce this problem.

**Comment by pinges** [comment]
You are absolutely right. The current limit has probably been selected by calculating what was expected to be the maximum possible size plus a margin. The question is whether we want to change the number of block ranges that we are requesting or increase the max message size. 
I'm not sure if it is possible to adjust either of these in a way that we do not run into that problem as block sizes grow in the future, but that would be the best solution!

**Comment by ajsutton** [comment]
I'm more concerned about whether the message limit also applies to unsolicited messages. We don't want to increase the amount of data we'd read and try to process as that can open up DoS vulnerabilities.  I'm not sure if increasing from 10Mb would be an issue, but it's something to consider as it's not necessarily guaranteed to be safe to increase that limit.

**Comment by iamhsk** [comment]
One approach is to investigate the message limit on other clients to decide on the limit

**Comment by pinges** [comment]
PR https://github.com/hyperledger/besu/pull/4120

**Comment by mbaxter** [comment]
The 10MB limit is mentioned [here](https://github.com/ethereum/devp2p/blob/87c916174414d59ffd2195f207c5558154ff8e2a/caps/eth.md#basic-operation):
```
Client implementations should enforce limits on protocol message sizes. The underlying RLPx transport limits the size of a single message to 16.7 MiB. The practical limits for the eth protocol are lower, typically 10 MiB. If a received message is larger than the limit, the peer should be disconnected.
```

**Comment by pinges** [comment]
Good question. I'm not sure what client did this, but as these limits in the p2p spec are only "should"s and the 10MB limit says "typically" I think there is a chance that other clients have not implemented that. 
Loosing these peers is really bad, as this happens on top of our problems finding peers in the first place. These peers are delivering useful data.
I think it would be good to understand which clients are sending these big messages and I will add a debug log message to find out!

**Comment by pinges** [comment]
Had a goerli node running for some time where I added a debug log to see which clients send messages that are bigger than 10MB
2022-07-26 16:50:54.367+10:00 | nioEventLoopGroup-3-7 | DEBUG | EthProtocolManager | Peer PeerId 0xc80015ba29d42f15e7f0b3a4f9f8c38f447a080b537ac8165386e72b8d7b82c0b1aa0935ea6185deffb1de6f9c1e228e48e075aa3944637f8335ce4a703e1ccf, reputation PeerReputation 100, validated? true, disconnected? false, client: besu/v22.4.3/linux-x86_64/openjdk-java-17, connection 90281444, enode enode://c80015ba29d42f15e7f0b3a4f9f8c38f447a080b537ac8165386e72b8d7b82c0b1aa0935ea6185deffb1de6f9c1e228e48e075aa3944637f8335ce4a703e1ccf@45.8.223.230:58342 sent a message with size 12443552, larger than the max message size 10485760

**Comment by pinges** [comment]
22.4.3 was released on the 17th of June 2022, @mbaxter PR for limiting the size of outgoing messages was merged on the 6th of July!

**Comment by mbaxter** [comment]
If we're only seeing this problem with Besu nodes, we should probably re-enable this limit now or in a few months time.

Another safe option, which would allow us to re-enable this limit if needed, would be to:
* Split up the [`--Xeth-max-message-size`](https://github.com/mbaxter/besu/blob/f3042590b11cb7b3fa6fce328f8b89232dd38f75/besu/src/main/java/org/hyperledger/besu/cli/options/unstable/EthProtocolOptions.java#L37-L44) flag into 2: `--Xeth-max-message-size-outbound` and `--Xeth-max-message-size-inbound`
* We could then increase the inbound limit to the [16MB RLPx limit](https://github.com/hyperledger/besu/blob/93da04cf0050fbdeae22e27d4976807b8475d727/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxFrameConstants.java#L21) to effectively disable the inbound limit temporarily
* After some time, we could then move the inbound limit back down the 10MB
