### ISSUE TITLE
JSON-RPC method eth_getLogs improperly interprets block arguments

### ISSUE THREAD

**Issue by mbaxter** [hyperledger/besu#4123]
### Description
Besu's implementation of `eth_getLogs` accepts a "blockParameter" for the `fromBlock` and `toBlock` values where the block parameter can be a number or a special string ("latest", "earliest", or "pending").  If a string parameter is provided, it is ignored and  [is instead replaced](https://github.com/hyperledger/besu/blob/32fd3476e3409ec5b10c654b96a00418f24f53a5/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetLogs.java#L61-L63) with the latest block (in the case of the `toBlock` parameter) or the earliest block (in the case of the `fromBlock` parameter).  This is a bug - if I request blocks from "latest" to "latest", I would expect to get logs from the latest block, but I instead initiate a query for all logs across the entire history of the chain. 

Additionally, the [JSON-RPC spec documentation](https://github.com/ethereum/execution-apis/blob/1e2058b3a104ada4adfd3d3b90e9982050541fc4/src/engine/specification.md#underlying-protocol) only mentions numeric values for the `fromBlock` and `toBlock` parameters.  So, the API should most likely be throwing an error if a string value is given.  However, if besu is going to have expanded functionality and accept string parameters, they should be interpreted correctly.

As a general protection, it's probably a good idea to return an error if the range of blocks requested is too large.  An optional upperbound parameter (`--rpc-logs-range-upper-bound`?) could be added to enforce this.  

### Acceptance Criteria
* Besu does not interpret requests to `eth_getLogs` from "latest" to "latest" as a query across the entire range of all blocks

**Comment by frankisawesome** [comment]
Unless this is a priority issue I'm interested in taking this (turn around will be a bit longer since this will be part time for me)

**Comment by matt-nelson-csi** [comment]
@frankisawesome this is great! Let me know if we can assist.

**Comment by non-fungible-nelson** [comment]
@mark-terry is this related to #4443?
