### ISSUE TITLE
Provide useful information when backward sync preconditions not met

### ISSUE THREAD

**Issue by ajsutton** [hyperledger/besu#4141]
### Description
When syncing a new teku+besu node, besu 22.4.0 wound up repeatedly logging: 
```
2022-07-20 21:00:12.578+00:00 | ForkJoinPool.commonPool-worker-1 | INFO  | BackwardsSyncAlgorithm | Waiting for preconditions...
```

This is an entirely unhelpful log message. It should clearly explain what preconditions it's waiting on so the user knows why sync is not progressing. Looking at the code in this case I think it was that the initial sync hadn't completed.

**Comment by iamhsk** [comment]
@daniellehrner This might be useful for our logging updates

**Comment by matt-nelson-csi** [comment]
@gezero as well RE backwards sync.

**Comment by non-fungible-nelson** [comment]
Closing for backwards sync changes in 22.10.x
