### ISSUE TITLE
Discrepancy in tracked peers

### ISSUE THREAD

**Issue by ladidan** [hyperledger/besu#4193]
### Description
I've recently noticed a significant difference in logged peer count per INFO logs (e.g. [...] Peers: 40) vs. various prometheus/grafana metrics-dashboards (querying the API) which after a certain amount of peer discovery time settle at around the max-peer defined number (e.g. 25).

### Versions (Add all that apply)
22.7.0-RC3 on Ubuntu 22.04 server

**Comment by iamhsk** [comment]
Hi @ladidan, thank you for opening an issue. Could you answer the following questions to help us investigate this further? Could you tell which network you were running besu on? And could you provide us a log extract?

**Comment by ladidan** [comment]
- tested on Goerli
- log would look like e.g.: `EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #7,339,454 / 26 tx / 0 om / 10,402,057 (34.7%) gas / (0x1afc02c542fc345d3286121f7ce25d16103262c3dcfcc832eed303b3a65b780b) in 0.232s. **Peers: 121**`

whereas the grafana dashboard shows 25 current peers (via the besu API)

**Comment by iamhsk** [comment]
Hi @ladidan, there is already an open issue to resolve this. Please follow #2689 for progress :)
