### ISSUE TITLE
Relax fast-sync-min-peers

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#4202]
### Description
Requiring a minimum of 5 peers before beginning a fast-sync has been deemed too costly, especially on low participation networks.  Similarly, post-merge there is no need for a peer minimum at all, since the consensus layer directs besu to the exact hash that should be used for the pivot block for a fast-sync via the finalized head.  

This PR suggests we should relax the minimum peer requirement for starting a fast sync to 2, and removing this requirement entirely post-merge.

### Acceptance Criteria
* PoW, PoA networks can fast-sync with a minimum of 2 peers https://github.com/hyperledger/besu/pull/4298
* Post-merge networks can fast-sync immediately, as long as they have peers that satisfy the pivot/finalized block requirements coming from the consensus client

**Comment by macfarla** [comment]
fast-sync-min-peers is used by FAST and SNAP sync

**Comment by macfarla** [comment]
@garyschulte can we close this ticket since the PR is merged? Or is there still work to be done?

**Comment by garyschulte** [comment]
Let's close it.
