### ISSUE TITLE
Make snap sync the default sync method for named ethereum networks

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#4203]
### Description
Move to snap sync as the default for ethereum mainnet and test networks

### Acceptance Criteria
* update network defaults
* update corresponding documentation

**Comment by macfarla** [comment]
besu change here https://github.com/hyperledger/besu/pull/6530
docs change here https://github.com/hyperledger/besu-docs/pull/1515

created #6612 to clean up the deprecated options (but they are widely used so could take a while to get all docs updated)
