### ISSUE TITLE
Mainnet Besu v22.7.0 API Execution Engine and Lighthouse v2.5.1 TTD override values do not match

### ISSUE THREAD

**Issue by Summerside-sys** [hyperledger/besu#4220]
In order to get it to match needed:

--override-genesis-config="terminalTotalDifficulty=115792089237316195423570985008687907853269984665640564039457584007913129638912"

Currently:
Lighthouse value is: 115792089237316195423570985008687907853269984665640564039457584007913129638912
Besu value is:           115792089237316195423570985008687907853269984665640564039457584007913129638911

or 
Lighthouse value:  0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc00
Besu value: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff

Besu Log:
Aug 04 19:50:18 server besu[475192]: 2022-08-04 19:50:18.298+00:00 | vert.x-worker-thread-0 | WARN  | EngineExchangeTransitionConfiguration | Configured terminal total difficulty 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff does not match value of consensus client 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc00

Lighthouse Beacon Log:
38912, terminal_block_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, terminal_block_number: 0 }, remote: TransitionConfigurationV1 { terminal_total_difficulty: 115792089237316195423570985008687907853269984665640564039457584007913129638911, terminal_block_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, terminal_block_number: 0 }, msg: ensure lighthouse and the execution client are up-to-date and configured consistently, service: exec

**Comment by daniellehrner** [comment]
Hi @Summerside-sys,
Yes, it seems you are correct. Thank you for opening the issue! I've created a PR to fix that.
