### ISSUE TITLE
Besu get's stuck with World State Root does not match expected value

### ISSUE THREAD

**Issue by Gabriel-Trintinalia** [hyperledger/besu#4225]
### Description
Besu get's stuck with `World State Root does not match expected value`

Besu got stuck on block 15286188 with error: World State Root does not match expected value, header 
User has restarted and error persisted and appear straight away. 

Discord: https://discord.com/channels/905194001349627914/1004830834873860127/1005385581821444128

### Versions (Add all that apply)
* Software version: 22.7.0

**Comment by Gabriel-Trintinalia** [comment]
![image](https://user-images.githubusercontent.com/14837672/183241453-9b715ff3-fe41-4725-912c-526eb63e719f.png)

**Comment by Gabriel-Trintinalia** [comment]
[besu_error_log.txt](https://github.com/hyperledger/besu/files/9274688/besu_error_log.txt)

**Comment by Gabriel-Trintinalia** [comment]
Maybe duplicate of https://github.com/hyperledger/besu/issues/4151

**Comment by ph1go** [comment]
When the error first occurred:

![besu_stopped_4](https://user-images.githubusercontent.com/30246276/183241674-5fd591b7-fbc0-47f2-a2ab-86554f1c343f.jpg)

**Comment by non-fungible-nelson** [comment]
Hi @ph1go - can you provide us with some more environment and config information? Either config file or command line arguments? and the environment where you are running Besu. Thank you!

**Comment by ph1go** [comment]
> Hi @ph1go - can you provide us with some more environment and config information? Either config file or command line arguments? and the environment where you are running Besu. Thank you!

Sure, the environment is a fresh-ish Ubuntu Server 20.04.4 install, no Docker or any other containerisation. I run Besu in a tmux session via a config file which is as follows:

    data-path="/nodes/ethereum/besu" < a mounted 2.5" SSD
    data-storage-format="BONSAI"
    sync-mode="X_SNAP"
    rpc-http-enabled=true
    rpc-http-api=["ETH","NET","WEB3","ADMIN"]
    metrics-enabled=true

**Comment by iamhsk** [comment]
This is a duplicate issue. We'll track this as part of #4151
