### ISSUE TITLE
besu classic pow gpu miner set low "difficulty"

### ISSUE THREAD

**Issue by feculay** [hyperledger/besu#4226]
hi, please
how to set low difficulty in besu classic stratum port for gpu pow miner?

ububtu besu java
thanks

**Comment by non-fungible-nelson** [comment]
Maybe @diega can help with this?

**Comment by diega** [comment]
Hello @feculay, what do you mean by setting "low difficulty" in Besu? PoW difficulty is defined by the protocol to keep a quite regular block sealing time. AFAICS, if there is any level of configuration regarding a target difficulty of the mining process, that's something that should be configured in the mining software.

**Comment by macfarla** [comment]
PoW is now deprecated so we won't be adding features to it
