### ISSUE TITLE
Change the default size for header and chain segment requests

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#4229]
@ajsutton noted the following:
[I’m not sure if I’ve said this somewhere already or not, but if it helps any, I’ve had a lot of success syncing besu nodes with 22.7.0-RC2 and RC3 using:
    besu_data_storage_format: "BONSAI"
    besu_cmdline_args:
      - "--Xsynchronizer-downloader-chain-segment-size=100"
      - "--Xsynchronizer-downloader-header-request-size=100"
      - "--Xsynchronizer-fast-sync-full-validation-rate=0.0001"
    besu_sync_mode: X_CHECKPOINT
The Xsynchronizer-fast-sync-full-validation-rate is just cheating to save CPU and I don’t think it’s actually affecting the ability to sync, though it may be making it a little faster.
The reduced request sizes I think are what’s been most helpful. I’ve sync’d ropsten, goerli and MainNet multiple times with this setup and they’ve found and held peers well.](url)

**Comment by pinges** [comment]
The task here is to create a draft PR and then create a few nodes to see whether this makes a difference

**Comment by iamhsk** [comment]
Duplicate issue. Closing.
