### ISSUE TITLE
Using getFeeHistory with "earliest"

### ISSUE THREAD

**Issue by sjmini** [hyperledger/besu#4231]
### Description
When getFeeHistory web3 API is used with "earliest" tag as below example,
it seems that the node produces the wrong output.

_**web3_nethermind.eth.getFeeHistory(400, "earliest", [20]);**_

**Expected behavior:**
Different clients give the below response.
{
        "oldestBlock": "0x0",
        "reward": [
            [
                "0x0"
            ]
        ],
        "baseFeePerGas": [
            "0x0",
            "0x3b9aca00"
        ],
        "gasUsedRatio": [
            0
        ]
    },

**Actual behavior:** 

Only the besu produce different results.

"oldestBlock": "0x0",
        "baseFeePerGas": [
            "0x0",
            "0x3b9aca00",
            "0x342770c0",
            "0x2da282a8",
            "0x27ee3253",
            "0x22f06c09",
            "0x1e925e88",
            "0x1ac012b7",
            "0x17681061",
            "0x147b0e55",
            "0x11ed611c",
            "0xfafb4f9",
            "0xdbb0c12",
            "0xc03aa90",
            "0xa83353e",
            "0x933ad95",
            "0x80d37e3",
            "0x70c3b5d",
            "0x62ab3f2",
            "0x565dfc1",
            "0x4b995bb",
            "0x4226304"
   ...
   ...
   ]
 "gasUsedRatio": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.0013010214939282877,
            0,
            0.0012984844028217674,
            0,
            0,
            0.0012946880060842939,
            0,
            0.0012921632880903895,
            0,
            0.0012896434872696834,
            0.0012883854505698652,
            0,
   ...
   ...
]

**Frequency:** 
Always

### Versions (Add all that apply)
* Software version: 
besu/v22.4.4/linux-x86_64/openjdk-java-11

**Comment by iamhsk** [comment]
Check if there is a hive test related to this. Also check how Geth's output looks like.

**Comment by macfarla** [comment]
would be good to add a "by spec" test for this - see org/hyperledger/besu/ethereum/api/jsonrpc/bonsai/EthJsonRpcHttpBySpecTest.java

**Comment by macfarla** [comment]
there is 1 `rpc-compat` hive test for eth_feeHistory https://hivetests2.ethdevops.io/

**Comment by gtebrean** [comment]
I'm closing this as the PR has been merged. If will occur again I will reopen it.
