### ISSUE TITLE
Incorrect logIndex when using getPastLogs API

### ISSUE THREAD

**Issue by sjmini** [hyperledger/besu#4239]
### Description
When we execute the attached test case (getPastLogs), the client produces the wrong values for the **logIndex** field.
Similar issues occur when using the getTransactionReceipt API.

### Steps to Reproduce (Bug)
1. Download test files
[test_cases.zip](https://github.com/hyperledger/besu/files/9293170/test_cases.zip)

2. Run the node with the following command
`besu --data-path test_cases/data-besu --genesis-file test_cases/besu.json --rpc-http-port 8549 --rpc-http-enabled --rpc-http-api ETH --network-id 15 --discovery-enabled false`

3. Execute the javascript test case
`test1.js`

**Expected behavior:** [What you expect to happen]
{ ... ,"logIndex": 1, ...}
{ ... ,"logIndex": 1, ...}
{ ... ,"logIndex": 5, ...}
{ ... ,"logIndex": 2, ...}
{ ... ,"logIndex": 5, ...}

**Actual behavior:** [What actually happens]
{ ... ,"logIndex": 0, ...}
{ ... ,"logIndex": 1, ...}
{ ... ,"logIndex": 1, ...}
{ ... ,"logIndex": 1, ...}
{ ... ,"logIndex": 1, ...}

**Frequency:** [What percentage of the time does it occur?]
Always

### Versions (Add all that apply)
* Software version: besu/v22.4.4/linux-x86_64/openjdk-java-16
* OS Name & Version: Ubuntu 20.04.4 LTS

**Comment by iamhsk** [comment]
Hi @sjmini, thank you for opening this issue. We are tracking this in relation to #4114.

**Comment by sjmini** [comment]
@iamhsk Thanks for letting me know this.

**Comment by iamhsk** [comment]
Fixed as part of #4114.
