### ISSUE TITLE
Wrong id in log objects when using getPastLogs API

### ISSUE THREAD

**Issue by JosephK95** [hyperledger/besu#4242]
### Description
When we execute `getPastLogs` API, it seems that Besu returns wrong value for the `id` field in every returned log object. The same thing happens when using `getTransactionReceipt` API.

### Steps to Reproduce (Bug)
1. Download the following file and untar it:
[test_log_id.tar.gz](https://github.com/hyperledger/besu/files/9295205/test_log_id.tar.gz)
2. Execute Besu binary with the following flags:
`besu --data-path test_log_id/data-besu --genesis-file test_log_id/besu.json --rpc-http-port 8549 --rpc-http-enabled --rpc-http-api ETH --network-id 15 --discovery-enabled false`
3. Execute the test case file: `node test1.js`

**Expected behavior:**
All other client implementations return the following result:
<pre>
[{..., "id": "log_e92989bc"},
 {..., "id": "log_f02e3690"},
 {..., "id": "log_2312ee27"},
 {..., "id": "log_deff5d41"}, 
 {..., "id": "log_0d27fabe"}, ...] 
</pre>

**Actual behavior:**
Only Besu returns the following result:
<pre>
[{..., "id": "log_207bb0d1"},
 {..., "id": "log_f02e3690"},
 {..., "id": "log_840ba6f4"},
 {..., "id": "log_3a16747a"}, 
 {..., "id": "log_1344d910"}, ...] 
</pre>

**Frequency:** 
Always

### Versions (Add all that apply)
* Software version: besu/v22.4.4/linux-x86_64/openjdk-java-16
* OS Name & Version: Ubuntu 20.04.4 LTS
* Node.js / web3.js Versions: v16.15.0 / v1.7.3

**Comment by NickSneo** [comment]
I have been testing about this bug, trying to reproduce it in 2 cases - 

1. Connected Geth and Besu to Goerli Testnet and ran the getPastLogs, and compared the results
2. Created my own private Testnet using Besu and Geth clients and CLIQUE consensus, ran the getPastLogs, and compared the results.

**1st Case -** 
GetPastLogs from Block 4350000 to 4350001. 

**2nd Case -** 
GetPastLogs from Block 0 to latest on address - "0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80".

[priv-testnet.zip](https://github.com/hyperledger/besu/files/10917243/priv-testnet.zip)

Steps to start and sync the network with all nodes running and reproduce the results - 

1. Download the uncompress the file above.
2. `cd clique-testnet-besu/node1`
3. `besu --data-path=data --genesis-file=../cliqueGenesis.json --network-id 1106 --rpc-http-enabled --rpc-http-api=ETH,NET,CLIQUE --host-allowlist="*" --rpc-http-cors-origins="all"`
4. `besu --data-path=data --genesis-file=../cliqueGenesis.json --bootnodes=enode://ad347c9d87ec29cdf3179269f342495afae88b72285a0fadb3630f703a46a3b5e3cf67414915841fce9fd7f07eb0e9a35874b426c793018fcf05787f0eb8bd9e@127.0.0.1:30303 --network-id 1106 --p2p-port=30304 --rpc-http-enabled --rpc-http-api=ETH,NET,CLIQUE --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8546`
5. `besu --data-path=data --genesis-file=../cliqueGenesis.json --bootnodes=enode://ad347c9d87ec29cdf3179269f342495afae88b72285a0fadb3630f703a46a3b5e3cf67414915841fce9fd7f07eb0e9a35874b426c793018fcf05787f0eb8bd9e@127.0.0.1:30303 --network-id 1106 --p2p-port=30305 --rpc-http-enabled --rpc-http-api=ETH,NET,CLIQUE --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8547`
6. `cd clique-testnet-geth/`
7. `geth  --port 30306 --http --http.corsdomain="https://remix.ethereum.org" --http.api web3,eth,debug,personal,net --vmdebug --networkid 1106 --datadir data --http.port 8548 --syncmode full --bootnodes enode://ad347c9d87ec29cdf3179269f342495afae88b72285a0fadb3630f703a46a3b5e3cf67414915841fce9fd7f07eb0e9a35874b426c793018fcf05787f0eb8bd9e@127.0.0.1:30303`


Results - 
Besu - 
`[
  {
    logIndex: 0,
    removed: false,
    blockNumber: 78,
    blockHash: '0x1f8686a0a93b95ac2d28a46ee2f8350140bbd9e2c5f0252fdfeeb9828ea4a59e',
    transactionHash: '0xd75a1432bce1dff80bf3b46bc6cfdc60df1f1858eb056e030c23a5760f61db8a',
    transactionIndex: 0,
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000000',
      '0x0000000000000000000000000000000000000000000000000000000000000001'
    ],
    id: 'log_00829549'
  },
  {
    logIndex: 0,
    removed: false,
    blockNumber: 79,
    blockHash: '0x0c890569283756985098d6761d396868424d6d11c5b6ddb8129370709f1b5416',
    transactionHash: '0x04aa70082411fdecc2d27fc785c5612f5dd1635ade6acf5493a0d3bc0328eb7c',
    transactionIndex: 0,
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000001',
      '0x0000000000000000000000000000000000000000000000000000000000000002'
    ],
    id: 'log_2202fc70'
  },
  {
    logIndex: 0,
    removed: false,
    blockNumber: 80,
    blockHash: '0x10e7ae40897f554a162d6995ac32440c26fd8f3a91edbca04041f1221a0da2f7',
    transactionHash: '0x81164136b6ca1941f9f86afd02cf8bc797a0bbd05e0c79c42b39bad2b64ed557',
    transactionIndex: 0,
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000002',
      '0x0000000000000000000000000000000000000000000000000000000000000003'
    ],
    id: 'log_5b3806a6'
  },
  {
    logIndex: 0,
    removed: false,
    blockNumber: 81,
    blockHash: '0x18ab030f0a10920b567a0cce954a2dcc4fab55dfb17dd0b5c6a2d8a8608df0a8',
    transactionHash: '0xa3e3d93972a22160a94aca54fcb2f3489d5003c9ec3a48cc9d045f777b490ab5',
    transactionIndex: 0,
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000003',
      '0x0000000000000000000000000000000000000000000000000000000000000004'
    ],
    id: 'log_8d314a83'
  },
  {
    logIndex: 0,
    removed: false,
    blockNumber: 82,
    blockHash: '0x6fc4252c4e63df8bd9db096176454d89e145c0e85dee70dca88163cf926f3260',
    transactionHash: '0x8e82b1e77cc7037b6ef3a6eebcfc1f4b4de966cc2af92918ec35ac6e7e8341da',
    transactionIndex: 0,
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000004',
      '0x0000000000000000000000000000000000000000000000000000000000000005'
    ],
    id: 'log_167ec3f9'
  },
  {
    logIndex: 0,
    removed: false,
    blockNumber: 83,
    blockHash: '0x3a7f20cf8b27f416c4b74ecd5ab3d8909f0be8416cd3bbf5aa520dbb0996ea4a',
    transactionHash: '0xcbed39d75418b99c1c30ada1e49db142c87e658397669354dc2aee6864973976',
    transactionIndex: 0,
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000005',
      '0x0000000000000000000000000000000000000000000000000000000000000006'
    ],
    id: 'log_e0516351'
  },
  {
    logIndex: 0,
    removed: false,
    blockNumber: 84,
    blockHash: '0x624dd23c14227a57b98313f2d438a6143e5bbed51d478bb02a9cc233f3894c92',
    transactionHash: '0x6a3b5fbdc1ef7af16945d5ceaf27bf83a3485b0ddd5a5a2f9dcfdeb14f1912b0',
    transactionIndex: 0,
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000006',
      '0x0000000000000000000000000000000000000000000000000000000000000007'
    ],
    id: 'log_1b3e5956'
  }
]`

Geth - 
`[
  {
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000000',
      '0x0000000000000000000000000000000000000000000000000000000000000001'
    ],
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    blockNumber: 78,
    transactionHash: '0xd75a1432bce1dff80bf3b46bc6cfdc60df1f1858eb056e030c23a5760f61db8a',
    transactionIndex: 0,
    blockHash: '0x1f8686a0a93b95ac2d28a46ee2f8350140bbd9e2c5f0252fdfeeb9828ea4a59e',
    logIndex: 0,
    removed: false,
    id: 'log_00829549'
  },
  {
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000001',
      '0x0000000000000000000000000000000000000000000000000000000000000002'
    ],
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    blockNumber: 79,
    transactionHash: '0x04aa70082411fdecc2d27fc785c5612f5dd1635ade6acf5493a0d3bc0328eb7c',
    transactionIndex: 0,
    blockHash: '0x0c890569283756985098d6761d396868424d6d11c5b6ddb8129370709f1b5416',
    logIndex: 0,
    removed: false,
    id: 'log_2202fc70'
  },
  {
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000002',
      '0x0000000000000000000000000000000000000000000000000000000000000003'
    ],
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    blockNumber: 80,
    transactionHash: '0x81164136b6ca1941f9f86afd02cf8bc797a0bbd05e0c79c42b39bad2b64ed557',
    transactionIndex: 0,
    blockHash: '0x10e7ae40897f554a162d6995ac32440c26fd8f3a91edbca04041f1221a0da2f7',
    logIndex: 0,
    removed: false,
    id: 'log_5b3806a6'
  },
  {
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000003',
      '0x0000000000000000000000000000000000000000000000000000000000000004'
    ],
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    blockNumber: 81,
    transactionHash: '0xa3e3d93972a22160a94aca54fcb2f3489d5003c9ec3a48cc9d045f777b490ab5',
    transactionIndex: 0,
    blockHash: '0x18ab030f0a10920b567a0cce954a2dcc4fab55dfb17dd0b5c6a2d8a8608df0a8',
    logIndex: 0,
    removed: false,
    id: 'log_8d314a83'
  },
  {
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000004',
      '0x0000000000000000000000000000000000000000000000000000000000000005'
    ],
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    blockNumber: 82,
    transactionHash: '0x8e82b1e77cc7037b6ef3a6eebcfc1f4b4de966cc2af92918ec35ac6e7e8341da',
    transactionIndex: 0,
    blockHash: '0x6fc4252c4e63df8bd9db096176454d89e145c0e85dee70dca88163cf926f3260',
    logIndex: 0,
    removed: false,
    id: 'log_167ec3f9'
  },
  {
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000005',
      '0x0000000000000000000000000000000000000000000000000000000000000006'
    ],
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    blockNumber: 83,
    transactionHash: '0xcbed39d75418b99c1c30ada1e49db142c87e658397669354dc2aee6864973976',
    transactionIndex: 0,
    blockHash: '0x3a7f20cf8b27f416c4b74ecd5ab3d8909f0be8416cd3bbf5aa520dbb0996ea4a',
    logIndex: 0,
    removed: false,
    id: 'log_e0516351'
  },
  {
    address: '0x00Be1A0db3eb8471e5FE41e35288E4b0DDa42D80',
    topics: [
      '0x855634b70e44fcab19c732cee4768b0d6b4607c9bc6448acbf502ef4d1a1d12d',
      '0x0000000000000000000000000000000000000000000000000000000000000006',
      '0x0000000000000000000000000000000000000000000000000000000000000007'
    ],
    data: '0x0000000000000000000000001fa8e0c8e72cfadade6d7325eef7b1c804e78f38',
    blockNumber: 84,
    transactionHash: '0x6a3b5fbdc1ef7af16945d5ceaf27bf83a3485b0ddd5a5a2f9dcfdeb14f1912b0',
    transactionIndex: 0,
    blockHash: '0x624dd23c14227a57b98313f2d438a6143e5bbed51d478bb02a9cc233f3894c92',
    logIndex: 0,
    removed: false,
    id: 'log_1b3e5956'
  }
]`

**Comment by NickSneo** [comment]
We can close this issue, as it is not reproducible in the latest Besu (23.1.0)
