### ISSUE TITLE
Uniswap on Private network

### ISSUE THREAD

**Issue by elmurci** [hyperledger/besu#4247]
### Description

I am using a private network and have managed to deploy the Uniswap contracts with no issues.
However, when trying to interact with them I keep getting the following error:

```
reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\n  \"jsonrpc\" : \"2.0\",\n  \"id\" : 58,\n  \"error\" : {\n    \"code\" : -32000,\n    \"message\" : \"Execution reverted\",\n    \"data\" : \"0x\"\n  }\n}","error":{"code":-32000,"data":"0x"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x5d21dba00\",\"from\":\"xxx\",\"to\":\"xxx\",\"data\":\"0x8a7c195f00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000001\"}],\"id\":58,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://regular01.okapi.blockchaincoe.sandigital.dev.corp/"}, method="estimateGas", transaction={"from":"xxx","gasPrice":{"type":"BigNumber","hex":"0x05d21dba00"},"to":"xx","data":"0x8a7c195f00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000001","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.1)
```

It seems the execution is failing on the `estimateGas` call, but even if I set the gas limit manually, it returns the same error on the same call.

Executing the same contracts and code in the Rinkeby network works just fine.

Checking the node logs, I can see this revert:

```
2022-07-22 08:35:26.352+00:00 | vert.x-worker-thread-5 | TRACE | EVM | Depth: 0
Operation: REVERT
PC: 846
Gas cost: 0
Gas Remaining: 9007199254718446
Depth: 0
Stack:
    0 0x0000000000000000000000000000000000000000000000000000000000000001
    1 0x0000000000000000000000000000000000000000000000000000000000000064
    2 0x00a8
    3 0x000000000000000000000000000000000000000000000000000000008a7c195f
```

(Gas limit is set very high, so not likely to be the issue)

### Versions

Besu version: 21.10.6

### Smart contract information 

Uniswap contracts. They work fine on Testnets like Rinkeby

**Comment by puneet166** [comment]
@matkt @shemnon @macfarla @garyschulte . please share your thought regarding the issue.

The same issue is happening in my case as well. when i am trying to deploy uniswap smart contract on besu network.

**Comment by shemnon** [comment]
With so little to go on it's hard to debug it.  My guess is that the version of uniswap you have deployed doesn't have the [`enableFeeAmount`](- https://www.4byte.directory/signatures/?bytes4_signature=8a7c195f) function (V3 and you deployed v2?) or you are calling the wrong contract to enable fees.  This is a solidity and contract issue, not a besu issue.

**Comment by puneet166** [comment]
Hi @shemnon Thanks for your response.

Our main issue is - `block.chainid` solidity function which is used to get chain id is not working in besu chain.
This function smoothly work in etherum mainnet aur testnets.

**Comment by macfarla** [comment]
@puneet166 I think you have the same problem as described here https://github.com/hyperledger/besu/issues/3417#issuecomment-1059759646

**Comment by puneet166** [comment]
@macfarla  not working after added "muirglacierblock": 0 in my network's genesis.

**Comment by puneet166** [comment]
`{
"config": {
"chainId": 9731,
"homesteadBlock": 1,
"eip150Block": 2,
"eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"eip155Block": 2,
"eip158Block": 3,
"muirglacierblock": 0,
"byzantiumBlock": 4,
"constantinopleBlock": 5,
"petersburgBlock": 6,
"blockreward": "20000000000000000",
"ethash": {
      "fixeddifficulty": 5000

}
},
"nonce": "0x42",
"timestamp": "0x5d5cdc87",
"extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
"gasLimit": "0x5B8D80", 
"difficulty": "0x80000",
"mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
"coinbase": "0x0000000000000000000000000000000000000000",
"alloc": {
"0x23a524b442342E833d06E5C556ED47A4E5C19953": {
  "balance": "0x25391EE35A05C54D000000"
},
"0xef9444D0810a445689622A5dc9D3B06c68CE94B4":{
"balance":"0x6C6B935B8BBD400000"
},
"0x0977c6B6B173d3e5275A2E50Ff1D90e9642DFfBd":{
"balance":"0x6C6B935B8BBD400000"
}
},
"number": "0x0",
"gasUsed": "0x0",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}`

@macfarla  Here is my genesis file.

**Comment by shemnon** [comment]
Muir glacier needs to be set to a block number after petersburg.

**Comment by macfarla** [comment]
@elmurci @puneet166 closing this one - assuming the above has resolved your issue :)

**Comment by sorXCode** [comment]
@puneet166 Does adding 
```
"muirglacierblock": 0,
"berlinBlock": 7
```

to your genesis file fix this issue?

**Comment by puneet166** [comment]
Yes It's fixed @sorXCode  @macfarla  Thanks for your feedback on this.

I have another concern - How could increasing mining complexity over running chain ? Please help regarding the same.

**Comment by sorXCode** [comment]
Thanks for the response @puneet166

**Comment by macfarla** [comment]
> I have another concern - How could increasing mining complexity over running chain ? Please help regarding the same.
Please ask your questions in Besu channel in Hyperledger Discord https://discord.com/channels/905194001349627914/938504958909747250
