### ISSUE TITLE
Invalid key field when using getProof API

### ISSUE THREAD

**Issue by JosephK95** [hyperledger/besu#4249]
### Description
When we execute `getProof` API, it returns an array of storage-entry objects as requested. According to the Ethereum API specification, the `key` field in the entry object should conform to `^0x([0-9a-f][0-9a-f]){0,32}$` regex pattern. However, it seems that Besu returns a non-conforming value.
(Specification link: https://github.com/ethereum/execution-apis)

**Expected behavior:** 
<pre>
{ 
  ...
  storageProof: [ { key: '0x2', value: '0x0', ... } ]
}
</pre>

**Actual behavior:**
<pre>
{ 
  ...
  storageProof: [ { key: '2', value: '0x0', ... } ]
}
</pre>

**Frequency:** 
Always

### Versions (Add all that apply)
* Software version: besu/v22.4.4/linux-x86_64/openjdk-java-16
* OS Name & Version: Ubuntu 20.04.4 LTS

**Comment by non-fungible-nelson** [comment]
Hi there - is this bug present on Besu v22.7.0? @fab-10 @daniellehrner is this something we addressed in Hive testing?
