### ISSUE TITLE
genesis file does not match chaindata

### ISSUE THREAD

**Issue by Neoblock8** [hyperledger/besu#4252]
Hi,
  Running private network in Hyperledger-Besu. Node is stopped due to 'genesis file does not match with chaindata'. But we cannot modify the genesis file.
  How to restore blocks from the chain?

**Comment by iamhsk** [comment]
Hi @neoblock8, thank you for opening this GH issue. Have you took a look at this in the docs? https://besu.hyperledger.org/en/stable/HowTo/Troubleshoot/Troubleshooting/#supplied-genesis-block-does-not-match-stored-chain-data
