### ISSUE TITLE
solidity chainID and inline assembly code not working on Hyperledger Besu smart contracts

### ISSUE THREAD

**Issue by sunidhiii** [hyperledger/besu#4281]
When I'm deploying smart contract for Uniswap clone, it is working on every other network except Hyperledger Besu run Blockchain.
Inline assembly code is not working on Hyperledger Besu.

@shemnon @macfarla @ajsutton @MadelineMurray Please look into it.

**Comment by macfarla** [comment]
Without details on the contract and your Besu setup, I would guess that you don't have all the milestones necessary in your genesis file? https://besu.hyperledger.org/en/stable/Reference/Config-Items/?h=milestone#milestone-blocks

**Comment by macfarla** [comment]
Closing this one - assuming you have the same issue as this https://github.com/hyperledger/besu/issues/4247
