### ISSUE TITLE
Losing multiple peers within seconds because of BREACH_OF_PROTOCOL

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#4294]
### Description
While syncing a number of nodes on Goerli and MainnetI noticed that most nodes do lose almost all their peers within a few seconds. The following screenshot was taken from a node that was started from a nightly build from around the 18th of August (besu/v22.7.1-dev-f847ead5/linux-x86_64/openjdk-java-11):
![0EA9234B-F693-4A6F-9CE8-99217A57E4FC.jpeg](https://images.zenhubusercontent.com/5e701925567b4e8945ea7800/85b15fbb-60ed-4765-a6a5-c38d8f4f8cdc)

A number of instances on different nodes have been checked and they all seem to follow the same pattern.
The following is from the logfile from one of the nodes:

`[DEBUG] 2022-08-18 15:15:00.125 [nioEventLoopGroup-3-1] RequestManager - Request ID incorrect (BREACH_OF_PROTOCOL), disconnecting peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 149, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303`

This is always followed by multiple lines of:
`[DEBUG] 2022-08-18 15:15:00.126 [nioEventLoopGroup-3-1] EthProtocolManager - Ignoring message received from unknown peer connection: NettyPeerConnection{nodeId=0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, clientId=Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, caps=eth/66, snap/1}`

And in all cases checked a timeout happened before the BREACH_OF_PROTOCOL:
`[DEBUG] 2022-08-18 15:14:53.365 [EthScheduler-Timer-0] EthPeer - Timed out while waiting for response from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303`

Logfile:
[https://app.zenhub.com/files/206414745/4784e0ca-727f-4bcb-b87b-1a8c92592aac/download](https://app.zenhub.com/files/206414745/4784e0ca-727f-4bcb-b87b-1a8c92592aac/download)

As can be seen in the screenshot this seems to start after some time of starting the sync and it does not seem to happen when the sync has finished (Maybe because CPU usage is very high during syncing?).

The following are the log lines that contain the node ID of the node that is disconnected because of the breach. 
**Note that the last successfull response is logged at 15:14:39, followed by multiple requests:**
`[DEBUG] 2022-08-18 15:14:39.619 [EthScheduler-Services-4 (downloadHeaders)] GetHeadersFromPeerByHashTask - Requesting 200 headers from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:39.689 [nioEventLoopGroup-3-1] AbstractGetHeadersFromPeerTask - Received 200 of 200 headers requested from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303
[DEBUG] 2022-08-18 15:14:40.147 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:40.979 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:41.994 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 330 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:42.351 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:42.864 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:43.382 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:44.003 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:44.599 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:45.622 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:46.284 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:46.904 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:47.591 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:48.364 [EthScheduler-Services-12 (batchDownloadData)] GetNodeDataFromPeerTask - Requesting 384 node data entries from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303.
[DEBUG] 2022-08-18 15:14:53.365 [EthScheduler-Timer-0] EthPeer - Timed out while waiting for response from peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303`

nioEventLoopGroup-1 is the thread that executes responses from that node.
The following shows the last time nioEventLoopGroup-1 shows up in the logs before the BREACH_OF_PROTOCOL:
`[DEBUG] 2022-08-18 15:14:49.149 [nioEventLoopGroup-3-1] GetReceiptsFromPeerTask - Requesting 144 receipts from peer PeerId 0x7ad04fe6eb034945c0a007a86e9a1f7048f1458ecd98c199fb9aa7aad6e4c46d53c5101406037421f81092e8ad700f4667b6b5479072602f4b38a180544aba5f, reputation PeerReputation 150, validated? true, disconnected? false, client: Geth/v1.10.21-stable-67109427/linux-amd64/go1.18.4, connection 2034465280, enode enode://7ad04fe6eb034945c0a007a86e9a1f7048f1458ecd98c199fb9aa7aad6e4c46d53c5101406037421f81092e8ad700f4667b6b5479072602f4b38a180544aba5f@107.23.195.27:0.
[DEBUG] 2022-08-18 15:15:00.125 [nioEventLoopGroup-3-1] RequestManager - Request ID incorrect (BREACH_OF_PROTOCOL), disconnecting peer PeerId 0x3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e, reputation PeerReputation 149, validated? true, disconnected? false, client: Geth/v1.10.21-stable-55d8eac8/linux-amd64/go1.18, connection 539126146, enode enode://3f88068013a17437b7fae2f155894a33dd94beb55b9d82c667123c6431d4967b52a9ce155f0c44dd2dcb405cbef5addcc97ffedc5bc6630e68e4b548d4b01a9e@44.198.36.250:30303`

**Note that the time between these log lines is more than 10 seconds!**

**Comment by macfarla** [comment]
@jflo are you looking into this one? it's in our backlog but assigned to you :)

**Comment by jflo** [comment]
@macfarla unassigned, happy to relinquish

**Comment by non-fungible-nelson** [comment]
@macfarla @jflo - if we can get this prioritized it would be great. I think another collaboration could be useful as well, not sure this can make it into 22.7.2, but would help with user sync challenges.

**Comment by macfarla** [comment]
We have not observed this recently. Next steps:
* check nightly nodes
* run up some new nodes - different machine types? try with less CPU?

**Comment by macfarla** [comment]
nothing of note on the nightly nodes (but also they were still running 22.7.1-SNAPSHOT - have updated them now)

**Comment by macfarla** [comment]
started some new nodes on t2.large and t3.large (by default we're using t3.xlarge) and it does look like this may have an effect on peering
![Screen Shot 2022-09-07 at 5.45.34 pm.png](https://images.zenhubusercontent.com/5e45df693f0e60cdfc2eb96e/1b7d134d-38fc-4dea-9e8b-06aed7d0c7af)

**Comment by macfarla** [comment]
The t2.large has a lot more volatility. Seems to have a lot of timeouts in the logs (need to turn DEBUG logging)
![Screen Shot 2022-09-07 at 7.02.12 pm.png](https://images.zenhubusercontent.com/5e45df693f0e60cdfc2eb96e/cc7c0c68-2c28-431a-8d3c-3c1acc581f45)

**Comment by macfarla** [comment]
`2022-09-07 09:06:14.530+00:00 | nioEventLoopGroup-3-4 | DEBUG | RlpxAgent | Failed to connect to peer 0x27c87a33889a08524bbe66b949ee68524eae21163586f2514eaa55ba174cc982ff2d55b3368b3c848ee00b4efb124a496b4988339162da9af1fb54dedf44f7fc: java
.util.concurrent.TimeoutException: Timed out waiting to establish connection with peer: 0x27c87a33889a08524bbe66b949ee68524eae21163586f2514eaa55ba174cc982ff2d55b3368b3c848ee00b4efb124a496b4988339162da9af1fb54dedf44f7fc
[DEBUG] 2022-09-07 09:06:14.530 [nioEventLoopGroup-3-4] RlpxAgent - Failed to connect to peer 0x27c87a33889a08524bbe66b949ee68524eae21163586f2514eaa55ba174cc982ff2d55b3368b3c848ee00b4efb124a496b4988339162da9af1fb54dedf44f7fc: java.util.co
ncurrent.TimeoutException: Timed out waiting to establish connection with peer: 0x27c87a33889a08524bbe66b949ee68524eae21163586f2514eaa55ba174cc982ff2d55b3368b3c848ee00b4efb124a496b4988339162da9af1fb54dedf44f7fc
2022-09-07 09:06:14.740+00:00 | nioEventLoopGroup-3-3 | DEBUG | RlpxAgent | Inbound connection established with 0xa8ece5145178773e4ecc8845867c25a0c8590427f78d9e72c29c13d6490a08645cedee1690aec669e4c4e16725ee325a19103c63d30a0752618ececd3039
a629`

**Comment by iamhsk** [comment]
After observing a few nodes for several days, we didn't see any breach of protocol error. Closing this.
