### ISSUE TITLE
Worldstate Sync Does Not Resume from where it left off following a restart 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4301]
### Description
As a user, I would like for my worldstate download to resume from where it left off if my node restarts during sync. This will give me a better UX if I have to restart my node for sync related (or unrelated) issues. 

### Acceptance Criteria
* Worldstate sync can continue across a restart. 

### Steps to Reproduce (Bug)
1. Begin sync and restart the node
2. Stop node 
3. Restart node and have world state sync start from scratch

**Expected behavior:** [What you expect to happen]
1. Begin sync and restart the node 
2. Stop the node 
3. Restart node and have world start sync start from where it left off 

**Frequency:** [What percentage of the time does it occur?]
All the time 
### Versions (Add all that apply)
* Software version: 22.7.1

**Comment by terahertz5k** [comment]
Bump for this.

My worldstate was already completed, but my client was still syncing (importing chain segments). I restarted besu to try some java heap size options and noticed the worldstate started from 0.0%.

**Comment by EdwardPrentice** [comment]
+1

As a relatively new user of Besu I have restarted the service doing minor, or none, configuration changes not realising this would incur a massive downtime penalty.


Suggestion: Additional/clearer logs that communicate that the node is healthy, such that non-expert Besu users don't feel the need to turn it off and on again.

**Comment by EdwardPrentice** [comment]
Affects 22.7.2 as well

**Comment by felix-halim** [comment]
What is the ETA for this fix? Please make this a priority.

I cannot afford to wait 1-2 days to sync the world state from 0 whenever I restart Besu.

**Comment by non-fungible-nelson** [comment]
This is implemented on 22.10.0 - @Felix-halim
