### ISSUE TITLE
Tracing and filtering prohibited transactions

### ISSUE THREAD

**Issue by YoKawaiiK** [hyperledger/besu#4307]
Hello!

I ran into a problem: I need to restrict the blockchain from users who should not be able to deploy contracts on the network, but only use those contracts that were deployed from a specific address.

Found that Besu has an API for [tracing and filtering](https://besu.hyperledger.org/en/22.7.0/HowTo/Troubleshoot/Trace-Transactions/#transaction-trace-filtering-apis) (well, or something like that). However, I don't understand how it can be used. I have to specify somewhere in the configuration files what the blockchain should reject, but how do I do it?

At the same time, it is desirable that the method of solving the problem does not involve paying for gas in the network (now I have a Besu configuration that does not require paying for gas).

**Expected behavior:** 
When attempting to deploy a contract from a regular user address (without privileges), the transaction must be rolled back.

**Actual behavior:** 
Any user can deploy a contract (including those who do not have ether).

### Versions 
* Software version: hyperledger/besu:22.7.0
* Java version: 18.0.2.1
* Docker Version: 4.11.1

**Comment by macfarla** [comment]
Hi!
The TRACE APIs are only for getting trace-level details of existing transactions, this doesn't enable you to do any restricting or rejecting of activity. 

It sounds like what you want (privileges) might be role based access - this can be implemented at the application layer eg https://docs.openzeppelin.com/contracts/2.x/access-control#role-based-access-control
