### ISSUE TITLE
Besu native crash in DB access

### ISSUE THREAD

**Issue by kirillp** [hyperledger/besu#4314]
I can observe besu crash 100% reproducible.

besu is latest besu-22.7.1
java version is openjdk-18.0.2
Host: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz, 6 cores, 15G,  Windows 11 , 64 bit Build 22621 (10.0.22621.317)

[besu.22.7.1.main.checkpoint.log.txt](https://github.com/hyperledger/besu/files/9427341/besu.22.7.1.main.checkpoint.log.txt)
[besu_main_checkpnt.cmd.txt](https://github.com/hyperledger/besu/files/9427356/besu_main_checkpnt.cmd.txt)
[hs_err_pid10300.log](https://github.com/hyperledger/besu/files/9427342/hs_err_pid10300.log)

Might it be a DB corruption ?

**Comment by kirillp** [comment]
commandline:
```
rem set pass=--engine-jwt-secret=C:/eth2D/jwt.secret.hex 
rem set rpc=--rpc-http-enabled

set port=--engine-rpc-http-port=9551
set p2pport=--p2p-port=33333
set api=--rpc-http-api=ETH,NET,WEB3,ADMIN

set besupath="C:/eth2D/besu-22.7.1"

title "Besu mainnet X_CHECKPOINT, data C:\eth2D\basu-main"

%JAVA_HOME%/bin/java -cp %besupath%/lib/* org.hyperledger.besu.Besu ^
  --sync-mode=X_CHECKPOINT --data-storage-format=BONSAI  --data-path C:\eth2D\basu-main ^
 %p2pport% %port% %pass% %rpc% %api% >> besu.22.7.1.main.checkpoint.log  2>&1

```

**Comment by ahamlat** [comment]
@kirillp : The JVM crash was in a GC thread, and I can see a new patch 18.0.2.1 https://jdk.java.net/18/release-notes that resolves some JVM crashes. The patch is related to C2 JIT compiler, but it may have an impact on your case.
Could you upgrade your Java version and let us know if you still have the same crashes ?

**Comment by kirillp** [comment]
I have my java upgraded 
and the DB was moved to another system and then was finally synced 
  so it is not in a reproducible state now

**Comment by non-fungible-nelson** [comment]
Closing as an issue with the JVM.
