### ISSUE TITLE
Do not ban (static) peers for late responses

### ISSUE THREAD

**Issue by pietjepuk2** [hyperledger/besu#4320]
## Usecase
(same backstory as #3801) I want to sync my Besu node against a single local (Geth) node, and not connect to the wider internet. The Besu node is in the `trusted-nodes.json` file of Geth, and the Geth node is in the `static-nodes.json` of Besu. 

For completeness sake, my command line is `./besu --data-storage-format=bonsai --p2p-port=30303 --sync-mode=FAST --fast-sync-min-peers=1 --discovery-enabled=false` (same behavior with `X_SNAP`)

## Issue
(Possibly related to #4294)
When using the command line above, I eventually get a situation where Geth takes _slightly_ too long to respond, e.g. 5.1 seconds. Besu has already considered the request to be timed out, and severely punishes the peer by disconnecting right away with `BREACH_OF_PROTOCOL`. It also never reconnects to it (which is unlike Geth/Nethermind, at least for static nodes).

The offending bit of code is https://github.com/hyperledger/besu/blob/113bd54c6b0ff748a3ed23f2e89fa31a4cb73795/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/RequestManager.java#L70-L93

I reproduced this issue on Besu/Geth/Nethermind by slightly [modifying Geth ](https://github.com/ethereum/go-ethereum/compare/master...pietjepuk2:go-ethereum:sometimes-delay-response-trusted-nodes) to delay the response to the Nth GetHeaders request.

## Other clients behavior
- Geth doesn't disconnect on late replies. It does requests sequentially it seems, and just waits with sending a new request until it gets a response (waits more than 10 seconds at least). If I delay the response with a minute, Geth just disconnects the peer after ~40-50 seconds before reconnecting to it a few seconds later.
- Nethermind is a bit weird in that it continuously disconnects and reconnects every minute or so. It doesn't punish a late response (>5 seconds), but either way always reconnects.
- (Not entirely sure). Late responses were probably not punished by Besu with Eth65 (i.e. no `RequestId`). I couldn't quite understand the code (or test it), but my gut feeling is that it just skipped processing the late response or handled it anyway.

## Suggested solutions
1. Just `LOG.debug("Request ID incorrect (BREACH_OF_PROTOCOL), disconnecting peer {}", peer);` but don't disconnect the peer. Maybe decrease peer reputation.
2. Keep track of timed-out request ids, and if response is in one of them -> ignore. If it's not -> disconnect.

## Sidenotes
- Even after disconnecting, whether it be "BREACH_OF_PROTOCOL" or because the reputation dropped too low, I would expect Besu to reconnect to static nodes regardless. Other clients seem to do so anyway.
- I have at least one logging of Besu receiving a response _barely_ within 5 seconds (in `RequestManager`), but `AbstractPeerRequestTask` still timing out on it ~200 ms later. The processing or delay on Besu's side surely shouldn't be part of the 5 seconds timeout window?

**Comment by non-fungible-nelson** [comment]
Thanks for this suggestion - this is a great catch here. We likely will not be able to prioritize this for our next release but will look to fix as soon as we can after the Merge. We will also look for additional mitigations in the short term. If you have any experience with Java and would like help writing and implementing a change, let us know.

**Comment by pietjepuk2** [comment]
I have been playing around today a bit, and have two small change sets. Will make a PR soon to get some feedback :)
