### ISSUE TITLE
Mining issue

### ISSUE THREAD

**Issue by puneet166** [hyperledger/besu#4339]
Please help regarding this issue - 

I started node with ""--miner-coinbase="0xaA......" After the node is running normally , the coinbase becomes "0x1cffe205e9....." 
i puted my address as minner adddress for mining rewards but i have seen another miner address when my node is mining / producing a block.

**Comment by non-fungible-nelson** [comment]
Hi there - what network is this on? Closing this issue as stale, but please re-open if there are still issues.
