### ISSUE TITLE
Sync prometheus metric flip/flops

### ISSUE THREAD

**Issue by schonex** [hyperledger/besu#4341]
### Description
As a user, I want ``besu_synchronizer_in_sync`` to be a realiable metric for whether or not my client is in sync

### Steps to Reproduce (Bug)
1. Utilize and monitor with prometheus ``besu_synchronizer_in_sync``
2. Set an alert for anytime it's below 0.9
3. Notice that periodically it'll hit that alert.  It currently seems to be that the client is indeed in sync so I assume those are errorneous.

**Expected behavior:** Not to go below 1.0 if it's in sync with head.

### Versions (Add all that apply)
* Software version: ``22.7.1``

**Comment by non-fungible-nelson** [comment]
Closing for tracking this issue with #2253
