### ISSUE TITLE
org.hyperledger.besu.Besu could not be found.

### ISSUE THREAD

**Issue by cvsolfari** [hyperledger/besu#4348]
I am trying to spin up an ethereum node using Besu software so that I can eventually stake some Eth. I have a RP4 with a 1 TB ssd and am trying first with the Goerli network since I know that I need at least a 2 TB SSD for an actual node.

I can not get the Besu software to run properly after working through installing Java and some other needed software. When I try to run Besu, I receive this message:

besu --config-file config-besu-goerli.toml
Error: Could not find or load main class org.hyperledger.besu.Besu
Caused by: java.lang.ClassNotFoundException: org.hyperledger.besu.Besu

From my reading that does not specifically have the answer, I inferred that it could be a configuration issue with Java and Besu. Or it could be that Besu needs to be compiled since I downloaded the 22.7.0 package and installed it through the CLI.

Any help is greatly appreciated as I work to increase my knowledge about Eth nodes!

**Comment by agg505** [comment]
I can get Besu started by running "./bin/besu" in root directory of extracted file downloaded from https://hyperledger.jfrog.io/ui/native/besu-binaries/besu/22.7.1/besu-22.7.1.tar.gz.
You may have a try.

**Comment by cvsolfari** [comment]
Thank you Vic! That worked and I was able to reproduce my error even with 22.7.1 because I didn't include './bin' in my CLI. My linux skills are rusty, but I thought that I had the /etc/environment file updated appropriately. Nonetheless, I am good to go now.
