### ISSUE TITLE
ERROR | ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_exchangeTransitionConfigurationV1

### ISSUE THREAD

**Issue by Chozowarrior** [hyperledger/besu#4354]
When turning on TRACE the ERROR " failed to exec consensus method engine_exchangeTransitionConfigurationV1" It is unclear whether this will result into merge issues to me. See ther error below:

sep 07 14:27:23 ssa-Blade besu[207075]: 2022-09-07 14:27:23.028+02:00 | vert.x-worker-thread-0 | DEBUG | ExecutionEngineJsonRpcMethod | execution engine JSON-RPC request engine_exchangeTransitionConfigurationV1 [{terminalTotalDifficulty=0xc70d808a128d7380000, terminalBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, terminalBlockNumber=0x0}]
sep 07 14:27:23 ssa-Blade besu[207075]: 2022-09-07 14:27:23.028+02:00 | vert.x-eventloop-thread-17 | ERROR | ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_exchangeTransitionConfigurationV1
sep 07 14:27:23 ssa-Blade besu[207075]: io.vertx.core.json.EncodeException: Failed to encode as JSON: Direct self-reference leading to cycle (through reference chain: org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.EngineExchangeTransitionConfigurationParameter["terminalTotalDifficulty"]->org.hyperledger.besu.ethereum.core.Difficulty["asBytes32"])
sep 07 14:27:23 ssa-Blade besu[207075]:         at io.vertx.core.json.jackson.DatabindCodec.toString(DatabindCodec.java:163)
sep 07 14:27:23 ssa-Blade besu[207075]:         at io.vertx.core.json.Json.encodePrettily(Json.java:71)
sep 07 14:27:23 ssa-Blade besu[207075]:         at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineExchangeTransitionConfiguration.lambda$syncResponse$1(EngineExchangeTransitionConfiguration.java:84)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
sep 07 14:27:23 ssa-Blade besu[207075]:         at org.hyperledger.besu.util.Slf4jLambdaHelper.traceLambda(Slf4jLambdaHelper.java:54)
sep 07 14:27:23 ssa-Blade besu[207075]:         at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineExchangeTransitionConfiguration.syncResponse(EngineExchangeTransitionConfiguration.java:81)
sep 07 14:27:23 ssa-Blade besu[207075]:         at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:67)
sep 07 14:27:23 ssa-Blade besu[207075]:         at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
sep 07 14:27:23 ssa-Blade besu[207075]:         at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
sep 07 14:27:23 ssa-Blade besu[207075]:         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
sep 07 14:27:23 ssa-Blade besu[207075]:         at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
sep 07 14:27:23 ssa-Blade besu[207075]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
sep 07 14:27:23 ssa-Blade besu[207075]:         at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by daniellehrner** [comment]
Thank you for submitting the issue! I've created a PR with a fix for it.

**Comment by non-fungible-nelson** [comment]
@daniellehrner following up so we can include this if the PR is ready.
