### ISSUE TITLE
Besu attempts to import the same block twice 

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#4360]
### Description
As part of #4350, we fixed log message about importing a block appearing twice. We know Besu does not actually import block twice but we need to investigate why Besu attempts to import the same block twice and find a mitigation for it.  

### Versions 
* Software version: v.22.7.1

### Note
`MainnetBlockImporter.importBlock` checks if the block is already in the blockchain and will return true if it is already imported.

```
public synchronized boolean importBlock(
      final ProtocolContext context,
      final Block block,
      final HeaderValidationMode headerValidationMode,
      final HeaderValidationMode ommerValidationMode) {
    if (context.getBlockchain().contains(block.getHash())) {
      return true;
    }
...
```

**Comment by macfarla** [comment]
This is no longer an issue for mainnet post-merge. And even for non-mainnet networks, it can be ignored since the block is not actually imported twice, just logged twice.
