### ISSUE TITLE
Error When I try to fast syncsync 

### ISSUE THREAD

**Issue by alptolga** [hyperledger/besu#4369]
### Here is the command that I use:
**sudo ./besu --network=classic --static-nodes-file=static-nodes.json --fast-sync-min-peers=5 --permissions-nodes-contract-version=2 --sync-mode=fast --nat-method=UPNP**

### I got these errors:
**2022-09-08 20:24:58.419+03:00 | EthScheduler-Services-2 (requestLoadLocalData) | ERROR | FastWorldStateDownloadProcess | Pipeline failed
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: block checksum mismatch: stored = 4257919811, computed = 2252973619, type = 1  in /home/tt/Downloads/besu-22.7.1/database/000125.sst offset 66369270 size 21580
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:178)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:64)
	at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.get(SegmentedKeyValueStorageAdapter.java:50)
	at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage.getTrieNode(WorldStateKeyValueStorage.java:75)
	at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage.getAccountStateTrieNode(WorldStateKeyValueStorage.java:62)
	at org.hyperledger.besu.ethereum.eth.sync.fastsync.worldstate.AccountTrieNodeDataRequest.lambda$getExistingData$1(AccountTrieNodeDataRequest.java:50)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.hyperledger.besu.ethereum.eth.sync.fastsync.worldstate.AccountTrieNodeDataRequest.getExistingData(AccountTrieNodeDataRequest.java:47)
	at org.hyperledger.besu.ethereum.eth.sync.fastsync.worldstate.LoadLocalDataStep.loadLocalData(LoadLocalDataStep.java:47)
	at org.hyperledger.besu.ethereum.eth.sync.fastsync.worldstate.FastWorldStateDownloadProcess$Builder.lambda$build$1(FastWorldStateDownloadProcess.java:191)
	at org.hyperledger.besu.services.pipeline.FlatMapProcessor.processNextInput(FlatMapProcessor.java:32)
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.rocksdb.RocksDBException: block checksum mismatch: stored = 4257919811, computed = 2252973619, type = 1  in /home/tt/Downloads/besu-22.7.1/database/000125.sst offset 66369270 size 21580
	at org.rocksdb.RocksDB.get(Native Method)
	at org.rocksdb.RocksDB.get(RocksDB.java:2084)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:176)
	... 17 more**

### **Software version:
besu 22.7.1

### Java version:
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu118.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu118.04, mixed mode, sharing)

### OS Name & Version:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
### 
Kernel Version:
Linux srv 5.6.17-050617-generic #202006071230 SMP Sun Jun 7 12:35:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DRIgnazGortngschirl** [comment]
Still persists in 22.10.3 and 23.1.0-beta

```
besu_1           | 2023-01-06 09:01:31.927+00:00 | EthScheduler-Timer-0 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
besu_1           | 2023-01-06 09:01:31.930+00:00 | EthScheduler-Timer-0 | INFO  | PivotBlockConfirmer | Confirm pivot block 16685615 with at least 5 peers.
besu_1           | 2023-01-06 09:01:31.960+00:00 | nioEventLoopGroup-3-9 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 16685615: 0xdc44f25846bcbd1131286345bb0bf09451da304736fb691b9b8355480ce2cbe3
besu_1           | 2023-01-06 09:01:31.963+00:00 | nioEventLoopGroup-3-6 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 16685615: 0xdc44f25846bcbd1131286345bb0bf09451da304736fb691b9b8355480ce2cbe3
besu_1           | 2023-01-06 09:01:32.048+00:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 16685615: 0xdc44f25846bcbd1131286345bb0bf09451da304736fb691b9b8355480ce2cbe3
besu_1           | 2023-01-06 09:01:32.056+00:00 | nioEventLoopGroup-3-5 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 16685615: 0xdc44f25846bcbd1131286345bb0bf09451da304736fb691b9b8355480ce2cbe3
besu_1           | 2023-01-06 09:01:32.062+00:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 16685615: 0xdc44f25846bcbd1131286345bb0bf09451da304736fb691b9b8355480ce2cbe3
besu_1           | 2023-01-06 09:01:32.064+00:00 | nioEventLoopGroup-3-4 | INFO  | FastWorldStateDownloader | Begin downloading world state from peers for block 16685615 (0xdc44f25846bcbd1131286345bb0bf09451da304736fb691b9b8355480ce2cbe3). State root 0x86a160bc487aa9585127920843804a3a0e6d5ebacb51dcbf57607810709ff80e
besu_1           | 2023-01-06 09:02:32.066+00:00 | EthScheduler-Services-21 (requestCompleteTask) | INFO  | CompleteTaskStep | Downloaded 1053217 world state nodes. At least 47755 nodes remaining.
besu_1           | 2023-01-06 09:03:06.006+00:00 | EthScheduler-Services-17 (requestLoadLocalData) | ERROR | FastWorldStateDownloadProcess | Pipeline failed
besu_1           | org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
besu_1           |      at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:373)
besu_1           |      at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.java:49)
besu_1           |      at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter$1.commit(SegmentedKeyValueStorageAdapter.java:119)
besu_1           |      at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage$Updater.commit(WorldStateKeyValueStorage.java:211)
besu_1           |      at org.hyperledger.besu.ethereum.eth.sync.fastsync.worldstate.LoadLocalDataStep.loadLocalData(LoadLocalDataStep.java:54)
besu_1           |      at org.hyperledger.besu.ethereum.eth.sync.fastsync.worldstate.FastWorldStateDownloadProcess$Builder.lambda$build$1(FastWorldStateDownloadProcess.java:191)
besu_1           |      at org.hyperledger.besu.services.pipeline.FlatMapProcessor.processNextInput(FlatMapProcessor.java:32)
besu_1           |      at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)
besu_1           |      at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
besu_1           |      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
besu_1           |      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
besu_1           |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
besu_1           |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
besu_1           |      at java.base/java.lang.Thread.run(Thread.java:829)
besu_1           | Caused by: org.rocksdb.RocksDBException: Busy
besu_1           |      at org.rocksdb.Transaction.commit(Native Method)
besu_1           |      at org.rocksdb.Transaction.commit(Transaction.java:208)
besu_1           |      at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:367)
besu_1           |      ... 13 more
```

My config 

```
    environment:
      - BESU_NETWORK=classic
      - BESU_DATA_PATH=/var/lib/besu/
      - BESU_MAX_PEERS=1000
      - BESU_METRICS_ENABLED=true
      - BESU_METRICS_HOST=0.0.0.0
      - BESU_METRICS_PORT=9545
      - BESU_HOST_ALLOWLIST=*
      - BESU_RPC_HTTP_ENABLED=true
      - BESU_RPC_HTTP_HOST=0.0.0.0
      - BESU_RPC_HTTP_PORT=8545
      - BESU_RPC_HTTP_CORS_ORIGINS=https://explorer-expedition.etc-network.info,https://chainlist.org,https://explorer-alethio.etc-network.info,https://explorer-blockscout.etc-network.info
      - BESU_RPC_HTTP_API=ETH,NET,WEB3,ADMIN
      - BESU_RPC_HTTP_AUTHENTICATION_ENABLED=false
````

**Comment by non-fungible-nelson** [comment]
@diega - any insight here? Did we break something on our side

**Comment by gfukushima** [comment]
Closing as it's been fixed by https://github.com/hyperledger/besu/pull/5328

**Comment by Shednandezstore** [comment]
Fixed the problem
