### ISSUE TITLE
Error: Argument must be positive

### ISSUE THREAD

**Issue by estensen** [hyperledger/besu#4384]
Mainnet
v22.7.2
Checkpoint sync
Bonsai
Paired with Lighthouse

```
2022-09-12 16:32:37.186+02:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #15,521,359 / 393 tx / 0 om / 30,016,771 (100.0%) gas / (0x79cfec6a1f1ebd1c9c68d5560e5b785cf10461a9b5af7d5fe093accba7319072) in 2.559s. Peers: 78
2022-09-12 16:33:15.802+02:00 | nioEventLoopGroup-3-9 | ERROR | Subscribers | Error in callback: Argument must be positive
2022-09-12 16:33:24.191+02:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #15,521,360 / 263 tx / 0 om / 18,855,084 (62.9%) gas / (0x920ef176060223780ae72d6381194127438308cb0a84a346de959862c35e14bc) in 1.751s. Peers: 77
```

**Comment by macfarla** [comment]
Thanks for reporting this @estensen - this one sounds like a "this should never happen" - will investigate

**Comment by hisnamesstake** [comment]
I am getting the same error roughly every 5 minutes:
v22.7.2
Snap sync
Bonsai
Paired with Lighthouse

```
Sep 14 14:33:06 hisnamesstake besu[770]: 2022-09-14 14:33:06.666+00:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #15,533,451 / 90 tx / 0 om / 9,426,199 (31.2%) gas / (0x31de584313d0e421ff841f48fa426d1cd1ae96b0cd6077c9b68271f22bdbf32f) in 0.779s. Peers: 25
Sep 14 14:33:36 hisnamesstake besu[770]: 2022-09-14 14:33:36.635+00:00 | nioEventLoopGroup-3-1 | ERROR | Subscribers | Error in callback: Argument must be positive
Sep 14 14:33:48 hisnamesstake besu[770]: 2022-09-14 14:33:48.748+00:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #15,533,452 / 345 tx / 0 om / 30,131,567 (99.9%) gas / (0x9431f035f140f5292ebd0d3275a807f728fe273eb35e85c5a3f24d317271f93c) in 3.251s. Peers: 25
```

**Comment by macfarla** [comment]
Hi - in 22.7.2 we changed the logging of this message - so the stacktrace goes to DEBUG level log as per https://github.com/hyperledger/besu/pull/4334 - it's usually not something that will cause a problem with Besu operations

We suspect it's to do with RLP decoding incoming messages - if you're curious, you could enable DEBUG logging for 5 minutes and share the stack trace with us. If you have ADMIN RPC API enabled you can do this without restarting your node as per https://besu.hyperledger.org/en/stable/public-networks/reference/api/?h=admin+change#admin_changeloglevel - otherwise you need to restart your node to enable the ADMIN methods

**Comment by macfarla** [comment]
@estensen any further updates on this?

**Comment by estensen** [comment]
Debug is producing a lot of logs 😅 
Is there an easy way to only log debug for the related code?

**Comment by macfarla** [comment]
Yeah you can use a custom log4j config file as per https://besu.hyperledger.org/en/stable/public-networks/how-to/monitor/logging/?h=log4j#advanced-logging
There's an example here that tunes logging for various packages https://github.com/lucassaldanha/besu-local-nodes/blob/master/config/besu/log4j.xml

**Comment by macfarla** [comment]
Are you using latest lighthouse version? Also Besu 22.7.5 ?

**Comment by macfarla** [comment]
@estensen @hisnamesstake are you still getting this error?

**Comment by estensen** [comment]
haven't seen this in a while, but aren't paying attention on a daily anymore
Feel free to close if you think it has been fixed

**Comment by macfarla** [comment]
we can reopen if the problem recurs!
