### ISSUE TITLE
increasing mining complexity over running chain 

### ISSUE THREAD

**Issue by puneet166** [hyperledger/besu#4389]
HI @macfarla @shemnon @matkt 

Is any way to increasing mining complexity over running besu chain?

**Comment by non-fungible-nelson** [comment]
@diega any insight?

**Comment by diega** [comment]
@puneet166 what do you mean by _increase mining complexity_? the mining difficulty is defined by the network to keep block time in ~12 seconds in average, there is nothing within the clients that can be done to change that

**Comment by macfarla** [comment]
PoW is now deprecated so we won't be adding features to it
