### ISSUE TITLE
Add RPC method to the log message with the stack trace

### ISSUE THREAD

**Issue by Gabriel-Trintinalia** [hyperledger/besu#4405]
### Description
As a Besu user, I want to see the RPC method to the log message so that it can help me to debug exceptions. 

**Expected behaviour:** 
RPC Method name is logged with the stack trace

**Actual behaviour:** 
Only the stack trace is logged

**Comment by Gabriel-Trintinalia** [comment]
Linked to https://github.com/hyperledger/besu/issues/4398

**Comment by siladu** [comment]
Similar to https://github.com/hyperledger/besu/pull/4395
