### ISSUE TITLE
Memory leak: vert.x-eventloop-thread-3 | WARN  | VertxPeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonded, enode=enode://1caf92ce1a229777c39b01683837de8d404f4cd1ddf241d7337e7eca6966eafd6fcf6286e6f4b70e76e5539fde87bfdf3180a4cc48f025f53f957a7d02f734d8@181.214.147.180:30300, firstDiscovered=1664050732022, lastContacted=1664050737023, lastSeen=1664050733439} failed, packet: 0x9d8a00856462ac78e05b2964d06d5bf47a955220f3f3aed5d2cfaf1cf22eb40433e92ce8c9f6e25d593623563dfd1511356f91ef2d523050e3164559800e43a07f03f60ed4fb689f7d4084a3208da2907fb8242be2e8bd88faf03b9264919d4d0003f847b8404e7f723bd75f1ab694f792e3ce2595680c30f16607837287ba2c90e6f2a7826ea0fcd7903b3276e1caac1ba5562504b6a5b60bcafdfb93fc6a913a7f50f3b9ea84632f72ba, stacktrace: io.netty.channel.StacklessClosedChannelException

### ISSUE THREAD

**Issue by Chozowarrior** [hyperledger/besu#4437]
vert.x-eventloop-thread-3 | WARN  | VertxPeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonded, enode=enode://1caf92ce1a229777c39b01683837de8d404f4cd1ddf241d7337e7eca6966eafd6fcf6286e6f4b70e76e5539fde87bfdf3180a4cc48f025f53f957a7d02f734d8@181.214.147.180:30300, firstDiscovered=1664050732022, lastContacted=1664050737023, lastSeen=1664050733439} failed, packet: 0x9d8a00856462ac78e05b2964d06d5bf47a955220f3f3aed5d2cfaf1cf22eb40433e92ce8c9f6e25d593623563dfd1511356f91ef2d523050e3164559800e43a07f03f60ed4fb689f7d4084a3208da2907fb8242be2e8bd88faf03b9264919d4d0003f847b8404e7f723bd75f1ab694f792e3ce2595680c30f16607837287ba2c90e6f2a7826ea0fcd7903b3276e1caac1ba5562504b6a5b60bcafdfb93fc6a913a7f50f3b9ea84632f72ba, stacktrace: io.netty.channel.StacklessClosedChannelException

### Description
After updating to 22.7.3 got the message above with failed attenstations on the beaconchain.
![2022-09-24 23_15_41-besu 2 7 3png](https://user-images.githubusercontent.com/43718356/192119363-ff72f165-9b65-4ab4-a6bd-dd00a750a736.png)

**Comment by Chozowarrior** [comment]
After restarting the client ran for a little over 24 hours after going into the related error attached.
![2022-09-26 06_22_46-beacon@ssa-Blade_ ~](https://user-images.githubusercontent.com/43718356/192214747-c239be85-a1d4-4713-9b5c-f8f75400b990.png)

**Comment by b-m-f** [comment]
There seem to be memory leaks. As a shortterm quickfix simply restart the client every 12 hours via cron jobs. D

**Comment by Chozowarrior** [comment]
Alright thank you

**Comment by Chozowarrior** [comment]
I think the Lodestar validator 1.0.0 had a memory leak. I just updated 1.1.0. Issue probably not on the Besu side. WIll update this issue accordingly tomorrow.

**Comment by Chozowarrior** [comment]
resolved with 22.7.4
