### ISSUE TITLE
Besu 22.7.4 created 2 blocks with 5-8% gas utilization

### ISSUE THREAD

**Issue by nhlroyrocks** [hyperledger/besu#4460]
### Description
As an validator, I want besu to create blocks at least in the ballpark of 50% full so that block space is not wasted and greater transaction fees may be collected. 

### Acceptance Criteria
produce blocks with 50-100% gas utilization

### Steps to Reproduce (Bug)
1. propose a block running besu execution client
    a. [Nearly empty block](https://etherscan.io/block/15637228)
    b. [Another nearly empty block within 12 hours of the first](https://etherscan.io/block/15640450)

**Expected behavior:** [What you expect to happen]
fuller blocks like the ones before and after my blocks.
before:  https://etherscan.io/block/15637227
   after:  https://etherscan.io/block/15637229
before:  https://etherscan.io/block/15640449
   after:  https://etherscan.io/block/15640451

**Actual behavior:** [What actually happens]
 1. [Nearly empty block](https://etherscan.io/block/15637228)
 2. [Another nearly empty block within 12 hours of the first](https://etherscan.io/block/15640450)
 
**Frequency:** [What percentage of the time does it occur?]
100% 2/2

### Versions (Add all that apply)
* Software version: besu/v22.7.4/linux-x86_64/openjdk-java-11

* Java version: 
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

* OS Name & Version: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 
* Kernel Version: Linux ogserver 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* 

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
[Unit]
Description=Besu Execution Client (Mainnet)
Wants=network-online.target
After=network-online.target
[Service]
User=besu
Group=besu
Type=simple
Restart=always
RestartSec=5
Environment="JAVA_OPTS=-Xmx8g"
ExecStart=/usr/local/bin/besu/bin/besu \
   --network=mainnet \
  --sync-mode=X_SNAP \
  --data-path=/var/lib/besu \
  --data-storage-format=BONSAI \
  --engine-jwt-secret=/var/lib/jwtsecret/jwt.hex
[Install]
WantedBy=multi-user.target

* System info - 
32 GB RAM
Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

**Comment by fab-10** [comment]
Release 22.10.0 has a first improvements that result in bigger blocks, please report your exeperience.
We are currently monitoring and working on further improvements.

**Comment by ajsutton** [comment]
Can confirm that we're consistently seeing full blocks now.  Important note that EIP1559 targets an average of 50% full blocks. There can be variation around that so it's not unexpected to have some blocks with block 50% utilisation (the baseFee will then be reduced to allow lower priced transactions in and increase demand for block space), it just averages 50% over the long term.

Since upgrading to 22.10.1 our teku nodes are seeing a range of 49%-95% full blocks which is significantly better than expected. I'd expect to see the average drop to around 50% over a longer period of time though.
