### ISSUE TITLE
Besu is failing some tests, please dedicate a person to work on this with me

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#4461]
Since besu has implemented test RPC it is a part of test stats program: http://retesteth.ethdevops.io/
Besu runs fine, but many tests are still red and I am trying to reach someone to work on fixing this from the besu team.

Please contact 
telegram: @wdimitry 

List of failing tests
```
info:[33m (stTransactionTest/HighGasPrice, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)[0m
info:[33m (stTransactionTest/ValueOverflow, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)[0m
info:[33m (stExample/accessListExample, fork: EIP150, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`)[0m
info:[33m (stExample/basefeeExample, fork: EIP150, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`)[0m
info:[33m (stExample/eip1559, fork: EIP150, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`)[0m

info:[33m (bcBlockGasLimitTest/GasUsedHigherThanBlockGasLimitButNotWithRefundsSuicideFirst_London, fork: London, block: 0)[0m
info:[33m (bcStateTests/TransactionNonceCheck2_London, fork: London, block: 0)[0m
info:[33m (bcEIP1559/feeCap_London, fork: London, block: 0)[0m
info:[33m (bcBerlinToLondon/initialVal_BerlinToLondonAt5, fork: BerlinToLondonAt5, block: 5)[0m
```

**Comment by non-fungible-nelson** [comment]
Thanks for these reports. @daniellehrner does this relate to any of the RPC issues you were investigating prior?

**Comment by daniellehrner** [comment]
> Thanks for these reports. @daniellehrner does this relate to any of the RPC issues you were investigating prior?

It seems not to be related. It seems more like EVM related problems.

**Comment by diega** [comment]
Hello @winsvega could you please post the command line that you are using to start Besu and the corresponding one for _retesteth_ to get the output in the OP? Thanks!

**Comment by winsvega** [comment]
The besu cmd is

```
besu retesteth --rpc-http-port $((47710+$i)) --data-path=$tmpdir --logging=DEBUG >> ~/.retesteth/logs/besu-$file
```

**Comment by diega** [comment]
@winsvega I'm trying to run the `retesteth` from Docker (as I'm not being able to compile it directly on my Mac) to connect it to my besu instance running in the host. From the guest perspective, the JSON-RPC endpoint would be `host.docker.internal:8545`. How can I configure the tool to run this way?

These are my steps so far for building/running the tests:
```
$ git clone git@github.com:ethereum/retesteth.git
$ cd retesteth
$ docker build . --platform linux/amd64 -t retesteth
$ docker run --platform linux/amd64 --rm -v /Users/diegoll/dev/upstream/eth-tests:/tests -e ETHEREUM_TEST_PATH=/tests retesteth -t GeneralStateTests/stTransactionTest -- --singletest HighGasPrice --clients besu --singlenet Berlin
Running 1 test case...
Running tests using path: /tests
Active client configurations: 'besu '
Filter: 'HighGasPrice Berlin'
Running tests for config 'Hyperledger Besu on TCP' 2
Test Case "stTransactionTest": (1 of 1)
100%
/root/.retesteth/besu/start.sh
Finishing retesteth run
java: no process found
/root/.retesteth/besu/stop.sh
*** Total Tests Run: 0

Error: Error connecting to TCP socket: 127.0.0.1:47710 (stTransactionTest/, step: TestSuite::executeTest)

--------
TestOutputHelper detected 1 errors during test execution!
/retesteth/retesteth/TestOutputHelper.cpp(226): error: in "GeneralStateTests/stTransactionTest":

*** 1 failure is detected in the test module "EthereumTests"
```

**Comment by winsvega** [comment]
https://ethereum-tests.readthedocs.io/en/latest/retesteth-tutorial.html

Client outside docker

**Comment by winsvega** [comment]
I can actually make besu into docker

**Comment by diega** [comment]
I need to run the `retesteth` command from inside Docker b/c I'm unable to compile it into my Apple M1 (I may open an issue about it later on), but most importantly I want to run Besu from the IDE so I'm able to better debug the behavior.
I'm running my Besu instance with the following arguments:
```
retesteth --rpc-http-host=0.0.0.0 --rpc-http-port=8545 --host-allowlist=* --logging=TRACE --data-path=/var/folders/qb/0fq2wn6j1bb9xxdbyff91s6r0000gn/T/retesteth
```
And the `retesteth` runs fine from its container, seemsly resolving fine the output client, e.g.
```shell
$ docker run --rm --platform linux/amd64 --entrypoint=/usr/bin/curl retesteth -s http://host.docker.internal:47710/liveness
{
  "status" : "UP"
}%
```
But when I run:
```shell
$ docker run --rm --platform linux/amd64 -v /Users/diegoll/dev/upstream/eth-tests:/tests -e ETHEREUM_TEST_PATH=/tests retesteth -t GeneralStateTests/stTransactionTest -- --singletest HighGasPrice --clients besu --singlenet Berlin --nodes host.docker.internal:8545
```
nothing seems to happen. The prompt gets stuck there, with no output and no apparent timeout (I waited more than 5 minutes and I couldn't see anything from Besu's console either) so I end up killing the process.

**Comment by winsvega** [comment]
There is no hostname resolution.

It actually should throw an error message but there is a bug.

**Comment by diega** [comment]
@winsvega ok, thanks for clarifying. I just found a hacky way to resolve host's IP and I'm using it to fire the test and it seems to be working. I'll keep you posted

**Comment by winsvega** [comment]
I pushed a fix to resolve the hostname. 

But once again how does it work from inside the docker need to check.

You can also use dretesteth.sh script to build the docker. Then it uses docker image providing the same interface as original executable.

Open an issue about mac build

**Comment by diega** [comment]
@winsvega I was waiting to finish the analysis for all the tests in this report but it's taking more than I expected. We can start talking about the first ones while I finish the others.

#### HighGasPrice@Berlin
Command run:
```shell
$ ./retesteth  -t GeneralStateTests/stTransactionTest -- --singletest HighGasPrice --clients besu --singlenet Berlin --nodes 127.0.0.1:8545
```
Response:
```json
{"jsonrpc":"2.0","id":3,"error":{"code":-32602,"message":"Invalid params"}}
```
Reason: `gasPrice * gasLimit` exceeds the max representable value.

#### ValueOverflow@Berlin
Command run:
```shell
./retesteth  -t GeneralStateTests/stTransactionTest -- --singletest ValueOverflow --clients besu --singlenet Berlin --nodes 127.0.0.1:8545
```
Response:
```json
{"jsonrpc":"2.0","id":3,"error":{"code":-32602,"message":"Invalid params"}}
```
Reason: tx value exceeds the max representable value.

---
Given that both tests are marked to `expectException` in their _post_ definitions, what would be the expected output from the client?

**Comment by winsvega** [comment]
Yes, we actually never come up with error reports. As I understand its difficult for besu to report transaction exceptions. The exception report is not required, but very nice to check that the tr rejected for expected reason.

In case of exception not an rpc request fails but a certain response comes. I can clarify the format tommorow

**Comment by diega** [comment]
**accessListExample@EIP150**, **basefeeExample@EIP150**, and **eip1559@EIP150** fail because the transactions are being sent with EIP-155 protection and this isn't enabled until _Spurious Dragon_ (`eip158Block` in Besu config).

Also, it's worth mentioning that the response to the `eth_sendRawTransaction` call from the test [returns success](https://github.com/hyperledger/besu/blob/22.7.7/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSendRawTransaction.java#L86) with the empty hash, which is the behavior [only](https://github.com/hyperledger/besu/blob/22.7.7/ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethService.java#L87) for use within the context of the `retesteth` subcommand. I.e.
```json
{"jsonrpc":"2.0","id":3,"result":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"}
```

**Comment by diega** [comment]
**GasUsedHigherThanBlockGasLimitButNotWithRefundsSuicideFirst@London** and **TransactionNonceCheck2@London** fail because the fifth transaction is being [rejected](https://github.com/hyperledger/besu/blob/22.7.7/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/BaseFeePendingTransactionsSorter.java#L223) from the txpool. We need to change the tx pool configuration for the `retesteth` subcommand [here](https://github.com/hyperledger/besu/blob/22.7.7/ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java#L206).

**Comment by winsvega** [comment]
Here in [-t GeneralStateTests/stTransactionTest -- --singletest ValueOverflow --verbosity RPC](http://retesteth.ethdevops.io/web/index.php?gtests=stTransactionTest&singletest=ValueOverflow&clients=t8ntool&snetwork=Merge&vmtrace=vmtrace&verbosity=RPC&trd=&trg=&trv=)

The transaction does not pass verification, so test_minBlocks report it with `rejectedTransactions` info

```
Response test_mineBlocks {1}
{
    "result" : 1,
    "rejectedTransactions" : [
        {
            "hash" : "0xfbd91685dcbf8172f0e8c53e2ddbb4d26707840da6b51a74371f62a33868fd82",
            "error" : "insufficient funds for gas * price + value: address 0xa94f5374Fce5edBC8E2a8697C15331677e6EbF0B have 1000000000 want 115792089237316195423570985008687907853269984665640564039457584007913131739937"
        }
    ]
}
```

This is not required to report transactions like this. so if you can't track the transactions in the pool, test_mineBlocks return 1, but the rejected transactions are discarded, so that all requests like `eth_getBlockByNumber`  will return block without the failing transaction. however if you implement this, while generating/runing the tests the exception will be checked to the one that test expects.

**Comment by diega** [comment]
We can add your suggestion to the roadmap and work towards that, but for the scope of this issue, do you think it would be possible to make the reference tests to pass against the current `main@ae6c885` given the analysis provided and the changes performed?

**Comment by winsvega** [comment]
since the method is `eth_sendRawTransaction`  I think it is a correct behavior to reject invalid transaction if the RLP or structure is invalid. but if transaction is semantically valid and rejected due to another reason then it should return hash.

**Comment by winsvega** [comment]
Ok all tests resolved now.
Only the shift operations on legacy forks need a fix.

Btw besu test rpc is the fastest now on the test run.

**Comment by iamhsk** [comment]
@winsvega, Thanks for reporting back! Can we close this issue then? Would you mind opening up another issue with the shift operations on legacy fork please?

**Comment by winsvega** [comment]
Yes, all fixed now.

Next are Merge tests
