### ISSUE TITLE
Provide way to set extraData in execution blocks post-merge

### ISSUE THREAD

**Issue by mikeygrier** [hyperledger/besu#4471]
### Description
As a Validator, I want to be able to specify the value of extraData in the execution blocks that I propose

### Acceptance Criteria
* Update existing pre-merge command line options and configuration to work in the post-merge world OR
* Provide new post-merge options that allow this value to be set e.g. `--validator-extra-data`

### Steps to Reproduce (Bug)
1. Configure a validator
2. Use existing `--miner-extra-data` or `miner-extra-data` config to set extraData in blocks built by Besu
3. Propose a block
4. See block proposed with null extraData field

**Expected behavior:** The value specified in the miner-extra-data configuration should make its way into the block's extraData field.

**Actual behavior:** The extraData field is null in the block.

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: besu/v22.7.4/linux-x86_64/oracle-java-18
* Java version: Java(TM) SE Runtime Environment (build 18.0.2+9-61)
* OS Name & Version: Arch Linux
* Kernel Version: 5.19.12-arch1-1

### Additional Information (Add any of the following or anything else that may be relevant)
* System info - 16GB Memory, Quad core i5-3570

**Comment by MysticRyuujin** [comment]
Bump
