### ISSUE TITLE
Error: Failed to update deposit cache

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#4495]
Reported in Discord 

Lighthouse v3.1.2-01e84b7
Besu v22.7.5
Oct 07 03:44:05.686 ERRO Error updating deposit contract cache   error: Failed to update deposit cache: "FailedToInsertDeposit(NonConsecutive { log_index: 450832, expected: 450831 })", retry_millis: 60000, service: deposit_contract_rpc

We (Protocols) are also seeing this on some Besu/Teku nodes that we run. at least one is running Besu 22.7.2

**Comment by macfarla** [comment]
Workaround while investigation continues:
stop besu
delete the caches/ folder under besu's data directory
start besu
restart teku

**Comment by macfarla** [comment]
for additional context, LH  requests the deposit contract logs in 1000 block ranges. The error implies that the logs in the given range are not in strictly increasing order. From past experience, this usually means that the EL is missing a few logs in that range

**Comment by macfarla** [comment]
teku nodes with this issue showing `Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 450831, but got 450832`

**Comment by macfarla** [comment]
Restarting besu (and deleting the caches/ dir) and restarting teku/lighthouse has resolved the problem for everyone I've seen so far.

**Comment by macfarla** [comment]
restarted with passing `--eth1-purge-cache` to lighthouse and errors have disappeared after lighthouse rebuilt it's cache

**Comment by macfarla** [comment]
looking at etherscan, there seems to be an indexing anomaly there too

**Comment by macfarla** [comment]
450831 is 06E10F in hex and 0FE106 in little endian - which matches the "index" of the log in etherscan

**Comment by jflo** [comment]
The current working theory is that when a re-org happens the logs bloom cache is not updated correctly. We are attempting to reproduce in test code.

**Comment by lincoln2020** [comment]
I'm having the same problem with Lighthouse 3.1.2, Besu 22.7.4.  I know how to stop/start Besu, but how exactly do you "delete the caches/ folder under besu's data directory" with the terminal only? Thanks

**Comment by macfarla** [comment]
@lincoln2020 sorry for late reply
if you look under besu's data folder you will see a `caches` dir
```
➜  besu1 ✗ ll data
total 16
-rw-r--r--   1 sallymacfarlane  staff    13B  1 Aug 12:12 DATABASE_METADATA.json
drwxr-xr-x  18 sallymacfarlane  staff   576B 12 Oct 12:10 caches
drwxr-xr-x  60 sallymacfarlane  staff   1.9K 12 Oct 12:10 database
drwxr-xr-x   3 sallymacfarlane  staff    96B  8 Sep 14:54 fastsync
-rw-r--r--   1 sallymacfarlane  staff   159B 12 Oct 11:40 static-nodes.json
```
command to delete would be
`rm -rf data/caches`
