### ISSUE TITLE
Hive test tx not processed because of gas price

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#4506]
This one is interesting - tx not processed because of gas price 
```
	>>  {"jsonrpc":"2.0","id":27,"method":"eth_sendRawTransaction","params":["0xf86303018261a894aa000000000000000000000000000000000000000a825544820a95a0487f7382a47399a74c487b52fd4c5ff6e981d9b219ca1e8fcb086f1e0733ab92a063203b182cd7e7f45213f46e429e1f5ab2a5660a4ed54b9d6ee76be8d84d5ca8"]}
<<  {
  "jsonrpc" : "2.0",
  "id" : 27,
  "error" : {
    "code" : -32009,
    "message" : "Gas price below configured minimum gas price"
  }
}
response differs from expected:
 {
-  "error": {
-    "code": -32009,
-    "message": "Gas price below configured minimum gas price"
-  },
   "id": 27,
   "jsonrpc": "2.0"
+  "result": "0xd02709b29dba8e71897d1d28d57712b69221d3d6e5e0b50fd05aa097a567f30f"
 }
```

_Originally posted by @macfarla in https://github.com/hyperledger/besu/issues/4490#issuecomment-1270870278_

**Comment by mark-terry** [comment]
The following conditions are responsible for Besu's responses:
- Besu config includes `--min-gas-price=16`
- Transaction gas price is `0x01`
- Where transaction gas price < --min-gas-price, Besu will reject if mining is **not** enabled.

**Comment by mark-terry** [comment]
If the config is updated to `--min-gas-price=1` to fix the gas price issue, we get a `ChainId not supported` error.

**Comment by macfarla** [comment]
> If the config is updated to `--min-gas-price=1` to fix the gas price issue, we get a `ChainId not supported` error.

why would that change the chain id?

**Comment by mark-terry** [comment]
It fails validation at a later check.

**Comment by mark-terry** [comment]
PR: https://github.com/ethereum/hive/pull/661
