### ISSUE TITLE
Hive tests failing with `could not fund account`

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#4507]
Hive tests - 15 of 38 failing under `rpc` seem to all fail with the error `could not fund account`
eg https://hivetests2.ethdevops.io/?page=v-pills-results-tab&suite=1665365843-7723b6f8498880db60b6c679527e30b2.json

_Originally posted by @macfarla in https://github.com/hyperledger/besu/issues/4490#issuecomment-1272773564_

**Comment by macfarla** [comment]
The error message comes from here https://github.com/ethereum/hive/blob/14da32ec9eab92f9d18487f22bdbc90a801172ce/simulators/ethereum/rpc/vault.go#L200

**Comment by mark-terry** [comment]
PR here: https://github.com/ethereum/hive/pull/661
