### ISSUE TITLE
Improve SLOAD performance

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4523]
### Description
As a user, I want to have less IO on the database to keep performance open for other operations when using the getStorageValue method in UpdateTrackingAccount. 
These calls are generated by SLOAD operation, we should make sure that [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) is correctly implemented in terms of caching accessed values.
 
### Acceptance Criteria
* The cache is hit only once if I need to read a storage value that is not being updated. I would like to use the cache for storage that is being updated as well but it is not as important. 

This issue is to track an analysis for future performance improvements. This issue is not a bug but area of improvement.

**Comment by non-fungible-nelson** [comment]
@ahamlat - can we close for tracking elsewhere or still useful?

**Comment by ahamlat** [comment]
We can definitely close it as we did a lot of work on improving SLOAD, the next improvements will be disabling RocksDB checksum verification and Bonsai Flat database.
