### ISSUE TITLE
I have an issue when checking logs on besu local node

### ISSUE THREAD

**Issue by cmiretf** [hyperledger/besu#4536]
### Description
As an [Actor], I want [feature] so that [why]. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
<img width="1079" alt="Screenshot 2022-10-14 at 09 10 58" src="https://user-images.githubusercontent.com/37304718/195784843-44d76a28-7ea0-47ac-bb48-b3ba0af4e937.png">

* System info - memory, CPU

**Comment by non-fungible-nelson** [comment]
Hi there - what network are you syncing?
