### ISSUE TITLE
Besu does not build with openJDK-19

### ISSUE THREAD

**Issue by kirillp** [hyperledger/besu#4581]
Gradle build failed with

Execution failed for task ':buildSrc:compileGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit 'C:\eth2\besu.git\buildSrc\src\main\groovy\CheckSpdxHeader.
groovy' Unsupported class file major version 63

**Comment by shemnon** [comment]
This will require Gradle 7.6 or Gradle 8.0, neither of which have been released.

https://docs.gradle.org/7.6-milestone-1/release-notes.html#java19

https://github.com/gradle/gradle/issues/20372

**Comment by macfarla** [comment]
java 21 now
