### ISSUE TITLE
libsodium with recent version should be listed as a dependency

### ISSUE THREAD

**Issue by Tectract** [hyperledger/besu#460]
### Description

I'm trying to build with the latest Zulu OpenJDK Java 13

   java --version

openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment Zulu13.29+9-CA (build 13.0.2+6-MTS)
OpenJDK 64-Bit Server VM Zulu13.29+9-CA (build 13.0.2+6-MTS, mixed mode, sharing)

    git clone --recursive https://github.com/hyperledger/besu
    cd besu
    ./gradlew build

but I'm getting errors, build is failing.

### Acceptance Criteria
   build failure bug

### Steps to Reproduce (Bug)

on Debian Linux, installed the latest OpenJDK from Azul . com. via

    sudo dpkg -i zulu*linux_amd64.deb

then tried to follow the normal install instructions for Bezu

**Expected behavior:** [What you expect to happen]

build success, all tests should succeed

**Actual behavior:** [What actually happens]

I'm seeing these deprecation warnings:

```
> Task :enclave:compileJava
Note: /home/locutus/installs/GBAChain_Besu/enclave/src/main/java/org/hyperledger/besu/enclave/VertxRequestTransmitter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :nat:compileJava
Note: /home/locutus/installs/GBAChain_Besu/nat/src/main/java/org/hyperledger/besu/nat/upnp/OkHttpStreamClient.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

and build fails

> Task :besu:test

```
org.hyperledger.besu.PrivacyReorgTest > reorgToShorterChain FAILED
    java.lang.UnsatisfiedLinkError at PrivacyReorgTest.java:140

org.hyperledger.besu.PrivacyReorgTest > reorgToLongerChain FAILED
    java.lang.UnsatisfiedLinkError at PrivacyReorgTest.java:140

org.hyperledger.besu.PrivacyReorgTest > reorgToChainAtEqualHeight FAILED
    java.lang.UnsatisfiedLinkError at PrivacyReorgTest.java:140

org.hyperledger.besu.PrivacyReorgTest > privacyGroupHeadIsTracked FAILED
    java.lang.UnsatisfiedLinkError at PrivacyReorgTest.java:140

426 tests completed, 4 failed

> Task :besu:test FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':besu:test'.
> There were failing tests. See the report at: ./besu/build/reports/tests/test/index.html

```

investigating the indext.html reveals:

    java.lang.UnsatisfiedLinkError: libsodium.so: cannot open shared object file: No such file or directory

attempting to fix this via
    sudo apt-get install libsodium-dev

seems to have made no effect

let's try

    ./gradlew build --rerun-tasks

and it still fails those 4 tests.

the index error report now reveals:

    java.lang.LinkageError: Unsupported libsodium version 1.0.8 (9:1)

finally I got it to compile by finding a libsodium-dev_1.0.16-2_amd64.deb for "trusty"

### Versions (Add all that apply)
* Software version: besu/v1.4.1-dev-ad5bfecd/linux-x86_64/zulu-java-13
* Java version: openjdk 13.0.2 2020-01-14
* OS Name & Version: linux mint 17 Qiana

### Additional Information

so, libsodium version 1.0.16 seems to be a dependency, it should be listed in dependencies

**Comment by faraggi** [comment]
The wiki has now been updated to list libsodium as a dependency: 

https://wiki.hyperledger.org/display/BESU/Building+from+source

**Comment by Tectract** [comment]
You guys should include the instuctions for Ubuntu 14.04.

A TON of people are version-locked at 14.04 in order to avoid the systemd "avalanche".

**Comment by faraggi** [comment]
That's a fair point, @Tectract.
I'll get a 14.04 VM up and running, test it out and update the docs accordingly. Thanks for your feedback.

**Comment by Tectract** [comment]
My notes indicate I got the needed lib for "trusty" compatible OS'es here:

https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+sourcepub/8814980/+listing-archive-extra

Cheers~

**Comment by faraggi** [comment]
updated: 
https://wiki.hyperledger.org/display/BESU/Building+from+source

**Comment by Tectract** [comment]
libsodium23_1.0.16-0ppa3~trusty1_amd64.deb

> You can find the appropriate package (v1.0.8-5) files here:

should say

> You can find the appropriate package (v1.0.16-0) files here:

1.0.8-5 is the one in the 14.04 repos by default, it's what I got stuck on, and why I had to go hunting for the updated trusty libs...

**Comment by faraggi** [comment]
Should be fixed now.
How stable has your Trusty been with the BB libsodium upgrde? I trust you haven't noticed any problems?

**Comment by abdelhamidbakhta** [comment]
I think libsodium could be added in https://github.com/hyperledger/besu-native dependencies
@shemnon ?

**Comment by Tectract** [comment]
I haven't been able to connect my node as a validator to the GBA blockchain yet, from outside the Azure cloud, due to issue 583:  https://github.com/hyperledger/besu/issues/583

Will try again tonight and update that ticket. 

It seems to run without warnings or errors on startup though, with this library in place. This ticket can likely be closed :)

**Comment by timbeiko** [comment]
@Tectract I'll close it for now then, and please re-open it if there are follow-on issues. Thanks!
