### ISSUE TITLE
Revisit InMemory Snapshot implementation

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#4606]
### Description
The current Bonsai snapshots implementation extends BonsaiPersistedWorldState and uses off-heap memory for worldstate mutation. There is likely some performance to be gained by only using snapshots as a repeatable read mechansim and leveraging the BonsaiInMemoryWorldState to mutate the worldstate.

### Acceptance Criteria
* (re-)implement bonsai snapshot world state extending BonsaiInMemoryWorldState
* benchmark both implementations for memory and execution speed on a full archive sync
* burn-in the InMemory implementation with concurrent operations such as block proposal to ensure there are no concurrency issues

**Comment by non-fungible-nelson** [comment]
@garyschulte - where does this stand with all other bonsai issues/features? Should we track here?
