### ISSUE TITLE
Sync sometimes stalls due to peering challenges

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4614]
### Description
As a user, I do not want my sync to stall so that I can get up and running as fast as possible. In a post-Merge environment, there are some changes to sync that may help with this, like
- PoS Friendly sync target
- Peer shuffling to avoid trying to peer with the same node over and over 
- Re-Evaluating best-peer rules in post-Merge context
- Better logging in a stuck sync  

### Acceptance Criteria
- Clearer or better sync process 

**NEED TIMING / SCOPE ESTIMATE FOR THIS** 

### Steps to Reproduce (Bug)
1. Have a sync stall

**Expected behavior:** [What you expect to happen]
- Completed sync 

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: latest

**Comment by fab-10** [comment]
@non-fungible-nelson can we close this? Recent work on syncing should have made this obsolete
