### ISSUE TITLE
Need restart to find new peers sometimes during sync

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4616]
### Description
As a user, I want to keep a sync moving forward without having to restart to find peers if I lose my useful peers. Potentially because of the lack of evaluating of peers during sync and post sync 

### Acceptance Criteria
* Continual sync without a restart even if peers are lost 

**NEED TIME / SCOPE ESTIMATE**

**Comment by Gabriel-Trintinalia** [comment]
maybe related: https://github.com/hyperledger/besu/pull/4651

**Comment by macfarla** [comment]
Hypothesis - this is because we haven't yet implemented the "useless response" for snap sync. This is WIP in this PR #4651

**Comment by non-fungible-nelson** [comment]
closing for implementation in #5178
