### ISSUE TITLE
[Investigation] Besu can still lose many peers during sync 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4617]
### Description
As a user, I want to keep my peers to ensure I can sync and stay at chain head. Potentially because threads were blocked, we lost many peers 
Vertx for example uses different approaches to threading  

### Acceptance Criteria
* More stable peer numbers 

### Timebox
* Investigating the root cause: 2 days

**Comment by macfarla** [comment]
anecdotal evidence that this is better in 23.1.0-RC1

**Comment by iamhsk** [comment]
Closing this one. Potential duplicate of #4616
