### ISSUE TITLE
Full sync / Forest performance

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4624]
### Description
As a user, I want to be able to complete a full sync quickly, so that I can catch up to chain head without state growing larger than the node can catch up. This most often happens in forest mode which is more useful for archive use-cases. 

* New storage format changes may be able to help with full sync on Bonsai #5052 
* Forest - we need to determine what the areas are for performance improvements - some of the bonsai improvements can be tweaked to suit forest use-case (unknown) 

### Acceptance Criteria
* Faster performance and catch up to chain head from Full Sync 

### Steps to Reproduce (Bug)
1. Start a full sync 

**Expected behavior:** [What you expect to happen]
- Quick and reliable sync 
- Decent query performance for old blocks

**Actual behavior:** [What actually happens]
Cannot catch up to chain head in many instances with Besu on a full archive node.

**Comment by non-fungible-nelson** [comment]
Updated April 5th 2023.

**Comment by siladu** [comment]
@non-fungible-nelson we'd like to close this as don't think we should be focusing on full sync forest
