### ISSUE TITLE
Improve block tracing performance

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#4672]
As an user I want to be able to trace blocks and transactions reliably and quickly . Besu has currently poor performance for tracing blocks / transactions.

Analyze performance of current implementation. Speed up performance by avoiding unnecessary work and/or parallelize work.

Acceptance Criteria

-  Queries return quickly

**Comment by non-fungible-nelson** [comment]
Can we close? @ahamlat

**Comment by ahamlat** [comment]
I think so @non-fungible-nelson
