### ISSUE TITLE
Backward sync running during snap sync

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#4681]
### Description

There are reports of backward sync running along snap sync, and this must not happen.
Backward sync wait for the "initial sync is done" event before it starts, and the "initial sync is done" must only be triggered when 
any initial sync phase is complete, so there is probably an that trigger the event even if the actual initial sync is not yet complete

**Expected behavior:** [What you expect to happen]

Backward sync never run in parallel of any initial sync, and only starts when any initial sync phase is done

**Actual behavior:** [What actually happens]

Backward sync runs in parallel with snap sync

**Frequency:** [What percentage of the time does it occur?]

seldomly

### Versions (Add all that apply)
* Software version: 22.10.0
* Java version: Java17

**Comment by non-fungible-nelson** [comment]
Status with newest BWS bugs or close? @fab-10

**Comment by fab-10** [comment]
We are not receiving new reports for this one, so I think fixes released in December also fixed this one
