### ISSUE TITLE
Log Bonsai Use Snapshots Config Options at Startup

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#4683]
Following #4451, we should log whether bonsai-use-snapshots is enabled

~If you use a toml file to configure besu, it can be hard to tell what options are *actually live* on a deployment.~

~Logging at startup would be a simple solution to this, though we need to consider if this could leak any sensitive information.~

**Comment by gfukushima** [comment]
Think #4451 fixes this.

**Comment by siladu** [comment]
Thanks @gfukushima I missed this PR.

It does cover my description of the issue, however presence of --Xbonsai-use-snapshots was the reason I created it and unfortunately @daniellehrner's PR doesn't print that - was there a reason for that?

I will edit this issue to include this flag

Alternatively, I think it would better if we didn't have to remember to add new options into this config print code...but I wonder if the reason is to avoid accidentally printing sensitive information - what do you think @daniellehrner?

**Comment by daniellehrner** [comment]
I think when I created the config overview bonsai snapshots was not yet implemented. There is no other reason for it not being there.

I think as long as the flag exists it makes sense to print it in the overview as well. Should it be removed in the future we simply can remove it from the overview as well.

**Comment by garyschulte** [comment]
this option no longer exists, closing
