### ISSUE TITLE
Smart Contract issue on AKS(Azure Kubernetes)

### ISSUE THREAD

**Issue by nowjean** [hyperledger/besu#4684]
I installed besu on AKS. I followed helm chart guideline and it worked well. But suddenly there is a problem with smart contract.

When i test with metamask and besu, i can see this error : "Error! MetaMask error: REPLACEMENT_UNDERPRICED". 

Also, while smart contracting i can see rpc-node log like this :  vert.x-worker-thread-1 | WARN  | TransactionSmartContractPermissioningController | Account permissioning smart contract not found at address 0x0000000000000000000000000000000000008888 in current head block. Any transaction will be allowed.

Anyone know this problem? I followed besu helm chart guide correctly and it worked fine with metamask test. But now i'm fall in the problem.  Please any advice or comment. 

Thanks.

**Comment by yeroc-sebrof** [comment]
Not super helpful but I'm stuck in the same boat. I deployed a testing AKS cluster from the Besu guide and Helm charts and my transactions get stuck in pending while the network keeps moseying along making blocks. I also see this error `...Account permissioning smart contract not found at address...` but I didn't set any On Chain permissioning in my setup.

Did you get anywhere with this issue on your side @nowjean?

**Comment by yeroc-sebrof** [comment]
I found the problem! I'll open a PR on the `https://github.com/ConsenSys/quorum-kubernetes` repo with the solution :)

**Comment by nowjean** [comment]
@yeroc-sebrof Thanks! It works fine!
