### ISSUE TITLE
Deprecate privacy-precompiled-address CLI option

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#469]
https://besu.hyperledger.org/en/latest/Reference/CLI/CLI-Syntax/#privacy-precompiled-address

This property isn't required. We should:
- [x] Change the PicoCLi option to hidden
- [x] Provide a warning in the logs if a node is started using this option.
- [x] Remove `privacyAddress` field from `PrivacyParameters` class
- [x] Ensure that priv_getPrecompiledAddress returns the offchain or onchain contract address based on the privacy mode that the node is running
- [x] Ensure that the node behaves as if the precompile doesn't exist when using a different privacy mode (e.g. when using onchain, tx sent to the offchain should behave as if the offchain precompile doesn't exist).

This option should be removed in v1.5.2. The first step will be hiding and warning the user (v1.5.1) and then removing it completely (v1.5.2).

**Comment by MadelineMurray** [comment]
https://besu.hyperledger.org/en/stable/Reference/API-Methods/#priv_getprivacyprecompileaddress

**Comment by MadelineMurray** [comment]
Split into two GIs - one to deprecate/one to remove.

**Comment by magooster** [comment]
I've raised #1194, as it seems that off-chain and on-chain privacy groups use a different precompile contract. if you manually generate the privacy marker transaction then you need to know which contract address to use in the 'to' field of the transaction.

**Comment by lucassaldanha** [comment]
> if you manually generate the privacy marker transaction then you need to know which contract address to use in the 'to' field of the transaction.

Correct! 

However, we are using two fixed addresses for the two precompiles. In this case, we can deprecate the CLI option to configure the precompile address, and update the `priv_getPrivacyPrecompileAddress` method to return the correct precompile address depending on the privacy mode being used.

Thoughts?

**Comment by magooster** [comment]
This works as long as the two privacy group mechanisms are mutually exclusive. This just seems to be a recommendation at the moment... Would this be enforced by the node? (Not currently as far as I can tell, could it be?) Is a migration path from off-chain to on-chain privacy groups proposed?

**Comment by lucassaldanha** [comment]
I believe the node isn't enforcing it because our flexible privacy group mechanism is still in early access. I can double-check that. But the assumption is that one node should never be running both privacy "modes".

Regarding the migration path from one to another, atm we don't have anything planned on our roadmap for that. I'm not saying that we'll never look at this option, but it isn't a priority right now :)

**Comment by macfarla** [comment]
The above PR resolves this deprecation issue and also #1194
