### ISSUE TITLE
Ethstats connection won't be retried properly if the ethstats server runs with TLS/SSL

### ISSUE THREAD

**Issue by skylenet** [hyperledger/besu#4696]
### Description
When forwarding metrics via the `--ethstats` flag to an ethstats server that serves under TLS/SSL, besu falls back to plain HTTP if the TLS connection fails and will never try again. The only way to establish a connection again is by restarting besu and hoping that the first connectivity attempt works. 

### Acceptance Criteria
Besu should be able to try to reconnect to an ethstats server that has TLS/SSL configured. 

### Steps to Reproduce (Bug)
1 Have a ethstats server (I'll name it ethstats.local:443 on the following steps) running with TLS/SSL 
2. Stop the ethstats server to simulate that it's not available.
3. Run besu with `--ethstats=mynode:mysecret@ethstats.local:443`
4. See that it will log something like `2022-11-17 12:46:54.910+00:00 | vert.x-eventloop-thread-4 | ERROR | EthStatsService | Failed to reach the ethstats server Failed to create SSL connection (trying without ssl)`
5. Start the ethstats server with TLS/SSL
6. Notice that besu won't be able to connect to it because it won't retry with TLS/SSL again. It will stick to plain HTTP.

### Versions (Add all that apply)
* Software version: [`besu --version`]: hyperledger/besu:22.10.0

**Comment by non-fungible-nelson** [comment]
reprioritizing - Pari from EF devops has asked for some of this. alongside #3792
