### ISSUE TITLE
Besu is not finishing syncing.

### ISSUE THREAD

**Issue by inDane** [hyperledger/besu#4698]
Hey everyone,
this is what I'm looking at.
Besu is not finishing syncing.

I don't know why. Closest it came to finish, was 700 blocks behind, then it got stuck. 
With:
`Nov 17 16:21:13 validator besu[242915]: 2022-11-17 16:21:13.690+01:00 | vert.x-worker-thread-0 | WARN  | EngineNewPayload | Invalid new payload: number: 15987194, hash: 0xaf[...], parentHash: 0x37[...], latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000, status: INVALID, validationError: Block already present in bad block manager.`

I've restarted besu and now im seeing this, over and over again (for newer blocks/hashes ofc):

```
Nov 17 18:16:24 validator besu[875]: 2022-11-17 18:16:24.634+01:00 | EthScheduler-Timer-0 | WARN  | MergeCoordinator | Sync to block hash 0x4a7ad88fda4ec8eaf44cf6fe1113bed9f60d317ad21e58d4a8cce16367d74264 failed
Nov 17 18:16:24 validator besu[875]: 2022-11-17 18:16:24.634+01:00 | EthScheduler-Timer-0 | WARN  | EngineNewPayload | Sync to block 15991175 (0xd73ef7809266ccaa7e90eaa7fb7d49ab39d351d07d8db586af1c42f024675bad) failed
Nov 17 18:16:24 validator besu[875]: 2022-11-17 18:16:24.634+01:00 | EthScheduler-Timer-0 | WARN  | MergeCoordinator | Sync to block hash 0xd73ef7809266ccaa7e90eaa7fb7d49ab39d351d07d8db586af1c42f024675bad failed
Nov 17 18:16:24 validator besu[875]: 2022-11-17 18:16:24.634+01:00 | EthScheduler-Timer-0 | WARN  | EngineNewPayload | Sync to block 15991176 (0xd95dcb6796e39660edf546f745442de9388240298b244c1bb6bc9a41516dabc3) failed
Nov 17 18:16:24 validator besu[875]: 2022-11-17 18:16:24.634+01:00 | EthScheduler-Timer-0 | WARN  | MergeCoordinator | Sync to block hash 0xd95dcb6796e39660edf546f745442de9388240298b244c1bb6bc9a41516dabc3 failed
Nov 17 18:16:37 validator besu[875]: 2022-11-17 18:16:37.038+01:00 | nioEventLoopGroup-3-2 | INFO  | BackwardSyncContext | Backward sync failed (org.hyperledger.besu.ethereum.eth.sync.backwardsync.BackwardSyncException: Did not receive a headers for hash 0x6c328640d3241afa23fb8b0f09679109857cc9d7c2f76f8abec293c47a94377c). Current Peers: 25. Retrying in 5000 milliseconds...
Nov 17 18:16:42 validator besu[875]: 2022-11-17 18:16:42.205+01:00 | nioEventLoopGroup-3-5 | INFO  | BackwardSyncContext | Backward sync failed (org.hyperledger.besu.ethereum.eth.sync.backwardsync.BackwardSyncException: Did not receive a headers for hash 0x6c328640d3241afa23fb8b0f09679109857cc9d7c2f76f8abec293c47a94377c). Current Peers: 25. Retrying in 5000 milliseconds...
Nov 17 18:16:47 validator besu[875]: 2022-11-17 18:16:47.222+01:00 | nioEventLoopGroup-3-3 | INFO  | BackwardSyncContext | Backward sync failed (org.hyperledger.besu.ethereum.eth.sync.backwardsync.BackwardSyncException: Did not receive a headers for hash 0x6c328640d3241afa23fb8b0f09679109857cc9d7c2f76f8abec293c47a94377c). Current Peers: 25. Retrying in 5000 milliseconds...

```

I have no idea, what it is trying to tell me, nor what I should do to make besu happy. 

All I know is, that my validator is down for 3 days now and I don't enjoy that.
I would be happy if someone could hint me into the right direction.

EDIT: Maybe i should add, that im using besu 22.10.0 and lighthouse 3.2.1

Best

**Comment by xrchz** [comment]
I also ran into this problem. No idea how to fix it. I may have to just resync from scratch.

**Comment by mrosack** [comment]
Same here, with teku for CL, this is my second attempt at syncing with the same result.  I use nethermind/teku as my live node and i'm trying to set up besu/teku as a backup, but i'm about to give up.  Once Besu gets almost caught up with head, Teku keeps saying

`Could not find latest valid execution payload hash (0x0000000000000000000000000000000000000000000000000000000000000000) in the non-finalized chain. Optimistic sync may have finalized an invalid transition block.`

I can wipe teku's DB and resync using a state download from my other teku node, and it gets a little further, but always ends up stuck in the same way.

**Comment by totoCZ** [comment]
Same issue here

**Comment by mrosack** [comment]
I finally got it to complete syncing on my third try which used 22.10.2, not sure if that made the difference.

**Comment by mrosack** [comment]
Nope!  It was good for a couple hours, and now it's dead again.

Besu:
```
2022-12-06 16:19:05.873+00:00 | vert.x-worker-thread-0 | WARN  | EngineNewPayload | Invalid new payload: number: 16126495, hash: 0x4877d10748fc3571e57462660cd2e955d54dd0072b4229e5058a31a4b1486e32, parentHash: 0x071d5a05b43f16519fbe9cbb080dae11a6ba5d92a54c46310d8ff77822e5765a, latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000, status: INVALID, validationError: Block already present in bad block manager.
```

Teku:
```
16:19:57.088 ERROR - Could not find latest valid execution payload hash (0x0000000000000000000000000000000000000000000000000000000000000000) in the non-finalized chain. Optimistic sync may have finalized an invalid transition block.
```

**Comment by ruigil** [comment]
> In my case it wasn't a fresh sync, I had 22.10.2 with bonsai, checkpoint sync, and snapshots enabled, then it looks like it hit a reorg..

The same here. Hit a reorg, paired with #4379 , and also #4765, unable to sync, stuck in invalid payload...

Deleted database. Resynced from scratch. Seems to be working fine now... But my confidence is shaken.

Besu 22.10.1
Lighthouse 3.3.0
Goerli Net

**Comment by non-fungible-nelson** [comment]
@fab-10 - check here against your BWS fixes.

**Comment by fab-10** [comment]
closing this since the backward sync issues reported in this ticket have been fixed by #4656, released in 22.10.1, while the other issues are related to Bonsai that incorrectly set the block as invalid

**Comment by mrosack** [comment]
I synced with 22.10.2 and the sync failed, I don't believe this is fixed.  I'm giving up on besu anyway, though 🤷

**Comment by fab-10** [comment]
@mrosack I you do not mind could you share the logs with the error?

**Comment by fab-10** [comment]
I see, then it is related to the db issues like #4768 or #4784, so not related to the backward sync itself, for this I have closed this one, but you can comment on the other issues if you want.
About your issue, work is in progress to fix it, watch for the changelogs in the next releases, if you want to give Besu another try.

**Comment by ianaz** [comment]
Same issue with v23.10.1

**Comment by maxikrie** [comment]
Same issue with v23.10.3

**Comment by scheer88** [comment]
> Same issue with v23.10.3

For me as well:
`Besu 23.10.3 ` & `Teku v23.12.1`

**Comment by aytunc-tunay** [comment]
I've experiencing the same problem and unfortunately couldnt find any solution for days 
Besu 23.10.3  & Teku v23.12.1

**Comment by maxikrie** [comment]
@aytunc-tunay I think my particular issue (and probably yours as well) is related to a bug, which brought 70% of besu clients down. There is a fix and description of the problem https://github.com/hyperledger/besu/releases/tag/24.1.0

There seems to be another (faster) way, but I basically updated to the latest versions of besu and teku, deleted the databases and re-synced. Everything running smoothly now.
