### ISSUE TITLE
Private migration failing from Pantheon 1.1 to Besu 1.4

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#470]
From RC:

> I believe i've identified an edge case related to private state migration, seems if the Besu node can't detect schema version i.e. version = 0. Besu still starts and private database migration won't run
Migration only runs if schema version is 1 and migration flag is set, otherwise node won't start... (PrivateStrorageMigrationService.java). The node I'm testing dates back to pantheon 1.1 and there's no DATABASE_METADATA.json in the database directory.

We need to check what is happening in this case.

**Expected behaviour**
• If no DATABASE_METADATA.json is present, the private database is assumed to be 1.0. If private transactions are present and the migration flag was set, the migration should happen.
• If no private transactions are present, migration shouldn't happen.

**Comment by magooster** [comment]
For clarification there is a DATABASE_METADATA.json file in the data directory I was looking in data/database.

However it looks like in Besu 1.4 private tx related items are being written to data/database whereas in Besu 1.3.x looks like it wrote to data/database/private.

The migration service sees the database as empty - so no migration occurs all I see in the PRIVATE_TRANSACTION segment is entries suffixed PGHEADMAP - which I believe are new in 1.4

The Besu 1.3.x PRIVATE_TRANSACTION segment in data/database/private contain keys suffixed LOGS and OUTPUT

**Comment by magooster** [comment]
In 1.3.x RocksDBPlugin.java createAndRegister

factory = new RocksDBKeyValueStorageFactory(configuration, segments);
privacyFactory = new RocksDBKeyValuePrivacyStorageFactory(configuration, segments)

separate storage path - factory = data/database, privateFactory = data/database/privacy

In Besu 1.4.x

factory =
        new RocksDBKeyValueStorageFactory(
            configuration, segments, RocksDBMetricsFactory.PUBLIC_ROCKS_DB_METRICS);
    privacyFactory = new RocksDBKeyValuePrivacyStorageFactory(factory);

privacyFactory inherits the configuration from factory so same storage path = /data/database

Unless i'm missing something Besu 1.4.x won't see content in old privacy storage, just looking in new location...

**Comment by lucassaldanha** [comment]
We are investigating this and will see what we can do. In the meantime, you have the option of re-syncing your node. This should get you back up and running with the database populated correctly.

**Comment by lucassaldanha** [comment]
And thanks for all the details reporting this problem. It helps us a lot!

**Comment by lucassaldanha** [comment]
@magooster Could you confirm the Orion version that you are using in your setup?

**Comment by magooster** [comment]
Was originally using Besu 1.3.4/Orion 1.4.0 have switched to Besu 1.4.0/Orion 1.5.0

**Comment by lucassaldanha** [comment]
@magooster Sorry, I meant the version that you were use of before trying the migration.

**Comment by magooster** [comment]
Orion 1.4.0

**Comment by magooster** [comment]
I just upgraded Besu to 1.4.0 from Besu 1.3.4, did not change Orion.

**Comment by lucassaldanha** [comment]
Ok, so just to confirm:
- You have this node since Pantheon 1.1.x, using private transactions
- Your last update before Besu 1.4.0 was Besu 1.3.4

Correct?

**Comment by magooster** [comment]
Private transactions from Besu 1.3.1, don't recall running privacy with earlier versions. NB: This is just a test network I have running...

**Comment by MadelineMurray** [comment]
Lucas to test rolling back and resyncing.

**Comment by lucassaldanha** [comment]
We have identified the issue. Between version 1.3.4 and 1.3.5 there was a change in the way that the private database metadata was maintained and, unfortunately, users migrating from 1.3.4. to 1.3.5 with existing private transactions in their chain will lose the transaction execution data for transactions prior to 1.3.5.

At the moment, the best way to recover from this situation is to start a fresh node running +1.3.5 (preferably 1.4.0+) using the same Orion keys as the <= 1.3.4 node and resync the chain.

Since the PMTs are stored in the public chain, and all private transaction payloads are in Orion, resyncing the node will ensure that the private state is rebuilt. In the end, all private transaction execution information will be available again.

Let us know if you have any questions.

**Comment by magooster** [comment]
Thanks for the update - I assume this will be added to the migration notes.

**Comment by lucassaldanha** [comment]
>  I assume this will be added to the migration notes.

Sure! We are preparing docs and comms to help others that might face this issue.

**Comment by MadelineMurray** [comment]
We've added a page to the Wiki describing this issue and how to recover - https://wiki.hyperledger.org/display/BESU/Critical+Issue+for+Privacy+Users

The migration notes have also been updated. 

Thanks for raising this issue and taking the time to provide additional information.  Have you got any further questions/comments on this before we close this?

**Comment by magooster** [comment]
All good thanks
