### ISSUE TITLE
Best peer has chain height below pivotBlock height hangs

### ISSUE THREAD

**Issue by ianaz** [hyperledger/besu#4725]
Hi,

when syncing from scratch with bonsai tree and X_CHECKPOINT, I always get to a point after a few hours where it logs

`INFO  | FastSyncTargetManager | Best peer 0x459cdebf7d99d644e7 has chain height 16024176 below pivotBlock height 16030869`

and keeps printing it without ever exiting from it (let it go for 2-3 hours twice). The block sync doesn't continue when this message appears.

**Expected behavior:** My guess is that the client should select another peer and continue from there, even if it's not the best (?)

**Frequency:** About 4-6 times during a fresh sync from start.

### Versions (Add all that apply)
* Software version: hyperledger/besu:22.10.0 running on Docker compose
* OS Name & Version: Ubuntu 22.04.1 LTS
* Kernel Version: linux 5.15.0-53-generic
* Docker Version: 20.10.21
* Cloud VM, type, size: own built, AMD Ryzen 5 2600 Six-Core Processor, 32GB RAM, 2TB nVME

**Comment by non-fungible-nelson** [comment]
@macfarla - Was this addressed in any peering fixes? The RPC issue may be unrelated...

**Comment by macfarla** [comment]
hi @ianaz we optimized the peering code a lot since you reported this issue. Can you please try the latest version of Besu and raise a new issue if you're still having trouble? Thanks!

**Comment by estensen** [comment]
@macfarla I'm experiencing this now with Besu 22.10.3 resyncing from scratch after hitting https://github.com/hyperledger/besu/issues/5053. Sync is progressing, but a lot of "Best peer" prints

**Comment by macfarla** [comment]
For historical purposes - the "best peer" message - added some additional context here https://github.com/hyperledger/besu/pull/4888

**Comment by macfarla** [comment]
@estensen 22.10.3 is from mid Dec, but #4888 was committed in Jan so there's still some fixes for peering on their way!
