### ISSUE TITLE
MergeProtocolSchedule overrides evmBuilder for post merge specs

### ISSUE THREAD

**Issue by diega** [hyperledger/besu#4740]
### Description
Shandong testnet is PoS from the begining but the transition mechanism is still fired, particularly overriding the _evmBuilder_ with the Paris definition.

As a workaround for syncing Shandong these lines can be removed

https://github.com/hyperledger/besu/blob/2cafa8a25d27ee302a4e42a9769eada9f800e7d9/consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeProtocolSchedule.java#L65-L68

but this cannot be applied in general because it will break ETH-Mainnet consensus

**Comment by gfukushima** [comment]
Would #4735 help with this @diega ?

**Comment by diega** [comment]
@gfukushima I can check!

**Comment by jflo** [comment]
Out of date, if you are still having this problem please re-open with current behavior.
