### ISSUE TITLE
Run Withdrawals WIP against Hive Tests

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#4747]
Draft Hive tests for Withdrawals: https://github.com/ethereum/hive/pull/659

How to run locally: https://hackmd.io/oLxmO14oTpK4pHdfKUBqRg#Create-a-local-docker-image 

Some notes from Mario https://notes.ethereum.org/@marioevz/Withdrawals-hive-testing
and another interop doc https://notes.ethereum.org/@marioevz/hive-withdrawals-interop

As part of this, might be good to check why the current engine-api tests are failing: https://hivetests2.ethdevops.io/ (sort by suite then client)

**Comment by jframe** [comment]
Have run tests for the current withdrawal hive tests. Basic tests are failing. Syncing tests however are not passing. Pausing this until the timestamp protocol schedule work and withdrawals work is more complete.
