### ISSUE TITLE
Critical Exception Processing Transaction

### ISSUE THREAD

**Issue by realsnick** [hyperledger/besu#4764]
execution_1                  | #                                                                                                  #
execution_1                  | # Besu 22.10.1                                                                                     #
execution_1                  | #                                                                                                  #
execution_1                  | # Configuration:                                                                                   #
execution_1                  | # Network: Mainnet                                                                                 #
execution_1                  | # Data storage: Bonsai                                                                             #
execution_1                  | # Sync mode: Snap                                                                                  #
execution_1                  | # RPC HTTP APIs: WEB3,ETH,NET                                                                      #
execution_1                  | # RPC HTTP port: 8545                                                                              #
execution_1                  | # Engine APIs: ENGINE,ETH                                                                          #
execution_1                  | # Engine port: 8551                                                                                #
execution_1                  | #                                                                                                  #
execution_1                  | # Host:                                                                                            #
execution_1                  | # Java: openjdk-java-17                                                                            #
execution_1                  | # Maximum heap size: 64.00 GB                                                                      #
execution_1                  | # OS: linux-x86_64                                                                                 #
execution_1                  | # glibc: 2.31                                                                                      #
execution_1                  | # Total memory: 503.87 GB                                                                          #
execution_1                  | # CPU cores: 80                                                                                    #
execution_1                  | #                                                                                                  #
execution_1                  | ####################################################################################################

execution_1                  | 2022-12-02 05:32:09.690+00:00 | vert.x-worker-thread-0 | ERROR | MainnetTransactionProcessor | Critical Exception Processing Transaction
execution_1                  | org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x1096914fc3346ec18f8bdbd10962f935e5afd9dce753889baf57a284d3eb67a0 location 0x
execution_1                  | 	at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:133)
execution_1                  | 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
execution_1                  | 	at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:131)
execution_1                  | 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:63)
execution_1                  | 	at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:119)
execution_1                  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateKeyValueStorage.getStorageValueBySlotHash(BonsaiWorldStateKeyValueStorage.java:199)
execution_1                  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.getStorageValueBySlotHash(BonsaiPersistedWorldState.java:421)
execution_1                  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValueBySlotHash(BonsaiWorldStateUpdater.java:353)
execution_1                  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValue(BonsaiWorldStateUpdater.java:340)
execution_1                  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiAccount.getStorageValue(BonsaiAccount.java:208)
execution_1                  | 	at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  | 	at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  | 	at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  | 	at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  | 	at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  | 	at org.hyperledger.besu.evm.operation.SLoadOperation.execute(SLoadOperation.java:58)
execution_1                  | 	at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:282)
execution_1                  | 	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:161)
execution_1                  | 	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:173)
execution_1                  | 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:492)
execution_1                  | 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:404)
execution_1                  | 	at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:104)
execution_1                  | 	at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:76)
execution_1                  | 	at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:205)
execution_1                  | 	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:135)
execution_1                  | 	at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:440)
execution_1                  | 	at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:454)
execution_1                  | 	at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:141)
execution_1                  | 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:217)
execution_1                  | 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:73)
execution_1                  | 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
execution_1                  | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
execution_1                  | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
execution_1                  | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
execution_1                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
execution_1                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
execution_1                  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
execution_1                  | 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by macfarla** [comment]
@realsnick is this with --Xbonsai-use-snapshots=true ? if so - recommend setting --Xbonsai-use-snapshots=false in your config - this feature is still early access so there is some instability there

**Comment by realsnick** [comment]
not sure, i use ethd to run and configure it. I'll check

**Comment by realsnick** [comment]
yes it is, thank you.

**Comment by macfarla** [comment]
thanks for following this up @realsnick - would be great to get the default setup sorted for this in eth-docker

**Comment by realsnick** [comment]
made a PR https://github.com/eth-educators/eth-docker/pull/1085

**Comment by realsnick** [comment]
@macfarla the PR was accepted with changeing the `Xbonsai-use-snapshots=false`

Though the `sync-mode` left unchanged and it is `X_SNAP`. Is it ok or is it considered alpha as well and should be defaulted to `X_CHECKPOINT`?

**Comment by macfarla** [comment]
@realsnick technically SNAP and CHECKPOINT are both "early access" but SNAP has been around longer.
