### ISSUE TITLE
Docker uses Java 11 - Docs recommends Java 17

### ISSUE THREAD

**Issue by MysticRyuujin** [hyperledger/besu#4774]
This is mostly just an observation but the documentation for Besu says:

> Java 11+. We recommend using at least Java 17 because that will be the minimum requirement in the next Besu version series.

[Source](https://besu.hyperledger.org/en/stable/public-networks/get-started/install/binary-distribution/)

However, the `latest` docker containers seem to use `Java: openjdk-java-11`

I don't know if this is intentional but I would assume the Docker should use the recommended version, no?

It looks like there is a `latest-openjdk-latest` but it still seems counter intuitive for the tag most people will run to not run the recommended version.

**Comment by siladu** [comment]
The default for the docker build for the latest release (and 24.3.3 tag) currently openjdk-java-17.

Soon, likely next release, it will be Java 21: https://github.com/hyperledger/besu/blob/ec06ab556769103ea11c72680a09db960557b88c/docker/Dockerfile#L6
