### ISSUE TITLE
Unable to copy layered worldstate on 22.10.2 - Snapshots=False

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#4784]
### Description
Besu user experiencing the following bug:

022-12-07 08:38:20.491-07:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Optional[Unable to copy Layered Worldstate for 0x3c2a249675dca59a4477c9a3ffdcc51e203617266f1a0f6434fa1a1dc5fec3f0]. Block 16130345 (0xa8b549ea57d83df60aec71c6fb40ab8391b0f640d7a2d2a013fce3a296800ad0), caused by org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x3c2a249675dca59a4477c9a3ffdcc51e203617266f1a0f6434fa1a1dc5fec3f0...

Directly after a restart and their node is stuck. Restart does not fix. Initially the user experienced the error below, then upon restart, the error above. 

2022-12-07 08:09:44.904-07:00 | vert.x-worker-thread-0 | WARN  | EngineNewPayload | Invalid new payload: number: 16130345, hash: 0xa8b549ea57d83df60aec71c6fb40ab8391b0f640d7a2d2a013fce3a296800ad0, parentHash: 0x3c2a249675dca59a4477c9a3ffdcc51e203617266f1a0f6434fa1a1dc5fec3f0, latestValidHash: 0x3c2a249675dca59a4477c9a3ffdcc51e203617266f1a0f6434fa1a1dc5fec3f0, status: INVALID, validationError: Unable to process block because parent world state 0x3b34cb5ab01b1b590a73ac002acbf60790360952ed1679bd6d9f9b608856b29a is not available

User does not have snapshots enabled. User is on 22.10.2. 

[Discord context](https://discord.com/channels/697535391594446898/888098626264502302/1049027346226757682)

### Acceptance Criteria
* Bonsai is resilient to this concurrency bug 

### Steps to Reproduce (Bug)
1. Run Besu
2. Halt or restart
3. Experience error (specific DB state)

**Expected behavior:** [What you expect to happen]
Continues normally. 

**Actual behavior:** [What actually happens]
Bonsai resumes as normal

**Frequency:** [What percentage of the time does it occur?]
Infrequent

### Versions (Add all that apply)
* Software version: 22.10.2

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - snapshots false
* System info - memory, CPU

**Comment by yorickdowne** [comment]
Yep ran into this. Restart doesn't fix it; no bonsai snapshots. Running bonsai tries with snap sync.

```
eth-main-execution-1  | 2022-12-20 13:41:14.414+00:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Optional[Unable to copy Layered Worldstate for 0x1551f6d040298ec23c52f0fcf6bab2ee80cff9b958e1bdc27c11ba98b612b1d4]. Block 16224004 (0xe6f16e7d0103a45734a8d744de0b1c57c143fac4e750ebd9afd6e0ee708e94fc), caused by org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x1551f6d040298ec23c52f0fcf6bab2ee80cff9b958e1bdc27c11ba98b612b1d4
eth-main-execution-1  | 2022-12-20 13:41:19.451+00:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Optional[Unable to copy Layered Worldstate for 0x1551f6d040298ec23c52f0fcf6bab2ee80cff9b958e1bdc27c11ba98b612b1d4]. Block 16224004 (0xe6f16e7d0103a45734a8d744de0b1c57c143fac4e750ebd9afd6e0ee708e94fc), caused by org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x1551f6d040298ec23c52f0fcf6bab2ee80cff9b958e1bdc27c11ba98b612b1d4
```

**Comment by bryson-m** [comment]
I ran into this today as well. Same hashes and block number as @yorickdowne

**Comment by AegeanDad** [comment]
I am having this exact issue following a proper shutdown and reboot. Prior to this, Besu I had deleted the Besu DB and completed a fresh sync. Following the sync, everything was normal until the reboot. 

Dec 22 15:31:26 GHBeelink2 besu[4272]: 2022-12-22 15:31:26.971-08:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Optional[Unable to copy Layered Worldstate for 0x3bc82334b7902026f2e9ed64122ccf224899f014dc25823a8b30568e588f20cd]. Block 16243159 (0xd25d6b550954f0b0358297170861224b6136e17d54180fb3ddfa0b04c7964f06), caused by org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x3bc82334b7902026f2e9ed64122ccf224899f014dc25823a8b30568e588f20cd

**Comment by 0xcd2c6** [comment]
Experiencing the same issue after having to transfer validators to a different machine earlier this week because of an unrelated issue. Running 22.10.3 combined with Teku. Have deleted db and trying to resync currently.

**Comment by garyschulte** [comment]
This issue is mitigated in the 23.1.0-beta release coming on the 28th.  The underlying data problem that is the cause of this issue persists, but 23.1.0 should be able to recover from these kinds of errors via backward sync of subsequent blocks.

**Comment by timjrobinson** [comment]
I started getting this issue and tried the 23.1.0 release candidate docker image to mitigate it and am getting these errors instead:

```
rocketpool_eth1  | 2023-01-01 02:26:03.390+00:00 | vert.x-eventloop-thread-17 | ERROR | ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_newPayloadV1
rocketpool_eth1  | java.lang.RuntimeException: java.lang.RuntimeException: org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x334a634a192f87ae76c23c1b8a1f40619382d00825877d07ebef1947d777f637
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:175)
rocketpool_eth1  | 	at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:441)
rocketpool_eth1  | 	at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:455)
rocketpool_eth1  | 	at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:142)
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:219)
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:73)
rocketpool_eth1  | 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
rocketpool_eth1  | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
rocketpool_eth1  | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
rocketpool_eth1  | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
rocketpool_eth1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
rocketpool_eth1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
rocketpool_eth1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
rocketpool_eth1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
rocketpool_eth1  | Caused by: java.lang.RuntimeException: org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x334a634a192f87ae76c23c1b8a1f40619382d00825877d07ebef1947d777f637
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiLayeredWorldState.copy(BonsaiLayeredWorldState.java:275)
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.MainnetBlockValidator.lambda$validateAndProcessBlock$0(MainnetBlockValidator.java:120)
rocketpool_eth1  | 	at java.base/java.util.Optional.map(Optional.java:260)
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:117)
rocketpool_eth1  | 	... 13 more
rocketpool_eth1  | Caused by: org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x334a634a192f87ae76c23c1b8a1f40619382d00825877d07ebef1947d777f637
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiLayeredWorldState.lambda$copy$4(BonsaiLayeredWorldState.java:272)
rocketpool_eth1  | 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
rocketpool_eth1  | 	at org.hyperledger.besu.ethereum.bonsai.BonsaiLayeredWorldState.copy(BonsaiLayeredWorldState.java:269)
rocketpool_eth1  | 	... 16 more
```

**Comment by non-fungible-nelson** [comment]
@timjrobinson - can you provide us your config? 
@garyschulte - see above and let's discuss tomorrow.

**Comment by garyschulte** [comment]
@timjrobinson, 23.1.0 mitigates the issue by preventing database corruption when this error occurs.  If you have run into it on 22.10.x, the database is in an inconsistent state.  I am working on a standalone cli tool that can repair the state, if you still have a besu database in an inconsistent state (i.e. you have not tried to resync)

**Comment by timjrobinson** [comment]
@non-fungible-nelson the config is all rocketpool defaults but with snap sync enabled. 

I deleted my besu data to switch back to geth so unfortunately I don't have that database any more.

**Comment by j4cko** [comment]
I ran into the same issue a few weeks back and admittedly switched to geth at the time. But I still have the corrupted database. If there is something I can try, let me know (could also share).

**Comment by felix-halim** [comment]
I also ran into the same issue today:

`2023-01-12 11:22:18.852-08:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Optional[Unable to copy Layered Worldstate for 0x8a8d1fbd1f40bea01fd7a4ec7e7c50661f3e5f30baf16de5db99fc660c53f882]. Block 16387938 (0x8c0993a6ee49b3e8f4726400117d377c1c358037b28701c4955ad58a303f2dcd), caused by org.hyperledger.besu.plugin.services.exception.StorageException: Unable to copy Layered Worldstate for 0x8a8d1fbd1f40bea01fd7a4ec7e7c50661f3e5f30baf16de5db99fc660c53f882`

I am using 22.10.3 with bonsai with checkpoint.

Is there a way to fix this using command line yet?
Or should I delete everything and sync from the start?
This will happen again, right?

Thanks!

**Comment by non-fungible-nelson** [comment]
Hi folks - this bug is a "symptom" of three underlying issues we have patched: 
 #4786 Bugfix snapshot transaction segfaults after storage truncation
 #4862 Bugfix potential chain head and worldstate inconsistency
 #4906 Bugfix for selfdestruct and bonsai during heal step.

We will be testing these over the weekend for a release next week. This upcoming release will also have a check at boot to check for these types of errors and correct them or resync the worldstate (much shorter than a full resync). But if your node is experiencing this on 22.10.3, a resync is the best way for now to address. The trigger for the majority of these bugs is very rare (fixed in #4906), and a resync should fix it. If you happen to be unlucky and complete your snap sync with the narrow conditions for this bug, it wont manifest immediately, and should be rectified when we release 22.10.4. Thanks for the patience.

**Comment by AegeanDad** [comment]
I'm not sure about the experience of others who have seen this issue but I
thought I would share my specific case. Right around Christmas, Gary from
the Besu team and I spent a few hours looking at this on my setup here.

This issue only started happening after a proper clean shutdown and restart
for me. This was the first shutdown I had had after a fresh sync of Besu.
Prior to shut-down, I was fully synced and logs were clean. When it came
back up, it got stuck on a particular block with these errors. Gary and I
kicked off a fresh sync that night and it is back to normal. Point being,
it did not occur during regular runtime; only after a restart and that was
with a fresh database. Maybe that's why it is hard to reproduce this issue.

Now that I did yet another resync, I am afraid to take Besu down for
maintenance until we have the patch.

**Comment by non-fungible-nelson** [comment]
Definitely leave your node running. The problem actually can _begin_ during the sync phase (i.e. one of the bugs we patched was in the "heal" step of sync, it improperly filled the database, leading to these worldstate errors). If your node is running fine for now, definitely let it run while we get the release ready for next week.

**Comment by b-m-f** [comment]
This happened to me twice in 1 week. 

The first time it was triggered by a full SSD. Second time around there was enough storage and it occured 2 days after a successful resync.

Bonsai with snapshots

**Comment by b-m-f** [comment]
@garyschulte any update on the CLI tool? I am currently resyncing on 22.10.3 again until the release of 23.1.0

**Comment by non-fungible-nelson** [comment]
@b-m-f make sure to disable snapshots if they are enabled. At this time, they are exacerbating these issues. We are tracking this here #4768. These bugs all manifest a bit differently, but

**Comment by non-fungible-nelson** [comment]
tracking in multiple other locations.  closing here
