### ISSUE TITLE
Add getPayloadBodies and getPayloadBodiesByRangeV1 Methods

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#4787]
~https://github.com/ethereum/execution-apis/pull/218~
~https://github.com/ethereum/execution-apis/pull/146~

This is merged into main now: 
https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_getpayloadbodiesbyhashv1
https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_getpayloadbodiesbyrangev1

**Comment by jflo** [comment]
These linked specs have been obviated by this latest revision:  https://github.com/ethereum/execution-apis/pull/352/files

The corresponding pr in #4980 will need to be updated to take this new version into consideration.
