### ISSUE TITLE
Besu test_setChainParams

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#4806]
How to enable besu Merge network? 

setting chain params with `terminalTotalDifficulty` does not enables besu in the Merge mode for testing
```
{
    "params" : {
       "homesteadForkBlock" : "0x00",
       "EIP150ForkBlock" : "0x00",
       "EIP158ForkBlock" : "0x00",
       "byzantiumForkBlock" : "0x00",
       "constantinopleForkBlock" : "0x00",
       "constantinopleFixForkBlock" : "0x00",
       "istanbulForkBlock" : "0x00",
       "berlinForkBlock" : "0x00",
       "londonForkBlock" : "0x00",
       "terminalTotalDifficulty" : "0x00",
       "chainID" : "0x01"
    },
    "accounts" : {
    }
}

```

**Comment by shemnon** [comment]
set "mergeNetsplitBlock" and if there is an implicit basefee set "baseFeePerGas".  IIRC reference tests depend on an implicit 10 wei basefee. - [code](https://github.com/hyperledger/besu/blob/f20b4b3bd1af09730b1e1172643d09f3691ee420/ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java#L73)

I think it looks like this in JSON...
```json
{
    "params" : {
        "mergeNetsplitBlock" : "0x00",
        "basefeePerGas" : "0x00",
        "chainID" : "0x01"
    },
...
}

(chainId comes from som global tweaks at line 95)
```

**Comment by winsvega** [comment]
base fee comes in genesis section

**Comment by shemnon** [comment]
Yea, my reverse reading of that code section was off.  Here's some json that parsed...
https://github.com/hyperledger/besu/blob/1c143f167ee57adecd9e1d309f395c8851f48542/config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java#L254

```
{
    "config":{
        "mergeNetsplitBlock":11
    },
    "baseFeePerGas":"0xa"
}
```

I think the issue may also be using hex strings for the block number instead of raw json numbers.

**Comment by non-fungible-nelson** [comment]
@shemnon - is this a bug via in our genesis config or can be closed?

**Comment by winsvega** [comment]
as besu switches to t8n tool I suppose RPC format will not be supported. given it is difficult to support it since after Merge. 
I close the test RPC too
