### ISSUE TITLE
Add withdrawals details to eth_getBlock methods

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#4808]
Return withdrawals details from the eth_getBlock methods when withdrawals are enabled.

https://github.com/ethereum/execution-apis/pull/334

Should probably also add to debug_getBadBlock - are there other debug/trace methods that might need withdrawals as well?

**Acceptance Criteria**
* When withdrawals are enabled return the withdrawalsRoot and withdrawals in the returned block
* Do not include the withdrawalsRoot or withdrawals when withdrawals are not enabled

**Comment by siladu** [comment]
Implemented a quick and dirty solution for the testnet https://github.com/hyperledger/besu/pull/4818/commits/161b70c74b06f94a4722b983aded45811364332a

**Comment by siladu** [comment]
Consider reviewing and updating all of the APIs that return a Block e.g. debug_*

**Comment by non-fungible-nelson** [comment]
Pending integration tests @siladu
