### ISSUE TITLE
Fix DCO Check Github Action

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#4837]
It appears that when the DCO check was moved from Circle CI to Github Action, it no longer picked up DCO failure on the main branch itself.

**Comment by macfarla** [comment]
rolled back in #4855

**Comment by non-fungible-nelson** [comment]
@macfarla - not fixed correct?

**Comment by macfarla** [comment]
correct. DCO on main branch is not prevented by the DCO checks we are running. it happens rarely but would be good to prevent this

**Comment by siladu** [comment]
@non-fungible-nelson why did you close? This isn't completed.

**Comment by macfarla** [comment]
The current DCO app that we use doesn't support the merge event trigger. 

I tried it out here https://github.com/daisy-row/vigilant-octo-umbrella/pull/18
and you can see the DCO job fail here https://github.com/daisy-row/vigilant-octo-umbrella/actions/runs/4409849241/jobs/7726648239
with `Unexpected end of JSON input`
which comes from https://github.com/tim-actions/get-pr-commits/blob/master/index.js

**Comment by jflo** [comment]
is this blocked/on hold or can it be moved to the product backlog? Not sure what the next action on this is...

**Comment by macfarla** [comment]
It's low priority but not explicitly blocked. Looks like tim-actions DCO still only supports "pull-request" events tho https://github.com/tim-actions/dco so think we would need to use a different action
