### ISSUE TITLE
Refactor gas calculator to move oparations and precompiled costs out

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#484]
Gas Calculator currently has all gas calculations locked up in its interface. The majority of all calls are single use calls in operations and precompiled contracts. This makes it difficult to create a "mix&match" test fork including a base fork and select EIPs.

To fix this all operations and precompiled contracts will handle gas calculations themselves. Operations that refer to base tier costs or memory storage costing will still rely on GasCalculator for those parts. Intrinsic transaction cost will continue to be use the GasCalculator.

In the interim, all new operations and precompiled contracts, as well as updates to existing ones, should use the new pattern where gas is calculated in the Operation or PrecompiledContract class.

**Comment by RatanRSur** [comment]
Seems like we were able to handle the devnets without needing to bring in specific EIPs so closing for now.
