### ISSUE TITLE
Full EOF

### ISSUE THREAD

**Issue by diega** [hyperledger/besu#4840]
### Description
Implement Full (Suite) EOF:
- [EIP-3670](https://eips.ethereum.org/EIPS/eip-3670) - Container and Code Validation -  #4644
- [EIP-4200](https://eips.ethereum.org/EIPS/eip-4200) - Relative Jumps - #4760 
- [EIP-4750](https://eips.ethereum.org/EIPS/eip-4750) - EOF Functions - #4781 
- [EIP-5450](https://eips.ethereum.org/EIPS/eip-5450) - Stack Validation - #4805

#### Useful links:
  * [EOF Unified Specification](https://notes.ethereum.org/@ipsilon/eof1-unified-specification) for developer convenience
  * [EOFv1 checklist](https://notes.ethereum.org/@ipsilon/eof1-checklist) from the [Ipsilon](https://mobile.twitter.com/teamipsilon) team

**Comment by shemnon** [comment]
(a) the individual EIPs are the final arbiter of the spec, the unified spec is a developer convenience
(b) This should be covered by the following PRs - 
- EIP-3670 - Container and Code Validation -  #4644
- EIP-4200 - Relative Jumps - #4760 
- EIP-4750 - EOF Functions - #4781 
- EIP-5450 - Stack Validation - #4805 

The "container" eip - EIP-3540 - has support wired in in #4644 (early draft of the eip), #4750 (functions required a re-write) and #4805 (stack validation also had some tweaks)

**Comment by diega** [comment]
@shemnon great. I added your comments to the issue description. Btw, this issue is a placeholder for a Zenhub epic, which you can follow in the public instance [here](https://app.zenhub.com/workspaces/hyperledger-besu-61fc06f457da1c0017f6347d/issues/gh/hyperledger/besu/4840).
