### ISSUE TITLE
Besu integration tests not running

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#4852]
The Besu gradle integrationTest task does not seem to be running the integration tests.

In a recent circle CI job there are no test results https://app.circleci.com/pipelines/github/hyperledger/besu/19158/workflows/e2071db0-6c17-47c1-b54e-569752237cd7/jobs/116688.

Locally it appears to be just be compiling and running any of the integration tests.

**Comment by siladu** [comment]
Looks like this was caused by migrating to junit 5 https://github.com/hyperledger/besu/commit/eb5e604bcddd2504489447ab5549208870f052b9

**Comment by diega** [comment]
@siladu was that commit causing some sort of intermittency in `acceptanceTests` across CI runs? Because I'm pretty sure those were running when I made that change

**Comment by siladu** [comment]
@diega nothing to do with acceptanceTests AFAIK, I'm just trying to fix the `integrationTest` task. It runs 'successfully' but doesn't actually find/run any tests. Problem is not confined to the CI, it happens when you run gradle locally as well or even when you run an individual test in IDE.
