### ISSUE TITLE
Reduce the number of times trie nodes are serialised

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#486]
Profiling shows that implementations of tech.pegasys.pantheon.ethereum.trie.Node.getRlp are a hot spot for CPU usage when downloading world state for fast sync (as part of TrieNodeDataRequest.getChildRequests). This appears to be because methods like isReferencedByHash serialize to RLP to check the length.

For world state download particularly we have just parsed the node from RLP so should be able to store the information rather than having to serialise again.

**Acceptance Criteria**
 * Store RLP information from node after parsing it instead of re-serializing to RLP when performing checks such as isReferencedByHash

**Comment by timbeiko** [comment]
Assigned to @davemec

**Comment by davemec** [comment]
All improvements related to this issue have been addressed already.
