### ISSUE TITLE
Calculate blockValue for engine_getPayloadV2

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#4861]
blockValue stub of 0 was created in https://github.com/hyperledger/besu/pull/4833

Now need to calculate the blockValue, which is still being discussed on https://github.com/ethereum/execution-apis/issues/307

**Comment by wcgcyx** [comment]
Looks like this should be implemented as part of the shanghai spec: https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#specification-2

**Comment by wcgcyx** [comment]
Draft PR: https://github.com/hyperledger/besu/pull/4883
