### ISSUE TITLE
Potential memory leak on Eth_GetLogs

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#4882]
### Description
A discord user reported an OOM Killer event on Besu. When the event occurred, Besu was consuming more than 24.5 GiB. 
```
Out of memory: Killed process 58403 (java) total-vm:31612904kB, anon-rss:24522548kB, file-rss:0kB, shmem-rss:8996kB, UID:1000 pgtables:57052kB oom_score_adj:0
```
The user calls Eth_GetLogs every five minutes to get logs with a small range of blocks (tens of blocks).

### Steps to Reproduce (Bug)
Call Eth_GetLogs with small range of blocks (tens of blocks) every 5 minutes on a synced node.

**Expected behavior:** 
Besu shouldn't run out of memory.

**Actual behavior:** 
Besu consumes all available memory until being OOM killed.

**Frequency:** 
TBD

### Versions 
* Besu version : besu/v22.10.3/linux-x86_64/openjdk-java-19

### Additional Information (Add any of the following or anything else that may be relevant)
* System info - memory, CPU : 32 GiB RAM

**Comment by non-fungible-nelson** [comment]
@macfarla @daniellehrner - Have we made any changes to this method recently that could cause memory challenges?

**Comment by macfarla** [comment]
the only change I know of recently is this one https://github.com/hyperledger/besu/pull/4597 which checks the to/from params. It did require wiring through the maxLogsRange param but can't see how that change would cause this issue

**Comment by xrchz** [comment]
Is it known that this was working before any recent changes? Perhaps this pattern of usage is uncommon and is uncovering an old issue?

**Comment by xrchz** [comment]
I've now been running for a week without reproducing the OOM. Would be curious if anyone got it to repro.

**Comment by macfarla** [comment]
@xrchz do you have a similar use case?
> The user calls Eth_GetLogs every five minutes to get logs with a small range of blocks (tens of blocks)

**Comment by xrchz** [comment]
Yes. I am also "the user".

**Comment by macfarla** [comment]
oh hi!

**Comment by macfarla** [comment]
we haven't managed to reproduce this one either - wonder if there was something different about the timeframe / blocks / load when the OOM happened for you?

Are you ok if we close this ticket? We can always reopen it if the problem recurs.

**Comment by xrchz** [comment]
Yep I'm happy to close for now and will re-open if it recurs.

**Comment by xrchz** [comment]
It happened again yesterday:
`Out of memory: Killed process 416419 (java) total-vm:37073904kB, anon-rss:23986352kB, file-rss:0kB, shmem-rss:8996kB, UID:1000 pgtables:65036kB oom_score_adj:0`

**Comment by ahamlat** [comment]
Hi @xrchz,
Sorry I coudn't find our discussion in Discord, I don't remember if you have Besu Grafana dashboard. 
I wanted to check the heap usage/committed when the process is killed, and your java heap configuration (-Xmx).
If the process get killed before Java is running Out Of Memory, this could be a memory leak in the native memory (ex. non closed RocksDB resources).

**Comment by xrchz** [comment]
Sorry I don't have Grafana. Here's the heap configuration: `BESU_OPTS=-Xmx8g`.
Not sure what you mean by heap usage/committed when killed - where can I check?

**Comment by non-fungible-nelson** [comment]
@daniellehrner - tracking elsewhere?

**Comment by ahamlat** [comment]
@xrchz You can check heap usage/committed when a java process is killed only on your monitoring tool, in our case Grafana. If you decide to install Grafana with Besu Full Dashboard, the Panel is in "Java Memory Management" section

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/5099602/214892801-f42fe17f-6ecc-4268-bb14-1b89c146610c.png">

**Comment by xrchz** [comment]
Died again today `Jan 27 11:28:39 kernel: Out of memory: Killed process 692718 (java) total-vm:47951864kB, anon-rss:23041952kB, file-rss:0kB, shmem-rss:8996kB, UID:1000 pgtables:82044kB oom_score_adjust=0`

**Comment by ahamlat** [comment]
I'm running currently a Java batch to try to reproduce. My java process is getting logs for one eth address every 20 seconds (instead of every 5 minutes to speed up memory growth), from latest - 10 blocks to latest (on mainnet). Do you think this is similar to your use case ?

**Comment by xrchz** [comment]
Yes that sounds close enough to me. You might want the calls to filter on topics or something if it doesn't reproduce.

**Comment by xrchz** [comment]
Any progress here? I was running fine for weeks, but then got a couple of OOMs again in the past 2 days.

**Comment by xrchz** [comment]
It's possible that there's some additional activity that triggers the leak, specifically an occasional `eth_getTransactionReceipt` alongside the periodic `eth_getLogs` mentioned already.

**Comment by ahamlat** [comment]
@xrchz I wasn't able to reproduce, this new pre-release https://github.com/hyperledger/besu/releases/tag/untagged-b13f6c098d1772aa0feb has a better memory management. Could you give it a try. The release is not a final one, don't use it in production environment.

**Comment by xrchz** [comment]
I have seen this occur on `besu/v23.1.2/linux-x86_64/openjdk-java-19`
