### ISSUE TITLE
Ability to add SNI header in TLS ClientHello message

### ISSUE THREAD

**Issue by wilsonfv** [hyperledger/besu#4894]
### Description
When join a network / connect to another node, as an INITIATOR during first plain handshake message, I want to add [SNI header](https://datatracker.ietf.org/doc/html/rfc6066#section-3) in TLS [ClientHello](https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.1.2) message so that Target Server can return correct certificate by reading TLS SNI header. 

Modern Server may host multiple virtual hostnames. In order to return correct TLS certificate to client, client may add SNI header during TLS clientHello. This is common industry solution to resolve one server hosting multiple virtual hostnames problem. 

Existing P2P RLPx agent does not add SNI header when constructing TLS ClientHello.  

https://github.com/hyperledger/besu/blob/7c926d20ae1b9a8cdba6a7c44a5d0817e86ff541/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java#L333-L349

https://github.com/hyperledger/besu/blob/1b45cac3795c59b52a8fcd2126ac4bed6943f537/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyTLSConnectionInitializer.java#L93-L102

In order to add SNI header in TLS ClientHello, NettyTLSConnectionInitializer should call another implementation of [sslContext.newHandler](https://github.com/netty/netty/blob/6c81a3fa025f31bc0308d7913f8ecbf540f99247/handler/src/main/java/io/netty/handler/ssl/SslContext.java#L1008-L1010)

```
    public final SslHandler newHandler(ByteBufAllocator alloc, String peerHost, int peerPort) {
        return newHandler(alloc, peerHost, peerPort, startTls);
    }
```

We could add a new command line option in Besu to enable this feature. Such as proposed [command line option](https://besu.hyperledger.org/en/stable/public-networks/reference/cli/options/) `p2p-tls-clienthello-sni`, once this is enabled, SNI header will be added in TLS ClientHello. Default behavior is disabled.

### Acceptance Criteria
If besu command line option `p2p-tls-clienthello-sni` is enabled, RLPx agent will add SNI header in TLS ClientHello message.

**Comment by non-fungible-nelson** [comment]
Hi there - thank you for requesting this! This is a great issue for a new contributor to pick up. It is likely the Maintainers can pick this up at this time. Tagging @atoulme

**Comment by atoulme** [comment]
I'm sorry, I'm unsure why I'm tagged on this issue. I have no insight into this work.

**Comment by GesusBitcoin** [comment]
76c52bd42cfe5d22214dff99b6e2f9215ae6f351
