### ISSUE TITLE
Implement eth_submitHashrate JSON RPC API

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#490]
Implement the EthSubmitHashrate API conforming to the EIP-1474 specification, copied below:

[*EIP-1474*|https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#methods]*: eth_submitHashrate*

*Parameters*
||#||Type||Description||
|1|{Data]|hash rate|
|2|{Data]|random ID identifying this node|

*Returns*

(boolean) - true if submitting went through successfully, false otherwise

Example
 # Request
curl -X POST --data '{
"id": 1337,
"jsonrpc": "2.0",
"method": "eth_submitHashrate",
"params": [
"0x0000000000000000000000000000000000000000000000000000000000500000",
"0x59daa26581d0acd1fce254fb7e85952f4c09d0915afd33d3886cd914bc7d283c"
]
}' <url>

 # Response
{
"id": 1337,
"jsonrpc": "2.0",
"result": true
}

**Comment by sbs2001** [comment]
I would like to work on this, I looked at existing implementation of `json rpc` methods and have a decent idea of how things work. 

I wanted some pointers on how to get a node by its id, and how to submit the hash rate once this node is obtained.

**Comment by timbeiko** [comment]
@sbs2001 that's great 😄! The best way to get your questions answered rapidly as you are working on this would be to share your questions in our chat. It's the `#besu-contributors` channel at  https://chat.hyperledger.org

**Comment by timbeiko** [comment]
@sbs2001 after looking into this more, it seems like other clients have already deprecated this method or are strongly in favor of doing so (see: https://github.com/ethereum/go-ethereum/pull/20802). Given that, I believe [this other JSON RPC API](https://github.com/hyperledger/besu/issues/544) is much more valuable to get implemented in Besu and will be closing this issue. Sorry about that!
