### ISSUE TITLE
Add Context to BackwardsSyncAlgorithm 

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#4915]
Add context to message BackwardsSyncAlgorithm | Waiting for preconditions..

**Comment by macfarla** [comment]
You already get the context in a separate debug log line before this one (also debug).

**Comment by macfarla** [comment]
This was originally raised in #4147 - it looks like the "Waiting for preconditions" log was INFO but has since been changed to DEBUG. 

closing this issue
