### ISSUE TITLE
Improve debug-level Logging

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#494]
In the past few weeks, we've had several issues with misconfigured nodes that have been difficult to debug. We should add additional logging to help with debugging.

*Connection-Level Misconfiguration*

The connection-level misconfiguration manifests as follows:
 * A user is configuring a private network using static nodes

 * The static nodes contain the correct endpoint, but the public keys are wrong

   * This can be due to file system issues where a node can’t access the correct key and so generates a new key. This means that any enode urls referencing this node will have the wrong public key.

 * When a connection is attempted to an enode with an inaccurate public key, the crypto handshake will fail.

We can catch this case in the [ECIESHandshaker here|https://github.com/PegaSysEng/pantheon/blob/a4bb4af0dfc8ca9e7b97720aa8ef47e330d7f903/ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/rlpx/handshake/ecies/ECIESHandshaker.java#L208]. If this error is thrown when a the handshaker is the initiator (initiator = true), we should log a debug error like: LOG.debug(“Outbound handshake to {} failed. Static nodes configured with the wrong public key are a possible cause of this error.”, theirPubKey.getEncodedBytes())

*Discovery-Level Misconfiguration*

The discovery-level misconfiguration manifests as follows:
 * The bootnode enode urls are inaccurate: they contain the correct endpoint information but the wrong public key.

 * As a result, our misconfigured node will send a discovery PING to its bootnode

 * The bootnode will respond with a PONG, but because the PONG comes from a peer with a non-matching node id, we’ll ignore it.

Suggested fix:
 * If a [PONG is received|https://github.com/PegaSysEng/pantheon/blob/80f293ae7cdf43b06317957c2d37221df7d0d57f/ethereum/p2p/src/main/java/tech/pegasys/pantheon/ethereum/p2p/discovery/internal/PeerDiscoveryController.java#L315] with no corresponding match, log a debug message (possibly including the list of inflight PING messages or the list of unbonded bootnodes).

**Comment by gabrieledm** [comment]
Hi, i would like to work on this issue

**Comment by macfarla** [comment]
closing. out of date
