### ISSUE TITLE
Add a new CLI option to limit the number of requests in a single RPC batch request

### ISSUE THREAD

**Issue by Gabriel-Trintinalia** [hyperledger/besu#4951]
### Description

Adds a `--rpc-max-batch-size` CLI option to restrict the maximum number of requests in a single RPC batch request.

Default `50`
When `-1`: unlimited - the current configuration.

When number of requests in batch > `--rpc-max-batch-size`:

- Throw a JsonRpcError.EXCEEDS_RPC_MAX_BATCH_SIZE; with type `INVALID_PARAM` and message `Number of requests in batch exceeds --rpc-max-batch-size.`

**Comment by Gabriel-Trintinalia** [comment]
Mitigation for https://github.com/ConsenSys/protocol-misc/issues/681

**Comment by macfarla** [comment]
I haven't confirmed but it seems geth only accepts batch size 1 - so maybe that should be our default
