### ISSUE TITLE
Implement new engine APIs needed for 4844

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#4966]
Still experimental, but can be prototyped onto main safely:

https://github.com/ethereum/execution-apis/blob/main/src/engine/experimental/blob-extension.md

- Add 3 methods to the Engine namespace
- extend PayloadResult and add excessDataGas, or update existing class but make sure that field doesn't appear on legacy apis.
-make sure configured shanghai and cancun timestamps are available to v3 methods
-get access to datablobs and kzgs and versioned hashes from RPC layer.

**Comment by non-fungible-nelson** [comment]
@jflo any status on this?

**Comment by jflo** [comment]
Implemented and merged into https://github.com/hyperledger/besu/tree/eip-4844-interop
