### ISSUE TITLE
Make Fast Sync Default on Named Networks

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#498]
The current default syncing mode for Besu is full sync with no pruning. On named networks (see [this list|https://besu.hyperledger.org/en/latest/Reference/CLI/CLI-Syntax/#network], excluding `dev`), the default should be changed to fast sync *and* pruning.

*Acceptance Criteria*:
 * Default syncing mode is fast sync on by default on the following networks:
   * mainnet
   * rinkeby
   * goerli
   * classic
   * mordor
   * kotti

**Comment by RatanRSur** [comment]
@NicolasMassart, assigned you since doccing is the last thing required before I close this
