### ISSUE TITLE
getUncle - geth returns null, besu returns a value

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#4987]
See ~#4243~ #4233 for reproduction instructions, test case etc. 

For a specific test case, 
node TC_1659708317.js

geth returns null for getUncle RPC and besu returns a value. 

Needs investigating

**Comment by gtebrean** [comment]
@macfarla I tested all the getUncle API methods:
eth_getUncleCountByBlockNumber
eth_getUncleByBlockHashAndIndex
eth_getUncleByBlockNumberAndIndex
eth_getUncleCountByBlockHash

On both Besu and Geth in dev mode they are returning the same result to API call, according to documentation.
When there are no uncles to latest block the results are the following:

Method                                                               Besu                                        Geth
eth_getUncleCountByBlockNumber                0x0                                          0x0
eth_getUncleByBlockHashAndIndex                 null                                         null
eth_getUncleByBlockNumberAndIndex            null                                         null
eth_getUncleCountByBlockHash                     0x0                                          0x0

Please tell me if you have any thoughts on this or what other tests I should do.

**Comment by macfarla** [comment]
@gtebrean apologies, I had linked the wrong ticket number for the setup instructions. Can you test the specific test case TC_1659708317 from #4233 - the test files are in https://github.com/hyperledger/besu/files/9286365/test_cases.tar.gz and instructions in #4233

**Comment by macfarla** [comment]
what if you run geth on the CHAIN_1 setup - does it report the same uncles as Besu on CHAIN_1 ?

**Comment by gtebrean** [comment]
> what if you run geth on the CHAIN_1 setup - does it report the same uncles as Besu on CHAIN_1 ?

I run geth on CHAIN_1 setup. After I full synced geth network with chain_1 data via enode results are:
Block with number 258 is correctly find:

> {
>   baseFeePerGas: 7,
>   difficulty: '160821',
>   extraData: '0xd883010a15846765746888676f312e31382e34856c696e7578',
>   gasLimit: 20581600,
>   gasUsed: 135091,
>   hash: '0xeba9e204f0d944749bbe9b75278efa224bc6dfd9d7fa5d48b5ff391da6001dfe',
>   logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
>   miner: '0x0123456789012345678901234567890123456789',
>   mixHash: '0x8caabeb1a10a035564105e076f6869a2170b0d0fbc0aac6dccdca4a01c4f2d46',
>   nonce: '0x06ebabf864acddc9',
>   number: 258,
>   parentHash: '0x20c76096e163397d3b3421f7443cbf1cdacfd2f419fd2eb4f0459dd282fbe1ff',
>   receiptsRoot: '0x88f346009ec2dfd1be9f6807e7fba47bd2f2e53923a14249616a7747df8ec3ef',
>   sha3Uncles: '0x76eb253e03b27cb2f49897b75d71270c22c6752bca2a006e0e4d645b6b489199',
>   size: 2479,
>   stateRoot: '0xcdd7051b1f764eb9fb6263e9660258e2760c6d722cf327552a758ec5ce6b083e',
>   timestamp: 1659702540,
>   totalDifficulty: '37512972',
>   transactions: [
>     '0xdcc3bd2f51256f219a6f7535f534849432b64cfbd7a20af8d00276870927fff1',
>     '0xad7b7fb5295570606a060b0c2c10831a26fd26d11060721f6ad5c6bb5f7a5e02',
>     '0x751eba9396c7971086626bf0093027684d8c65231afb04dc84347536576baece',
>     '0x96ebd4242fcf23b03d0cd0d78d0a1ed8516907dd2a676f8d6e936001357f837f'
>   ],
>   transactionsRoot: '0x0fe9986f081b00102199c2f4bc827e08af11fc58962edc600ca19da3ba050c62',
>   `uncles`
> : [
>     '0xfb268fc077b70766ab30c22af214f4e88de74e290dc5abb3cbb98c0231c26e17',
>     '0xd3dd978e5e8f3cdf197a7b9c7b02ffdea09ac230d1ddbdf4f2d9b70ae8e147e5'
>   ]
> }
> 

getUncle correctly returns the first uncle:

> {
>   baseFeePerGas: 7,
>   difficulty: '160197',
>   extraData: '0xd883010a15846765746888676f312e31382e34856c696e7578',
>   gasLimit: 20461425,
>   gasUsed: 432835,
>   hash: '0xfb268fc077b70766ab30c22af214f4e88de74e290dc5abb3cbb98c0231c26e17',
>   logsBloom: '0x00000040000000000000000000000000000000200400000000000000000400004000000000200000000040000000000008004000040000000020a401402000000108000000000400000000080000000000108040000000400000000008000010020000040200000004000000422008000080000080000000000000100000000000000000000000000100000010000000080100000000084000200000000000000200040000000000000000000000000000000000008000000000000000002000000010020000000000000000000000000000020000100000800000000480200080102008000000000000000000200000004080084000000000000040300000a0',
>   miner: '0x0123456789012345678901234567890123456789',
>   mixHash: '0x9f67070db3f0ec1bd4ff2757c107d9536dacfbd75dacb33b7e9643a4a7207eb6',
>   nonce: '0x4ddaf1d07d8b1473',
>   number: 252,
>   parentHash: '0x3eaa16a69d5a4a56405e2a9eb4fc656f303ead886010912521f2eb5200c38b64',
>   receiptsRoot: '0x225a943f50c1a8ee71eb5ad92b2c52de5d8895d4485acfdd610e5ca6588c8845',
>   sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
>   size: 542,
>   stateRoot: '0x581c64f7961011b8d802e5550f4af8429a4e7c67fca44559dd69b5be3fc36ae1',
>   timestamp: 1659702508,
>   transactionsRoot: '0xc433e9516a92b1d30c0f9c75222a6c22199ddd5d535439fbb1b7ccb0cec5c061',
>   `uncles`: []
> }

Both besu and geth are returning the same thing.

I think the issue appeared because when testing on geth data wasn't synced correctly from CHAIN_1, as node 258 couldn't be find the getUncles returned `null`

**Comment by macfarla** [comment]
ok fair enough, that makes sense. thanks for investigating and confirming behaviour - I think we can close it!
