### ISSUE TITLE
Unable to call debug_traceBlockByHash due a transaction with gasPrice as Big Number to fit in Long values

### ISSUE THREAD

**Issue by helderjnpinto** [hyperledger/besu#5010]
### Description

In one of blockchains we got 3 transactions with a big gasPrice the code of besu was previous to this PR https://github.com/hyperledger/besu/pull/3065

I detected because in the explorer miss 3 blocks and when i fetched give-me Internal Error due this function [here](https://github.com/hyperledger/besu/pull/4993/files) that calculates _getEffectiveGasPrice_ giving a negative number.. after this _getTransactionReceipt_ also give the same problem
For traceBlockByHash or Number the blocks with this types of transactions with big gasPrice 0xc097ce7bc90715b34b9f1000000000, i checked the hash of merkle tries and it seems not be right....

![merk](https://user-images.githubusercontent.com/12281088/214939154-496b4430-59be-45c6-a403-7cc930775450.png)

Eg. of transactions with high gas price 
`
{
        "blockHash": "0xb87339501942337b8fcdc5278f24d7bb5c9da7ac4de1a00eb0c9fd378ea5f646",
        "blockNumber": "0x9ad07a", <- 10145914
        "gas": "0x989680",
        "gasPrice": "0xc097ce7bc90715b34b9f1000000000", <- HERE THE PROBLEM WHEN TRY CONVERT TO LONG TYPE
        "hash": "0xc6b5015a3b80374baefe9a168e2a73cd5adcde94dd83adeadea0f4d9c098ac13",
        "input": "0xa9059cbb000000000000000000000000d745798106f1cf1538ac4d57d2a9ac359bdd5b140000000000000000000000000000000000000000000000056bc75e2d63100000",
                 ...
    }
`
![image](https://user-images.githubusercontent.com/12281088/214940036-f6921714-4ce4-44cb-9620-4c86d172fbd3.png)

After i fix the code to not return or calculate baseFee because is one Optional.empty and our Hardfork is previous to London and gasPrice is present in this 3 transactions on blocks 10145914, 10145926, 10145939, now i can return the block, receipt and the transaction by hash via JSON RPC.

The problem here is in traceBlockByHash or Number the query return null for this 3 blocks that have 1 transaction on each.

### Steps to Reproduce (Bug)

You can check the explorer here https://explorer.tst.publicmint.io/
and the RPC for this is https://rpc.tst.publicmint.io:8545

Block hash 0xb87339501942337b8fcdc5278f24d7bb5c9da7ac4de1a00eb0c9fd378ea5f646 for block number 10145914 that have this transaction 0xc6b5015a3b80374baefe9a168e2a73cd5adcde94dd83adeadea0f4d9c098ac13 with the gasPrice problem.

`
curl --location --request POST 'http://rpc.tst.publicmint.io:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByHash",
    "params": [
        "0xb87339501942337b8fcdc5278f24d7bb5c9da7ac4de1a00eb0c9fd378ea5f646"
    ],
    "id": 1
}'

curl --location --request POST 'https://rpc.tst.publicmint.io:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionByHash",
    "params": [
        "0xc6b5015a3b80374baefe9a168e2a73cd5adcde94dd83adeadea0f4d9c098ac13"
    ],
    "id": 1
}'

`
In the testNet is missing the fix for getTransactionReceipt but i can put the result here: 

`
{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionReceipt",
    "params": [
        "0xc6b5015a3b80374baefe9a168e2a73cd5adcde94dd83adeadea0f4d9c098ac13"
    ],
    "id": 1
}
`
`
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0xb87339501942337b8fcdc5278f24d7bb5c9da7ac4de1a00eb0c9fd378ea5f646",
        "blockNumber": "0x9ad07a",
        "contractAddress": null,
        "cumulativeGasUsed": "0x6c73",
        "from": "0x352abe22d01ac782bbe79a042b79964f770b91e2",
        "gasUsed": "0x6c73",
        "effectiveGasPrice": "0x0",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "status": "0x0",
        "to": "0x0000000000000000000000000000000000002070",
        "transactionHash": "0xc6b5015a3b80374baefe9a168e2a73cd5adcde94dd83adeadea0f4d9c098ac13",
        "transactionIndex": "0x0"
    }
}
`

**Expected behavior:** [What you expect to happen]

Expected debug_traceBlockByHash with this transactions

**Actual behavior:** [What actually happens]

Returns null as result

### Versions (Add all that apply)
* Software version: [`besu --version`] is prior this PR https://github.com/hyperledger/besu/pull/3065
* Java version: [`java -version`] - 13
* OS Name & Version: [`cat /etc/*release`] 
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

* Kernel Version: [`uname -a`] Linux tuf-15 6.0.12-76060006-generic #202212290932~1673966427~22.04~e15d5b5 SMP PREEMPT_DYNAMIC Tue J x86_64 x86_64 x86_64 GNU/Linux

**Comment by non-fungible-nelson** [comment]
To clarify, did you run your tests **on** Besu 22.1.0 with this PR #3065 or **before** (version 21.10.9)?

**Comment by non-fungible-nelson** [comment]
@macfarla to review here. if this was run 21 days ago, can we presume 22.10.3 and test?

**Comment by macfarla** [comment]
I'm a bit confused. I think #3065 would exactly fix this. @helderjnpinto are you able to upgrade Besu?
the `getEffectivePriorityFeePerGas` doesn't return a long any more

https://github.com/hyperledger/besu/blob/17455d62e9a8179eae775e66e51ef4c0e7b96882/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java#L451

**Comment by helderjnpinto** [comment]
@macfarla yes. this PR fix the issue for get transaction and receipt RPC, but not for the mined blocks with incorrect state root i think. i do not upgrade the client code because i will be leaving the project soon. when i do a debug_traceBlockByHash in debug mode the worldstate is not available for this 3 blocks. This only happened on testnet :pray: . but in case of happens in the future with other structures not in particular with this case of gasPrice as incorrect long value, how can we fix this ?

**Comment by helderjnpinto** [comment]
And other question more important why a gasPrice as incorrect value caused this not linked root states. if you check the root states like in the image the red boxes has the incorrect hash from previous block root and it's expected to be equal right ?

**Comment by helderjnpinto** [comment]
I tested again the `debug_traceBlockByNumber` in testnet now works for this 3 blocks... :exploding_head: and i do not updated the code... strange behaviour ... when i tested this RPC was returning null as jsonrpc result for other empty blocks a empty []. now return the correct trace ... i don't know what happened here... sorry @macfarla @non-fungible-nelson 


 i will close this issue thanks !

**Comment by non-fungible-nelson** [comment]
No problem!! Thank you for your reports, we love it 🙏🏻 @helderjnpinto
