### ISSUE TITLE
Improvement behaviour like other eth clients in `eth_call` (verifications too strict)

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#502]
Problem: 

Using web3 with options on contract instantiation link for web3 doc options like `gasPrice` and `gasLimit` or `gas`, any `eth_call` that should be simulation mode is verifing the `from` address balance, giving the following error:

> `UnhandledPromiseRejectionWarning: Error: Returned error: Upfront cost exceeds account balance`

Clients like geth, infura do not give this error.

For at least `eth_call` (i not tested `eth_estimategas`) contract methods with `view` do not pay the balance and gas parameters should be ignorated. 

Here the chat link: https://chat.hyperledger.org/channel/besu?msg=kuD2ysMRHExvRbWbz  

Raised by @helderjnpinto in Jira - https://jira.hyperledger.org/projects/BESU/issues/BESU-137

**Comment by vmichalik** [comment]
Closed by #1834

**Comment by fab-10** [comment]
Geth has updated its behavior, and it is now ignoring the account balance if `gasPrice` (or `maxFeePerGas` + `maxPriorityFeePerGas` ) are not set, see https://github.com/ethereum/go-ethereum/issues/21108#issuecomment-632498225
