### ISSUE TITLE
eth_getBalance returning 0x0 for latest block

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#5038]
### Description
eth_getBalance endpoint often erroneously returns 0 balance for accounts when querying using 'latest' block identifier.

### Acceptance Criteria
* eth_getBalance should reliably return the balance of an account

### Steps to Reproduce (Bug)
1. sync besu to head using bonsai storage format
2. query eth_getBalance endpoint for any address, using `latest` as the block hash

**Expected behavior:** [What you expect to happen]
correct balance returned

**Actual behavior:** [What actually happens]
0x0 balance returned vast majority of the time

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: 23.1.0-RC1

**Comment by siladu** [comment]
Do we know the commit that introduced this bug?

**Comment by siladu** [comment]
We had to revert https://github.com/hyperledger/besu/pull/5039 as it caused "Unable to copy layered world state" errors frequently.

**Comment by siladu** [comment]
@garyschulte @ahamlat @matkt are you happy to close this as resolved by https://github.com/hyperledger/besu/pull/5076?

**Comment by non-fungible-nelson** [comment]
Mitigation in 23.1.0.
