### ISSUE TITLE
Improve the error when failing to submit a Private Marker Transaction

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#505]
When using privacy without defining the `--privacy-marker-transaction-signing-key-file` an auto-generated key (account) is used. 

On a network with a non-zero gas price, when a private transaction is submitted with the `from` account being well funded, the error `Upfront cost exceeds account balance` is encountered (because the account signing the PMT is not funded).

While the error is technically correct, it is fair to assume that a user (who submits the private transaction) will infer that the error relates to the transaction they have submitted, and the insufficient funds relate to the account they submitted in the `from` field.

Let's do something to improve this user experience, either something in the JSON-RPC response, or at a minimum additional logging to help people diagnose the problem (i.e. identify the PMT failed). 

Raised by @CjHare in Jira

**Comment by Amit-codezeros** [comment]
I am getting the same issue..
Where to define this marker tag ??

**Comment by Amit-codezeros** [comment]
How to disable privacy ?

**Comment by MadelineMurray** [comment]
@amitcz - privacy must be explicitly enabled and configured as described in this tutorial https://besu.hyperledger.org/en/stable/Tutorials/Privacy/Configuring-Privacy/ 

Are you using privacy and getting this error message?  Or getting this error message with public transactions?
