### ISSUE TITLE
Archive sync intermittently freezes with "No sync target"

### ISSUE THREAD

**Issue by duncancmt** [hyperledger/besu#5056]
### Description
As an blockchain application developer, I want to retrieve and inspect historical blockchain state so that build a metrics dashboard for my dapp. 

### Steps to Reproduce (Bug)
1. Install besu
2. Configure port forwarding
3. Attempt a to sync with `--sync-mode=FULL`

**Expected behavior:**
Sync proceeds at ~200msec/block

**Actual behavior:**
Sync proceeds at ~400msec/block. Sync frequently stops/pauses/freezes for extended periods of time with no progress.

So far I can only say that it _isn't_ a hardware or network issue. I have teku syncing on the same VM with no problem, and I verify that connectivity is good with other monitoring tools. It's perplexing to me what the peer threshold for having a sync target is because I see the "No sync target" message even when there are >20 peers.

**Frequency:**
The duty cycle of actual syncing vs being frozen appears to be ~50%.

### Versions (Add all that apply)
* Software version: `besu/v22.10.3/linux-x86_64/openjdk-java-19`
* Java version: 
```
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7)
OpenJDK 64-Bit Server VM (build 19.0.2+7, mixed mode)
```
* OS Name & Version: Archlinux - last software update 24 hours ago
* Kernel Version: `Linux ethereum 6.1.3-arch1-1-bcachefs-git #1 SMP PREEMPT_DYNAMIC Thu, 02 Feb 2023 21:04:14 +0000 x86_64 GNU/Linux`
* Virtual Machine software & version:
```
$ qemu-system-x86_64 --version
QEMU emulator version 7.2.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```
* Docker Version: N/A
* Cloud VM, type, size: N/A

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - Full command line:
```
BESU_OPTS=-Xmx8g besu \
    --sync-mode=FULL \
    --data-storage-format=BONSAI \
    --nat-method=NONE \
    --p2p-enabled=true \
    --p2p-host="$EXTERNAL_IP" \
    --p2p-port="$EXTERNAL_PORT" \
    --max-peers=50 \
    --rpc-http-enabled \
    --rpc-http-host=127.0.0.1 \
    --rpc-ws-enabled=true \
    --rpc-ws-host=127.0.0.1 \
    --engine-rpc-enabled \
    --engine-jwt-secret="$JWT_SECRET" \
    --network=mainnet \
    --Xplugin-rocksdb-high-spec-enabled
```
* System info - memory, CPU
host has a Ryzen 9 7950x, 64GB of DDR5-6000, and 2 SSDs configured as a bcachefs cache pair - 118GB Intel Optane P1600X, 4TB Samsung 870 QVO

---
[besu.log](https://github.com/hyperledger/besu/files/10611285/besu.log)
I'm re-running besu with loglevel DEBUG and can post that here in a few hours.

**Comment by madenmud** [comment]
I have same issue with 23.1.0-RC1.

**Comment by non-fungible-nelson** [comment]
@macfarla - related to peering stalling in sync? Not sure if not using snap will impact our peering changes.  

And one note here - when using bonsai with a full archive node, you will not have immediate access to historical state. Would recommend FOREST or tweaking understanding and tweaking [this configuration option](https://besu.hyperledger.org/en/latest/public-networks/reference/cli/options/#bonsai-maximum-back-layers-to-load)

**Comment by non-fungible-nelson** [comment]
@pinges tagging you as well.

**Comment by macfarla** [comment]
@ahamlat looks like you're running an archive node - have you run into this issue?

**Comment by duncancmt** [comment]
FWIW, 23.1.0 hasn't fixed this. I'm also observing that besu sometimes freezes _**without**_ the "No sync target" message at all. Sometimes for hours. Here's an example log from before I upgraded (the behavior is the same on 23.1.0).

Whether or not I run the consensus client concurrently does not make a difference on the observed behavior.

[besu.log](https://github.com/hyperledger/besu/files/10787388/besu.log)

**Comment by macfarla** [comment]
we would be interested to see your DEBUG logs - even if you turn it on for a few hours - since it's an hour or so in between stalls. 
You could try changing max-peers to 25. 50 might be too many - there's a CPU and network overhead involved. 

We need to improve this message - it means that you have 5 peers but they might not turn out to be useful - each one needs to be checked.
`2023-02-09 13:21:16.524-05:00 | nioEventLoopGroup-3-4 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 5
`

**Comment by duncancmt** [comment]
Do you have a good place to upload the compressed logfile? Even with `gzip -9` it's over 25MiB. `xz` is _much_ better (<10MiB), but GitHub doesn't like that extension.

I originally set `--max-peers` higher in an attempt to fix the observed behavior. Nothing changes when it's set down to 25 from 50. When besu is frozen, the CPU is near-idle and network usage is <1% of my link's speed.

**Comment by Gabriel-Trintinalia** [comment]
https://github.com/hyperledger/besu/pull/5119 - making this log message consistent with other sync methods

**Comment by macfarla** [comment]
@duncancmt dropbox for the logfile?

**Comment by duncancmt** [comment]
I ended up using mega. Here's the logfile; it's about 360M uncompressed.

[besu.log.xz](https://mega.nz/file/NFUjkBJT#GDOcRHzcU7_BefFSVBCURfu7WNX_FJ3LTNFTvpANqTU)

**Comment by duncancmt** [comment]
I tried switching to GraalVM. It did not help.

**Comment by duncancmt** [comment]
23.1.1 (i.e. #5140 ) does not appear to have fixed the problem. I'm still observing that besu stops for long periods, consuming no CPU or disk IO and printing no log messages other than "Execution engine not called in 120 seconds, consensus client may not be connected". Would it help to post another DEBUG log?

**Comment by Gabriel-Trintinalia** [comment]
I would be interested in another DEBUG log if you could provide us

**Comment by duncancmt** [comment]
New log. The download is 175M, but the uncompressed file is 2.3G

[besu.log.xz.1](https://mega.nz/file/gE1y1LDL#T9GXAcJ4EHAHL0k-B9B1xMhJmpMPfjyy9JKV1_r41h0)

**Comment by duncancmt** [comment]
v23.1.2 also does not fix this issue. I have another DEBUG log to upload, if that would be helpful to you.

**Comment by macfarla** [comment]
Hi @duncancmt it's been a while since there was activity on this GH issue - however in the meantime we have made [numerous improvements to sync and peering](https://github.com/hyperledger/besu/blob/main/CHANGELOG.md). I'm going to close this ticket since it is quite stale - please open a new ticket if you're still having issues!
