### ISSUE TITLE
Recent getBlockByNumber changes caused Goerli sync issue

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#5064]
This commit caused an issue when syncing fresh goerli nodes: https://github.com/hyperledger/besu/commit/9ceebc4a57f648ed412ed6dcbc12a42699fffe54

`
{"@timestamp":"2023-02-07T21:49:39,513","level":"INFO","thread":"EthScheduler-Workers-0","class":"CoinbaseHeaderValidationRule","message":"Invalid block header: No clique in/out voting may occur on epoch blocks (7470000)","throwable":""}
{"@timestamp":"2023-02-07T21:49:44,311","level":"WARN","thread":"EthScheduler-Services-800 (downloadHeaders)","class":"PipelineChainDownloader","message":"Invalid block detected (BREACH_OF_PROTOCOL). Disconnecting from sync target. Header failed validation.: Invalid block at #7470000 (0xaaea1696007267a518ee5c6550742f58c81333e71cdee6c38dc2403b628816e1)","throwable":""}
`

The issue was experienced during 23.1.0-RC2 burn-in, specifically on four of these nodes after needing to resync due to another bug: https://github.com/ConsenSys/protocols-aws-inventories/blob/master/clc-goerli.yml

These were all BONSAI, mostly X_SNAP but one FAST.
I then span up a further three nodes to confirm and got the same error with FOREST (with X_SNAP).

The issue was **not experienced while syncing sepolia**: https://github.com/ConsenSys/protocols-aws-inventories/blob/master/clc-sepolia.yml

I am yet to confirm mainnet is unaffected as nodes are still syncing.

**Comment by jframe** [comment]
This was commit reverted on main https://github.com/hyperledger/besu/pull/5063

**Comment by siladu** [comment]
To save a full resync, I already have a node with a database that is synced to just before the issue will occur: 
*dev-besu-clc-teku-ohio-goerli-23.1.0-RC2-snap*

`{"@timestamp":"2023-02-08T04:04:07,623","level":"INFO","thread":"EthScheduler-Services-29 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 7329800 of 8452736 (86%)","throwable":""}`

Issue will occur at block #7470000

**Comment by iamhsk** [comment]
Related to #4789
