### ISSUE TITLE
Issue in smart contract deploy

### ISSUE THREAD

**Issue by Neoblock8** [hyperledger/besu#5069]
Hi,
   Running private network in besu. Facing issue while deploying below **rollup contract** in this network. It will results **internal error**. 
   How to deploy this contract?
   
   **contract:** https://goerli.etherscan.io/address/0x60e32d4a74ecab8e86d4649735022ab3449af14e#code

**Comment by non-fungible-nelson** [comment]
Can you provide more information on what errors you are seeing in besu and version information? Your genesis file and node configuration will be useful as well.
