### ISSUE TITLE
How can I find some reference about online (as opposed to 'offline') pruning?

### ISSUE THREAD

**Issue by lurais** [hyperledger/besu#5089]
hello, Are you working on online (as opposed to 'offline') pruning? is that completed now ? where is the discussion about the way you take?

**Comment by daniellehrner** [comment]
Besu has implemented the Bonsai data storage format, which does online pruning, already last year. 

https://besu.hyperledger.org/en/stable/public-networks/concepts/data-storage-formats/#bonsai-tries

I'll close this comment for now. If you should have other questions please feel free to reach out on Discord: https://discord.com/channels/905194001349627914/938504958909747250
