### ISSUE TITLE
Add detail messages to particular cases for INVALID_PARAMS

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5098]
"invalid params" error code is used a lot, but always with the same message, which can hide a lot of detail. 

eg for #4212 it's hard to get any clues as to the nature of the problem. Could add further values to the JsonRpcError enum with the same code -32062 but with different messages that might help the user diagnose or at least report issues
eg
missing param
wrong type for param
unable to decode param (eg RLP)

JsonRpcError
  INVALID_PARAMS(-32602, "Invalid params"),

**Comment by macfarla** [comment]
Another instance  - when transaction type is incorrect, eth_sendRawTransaction can respond with invalid params but it's not obvious what the problem is https://discord.com/channels/905194001349627914/938504958909747250/1108931495797727354

**Comment by chenqping** [comment]
yes, invalid params don't indication where is wrong

**Comment by macfarla** [comment]
changed default to internal error not invalid params https://github.com/hyperledger/besu/pull/5506

**Comment by macfarla** [comment]
suggest to follow the pattern used here for peer disconnect reasons https://github.com/hyperledger/besu/pull/6899
