### ISSUE TITLE
Testing of Github Merge Queue 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5102]
https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

Testing of merge queue for Github to avoid conflicts going forward.

**Comment by macfarla** [comment]
I tried merge queue in a test repo - works as expected. 
- PR A  with no conflicts merged without trouble
- PR B with conflict resulting from PR A was removed from the merge queue
- PR C with conflict resulting from PR A was able to be added to the merge queue - it's still sitting there waiting for the conflict to be resolved
- PR D reverting an earlier PR was merged without trouble
I still have some unmerged PRs sitting there if anyone else wants to play with it

**Comment by macfarla** [comment]
Squash commits?
I set the settings in the test repo to match besu - ie allow squash merging. The "add to merge queue" button doesn't show any options around squash commits, and the PR I created with multiple commits did not get squashed. (This commit and the two before it are from the same PR https://github.com/daisy-row/vigilant-octo-umbrella/commit/78576553486c62e44eb17837e870d537ab34d5c6)  Not sure if there's something else in Besu repo settings that would make this behave differently.

**Comment by macfarla** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue

**Comment by macfarla** [comment]
Now we have merge queue + squash commits
https://github.com/daisy-row/vigilant-octo-umbrella/commits/main

**Comment by macfarla** [comment]
added DCO as a required check

**Comment by macfarla** [comment]
I think we would need to make this change ie add `merge_group` trigger to CI config

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Comment by macfarla** [comment]
DCO strikes again - the DCO that we use https://github.com/tim-actions/dco does not support merge_group event trigger (neither does it support merge events which is why we have this open issue https://github.com/hyperledger/besu/issues/4837) - we can investigate other dco options (write our own? dcoapp doesn't support merge queue yet either https://github.com/dcoapp/app/issues/199). But DCO has to be a required check at that point, there isn't a separate set of checks for the merge queue. 

So for now have turned off merge queue. Back to status quo.

**Comment by macfarla** [comment]
https://wiki.hyperledger.org/display/BESU/GitHub+Merge+Queue

**Comment by macfarla** [comment]
https://github.com/hyperledger/besu/pull/5207

**Comment by macfarla** [comment]
Merge queue update - I think we have a solution! 

Added a separate "dco" check that is triggered by the merge_group event but doesn't check anything https://github.com/hyperledger/besu/pull/5207 (existing dco check runs on pull_request event as before) - and merge queue is happily running it eg this PR https://github.com/hyperledger/besu/pull/5209 is merging via the merge queue - and here is the dco job - https://github.com/hyperledger/besu/actions/runs/4402919772/jobs/7710635563
