### ISSUE TITLE
API JSON RPC not working (parse error)

### ISSUE THREAD

**Issue by Danniilpz** [hyperledger/besu#5109]
I have followed this tutorial from the wiki: https://besu.hyperledger.org/en/stable/private-networks/tutorials/clique/
After creating a Clique Network, apparently working well, I can't use the API JSON RPC. When I make any CURL call, I receive a parse error. For example, this one from the tutorial:
curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' localhost:8545
{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}

**Comment by non-fungible-nelson** [comment]
have you tried this using the postman collection found [here](https://besu.hyperledger.org/en/latest/public-networks/how-to/use-besu-api/json-rpc/?h=json+rpc+api)? or have you otherwise handled this issue?

**Comment by Danniilpz** [comment]
Finally I could handled it using postman with the wscat requests.
