### ISSUE TITLE
Add Block Import Time Metric

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#5111]
We log out the block processing+import time:

`{"@timestamp":"2023-02-18T21:33:24,311","level":"INFO","thread":"vert.x-worker-thread-0","class":"AbstractEngineNewPayload","message":"Imported #2,929,002 / 2 tx / base fee 7 wei / 207,637 (0.7%) gas / (0x7a8f1361328a384f1b8b25075fd7053917e024c35bce74b735d2ca3ac24a8c24) in 0.009s. Peers: 23","throwable":""}`

but it would be good to expose this as a metric too for easy aggregation and analysis.

Consider adding to the Besu Full Grafana Dashboard

**Comment by ahamlat** [comment]
Hi @siladu, we already have this metric in Besu Full Dashboard, and most of our performance improvements are based on this metric : Besu Full Dashboard -> Execution Engine Details -> Check "engine_newPayloadV1 time (quantile=0.5)"  and "engine_newPayloadV1 time (quantile=0.95)". You have to get the last version from Grafana.com

**Comment by siladu** [comment]
Thanks @ahamlat didn't realise that.
