### ISSUE TITLE
Issue "Unable to copy Layered Worldstate" persists in v23.1.0

### ISSUE THREAD

**Issue by Chozowarrior** [hyperledger/besu#5112]
Yesterday I updated to Besu 23.1.0 and today I ran into a corrupted database error on Ethereum mainnet which a restart does not resolve. Have never got a similar issues like this with Besu since the merge.

Config:
 --network=mainnet 
 --sync-mode=X_CHECKPOINT
 --data-storage-format=BONSAI

<img width="1145" alt="2023-02-19 11_50_28-beacon@ssa-Blade_ ~" src="https://user-images.githubusercontent.com/43718356/219976899-924baadd-9f96-4286-b96d-79e538a698de.png">

**Comment by non-fungible-nelson** [comment]
Hi there - please update to the latest 23.1.2 which has a bonsai rewrite that should fix this issue! Let me know if this is not the case.
