### ISSUE TITLE
evm t8n support reward -1

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#5124]
```
Invalid value for option '--state.reward': cannot convert '-1' to Wei (java.lang.NumberFormatException: Illegal leading minus sign on unsigned string -1.)
```

state.reward  = -1  means to just calculate state hash without coinbase touch or mining rewards to be applied.

**Comment by shemnon** [comment]
Where is this documented in the t8n docs?

**Comment by winsvega** [comment]
You mean this docs?

https://ethereum-tests.readthedocs.io/en/latest/t8ntool-ref.html

It's not up. We actually doesn't have t8n versioning which we should

**Comment by shemnon** [comment]
Would PR #5138 address this? While I can not touch coinbase and not use the default reward, the TX processing will always send fees to the coinbase.  Not paying coinbase fees is going to be really hard to unwind.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/issues/1165

**Comment by winsvega** [comment]
coinbase fee is paid, it is just 0. if no transactions there is no fee.

**Comment by non-fungible-nelson** [comment]
Did #5138 complete this issue?

**Comment by winsvega** [comment]
Seems to work, thanks!
