### ISSUE TITLE
Commit for tag 23.1.0 missing 

### ISSUE THREAD

**Issue by ph03** [hyperledger/besu#5130]
Seems like the commit 

https://github.com/hyperledger/besu/commit/058febab0f535730b1c264671bede0a170e70153

for tag

https://github.com/hyperledger/besu/releases/tag/23.1.0

and therefore the tag itself is missing from the current repo:

![image](https://user-images.githubusercontent.com/390527/220849646-495e189a-70df-4424-b961-2ec3628df631.png)

Which commit is closest / can be used in place of the tagged `23.1.0` version (perhaps `23.1.0-RC2`)?

**Comment by garyschulte** [comment]
Thanks, we just now saw this issue, sorry for the slow resolution.  This is an artifact of auto-creating tags on publish.  Moved the tag to 79c1a97fc862fc359cf5c79790f1f17f1efcac9e which was the sha used for publishing the release from branch `release-23.1.x`
