### ISSUE TITLE
Calls to eth_gasEstimate and eth_call being cached somewhere?

### ISSUE THREAD

**Issue by antonydenyer** [hyperledger/besu#5147]
When investigating improvements to eth_gasEstimate as part of https://github.com/hyperledger/besu/pull/5142 I found the following strange issue.

On goerli I have deployed the following contract at address `0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da` 

## Note!!! There are currently no other transactions to this contract at time of writing. ##
Submitting transactions to this contract it will affect the gas required!!!  

```solidity
pragma solidity >=0.7.0 <0.9.0;

contract TestDepth {
    uint256 public x;

    function depth(uint256 y) public {
        // bool result;
        if (y > 0) {
            bytes memory call = abi.encodeWithSignature("depth(uint256)", --y);
            (bool result,) = address(this).delegatecall(call);
            require(result);
        }
        else {
            // Save the remaining gas in storage so that we can access it later
            x = gasleft();
        }
    }
}
```

When performing an `eth_estimateGas` on different clients I get different results. My expectation was that besu was overestimating the required gas compared to other clients. It turns our the estimate provided can be incorrect.

### Steps to Reproduce (Bug)

Using the following test code:
```js
for (const depth of [1,2,3,4,5,10,65]) {

    const data = contract.encodeFunctionData('depth', [depth]);

    const estimate = await provider.estimateGas({
        to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
        data: data
    })
    
    const result = await provider.call({
	to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
	data: data,
	gasLimit: estimate.toNumber()
    })

    console.log(`Depth ${depth} has gasEstimate ${estimate.toNumber()} eth_call result ${result}`)

}
```
With Geth/v1.10.23-stable-13ddb046/linux-amd64/go1.18.10 

```
Depth 1 has gasEstimate 45554 eth_call result 0x
Depth 2 has gasEstimate 47387 eth_call result 0x
Depth 3 has gasEstimate 49249 eth_call result 0x
Depth 4 has gasEstimate 51141 eth_call result 0x
Depth 5 has gasEstimate 53063 eth_call result 0x
Depth 10 has gasEstimate 63139 eth_call result 0x
Depth 65 has gasEstimate 246462 eth_call result 0x
```

With `besu/ConsenSys/v23.1.1-dev-b0daf148/linux-x86_64/openjdk-java-17` I get some funny results. Occasionally I would get an error between the estimate and call but after a few attempts I consistently get something like:

```
Depth 1 has gasEstimate 48337 eth_call result 0x
Depth 2 has gasEstimate 21204 eth_call result 0x
Depth 3 has gasEstimate 21204 eth_call result 0x
Depth 4 has gasEstimate 21204 eth_call result 0x
Depth 5 has gasEstimate 21204 eth_call result 0x
Depth 10 has gasEstimate 21204 eth_call result 0x
Depth 65 has gasEstimate 21204 eth_call result 0x
```

Well this is really strange, the value definitely shouldn't be lower. After investigating further it would appear that there's something very funky going on with either caching on shared state between calls. If I run the script in quick succession the first result changes between `48337` and `21204`! Very odd indeed.

What's also strange is that the eth_call with a gasLimit of `21204` should definitely fail but doesn't! 

Because of this it means you can do things that are clearly nonsense. 

```js
const depth = 10
const data = contract.encodeFunctionData('depth', [depth]);

const estimate = await provider.estimateGas({
    to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
    data: data
})

const result = await provider.call({
  to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
  data: data,
  gasLimit: 21204
})

console.log(`Depth ${depth} has gasEstimate ${estimate.toNumber()} eth_call result ${result}`)
```

All of this assumes that the contract has been deployed and no transactions have occurred against it. 

I do not believe this to be an issue with OPCODE pricing or gas usage calculation in the EVM. I suspect that somehow the world state from the previous `eth_call` or `eth_estimateGas` is lingering somewhere so as to reduce the amount the gas required.

If you deployed the contract, then performed a call to `depth(1)` then the subsequent call to that contract would indeed have a lower gas limit requirement.

To test the theory I tried the following:

```js

const sleep = (ms) => new Promise((resolve) => {
  setTimeout(resolve, ms);
});


const nextBlockToBeMined = async () => {
  const block = await provider.getBlock('latest');

  for (let i = 0; i < 24; i += 1) {
    const nextBlock = await provider.getBlock('latest');
    if (nextBlock.number > block.number) {
      break;
    }
    await sleep(1000);
  }
};


for (const depth of [1,2,3,4,5,10,65]) {
    const data = contract.encodeFunctionData('depth', [depth]);

    await nextBlockToBeMined()

    const estimate = await provider.estimateGas({
        to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
        data: data
    })
    
    const result = await provider.call({
	to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
	data: data,
	gasLimit: estimate
    })

    console.log(`Depth ${depth} has gasEstimate ${estimate.toNumber()} eth_call result ${result}`)
}

```
Which yielded something more sensible:

```
Depth 1 has gasEstimate 48337 eth_call result 0x
Depth 2 has gasEstimate 50685 eth_call result 0x
Depth 3 has gasEstimate 53095 eth_call result 0x
Depth 4 has gasEstimate 55567 eth_call result 0x
Depth 5 has gasEstimate 58104 eth_call result 0x
Depth 10 has gasEstimate 71802 eth_call result 0x
Depth 65 has gasEstimate 401088 eth_call result 0x
```

The problem now is that there's still something funny going on between `eth_estimateGas` and `eth_call`. Which means I can do silly things like .... 

```js
for (const depth of [1,2,3,4,5,10,65]) {
    const data = contract.encodeFunctionData('depth', [depth]);

    await nextBlockToBeMined()

    const estimate = await provider.estimateGas({
        to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
        data: data
    })
    
    const result = await provider.call({
	to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
	data: data,
	gasLimit: estimate - 1000
    })

    console.log(`Depth ${depth} has gasEstimate ${estimate.toNumber()} eth_call result ${result}`)

}
```

And everything still works !!! Presumably because the `eth_estimateGas` is somehow committing/caching world state.

So I thought I'd write a simple binary search to get the required gas for a call using trial and error with `eth_call`. 

```js
let high = 45554
let low = 21204
const depth = 1
const data = contract.encodeFunctionData('depth', [depth]);


while (low + 1 < high) {
  mid = Math.ceil((high + low) / 2);
  await nextBlockToBeMined()

  try {
    const result = await provider.call({
      to: "0x9AAe0D2009a14cB6c1140a9C5715Bb345690b0da",
      data: data,
      gasLimit: mid
    })
    
    if (result != "0x") {
      low = mid;
    } else {
      high = mid;
    }
    console.log(`High ${high} Low ${low} Mid ${mid}`)
  } catch {
    console.log(`ERROR High ${high} Low ${low} Mid ${mid}`)
    low = mid;
  }
}
```

Observations:

1. When the gas is too low you get an internal server error rather than an rpc error.
2. You need to wait for a block before you can perform an eth_call again (as discussed).
3. You can use a lower gas limit on `eth_call` than you actually need.
4. You can use a lower gas limit than the gas used!

It would appear that `eth_call` is just flat out broken when it comes to respecting gas limits.

## Summary 

Th transaction simulator appears not be calculating gas correctly. I believe the problem to be isolated to just `eth_call` and `eth_estimateGas` I do not believe their is any issues when mining transactions. 

**Expected behavior:**
Consistent eth_gasEstimate results based on the LATEST block 
eth_call to correctly use the gasLimit provided and to behave the same as a mined transaction

**Actual behavior:** 
Inconsistent eth_gasEstimate results 
Invalid eth_gasEstimate results returned
Incorrect eth_call behaviour - calls succeeding when the should fail

**Frequency:** 
90% of the time

### Versions (Add all that apply)
besu/ConsenSys/v23.1.1-dev-b0daf148/linux-x86_64/openjdk-java-17

**Comment by non-fungible-nelson** [comment]
@shemnon - any insight on this? Or not your area of concern.

**Comment by jframe** [comment]
I've tested this on a synced goerli node with Besu v23.1.1-dev-b0daf148 and with 23.1.2 and I get these results when running the javascript script. Which is the same as what given in the 2nd script with the wait for the next block to be mined. So not getting the issue on the node I deployed to test this on.

```
Depth 1 has gasEstimate 48337 eth_call result 0x
Depth 2 has gasEstimate 50685 eth_call result 0x
Depth 3 has gasEstimate 53095 eth_call result 0x
Depth 4 has gasEstimate 55567 eth_call result 0x
Depth 5 has gasEstimate 58104 eth_call result 0x
Depth 10 has gasEstimate 71802 eth_call result 0x
Depth 65 has gasEstimate 401088 eth_call result 0x
```

This was with Bonsai though. Were you using Bonsai or Forest to test on?

**Comment by antonydenyer** [comment]
Agreed, it appears to have sorted itself out. 

https://github.com/hyperledger/besu/pull/5142

should provide some coverage to prevent it from happening again.
