### ISSUE TITLE
Upgrade Besu gradle wrapper to 8.0.1

### ISSUE THREAD

**Issue by usmansaleem** [hyperledger/besu#5152]
### Description
Upgrade Besu gradle wrapper to 8.0.1 so that the build keep using latest Gradle features.

### Acceptance Criteria
* Besu Gradle build is upgraded to 8.0.1

### Additional Information
* Dependent on https://github.com/web3j/solidity-gradle-plugin/pull/56

**Comment by macfarla** [comment]
not relavant anymore ... we are on gradle 8.7.0 now
