### ISSUE TITLE
The name "enclave key" is used for different concepts in the code which is confusing

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#517]
The name "enclave key" is used to describe 2 different things in besu

The (public) key used in Orion that is used to encrypt messages for members of privacy groups. In besu this key is used to identify members of a privacy group, e.g. privateFor and privateFrom

The hash of an encrypted private transaction. This hash is placed in a private marker transaction and is used to retrieve the private transaction from Orion.

Come up with good names for these different concepts (or at least for one of the usages) and replace as needed.

**Comment by macfarla** [comment]
looks like we use enclaveKey and transactionEnclaveKey for the 2 different concepts. So provided those terms are used consistently, renaming one shouldn't be to difficult

**Comment by pinges** [comment]
I propose that we change variables that refer to the hash of the encrypted private transaction to 
**privateTransactionKey**
so nobody get's confused when reading the code.
Other options that I have considered are:

- privateTransactionAddress
- hashOfEncryptedPrivateTransaction
- privateEncryptionKeyInEnclave
- keyInEnclave

**Comment by pinges** [comment]
The team came up with this one:

**PrivateTransactionLookupId**

**Comment by pinges** [comment]
While changing this we should change 

enclaveKey to **participantEnclaveKey**

**Comment by macfarla** [comment]
checked for "orion" - no occurrences, other than the OrionTestHarness and Enclave type which is directly tied to Orion. Everywhere else we use "enclave"
