### ISSUE TITLE
eth_call returning 0x0 for latest, safe, finalized block

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#5175]
Report from https://discord.com/channels/905194001349627914/938504958909747250/1081825458561232947

Similar to https://github.com/hyperledger/besu/issues/5038

Problem is here: https://github.com/hyperledger/besu/blob/a2dedb0b2c7980cdc35db8eb4c094f2eb0dc7deb/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java#L168

Fix for #5038 is the following, can probably so something similar: https://github.com/hyperledger/besu/pull/5076/files#diff-c0632ac4ed64edd521a0489727f7160ddc943d088eae3398867a8b769671d041R861

**Comment by non-fungible-nelson** [comment]
Regression in 23.1.0.  PR #5123 fixes this, but can mitigate with stop-gaps if BonsaiSafe is not ready before release.
