### ISSUE TITLE
Cannot create an account when one already exists

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#5176]
### Description
When testing PR #5123, I had an issue on bloc 16,763,162 with this message error :  "Cannot create an account when one already exists".

You can find attached Besu logs.
[error_log_PR5123.log](https://github.com/hyperledger/besu/files/10900875/error_log_PR5123.log)

**Comment by garyschulte** [comment]
fixed in [commit](https://github.com/hyperledger/besu/pull/5123/commits/3d92a61cb04fb70d72b9a6486056543bdc3585ef)
