### ISSUE TITLE
Enable HTTP/2 support for the Http JSON-RPC API when TLS is enabled

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu#519]
### Description
As a node operator, I want to enable support for HTTP/2 over TLS so that clients can use HTTP2/multiplexing  to reduce the number of connections to the server and improve performance.

### Acceptance Criteria
* When TLS is enabled server supports both HTTP/1.1 and HTTP/2 (h2) connections

### Additional Information

Simple testing with okhttpclient shows a significant reduction in request time for multiple requests when server enabled for HTTP/2 support. 

one line addition in JsonRpcHttpService.java

httpServerOptions.setUseAlpn(true)

**Comment by usmansaleem** [comment]
Implemented via PR #1145

**Comment by bgravenorst** [comment]
No documentation required.
