### ISSUE TITLE
Sync halts at 99%

### ISSUE THREAD

**Issue by gfukushima** [hyperledger/besu#5191]
### Description
Syncing Goerli with 23.1.1 we hit a scenario where Besu gets stuck at 99% of the block import, see logs below

> {"@timestamp":"2023-03-08T10:03:59,007","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8542800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:04:32,781","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8544800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:05:04,473","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8546400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:05:38,277","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8547200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:06:09,892","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8548400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:06:41,928","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8549600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:07:12,818","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8551000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:07:44,352","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8552600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:08:17,975","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8553400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:08:48,626","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8554400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:09:20,004","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8555400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:09:50,629","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8556600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:10:23,214","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8558000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:10:53,998","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8559400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:11:24,606","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8560200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:11:58,050","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8561000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:12:29,576","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8563000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:13:01,724","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8563800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:13:41,389","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8565000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:14:11,556","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8566400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:14:48,501","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8567600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:15:21,166","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8568400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:15:55,490","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8569800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:16:28,539","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8571000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:17:02,038","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8571800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:17:48,886","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8573200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:18:20,790","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8573800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:18:52,655","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8574800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:19:25,677","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8575800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:20:02,144","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8577200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:20:46,712","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8578000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:21:37,424","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8580400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:22:12,660","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8581400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:22:48,252","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8583200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:23:23,129","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8585200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:24:02,372","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8587200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:24:35,243","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8589000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:25:05,641","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8591600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:25:37,586","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8593200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:26:08,260","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8594200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:26:44,761","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8596200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:27:15,205","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8597000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:27:48,814","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8598800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:28:26,091","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8600200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:29:00,606","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8601600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:29:31,402","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8602600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:30:01,821","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8604200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:30:32,721","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8605400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:31:09,485","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8607600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:31:40,492","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8608600 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:32:17,312","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8610000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:32:47,990","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8611000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:33:18,582","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8612000 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:33:49,990","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8613400 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:34:28,553","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8614200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:35:09,167","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8615200 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T10:35:41,935","level":"INFO","thread":"EthScheduler-Services-39 (importBlock)","class":"FastImportBlocksStep","message":"Block import progress: 8616800 of 8616967 (99%)","throwable":""}
{"@timestamp":"2023-03-08T14:58:08,352","level":"INFO","thread":"Timer-0","class":"DNSResolver","message":"Resolved 426 nodes","throwable":""}
{"@timestamp":"2023-03-08T20:58:08,309","level":"INFO","thread":"Timer-0","class":"DNSResolver","message":"Resolved 426 nodes","throwable":""}

Another similar case has been reported in discord as well: https://discord.com/channels/905194001349627914/1082779291454034002

**Comment by macfarla** [comment]
hypothesis - this will be fixed by #5200 and/or #5178
