### ISSUE TITLE
[Question] RangeStorageEntriesCollector.onLeaf

### ISSUE THREAD

**Issue by halibobo1205** [hyperledger/besu#5222]
### Description
As [RangeStorageEntriesCollector.onLeaf ](https://github.com/hyperledger/besu/blob/main/ethereum/trie/src/main/java/org/hyperledger/besu/ethereum/trie/RangeStorageEntriesCollector.java#L77)  see, why `!values.isEmpty()` is required. 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/82020050/225309407-573c4256-b36c-42b4-806b-eda081470a7f.png">

**Comment by garyschulte** [comment]
@matkt I am inclined to agree.  Whether we have found leaf nodes within the range or not seems immaterial.  If the keyHash exceeds the range, we should stop.  Is ther a non-obvious reason to have a values check here?

**Comment by matkt** [comment]
If I remember correctly this class should be used for Snapsync. According to the specification if no leaf is in the range we take the first after the range.

**Comment by non-fungible-nelson** [comment]
@halibobo1205 does this answer your question ? Closing for now but please continue the discussion thread if you are looking for more info.
