### ISSUE TITLE
`priv_call` doesn't show a revert message, but "invalid params"

### ISSUE THREAD

**Issue by CMajeri** [hyperledger/besu#5223]
### Description
As an user, I want to see revert messages on `priv_call` so that I can see errors. 

### Acceptance Criteria
I run `priv_call` on a private contract, the call reverts, and I see the revert reason.

### Steps to Reproduce (Bug)
- Create a contract wih a revert in it in a public transaction.
- Trigger a revert using `eth_call`.
- Notice that the revert reason is there.
- Create the same contract in a private transaction.
- Call it using `priv_call`
- Notice that the revert reason isn't there

^ Is that expected or actually a bug?
I _do_ see the revert reason when the tx gets mined, but I get "invalid params" when I just call it using `priv_call`.
This is _very_ impractical when simulating calls to see if they'll work before sending them out.

**Comment by non-fungible-nelson** [comment]
@macfarla - related to RPC cleanup/invalid params? maybe add to #5098 ?

**Comment by NickSneo** [comment]
Hey @macfarla , are you working on this issue in your draft PR - https://github.com/hyperledger/besu/pull/5241 ?

**Comment by macfarla** [comment]
@NickSneo that PR won't help private transactions, and it's only to expose more details about the "invalid params". 
This issue is about the revert reason being hidden for private tx. So I think it's unrelated. Feel free to pick this one up!

**Comment by NickSneo** [comment]
@macfarla okay cool, thanks! Will pick this up!

**Comment by NickSneo** [comment]
Closing ticket as issue fixed with MR - https://github.com/hyperledger/besu/pull/5369
