### ISSUE TITLE
Besu - Local permission (with Node Allowlist)

### ISSUE THREAD

**Issue by gokulraj17687** [hyperledger/besu#5227]
Hello Everyone, 
I am using local permission concept to restrict the nodes. My environment is under AWS ECS and has DNS mapped. I have enabled --xdns-enabled & --xdns-update-enabled param in my network. Have a permissions_config.toml file with list of all enodes that can connect. While deploying the network, the permission file is got deployed into the container.  Even the DNS and IP mapping is also getting resolved after few mins of node start or when I do a permission file reload throught api call. Also I have the same permission config file for all the nodes.
When I pull the Allowlist through api call, it gives the result with all enodes along with DNS to connect with the node.
But if I do a net_peerCount, the result is 0x0, means the nodes are not connected with each other. There was no log with error. Then I have to a redeploy all the nodes to make it sync and then the peer count comes with exact number of nodes.
Any idea, why the behaviour is like this? Is anything I am missing here?
<@680245613258211336> We were able to check further on this and below is the scenario where discovery fails when we enable node local permisioning.

We are starting boot node with the initial list of peers having permission to network. The permission list is updated with Enode URL having hostname rather than IP. Also we have enabled BESU_DNS_ENABLED and BESU_XDNS_UPDATE_ENABLED parameters for this. As none of the Besu nodes are currently up and when we call the Perm method ( curl
-X POST - - data ‘{" jsonrpc": "2.0- "method":"perm getNodesAllowlist", "params": [], "id": 1}’ http://bootnode_hostname:8545 ) to list the permitted node list from boot node, its giving the enode addresses of all nodes with loopback IP instead of hostname which we passed in permission TOML file. In our environment, Besu nodes hostname is only resolvable after the node starts as we are using discovery to get the DNS configured.
Now if we start any of the besu nodes - it won't be able to communicate to bootnode for discovery as the permission list of bootnode is still with 127.0.0.1. Post besu node starts and the corresponding hostname is resolvable - when we do a reload of permission list in bootnode - the enode URL of node will get updated with the hostname entry as we given in permission TOML file ( enode://enodeaddrss@DNS_NAME: p2p_port )
Even after the boot node permission list is updated with host entries
- besu node is not able to do the discovery until the node is restated.

Following are our queries

How we can retrigger the connection to bootnode from besu nodes to do the discovery again?

Why the permission list is giving loopback IP when we are providing hostnames in the TOML file?

This has been raised in discord channel(Topic : Besu-Local permissioning issue) and as advised raising an issue here

**Comment by NickSneo** [comment]
Hey @gokulraj17687 ,

Can you also attach the logs for different scenarios.
Set log level to trace - https://besu.hyperledger.org/en/stable/public-networks/reference/api/#admin_changeloglevel
and then collect all the logs.

Thanks!

**Comment by NickSneo** [comment]
@macfarla There has been no reply from the reporter @gokulraj17687 
Shall we close or wait for more time?

**Comment by NickSneo** [comment]
Closing issue, as no reply from the issue reporter.
@gokulraj17687 You can reopen the issue if you face the error again. Thanks!!
