### ISSUE TITLE
retesteth support: eth_getblockbyhash

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#523]
can you please add `https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash` method to the RPC. I use this for better post condition check when chain reorg happens in the tests. 

also I am adding besu client to tests automation: http://retesteth.ethdevops.io check it out.

**Comment by sbs2001** [comment]
I might be  wrong but, I think this might be what you are looking for  https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_getblockbyhash

**Comment by winsvega** [comment]
The method appears to be not available in `besu retesteth` mode.

**Comment by shemnon** [comment]
That method was not enumerated in the docs - https://github.com/ethereum/retesteth/wiki/RPC-Methods

**Comment by winsvega** [comment]
Yes. I recently start using it for chain reorg tests better post condition verification.
