### ISSUE TITLE
Configurable Allow/Reject List in Besu Transaction Pool

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5243]
## Description ## 

As a user, I would like to have an allowlist/reject list for certain types of transactions. Besu should have an aware reject-list where when transactions from certain (configurable) addresses enter my mem pool, I can eject them without much fuss. Or specify a certain allowlist where _only_ transactions from this list are accepted. This can be useful for certain private networks and public networks use pertaining to regulations or ethical concerns. 

## Acceptance Criteria ## 

Reject List
1. User defines a list of addresses that they want to reject from executing. 
2. Besu's mem-pool receives a transaction from an address on this list. 
3. Besu's mem-pool ejects the transaction and logs in the console what it has done. 
4. User does not execute reject list address tx.

Allow List
1. User defines a list of addresses from where they are interested in executing transactions. 
2. Besu's mem-pool receives a transaction from an address on this list. 
3. Besu's mem-pool executes the transaction. 
4. User executes accept list address tx.

2a. Besu's mem-pool receives a transaction from an address _not_ on the list.
3a. Besu's mem-pool ejects the transaction outright. 
4a. User does not execute transactions not on the allow-list.

**Comment by non-fungible-nelson** [comment]
@fab-10 does any of the recent tx pool work make this simpler to implement?

**Comment by fab-10** [comment]
not really, and I think it is better to delegate this feature to a plugin, the plugin interface could allow for generic added validation/checks of the tx on top of the standard validation /checks done by default-

**Comment by macfarla** [comment]
@Brindrajsinh-Chauhan are you still working on implementing this as a plugin? We're also actively collecting feedback with the aim to improve docs and devx of the plugin API!

**Comment by jflo** [comment]
Any interim work/notes/designs might be useful for EIP-7547 so users could write their own censorship detection heuristics.

**Comment by macfarla** [comment]
@Brindrajsinh-Chauhan are you still working on implementing this as a plugin? We're also actively collecting feedback with the aim to improve docs and devx of the plugin API!

**Comment by krsh24** [comment]
@matthew1001 raised a valid point in the linked issue ticket #6521, account permissioning which can be controlled via smart contract provides similar functionality that this spec requires. Do we need a plugin to achieve a similar functionality? Unless I got this wrong. I currently use GoQuorum and I use a smart contract-based whitelist to control the accounts whitelist. Both Besu and GoQuorum have this similar feature.

```
@CommandLine.Option(
      names = {"--permissions-accounts-contract-address"},
      description = "Address of the account permissioning smart contract",
      arity = "1")
  private final Address permissionsAccountsContractAddress = null;

  @CommandLine.Option(
      names = {"--permissions-accounts-contract-enabled"},
      description =
          "Enable account level permissions via smart contract (default: ${DEFAULT-VALUE})")
  private final Boolean permissionsAccountsContractEnabled = false;
```

**Comment by fab-10** [comment]
thanks @krsh24 for the details on how to achieve this with permissioning.

@non-fungible-nelson I think we can close this ticket, since or via plugin or via permissining contracts, we are not implementing this in core Besu, wdyt?

**Comment by non-fungible-nelson** [comment]
We can share some relevant details as we update plug-in docs.
