### ISSUE TITLE
QBFT validator smart contract method does not work with london fork with Fees.

### ISSUE THREAD

**Issue by D3athGr1p** [hyperledger/besu#5249]
I want to use EIP-1559 fee stucture but when i try using london fork it does not work with validator smart contract. it works fine with blockheader selection method. i tried both way using ```londonBlock: 0``` and 
```
"transitions": {
      "qbft": [
        {
          "block": 25,
          "validatorselectionmode": "contract",
          "validatorcontractaddress": "0x42699A7612A82f1d9C36148af9C77354759b210b"
        }
      ]
    }
```

but i'm getting this error
![image](https://user-images.githubusercontent.com/86771928/226526894-06e906c4-647c-46fe-99a0-1b840f7b60b9.png)

as for genesis file  :
```
{
  "config": {
    "chainId": 878145,
    "londonBlock": 0,
    "berlinBlock": 0,
    "qbft": {
      "blockperiodseconds": 2,
      "epochlength": 30000,
      "requesttimeoutseconds": 4,
      "blockreward": "1500000000000000000"
    },
    "transitions": {
      "qbft": [
        {
          "block": 50,
          "validatorselectionmode": "contract",
          "validatorcontractaddress": "0xb9A219631Aed55eBC3D998f17C3840B7eC39C0cc"
        }
      ]
    }
  },
  "nonce": "0x0",
  "timestamp": "0x58ee40ba",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "f17f52151EbEF6C7334FAD080c5704D77216b732" : {
      "balance" : "0x446c3b15f9926687d2c40534fdb56400"
    }
  },
  "extraData": "0xf87aa00000000000000000000000000000000000000000000000000000000000000000f8549447349b0e16718f7439261616c48fd1b92a9d64d7945c2ec9937230a20ab9a6008bc32952d0551c14fc94903e1eedcb60cc27a386ee2879274b2a445bd72a9457a71c05d16403165c21ce27914573ef5ffad819c080c0"
}
```

I also tried londonBlock at 55 and my `"validatorselectionmode": "contract"` at block 50 but still got same issue.

as for validator smart contract I'm using [ConsenSys](https://github.com/ConsenSys/validator-smart-contracts) and this works fine without london block

**Comment by notatestuser** [comment]
The solution is here: https://github.com/hyperledger/besu/issues/3883#issuecomment-1162623267

Or add `"zeroBaseFee": true` to the `config` section.

**Comment by D3athGr1p** [comment]
Still this is not working for me

> The solution is here: [#3883 (comment)](https://github.com/hyperledger/besu/issues/3883#issuecomment-1162623267)
> 
> Or add `"zeroBaseFee": true` to the `config` section.

**Comment by siladu** [comment]
@D3athGr1p - I have recreated your issue. Enabling DEBUG reveals what is likely the actual problem:
> 2023-03-28 14:23:53.040+10:00 | BftProcessorExecutor-QBFT-0 | DEBUG | MainnetTransactionProcessor | Invalid transaction: gasPrice is less than the current BaseFee 

Using validator contract mode results in an internal "transaction"...it's actually a simulated transaction, similar to eth_call which _shouldn't_ cost any gas. Seems the bug is related to requiring a non-zero gas price regardless. Looking into it now.

**Comment by D3athGr1p** [comment]
> @D3athGr1p - I have recreated your issue. Enabling DEBUG reveals what is likely the actual problem:
> 
> > 2023-03-28 14:23:53.040+10:00 | BftProcessorExecutor-QBFT-0 | DEBUG | MainnetTransactionProcessor | Invalid transaction: gasPrice is less than the current BaseFee
> 
> Using validator contract mode results in an internal "transaction"...it's actually a simulated transaction, similar to eth_call which _shouldn't_ charge for the gas cost. Seems the bug is related to requiring a non-zero gas price regardless. Looking into it now.

Sure, Thanks a lot for looking into it, I thought I was missing something.

**Comment by siladu** [comment]
@D3athGr1p This fix is on the besu main branch now, but unreleased. If you like to test it out you can either build from source: https://wiki.hyperledger.org/display/BESU/Building+from+source
Or just the `develop` docker tag: `docker pull hyperledger/besu:develop`

**Comment by D3athGr1p** [comment]
> @D3athGr1p This fix is on the besu main branch now, but unreleased. If you'd like to test it out before the next release you can either build from source: https://wiki.hyperledger.org/display/BESU/Building+from+source Or use the `develop` docker tag: `docker pull hyperledger/besu:develop`

Thanks a lot i'll check it out
