### ISSUE TITLE
Node is unable to sync

### ISSUE THREAD

**Issue by Inderdeep01** [hyperledger/besu#5270]
### Description
I was following the official Hyperledger guide to set up a private network using IBFT 2.0. I want my network to have zero gas fee. I am facing this issue(attached screenshot). Can you please figure this out?
<img width="1437" alt="Screenshot 2023-03-26 at 5 34 26 PM" src="https://user-images.githubusercontent.com/75632849/227775084-4a493b77-4a7b-47f6-baa9-4824e5ee1375.png">

**Expected behavior:** Nodes should be able to sync and produce blocks

**Actual behavior:** Unable to find sync target.

**Frequency:** Every time

### Versions (Add all that apply)
* Software version: besu/v23.1.2/linux-x86_64/openjdk-java-17
* Java version: openjdk version "17.0.6" 2023-01-17
                         OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
                         OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)

* OS Name & Version: 
                                      PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
                                      NAME="Debian GNU/Linux"
                                      VERSION_ID="11"
                                      VERSION="11 (bullseye)"
                                      VERSION_CODENAME=bullseye
                                      ID=debian

* Kernel Version: Linux instance-1 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
* Cloud VM, type, size: Google Cloud Provider t2d-standard-1

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
{
  "genesis": {
    "config": {
      "chainId": 1337,
      "londonBlock": 0,
      "zeroBaseFee":true,
      "ibft2": {
        "blockperiodseconds": 2,
        "epochlength": 30000,
        "requesttimeoutseconds": 4
      }
    },
    "nonce": "0x0",
    "timestamp": "0x58ee40ba",
    "gasLimit": "0x47b760",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
      "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
        "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
        "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
        "balance": "0xad78ebc5ac6200000"
      },
      "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
        "privateKey": "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
        "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
        "balance": "90000000000000000000000"
      },
      "f17f52151EbEF6C7334FAD080c5704D77216b732": {
        "privateKey": "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
        "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
        "balance": "90000000000000000000000"
      }
    }
  },
  "blockchain": {
    "nodes": {
      "generate": true,
      "count": 4
    }
  }
}
* Documentation I followed:
    1) https://besu.hyperledger.org/en/stable/private-networks/tutorials/ibft/
    2) https://besu.hyperledger.org/en/stable/private-networks/how-to/configure/free-gas/#3-start-besu-with-a-minimum-gas-price-of-zero

**Comment by Inderdeep01** [comment]
Can anybody help?

**Comment by Inderdeep01** [comment]
## Steps to recreate:
- Follow the official set up guide and just replace the ibftConfigFile.json with my config

**Comment by jframe** [comment]
@Inderdeep01 I've been able to recreate the issue locally. Looks like there is a bug here. Will work on a fix for this

**Comment by Inderdeep01** [comment]
@jframe ok 👍

**Comment by jframe** [comment]
I've merged a change that fixes this issue into main. You can test it out by using the develop build of Besu. Or wait for the next release of Besu.
