### ISSUE TITLE
On-chain permissioning nodes can't peer when using a non-validator bootnode

### ISSUE THREAD

**Issue by arash009** [hyperledger/besu#528]
Nodes are not able to peer to each other when using on-chain permissioning with a bootnode that is not a validator. In this configuration the bootnode is not a validator and all the validator nodes in the POA network have on-chain node permissioning enabled.

Hypothesis

What appears to be happening is that all the validator nodes are able to connect to the bootnode but not to each other. This appears to be happening because the network is never in sync. When the network is not in sync on-chain permissioning is only able to connect to the bootnodes and so we are not able to connect the bootnodes neighbours or peers.

In the SyncStatusNodePermissioningProvider the hasReachedSync flag defaults to false and will toggle to true when we get an in sync event. We never get a sync status change event because the network state never changes and is stalled because none of the validators are able to connect to each other.

When a validator node is used as a bootnode that node has peer connections to all the other nodes same as in the other case but because it is an IBFT validator it also gossiping IBFT messages. So the same issue with peers still occurs in this case but the network is able to function because all IBFT messages are going via the bootnode using gossip.

 

Defect Prioritisation

Probability: Frequent. This will always happen in a scenario where IBFT2.0 is used along with a bootnode that is not a validator

Severity: Critical. The network stalls and is unable to produce blocks.

**Comment by arash009** [comment]
Refer to https://jira.hyperledger.org/browse/BESU-181 for more information

**Comment by macfarla** [comment]
timebox this to 3 days

**Comment by macfarla** [comment]
when this is fixed, need to add a CHANGELOG entry and remove from known issues
