### ISSUE TITLE
No way to trace private transactions

### ISSUE THREAD

**Issue by CMajeri** [hyperledger/besu#5280]
### Description
As a user, I want to trace private transactions so that I can see why some calls fail. 

### Acceptance Criteria
Run `priv_traceTransaction` or similar with a private transaction hash and see the trace

^ As far as I can see, there's no way to get the trace for a private transaction.
This would be supremely useful in debugging

**Comment by NickSneo** [comment]
Update: We are working on this ticket, will soon raise a draft PR

**Comment by NickSneo** [comment]
@CMajeri If I am not wrong you want this functionality - [trace_transaction](https://besu.hyperledger.org/en/latest/public-networks/reference/api/#trace_transaction) for private Transactions ?

**Comment by macfarla** [comment]
implemented
