### ISSUE TITLE
Increased disk I/O leading to slower block processing.

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#5297]
### Description
Ben ([benjaminion](https://github.com/benjaminion)) reported an issue where suddenly I/O activity increased resulting in low block processing performance :

"Pre-issue disk iops were averaging 108 io/s read, 1.92 io/s write
Post-issue, 557 io/s read, 329 io/s write - a sustained 5x increase in read and 170x increase in write. The nvme has reached its thermal limit (70C) and is now throttling the performance."

Besu version : 23.1.2
Java 17 

![image](https://user-images.githubusercontent.com/5099602/229520563-f7421d58-8852-42b1-8125-f0dd763dc1f4.png)

![image](https://user-images.githubusercontent.com/5099602/229520731-c2478cec-165c-40a4-a18a-b23f76921d8c.png)

![image](https://user-images.githubusercontent.com/5099602/229520806-01f76b63-22a8-4082-93ac-3b4c852c13ce.png)

**Comment by ahamlat** [comment]
It seems like I encountered a similar issue on one of the nodes I restarted this morning. It was due to a huge RocksDB compaction that took around 15 minutes, which is not normal. Compaction are usually very fast. 
 
![image](https://user-images.githubusercontent.com/5099602/229522250-9b93388c-9500-4857-b4ea-dabc9e4ea3bf.png)

![image](https://user-images.githubusercontent.com/5099602/229522301-802ac9fb-8347-443b-948f-cf0306b6d900.png)

![image](https://user-images.githubusercontent.com/5099602/229522612-c7a3fbd3-c90d-4f60-b921-5f5e5f0837f1.png)

![image](https://user-images.githubusercontent.com/5099602/229522697-567dc887-72d5-49e9-95e3-9dc0e9959110.png)

![image](https://user-images.githubusercontent.com/5099602/229522769-b0d8b9d8-ca57-4012-b0e3-6cb1c2eb1824.png)

![image](https://user-images.githubusercontent.com/5099602/229522936-70265c28-d1ba-4e5e-8589-92daf7e1c390.png)

![image](https://user-images.githubusercontent.com/5099602/229523050-3f75fbe3-c378-4b11-b5a9-29f01c0b7756.png)

**Comment by benjaminion** [comment]
I've just remembered that we [recently downgraded RocksDB](https://github.com/ConsenSys/teku/pull/6930) in Teku due to a user reporting long (multi-minute) freezes. RocksDB is not our default, but some users prefer it. The reported symptoms from our user look very similar to those in this issue.

More info [here](https://github.com/ConsenSys/teku/pull/6930). Also cross-reference [here](https://github.com/ConsenSys/teku/issues/6940).

**Comment by ahamlat** [comment]
Besu is running RocksDB 7.7.3 on release 23.1.2. If understand correctly, Teku had the issue on a newer version and the issue was fixed by downgrading to RocksDB 7.7.3
