### ISSUE TITLE
How is the address of a privately-deployed contract derived?

### ISSUE THREAD

**Issue by ntauth** [hyperledger/besu#5304]
Hello everyone,

For standard Ethereum contracts, one can predict the address of a deployed contract from the 12 most significant bytes of the Keccak256 hash of the RLP-encoded address of the deployer + the nonce. Is it also the case for contracts deployed within a Besu privacy group?

**Comment by macfarla** [comment]
From memory - I think it is deterministic - but I'm not sure it's that simple. Should be pretty easy for you to verify this behavior though :)
