### ISSUE TITLE
flaky test - getBlockByNumberForLatest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5309]
I've seen this test fail twice recently
`getBlockByNumberForLatest`

[FLAKY](https://app.circleci.com/insights/github/hyperledger/besu/workflows/default/tests?branch=main)
org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpServiceTest

https://app.circleci.com/pipelines/github/hyperledger/besu/21501/workflows/b449a2aa-30b7-497b-8e3c-1b87f104de05/jobs/132748
https://app.circleci.com/pipelines/github/hyperledger/besu/21466/workflows/2f5cdbdf-900e-4f5a-8127-74b2d18a9ef7/jobs/132514

**Comment by jframe** [comment]
Looks like the same as this issue https://github.com/hyperledger/besu/issues/5296

**Comment by macfarla** [comment]
duplicate
