### ISSUE TITLE
Plugins directory should be configurable from CLI

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#533]
## Context:

The current way plugins are working require that we create a `plugins` directory in besu.home path. This path is by default where bin/besu is, usually where release is unzipped. This besu.home is defined by the besu bash script depending on where the script is.

## Issue:

For people manually installing besu it's not a big deal as they easily have access and know besu.home. However when installing with a package manager (brew or else) you are not easily aware of the path of besu.home and in some cases you may even not be able to write in this path.
User then have no way to create the plugin directory.

## Proposed option:

User could be able to set a --plugins-dir=<PATH> option on the CLI to set this path to anywhere else.
This option should return an error if the plugins directory doesn't exist and it should not try to create it as it would be empty anyway, and would confuse users.

An empty plugins dir could also be created in the besu.home by default with a readme indicating that's the place to put plugins in. That would prevent users who are ok with using the default dir to have to create it and it would help them to locate it too.

**Comment by abdelhamidbakhta** [comment]
It is possible to configure the path of the plugins directory using the `BESU_OPTS` environment variable.
You can set the plugins directory like this:
`export BESU_OPTS="-Dbesu.plugins.dir=/path/to/plugins/dir"`

**Comment by timbeiko** [comment]
@abdelhamidbakhta should this be closed then?

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta should this be closed then?

Yes. Adding a CLI option would be redundant IMO
