### ISSUE TITLE
Question: Streams API

### ISSUE THREAD

**Issue by dimitardanailov** [hyperledger/besu#5345]
Greetings, 

I've been working on research. I can't a find a solition that is the reason to use the current channel. 
I'd like to find a Streams API or something similiar with functions.

The final goal is: Reading data from smart contracts. The additional requirement is: The solution should be hosted by us;

**Comment by non-fungible-nelson** [comment]
Let me know if this [thread](https://discord.com/channels/905194001349627914/938504958909747250/1097564144242262173) had enough info for your use! 

Closing for now - please re-open with follow up questions.
