### ISSUE TITLE
Faild validator smart contract call

### ISSUE THREAD

**Issue by D3athGr1p** [hyperledger/besu#5358]
I've one localchain and that chain has approx 500k blocks and have 4 peers

previously I didn't try to make new peer and sync it but now when I try to add new peer and sync it from genesis it throws error saying

![1](https://user-images.githubusercontent.com/86771928/232678671-73a345eb-8d29-4a2c-a944-4d2d65e7f7ca.png)

I compiled binary from this from source code
[Code](https://github.com/hyperledger/besu/tree/9978cb48a3fe2e6b9921b22e97d138cc61b6727f)

Genesis file contain:
```javascript
{
  "config" : {
    "chainid" : 878145,
    "berlinBlock" : 0,
    "qbft" : {
      "epochlength" : 30000,
      "blockperiodseconds" : 1,
      "requesttimeoutseconds" : 10,
      "blockreward" : "1500000000000000000"
    },
    "transitions" : {
      "qbft" : [ {
        "block" : 100,
        "validatorselectionmode" : "contract",
        "validatorcontractaddress" : "0xb9A219631Aed55eBC3D998f17C3840B7eC39C0cc"
      }
     ]
    }
  },
  "nonce" : "0x0",
  "timestamp" : "1679403873",
  "gasLimit" : "0x29b92700",
  "difficulty" : "0x1",
  "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase" : "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "f17f52151EbEF6C7334FAD080c5704D77216b732" : {
      "balance" : "0x446c3b15f9926687d2c40534fdb56400"
    }
  },
  "extraData" : "0xf87aa00000000000000000000000000000000000000000000000000000000000000000f8549447349b0e16718f7439261616c48fd1b92a9d64d7945c2ec9937230a20ab9a6008bc32952d0551c14fc94903e1eedcb60cc27a386ee2879274b2a445bd72a9457a71c05d16403165c21ce27914573ef5ffad819c080c0"
}

```

After throwing this error it resume syncing the node but it does occur time to time and after 3 to 4 times it disconnect from other peers and stop syncing it.

**Comment by siladu** [comment]
Haven't been able to recreate the issue so far. Been in contact with @D3athGr1p on discord and it's with them at the moment. Blocking this for now.

**Comment by siladu** [comment]
Hi @D3athGr1p, since we couldn't recreate, can this issue be closed now?

**Comment by D3athGr1p** [comment]
@siladu sure
