### ISSUE TITLE
Update input warning and error text

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#537]
Update all warning and error messages that can occur from specifying options when starting Besu. This does NOT include adding color.

The general formatting should follow this template:

WARNING: <setting> has been set to <value> but <other factors to consider>.
If applicable, explain more about what can be done on a second line.

ERROR: <error code> - <setting> can not be set to <value> because of <reason>.
Solution: If a potential remedy exists, it goes here.

UX will support and help work through exceptions as needed.

*Open Questions:*
I'm assuming these messages should also appear in logs, right?

*Acceptance Criteria:*
 * Errors and warnings follow the structure outlined in the CLI style guide

**Comment by RatanRSur** [comment]
Closing since I think we already do this?
