### ISSUE TITLE
besu build command requires reference tests?

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#5381]
cmd `    ./gradlew clean distZip -x test`

```
> Task :ethereum:referencetests:validateReferenceTestSubmodule FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/data/besu/ethereum/referencetests/build.gradle' line: 181

* What went wrong:
Execution failed for task ':ethereum:referencetests:validateReferenceTestSubmodule'.
> For the Ethereum Reference Tests the git commit did not match what was expected.
    
  If this is a deliberate change where you are updating the reference tests 
  then update "expectedHash" in `ethereum/referencetests/build.gradle` as the 
  commit hash for this task.
  Expected hash   :  04f338a6e673a6b4d906ec9d6d2bc939309357a5
  Full git output : +638da7ca7b2ca371ebb33d7d7d2562981aafd9b2 src/reference-test/external-resources (PoC6-2983-g638da7ca7b)

```

it was not like this before. but the tests are heavy can I compile besu without the tests?

**Comment by matkt** [comment]
This does not execute the tests it just checks that it is the right commit and that the test references have not been changed by mistake . If you have changed the test references, you just have to put the right hash

**Comment by winsvega** [comment]
how do i provide the hash?

**Comment by matkt** [comment]
yes  you need the folder and the hash is here https://github.com/hyperledger/besu/blob/4875ba3a64d9a438c452e5c855a6fe2f83d5f5d8/ethereum/referencetests/build.gradle#L166

**Comment by winsvega** [comment]
I see. I update every date so this way I would need a post pull script to fix this hash issue.

Strange to require tests repo when just compiling for release

**Comment by shemnon** [comment]
We've been having problems with the reference test submodule being altered accidentally, so this check breaks the checkin.  Next time I'm in the reference tests I'll tweak it so that it doesn't trip on that particular gradle invocation.
