### ISSUE TITLE
Change bytecode storage to be by hash as opposed to by address

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5388]
Today, code storage is stored by account address, but we need to store by code hash. Duplicated smart contracts can point to the same hashed bytecode. We also must serve data by hash in the context of the snapsync server. 

* Do a comparison with a full sync node to compare the improvement in storage reduction
* Measure the performance impact of the change on syncing and block import

- [x] Change  code storage to be stored by code hash instead of account address
- [x] Backwards capability for code storage by account
- [x] Compare stored code values from existing column family to new column to ensure consistency
- [x] Performance test syncing to ensure read/write performance caused by changes to tracking code hashes by address have minimal impact
- [x] Experimental flag to enable code storage by code hash
- [x] Compare storage size taken by new column families with old storage mode
- [ ] Track code hashes by address so that self-destruct can removed when all code storage is unreferenced

**Comment by jframe** [comment]
Mainnet code by address hash column size

| Column Family                  | Keys            | Column Size  | SST Files Size  |
|--------------------------------|-----------------|--------------|-----------------|
| CODE_STORAGE                   | 37701832        | 10 GiB       | 12 GiB          |

Mainnet code by code hash column size
| Column Family                  | Keys            | Column Size  | SST Files Size  |
|--------------------------------|-----------------|--------------|-----------------|
| CODE_STORAGE                   | 1231697         | 3 GiB        | 3 GiB           |

We save ~7GB by storing by code hash
