### ISSUE TITLE
Add color and formatting to input warnings and errors

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#539]
Add color and formatting to input warnings and errors in the CLI as shown in the style guide .

*Errors Formatting*
 * “ERROR” Label: Bold, Red - ANSI 31

 * Error Message: Red - ANSI 31

 * “Solution:” Label (Optional): Bold

 * Solution Message (Optional): No formatting

*Warning Formatting:*
 * “WARNING” Label: Bold, Bright Yellow - ANSI 33

 * Warning Message: Bright Yellow - ANSI 33

 * Additional Message Optional: No formatting

*Acceptance Criteria:*
 * Color is only outputted in TTY sessions

 * Formatting matches what is shown in the CLI style guide

**Comment by RatanRSur** [comment]
fixed by #1026
