### ISSUE TITLE
Implement new default profile for Besu configuration

### ISSUE THREAD

**Issue by gfukushima** [hyperledger/besu#5391]
### Description 
As a Besu node runner, I want sensible defaults so that when experimenting with the client and learning to configure it, I can have sensible and performant defaults. Additionally, If I only configure some options, I still want an optimal experience. 

These defaults promote the most performant profile for public networks with the full chain history. This is especially important when we ship SnapSync as a Server in Q1. We want these users to be able to serve any data required by peers to be good network citizens. We also want to bump the peer count to enable more robust peering and serving more data to the network.

### Acceptance Criteria
When starting up Besu with no additional commands ./bin/besu , the following defaults are configured:
- Sync Mode: SNAP
- Data-storage-format: BONSAI
    - Full flat DB will be default for all BONSAI users `Xsnapsync-synchronizer-flat-db-healing-enabled=true` (DELETE THIS FLAG → Safety concerns Gary Schulte) #6157
    - bonsai-limit-trie-logs-enabled=True
    - bonsai-historical-block-limit=512
- Network: Mainnet (should we specify a testnet for first time users without a config?)
- Max-peers: 50 (in line with Geth and other clients)
- Tx-pool: Layered (already default)

**Comment by non-fungible-nelson** [comment]
suggestion: for named networks use bonsai; for private networks, default to forest

**Comment by garyschulte** [comment]
additional suggestion: as part of this change, ensure we can correctly identify an already-existing database format, so we don't try to open an forest db as bonsai if there isn't a specific config for it at startup
