### ISSUE TITLE
Update colors and formatting of CLI help screen

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#541]
Update the colors and formatting of the --help screen in CLI. 

*Acceptance Criteria:*
 * Headings are bold and cyan

 * Description is on a second line and indented

 * Description wraps after 85 characters

 * Note that this criteria may change if NC-2024 is completed before this.

**Comment by SabaKathawala** [comment]
I would like to work on this issue :)

**Comment by azhang919** [comment]
I'd like to work on this issue!

**Comment by macfarla** [comment]
👋 Hi @SabaKathawala @azhang919 are you still interested in working on this?

**Comment by macfarla** [comment]
closing. out of date. help is beautiful.
