### ISSUE TITLE
Dependency Fix - Quorum Mainnet Launcher 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5413]
Older versions of Besu can no longer build the dependencies around the Mainnet Launcher. Issue to reinstate dummy classes / artifact to restore building of old versions. 

Investigating cloudsmith dependencies.

**Comment by jframe** [comment]
The existing artifact marked as version 1.0.1 in cloudsmith was actually 1.0.2-SNAPSHOT. I've removed that one and uploaded another 1.0.1 version with 1.0.1 binaries.

Tested on AWS instance was having this issue and is working now.
