### ISSUE TITLE
Logging to Indicate Besu is waiting on the CL to begin its sync, instead of hanging 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5416]
### Description
As a user, I need logs that tell me Besu is waiting on the CL to begin / resume the sync process. Currently the node hangs without much indication of what is occuring.

### Acceptance Criteria
* Logging to describe when Besu is waiting for the CL to begin/resume sync 
  * At initial sync
  * Before long BWS

**Comment by siladu** [comment]
Maybe could usehttps://github.com/hyperledger/besu/blob/main/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineQosTimer.java
