### ISSUE TITLE
Update warning and error language in logs

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#542]
Update each error and warning message that ends up in our logs (or in the CLI if running a TTY session) to match the formatting (wording only, not color for this story) the CLI style guide. See attached images for the general formatting. UX will support and help write any messages as needed.

*Acceptance Criteria:*
 * Errors and warnings follow the structure outlined in the CLI style guide

![CLI Logging - Real Example](https://user-images.githubusercontent.com/9390255/77542351-6c49d700-6e7c-11ea-80a7-2626afefde02.png)
![Log - Warning](https://user-images.githubusercontent.com/9390255/77542357-6f44c780-6e7c-11ea-9517-cf98a46a41a6.png)
![Log - Info](https://user-images.githubusercontent.com/9390255/77542363-71a72180-6e7c-11ea-8773-bf1e2d4a5378.png)
![Log - Error](https://user-images.githubusercontent.com/9390255/77542370-74097b80-6e7c-11ea-8bfa-b78fecda8ab6.png)
![Log - Failure](https://user-images.githubusercontent.com/9390255/77542373-75d33f00-6e7c-11ea-9a37-c3838bb55203.png)

**Comment by RatanRSur** [comment]
Superceded by structured logging
