### ISSUE TITLE
Missing RocksDB metrics even when they are enabled

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#5427]
### Description
Even when RocksDB metrics are enable by adding for example this option  --metrics-category=JVM,PROCESS,BLOCKCHAIN,ETHEREUM,EXECUTORS,NETWORK,PEERS,**KVSTORE_ROCKSDB**,**KVSTORE_ROCKSDB_STATS**,PRUNER,RPC,SYNCHRONIZER,TRANSACTION_POOL to your besu command, they are not exposed on /metrics endpoint.

RocksDB metrics are not exposed thus not collected by prometheus

![image](https://user-images.githubusercontent.com/5099602/235885905-461ea2e2-f146-4151-acfe-a5d37a83db53.png)

This is a regression on main branch.

**Comment by macfarla** [comment]
closed by #5426
