### ISSUE TITLE
Investigate Besu Issue on Hive PR #764 - GraphQL Withdrawals

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#5431]
https://github.com/ethereum/hive/pull/764

https://discord.com/channels/905194001349627914/905205502940696607/1103324482610925598
> I'm writing a new Hive test and having difficulties with Besu... have a PoW chain and extended it with 1 Shanghai block. Besu errors on importing these blocks. I'm thinking it's a configuration error.

**Comment by gfukushima** [comment]
Initial investigation suggests that it's likely a bug related to the addition of withdrawals to the block body specifically in the the block importer feature.
