### ISSUE TITLE
Decouple JsonRpcError enum from the data field

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5437]
JsonRpcError enum has code/message. It also has a data field which is used sometimes - currently for revert reason. But it's a bit of a hack because it gets reset as soon as that enum field gets used again (so, for example, you can't use this in unit tests to test actual vs expected values of the data field). 

~~See #5421 for an example~~

See #5241 for an example

**Comment by siladu** [comment]
> See https://github.com/hyperledger/besu/issues/5421 for an example
Can you point to the specific example please @macfarla? All I see are cert updates.

**Comment by jframe** [comment]
The JsonRpcError.setData is used in a few RPCs. One example is the EthCall for the revert reason https://github.com/hyperledger/besu/blob/main/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCall.java#L119

**Comment by macfarla** [comment]
> > See #5421 for an example
> 
> Can you point to the specific example please @macfarla? All I see are cert updates.

Linked the wrong ticket - meant to be #5241

**Comment by macfarla** [comment]
added snack/TeamRevenant label but any team could pick this up

**Comment by gtebrean** [comment]
@macfarla please check if the open PR has the expected approach
