### ISSUE TITLE
Shanghai support for QBFT/IBFT

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#5446]
QBFT chains are not able to produce blocks when configured to use Shanghai. Even though Shanghai is mostly about supporting Withdrawals it does add new EVM opcodes e.g. PUSH0 that could be of use in private networks.

To reproduce configure a genesis file with:
```
{
  "config": {
    "chainid": 1337,
    "shanghaiTime": 0,
    "zeroBaseFee":true,
    "qbft": {
      "epochlength": 30000,
      "blockperiodseconds": 5,
      "requesttimeoutseconds": 10
    }
```

This is the error we get:
```
2023-05-11 10:49:44.474+10:00 | BftProcessorExecutor-QBFT-0 | WARN  | WithdrawalsValidator$AllowedWithdrawals | withdrawals must not be null when Withdrawals are activated
2023-05-11 10:49:44.474+10:00 | BftProcessorExecutor-QBFT-0 | INFO  | MainnetBlockValidator | Invalid block 1 (0x2dc8d5f94285d22afab11929b5cb872e1b158825459ef01cb7230520a36f9dfc)
2023-05-11 10:49:44.475+10:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalPayloadValidator | Invalid Proposal Payload: block did not pass validation. Reason Optional[failed to validate output of imported block]
```

**Comment by jframe** [comment]
Shanghai works with QBFT in 23.1.0 but not with 23.4.0

**Comment by jframe** [comment]
Suggestion from @siladu:
Maybe just need to wire in ProhibitedWithdrawals in the "qbftSpecificModifications"

**Comment by jframe** [comment]
Confirmed that this wasn't working with 231.0, the shanghaiTime was being ignored for this config and we are using defaulting to using frontier. So this isn't a regression.

**Comment by NickSneo** [comment]
Did you check if it works with CLIQUE or ethash? I am getting the same error when trying to configure shanghaiTime with CLIQUE and ethash - https://github.com/hyperledger/besu/issues/5468
If it works for you then let me know the genesis file you used

**Comment by jframe** [comment]
Didn't test with Clique or ethhash yet. I suspect the same issue also applies to them, as the changes for shanghaiTime were made to work with POS. Will have a look at #5468 and respond there if it's the same issue or not.

**Comment by NickSneo** [comment]
Is someone working on this bug? Or maybe we can pick this to look into it?

**Comment by jframe** [comment]
Not sure it would technically be a bug since we haven't added support for QBFT beyond London at the moment. But no one is working on this at the moment. You are welcome to pick it up.

**Comment by matthew1001** [comment]
This is something we're seeing more and more requests for as the `PUSH0` op-code is used by the latest releases of open zeppelin that enterprise users are moving to. So even without wanting the specific optimisation that the new op-code provides, it's prevent use of current web3 libraries.

I'm planning to spend some investigation time understand how much work is required to add support for it with QBFT, any insight others have would be really useful.
