### ISSUE TITLE
Sending message that exceeds local message size limit

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#5455]
### Description

It happens seldomly that Besu tries to send messages that are bigger than the configured size limit and as [stated in the code, this should be a bug](https://github.com/hyperledger/besu/blob/d7656b98993df18488ef7fbcd66bd3039162fb0a/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java#L292)

**Frequency:** [What percentage of the time does it occur?]
Rare

### Logs (if a bug)
Error message
```
Sending eth message to peer (PeerId 0x771af70ea1f0f269c70aabd8be2411d1dc20fe9694380cc137d67c3ca033157e118ed04a1fbf8c37aef28a50e81f19531177907d84cb64f7e7eda7af56172815, reputation PeerReputation 118, validated? true, disconnected? false, client: erigon/nd-222-222-222/v2.42.0-stable-beb97784/linux-amd64/go1.20.2, connection [Connection with hashCode 1450331933 with peer 0x771af70ea1f0f269c70aabd8be2411d1dc20fe9694380cc137d67c3ca033157e118ed04a1fbf8c37aef28a50e81f19531177907d84cb64f7e7eda7af56172815 inboundInitiated true initAt 1684118305150], enode enode://771af70ea1f0f269c70aabd8be2411d1dc20fe9694380cc137d67c3ca033157e118ed04a1fbf8c37aef28a50e81f19531177907d84cb64f7e7eda7af56172815@188.42.93.159:0) which exceeds local message size limit of 10485760 bytes.  Message code: 6, Message Size: 10485762
```

### Versions (Add all that apply)
* Software version: 23.4.0

**Comment by fab-10** [comment]
the message should not have been created in the first place, however according to current code, it is sent anyway, but the receiving peer is free to just ignore it.

So the ideal solution should be to avoid creating these messages, otherwise as last resort drop it instead of sending.

**Comment by rodionlim** [comment]
@fab-10, let me give this a pass. Seems like it's the block messages that are occasionally slipping through, added a check before creating the block message itself. Also amended the catch all to drop the messages instead of forwarding it through when size exceeds the limit
