### ISSUE TITLE
eth_getCode unpredictable behaviour

### ISSUE THREAD

**Issue by cbayraktaroglu** [hyperledger/besu#5456]
### Description
The response from "eth_getCode"rpc call is unpredictable. Consecutive runs of the same call may result with no code returned. (Potential Bug)

### Steps to Reproduce (Bug)
1. Initialize the client
```
client, err := ethclient.Dial("besu node rpc url")

```
2. Get the address format ready
```
targetAddress := common.HexToAddress("0x3E7d1eAB13ad0104d2750B8863b489D65364e32D")
```

3. Send the request
```
code, err := client.CodeAt(context.Background(), common.HexToAddress("0x3E7d1eAB13ad0104d2750B8863b489D65364e32D"), nil)
```

4. Check the returned bytes length
```
log.Println(len(code))
```

**Expected behavior:**
The length of the returned bytes array should be the same between the runs

**Actual behavior:** 
Non predictable behaviour, sometimes the length is 9571 and sometimes 0

**Frequency:**
1 in 10 runs returns the length of 0

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - version 23.4.0

**Comment by non-fungible-nelson** [comment]
Hey can you please provide your nodes configuration files? And your CL config if you're on Mainnet/public testnet?

**Comment by non-fungible-nelson** [comment]
Reference - #5038, #5076, #5123 @garyschulte

**Comment by cbayraktaroglu** [comment]
Hi, here are the command line arguments used:

For Besu:
```
        - '--sync-mode=X_SNAP'
        - '--data-storage-format=BONSAI'
        - '--network=mainnet'
        - '--data-path=/var/lib/besu/data'
        - '--metrics-enabled=true'
        - '--metrics-host=0.0.0.0'
        - '--metrics-port=8008'
        - '--engine-rpc-enabled=true'
        - '--engine-jwt-secret=/var/lib/besu/jwtsecret'
        - '--engine-rpc-port=8551'
        - '--engine-host-allowlist=*'
        - '--rpc-http-enabled=true'
        - '--rpc-http-host=0.0.0.0'
        - '--rpc-http-port=8545'
        - >-
          --rpc-http-api=ETH,NET,CLIQUE,DEBUG,MINER,NET,PERM,ADMIN,EEA,TXPOOL,PRIV,WEB3
        - '--rpc-http-cors-origins=*'
        - '--host-whitelist=*'
        - '--graphql-http-enabled'
        - '--rpc-ws-enabled=true'
        - '--rpc-http-max-active-connections=1000'
        - '--rpc-ws-max-active-connections=30'
        - '--rpc-ws-port=8546'
        - >-
          --rpc-ws-api=CLIQUE,DEBUG,EEA,ETH,IBFT,MINER,NET,PLUGINS,PRIV,QBFT,TRACE,TXPOOL
        - '--tx-pool-max-size=10000'
```

For the CL (Teku):
```
        - '--log-destination=CONSOLE'
        - '--logging=info'
        - '--network=mainnet'
        - '--p2p-enabled=true'
        - '--p2p-port=9000'
        - '--p2p-peer-upper-bound=50'
        - '--rest-api-enabled=true'
        - '--rest-api-host-allowlist=*'
        - '--rest-api-interface=0.0.0.0'
        - '--rest-api-port=4000'
        - '--rest-api-cors-origins=*'
        - '--rest-api-docs-enabled=false'
        - '--data-beacon-path=/var/lib/teku/beacon'
        - '--data-path=/var/lib/teku'
        - '--data-storage-archive-frequency=2048'
        - '--data-storage-mode=minimal'
        - '--data-storage-non-canonical-blocks-enabled=false'
        - '--ee-endpoint=http://besu-service:8551'
        - >-
          --validators-proposer-default-fee-recipient=0x760b522Eb7384174d471c6294Bd4C4E368096B64
        - '--ee-jwt-secret-file=/tmp/jwt/jwtsecret'
        - '--metrics-enabled=true'
        - '--metrics-host-allowlist=*'
        - '--metrics-interface=0.0.0.0'
        - '--metrics-port=5054'
        - >-
          --initial-state=https://beaconstate.ethstaker.cc/eth/v2/debug/beacon/states/finalized
```

**Comment by garyschulte** [comment]
@cbayraktaroglu we are having trouble reproducing this problem.  

Is this a besu mainnet node?  if so, what version of besu?  Are you using bonsai storage format or forest?

Have you seen anything relevant in the besu logs that would shed some more light on why the empty response?

testing with a similar snippet does not seem to yield any problems on the latest besu when run repeatedly or in parallel:

```
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	// Connect to the Ethereum client
	client, err := ethclient.Dial("http://127.0.0.1:8545")
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}

	// Convert the address string to a common.Address
	address := common.HexToAddress("0x3E7d1eAB13ad0104d2750B8863b489D65364e32D")

	// Call the CodeAt method to get the contract code
	code, err := client.CodeAt(context.Background(), address, nil) // nil means latest block
	if err != nil {
		log.Fatalf("Failed to get contract code: %v", err)
	}

	// Convert the code bytes to a string and print
	fmt.Printf("%x\n", code)
}
```

Any additional details that will help reproduce would be helpful

**Comment by cbayraktaroglu** [comment]
Hi @garyschulte. Here is the config we are using, yes it is mainnet

```
        - '--sync-mode=X_SNAP'
        - '--data-storage-format=BONSAI'
        - '--network=mainnet'
        - '--data-path=/var/lib/besu/data'
        - '--metrics-enabled=true'
        - '--metrics-host=0.0.0.0'
        - '--metrics-port=8008'
        - '--engine-rpc-enabled=true'
        - '--engine-jwt-secret=/var/lib/besu/jwtsecret'
        - '--engine-rpc-port=8551'
        - '--engine-host-allowlist=*'
        - '--rpc-http-enabled=true'
        - '--rpc-http-host=0.0.0.0'
        - '--rpc-http-port=8545'
        - >-
          --rpc-http-api=ETH,NET,CLIQUE,DEBUG,MINER,NET,PERM,ADMIN,EEA,TXPOOL,PRIV,WEB3
        - '--rpc-http-cors-origins=*'
        - '--host-whitelist=*'
        - '--graphql-http-enabled'
        - '--rpc-ws-enabled=true'
        - '--rpc-http-max-active-connections=1000'
        - '--rpc-ws-max-active-connections=30'
        - '--rpc-ws-port=8546'
        - >-
          --rpc-ws-api=CLIQUE,DEBUG,EEA,ETH,IBFT,MINER,NET,PLUGINS,PRIV,QBFT,TRACE,TXPOOL
        - '--tx-pool-max-size=10000'
```

The important thing about the code snippet you have shared

```
// Call the CodeAt method to get the contract code
	code, err := client.CodeAt(context.Background(), address, nil) // nil means latest block
	if err != nil {
		log.Fatalf("Failed to get contract code: %v", err)
	}

	// Convert the code bytes to a string and print
	fmt.Printf("%x\n", code)
```

this part won't crash since, the node is responding to the request properly (which means that the err will be nil). The problem lies in the data it returns. Sometimes it is able to return the contract data, but sometimes it returns empty data object. In this case you should modify the above code like this to notice the error

```
// Call the CodeAt method to get the contract code
	code, err := client.CodeAt(context.Background(), address, nil) // nil means latest block
	if err != nil {
		log.Fatalf("Failed to get contract code: %v", err)
	}
        
        if len(code) == 0 {
                log.Fatal("Empty code data has been returned by the node!")
        }

	// Convert the code bytes to a string and print
	fmt.Printf("%x\n", code)
```

You can also replicate the error with Postman, sending this data object ın the body of a POST request to the node

```
{"jsonrpc":"2.0","method":"eth_getCode","params":["0x3E7d1eAB13ad0104d2750B8863b489D65364e32D", "latest"],"id":53}
```

And as for the logs there is no print outs/logs about this request in the Besu logs. It just continues its usual operations

Hopefully this helps! If you have any further questions, feel free to ask them also

PS: Since the node is sometimes able to return the correct data, I do not think this is a data corruption. It seems like more like a race condition (I haven't looked at the source code just guessing)

**Comment by garyschulte** [comment]
I agree it sounds like a worldstate availability race condition, I just haven't been able to reproduce it.  I suspect the worldstate is unavailable here:

https://github.com/hyperledger/besu/blob/main/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java#L867-L880

For every instance I have tried to reproduce with, every call is returning the exact same code, never empty.

What is your hardware config?  Processor, ram, disk?   When you run your client, are you just manually executing it or running it in a loop or ?  

It sounds like this is easy for you to reproduce, but unfortunately there isn't any relevant logging in this code path we can enable.  If I created a branch with some additional trace logging on that code path, would you be able to build and run that branch?

**Comment by cbayraktaroglu** [comment]
Sounds like a plan, we can definately do that. As long as the only difference between that branch and the current version is additional logs. 


As for the other question node is currently running on r6i.xlarge, kubernetes version 1.23, AMI relese 1.23.16-20230217

**Comment by garyschulte** [comment]
how much ram is allocated to the pod and are you setting an explicit Xmx?  This race might be due to heavy GC if there is a lot of memory pressure

**Comment by garyschulte** [comment]
pull this [branch](https://github.com/garyschulte/besu/tree/investigate-worldstate-availability)

it is just main, with one [commit](https://github.com/garyschulte/besu/commit/185d1587cfb4bf9c87aedfcad4da951ded8bab42)

to build docker images, from the checked out branch, run:
`./gradlew distDocker`

if you are using minikube on your ec2 instance, you can publish directly to the k8s registry by running this before you build the docker images: 
`eval $(minikube docker-env)`

otherwise, you will probably have to jump through some hoops to publish to a repo that your cluster can pull from.

**Comment by cbayraktaroglu** [comment]
@garyschulte the node is the only pod running in that instance, thus there are no resource limits set for it.

I will return you with the logs. Setting up the environment and backing up the db might take some time (also there are some other stuff that needs to be taken care of prior to this, so give me some time). I will return to you probably around 23.05.2023

until then,

Have a nice day,
Stay healthy!

**Comment by non-fungible-nelson** [comment]
Hey @cbayraktaroglu - let us know if you have any logs so we can proceed! Thank you

**Comment by cbayraktaroglu** [comment]
We are working on that, we have setup an isolated environment, we have built from the branch you have provided. Now we are just waiting for the sync to complete. I will write as soon as I have the logs

**Comment by cbayraktaroglu** [comment]
Status update:

- We have deployed a secondary node with the version of Besu you have provided
- The newly deployed node is running on AWS r6i.xlarge instance
- We are running ubuntu-server OS on this node and it is not connected to any cluster
- The new node was deployed using the docker 
- After testing we did not manage to replicate the problem with the newly deployed node 

Furthermore:

- We have removed all the images of Besu from our cluster and rebooted the Besu pod
- The error we were encountering is gone on that node as well

So we believe there may be 2 possible causes for this, and we are not sure which one is the real cause:

1. We have optimized some processes running inside the cluster so, it may have reduced the memory pressure, even though we have not set an explicit limit on Besu's resource usage EKS might have put some without us noticing

2. The image might have been corrupted (we are not sure how this is possible), we have also pulled many different Besu images (development, different version, RCs) they might have gotten mixed up

So for now, there seems like nothing we can do about this issue, as neither we nor you guys can replicate it 

I will be back if we encounter more issues, but until then 

Have a nice day,
Stay healthy!

**Comment by non-fungible-nelson** [comment]
Close until we can reproduce - thank you for the detailed report and please reopen if it comes back!
