### ISSUE TITLE
Indicate that it is the node public key displayed in the log

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#548]
The log message is as follows when a new key is generated on starting Pantheon:
Generated new key key 0x6b28eaf11a8757976c567c50db229a3b1106b98916f6670a9f95c7e8353c5bad30e8574a9fdd4fbd5ed8036bee1ba15f433ff9d0859e1d0a2123c62f34321005

And when a key file already exists:
Loaded key 0xaf80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d7434c380f0aa4c500e220aa1a9d068514b1ff4d5019e624e7ba1efe82b340a59

It would reduce confusion if these log messages indicated these are the ‘node public key’

Originally raised - https://jira.hyperledger.org/projects/BESU/issues/BESU-85

**Comment by magooster** [comment]
IMHO Log message could still be confusing as you actually load the private key from a file and derive the public key from that. When saving its actually writing the private key.

Could say "Loaded keypair, public key {} from private key file {}" and "Generated new keypair, public key {} and stored private key to {}"
