### ISSUE TITLE
Revert SSZ toRLP

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#5484]
We have decided against introducing SSZ as an encoding format in the execution layer for the time being.

Initial reversion is specified here:  https://github.com/ethereum/EIPs/pull/6985
Subsequent cleanup is here: https://github.com/ethereum/EIPs/pull/7038

Spec update is already live here:  https://eips.ethereum.org/EIPS/eip-4844#new-transaction-type

**Comment by Gabriel-Trintinalia** [comment]
https://github.com/jflo/besu/pull/13
