### ISSUE TITLE
KZG Precompile to BigEndian

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#5485]
The Consensus Layer has agreed to send kzg commitments in big endian for consistency:

https://github.com/ethereum/consensus-specs/pull/3354
Once this pr for the KZG library is merged and released:  https://github.com/ethereum/c-kzg-4844/pull/305

We need to update the KZG library, and make sure that the KZGPrecompile works correctly.  Since we just pass whatever the CL sends us down to the library, this should "just work" but at the very least new test vectors need to be added to work with the updated library.

**Comment by non-fungible-nelson** [comment]
Completed in #5536
