### ISSUE TITLE
Fix generation of legacy privacy group IDs 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#551]
Fix generation of legacy privacy group IDs to be calculated using the contents of the address not the memory address. 

Existing legacy privacy group IDs will need to be migrated to the new generation.

**Comment by MadelineMurray** [comment]
Not sure this is worth doing but need to either capture this information in comments or documentation so we're not caught by it at some stage in the future.

**Comment by macfarla** [comment]
this was fixed in EthSigner. Find the code and link here.

**Comment by macfarla** [comment]
This is the code in Besu https://github.com/hyperledger/besu/blob/a93d06f1827f3bd346c42add45e32c57a27440d3/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyGroupUtil.java

**Comment by macfarla** [comment]
And in Orion https://github.com/ConsenSys/orion/blob/05759341ec1a216e6837df91e421207c8294ad2a/src/main/java/net/consensys/orion/enclave/sodium/SodiumEnclave.java

**Comment by macfarla** [comment]
generation code was removed from EthSigner - it gets the id from besu/orion
