### ISSUE TITLE
Misleading error message when Besu cannot create parent directories

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#552]
When starting Besu will create a directory if the parent directories already exist but will not create parent directories. This is standard behavior that we do not want to change but a better error message would be helpful.

If parent directories are specified that do not exist, startup fails with the following error:

Cannot store generated private key.

This error message should indicate the actual issue:
Cannot create multiple directories for $path

Probability: Remote
Severity: Marginal

**Comment by MadelineMurray** [comment]
Since raising this, it appears Besu does create multiple directories in some cases which is not the behaviour we want. ie, the following creates the three directories and the database inside dir3 
besu --network=dev --data-path=dir1/dir2/dir3

**Comment by holiman** [comment]
This also happens in other circumstances, notably when running in docker. 

It's the "Correct Way To Do It" that `besu` doesn't use the `root` user within the docker image, but if the mounted datadir is non-writeable by the `besu` inside-docker user, then this error happens aswell.

**Comment by pullurib** [comment]
> This also happens in other circumstances, notably when running in docker.
> 
> It's the "Correct Way To Do It" that `besu` doesn't use the `root` user within the docker image, but if the mounted datadir is non-writeable by the `besu` inside-docker user, then this error happens aswell.

This should now be fixed by https://github.com/hyperledger/besu/pull/7575 which sets permissions for data path inside docker image . Should this be issue be closed now ?
