### ISSUE TITLE
Flaky tests - Privacy Container Tests

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5544]
These tests use docker via the third party lib ContainerTests, to run Tessera.

An alternative is to run Tessera as a java process within the unit tests - similar to what we (used to) do with Orion.

**Comment by macfarla** [comment]
See https://github.com/hyperledger/besu/issues/2867
And https://github.com/hyperledger/besu/pull/4466 which never got merged

**Comment by gtebrean** [comment]
@macfarla If the changes from #2867 are the ones that we are looking for maybe we should let the person which proposed them to update the branch and recreate the PR, as i don't see a specific reason for which the PR was closed.

**Comment by gtebrean** [comment]
@macfarla could you please help me with the message above?

**Comment by macfarla** [comment]
@gtebrean  #4466 was simply changed because we shifted priorities, and this issue was also blocked by other things. 

Several of the blockers are resolved now (Besu is now on Java 17, Tessera has been released). Not sure about the status of this one https://github.com/Consensys/tessera/issues/1490 - may just need testing or may need fixing (in Tessera)
