### ISSUE TITLE
nat - migrate test from Junit4 to Junit5

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5561]
Module nat
eg 
public class NatServiceTest

- Add dependency for junit.jupiter (junit5)
- Migrate per https://blogs.oracle.com/javamagazine/post/migrating-from-junit-4-to-junit-5-important-differences-and-benefits
- Remove dependency on junit 4

Here's an example https://github.com/hyperledger/besu/pull/5525/files

**Comment by fspirola** [comment]
I'm working in this issue.

**Comment by fspirola** [comment]
@macfarla This issue was resolved by PR #6122

**Comment by macfarla** [comment]
thanks @fspirola
