### ISSUE TITLE
besu - migrate tests from Junit4 to Junit5

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5571]
Module besu
eg 
public class RlpBlockImporterTest 

- Add dependency for junit.jupiter (junit5)
- Migrate per https://blogs.oracle.com/javamagazine/post/migrating-from-junit-4-to-junit-5-important-differences-and-benefits
- Remove dependency on junit 4

Here's an example https://github.com/hyperledger/besu/pull/5525/files

**Comment by 0xBlockPay** [comment]
Hi :) I asked on discord about assign this task to me :)

**Comment by macfarla** [comment]
hey @0xBlockPay are you still interested in working on this one? hopefully the blockers are out of the way now! Otherwise I will unassign you

**Comment by fspirola** [comment]
@macfarla please, can you assign this issue to me.

**Comment by jflo** [comment]
assigned, have fun!

**Comment by fspirola** [comment]
@jflo Done. This issue was resolved by PR #6122

**Comment by macfarla** [comment]
done!
