### ISSUE TITLE
Blockskout does not start in Developer Quickstart

### ISSUE THREAD

**Issue by damianlluch** [hyperledger/besu#5577]
Hi, this is the second time I have used Hyperledger Besu (the previous time was about a year ago). And this time I wanted to try the Developer Quickstart that they have in the documentation with all dockerized services. The problem I see is that it doesn't start Blockskout, I don't know why.
Could it be that you are using another block explorer than Blockscout?

After running ./run.sh I see the list of services with their ports, but Blockscout does not open.

Any suggestions?

thanks

<img width="1243" alt="image" src="https://github.com/hyperledger/besu/assets/1463804/c7461995-dc77-405f-b3ac-d73ae9a8114d">
<img width="1268" alt="image" src="https://github.com/hyperledger/besu/assets/1463804/e2856135-e050-4eba-904f-4e05e585c27a">

**Comment by NickSneo** [comment]
If you want you can use Sirato (Blockchain Explorer) instead of Blockscout
