### ISSUE TITLE
acceptanceTestMainnet fails on OSX

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#5599]
> Task :acceptance-tests:tests:acceptanceTestMainnet

BadCLIOptionsPluginTest > shouldNotRegister() FAILED
    java.lang.AssertionError:
    Expecting path:
      /var/folders/1k/pyws18jj58d5gfn292v4jhh80000gn/T/acctest10781140850353098414/plugins/badCliOptions.register
    not to exist
        at org.hyperledger.besu.tests.acceptance.plugins.BadCLIOptionsPluginTest.shouldNotRegister(BadCLIOptionsPluginTest.java:58)

BadCLIOptionsPluginTest > shouldNotStart() FAILED
    java.lang.AssertionError:
    Expecting path:
      /var/folders/1k/pyws18jj58d5gfn292v4jhh80000gn/T/acctest13525771553980842822/plugins/badCliOptions.start
    not to exist
        at org.hyperledger.besu.tests.acceptance.plugins.BadCLIOptionsPluginTest.shouldNotStart(BadCLIOptionsPluginTest.java:67)

This test passes fine on linux during CI.

**Comment by macfarla** [comment]
@jflo think this is duplicated now by #6815 - which one do you wanna close?
