### ISSUE TITLE
[4844] Investigate Failing 4844 Hive testing 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5625]
Failing tests:

engine-blobs: (2/34)
pyspec: (11/579)

For details on running hive tests - https://wiki.hyperledger.org/display/BESU/Using+Hive+Test+Suite?flashId=-950349581

**Comment by Gabriel-Trintinalia** [comment]
pyspec:  Failed:  69, passed 496, ignored: 12, total: 577

**Comment by macfarla** [comment]
closing this one - opening issues for individual hive test failures as required.
