### ISSUE TITLE
EIP-2124 (forkid) and EIP-2364 (eth/64) supported?

### ISSUE THREAD

**Issue by bobsummerwill** [hyperledger/besu#564]
Is there support for EIP-2124 (forkid) and EIP-2364 (eth/64)?
Or planned support for these?

https://eips.ethereum.org/EIPS/eip-2124
https://eips.ethereum.org/EIPS/eip-2364

The same logic works for ETC as for ETH, but the canonical data describing the forks for ETC is different than ETH after block 1,920,000.

@meowbits has been working on an implementation/extension of this logic in the Core-Geth downstream.   Is there any logic for these network protocols in Besu yet?

See https://ecips.ethereumclassic.org/ECIPs/ecip-1082 and https://github.com/ethereumclassic/ECIPs/issues/294.

Thanks!

**Comment by timbeiko** [comment]
It appears to me that both were already merged, see: 
* https://github.com/hyperledger/besu/pull/156
* https://github.com/hyperledger/besu/pull/425

Closing for now, but please re-open if anything is missing.

**Comment by bobsummerwill** [comment]
Great - thanks for the info, @timbeiko.

CC @meowbits.

**Comment by meowsbits** [comment]
@timbeiko Thanks for linking those PRs.

Given these code snippets, I doubt that besu has implemented ECIP1082 (as Bob cited). 

I looked specifically at 
- https://github.com/hyperledger/besu/pull/156/files#diff-9520ad255c411c9005db256398e0c312R170
- https://github.com/hyperledger/besu/blob/master/config/src/main/resources/classic.json

From the specification, the fork list gathering function should omit block 1920000 under the classic configuration.

Here's some test data https://github.com/etclabscore/core-geth/pull/82/files#diff-cfc9a5f866915f6231af672563880e03R129.

**Comment by timbeiko** [comment]
Oh, I don't know of any ECIP. The PegaSys doesn't implement those. If the two linked above are the equivalent to the EIPs, then it should be fairly simple to make compatible with ETC.

**Comment by meowsbits** [comment]
Just for reference, here's how multi-geth implemented it: https://github.com/multi-geth/multi-geth/commit/269fdfe5974f2d5068b3740a07d117808afc0c88#diff-b02f7700e9e7a28b82d2b7ba19e4bc9eR214

**Comment by bobsummerwill** [comment]
To be clear, I was not thinking that the ECIP had been implemented, @timbeiko.

That is work which we would need to contract out.

I just wanted to check if the base functionality was there for Besu.
