### ISSUE TITLE
EIP-4788: Beacon Block Root

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#5655]
Implement EIP-4877 for the Cancun hardfork.

https://eips.ethereum.org/EIPS/eip-4788

Execution Engine spec updates are here:

https://github.com/ethereum/execution-apis/pull/420

**Comment by macfarla** [comment]
https://github.com/ethereum/execution-apis/pull/451
https://github.com/ethereum/execution-apis/pull/398
