### ISSUE TITLE
json output mixed with logging output

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#5676]
When running the besu `evmtool` on a state-test, the text
```
Protocol schedule created with milestones ... 
```
Appears (multiple times). I saw this today when I updated the fuzzer-binaries. The output from `evmtool  --json state-test` should preferrably consist only of `jsonl`.

**Comment by non-fungible-nelson** [comment]
Just to confirm this was running on main? Any commit hash? 
@shemnon if I recall was tweaking the log4j outputs in relation to evmtool. Not sure if you picked up his changes before this report.

**Comment by non-fungible-nelson** [comment]
can also try `--logging=OFF` to remove log4j logging.

**Comment by siladu** [comment]
Looks like this will be fixed in https://github.com/hyperledger/besu/pull/5701
