### ISSUE TITLE
How to log request.headers() in besu RPC call: JsonRpcRequest jsonRpcRequest = request.getRequest();

### ISSUE THREAD

**Issue by im-kapil** [hyperledger/besu#5685]
Hello There Besu developers, 

I am new to Besu and learning besu by myself.

I forked Besu, build dependencies, ran Besu node. Upto here everyting is fine. 

But now I started making small changes inside the RPC methods for example adding logs etc. 

So Inside the rpc method name eth_getBalance, and the file name is EthGetBalance.java. 

I made some changes for logging the request payload. for logging the request payload I used this code. 

`JsonRpcRequest jsonRpcRequest = request.getRequest();

    LOG.error("jsonRpcRequest payload:::::::::::::: {}", jsonRpcRequest);`
    
  it works fine and I am able to see the logs for my request payload at console.
  
  
![image](https://github.com/hyperledger/besu/assets/89021712/15fae3e3-6f73-4c9e-91af-222afafe34f9)

Now I want to log the request header. but I am not sure how can I do so. and looking for some help from some help. 

Thanks.

**Comment by siladu** [comment]
Hi @im-kapil The JsonRpcRequest you reference is really just the request body. 
I think this is more the level you'd need to log at: https://github.com/hyperledger/besu/blob/main/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/JsonRpcObjectExecutor.java#L54-L55
(we currently only log the body at TRACE level)

Feel free to carry on the conversation in the #besu-contributors channel of the Hyperledger Discord: https://discord.gg/hyperledger
