### ISSUE TITLE
Question: About parsing errors on admin_addPeer w/ enode URL with a DNS

### ISSUE THREAD

**Issue by je-martinez** [hyperledger/besu#5695]
## Description

Hi, everyone, just (probably a silly question) is there an additional configuration to apply on a Permissioned Network to add peers into a Node using the Admin method `admin_addPeer`? I'm using `besu-23.4.1` from `https://hyperledger.jfrog.io/hyperledger/besu-binaries/besu/23.4.1/besu-23.4.1.zip`

```
{
    "jsonrpc": "2.0",
    "method": "admin_addPeer",
    "params": ["enode://c35c3ec90a8a51fd5703594c6303382f3ae6b2ecb9589bab2c04b3794f2bc3fc2631dabb0c08af795787a6c004d8f532230ae6e9925cbbefb0b28b79295d615f@node-1.mydomain.com:30301"],
    "id": 1
}
```

But the response always return a parsing error:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32700,
        "message": "Parse error"
    }
}
```

I'm currently running the Permissioned Network on a Ubuntu instance using these commands:
```
/besu/bin/besu --config-file=/besu_config/Permissioned-Network/config.toml --Xdns-enabled=true --Xdns-update-enabled=true
```
But I got the same error, also I try it using those two arguments in the configuration file (`.toml`) but the result is the same

```
...

Xdns-enabled=true
Xdns-update-enabled=true

...
```
Thanks in advance for your help!  🦾

**Comment by non-fungible-nelson** [comment]
Do you have the ADMIN RPC enabled in your config as well? https://besu.hyperledger.org/stable/public-networks/reference/cli/options#rpc-http-api

I am guessing you do but wanted to double check.

**Comment by je-martinez** [comment]
> Do you have the ADMIN RPC enabled in your config as well? https://besu.hyperledger.org/stable/public-networks/reference/cli/options#rpc-http-api
> 
> I am guessing you do but wanted to double check.
> 
> also how are you submitting the request? through postman, CURL, something else?

Thanks for your response, @non-fungible-nelson.

Yes, I have enabled the Admin RPC on my configuration file (`config.toml`), like this:

```
...

rpc-http-api=["ADMIN","ETH","NET","PERM","IBFT"]

...
```

I tried using `Postman` and `CURL` but I got the same error, I don't have this issue when I made the request using the IP of the Node instead of the DNS and adding the required arguments for`p2p-host` configuration, for example:

```
{
    "jsonrpc": "2.0",
    "method": "admin_addPeer",
    "params": ["enode://c35c3ec90a8a51fd5703594c6303382f3ae6b2ecb9589bab2c04b3794f2bc3fc2631dabb0c08af795787a6c004d8f532230ae6e9925cbbefb0b28b79295d615f@228.43.206.214:30301"],
    "id": 1
}
```

**Comment by macfarla** [comment]
admin_addPeer won't support DNS until this PR is released https://github.com/hyperledger/besu/pull/5584 - next besu release!

for now, you need to use IP addressing
