### ISSUE TITLE
Unable to place 4 first nodes on multiple servers in IBFT2.0 Network with Besu v23.1.2

### ISSUE THREAD

**Issue by khiem20tc** [hyperledger/besu#5707]
I followed by tutorials and because of the limitation of servers, I need separate 4 nodes on multiple machines: AWS vs DO.
[https://besu.hyperledger.org/23.4.0/private-networks/tutorials/ibft/validators]

**Issue Description:**
I am encountering an issue with the deployment of an IBFT2.0 network involving four nodes. Three nodes are hosted on AWS instances, and one node is deployed on a DigitalOcean (DO) instance. The network uses Besu v23.1.2 and Java version jdk20. Although the nodes have been successfully synced, the block production process is not functioning as expected.

**Steps to Reproduce:**

Deploy three nodes on AWS instances using Besu v23.1.2 and Java version jdk20.
Deploy one node on DigitalOcean (DO) with the same Besu and Java versions.
My step-by-step start time includes: node1 as a boot node (AWS), node4 (DO), node2 (AWS), node3 (AWS)
Configure all nodes to use the IBFT2.0 consensus mechanism.
Ensure all necessary ports (including the default Ethereum port 30303) are open for communication among the nodes.
Start each node and monitor the synchronization process.

**Expected Behavior:**
Upon successful deployment and synchronization of the four nodes, the IBFT2.0 network should function correctly, and the nodes should be able to produce blocks in a distributed manner.

**Actual Behavior:**
Despite successful node deployment and synchronization, the nodes are not producing blocks as expected. The block production process seems to be stuck or halted, leading to a failure in achieving consensus among the nodes.

**Additional Information:**

The AWS and DO instances are properly provisioned with sufficient resources to handle the network's demands.
There are no apparent firewall or networking issues, as all nodes are reachable and can sync with each other.
The time synchronization has been verified to ensure that nodes are operating with the correct time.
Possible Root Causes:

There might be an issue with the IBFT2.0 consensus algorithm implementation or configuration that is preventing block production.
There could be a compatibility issue with Besu v23.1.2 and the Java version jdk20 when running on the specified server infrastructure.
Workarounds Tried:
As a workaround, I have attempted to restart the nodes, reconfigure the consensus mechanism, and redeploy the network on fresh instances. However, none of these measures have resolved the block production problem.

Expected Resolution:
I kindly request the Besu contributors to investigate this issue further to identify the root cause and provide a resolution. The ability to deploy and operate an IBFT2.0 network on multiple servers is crucial for our use case, and we are eager to participate in resolving this matter collaboratively.

Please let me know if any additional information or logs are required to diagnose and address the problem effectively. Thank you for your attention to this matter.

Best regards,

![image](https://github.com/hyperledger/besu/assets/53548789/3437fa61-497a-4d31-af0d-d5e64f72a94b)

![image](https://github.com/hyperledger/besu/assets/53548789/faf69bc5-0231-42ad-87b6-d0c42ead43c6)

**Comment by siladu** [comment]
Hi @khiem20tc, the most common cause of no blocks being produced is a misconfigured extraData in the genesis file. The extraData needs to contain all your validating nodes' node addresses.

Please double check that the extraData string you have in your genesis file matches the list of validator addresses that you have set up, and note the validator addresses change if the private node key changes. Besu will auto-generate a private node key if you don't specify one, so redeploying nodes may be cause the keys to change if you don't separately specify them, https://besu.hyperledger.org/development/public-networks/reference/cli/options#node-private-key-file

More info about extraData is here:
https://besu.hyperledger.org/23.4.0/private-networks/how-to/configure/consensus/ibft#extra-data

There's two ways you can validate the extraData is correct:
1. Decode the extraData string as RLP, e.g. using this tool https://toolkit.abdk.consulting/ethereum#rlp which will give you a list of node addresses
2. Manually re-encode your deployed nodes' address using `besu rlp encode --from=toEncode.json` as shown in the docs and then compare the result with your genesis file.

I recommend getting used to configuring the network using https://docs.goquorum.consensys.net/tutorials/quorum-dev-quickstart/using-the-quickstart on one machine first, before you introduce the complication of multiple machines.

If this does not resolve your issue, please can you post some more logs, maybe can try increasing to DEBUG level as well: https://besu.hyperledger.org/development/public-networks/how-to/monitor/logging

**Comment by khiem20tc** [comment]
Thank Sir,

I have already set it up successfully by checking extra data and putting the key to match the boot node's first position in the array after decoding. And then, I also specified the location of the key for each node when starting to run to avoid node auto-gen new key.

![image](https://github.com/hyperledger/besu/assets/53548789/ed290ff3-3527-45ee-9a9c-ed91c028118a)

**Comment by siladu** [comment]
Great news, sounds like you're sorted then - I will close this, feel free to reopen with more info if it's not actually resolved.
