### ISSUE TITLE
Concurrent Private Transactions fail to be processed

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu#571]
### Steps to Reproduce (Bug)

1.  Using web3js-eea, submit two private transactions in rapid succession, with an incrementing private tx nonce. 

**Expected behavior:** 
Transactions are processed in the submitted order - according to private transaction nonce

**Actual behavior:** 
Transactions fail to be processed, typically one will fail. In web3j-eea polling for transaction receipt times out...

**Frequency:** 
Majority of the time

### Versions (Add all that apply)
* Software version: Besu 1.4.2-SNAPSHOT, Orion 1.5.0, Web3js-eea latest

### Additional Information
Besu running with fixed signing key

Issue relates to the privacy marker transaction nonce which ultimately determines order of transactions. The privacy marker transaction can get duplicate nonces or even out of order with respect to private transaction nonce.

I adding some logging for the generated privacy marker transaction nonce and see for example two requests using the same nonce.

2020-03-25 08:41:42.570+00:00 | vert.x-worker-thread-16 | DEBUG | EeaSendRawTransaction | Privacy Marker Transaction nonce 7755
2020-03-25 08:41:42.570+00:00 | vert.x-worker-thread-17 | DEBUG | EeaSendRawTransaction | Privacy Marker Transaction nonce 7755

Where privacy marker transaction nonce is out of order with respect to private transaction nonce - see the following in the logs

2020-03-25 10:22:00.034+00:00 | pool-10-thread-1 | ERROR | PrivacyPrecompiledContract | Failed to process private transaction 0xa53b8b21ea7799b3897924e3cb13f4fe40b3afcf23ca437179f18e468b28eade: Private Transaction nonce 50, does not match sender account nonce 49.

**Comment by MadelineMurray** [comment]
Next step - test incrementing nonce outside of library and sending with transaction. 
Next next step - document above approach. 
Next next next step - add nonce incrementing to library as default behaviour.  Raise JI for libraries once at this step.

**Comment by magooster** [comment]
The failures i describe occur when incrementing the nonce outside of the call to web3.eea.sendRawTransaction...

IMHO: There's still an issue with the generation of the privacy marker transaction nonces - race condition

**Comment by lucassaldanha** [comment]
> There's still an issue with the generation of the privacy marker transaction nonces in the request handler in Besu
We are aware of this issue and we are investigating how we can solve it (or get around it). It isn't a race condition in the code but it is a consequence of the way public and private tx nonces are independent of each other.

**Comment by magooster** [comment]
Thanks for the update - it's a race condition in the system, two or more private transaction requests are trying to generate a privacy marker transaction at the same time but they need to be generated in the same order as the private transaction nonces to be processed correctly.

**Comment by lucassaldanha** [comment]
At the moment we don't have a way to specify the PMT nonce when using `eea_sendRawTransaction`. However, it is possible to use `priv_distributeRawTransaction` to distribute the private tx to the participants (with the private nonce) and `eth_sendRawTransaction` to create the PMT (with the public nonce).

I'm gonna update web3js-eea with an example on how to do that through the library.

We will also raise a ticket for implementing a utility method in the library to make sending batch private transactions easier.

**Comment by magooster** [comment]
You can pass the nonce in web3js-eea to eea_sendRawTransaction via the options map

* options map can contain the following:
   * privateKey : Private Key used to sign transaction with
   * privateFrom : Enclave public key
   * privateFor : Enclave keys to send the transaction to
   * privacyGroupId : Enclave id representing the receivers of the transaction
   * nonce(Optional) : If not provided, will be calculated using `eea_getTransctionCount`
...

const genericSendRawTransaction = (options, method) => {
    if (options.privacyGroupId && options.privateFor) {
      throw Error("privacyGroupId and privateFor are mutually exclusive");
    }
    const tx = new PrivateTransaction();
    const privateKeyBuffer = Buffer.from(options.privateKey, "hex");
    const from = `0x${privateToAddress(privateKeyBuffer).toString("hex")}`;
    return web3.priv
      .getTransactionCount({
        from,
        privateFrom: options.privateFrom,
        privateFor: options.privateFor,
        privacyGroupId: options.privacyGroupId
      })
      .then(transactionCount => {
        tx.nonce = options.nonce || transactionCount;
...

Obviously there's an unnecessary JSON-RPC call but you can override the nonce.

**Comment by lucassaldanha** [comment]
`eea_sendRawTransaction` allows you to choose the nonce of the private transaction, not the nonce of the PMT that will be created (the public tx). The process that I have described, using `priv_distributeRawTransaction` and `eth_sendRawTransaction` (ETH not EEA), makes it possible to specify both the private and the public nonce.

**Comment by magooster** [comment]
Thanks for the clarification, I had misread the previous response... it sounds like we'll need a public account for each privacy group account, to ensure both the private tx nonce and PMT nonce are aligned by order. Does this mean eea_sendRawTransaction will be deprecated in a future release?

**Comment by lucassaldanha** [comment]
> it sounds like we'll need a public account for each privacy group account

I'm not sure if I understood what you mean. Basically, any account can sign the private tx, and any account can sign the PMT. The important thing is, when creating the Private TXs and the PMTs, that the private and public nonces are chosen in a sensible way that will ensure that the PMTs will be executed in the expected order, and by consequence, the private txs will also be executed in the expected order.

The order that the PMTs are executed will dictate the ordering of the private transactions.

We don't have plans to deprecate eea_sendRawTransaction. It can still be used for sending private transactions (with the caveat of sending multiple txs from the same account at once being hard). We'll investigate how we can improve this in the future.

At this point in time, we'll recommend users to use the distribute/create PMT "trick" when needing to send multiple private txs at once.

**Comment by magooster** [comment]
> The important thing is, when creating the Private TXs and the PMTs, that the private and public nonces are chosen in a sensible way that will ensure that the PMTs will be executed in the expected order, and by consequence, the private txs will also be executed in the expected order.

That's what I meant 'lock' a public account to a private account ensuring nonce increment in step.

**Comment by lucassaldanha** [comment]
Got it! You are right, using the same account for the private transaction and for the PMT should definitely make things easier for the user. Easier to keep track of. This isn't something we'll enforce in the protocol level though.

Have you had a chance to look at the PR that I have raised with the example on how to send concurrent txs? Do you think it can help others having the same problem?

**Comment by MadelineMurray** [comment]
@magooster - following up to see if you've got anymore questions/comments before I close this one?  

Raised https://github.com/hyperledger/besu-docs/issues/287 to reflect how to handle sending concurrent private transactions.
