### ISSUE TITLE
Change default to remove Pretty JSON and make it user configurable

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5712]
Pretty JSON is costly in the RPC stack and in file sizes. This issue tracks removing Pretty JSON as the default for Besu and creates a new flag:

`--pretty-json-enabled` with a default of `false`

This will be considered a breaking change and should be included in the RC series.

**Comment by gtebrean** [comment]
@non-fungible-nelson, I started looking into this.
From what I see writerWithDefaultPrettyPrinter is called from 2 different utility classes ([JsonUtil](https://github.com/hyperledger/besu/blob/a46cf27ec5cfee049e627614ab345b0ed4f172c4/config/src/main/java/org/hyperledger/besu/config/JsonUtil.java#L331C27-L331C27) and [JsonUtils](https://github.com/hyperledger/besu/blob/a46cf27ec5cfee049e627614ab345b0ed4f172c4/ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/JsonUtils.java#L38)), however both are in different modules and have different command interfaces (BesuCommand and  EvmToolCommand). The second one it's easy to update with a command argument but for the first one the things are a lot complicated as I can't find any proper configuration class referred inside BesuCommand that could help.
Could you share your thoughts about this? what might be a possible hint?
