### ISSUE TITLE
Trace context changes in the EVM

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#5728]
Geth offers a more fine grained tracing capability than Besu. Currently in Besu it is not possible to trace the EVM on a context change (via call, create or selfdestruct). In Geth those methods are defined as:

```
// CaptureEnter is called when EVM enters a new scope (via call, create or selfdestruct).
func (t *opcounter) CaptureEnter(op vm.OpCode, from common.Address, to common.Address, input []byte, gas uint64, value *big.Int) {}

// CaptureExit is called when EVM exits a scope, even if the scope didn't
// execute any code.
func (t *opcounter) CaptureExit(output []byte, gasUsed uint64, err error) {}
```
For consistency I would name those methods `traceContextEnter` and `traceContextExit`.

**Comment by shemnon** [comment]
Can you propose a full java signature?

**Comment by daniellehrner** [comment]
I have created a draft PR with the following signatures:

```
  default void traceContextEnter(final MessageFrame frame) {}

  default void traceContextExit(final OperationResult operationResult) {}
```

I think those should be more or less equivalent. @shemnon What do you think?

Draft PR: #5741
