### ISSUE TITLE
Implement Debug_traceCall in Besu

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5747]
### Description

Besu has implemented the Parity style Trace_Call but not the more recent Debug_TraceCall that is implemented in [Geth](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracecall) and Erigon and used by infrastructure providers like Infura and Linea.

As a network participant, I would like access to this debug call in the same namespace and format as other clients so that I can drop in replace Besu in certain networks/tooling/RPC stacks. 

### Acceptance Criteria
* Implementation - can be based on Geth implementation and Besu Trace_Call (with slightly different format).

**Comment by non-fungible-nelson** [comment]
Hey @fainashalts - for Infura's usage of this endpoint, do you have any insights into the "override" parameter outlined in the Geth Docs? Would we be able to determine the usage of this? We need to see how we implement this in Besu or if we copy the functionality exactly.

**Comment by fainashalts** [comment]
Hey @non-fungible-nelson! I do not currently have insights into this, we are still enabling it for the most part. Perhaps @sebaespindola has more info because he is working on debug_traceCall for Polygon.

**Comment by non-fungible-nelson** [comment]
Let's update this ticket and merge the underlying PR.

**Comment by non-fungible-nelson** [comment]
Let's update this ticket and merge the underlying PR.
