### ISSUE TITLE
Besu 23.4.4 Low TPS around 37 TPS Compared to Besu-21.10.8 Which can go above 1000 TPS

### ISSUE THREAD

**Issue by shehinfn** [hyperledger/besu#5757]
Description:
As a Besu node operator, I want to achieve higher Transactions Per Second (TPS) on the latest version of Besu (23.4.4) as was possible with version besu-21.10.8. When benchmarking using the wrk tool at TPS above 37, the network starts to break down and produces errors, specifically "Transaction nonce is too distant from current sender nonce". Interestingly, the earlier version (besu-21.10.8) did not have this issue.

`../../besu-23.4.4/bin/besu --tx-pool-max-size=100000 --revert-reason-enabled   --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT,ADMIN,TXPOOL,TRACE --rpc-ws-enabled=true --rpc-ws-host=0.0.0.0 --rpc-ws-port=9545 --host-allowlist="*" --rpc-http-cors-origins="all" 
`

Images:

Below is the most ideal case around 30-40 milliseconds of delay we get the transaction
![image](https://github.com/hyperledger/besu/assets/13316230/6e8c1a79-206e-4a72-83e9-6f0473efc767)
Below is the most ideal case around 10-30 milliseconds of delay starts breaking
![image](https://github.com/hyperledger/besu/assets/13316230/00397ede-66da-49c8-9e8a-bf93ab857979)
Acceptance Criteria:
Besu 23.4.4 should be able to handle a TPS comparable to, or better than, besu-21.10.8.

Steps to Reproduce (Bug):

Set up a Besu node using version 23.4.4.
Benchmark the node using the wrk tool, increasing the TPS load.
Observe that when the load surpasses 37 TPS, the network starts to degrade, and errors start appearing.
Expected behavior:
Besu 23.4.4 should handle higher TPS without breaking.

Actual behavior:
At TPS rates above 37, the network fails and errors appear indicating nonce issues.

Frequency:
This issue occurs consistently when the TPS threshold is crossed.

Logs (if a bug):
Relevant logs from Besu showing the "Transaction nonce is too distant from current sender nonce" error would be beneficial here.

Versions (Add all that apply):

Software version: Besu 23.4.4
Java version: [Specify version]
OS Name & Version: [Specify OS & version]
Kernel Version: [Specify kernel version]
Virtual Machine software & version: [e.g., vmware -v]
Docker Version: [Specify version]
Cloud VM, type, size: Amazon Web Services I3-large
Consensus Client & Version if using Proof of Stake: [Specify consensus client & version if relevant]
Smart contract information:

Solidity version: [Specify version using solc --version]
Repo with minimal set of deployable/reproducible contract code: [Please provide a link]
Deployment/calling method of the contract: [Specify how the contract is deployed/called]
Reproduction on other ETH clients: [Specify if the issue also occurs on other Ethereum clients]
Additional Information:

Besu setup info: [Please provide genesis file, config options, etc.]
System info:
Memory: 32 GB RAM
CPU: 8 core

**Comment by non-fungible-nelson** [comment]
Hi there - would you be able to provide any more information in the ticket? there are a few questions in the description that you could fill out that would help us with this issue. At minimum, please provide your configuration and logs from Besu and any CL client (if on public networks). Thank you

**Comment by shehinfn** [comment]
@non-fungible-nelson hi I have updated now please check

**Comment by non-fungible-nelson** [comment]
Hi there - can you tweak the `tx-pool-limit-by-account-percentage` option in your configuration and let me know if you are still seeing the nonce errors and slow TPS? There is [documentation for this here.](https://besu.hyperledger.org/development/public-networks/reference/cli/options#tx-pool-limit-by-account-percentage)

**Comment by shehinfn** [comment]
Hello. Previously, I encountered an issue where transactions would remain pending in the pool due to the max pool capacity being set to around 4095 by default. When I added "tx-pool-limit-by-account-percentage=1" to the configuration, the issue became more evident. I initially raised this concern, but later removed the "tx-pool-limit-by-account-percentage" setting because it wasn't supported in the older version. Back then, I was puzzled as to why the transactions weren't getting stuck in the mempool. Now, it's clear that version 23.4.4 has significant flaws. Moreover, the stuck 4095 transactions will only clear after 13 hours, given the default setting for --tx-pool-retention-hours is 13 hours. If you need a visual demonstration, I can provide a video recording. My setup involves two AWS virtual machines, and I run them in command mode without any containers.

![image](https://github.com/hyperledger/besu/assets/13316230/ba0de145-a409-40d3-9f63-e1e3f5d8a0c2)

**Comment by 7suyash7** [comment]
Hey, @shehinfn, I looked into the code and found that these CLI options are dependent on each other
```
@Value.Derived
  default int getTxPoolMaxFutureTransactionByAccount() {
    return (int) Math.ceil(getTxPoolLimitByAccountPercentage() * getTxPoolMaxSize());
  }
```
[tx-pool-max-size](https://besu.hyperledger.org/stable/public-networks/reference/cli/options#tx-pool-max-size)
[tx-pool-limit-account-percentage](https://besu.hyperledger.org/stable/public-networks/reference/cli/options#tx-pool-limit-by-account-percentage)
Try looking into these two options, I was able to get around 1000 TPS after using these.

**Comment by shehinfn** [comment]
@7suyash7 sure i can try add both the values increase max pool size and keep tx pool limit to 1 make sure 100% transactions from the users can be held in pool . But not sure it will fix the issue since the issue here is pool getting stuck .. let me try and send additional screenshots

**Comment by shehinfn** [comment]
![image](https://github.com/hyperledger/besu/assets/13316230/f46566ed-70b8-4dfb-8038-2061583c7fcb)

Same issue queue getting stuck

../../besu-23.4.4/bin/besu --tx-pool-limit-by-account-percentage=1 --tx-pool-max-size=100000 --revert-reason-enabled   --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT,ADMIN,TXPOOL,TRACE --rpc-ws-enabled=true --rpc-ws-host=0.0.0.0 --rpc-ws-port=9545 --host-allowlist="*" --rpc-http-cors-origins="all"

**Comment by ahamlat** [comment]
Are the transactions you're generating from your load testing tool related to the same account (sender) ? If it is the case or the ratio is significant for few accounts, you may need to raise --tx-pool-limit-by-account-percentage to more than 1%.

**Comment by hardice501** [comment]
I have same problem.
load testing generate transactions by random accounts.

BESU OPTIONS:
besu ....some options ..  --rpc-http-port=8545 --rpc-ws-port=8546 --p2p-port=30303 --rpc-http-max-active-connections=1000 --rpc-http-enabled --rpc-http-apis=ETH,NET,QBFT,ADMIN,PRIV,EEA,MINER,WEB3,TXPOOL,DEBUG,TRACE --rpc-http-cors-origins=all --rpc-ws-enabled --rpc-ws-host=0.0.0.0 --rpc-ws-apis=ETH,NET,QBFT,ADMIN,PRIV,EEA,MINER,WEB3,TXPOOL,DEBUG --min-gas-price=0 --rpc-ws-max-frame-size=10485760 --tx-pool-limit-by-account-percentage=1 --tx-pool-max-size=16000 --host-allowlist="*" --graphql-http-enabled=true --revert-reason-enabled=true --tx-pool-disable-locals=true

But 300TPS load test failed.(300 TPS, 10000 Transactions)
After failed load test, also 1 TPS test failed.(after nonce error occured, the same error occurs very easily.)

**Comment by macfarla** [comment]
we've done a lot of performance improvements since this time - recommend trying the latest besu!

**Comment by aniruddhsingh7901** [comment]
Subject: Seeking Guidance: Low TPS in QBFT Private Network with ERC-20 Transactions

Environment:
Besu Version: Latest
Network Type: QBFT Private Network
Nodes: 4 validator nodes
Smart Contract: Standard ERC-20 Token
Testing Tool: Hyperledger Caliper

Current Setup:
4 nodes running on single machine
Genesis Configuration:
blockperiodseconds: 2
epochlength: 30000
requesttimeoutseconds: 4
gasLimit: 0x8000000

Testing Results:
Target TPS: 100
Achieved TPS: ~12
Transaction Success Rate: 100%
Average Latency: 4.34 seconds

Issues Observed:
Low transaction throughput despite no failures
Higher than expected latency
Nonce-related issues during concurrent transactions

Questions:
What would be the recommended configuration for achieving higher TPS (500+)?
Are there specific system requirements or network topology suggestions?
What are the best practices for tuning QBFT parameters in a private network?
How can we optimize the transaction pool handling for better throughput?

Any guidance on improving the performance would be greatly appreciated.
