### ISSUE TITLE
Free Gas fee

### ISSUE THREAD

**Issue by mydappwallet** [hyperledger/besu#5769]
### Description

I want to run private network with QBFT consensus and free gas network
When I run besu with parameter --min-gas-price=0 besu log the warning: 
 _--min-gas-price has been ignored because --miner-enabled was not defined on the command line._

### Steps to reproduce
_besu --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT,WEB3 --host-allowlist="*" --rpc-http-cors-origins="all" --min-gas-price=0_
_No response_

**Comment by non-fungible-nelson** [comment]
Hi there! I believe this was fixed by #5669 which was just released today! Can you try this again on [version 23.7.1](https://github.com/hyperledger/besu/releases/tag/23.7.1) and let me know if you notice the same behavior? Thanks for the report!

**Comment by mydappwallet** [comment]
Thanks. I was tested. And works fine. Thanks
