### ISSUE TITLE
Kubernetes Operator

### ISSUE THREAD

**Issue by gbaufake** [hyperledger/besu#5773]
### Description
As a Kubernetes Engineer, I want a Kubernetes Operator, so that I can easily deploy Besu with all the resources needed.

**Comment by non-fungible-nelson** [comment]
Hi there - does [the documentation](https://besu.hyperledger.org/stable/private-networks/tutorials/kubernetes/charts) have the answers you need? If so, let me know and we can close this issue - thank you! If not, you can reach out on [the Hyperledger Discord](discord.gg/hyperledger) for more support!

**Comment by garyschulte** [comment]
If you specifically are looking for an operator rather than a helm deployment option, it looks like [kotal](https://github.com/kotalco/kotal) supports besu.

Let us know if there is a specific resource management behavior you are looking for from an operator beyond just deployment lifecycle.

**Comment by gbaufake** [comment]
Hi @non-fungible-nelson  and @garyschulte.

Thanks for this answer. 
Does Besu have any plans to support any Kubernetes operator? I was interested in starting an OpenShift version

**Comment by garyschulte** [comment]
We do not have plans currently, and pull requests are always welcome 🙏

**Comment by joshuafernandes** [comment]
Hi @gbaufake this might be handy as a start https://github.com/hyperledger-labs/besu-operator

**Comment by gbaufake** [comment]
@joshuafernandes thanks for the code. @garyschulte I will try to create some operator code and send the pull request.
