### ISSUE TITLE
Allow state override on eth_call and eth_estimateGas 

### ISSUE THREAD

**Issue by antonydenyer** [hyperledger/besu#5788]
### Description
Currently, you can not perform an `eth_estimateGas` or an `eth_call` on something that isn't in the 'correct' state as the evm will, correctly, return an error. For example, on an erc20 you may wish to send an approval followed by a transfer call. 

You can estimate gas for the approve but not the transfer.
You can not check the result of a transfer without an approval first. 

As a network participant, I would like access to be able to drop in and replace Besu in certain networks/tooling/RPC stacks.

### Acceptance Criteria
Whilst it's not specified in the ethereum rpc spec the implementation should be based on the Geth rpc docs to allow a drop in replacement.

https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth#eth-call

**Comment by adarcanum** [comment]
gm, anyone working on this? I recently had to implement this on client side for jvm wouldn't mind submitting a PR for besu.

**Comment by macfarla** [comment]
Block overrides https://geth.ethereum.org/docs/interacting-with-geth/rpc/objects#block-overrides

State overrides https://geth.ethereum.org/docs/interacting-with-geth/rpc/objects#state-override-set

**Comment by macfarla** [comment]
Created new issue for block overrides https://github.com/hyperledger/besu/issues/7822

**Comment by macfarla** [comment]
#7801 implements this for eth_call, PR incoming to add the param parsing for eth_estimateGas
