### ISSUE TITLE
Bugs causing high memory usage

### ISSUE THREAD

**Issue by RogerHKW** [hyperledger/besu#5796]
I was excited to install your new version, announced to fix "bugs with memory usage". Unfortunately the amount of memory that your software uses now is even worse than before.

Despite the use of `-Xmx11G`, your previous versions were constantly using between 11 GB and 13 GB. Since the installation of version 23.7.1, my machine is totally clogged. Besu uses consistently 21 GB, leaving the absolute minimum to the kernel to work.

My configuration in `/etc/systemd/system/besu.service` :

> [Unit]
Description=Besu Execution Client (Mainnet)
Wants=network-online.target
After=network-online.target
[Service]
User=besu
Group=besu
Type=simple
Restart=always
RestartSec=5
Environment="JAVA_OPTS=-Xmx11G"
Environment="BESU_OPTS=-Xmx11G"
Environment="JAVA_OPTS=-XX:-HeapDumpOnOutOfMemoryError"
Environment="LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so"
ExecStart=/usr/local/bin/besu/bin/besu \
  --network=mainnet \
  --sync-mode=X_SNAP \
  --data-path=/dev/data2TB/besu-mainnet \
  --data-storage-format=BONSAI \
  --engine-jwt-secret=/var/lib/jwtsecret/jwt.hex \
  --Xplugin-rocksdb-high-spec-enabled \
  --rpc-http-enabled \
  --rpc-http-api=ETH,NET,WEB3,TXPOOL \
  --tx-pool-max-size=65535 \
  --tx-pool-retention-hours=36 \
  --tx-pool-price-bump=2 \
  --tx-pool-enable-save-restore=true \
  --Xlayered-tx-pool=true \
  --Xlayered-tx-pool-max-prioritized=16384 \
  --Xlayered-tx-pool-layer-max-capacity=134217728 \
  --Xlayered-tx-pool-max-future-by-sender=8 \
  --max-peers=75
[Install]
WantedBy=multi-user.target

**update**: After setting `vm.vfs_cache_pressure` to 33 (previously it was 66) and rebooting, the memory consumption is back to what it was with the previous version. Still above the Xmx limit, but at least the computer is healthy.

**Comment by matkt** [comment]
hello, thanks for your info. could you tell me what is your CL ?

**Comment by RogerHKW** [comment]
> hello, thanks for your info. could you tell me what is your CL ?

Thanks for considering my report. This computer runs Teku. According to its self-reporting (that I visualize on the app _beaconcha.in_) Teku's RAM consumption stays always under its own Xmx limit (but is this self measure accurate?)

**Comment by non-fungible-nelson** [comment]
--Xplugin-rocksdb-high-spec-enabled
Remove this flag and your usage should decrease. This plug-in allows Besu to gobble up a lot of off-heap memory. Removing this flag should reduce the overall footprint.

**Comment by ahamlat** [comment]
@RogerHKW To use less memory on Besu, you need to reduce -Xmx. If the node is already synced, I suggest to set your -Xmx to 4 GiB if your node is not used as an RPC node. I also recommend these GC options :
export BESU_OPTS="-XX:G1ConcRefinementThreads=2 -XX:G1HeapWastePercent=15 -XX:MaxGCPauseMillis=100"
We're thinking of making these flags default.
With these options and high spec flag disabled, your Besu node will use less than 8 GiB

**Comment by macfarla** [comment]
hopefully these suggestions helped you resolve your issue
