### ISSUE TITLE
handle timestamp with max value

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5798]
eg for engine hive tests, they use max unsigned long and get this error

Cannot convert value to long: 18446744073709551615` 

~Also for cancunTime for holesky network - for EF devops testing~

**Comment by macfarla** [comment]
also for blobGas

**Comment by spencer-tb** [comment]
I had a small look into this last week after noticing the errors on https://hivecancun.ethdevops.io/. So just noting down what I came across if its helpful.

It looks like most of the unsigned 64-bit fields within the engine api execution payload are a subset of the `long` type via a custom `UnsignedLongParameter` type - https://github.com/hyperledger/besu/blob/main/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadParameter.java#L71-L89:
```java
  public EnginePayloadParameter(
      ...
      @JsonProperty("blockNumber") final UnsignedLongParameter blockNumber,
      @JsonProperty("baseFeePerGas") final String baseFeePerGas,
      @JsonProperty("gasLimit") final UnsignedLongParameter gasLimit,
      @JsonProperty("gasUsed") final UnsignedLongParameter gasUsed,
      @JsonProperty("timestamp") final UnsignedLongParameter timestamp,
      @JsonProperty("extraData") final String extraData,
      @JsonProperty("receiptsRoot") final Hash receiptsRoot,
      @JsonProperty("logsBloom") final LogsBloomFilter logsBloom,
      @JsonProperty("prevRandao") final String prevRandao,
      @JsonProperty("transactions") final List<String> transactions,
      @JsonProperty("withdrawals") final List<WithdrawalParameter> withdrawals,
      @JsonProperty("blobGasUsed") final UnsignedLongParameter blobGasUsed,
      @JsonProperty("excessBlobGas") final String excessBlobGas,
      ...
  }
```

Note the max long value is `2^63 - 1` and not `2^64-1` (18446744073709551615) which is expected in the tests on hive.

Maybe the solution is to use `String` for these fields like excessBlobGas, with toHexString conversions etc.
