### ISSUE TITLE
transaction selection - consider blobs

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5799]
There are 2 hive tests (blob ordering) that tests that max blobs are included in a block. Besu does not consider blobs right now for transaction selection, which is why these tests are failing.

**Comment by macfarla** [comment]
geth is also failing these 2 tests so don't think this is high priority

<div class="row" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(-1 * var(--bs-gutter-y)); margin-right: calc(-.5 * var(--bs-gutter-x)); margin-left: calc(-.5 * var(--bs-gutter-x)); color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-md-7" style="box-sizing: border-box; flex: 0 0 auto; width: 1239.39px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y);"><h2 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 500; line-height: 1.2; font-size: 2rem;"><span id="testsuite_state" style="box-sizing: border-box;">Results:</span><span> </span><span id="testsuite_name" style="box-sizing: border-box;">engine-cancun</span></h2><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><span id="testsuite_desc" style="box-sizing: border-box;">Test Engine API on Cancun.</span></p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><span id="testsuite_clients" style="box-sizing: border-box;"><dl style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><dt style="box-sizing: border-box; font-weight: 700;">go-ethereum_cancun-git</dt><dd style="box-sizing: border-box; margin-bottom: 0.5rem; margin-left: 0px;">Geth/v1.13.0-unstable-79f3c2d9-20230829/linux-amd64/go1.20.7</dd></dl></span></p></div><div class="col-md-5" style="box-sizing: border-box; flex: 0 0 auto; width: 885.278px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y);"><ul id="testsuite_info" class="justify-content-end list-group list-group-horizontal-xl" style="box-sizing: border-box; padding-left: 0px; margin-top: 0px; margin-bottom: 0px; --bs-list-group-color: #212529; --bs-list-group-bg: #fff; --bs-list-group-border-color: rgba(0, 0, 0, .125); --bs-list-group-border-width: 1px; --bs-list-group-border-radius: .375rem; --bs-list-group-item-padding-x: 1rem; --bs-list-group-item-padding-y: .5rem; --bs-list-group-action-color: #495057; --bs-list-group-action-hover-color: #495057; --bs-list-group-action-hover-bg: #f8f9fa; --bs-list-group-action-active-color: #212529; --bs-list-group-action-active-bg: #e9ecef; --bs-list-group-disabled-color: #6c757d; --bs-list-group-disabled-bg: #fff; --bs-list-group-active-color: #fff; --bs-list-group-active-bg: #0d6efd; --bs-list-group-active-border-color: #0d6efd; display: flex; flex-direction: row; border-radius: var(--bs-list-group-border-radius); justify-content: flex-end !important;"><li id="testsuite_start" class="list-group-item" style="box-sizing: border-box; position: relative; display: block; padding: var(--bs-list-group-item-padding-y) var(--bs-list-group-item-padding-x); color: var(--bs-list-group-color); text-decoration: none; background-color: var(--bs-list-group-bg); border: var(--bs-list-group-border-width) solid var(--bs-list-group-border-color); border-top-left-radius: inherit; border-top-right-radius: 0px; border-bottom-left-radius: var(--bs-list-group-border-radius);">🕒 06/09/2023, 08:08:25</li><li id="testsuite_duration" class="list-group-item" style="box-sizing: border-box; position: relative; display: block; padding: var(--bs-list-group-item-padding-y) var(--bs-list-group-item-padding-x); color: var(--bs-list-group-color); text-decoration: none; background-color: var(--bs-list-group-bg); border-top-color: ; border-top-style: ; border-top-width: var(--bs-list-group-border-width); border-right-color: ; border-right-style: ; border-right-width: ; border-bottom-color: ; border-bottom-style: ; border-bottom-width: ; border-left-color: ; border-left-style: ; border-left-width: 0px; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ;">⌛️ 8min0s</li><li class="list-group-item" style="box-sizing: border-box; position: relative; display: block; padding: var(--bs-list-group-item-padding-y) var(--bs-list-group-item-padding-x); color: var(--bs-list-group-color); text-decoration: none; background-color: var(--bs-list-group-bg); border-top-color: ; border-top-style: ; border-top-width: var(--bs-list-group-border-width); border-right-color: ; border-right-style: ; border-right-width: ; border-bottom-color: ; border-bottom-style: ; border-bottom-width: ; border-left-color: ; border-left-style: ; border-left-width: 0px; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-bottom-right-radius: inherit; border-bottom-left-radius: 0px; border-top-right-radius: var(--bs-list-group-border-radius);"><a id="sim-log-link" href="https://hivecancun.ethdevops.io/viewer.html?suiteid=1693952186-e02d410eb72a0d4942d5ea9076243539.json&amp;suitename=engine-cancun&amp;file=%2Fresults%2F1693951704-simulator-b7def7933128dc5c93658c689a130f1764df449416af91af2a773685c5c01292.log" style="box-sizing: border-box; color: rgb(0, 0, 0); text-decoration: underline;">simulator log</a></li></ul></div></div><div id="execresults_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer" style="box-sizing: border-box; margin-top: 10px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="row" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(-1 * var(--bs-gutter-y)); margin-right: calc(-.5 * var(--bs-gutter-x)); margin-left: calc(-.5 * var(--bs-gutter-x));"><div class="col-sm-12 col-md-6" style="box-sizing: border-box; flex: 0 0 auto; width: 1062.34px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y);"><div class="dataTables_length" id="execresults_length" style="box-sizing: border-box;"><label style="box-sizing: border-box; display: inline-block; font-weight: 400; text-align: left; white-space: nowrap;">Show<span> </span><select name="execresults_length" aria-controls="execresults" class="form-select form-select-sm" style="box-sizing: border-box; margin: 0px; font-family: inherit; font-size: 0.875rem; line-height: 1.5; text-transform: none; overflow-wrap: normal; display: inline-block; width: auto; padding: 0.25rem 2.25rem 0.25rem 0.5rem; font-weight: 400; color: rgb(33, 37, 41); background-color: rgb(255, 255, 255); background-image: url(&quot;data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e&quot;); background-repeat: no-repeat; background-position: right 0.75rem center; background-size: 16px 12px; border: 1px solid rgb(206, 212, 218); border-radius: 0.25rem; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; appearance: none;"><option value="10" style="box-sizing: border-box;">10</option><option value="25" style="box-sizing: border-box;">25</option><option value="50" style="box-sizing: border-box;">50</option><option value="100" style="box-sizing: border-box;">100</option></select><span> </span>entries</label></div></div><div class="col-sm-12 col-md-6" style="box-sizing: border-box; flex: 0 0 auto; width: 1062.34px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y);"><div id="execresults_filter" class="dataTables_filter" style="box-sizing: border-box; text-align: right;"><label style="box-sizing: border-box; display: inline-block; font-weight: 400; white-space: nowrap; text-align: left;">Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="execresults" style="box-sizing: border-box; margin: 0px 0px 0px 0.5em; font-family: inherit; font-size: 0.875rem; line-height: 1.5; outline-offset: -2px; appearance: none; display: inline-block; width: auto; padding: 0.25rem 0.5rem; font-weight: 400; color: rgb(33, 37, 41); background-color: rgb(255, 255, 255); background-clip: padding-box; border: 1px solid rgb(206, 212, 218); border-radius: 0.25rem; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; min-height: calc(1.5em + 0.5rem + 2px);"></label></div></div></div><div class="row dt-row" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(-1 * var(--bs-gutter-y)); margin-right: calc(-.5 * var(--bs-gutter-x)); margin-left: calc(-.5 * var(--bs-gutter-x)); position: relative;"><div class="col-sm-12" style="box-sizing: border-box; flex: 0 0 auto; width: 2124.69px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y);">

Test | Status | ⌛️ | Logs
-- | -- | -- | --
Blob Transaction Ordering, Multiple Clients (go-ethereum_cancun-git)

</div></div></div>Results: engine-cancun
Test Engine API on Cancun.

go-ethereum_cancun-git
Geth/v1.13.0-unstable-79f3c2d9-20230829/linux-amd64/go1.20.7

🕒 06/09/2023, 08:08:25
⌛️ 8min0s
[simulator log](https://hivecancun.ethdevops.io/viewer.html?suiteid=1693952186-e02d410eb72a0d4942d5ea9076243539.json&suitename=engine-cancun&file=%2Fresults%2F1693951704-simulator-b7def7933128dc5c93658c689a130f1764df449416af91af2a773685c5c01292.log)
Show 
100
 entries
Search:
Test	Status	⌛️	Logs
Blob Transaction Ordering, Multiple Clients (go-ethereum_cancun-git)

**Comment by non-fungible-nelson** [comment]
@Gabriel-Trintinalia @macfarla @jflo let's check for close / complete. Thank you!

**Comment by jflo** [comment]
Test is passing.
