### ISSUE TITLE
--genesis-file CLI description doesn't match Besu's behaviour 

### ISSUE THREAD

**Issue by gfukushima** [hyperledger/besu#5877]
```
 --genesis-file=<FILE>  Genesis file. Setting this option makes --network
                               option ignored and requires --network-id to be
                               set.

--network option and --genesis-file option can't be used at the same time.  Please refer to CLI reference for more details about this constraint.
```

Issue raised by Sea Monkey user in discord: https://discord.com/channels/905194001349627914/938504958909747250/1151712519388397619

"I was pointing out that the CLI reference contradicts the actual behavior of the client.  It implies that --genesis-file overrides --network.  Instead, the client errors and exits"

**Comment by non-fungible-nelson** [comment]
Changing docs to address this behavior. These options CANNOT be used in conjunction, one or the other must be used, not both.
