### ISSUE TITLE
Unnecessary DNS Lookups to raw.githubusercontent.com

### ISSUE THREAD

**Issue by akshaykant** [hyperledger/besu#5878]
**Description:**

We are running a private blockchain using the Besu client on a VM with an internal network setup. We have observed continuous DNS lookups to **raw.githubusercontent.com**, which I believe are unnecessary for this setup.

**Setup Details:**

Besu Version: 23.4.0

OS: Linux RHEL 8

Number of Nodes: 4
All nodes are running on the same VM, as part of different **docker containers using besu docker image** and are part of the same internal docker network.

**IBFT** algorithm is used for blockchain consensus protocol as part of this network.

**Expected Behavior:**

Given that my nodes are all on an internal network and  not relying on external configurations/scripts, I would expect no external DNS lookups, especially continuous ones.

**Actual Behavior:**
Continuous DNS lookups to raw.githubusercontent.com.

What could be the expected resolution for this.

Here is the reference in the [code](https://github.com/search?q=repo%3Ahyperledger%2Fbesu%20raw.githubusercontent.com&type=code).

**Comment by jflo** [comment]
What you've found is part of our build automation, and would not be present on any built binaries/docker files that we produce.

What type of peer discovery do you have for your private network?

Could you provide the evidence you have captured that leads you to believe this so we can analyze further?

**Comment by akshaykant** [comment]
Bootnodes is setup as the peer discovery with Node 1 is used to discover other peers in the network.

A docker network is set for these 4 Nodes.

As part of docker-compose.yml, here is the snippet of the network.

``priv-besu-net: 
      name: net-name 
      external: true``


Here is the snippet of config.toml

``host-allowlist=["*"] 
rpc-ws-enabled=true discovery-enabled=true rpc-http-apis=["ETH", "NET", "WEB3", "ADMIM", "IBFT"] 
p2p-host=docker subnet ip
bootnodes=[enode:node1]``

Regarding the analysis, the infrastructure team were able to trace the requests for dns resolution being called continuously.

We could perform any specific analysis you feel could be needed for this, and any specific tool to use for this analysis.

**Comment by akshaykant** [comment]
> What you've found is part of our build automation, and would not be present on any built binaries/docker files that we produce.
> 
> What type of peer discovery do you have for your private network?
> 
> Could you provide the evidence you have captured that leads you to believe this so we can analyze further?

Bootnodes is setup as the peer discovery with Node 1 is used to discover other peers in the network.

A docker network is set for these 4 Nodes.

As part of docker-compose.yml, here is the snippet of the network.

``priv-besu-net: 

      name: net-name 

      external: true``


Here is the snippet of config.toml

``host-allowlist=["*"] 

rpc-ws-enabled=true

discovery-enabled=true

rpc-http-apis=["ETH", "NET", "WEB3", "ADMIM", "IBFT"] 

p2p-host=docker subnet ip

bootnodes=[enode:node1]``

Regarding the analysis, the infrastructure team were able to trace the requests for dns resolution being called continuously.

We could perform any specific analysis you feel could be needed for this, and any specific tool to use for this analysis.

**Comment by macfarla** [comment]
in your besu config, do you have DNS enabled? Actually can you post your entire besu config.toml?

**Comment by macfarla** [comment]
Are you able to share the logs that show the continuous requests? Increase logging level if you can to show more info.
