### ISSUE TITLE
Empty Block Creation when Transactions are in Mempool

### ISSUE THREAD

**Issue by 7suyash7** [hyperledger/besu#5881]
On load testing Besu Private Networks (QBFT and IBFT), when Transactions are still pending in the Mempool, Besu continues to produce Empty Blocks.

![Screenshot from 2023-09-14 11-25-38](https://github.com/hyperledger/besu/assets/89125422/3953c64d-5ac8-4389-ac62-6d056efa9a58)

**Comment by non-fungible-nelson** [comment]
Do you have any more detail about the transactions? Are you pre- or post-london fork (i.e. have you specified a base-fee for the transactions)? Are you using a gas-free network? Do any of these transactions have non-sequential nonces or nonce gaps? Besu will not execute transactions that are not ready to execute and will keep them in the pool if there is a nonce gap.  

What version of Besu are you running?

**Comment by non-fungible-nelson** [comment]
@fab-10 maybe an opportunity for better logging around 0 txs included in the block (if this user is using new tx pool).

**Comment by 7suyash7** [comment]
@non-fungible-nelson, I haven't specified a base-fee for transactions since its on a gas-free network, the nonce for these transactions are correct afaik, however, when pending transactions start piling up on the network, the load generator (Caliper) throws out a Nonce Error after some time when the network gets unclogged, probably because it drops the old transactions due to them being a long time in the pool and starts processing the new ones? I'm not sure.

My besu version: besu/v23.4.4/linux-x86_64/oracle-java-17

**Comment by fab-10** [comment]
if all the produced blocks have not transactions, then probably no transaction is _executable_ at that moment, and there could be different reason for that, for example the gas price, the account balances and gaps in the nonce sequence. I need to setup this load generator locally in order to reproduce its behavior.
@7suyash7 could you share the way you setup Caliper so I can try to reproduce it myself?

**Comment by ahamlat** [comment]
@fab-10 I made a meeting with @7suyash7 and suggest him to create this ticket, I also asked the process to reproduce the load testing with Caliper, I will share the results with you once I have the documentation

**Comment by 7suyash7** [comment]
Yes, @fab-10 as Ameziane said he has already requested a document to reproduce my Caliper setup, I'm waiting for my PR at Caliper to merge so it becomes way easier to get it setup and running.
