### ISSUE TITLE
besu t8n (not server) rejects txs.rlp file

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#5910]
```
http://retesteth.ethdevops.io/results/log//2023-09-20-1695205499-dretesteth.txt
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 56, column 1
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 56, column 1
```

why?  it was working before and geth t8n accepts it. (actually all the other t8n's are fine)

**Comment by garyschulte** [comment]
@shemnon any insight on why we might have t8n parsing issues in the latest main?

**Comment by winsvega** [comment]
It might be still this one 

https://github.com/hyperledger/besu/issues/5934

If it appers again I reopen  the issue

**Comment by shemnon** [comment]
There are two issues: (a) the error in #5934 and (b) our encodeing trips up retesteth because of escaped tabs and newlines.  This bug will track the latter.
