### ISSUE TITLE
Devnet9 Hive Fail - Blob TX replacement

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#5922]
To reproduce, i use the following setup to debug hive tests:

i hacked a thing: https://github.com/ethereum/hive/compare/master...jflo:hive:local_debug_hacks

which uses this snooper as a fake client

https://github.com/parithosh/json_rpc_snoop/compare/master...jflo:json_rpc_snoop:dualSnoopers

which you'll have to build and tag, so the hive test will use it.

then ran hive like:

` ./hive -sim ethereum/engine -client-file ./configs/local-client.yaml --sim.limit "engine-cancun/Replace Blob Transactions" --docker.output`  to isolate a single test, and step through in my debugger.

Replace Blob Transactions (Cancun) is the failing test, and it is expecting only 1 blob transaction in the produced block, assuming that the second one sent would replace the prior one, instead of being sent with it.  The two that are included in the produced block are from the same sender, and they have the same nonce, so this is likely a bug, not a pricing issue.

**Comment by fab-10** [comment]
Not reproducible, probably already fixed elsewhere
