### ISSUE TITLE
Devnet9 Hive Fail - peering fail on ForkID tests

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#5924]
To reproduce, i use the following setup to debug hive tests:

i hacked a thing: https://github.com/ethereum/hive/compare/master...jflo:hive:local_debug_hacks

which uses this snooper as a fake client

https://github.com/parithosh/json_rpc_snoop/compare/master...jflo:json_rpc_snoop:dualSnoopers

which you'll have to build and tag, so the hive test will use it.

then ran hive like:

./hive -sim ethereum/engine -client-file ./configs/local-client.yaml --sim.limit "engine-cancun/ForkID: Genesis at " --docker.output to isolate a single test, and step through in my debugger.

`ForkID: Genesis at *` are the tests failing. Suspect peers may be disagreeing over forkId.

**Comment by Gabriel-Trintinalia** [comment]
This seems to work in their environment. Need to understand what is different

**Comment by non-fungible-nelson** [comment]
Need to confirm this is still passing in the hive environment.

**Comment by macfarla** [comment]
It is failing in the hive environment. error indicates unable to connect to mock client

FAIL: Error waiting for response: could not rlp decode message: EOF

**Comment by Gabriel-Trintinalia** [comment]
Removing from the fork_id.go in the engine simulator makes the tests pass. It looks like an issue when waiting for the pong response

	```
// Finally wait for the pong response
	/*	msg, err := conn.WaitForResponse(timeout, 0)
		if err != nil {
			t.Fatalf("FAIL: Error waiting for response: %v", err)
		}
		switch msg := msg.(type) {
		case *devp2p.Pong:
			t.Logf("INFO: Received pong response: %v", msg)
		default:
			t.Fatalf("FAIL: Unexpected message type: %v", err)
		}*/
```

**Comment by Gabriel-Trintinalia** [comment]
https://github.com/hyperledger/besu/pull/5955

**Comment by Gabriel-Trintinalia** [comment]
Fixed by https://github.com/hyperledger/besu/pull/5955
