### ISSUE TITLE
Snap sync'd QBFT validator fails to start mining after sync has completed

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu#5935]
### Description
With a 5-validator-node QBFT chain, stop one of the validators, delete its DB, then restart with `SNAP_X` sync mode. The sync completes, but the node never starts mining.

I spotted this while raising/fixing https://github.com/hyperledger/besu/issues/5856. That issue resolved an `NPE` with both `FAST` and `SNAP_X` sync but with the latter, the node never starts mining.

### Acceptance Criteria
After a successful `SNAP_X` sync with other QBFT nodes, a validator should continue mining new blocks.

**Comment by matthew1001** [comment]
Closing as invalid. `X_SNAP` not currently supported with QBFT

**Comment by icemagno** [comment]
Consider adding to https://besu.hyperledger.org/public-networks/get-started/connect/sync-node
