### ISSUE TITLE
Devnet9 Hive Fail - parent beacon root timestamps not at expected storage

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#5937]
To reproduce, i use the following setup to debug hive tests:

i hacked a thing: https://github.com/ethereum/hive/compare/master...jflo:hive:local_debug_hacks

which uses this snooper as a fake client

https://github.com/parithosh/json_rpc_snoop/compare/master...jflo:json_rpc_snoop:dualSnoopers

which you'll have to build and tag, so the hive test will use it.

then ran hive like:

` ./hive -sim ethereum/engine -client-file ./configs/local-client.yaml --sim.limit "engine-cancun/ForkchoiceUpdatedV2 To Request Shanghai" --docker.output`  to isolate a single test, and step through in my debugger.

**Comment by macfarla** [comment]
fixed by #5949
