### ISSUE TITLE
Add a toString implementation for TransactionSimulatorResult

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5942]
Add a toString implementation for TransactionSimulatorResult

Default toString(): TransactionSimulatorResult inherits toString() from Object, and so is not suitable for printing.

see https://github.com/hyperledger/besu/security/code-scanning/1029

**Comment by Shritesh99** [comment]
Hi, can I work on the issue?

**Comment by macfarla** [comment]
> Hi, can I work on the issue?

Go ahead @Shritesh99 - assigned the issue to you!
