### ISSUE TITLE
eth_call strict parameter not working as intended

### ISSUE THREAD

**Issue by nano-adhara** [hyperledger/besu#5943]
### Description
As a besu blockchain consumer, I want that eth_call strict parameter is working as intended defaulting to false when value is not provided.

Not providing the strict parameter should work as intended as defined in changelog 21.1.0:
https://github.com/hyperledger/besu/blob/main/CHANGELOG.md#2110-breaking-changes

The implementation for this parameter was included as part of 21.1.0 as we can see in here:
https://github.com/hyperledger/besu/blob/21.1.0/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java

It was working as intended until 21.7.0 version where this code changed:
https://github.com/hyperledger/besu/blob/21.7.0/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java

Motivation for this change was this PR https://github.com/hyperledger/besu/pull/2445 but these changes are not working as intended, because not sending the strict parameter is actually working the same as strict: true. 

Only workaround is to actually send the strict: false.

### Steps to Reproduce (Bug)
1. Execute any call without providing strict parameter to eth_call in any version post 21.1.7. Call should be performed with an account that doesnt have any balance.
2. Error returned Upfront cost exceeds account balance from Besu

**Expected behavior:**
Not providing the strict parameter should work as intended as defined in changelog 21.1.0:
https://github.com/hyperledger/besu/blob/main/CHANGELOG.md#2110-breaking-changes

**Actual behavior:**
Error returned Upfront cost exceeds account balance from Besu

**Frequency:** 
Always

### Versions (Add all that apply)
* Software version: [`besu --version`] Any version > 21.1.7

**Comment by non-fungible-nelson** [comment]
This is a great candidate for a PR - do you have enough knowledge to open one we can review? Reaching out in #besu-contributors on discord is also a great place to get help. 

If not, I will have the maintainers take a look and prioritize when we are able. Thank you for the report.

**Comment by Shritesh99** [comment]
Hi, Can I work on the issue?

**Comment by non-fungible-nelson** [comment]
Yes absolutely! No permission needed. Please go ahead and reach out on #besu-contributors with any questions.

**Comment by macfarla** [comment]
Ok the confusion is that we [said](https://github.com/hyperledger/besu/blob/main/CHANGELOG.md#2110-breaking-changes)
> eth_call will not fail for account balance issues by default. 

which implies the default for strict is false - whereas the code actually tries to get a "sensible" default based on the other values.

The change in #6045 effectively makes the default for `strict` false for pre-1559 (if gas=0, check the sender's balance, if gas !=0, don't check the balance)

Whereas current behavior is to check the balance if gas != 0 (even if `strict` not specified)

However
* I don't know if it makes sense for the behaviour to be different there for pre-1559 vs post-1559 - and not sure of the implications of changing this
* if we do want to make that change, it's much clearer to just default `strict` to false directly 

The other option is to more clearly define/doc the behavior when `strict` is not specified

@siladu @matkt welcome your input

**Comment by macfarla** [comment]
@nano-adhara I think you could get your desired result by not including gas price in the eth_call - then the balance would not be checked - does this work for you?

**Comment by nano-adhara** [comment]
@macfarla documentation/changelog is fine as a solution for this, specifying that the absence of strict value is the same as strict true. what is weird to me is if it should be different for pre-1559 vs post-1559. 

related to the gas price itself, it could be a possibility, but technically if i need to change behavour, id rather make explicit strict false calls to the blockchain client so im not impacted by unexecpected backwards breaking compatibility changes

**Comment by macfarla** [comment]
created a docs issue for this - https://github.com/hyperledger/besu-docs/issues/1429

thanks for raising @nano-adhara
