### ISSUE TITLE
Devnet 9 - Blob Memory Leak & DOS

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5944]
Conversation in Eth R&D discord in the Dencun- Interop channel on 9/21:  

https://discord.com/channels/595666850260713488/892088344438255616/1154487164999045280

> I'm testing nethermind's blob pool by sending 16k 6-blob txs (16 txs from 1000 senders) and looks like I accidentally killed few nodes https://ethstats.dencun-devnet-8.ethpandaops.io/
14k txs already sent, 2k left

The spammer being used is here: https://github.com/NethermindEth/nethermind/tree/feature/send-blobs-tool/src/Nethermind/Nethermind.SendBlobs

Besu died with OOM error.

**Comment by fab-10** [comment]
Until we have a good support for Blobs in the txpool, it make sense that we tune some options to reduce the effects of too many blobs
