### ISSUE TITLE
Is there any Privacy Enhancements feature available in Hyperledger Besu (Similar to GoQuorum)?

### ISSUE THREAD

**Issue by ghost** [hyperledger/besu#5982]
### Context
In addition to the [standard privacy (SP)](https://docs.goquorum.consensys.net/concepts/privacy/private-and-public#private-transactions), GoQuorum provides three kinds of privacy enhancements:

- [Counter-party protection](https://docs.goquorum.consensys.net/concepts/privacy/privacy-enhancements#counter-party-protection)
- [Mandatory party protection](https://docs.goquorum.consensys.net/concepts/privacy/privacy-enhancements#mandatory-party-protection)
- [Private state validation](https://docs.goquorum.consensys.net/concepts/privacy/privacy-enhancements#private-state-validation)

### Query

1. Is there any similar feature available in Hyperledger Besu? What are its configuration options?
2. If not natively supported, how are these scenarios handled in Besu?

**Comment by siladu** [comment]
Hi @syed-shamayel take a look at https://besu.hyperledger.org/private-networks/concepts/privacy to start with.

Maybe @macfarla or @pinges can answer any specifics about those mentioned privacy enhancements.

**Comment by macfarla** [comment]
Privacy is now deprecated. won't be adding any features to it
