### ISSUE TITLE
Disable TransactionPool observer on new blocks during Full sync 

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#6001]
### Description
During Full sync (archive node), the transaction pool observer event is triggered for each new imported block to re-organize the transaction pool (remove block's transactions, sort one of the layers per base fee, ...etc).
Besu should disable transaction pool event during Full sync (and other syncs)

![image](https://github.com/hyperledger/besu/assets/5099602/ade58a05-be70-4912-aa37-407edc253060)

### Steps to Reproduce (Performance issue)
Start Besu with Full sync and Forest.

**Expected behavior:** 
Besu does not trigger the transaction pool observer event for each new block

**Actual behavior:** [What actually happens]
Besu triggers the transaction pool observer event for each new block

**Frequency:** [What percentage of the time does it occur?]
100%

**Comment by fab-10** [comment]
Some context to help with the implementation.

* `TransactionPool` now has methods `setEnabled` and `setDisabled`.
* The txpool should be disabled when the current local chain head is too far from the target chain head, `SyncState::isInSync` already provide this information

**Comment by non-fungible-nelson** [comment]
@fab-10 if we have some "spare time" (unlikely) before Wednesday, can you take a look?

**Comment by macfarla** [comment]
@fab-10 are you working on this one?

**Comment by fab-10** [comment]
yes, currently on it
