### ISSUE TITLE
Besu Cookie Jar - Snacks & Continuous Improvements

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6018]
This epic tracks "snackable" items in the Besu backlog and overall continuous improvements that don't necessarily tie to another epic (or one's that do but are small tasks). 

Use this epic when you want to take a break from other work or have a small amount of time before another obligation. This can be picked up whenever you have a moment or when you have hit a wall but are still caffeinated :)

**Comment by macfarla** [comment]
This epic is not needed. `snack` label is fine as a signal for this.
