### ISSUE TITLE
trace_callMany API with block number option is not working properly

### ISSUE THREAD

**Issue by sungmin7465** [hyperledger/besu#6033]
### Description

when calling trace_callMany API with blockNumber option (any value except 'latest'), it always returns a result based on latest block state. 
 

### Steps to Reproduce (Bug)
1. call trace_callMany API with a blockNumber
`const result = await provider.send('trace_callMany', [
                [
                    [
                        {
                            from: admin.address,
                            to: args.target,
                            gas: '0xfffffffff',
                            data: calldata,
                        },
                        ['trace'],
                    ],
                ],
                '1940',
            ]);`

**Expected behavior:**
it returns a result based on 1940st block's state in the blockchain

**Actual behavior:**
it returns a result based on latest block's state in the blockchain

**Frequency:**
always 

### Logs
`2023-10-16 13:37:32.472+09:00 | vert.x-worker-thread-15 | DEBUG | JsonRpcExecutor | JSON-RPC request -> trace_callMany [[[{"from":"0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1","to":"0xC89Ce4735882C9F0f0FE26686c53074E09B0D550","gas":"0xfffffffff","data":"0x111002aa0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a66697273745f7461736b00000000000000000000000000000000000000000000"},["trace"]]],"1940"]`

`2023-10-16 13:37:32.473+09:00 | vert.x-eventloop-thread-3 | DEBUG | JsonRpcHttpService | Connection closed from 127.0.0.1:54797. Total of active connections: 2/80`

`2023-10-16 13:37:32.490+09:00 | vert.x-worker-thread-15 | TRACE | TraceCallMany | Received RPC rpcName=trace_callMany trace_callManyParams=[org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.TraceCallManyParameter@33c0a4d6] block=1963`

### Versions
Software version : besu/23.10.1

**Comment by non-fungible-nelson** [comment]
Thanks for picking up this issue. We will have a maintainer review the PR!
