### ISSUE TITLE
Set default `--tx-pool-price-bump` to `0` for `zeroBaseFee` chains

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu#6043]
### Description
See discord discussion https://discord.com/channels/905194001349627914/905205502940696607/1163795216256471042

After discussion with @fab-10 and @ajsutton there was a general consensus that for free gas chains, the price bump % ought to be set to a default value of `0%`, instead of `10%`. Replacement of transactions in a free gas chain where `priceBump != 0` is effectively impossible and relies on unpleasant work-arounds (such as setting TX pool retention to 1 hour and waiting for it to be removed).

### Acceptance Criteria
When I create a new Besu node with `zeroBaseFee=0` and/or `--max-gas-price=0` the value of `--tx-pool-price-bump` is set to a default value of 0. I can change it back to 10% or any other valid value by setting it manually.

**Comment by matthew1001** [comment]
Having raised this, I re-tested the effect of `--tx-pool-price-bump=0` with non-EIP1559 transactions, and even setting it to 0 does not allow you to replace a transaction.

It would require the addition of e.g.

```
if (priceBump.getValue() == 0
        && existingPendingTransaction.getGasPrice().compareTo(newPendingTransaction.getGasPrice())
            == 0) {
      return true;
}
```

to `TransactionReplacementByGasPriceRule.shouldReplace()` for it to accept a new transaction as the replacement for an old one with the same `gasPrice`.

I would have added the above under this or another issue, but my concern is that the EIP1559 test (`TransactionReplacementByFeeMarketRule.shouldReplace()`) has a specific check for the new TX having 0:

```
// bail early if price is not strictly positive
    if (newEffPrice.equals(Wei.ZERO)) {
      return false;
}
```

So I'm reticent to put a change like ^^ in since anyone who switched from `gasPrice` to `maxBaseFee/maxPriorityFee` would suddenly see a breaking change in TX replacement behaviour.

**Comment by fab-10** [comment]
I think, that we just miss the specific _transaction replacement rule_ for zero base fee chains, like we have it for the other fee market. Such rule can just accept any replacement without checking the price.

**Comment by fab-10** [comment]
Following you initial investigation, I have made this PR #6079 that should make `--tx-pool-price-bump=0` works as expected

**Comment by matthew1001** [comment]
Thanks @fab-10 Sorry for the delay, just back from a week off. Yes I'd be happy to give it a try, I'll pull the branch now.
