### ISSUE TITLE
Accept `input` as well as `data` in eth_call

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#6055]
Context on #6041

We currently only accept `data` as the name of the payload field when during an eth_call (and presumably other transaction-related RPCs) https://github.com/hyperledger/besu/blob/a90ea056f19915a4eca787fc066c080e1789c14c/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java#L52-L53

The spec requires `input` as the name instead:
https://github.com/ethereum/execution-apis/blob/057892b256c181232ca22499d1801b9637192698/src/schemas/transaction.yaml#L33

We will need to continue accepting `data` to avoid forcing a lot of tooling to update.

We should add support for `input` xor `data`

**Comment by non-fungible-nelson** [comment]
Context in [discord here.](https://discord.com/channels/905194001349627914/905205502940696607/1164073135235137566)
