### ISSUE TITLE
Issue on peer connection 

### ISSUE THREAD

**Issue by Neoblock8** [hyperledger/besu#6065]
Hi,
 Running besu private node in server, all the ports are in public. Trying to connect peernode in another server, but peer connection always returns 0.
  Added enode in static-node.json
  
  How to connect a fullnode?

**Comment by non-fungible-nelson** [comment]
Maybe related to #6039 

If you have your ADMIN namespace enabled on rpc - you can try using this [addPeer method. ](https://besu.hyperledger.org/public-networks/reference/api#admin_addpeer)

**Comment by macfarla** [comment]
@Neoblock8 are you still having issues? If so can you provide more detailed info including besu logs

**Comment by macfarla** [comment]
closing as a stale issue
