### ISSUE TITLE
Cannot resolve all.mainnet.ethdisco.net

### ISSUE THREAD

**Issue by TheAviationDoctor** [hyperledger/besu#6070]
### Description

- Besu is reporting DNS resolution errors to `all.mainnet.ethdisco.net` every 10 minutes in the log.
- Besu behaves otherwise as expected (attesting and peering are fine - even a sync committee happened successfully), so the issue does not appear to affect node and staking operations in any way.
- This is on a staking NUC running Besu+Nimbus with dedicated 1Gbs fiber and ports 9000 & 30303 open.

### Steps to Reproduce (Bug)

As far as I can tell, simply run Besu v23.10.0 on the config described below.

**Expected behavior:** Besu should be able to resolve `all.mainnet.ethdisco.net` (if the server exists) or not attempt to resolve it (if the server does not exist).

**Actual behavior:** Besu attempts and is unable to resolve `all.mainnet.ethdisco.net`. I also tried resolving/pinging/tracerouting `all.mainnet.eth.disco` myself, and am unable to (`ping: all.mainnet.ethdisco.net: No address associated with hostname`). I can ping other known servers just fine.

**Frequency:** Every 10 minutes exactly.

### Logs (if a bug)

```
Oct 22 14:54:48 intel-nuc besu[906]: 2023-10-22 14:54:48.204+08:00 | vert.x-eventloop-thread-1 | WARN  | DNSResolver | I/O exception contacting remote DNS server when resolving all.mainnet.ethdisco.net
Oct 22 14:54:48 intel-nuc besu[906]: io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Network is unreachable
[...]
Oct 22 15:04:48 intel-nuc besu[906]: 2023-10-22 15:04:48.204+08:00 | vert.x-eventloop-thread-1 | WARN  | DNSResolver | I/O exception contacting remote DNS server when resolving all.mainnet.ethdisco.net
Oct 22 15:04:48 intel-nuc besu[906]: io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Network is unreachable
```

### Versions (Add all that apply)

* Software version: besu v23.10.0
* Java version: 17.0.8.1 2023-08-24
* OS Name & Version: Ubuntu 22.04.3 LTS
* Kernel Version: Linux 5.15.0-87-generic 97
* Virtual Machine software & version: N/A
* Docker Version: N/A
* Cloud VM, type, size: N/A
* Consensus Client & Version if using Proof of Stake: Nimbus beacon node v23.10.0-8b07f4-stateofus

### Additional Information (Add any of the following or anything else that may be relevant)

* Besu setup info: see below
* System info: 32Gb, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
* DNS was switched from the ISP's to 8.8.8.8 in an attempt to rule out resolution issues, to no effect

```
[Unit]
Description = Besu Execution Client (Mainnet)
Wants       = network-online.target
After       = network-online.target

[Service]
User        = besu
Group       = besu
Type        = simple
Restart     = always
RestartSec  = 5
Environment = "JAVA_OPTS=-Xmx8g"
ExecStart   = /usr/local/bin/besu/bin/besu \
  --network=mainnet \
  --sync-mode=X_CHECKPOINT \
  --data-path=/mnt/ssd/besu \
  --data-storage-format=BONSAI \
  --rpc-http-enabled=true \
  --engine-host-allowlist=localhost,127.0.0.1 \
  --engine-jwt-secret=/mnt/ssd/secrets/jwtsecret \
  --max-peers=32 \
  --Xplugin-rocksdb-high-spec-enabled

[Install]
WantedBy    = multi-user.target
```

**Comment by shemnon** [comment]
DNS info is not currently published

https://github.com/ethereum/discv4-dns-lists/issues/9

The bug to besu would be to fail in a quieter fashion.

**Comment by non-fungible-nelson** [comment]
Referencing #5725 - Needs Tuweni logging change.

**Comment by zrock23** [comment]
I immediately joined in I personally work with a dns server: nessi.cloudns.cl

**Comment by siladu** [comment]
Hi @TheAviationDoctor is this still a problem for you?

**Comment by TheAviationDoctor** [comment]
> Hi @TheAviationDoctor is this still a problem for you?

Hi @siladu, yes, I am still seeing this DNSResolver issue every 10 minutes in the Besu log, even after upgrading Besu to v23.10.1.

Not a big deal, though, as it does not seem to impact peering nor attestations in any meaningful way.
