### ISSUE TITLE
Install binary distribution in ubuntu

### ISSUE THREAD

**Issue by digitalinformation** [hyperledger/besu#6084]
What do I do after downloading the besu binary here? I can't find the /bin/besu directory in the downloaded installation package, and typing /bin/besu --help on the command line shows that there is no file or directory, what should I do?
In addition, what is the difference between docker installation besu and binary installation besu
![1](https://github.com/hyperledger/besu/assets/94784449/b99e3189-61df-48a9-ac8c-d438b0dc4430)
![图片](https://github.com/hyperledger/besu/assets/94784449/bbe9bbce-4e38-4dd8-a024-50fc27a04faa)

**Comment by digitalinformation** [comment]
What is the reason for this? Do you want to create a directory? So where to create a directory?
![2](https://github.com/hyperledger/besu/assets/94784449/5cf0550f-94d2-46e6-a414-5ff9694987ca)

**Comment by jframe** [comment]
@digitalinformation It looks like you have downloaded the source distribution of Besu and not the binaries. On the releases page https://github.com/hyperledger/besu/releases the jfrog links have the binary distribution you need.

The directory structure should look like this.
<img width="230" alt="Screenshot 2023-11-02 at 8 09 35 am" src="https://github.com/hyperledger/besu/assets/909467/c66dcec4-cc52-4af3-b031-57ae1ea513d7">

Then you can run besu from the bin directory.

re: docker question
You do need to create a directory. The directory is needed for the local database that Besu uses as it's copy of the blockchain. It's up to you where you create the directory but for the location you will need to have a large amount of disk space at least 650GB for mainnet https://besu.hyperledger.org/development/public-networks/concepts/data-storage-formats#storage-requirements.
