### ISSUE TITLE
Minor issue on Mac installation documentation

### ISSUE THREAD

**Issue by tjayrush** [hyperledger/besu#612]
### Description

I am a regular non-mining user of `besu` on Mac. I noticed a small issue in the installation docs for Brew.

### Steps to Reproduce (Bug)

I initially installed Besu prior to version 1.4.2 using `Brew` on Mac. The installation was very easy and went smoothly.  Recently, I upgraded to version 1.4.2. (I'm not very familiar with using `brew`).

The instructions (here: https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Install-Binaries/) tell me to use `brew install hyperledger/besu/besu` which I did, but I didn't notice the message saying I should use `brew upgrade hyperledger/besu/besu`.

I stupidly spent longer than I should have trying to figure out why the `besu --version` still reported the previous version.

**Expected behavior:** [What you expect to happen]

Add instructions for 'newbie' `brew` users (who don't pay careful enough attention) to use ``brew upgrade hyperledger/besu/besu` if they already have a previous version of `besu` installed.

**Comment by grantnoble** [comment]
Created pull request in besu-docs repository: https://github.com/hyperledger/besu-docs/pull/290.
Updated instructions to include upgrading an existing installation using homebrew, and also displaying the version number.

**Comment by grantnoble** [comment]
Fixed by [hyperledger/besu-docs#290](https://github.com/hyperledger/besu-docs/pull/290), closing.
