### ISSUE TITLE
Document the Clique option to not create empty blocks

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu#6123]
In the [Genesis file](https://besu.hyperledger.org/development/private-networks/how-to/configure/consensus/clique) topic, document the new Clique option, `createemptyblocks`, to prevent the creation of empty blocks.

See PR: [Add option to clique to skip creating empty blocks #6082](https://github.com/hyperledger/besu/pull/6082) for details.

**Comment by siladu** [comment]
Hi @mjsmike62 think this should be in besu-docs repo

**Comment by mjsmike62** [comment]
Issue was created in wrong repo.
