### ISSUE TITLE
Document the Json RPC methods: `miner_setMinPriorityFee` and `miner_getMinPriorityFee`

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu#6124]
Document the new Json RPC methods: `miner_setMinPriorityFee` and `miner_getMinPriorityFee`.

See PR: [Implement miner_setMinPriorityFee and miner_getMinPriorityFee #6080](https://github.com/hyperledger/besu/pull/6080) for details.

**Comment by siladu** [comment]
Issue should be opened in besu-docs please 🙏

**Comment by mjsmike62** [comment]
Issue was created in wrong repo.
