### ISSUE TITLE
Doc the parameter violations for the Json RPC method `setMinPriorityFee`: invalid parameter and missing parameter

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu#6125]
Document the parameter violations for the new Json RPC method `setMinPriorityFee`: invalid parameter and missing parameter. Invalid parameter could be one that's too large (>32 bytes).

See [setMinPriorityFee - Return Invalid Param when invalid and use hexadecimal instead of Long #6099](https://github.com/hyperledger/besu/pull/6099) for details. [Document the Json RPC methods: miner_setMinPriorityFee and miner_getMinPriorityFee #6124](https://github.com/hyperledger/besu/issues/6124) is related to this issue.

**Comment by siladu** [comment]
besu-docs repo please :)

**Comment by mjsmike62** [comment]
Issue was created in wrong repo.

**Comment by mjsmike62** [comment]
Issue was created in wrong repo.
