### ISSUE TITLE
Document the JSON RPC methods: `miner_getMinGasPrice` and `miner_setMinGasPrice` for the `min-gas-price` CLI option

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu#6132]
Document the new JSON RPC methods: `miner_getMinGasPrice` and `miner_setMinGasPrice` for the `min-gas-price` CLI option [topic](https://besu.hyperledger.org/public-networks/reference/cli/options#min-gas-price).

See [Add API to set and get the minGasPrice at runtime #6097](https://github.com/hyperledger/besu/pull/6097) for details.

**Comment by siladu** [comment]
Open in besu-docs please :)

**Comment by mjsmike62** [comment]
Issue was created in wrong repo.
