### ISSUE TITLE
Point Sepolia validators to mev-relays

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#6134]
From Pari

> Someone working at the EF with ERC-4337 bundlers reached out and asked if we can point more sepolia validators towards mev-relays. Currently the number is ~40%, goerli is the highest at 64%(but deprecated) and mainnet has ~94%. So ideally they want to move from goerli to sepolia, but would need a higher % to be using mev-relays.

**Comment by siladu** [comment]
@non-fungible-nelson can you help us prioritise this please

**Comment by non-fungible-nelson** [comment]
Hey @matkt - can you take a look at this as part of devwatch this week?
