### ISSUE TITLE
Better handling of private and public nonces with Private Transactions

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#614]
This problem was first identified on #571. Given that the private transaction has its own nonce (relative to the sender account withing the privacy group), and the PMT has its own nonce (relative to the account that is creating the PMT), things can get messy.

The simplest scenario is the following:
- account X has private nonce 0 in privacy group P
- account X has public nonce 0 in the public world
- User send privTx1 (sender: X, nonce: 0) and privTx2 (sender: X, nonce: 1)

When creating the PMT, we check for pending txs in the pool. However, things happen asynchronously so when creating the second PMT, the first one might not be in the pool yet. So we might end up with:
-  PMT1(privTx1, sender: x, nonce: 0)
- PMT2(privTx2, sender: X, nonce: 0)

This will lead to a failure of the second PMT.

Even worse, depending on the order that the transactions reach the client, we might end up with:
- PMT1(privTx1, sender: x, nonce: 1)
- PMT2(privTx2, sender: X, nonce: 0)

This will cause the PMTs to succeed but the underlying private transaction will be executed in the wrong order and will fail.

We have identified a workaround, using priv_distributeRawTransaction and eth_sendRawTransaction, to have control over the private and public nonces being used. However, this is hard work and it would be good if we could come up with an alternative.

This is the example of using web3js-eea to do it: https://github.com/PegaSysEng/web3js-eea/blob/master/example/concurrentPrivateTransactions/concurrentPrivateTransactions.js

**Comment by MadelineMurray** [comment]
We should take this into account in the design of the interoperable privacy solution.

**Comment by nmvalera** [comment]
Would it be an option to make the private transaction nonce a unique identifier and not an incremental number? So for a private transaction to be processed, it should have a nonce that has not been used by any prior transaction.

It would
- protect private transaction against replay attacks
- ensure the ordering of transaction by relying on PMT nonce

This would require
- storing all nonces already used by an account on the account storage
- checking if a nonce has already been used without a significative drop in performance

A Bloom filter could maybe do the job but it would probably imply updating the private account data structure which is something we may prefer to avoid.

**Comment by nmvalera** [comment]
Btw Orchestrate does not use `eea_sendRawTransaction` anymore but uses a `priv_distributeRawTransaction` then `eth_sendRawTransaction` approach to retain full control over both nonces.

**Comment by macfarla** [comment]
https://github.com/hyperledger/besu/pull/2969from my tests locally
successive calls to generateAndSendRawTx are
with my change: successful with 20ms sleep. fails with 10ms
without my change, successful with 1500ms. fails with 100. fails with 1000

that's running PoW, ethash so blocktimes are < 1s
