### ISSUE TITLE
Static Peers with Useless Connection for a period of time 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6141]
### Description
Static nodes are being connected in code, but are not contributing to the initial sync. It can sometimes take 25 minutes to begin syncing in a network with low peer counts, even if directly setting static peers. There seems to be a boolean that states "isConnected" to static nodes as true, but Besu does not make the proper requests to these peers to pull data for a sync. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. Specify static peers, 
2. Start Besu,
3. Wait for a sync to begin (can take a while)
4. Check peer table, can mostly be other peers 

**Expected behavior:** [What you expect to happen]
Static nodes immediately help in peering and sync 

**Actual behavior:** [What actually happens]
Static nodes do not seem to help with sync immediately. This can cause a huge delay in syncing a fresh node 

**Frequency:** [What percentage of the time does it occur?]
Every time with static nodes

### Logs (if a bug)
Please post relevant logs from Besu (and the consensus client, if running proof of stake) from before and after the issue. 

### Versions (Add all that apply)
* Latest

**Comment by macfarla** [comment]
This issue can be fixed by setting fast-sync-min-peers=1 which works for FAST and SNAP sync - not sure if we have added that to the docs yet for X_SNAP since it's still experimental... so added the docs label so we remember to check

Otherwise, the default behavior for SNAP sync is to wait for 5 peers to confirm the pivot block.
