### ISSUE TITLE
Return yParity from eth_getBlockByNumber

### ISSUE THREAD

**Issue by quickchase** [hyperledger/besu#6149]
### Description
The outputs of eth_getBlockByNumber are not standardized across clients because of the yParity field

### Acceptance Criteria
Return yParity from eth_getBlockByNumber

### Steps to Reproduce (Bug)

Send the following JSON-RPC request to a Besu node and then either a Geth, Reth, or Nethermind Node, and compare the outputs:

```json
{"method":"eth_getBlockByNumber","params":["0x10b7cfb",true],"id":1,"jsonrpc":"2.0"}
```

Geth, Reth, and Nethermind include a field called yParity in the output. Besu does not.

**Expected behavior:**
Standardized outputs between all clients

**Actual behavior:**
yParity key missing in the output of eth_getBlockByNumber

**Frequency:**
Always

**Comment by shemnon** [comment]
Already fixed, coming in next weeks release - https://github.com/hyperledger/besu/pull/6119

**Comment by quickchase** [comment]
Thanks, I searched issues, but didn't search PRs 😄
