### ISSUE TITLE
SHA256sum mismatch in 23.10.1 release

### ISSUE THREAD

**Issue by dtto** [hyperledger/besu#6160]
### Description
The stated SHA256 checksum on the release page does not match the tar.gz release file.

### Steps to Reproduce (Bug)
1. Download 23.10.1 release
2. Attempt to confirm checksum
3. Receive checksum mismatch

**Expected behavior:** [What you expect to happen]
Checksum should match what is stated on release page:

```
https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/23.10.1/besu-23.10.1.tar.gz / sha256: e27645f345583f3ee447e5418302382c6f8335d2da8707bdd20033aabd86ce4c
```

**Actual behavior:** [What actually happens]
Checksum does not match:

```
498afb6cb4d8e5cdeae0a00db000bd2f4ed97aa833b0467ffed9668ad326f335  besu.tar.gz
```

**Frequency:** [What percentage of the time does it occur?]

100%

I have downloaded multiple times from different computers, same result.

### Logs (if a bug)
N/A

### Versions (Add all that apply)

23.10.1 tar.gz release file

**Comment by dtto** [comment]
It would also be great if the besu team could add gpg signature verification.

Thanks for all the great work!

**Comment by p4fg** [comment]
I get the same result:

```
# wget https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/23.10.1/besu-23.10.1.tar.gz
--2023-11-13 16:13:04--  https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/23.10.1/besu-23.10.1.tar.gz
Resolving hyperledger.jfrog.io (hyperledger.jfrog.io)... 13.91.18.13
Connecting to hyperledger.jfrog.io (hyperledger.jfrog.io)|13.91.18.13|:443... connected.
HTTP request sent, awaiting response... 200
Length: 165372941 (158M) [application/x-gzip]
Saving to: ‘besu-23.10.1.tar.gz’

besu-23.10.1.tar.gz                    100%[===========================================================================>] 157.71M  5.41MB/s    in 31s

2023-11-13 16:13:36 (5.16 MB/s) - ‘besu-23.10.1.tar.gz’ saved [165372941/165372941]

# sha256sum ./besu-23.10.1.tar.gz
498afb6cb4d8e5cdeae0a00db000bd2f4ed97aa833b0467ffed9668ad326f335  ./besu-23.10.1.tar.gz
```

**Comment by jflo** [comment]
Thanks for catching this, the 23.10.1 build was updated during a build of 23.10.2.RC which is on the way. Existing artifacts are correct at those URLs, but their SHAs have changed. Release notes include both the prior and current SHAs now.

https://github.com/hyperledger/besu/releases/tag/23.10.1
