### ISSUE TITLE
I have created a permissioned network on my local computer, but MetaMask cannot connect to localhost.

### ISSUE THREAD

**Issue by haerker** [hyperledger/besu#6162]
I have created a permissioned network on my local computer, but MetaMask cannot connect to localhost.

The node startup parameters include: --rpc-http-enabled --rpc-http-api=ADMIN,ETH,NET,PERM,IBFT --host-allowlist="" --rpc-http-cors-origins=""*"。chainid is 1337.
"In MetaMask, the RPC URL for the network I created is http://127.0.0.1:8545/, and the chain ID is 1337. However, it shows: 'Could not fetch chain ID. Is your RPC URL correct?'"

**Comment by siladu** [comment]
Hi @haerker have you followed the recommendations about metamask cors on here? https://besu.hyperledger.org/development/public-networks/reference/cli/options#rpc-http-cors-origins

**Comment by haerker** [comment]
hello @siladu "I am certain that my parameters are correct: “--rpc-http-enabled=true --rpc-http-host=0.0.0.0 --rpc-http-port=8545 --rpc-http-api=ADMIN,ETH,NET,PERM,IBFT --host-allowlist="" --rpc-http-cors-origins=""  ”. However, I am still encountering an error. Is this a common issue?"

**Comment by haerker** [comment]
"Additionally, my permissioned network is set up on WSL (Windows Subsystem for Linux), and my MetaMask is in Chrome. I have tried both 'localhost' and the WSL IP for the URL, but neither works."

**Comment by haerker** [comment]
**### "It has been resolved; I switched from Chrome to Firefox."**
