### ISSUE TITLE
Categorize block builder CLI options to improve UX 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#6176]
The Besu CLI help groups the following options as Block Builder options. Depending on the consensus algorithm used, some are not applicable, and some have different default values.  Grouping these and including the different default values by consensus mechanism will improve UX. 

```Block Builder Options
      --min-block-occupancy-ratio=<minBlockOccupancyRatio>
                             Minimum occupancy ratio for a mined block
                               (default: 0.8)
      --min-gas-price=<minTransactionGasPrice>
                             Minimum price (in Wei) offered by a transaction
                               for it to be included in a mined block (default:
                               0x00000000000000000000000000000000000000000000000
                               000000000000003e8)
      --min-priority-fee=<minPriorityFeePerGas>
                             Minimum priority fee per gas (in Wei) offered by a
                               transaction for it to be included in a block
                               (default:
                               0x00000000000000000000000000000000000000000000000
                               00000000000000000)
      --miner-coinbase=<coinbase>
                             Account to which mining rewards are paid. You must
                               specify a valid coinbase if mining is enabled
                               using --miner-enabled option
      --miner-enabled        Set if node will perform mining (default: false)
      --miner-extra-data=<extraData>
                             A hex string representing the (32) bytes to be
                               included in the extra data field of a mined
                               block (default: 0x)
      --miner-stratum-enabled
                             Set if node will perform Stratum mining (default:
                               false)
      --miner-stratum-host=<stratumNetworkInterface>
                             Host for Stratum network mining service (default:
                               0.0.0.0)
      --miner-stratum-port=<stratumPort>
                             Stratum port binding (default: 8008)
      --target-gas-limit=<targetGasLimit>
                             Sets target gas limit per block. If set, each
                               block's gas limit will approach this setting
                               over time.
```

**Comment by MadelineMurray** [comment]
From @fab-10 (paraphrased by me in places) 


* stratum options are definitely PoW only, but `--miner-coinbase` could possibly have a role in PoS as last resort for the fee recipient, if none is passed by the CL. 
* `--miner-extra-data` could be also used with PoS
* `--min-priority-fee` is related to the fee market, and consensus agnostic
*  `--min-block-occupancy-ratio` defaults to 1 on PoS
* `--miner-enabled` has no effect on Clique and PoS, because in these setup it is expected to build blocks

**Comment by macfarla** [comment]
closing. complete.

Block Builder Options
      --block-txs-selection-max-time=<nonPoaBlockTxsSelectionMaxTime>
                             Specifies the maximum time, in milliseconds, that could be spent
                               selecting transactions to be included in the block. Not compatible
                               with PoA networks, see poa-block-txs-selection-max-time. (default:
                               +5000)
      --min-block-occupancy-ratio=<minBlockOccupancyRatio>
                             Minimum occupancy ratio for a mined block (default: 0.8)
      --min-gas-price=<minTransactionGasPrice>
                             Minimum price (in Wei) offered by a transaction for it to be included in
                               a mined block (default:
                               0x00000000000000000000000000000000000000000000000000000000000003e8)
      --min-priority-fee=<minPriorityFeePerGas>
                             Minimum priority fee per gas (in Wei) offered by a transaction for it to
                               be included in a block (default:
                               0x0000000000000000000000000000000000000000000000000000000000000000)
      --miner-coinbase=<coinbase>
                             Account to which mining rewards are paid. You must specify a valid
                               coinbase if mining is enabled using --miner-enabled option
      --miner-enabled        Set if node will perform mining (default: false)
      --miner-extra-data=<extraData>
...
