### ISSUE TITLE
priv.distributeRawTransaction method not working

### ISSUE THREAD

**Issue by Alexsilva43** [hyperledger/besu#6180]
### Description
 In the context of concurrent transactions in a privacy group, the method priv.distributeRawTransaction of web3js-quroum library doesn't work. The method is unable to decode the private signed raw transaction. With ethers.js and web3.js out of a privacy group context, the concurrent transactions are executed correctly. 

**Expected behavior:** the method should return the enclave key.

**Actual behavior:** Error: Returned error: Unable to decode the private signed raw transaction

**Frequency:** 100% of the time

### Versions 
* Besu : 23.7.1
* Tessera: 23.4.0
* Java version: 20.0.2
* web3.js : 1.8.0
* web3js-quorum: 22.4.0
* ethereumjs-tx : 2.1.2
*  Solidity version : 0.8.20

* Have you reproduced the issue on other eth clients : No

### Additional Information: 

Snipped code in Typescript:

```
import Web3 from "web3";
const Web3Quorum = require("web3js-quorum");
const {Transaction} = require('ethereumjs-tx');

// privacy options masked
const privacyOptions = {
  privateFrom: "XXX",
  privateKey: "YYY",
  privacyGroupId: "ZZZ"
};

const web3 = new Web3("address provider");
const web3q = new Web3Quorum(web3);

const rawTx= {
    ...privacyOptions,
    to: contractAddress,
    data: "0xa621d15e",
    nonce : ethers.toBeHex(nonce)
  }
   const tx = new Transaction(raxTx);
   tx.sign(Buffer.from(privateKey, "hex"));
   const hexTx = `0x${tx.serialize().toString("hex")}`;
 
  const enclaveKey = web3q.priv.distributeRawTransaction(hexTx);
```

**Comment by non-fungible-nelson** [comment]
@gtebrean and @NickSneo - any ideas here?
