### ISSUE TITLE
Unable to create flexible privacy group with Besu version >= 22.10.0

### ISSUE THREAD

**Issue by syed-shamayel** [hyperledger/besu#6192]
### Description
We were trying to create flexible privacy group between two parties. While creating privacy group, we observed an error "Returned error: Flexible Privacy group does not exist".

This behavior is only observed for Besu's version >= 22.10.0 (including latest). 

`Note:` It is working fine with Besu's version 22.7.7.

### Steps to Reproduce (Bug)
1. Create a flexible privacy group between two parties using web3js-quorum method: `web3.eth.flexiblePrivacyGroup.create`

### Logs (if a bug)
1. Error observed from client: `Flexible Privacy group does not exist.`

### Versions (Add all that apply)
* Software version: `Besu >= 22.10.0`
* Added Configuration:  `--privacy-flexible-groups-enabled=true`

**Comment by NickSneo** [comment]
The issue could be due to this change - https://github.com/hyperledger/besu/pull/4282
And there is a web3j open issue related to this - https://github.com/web3j/web3j/issues/1821

**Comment by NickSneo** [comment]
Issue is fixed in this PR - https://github.com/Consensys/web3js-quorum/pull/58

**Comment by NickSneo** [comment]
Closing the issue as PR is merged into Web3js-Quorum
