### ISSUE TITLE
 can't connect when I connect to the 8545 node, 

### ISSUE THREAD

**Issue by digitalinformation** [hyperledger/besu#6213]
Hello, I have built a consortium chain according to the tutorial, but I always can't connect when I connect to the 8545 node, what is the reason for this?
![捕获](https://github.com/hyperledger/besu/assets/94784449/38e8b725-b169-4d98-bf02-da3f38c07d87)

**Comment by non-fungible-nelson** [comment]
Hi there - can you share your configuration file or startup parameters for Besu please?

**Comment by digitalinformation** [comment]
Hello, I am operating on the server with a remote connection to the localhost, I found yesterday that after the previous command changed localhost to 127.0.0.1, the correct result can be displayed, but I am not sure if there will be other problems, and I don't know why this result occurs, here are some materials:
![QQ图片20231201124001](https://github.com/hyperledger/besu/assets/94784449/8011db5e-759e-41b9-8869-3a219c777703)











![QQ图片20231201123955](https://github.com/hyperledger/besu/assets/94784449/10623102-c4b8-4eaf-b184-453b68e37866)
![007](https://github.com/hyperledger/besu/assets/94784449/7e305aa9-724c-4570-b58d-46125c6870d7)
![4018](https://github.com/hyperledger/besu/assets/94784449/b5ea5a8a-c78e-4b4f-a715-79e9bd6d7856)

**Comment by non-fungible-nelson** [comment]
Based on the screenshot you provided, it seems you were able to successfully hit the RPC API. Are you still facing this issue?
