### ISSUE TITLE
vmTraces' don't show the opcode being executed, only the program counter

### ISSUE THREAD

**Issue by CMajeri** [hyperledger/besu#6216]
### Description
As a user, I want to see opcodes in vmtraces so that I can debug my calls when they fail. 

### Acceptance Criteria
Run `trace_call` on a contract call, and see the opcodes in the returned trace.

------------------------------------------------------------------------

Hello, 
When debugging failed contract calls that do not revert with a reason, we often want to turn to traces in order to debug them properly.
In besu, this means using one of the 3 trace types:
- `trace` is useful for tracking failed contract calls
- `stateDiff` is useful but only for stuff that actually changes the state, not so much for reverts/debugging.
- `vmTrace` is great, except it only gives information using program counters

This means we need to use a disassembler, to turn the contract bytecode into opcodes, and then match the pc to that.
In practice, this means I have to use external tools every time I want to look at a trace.

Could it be possible to have, in addition to the program counter, the actual opcode at that offset?
This would help _a lot_.

Thanks.

**Comment by non-fungible-nelson** [comment]
@daniellehrner is there another trace call provided in Besu that would accomplish this ask? 

Additionally, if we accepted this enhancement to the RPC, it would presumably break spec on trace_call with other clients? Maybe we could provide a flag here...

Could you also take a look at `debug_traceTransaction`? https://besu.hyperledger.org/development/public-networks/reference/api#debug_tracetransaction 

Might help with your needs

**Comment by CMajeri** [comment]
That would be perfect yes!

**Comment by CMajeri** [comment]
Thanks that was fast!

@shemnon I know the code is there, I'm just saying the json needs additional processing before it's readable by a human.
Typically this means taking the code, and disassembling it (not decompiling, just getting human readable opcodes from bytes), and mapping them to the PC in the json. This is a lot harder to do when you're on a phone, reading a trace someone pasted on slack for you to read :)

The geth-style (I'm guessing EIP-3155) traces from the `debug_` endpoints are great for that, and I'm happy to see there's one available for simulating transactions!
