### ISSUE TITLE
[Question] How to use Besu as a sidechain to, say a L1/L2 EVM-compatible chain like Ethereum, Polygon PoS

### ISSUE THREAD

**Issue by kabaluyot** [hyperledger/besu#6217]
Planning to create a permissioned network that is a sidechain to a public EVM chain

**Comment by non-fungible-nelson** [comment]
Hi there - I encourage you to reach out on Discord. The project Maintainers likely cannot help you with this in this forum. Folks in the Discord may have examples as well.
