### ISSUE TITLE
throttle disconnects if we are still finding peers

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6219]
in networks with high latency, these types of disconnects are common, even with otherwise "good" peers. If even the best peers are laggy, it doesn't make sense to continually disconnect for these reasons:

For 3 types of infractions, don't actively disconnect if we are still finding peers
* timeout
* useless response
* IO exception (common from DeFramer)

**Comment by macfarla** [comment]
see #6210

**Comment by non-fungible-nelson** [comment]
Status?

**Comment by macfarla** [comment]
closing this - it's being addressed in other ways
