### ISSUE TITLE
[Question] Inquiry on Building Besu Hyperledger Mainnet and Specifications

### ISSUE THREAD

**Issue by avenbreaks** [hyperledger/besu#6220]
### Description
Hello Besu Hyperledger community,
We hope this message finds you well. We have successfully implemented a public testnet using Besu Hyperledger, and we are now eager to transition to building a mainnet for our project. As we embark on this journey, we have some questions and would greatly appreciate your guidance.

**Building Besu Hyperledger Mainnet:**
Could you provide a step-by-step guide or documentation on how to build a blockchain mainnet using Besu Hyperledger?
Are there any best practices or considerations we should keep in mind during the mainnet deployment process?

All About Projects : 
- Website : https://engramnet.io
- Explorer : https://tokioscan-v2.engram.tech
- Beaconscan : https://beaconscan-v2.engram.tech

**Comment by non-fungible-nelson** [comment]
Hi there - I encourage you to reach out on Discord. The project Maintainers likely cannot help you with this in this forum. Folks in the Discord may have examples, suggestions, etc. They may have suggestions on how to harden and prep a public network. 

I would encourage you to read the [private network docs](https://besu.hyperledger.org/development/private-networks) for your consensus type.
