### ISSUE TITLE
High memory usage during snapsync

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#6223]
### Description
During a checkpoint sync of mainnet my node experienced high memory usage and a high amount of GC.

heap dump:
<img width="1395" alt="Screenshot 2023-12-01 at 2 13 30 pm" src="https://github.com/hyperledger/besu/assets/909467/aae614d1-bbe5-4363-88ab-39fb9eecc8fc">

java memory:
<img width="1249" alt="Screenshot 2023-12-01 at 2 21 00 pm" src="https://github.com/hyperledger/besu/assets/909467/856a382e-91ad-4148-be03-212811c80d64">

I did a heap dump and there are 366,736 `StorageRangeDataRequest` objects in the `InMemoryTaskQueue` retaining 1.68GB.  I think there were more previously but I wasn't able to capture a heap dump when there was a high amount of GC occurring.

### Acceptance Criteria
* Able to sync without high GC or high heap usage

### Steps to Reproduce (Bug)
Checkpoint sync on mainnet. I don't know the exact steps I have only seen this occur once. Likely due to specific network conditions.

### Versions (Add all that apply)
* Besu version 23.10.3-dev-3765aaf3

**Comment by ahamlat** [comment]
@matkt Could you take a look, why we would have 366,736 pendingLargeStorageRequests stuck in the pipeline ?
I think we should limit these pending requests with an eviction mecanism, like FIFO.

<img width="1064" alt="image" src="https://github.com/hyperledger/besu/assets/5099602/48d2b1b8-a29a-43f9-a39f-d90ec8a99fa4">

**Comment by non-fungible-nelson** [comment]
Status on this one?

**Comment by non-fungible-nelson** [comment]
One more time @jframe - should we keep this ticket open for the sync workstream? Still a p2?

**Comment by matkt** [comment]
Is it something we can reproduce?
