### ISSUE TITLE
Is it possible to connect a BESU node to a running Quorum IBFT network?

### ISSUE THREAD

**Issue by PLucianP** [hyperledger/besu#6229]
I have a running network with Quorum IBFT consensus. 
I managed to migrate from IBFT to QBFT.

The way that I tried to connect the BESU is by:
- installing with helm the genesis charts (made sure that the properties are the same as quorum). 
- installing with helm the besu-node charts.
- Add the peers to both BESU and Quorum by connecting them with external IP.

Somehow the Quorum nodes sees the Besu node but I have a mismatch in the genesis block and I'm not sure how to solve this.

Are there other steps to be able to connect Besu to Quorum or am I missing something in my steps?

Thanks!

**Comment by non-fungible-nelson** [comment]
Can you post their genesis config ? for both besu and GoQuorum.

**Comment by PLucianP** [comment]
Absolutely!
quorum-genesis:
`apiVersion: v1
data:
  enode: |
    d260480ca50b2e0b8b0143f965e078c654c9b0a43a6d77094eadc046f989cb9aa103a157c3fde5b5962012b8bab26e9db27aa1cc9599fae57306fe3844594433
  genesis-geth.json: |-
    {
      "alloc": {
        "0x2d596d82940018c32393e9b5166b3e97de1e137a": {
            "balance": "1000000000000000000000000000"
        }
      },
      "coinbase": "0x0000000000000000000000000000000000000000",
      "config": {
        "homesteadBlock": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "eip150Block": 0,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 0,
        "eip158Block": 0,
        "maxCodeSizeConfig": [
          {
            "block": 0,
            "size": 32
          }
        ],
        "chainId": 10,
        "isQuorum": true,
        "istanbul": {
          "epoch": 30000,
          "policy": 0
        },
        "transitions":[{
          "algorithm": "qbft",
          "block": 520,
          "blockperiodseconds": 2,
          "emptyblockperiodseconds": 60,
          "requesttimeoutseconds": 4,
          "epochlength": 30000,
          "validatorselectionmode": "blockheader"
        }]
      },
      "difficulty": "0x1",
      "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000d8d59497ff20cdcdd5dfba3b8c3f7b7dbfa69d9aa77f0380c0",
      "gasLimit": "0xE0000000",
      "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
      "nonce": "0x0",
      "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "timestamp": "0x00"
    }
  istanbul-validator-config.toml: |-
    vanity = "0x00"
    validators = [
      "0x97ff20CdcDD5dFba3B8c3f7b7DBFa69D9aA77f03"
    ]
  nodekey.pub: |
    0x97ff20CdcDD5dFba3B8c3f7b7DBFa69D9aA77f03
  permissioned-nodes.json: |
    [
      "enode://d260480ca50b2e0b8b0143f965e078c654c9b0a43a6d77094eadc046f989cb9aa103a157c3fde5b5962012b8bab26e9db27aa1cc9599fae57306fe3844594433@quorum-p2p:30303?discport=0"
    ]
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: qn-0
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-05T07:24:10Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    name: quorum-settings
  name: quorum-settings
  namespace: default
  resourceVersion: "10161"
  uid: c61c3e89-f6b8-430b-b9de-c89d31749b50
`

besu-genesis:
`apiVersion: v1
data:
  genesis.json: |-
    {
      "nonce": "0x0",
      "timestamp": "0x58ee40ba",
      "extraData": "0xf83aa00000000000000000000000000000000000000000000000000000000000000000d59485e2dfa8e8d3ea01d715739245ebd99e1fea695ec080c0",
      "gasLimit": "0xE0000000",
      "gasUsed": "0x0",
      "number": "0x0",
      "difficulty": "0x1",
      "coinbase": "0x0000000000000000000000000000000000000000",
      "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
      "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "config": {
        "chainId": 10,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "muirglacierblock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "zeroBaseFee": true,
        "qbft": {
          "blockperiodseconds": 2,
          "epochlength": 30000,
          "requesttimeoutseconds": 4
        }
      },
      "alloc": {
        "0x2d596d82940018c32393e9b5166b3e97de1e137a": {
          "balance": "1000000000000000000000000000"
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-05T08:08:12Z"
  name: besu-genesis
  namespace: default
  resourceVersion: "19587"
  uid: 6b6d4f72-d50b-47a1-8185-1565d6888e34
`

**Comment by jframe** [comment]
@PLucianP From your config there are some differences which could be causing this
- The timestamp in quorum has a value of `0x00` and Besu has a value of `0x58ee40ba`
- You have Besu using the London fork at genesis and quorum using the Istanbul fork at genesis

Hopefully, after changing besu values to match quorum config the genesis block mismatch error will be resolved

**Comment by NickSneo** [comment]
@PLucianP Hey, the error you are facing is due to mismatching `extraData` value.
In Besu the value is - 
```
"extraData": "0xf83aa00000000000000000000000000000000000000000000000000000000000000000d5940f166ab0a0cbd2a77d2bc83c2cf98d1dc7a1bc03c080c0"
```

While in Quorum the value is - 
```
"extraData": "0x0000000000000000000000000000000000000000000000000000000000000000d8d5948166cc298c2ef87031c585b1f01549c63ea717ba80c0"
```

Since it is a QBFT network, the extraData value must be same in both genesis. For more info check this - https://besu.hyperledger.org/23.10.2/private-networks/how-to/configure/consensus/qbft#extra-data
