### ISSUE TITLE
Accidental downgrade followed by re-upgrade leaves node broken

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu#6266]
### Description
If Besu is accidentally downgraded to a lower version, the node's data can be corrupted in such as way that when the node is restarted at the correct version the node isn't usable. E.g.

- Start node at `v23.10.2`
- Stop node
- Start node with `v23.4.1`
- Node doesn't work
- Stop node
- Start node with `v23.10.2` again
- Node doesn't work any more

### Acceptance Criteria
When starting Besu at a version lower than the highest version that has been used with that node's data, Besu should fail on startup with a clear error message, rather than attempt to start and correct the data.

**Comment by non-fungible-nelson** [comment]
Hi Matt - let us know if you have any ideas here. Specifically we changed the DB format in [23.4.4](https://github.com/hyperledger/besu/releases/tag/23.4.4) and provided downgrade commands in the release notes. A change to recognize "older versions" would really only be compatible from the version its released with onward.

**Comment by matthew1001** [comment]
Yeah I think my idea for a resolution to this was to detect a downgrade and prevent startup without an extra CLI arg being set. I thought I'd have a go at a draft PR along those lines and see what others think.

**Comment by fab-10** [comment]
could you share the logs of every step? 
the automated db upgrade, should not left the db in an inconsistent state, and using the sub command as described here should make the db working again.

**Comment by non-fungible-nelson** [comment]
@matthew1001 pinging here

**Comment by matthew1001** [comment]
Sorry, didn't see @fab-10 's comment. I did post an updated in the PR a few days ago though (https://github.com/hyperledger/besu/pull/6307#issuecomment-1875125648) which would be good to get peoples' views on.

I don't have logs retained for the scenario where we hit it, but it was a fairly simple QBFT setup as outlined in the description. The chain had been mining blocks at 23.10.2 perfectly fine, then after restarting with version 23.4.1 installed the chain wouldn't mine blocks at all.

I suspect the DB revert command would have worked, but I think it would be useful to have the option to prevent a lower version of Besu from starting given that the likelihood of needing to upgrade/downgrade isn't very common and having to set an option to allow it isn't particularly onerous.
