### ISSUE TITLE
Receipt encoding 

### ISSUE THREAD

**Issue by gfukushima** [hyperledger/besu#6271]
Prototype receipt encoding, similar to what other ELs approach.

Some references & implementations:
ethereum/go-ethereum#19345
NethermindEth/nethermind#5531

**Comment by jframe** [comment]
Besu already stores the minimal amount of fields necessary. The changes for Geth and Nethermind were to not store fields that can derived but don't store those fields. E.g. Geth was storing the transaction hash, gas cost, and contract address.

In Besu we are only storing state root | status, cumulative gas, bloom filter and logs and optionally the revert reason. This is also what Geth is storing with the changes that were made.

**Comment by jframe** [comment]
Closing this as we already storing the bare minimum fields except the bloom filter. We have another ticket to investigate not storing the bloom filters in the receipts storage #6277
