### ISSUE TITLE
Do not store bloom filter and generating that on demand

### ISSUE THREAD

**Issue by gfukushima** [hyperledger/besu#6272]
Investigate the possibility of not storing bloom filter and generating that on demand.

try understand what the results were for the attempt on this PR: https://github.com/hyperledger/besu/pull/5392 - not great results but @matkt didn't spend much time on it. maybe rocksdb is already compressing all the leading zeros?

**Comment by jframe** [comment]
Tested with and without this change on mainnet and saw ~50 GB improvement in disk space. So I think this approach is worth doing. 

<img width="1248" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzN5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef1ce639acf3a333d2366ee4a0a24b7672e95e8b/Screenshot%202024-01-24%20at%208.59.12%E2%80%AFam.png" alt="Screenshot 2024-01-24 at 8.59.12 am.png" />

**Comment by jframe** [comment]
With receipts changes:
| Column Family                  | Keys            | Column Size  | SST Files Size  |
|--------------------------------|-----------------|--------------|-----------------|
| BLOCKCHAIN                     | 1409631207      | 603 GiB      | 100 GiB         |
| VARIABLES                      | 3014            | 4 KiB        | 36 KiB          |
| CODE_STORAGE                   | 37580056        | 11 GiB       | 12 GiB          |
| TRIE_BRANCH_STORAGE            | 1832339529      | 118 GiB      | 131 GiB         |
| ACCOUNT_INFO_STATE             | 2330085         | 103 MiB      | 109 MiB         |
| ACCOUNT_STORAGE_STORAGE        | 4883367         | 207 MiB      | 215 MiB         |
| TRIE_LOG_STORAGE               | 42339           | 2 GiB        | 2 GiB           |

Control:
| Column Family                  | Keys            | Column Size  | SST Files Size  |
|--------------------------------|-----------------|--------------|-----------------|
| BLOCKCHAIN                     | 1409631272      | 656 GiB      | 100 GiB         |
| VARIABLES                      | 4797            | 4 KiB        | 99 KiB          |
| CODE_STORAGE                   | 37577781        | 11 GiB       | 12 GiB          |
| TRIE_BRANCH_STORAGE            | 1832101439      | 118 GiB      | 131 GiB         |
| ACCOUNT_INFO_STATE             | 2233071         | 104 MiB      | 111 MiB         |
| ACCOUNT_STORAGE_STORAGE        | 4838918         | 218 MiB      | 218 MiB         |
| TRIE_LOG_STORAGE               | 42753           | 2 GiB        | 2 GiB           |
