### ISSUE TITLE
Expose runtime values of minGasPrice and minPriorityFee as metrics

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#6291]
With #6080 and #6097, is now possible to change the values of the `--min-gas-price` and `--min-priority-fee` options at runtime, for this is convenient to expose the runtime values of both options as metrics so they can be tracked and monitored

**Comment by Brindrajsinh-Chauhan** [comment]
@fab-10 Would be happy to work on this if this not something you are actively working on

**Comment by fab-10** [comment]
Hi @Brindrajsinh-Chauhan, I am not working on it at the moment, so feel free to work on it.

**Comment by Brindrajsinh-Chauhan** [comment]
@fab-10 Opened a PR (mentioned above) for the same, would be grateful to get your reviews/feedback on it.

Thank you

**Comment by matthew1001** [comment]
It sounds like this can be closed as PR https://github.com/hyperledger/besu/pull/6587 has now merged.
