### ISSUE TITLE
Transaction has been reverted by the EVM (when trying to deploy a smart contract)

### ISSUE THREAD

**Issue by jeremyGrelaud** [hyperledger/besu#6304]
### Description
Hi, I am trying to deploy a smart contract in my private besu network (IBFT 2.0) but the transaction to do so is being reverted by the EVM. I was succesfully able  to deploy the same smart contract with remix and then interract with it as described in the besu documentation with a js script.

### Acceptance Criteria
* Smart contract being deployed successfully.

### Steps to Reproduce (Bug)
1. Deploy a Besu network following the [documentation](https://besu.hyperledger.org/private-networks/tutorials/ibft) 
2. Create a SimpleStorage.sol smart contract using the following 

```
pragma solidity ^0.7.0;

contract SimpleStorage {
  uint public storedData;
  event stored(address _to, uint _amount);

  constructor(uint initVal) public {
    emit stored(msg.sender, initVal);
    storedData = initVal;
  }

  function set(uint x) public {
    emit stored(msg.sender, x);
    storedData = x;
  }

  function get() view public returns (uint retVal) {
    return storedData;
  }
}
```

3. Compile the smart contract with a compile.js file just like the [documentation ](https://besu.hyperledger.org/private-networks/tutorials/contracts) and generating the bin and abi with solc

4. Creating a public_tx.js file 

```
const host = 'http://127.0.0.1:8545'; // URL of the node
const fs = require('fs');
const path = require('path');
const Tx = require('ethereumjs-tx').Transaction;

const { Web3 } = require('web3');

async function deployContract() {
  //instance Web3
  const web3 = new Web3(host);
  const privateKey = "secret...";
  const account = web3.eth.accounts.privateKeyToAccount(privateKey);

  const contractJsonPath = path.resolve(__dirname, "SimpleStorage.json");
  const contractJson = JSON.parse(fs.readFileSync(contractJsonPath));

  const contractAbi = contractJson.abi;
  const contractBinPath = path.resolve(__dirname, "SimpleStorage.bin");
  const contractBin = fs.readFileSync(contractBinPath);

  const contractConstructorInit =
    "000000000000000000000000000000000000000000000000000000000000002F";

  const txnCount = await web3.eth.getTransactionCount(account.address);

  const rawTxOptions = {
    nonce: web3.utils.numberToHex(txnCount),
    from: account.address,
    to: null,
    value: "0x00",
    data: "0x" + contractBin + contractConstructorInit,
    gasPrice: "0x0",
    gasLimit: "0x24A22",
  };

  console.log("Creating transaction...");
  const tx = new Tx(rawTxOptions);
  console.log("Signing transaction...");
  tx.sign(Buffer.from(privateKey.slice(2), 'hex'));
  console.log("Sending transaction...");
  const serializedTx = tx.serialize();

  const pTx = await web3.eth.sendSignedTransaction(
    "0x" + serializedTx.toString("hex").toString("hex")
  );

  console.log("tx transactionHash: " + pTx.transactionHash);
  console.log("tx contractAddress: " + pTx.contractAddress);
}

//calling main
deployContract()
  .then(() => {
    console.log("Contrat sucesfully deployed");
  })
  .catch((error) => {
    console.error("Error during contract's deployment :", error);
  });
```

**Expected behavior:** The smart contract to be deployed successfully when running the public_tx.js file

**Actual behavior:** 
```
Creating transaction...
Signing transaction...
Sending transaction...
Erreur lors du déploiement du contrat : TransactionRevertInstructionError: Transaction has been reverted by the EVM
    at /home/.../smartcontracts/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:48:21
    at Generator.next (<anonymous>)
    at /home/.../smartcontracts/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:24:71
    at new Promise (<anonymous>)
    at __awaiter (/home/.../smartcontracts/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:20:12)
    at getTransactionError (/home/.../smartcontracts/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:33:12)
    at SendTxHelper.<anonymous> (/home/.../smartcontracts/node_modules/web3-eth/lib/commonjs/utils/send_tx_helper.js:74:84)
    at Generator.next (<anonymous>)
    at fulfilled (/home/.../smartcontracts/node_modules/web3-eth/lib/commonjs/utils/send_tx_helper.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: undefined,
  reason: 'Internal error',
  signature: undefined,
  receipt: undefined,
  data: undefined,
  code: 402
}
```

II tried to change the gas and log every data in the script and it seems correctly initialized. So I don't know if it's an error of logic in the public_tx.js or a problem of configuration of my besu network. (or something else)

**Frequency:** Always

### Versions
* Software version: besu/v23.10.2/linux-x86_64/openjdk-java-17
* Java version: openjdk version "17.0.6" 2023-01-17 / OpenJDK Runtime Environment (build 17.0.6+10-Debian-1) / OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1, mixed mode, sharing) 
* Consensus : IBFT 2.0 POA consensus

### Smart contract information 
* Solidity version solcjs --version :  0.8.23+commit.f704f362.Emscripten.clang

**Comment by non-fungible-nelson** [comment]
Hi there - in your custom genesis, have you specified milestone blocks that are up to date for the op-codes you're using in the smart contract? 

There is some detail here: https://besu.hyperledger.org/public-networks/reference/genesis-items#milestone-blocks

If you are attempting to use an older milestone (i.e. before a certain fork), the EVM will revert the tx if it encounters a newer piece of functionality in the smart contract.

**Comment by jeremyGrelaud** [comment]
Indeed I used "BerlinBlock" and I see that the latest EVM version seems to be Shangai. Is it possible to directly change this configuration in the genesis file  or do we need to make some kind of transition ?

**Comment by tasty007** [comment]
> 事实上，我使用了“BerlinBlock”，我看到最新的 EVM 版本似乎是 Shangai。是否可以直接在创世文件中更改此配置，或者我们需要进行某种过渡？
> 
> 我明天会尝试，看看问题是否与不兼容的 EVM 版本有关。
> 
> 编辑：我尝试在我的智能合约中指定正确的编译器版本，并使用 solc 命令的 evm-version 选项来生成 abi、bin 和 json 文件，但我最终得到了同样的错误（我的事务被 EVM 恢复了）。 ![image](https://private-user-images.githubusercontent.com/73029242/291539350-2f97b0d9-a068-4cf6-9ca2-5910f1e67a04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTc0OTcsIm5iZiI6MTcyMDA1NzE5NywicGF0aCI6Ii83MzAyOTI0Mi8yOTE1MzkzNTAtMmY5N2IwZDktYTA2OC00Y2Y2LTljYTItNTkxMGYxZTY3YTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAxMzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxODcwYmQxNTk1OTU0NmMxMThjNjMxNTE0MDViY2Q1YTdmOTIyNGQ1ZWFkYzQyNWMxMTExZjgyNDNkNmRlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IpS_G4y91WqqzFH2tvkHKTfeETq2vg9PYfDCPub5vjc)
> 
> 通过遵循本教程 （https://github.com/lacchain/besu-pro-testnet/blob/master/DEPLOY_APPLICATIONS.md#web3），我能够在我的私有区块链上部署合约，就像我使用 remix 和 metamask 所做的那样。我只是添加以调整我的交易的 gas 量。我想知道在问题的情况下，问题是否是由 gas 还是编译器版本引起的......

**Comment by tasty007** [comment]
> Indeed I used "BerlinBlock" and I see that the latest EVM version seems to be Shangai. Is it possible to directly change this configuration in the genesis file or do we need to make some kind of transition ?
> 
> I'll try tomorrow to see if the problem was linked to an incompatible EVM version.
> 
> Edit : I tried specifying the right compiler version in my smart contract and using the evm-version option of the solc command to generate the abi, bin and json files but I end up getting the same error (my transaction reverted by the EVM). ![image](https://private-user-images.githubusercontent.com/73029242/291539350-2f97b0d9-a068-4cf6-9ca2-5910f1e67a04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTgzMzcsIm5iZiI6MTcyMDA1ODAzNywicGF0aCI6Ii83MzAyOTI0Mi8yOTE1MzkzNTAtMmY5N2IwZDktYTA2OC00Y2Y2LTljYTItNTkxMGYxZTY3YTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAxNTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTEyNDJmNzgwNzQ0ODUyMDczMGFhZWQ3NTBmZWIzZGFjZjE4NDAyMGFjOGViOTNmMThhMDFhNmVhODE4ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6hGZKqRynylNZ-kmf9eTe9YJ8O3EvhyoEnyhRcHqoWM)
> 
> By Following this tutorial (https://github.com/lacchain/besu-pro-testnet/blob/master/DEPLOY_APPLICATIONS.md#web3) I was able to deploy a contract on my private blockchain just like I did with remix and metamask. I just add to adjust the amount of gas for my transaction. I wonder If the problem in the case of the issue is due to gas or compiler version ...

Hello, I also encountered the same problem, looking at the EVM source code, found that the virtual machine has executed the operation code REVERT and returned...
Now I don't know how to deal with it, can you help me?

**Comment by fangfu-kou** [comment]
Reducing the webjs version can solve the problem.   npm install web3@1.8.1
