### ISSUE TITLE
Besu Prague Tracker

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6308]
[EIP-7600: Hardfork Meta - Pectra](https://eips.ethereum.org/EIPS/eip-7600)

[Prague Meta Thread](https://ethereum-magicians.org/t/prague-electra-network-upgrade-meta-thread/16809/26)

[Prague Hyperledger Wiki Thread](https://wiki.hyperledger.org/display/BESU/Prague+Planning)

## EIP List for pectra-devnet-1
https://notes.ethereum.org/@ethpandaops/pectra-devnet-1

| EIP Number | EIP Link | Additional Links | Status |
|------------|----------|------------------|--------|
| EIP-2537   | [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) | [GitHub PRs](https://github.com/hyperledger/besu/pulls?q=is%3Apr+EIP-2537+is%3Aclosed) | Implemented |
| EIP-2935   | [EIP-2935](https://eips.ethereum.org/EIPS/eip-2935) | [#7080](https://github.com/hyperledger/besu/pull/7080) | Implemented |
| EIP-6110   | [EIP-6110](https://eips.ethereum.org/EIPS/eip-6110) | [GitHub PRs](https://github.com/hyperledger/besu/pulls?q=is%3Apr+6110+is%3Aclosed) | Implemented  |
| EIP-7002   | [EIP-7002](https://eips.ethereum.org/EIPS/eip-7002) | [GitHub PRs](https://github.com/hyperledger/besu/pulls?q=is%3Apr+EIP-7002+is%3Aclosed) | Implemented |
| EIP-7685   | [EIP-7685](https://eips.ethereum.org/EIPS/eip-7685) | [#6986](https://github.com/hyperledger/besu/issues/6986) | Implemented |
| EIP-7702   | [EIP-7702](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7702.md) | [#7237](https://github.com/hyperledger/besu/pull/7237/) | In Progress
| EIP-7251   | [EIP-7251](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7251.md) | [#7266](https://github.com/hyperledger/besu/pull/7266/) | Implemented

**Comment by siladu** [comment]
Potentially 6110 update https://github.com/ethereum/EIPs/pull/8440

**Comment by shemnon** [comment]
EIP-2537 needs to go back to in progress, it doesn't pass all of the tests in https://github.com/ethereum/tests/pull/1366 - it may be a bit of a moving target

**Comment by winsvega** [comment]
the tests are filled with geth Prague. which is basically cancun + 2537 at this point

**Comment by jflo** [comment]
closing as prague work is small enough to track in single issues
