### ISSUE TITLE
Remove experimental flag from SNAP and CHECKPOINT

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6311]
SnapSync is ready for prime-time. We are also preparing to ship snap server, the final piece of the puzzle. 

This ticket tracks some final cleanup for UX and simplicity as we move Snap to non-experimental and the default for the client over time. 

- Since SNAP is an extension of FAST in the codebase, the log entries for a SNAP sync node all show as FAST sync e.g. "main | INFO  | FastSyncDownloader | Starting sync". It's not ideal when looking through logs that the class names logged out can mislead you as to which sync mode is being used. We should tidy this up. #6386
- SNAP sync and --fast-sync-min-peers. In a PoW or PoA network this flag applies to SNAP and CHECKPOINT sync. A synonym should be added as part of moving it out of experimental, with --fast-sync-min-peers  deprecated for removal in a future version. We could use --sync-min-peers and update the docs to reflect this flag only impacts _non-PoS_ networks in Besu. #6327

**Comment by matthew1001** [comment]
Currently the logs say `main | INFO  | FastSyncDownloader | Starting sync` when a node is configured with `SNAP` sync. I realise that's down to Java classes/extensions, but it can be misleading when looking at logs. If any tidy up can be done to log from the `SnapSyncDownloader` class instead that would be a nice but of tidy up.

**Comment by matthew1001** [comment]
Is `--fast-sync-min-peers` supported for `SNAP` sync? If so, it might be good to deprecate/rename it. If it isn't supported, I think the consistent behaviour would be to fail startup in the way it does with `FULL` sync today.

**Comment by matthew1001** [comment]
Another consideration if moving `X_SNAP` out of experimental is whether PoA nodes should fail to start or give a warning that they are falling back to `FAST` sync, since `SNAP` is not supported with PoA chains currently. Today if you try to use `X_SNAP` with e.g. `QBFT` the node looks like it's going to start but never actually works.

**Comment by macfarla** [comment]
created #6385 for SNAP / QBFT

**Comment by macfarla** [comment]
created #6386 for the SyncDownloader logging change

**Comment by macfarla** [comment]
@non-fungible-nelson questions 
* are we planning on making this a breaking change (if I start besu with sync-mode=X_SNAP it will fail?) or do we want to support both for a while?
* what do you mean by "full flat DB"

**Comment by non-fungible-nelson** [comment]
> @non-fungible-nelson questions
> 
> * are we planning on making this a breaking change (if I start besu with sync-mode=X_SNAP it will fail?) or do we want to support both for a while?
I think for a while we should alias X_SNAP and X_CHECKPOINT to avoid breaking user configs. We can signal the X will go away in 24.4.0 and users will need to update config. 
> * what do you mean by "full flat DB"
`--Xsnapsync-synchronizer-flat-db-healing-enabled=true` by default. Details in #6157

**Comment by garyschulte** [comment]
We can mark it deprecated for a while so that it does not break the setup of early adopters

**Comment by macfarla** [comment]
ok that makes sense - #6157 is assigned to you @garyschulte , but are you working on it or do you want to throw it over to me?
