### ISSUE TITLE
Does besu support /eth/v1/config/spec api?

### ISSUE THREAD

**Issue by meijiesky** [hyperledger/besu#6334]
### Description
Ethereum supports the following apis:
https://ethereum.github.io/beacon-APIs/#/Config/getSpec

And I want to call  /eth/v1/config/spec as follows.
```
curl -X 'GET' \
  'http://127.0.0.1:8545/eth/v1/config/spec' \
  -H 'accept: application/json'
```

### Steps to Reproduce (Bug)
* run curl command above

**Expected behavior:**
* return the config on chain

**Actual behavior:**
* the response is `<html><body><h1>Resource not found</h1></body></html>%`

### Logs (if a bug)
```
2023-12-29 16:05:20.602+08:00 | vert.x-eventloop-thread-1 | DEBUG | JsonRpcHttpService | Opened connection from 127.0.0.1:51734. Total of active connections: 1/80
2023-12-29 16:05:20.602+08:00 | vert.x-eventloop-thread-1 | DEBUG | B3PropagatorExtractorMultipleHeaders | Invalid TraceId in B3 header: null'. Returning INVALID span context.
2023-12-29 16:05:20.604+08:00 | vert.x-eventloop-thread-1 | DEBUG | JsonRpcHttpService | Connection closed from 127.0.0.1:51734. Total of active connections: 0/80
```

### Versions (Add all that apply)
* Software version: besu commit be5cc68b6069ca2f718d08c95994e1a764576391
* Java version: 17.0.9
* OS Name & Version: macOS x86 14.1
* Kernel Version: Darwin B-Q1EKMD6R-0128.local 23.1.0 Darwin Kernel Version 23.1.0
* Docker Version: 24.0.7
* Consensus Client & Version if using Proof of Stake: No, just a local private network with one besu client

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version 0.8.23+commit.f704f362.Darwin.appleclang

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - config.toml
```
# 节点数据存储路径
data-path="/Users/mjsky/CLionProjects/anole-besu/tmp/besudata"

# Network
#bootnodes=["enode://001@123:4567", "enode://002@123:4567", "enode://003@123:4567"]
bootnodes=["enode://011f758e6552d105183b1761c5e2dea0111bc20fd5f6422bc7f91e0fabbec9a6595caf6239b37feb773dddd3f87240d99d859431891e4a642cf2a0a9e6cbb98a@127.0.0.1:30303"]

#p2p-host="1.2.3.4"
#p2p-port=1234
#max-peers=42

# JSON-RPC 配置
rpc-http-host="0.0.0.0"
rpc-http-port=8545
# WebSocket 配置
rpc-ws-host="0.0.0.0"
rpc-ws-port=9101

rpc-http-api=["ETH","DEBUG","MINER","NET","PERM","WEB3","ADMIN","EEA","PRIV","TXPOOL","TRACE","PLUGINS","CLIQUE","IBFT","ENGINE","QBFT"]

rpc-http-cors-origins=["all"]
host-allowlist=["*"]
rpc-ws-enabled=true
rpc-http-enabled=true

# Chain
genesis-file="/Users/mjsky/CLionProjects/anole-besu/genesis.json"

# Mining
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

#tx-pool-limit-by-account-percentage=1
#min-gas-price=0

# 日志级别
logging="DEBUG"
```

**Comment by mbaxter** [comment]
Hi @meijiesky - besu is an execution client and the API's you're looking for are only served by consensus clients.  See [the docs here](https://besu.hyperledger.org/public-networks/concepts/the-merge#execution-clients) for an explanation.

You can find documentation on besu's API's [here](https://besu.hyperledger.org/public-networks/reference/api).
