### ISSUE TITLE
Link to "Documentation's Logging section" in the README.md is broken

### ISSUE THREAD

**Issue by yerayrodriguez** [hyperledger/besu#6342]
### Description
Link to "Documentation's Logging section" in the [README.md](https://github.com/hyperledger/besu/blob/main/README.md) is broken. 
The link goes to https://besu.hyperledger.org/en/stable/HowTo/Monitor/Logging/ and I think it should goes to https://besu.hyperledger.org/public-networks/how-to/monitor/logging.

### Acceptance Criteria
Link works and shows correct info.

### Steps to Reproduce (Bug)
1. Go to https://github.com/hyperledger/besu
2. Click on [Documentation's Logging section](https://besu.hyperledger.org/en/stable/HowTo/Monitor/Logging/)

**Expected behavior:** 
Link works and shows correct info.

**Actual behavior:**
Page not found

**Comment by macfarla** [comment]
thanks for the report @yerayrodriguez
