### ISSUE TITLE
Snap sync - filter peers

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6349]
During syncing, we specifically need peers that support snap (responding to snap requests, not just advertising the capability) - currently we could have a full complement of peers without necessarily getting any that serve snap data

and only request snap data from those peers that will serve snap data

**Comment by gfukushima** [comment]
Not sure how exactly it works but it might be worth looking into the snap DNS address.
E.g [snap.mainnet.ethdisco.net](https://github.com/ethereum/discv4-dns-lists/tree/master/snap.mainnet.ethdisco.net)
