### ISSUE TITLE
Block Period below 1 Second using *BFT Consensus 

### ISSUE THREAD

**Issue by CryftCreator** [hyperledger/besu#6399]
### Description
As a blockchain developer, I want the ability to configure **block periods of less than one second** in Hyperledger Besu. This capability is critical for meeting commercial speed expectations in real-world applications, especially for **efficiently processing private transactions** and their accompanying privacy marker transactions. Utilizing the **Bonsai data storage format** can contribute significantly to space savings and efficiency enhancements necessary for such speeds.

### Acceptance Criteria
- Enable configuration for block periods less than one second in Besu.
- Ensure network stability and optimal performance with shorter block periods.
- Efficiently manage private transactions, completing them in under a second.

### Rationale
- **Commercial Speed Expectations:** Rapid transaction processing is a necessity in many enterprise applications. Sub-second block periods would make blockchain solutions more viable for these use cases.
- **Efficiency in Private Transactions:** Quick completion of private transactions enhances user experience and operational efficiency in business contexts.
- **Bonsai for Space Efficiency:** Utilizing Bonsai data storage could provide the necessary space efficiency and performance for supporting such rapid block times.
- **Broader Market Adoption:** Faster transactions are a competitive feature, encouraging wider adoption of blockchain technology in sectors where speed is crucial.
- **Advancing Blockchain Technology:** This feature could position Besu at the forefront of high-performance blockchain platforms.

### Potential Challenges
- **Maintaining Network Stability:** It's essential to address how sub-second block periods might affect the overall stability and security of the network.
- **Bonsai Data Storage Integration:** Ensure that Bonsai's space-efficient storage capabilities are fully compatible with rapid block times.

### Versions
- Software version: [`besu --version`]
- Java version: [`java -version`]
- OS Name & Version: [`cat /etc/*release`]
- Consensus Client & Version if using Proof of Stake: [e.g. Teku]

### Additional Information
- **Besu Setup Info:** Exploring configurations to support sub-second block periods, specifically with Bonsai data storage.
- **Efficiency Enhancements:** Details on any proposed efficiency enhancements that can support these faster transaction times.
- **Case Studies:** Relevant benchmarks or studies demonstrating the impact of faster transaction times on blockchain networks, with a focus on private, enterprise scenarios.

**Comment by daniellehrner** [comment]
One problem I can think of is that the block header contains the block time as UNIX timestamp, which is expressed in seconds. So this means this would need to be changed to a different format to be able to express sub-second values. Further this timestamp is exposed in the EVM, e.g. in Solidity via `blocks.timestamp`, which might require a custom / forked version of Solidity.

It might be possible to keep the timestamp as integer and have a format similar to UNIX time stamp, but in milliseconds. This might not break the EVM, but would require custom tooling to interpret the timestamp correctly. Further existing smart contracts which require the timestamp would need to be adapted to take this into consideration.

**Comment by garyschulte** [comment]
This is more than a configuration issue as it affects block structure, block validation, and consensus, not just block production timing.  If you want to take a stab at making block time resolution below one second, do feel free to reopen and submit a (series of) PR(s) .
