### ISSUE TITLE
document the user profiles

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6409]
create at least draft documentation for the new profiles, how to use them and how to override defaults etc.

**Comment by Gabriel-Trintinalia** [comment]
# User Documentation

## Introduction to --profile CLI Option in Besu

Besu introduces a new feature, the `--profile` CLI option. This feature allows users to load existing TOML configuration files from resources, thereby enabling the override of default options. 

### How to Use the --profile CLI Option

To use the `--profile` CLI option, you need to specify it when running Besu, along with the name of the profile you want to use. For example:

```bash
besu --config-file=config.toml --profile=STAKER
```

In this case, `config.toml` is the user-provided configuration file, and `STAKER` is the pre-configured profile containing custom settings.

### Configuration Resolution

The configuration provider resolves settings in a cascading manner. It prioritizes settings in the following order:

1. Environment variables
2. Configuration file (specified by the `--config-file` option)
3. Profile file (specified by the `--profile` option)
4. Default values (used if no other configuration source is available)

For instance, if a setting is not found in the environment variables, Besu will look for it in the `config.toml` file. If the setting is not found in the `config.toml` file, Besu will then look for it in the `STAKER.toml` file. If the setting is not found in the `STAKER.toml` file, Besu will use the default value for that setting.

### Available Profiles

The `--profile` flag accepts the following profiles:

- `minimalist-staker`
- `staker`
- `privat` and `enterprise` (both alias to the same profile)

Any configuration options explicitly set in the config file or command line will overwrite any of the defaults set via the profile.

## Minimalist Staker Profile

For stakers who want to maximize their hardware value but don't want to serve full sets of data to their peers, Besu offers a `minimalist_staker` profile. This profile implements the following defaults:

- Sync mode: `CHECKPOINT`
- Data-storage-format: `BONSAI`
- bonsai-historical-block-limit: `128`
- Max-peers: `25`

To use the `minimalist_staker` profile, run Besu with the `--profile` option set to `minimalist_staker`:

```bash
besu --profile=minimalist_staker
```

Please note that any configuration options explicitly set in the config file or command line will overwrite the defaults set via the `minimalist_staker` profile.

## Enterprise/Private Profile

For private network operators who want to minimize unexpected confusion by setting sensible defaults, Besu offers an `enterprise` or `private` profile. This profile is designed to handle specific use-cases for private network operators.

To use the `enterprise` or `private` profile, run Besu with the `--profile` option set to `enterprise` or `private`:

```bash
besu --profile=enterprise
```
or
```bash
besu --profile=private
```

The `enterprise` or `private` profile implements the following defaults:

- Sync-mode: `FAST`
- `-sync-min-peers=1`
- `--remote-connections-limit-enabled=false`
- Tx-pool: `Legacy / Sequential`
- `--tx-pool-no-local-priority`
- `--tx-pool-limit-by-account-percentage` (set to a value larger than 4 transactions)

Please note that any configuration options explicitly set in the config file or command line will overwrite the defaults set via the `enterprise` or `private` profile.

**Comment by Gabriel-Trintinalia** [comment]
@non-fungible-nelson draft doco for the `profile` feature

**Comment by non-fungible-nelson** [comment]
nitpick
> Besu will use the default value for that setting.

let's make this Besu will use the universal default value for that setting.

We are also missing the staker profile (maybe it can be a note at the end of the minimalist staker , or vice versa)

**Comment by macfarla** [comment]
closing this ticket now that there's a besu-docs ticket specifically for this.
