### ISSUE TITLE
RocksDB upgrade introduce issues when used with Forest

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#6421]
RocksDB has been upgraded from 8.3.2 to 8.9.1 in #6377, but was found by @siladu that it can prevent a Forest node to start, since it gets stuck (indefinitely?) at the initial compaction step, a specific node was stopped after being stuck there for 45min, and a restart didn't help
```
16T22:54:50,765","level":"INFO","thread":"main","class":"RocksDBKeyValueStorageFactory","message":"Existing database detected at /data/besu. Version 1. Compacting database...","throwable":""}
```
Reverting RocksDB to 8.3.2 (#6419) solves the issue, so further investigation is need to identify the source of the issue.

**Comment by siladu** [comment]
>  it gets stuck (indefinitely?) at the initial compaction step

I believe it was stuck indefinitely because I waited at least 45mins and compaction was very fast as soon as I reverted

**Comment by non-fungible-nelson** [comment]
ok to close?
