### ISSUE TITLE
Publish `develop` version to artifactory

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#6426]
We do this already for docker tags. This is a useful version for nightly canaries to target so that we don't have to update them every besu release.

**Comment by jflo** [comment]
I assume you are referring to the distributions, not all produced jars?

**Comment by siladu** [comment]
Think we can unblock this now @jflo @non-fungible-nelson ?

**Comment by jflo** [comment]
Yes, just need more details on what we want here. Sounds like every night we cut a tarball/zip archive from main (if changed) and make sure it lives at a static URL for use? I assume you're not married to `artifactory` specifically, and just need these publicly available.

**Comment by macfarla** [comment]
not married to artifactory!

**Comment by macfarla** [comment]
@jflo looks like the develop tag isn't being updated. I downloaded besu-develop.tar.gz from [there](https://github.com/hyperledger/besu/releases/tag/develop) and it gives besu-24.3-develop-c564fcd919 as the version... which is this commit from an hr ago - so I think the release binaries are updated (built off the merge to main commit) but not the source code that is attached to the develop release, nor the develop tag itself.

**Comment by jflo** [comment]
I will research how to either remove the source attachment, or have it updated.   I'm not sure about the develop tag though, that would just be a synonym for the head of main, so is it worth using?
