### ISSUE TITLE
Error message when output directory already exists isn't clear

### ISSUE THREAD

**Issue by blockchain-trainer** [hyperledger/besu#643]
https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

indicates that it does.

IBFT-Network/
├── Node-1
│   ├── data
├── Node-2
│   ├── data
├── Node-3
│   ├── data
└── Node-4
    ├── data

Copy the following configuration file definition to a file called ibftConfigFile.json and save it in the IBFT-Network directory:

**Comment by MadelineMurray** [comment]
@blockchain-trainer - I've transferred this over to the `besu` repository to reflect it's a code change rather than a docs change.  
 
I think Grant's suggestion of `Output directory already exists` would make it clearer what the issue is in this case.

**Comment by blockchain-trainer** [comment]
submitted [PR](https://github.com/hyperledger/besu/pull/652)
