### ISSUE TITLE
Retrieve Key from Ethereum Patricia Tree

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [hyperledger/besu#6450]
I want to retrieve and stream all the keys of the Ethereum Patricia tree but I can't find any viable way can you help me? is this possible?

**Comment by siladu** [comment]
Hi @PanagiotisDrakatos I believe this question was answered on the Hyperledger Discord: https://discord.com/channels/905194001349627914/938504958909747250/1199375217139654766. 

Please reopen if I am mistaken :)

**Comment by PanagiotisDrakatos** [comment]
@siladu that's correct i forgot to delete it this question was answered on the Hyperledger Discord
