### ISSUE TITLE
Make sure that Backward Sync does not run when Snap Sync is happening

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#6464]
### Description
It does not make sense to run two different syncs (e.g. snap and backward sync)
We found an issue in 24.1.1 RC1, where we receive a engine_forkChoiceUpdate containing a head block hash that get's reorged. This happened during initial sync, which means that we have not imported this block when we received the engine_newPayload containing that block hash. Eventually we would trigger 
backwardSyncContext .syncBackwardsUntil(headHash) (in MergeCoordinator). 
[PR #6455](https://github.com/hyperledger/besu/pull/6455/) fixes this for the initial sync, but there might be other cases where we want to make sure that backward sync is not running, or where we have to kill running backward syncs, e.g. when we are starting a snap sync for some other reason than intial sync.

### Acceptance Criteria
* Make sure that only one kind of sync can run at a time

**Comment by non-fungible-nelson** [comment]
implemented via #6545
