### ISSUE TITLE
Investigate EIP-2046

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#649]
**Update** on [AllCoreDevs #89](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2089.md), it was mentioned that test vectors have been created for the EIP. We should make sure that Besu can run the test vectors. See this part of the transcript for more details: https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2089.md#2-call-to-discuss-precompile-repricing-eip-2046-reduced-gas-cost-for-static-calls-made-to-precompiles--eip-2666-repricing-of-precompiles-and-keccak256-function

--- 

On the [AllCoreDevs call #84](https://github.com/ethereum/pm/issues/162) it was discussed that clients should run benchmarks on EIP-2046 to make sure the gas cost changes work on all clients. We should investigate this and report back on the ACD call as well as the relevant [EthMagicians thread](https://ethereum-magicians.org/t/eip-2046-reduced-gas-cost-for-static-calls-made-to-precompiles/3291).

**Comment by sambacha** [comment]
is this all clients and consensus mechanisms (i.e clique as well) or just mining?

**Comment by timbeiko** [comment]
It would change the gas cost across all consensus mechansims, but what we are more interested in here is the block execution time, which is independent of the consensus mechanism.
