### ISSUE TITLE
Problem syncing (withdrawals) in besu 24.1.1 with QBFT y shanghai

### ISSUE THREAD

**Issue by danielherrero** [hyperledger/besu#6507]
Hi
We are trying to move from paris to shaghai milestone
In our first tests we are creating a new fresh network with docker-desktop (same problem with openshift 4x) using besu 24.1.1 with 3 members and 4 validators
I have attached the genesis file, and this is the main configuration
`"config": {
        "chainId": 1337,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "constantinopleFixBlock": 0,
        "istanbulBlock": 0,
        "muirGlacierBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "arrowGlacierBlock": 0,
        "grayGlacierBlock": 0,
        "parisBlock": 0,
        "shanghaiTime": 0,
        "zeroBaseFee": true,
        "qbft": {
          "blockperiodseconds": 2,
          "epochlength": 30000,
          "requesttimeoutseconds": 4
        }
      },
      "nonce": "0x0",
      "timestamp": "0x65ba2eda",
      "gasLimit": "0xf7b760",
      "difficulty": "0x1",
      "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
      "coinbase": "0x0000000000000000000000000000000000000000",`
[besu-genesis-configmap.txt](https://github.com/hyperledger/besu/files/14112253/besu-genesis-configmap.txt)

In every node it happens the same error when starting (attached complete startup log):
`2024-01-31 13:26:33.582+00:00 | BftProcessorExecutor-QBFT-0 | WARN  | WithdrawalsValidator$AllowedWithdrawals | withdrawals must not be null when Withdrawals are activated
2024-01-31 13:26:33.583+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | MainnetBlockValidator | Invalid block 1 (0x1e9bf2ea049d3632d5d1b4edf27d7586b53a6578af60e329bb27b4891096d709)
2024-01-31 13:26:33.584+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalPayloadValidator | Invalid Proposal Payload: block did not pass validation. Reason Optional[failed to validate output of imported block]    
2024-01-31 13:26:33.584+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: invalid proposal payload in proposal message`

Is there any kind of problem between QBFT and shaghai milestone?

[log.txt](https://github.com/hyperledger/besu/files/14112267/log.txt)

![image](https://github.com/hyperledger/besu/assets/1422690/0ff91a0f-b609-45bd-b100-60bd98ecc7fb)
![image](https://github.com/hyperledger/besu/assets/1422690/efb99028-a9ac-4e55-a6de-081896e4a7f2)

Thanks in advance

**Comment by matthew1001** [comment]
QBFT and Shanghai cannot be used until https://github.com/hyperledger/besu/pull/6353/ is merged. Closing as a dup of https://github.com/hyperledger/besu/issues/5446
