### ISSUE TITLE
A node with misconfigured  min-gas-price will silently drop remote transactions

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu#653]
# Description
As a node operator, I want to log/report when remote transactions are dropped so that I can quickly identify misconfiguration issues. 

### Acceptance Criteria
* Besu logs/metrics contain notification of dropped transactions due to too low gas price.

### Steps to Reproduce
1. Add a validating node to an existing zero-gas network with min-gas price not set to zero
2. Submit transactions to a node with min-gas-price set to zero
3. Check for empty blocks and/or the validating nodes transaction pool (will be empty)

**Expected behavior:** [What you expect to happen]

Node should log that remote transactions are being dropped

**Actual behavior:** [What actually happens]

Node silently drops remote transactions with gasPrice < nodes minimum gas price.

**Frequency:** [What percentage of the time does it occur?]

All the time in a zero gas network.

### Versions (Add all that apply)
* Software version:  1.4.x, 1.3.x

### Additional Information

This is especially critical for validating nodes, as this results in empty blocks causing network throughput to fall and transactions to take longer to process.

This issue is obvious when submitting transactions directly to a node as the JSON-RPC interface will return an error.

Documentation on min-gas-price needs to explicitly call this out especially for a zero gas network.

**Comment by rain-on** [comment]
Hi @magooster,
It's worth considering the following when approaching this issue:

1. In an Ethereum network, transactions are dropped regularly, each miner effectively has its own set of rules for transaction selection (Besu is quite simple, and selects anything above a threshold (min-gas-price)). Usually, the rules are such that "cheap" transactions don't get mined.

2. In the situation above, the 0-gas-price transaction is only being ignored by one of the validators, and thus will be mined in the next block (which would be proposed by a different validator).

3. While we talk about "zero gas networks" - the reality is, each node is completely independent of the others, there is no overarching controller. So having each validator with a different min-gas-price is a legal configuration.

**Comment by MadelineMurray** [comment]
Moving this to a docs issue so we can make this expected behaviour clearer.

**Comment by MadelineMurray** [comment]
Issue moved to [hyperledger/besu-docs #322](https://github.com/hyperledger/besu-docs/issues/322) via [**ZenHub**](https://www.zenhub.com/)
