### ISSUE TITLE
Besu Testing Improvements

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6538]
As Besu is adopted by more and more institutions and users, we owe it to them to complete a more and more robust testing process. Besu has highly detailed tests, but may have some gaps in its testing process. This epic outlines a gap analysis and creation of next steps around our testing in the Besu codebase. 

Some brainstorming is being started [here](https://wiki.hyperledger.org/display/BESU/Testing+Taskforce+Brainstorming).

### Acceptance Criteria 
- Brainstorm is completed and testing gaps are identified.
- An Epic/workstream is created with actionable item based on the findings from the brainstorm

### Suggestions 
- Review of existing test coverage that takes into account problem spots like sync, Bonsai.
- Review of process to incorporate Hive into release pipeline 
- Review of code coverage...
- ???

**Comment by macfarla** [comment]
this issue represents the effort to identify testing gaps, which has been done and separate issues have been created to capture those tasks. look for `testing` label
