### ISSUE TITLE
Add metric some transactions' metrics in preparation of a performance work

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#6544]
Before we start some performance work, it might be helpful to gather more data. This can help us decide if it's worth starting the project. I suggest we add these measurements:

- How many transactions are in each imported block

- How much gas is used by each imported block

- What percentage of transactions in the imported block are "remote confirmed". We can figure this out the existing metrics and the ones above.

- What percentage of the total gas used in the imported block is from "remote confirmed" transactions. We can also figure this out from the above metrics.

**Comment by jflo** [comment]
@ahamlat and @fab-10 this seems stale, please reopen if this still needs to be implemented.
