### ISSUE TITLE
Remaining Hive Cancun Failures

### ISSUE THREAD

**Issue by spencer-tb** [hyperledger/besu#6554]
## Description

I'm tagging the last 3 failures here for the hive cancun tests.
(note: on [hivecancun](https://hivecancun.ethdevops.io/suite.html?suiteid=1707445951-a0c29c2634925b0c36a58544287836c5.json&suitename=engine-cancun) all other failures pass locally and are due to something internal to the CI).

Specifically from the `engine-cancun` simulator.
```
ForkchoiceUpdatedV3 To Request Shanghai Payload, Null Beacon Root
ForkchoiceUpdatedV2 To Request Shanghai Payload, Non-Null Beacon Root
ForkchoiceUpdatedV2 To Request Cancun Payload, Non-Null Beacon Root
```
These can all be explained from the execution apis spec update in https://github.com/ethereum/execution-apis/pull/498.
We are essentially sending an fcu with invalid payload attributes and hence expect an error reponse of `INVALID_PAYLOAD_ATTRIBUTES`. Besu is returning `INVALID_PARAMS`. Should be a simple parameter fix.

#### Steps to reproduce

Using the latest version of [hive](https://github.com/ethereum/hive/tree/master) run the following command:
```
./hive --sim ethereum/engine --client besu --client-file configs/cancun.yaml --docker.output --sim.limit engine-cancun/"<test_name>"
```

**Comment by macfarla** [comment]
@jflo are you on this one already?

**Comment by macfarla** [comment]
thanks @spencer-tb - all should be passing in the next run!
