### ISSUE TITLE
default for bonsai-limit-trie-logs-enabled=True

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6560]
change default (currently false) for

bonsai-limit-trie-logs-enabled=True

**Comment by macfarla** [comment]
this change breaks the minimalist-staker profile with the message  --bonsai-historical-block-limit minimum value is 512
minimalist-staker profile has it set to 128
check is done [here](https://github.com/hyperledger/besu/blob/61c7e18ab446a7383bafc2e10d96a88595cf1986/besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java#L113)
with trie-log-limit enabled = false (previous default), it doesn't do that check

can we lower the minimum value from 512 to 128 cc @non-fungible-nelson

**Comment by macfarla** [comment]
actually went the other way in the PR - changed minimalist-staker limit from 128 to 512

**Comment by macfarla** [comment]
(won't be a breaking change if we want to go the other way in the future)

**Comment by macfarla** [comment]
nope, changed again. minimum = 128 and default = 512

**Comment by non-fungible-nelson** [comment]
@siladu - any comments here? I know we had some interesting behaviors with minimums and defaults. What we would like to do is support a global default of 512, but a local default of 128 for the minimal staker profile.

**Comment by siladu** [comment]
> @siladu - any comments here? I know we had some interesting behaviors with minimums and defaults. What we would like to do is support a global default of 512, but a local default of 128 for the minimal staker profile.

Discussed this with @macfarla.
I'm wondering what is the benefit of reducing from 512 -> 128? 
In terms of storing trie logs, there's only about 60MB difference between 512 vs 128 so not worth the extra logic IMO.
