### ISSUE TITLE
change ATs to use Bonsai since this is now the default storage mode

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6583]
See comments on https://github.com/hyperledger/besu/pull/6536

Change ProcessBesuNodeRunner and ThreadBesuNodeRunner to use DEFAULT_BONSAI_CONFIG

**Comment by siladu** [comment]
See https://github.com/hyperledger/besu/pull/6048

**Comment by macfarla** [comment]
reopened since this change was reverted due to some AT flakiness

**Comment by macfarla** [comment]
the AT flakiness seems to have resolved itself... fishy. but I cannot make it happen again 
- original PR which shows failure https://github.com/hyperledger/besu/pull/6619
- second PR which shows when it was failing https://github.com/hyperledger/besu/pull/6729 and is now passing (I thought maybe the last change was making it pass)
- redux PR which has the same code (with and without that last change) and doesn't fail https://github.com/hyperledger/besu/pull/6770

**Comment by macfarla** [comment]
Node Runners now use the config passed in - since #7495 
however most ATs still use FOREST so that still needs to be addressed
