### ISSUE TITLE
"purpose": "Create WalletAccount" - "type": "MethodUnavailable". We use our own API and deploy the contracts. Method error

### ISSUE THREAD

**Issue by Afonsodalvi** [hyperledger/besu#6586]
I used EVM Paris and deployed the contracts correctly, and I can read them through the same API. However, when interacting, the following error appears:

![error](https://github.com/hyperledger/besu/assets/66927949/04ea264b-437e-4b5d-88ce-6edb31956b14)

I've already deployed the same contracts to other EVM chains and it worked. Only Besu is still giving me this error. We use w3.py and I believe this is not the problem.

**Comment by Afonsodalvi** [comment]
Hi @macfarla Thank you for your answer!
We are using eth_sendRawTransaction. 

We are debugging and it returned this error: 

![image](https://github.com/hyperledger/besu/assets/66927949/8814f06c-b5f5-4df4-956e-2c9e5655f42d)

**Comment by macfarla** [comment]
The Invalid TraceId warning can be ignored as per https://github.com/hyperledger/besu/issues/6440 (there's also a workaround there to silence that specific log warning)

**Comment by non-fungible-nelson** [comment]
Can this issue be closed with the ignore / suggestion above?

**Comment by macfarla** [comment]
@ Afonsodalvi did you find out where the "Method not found" is coming from?

**Comment by jframe** [comment]
Closing this, if you are still having an issue feel free to reopen with more details
