### ISSUE TITLE
How to deploy a smartcontract on Besu - Rinkeby with truffle

### ISSUE THREAD

**Issue by Louvivien** [hyperledger/besu#659]
Hello, 

I try to deploy a smartcontract on Besu, I can deploy on a private Besu with docker and truffle and now I try to deploy my contract on Besu with Rinkeby. 

I start the network with this script and it works fine :
`"besu": "sudo docker run -p 30303:30303 --mount type=bind,source=/tmp/besu/rinkeby,target=/var/lib/besu hyperledger/besu:latest --network=rinkeby --data-path=/var/lib/besu"`

I can't find in the documentation how to migrate my smartcontract to this network.
I try :
`truffle migrate --reset --compile-all --network besu` but i get an error message. 

This is my truffle config with the private key provided in the documentation :

```
const PrivateKeyProvider = require("@truffle/hdwallet-provider");
const privateKeys = [
  "0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63"
];

const privateKeyProvider = new PrivateKeyProvider(
  privateKeys,
  "http://localhost:8545",
  0,
  3
);

module.exports = {
  networks: {
    besu: {
      provider: privateKeyProvider,
      network_id: "*"
    }
  }
};
```

Do I need to change something in the truffle config file ?

Thank you for your work

**Comment by Louvivien** [comment]
ok i found out part of the solution :

- I changed the script to include both ports : 
`sudo docker run -p 8545:8545 -p 30303:30303 --mount type=bind,source=/tmp/besu/rinkeby,target=/var/lib/besu hyperledger/besu:latest --rpc-http-enabled --rpc-http-cors-origins='all' --host-whitelist='*' --network=rinkeby --data-path=/var/lib/besu`
- and I have changed the privateKey for the privateKey of an account with Rinkeby faucets

but now it fails for insufficient funds :  
`Error:  *** Deployment Failed ***

"Migrations" could not deploy due to insufficient funds
   * Account:  0x20cEE93C127d8F35F54f56e0d28D14219Fe23919
   * Balance:  0 wei
   * Message:  sender doesn't have enough funds to send tx. The upfront cost is: 372936000000000 and the sender's account only has: 0
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.`
<img width="293" alt="Screen Shot 2020-04-06 at 19 04 40" src="https://user-images.githubusercontent.com/43605778/78585062-818a1280-7839-11ea-881f-ca3e69c1e55a.png">

What can I do ? 

Thank you

**Comment by timbeiko** [comment]
Hey @Louvivien, 

Based on this:
>On the terminal where i have started besu I see that very often, I don't know if it is important :
`No peers available, wait for peer.`

I assume your Besu node hasn't fully synced up to Rinkeby yet. Is that the case? 

One quick way to find out is to look at the logs of your Besu node and see if you have logs showing the latest blocks being imported, such as:

```
2020-04-07 08:48:35.548-04:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 3000
2020-04-07 08:48:36.702-04:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 3200
2020-04-07 08:48:37.539-04:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 3400
2020-04-07 08:48:38.113-04:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 3600
2020-04-07 08:48:38.610-04:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 3800
2020-04-07 08:48:39.537-04:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 4000
```

For Rinkeby, you'll need to sync ~6.2 million blocks. You can use [fast sync](https://besu.hyperledger.org/en/latest/Concepts/Pruning/#fast-synchronization) to do this quicker, and if you are looking for any testnet, [Goerli](https://besu.hyperledger.org/en/latest/HowTo/Get-Started/Starting-node/#run-a-node-on-goerli-testnet) is quicker to sync than Rinkeby (it can usually fast sync in ~1h). 

Let me know if that helps!

**Comment by Louvivien** [comment]
Hi, 

Thank you for you reply. 
I have updated my starting script to include the fast sync option. After one hour this is what I get :  
<img width="742" alt="Screen Shot 2020-04-07 at 19 04 36" src="https://user-images.githubusercontent.com/43605778/78792808-e36d8800-79b1-11ea-8dfc-e0dcdf7c356f.png">

and at the end after more than one hour this is what I have : 
<img width="647" alt="Screen Shot 2020-04-07 at 15 54 12" src="https://user-images.githubusercontent.com/43605778/78792881-00a25680-79b2-11ea-860b-9befd22b1954.png">

I don't see "FullImportBlockStep | Import reached block"

when I try `truffle migrate --reset --compile-all --network besu` but i still get the same error message

**Comment by timbeiko** [comment]
Thanks for the update! It seems that what happens is that your fast sync started well (as per your first screenshot), but then you lost the peers you were syncing from (possibly just because they went offline, or they didn't have the state you needed). Once it finds peers again it will start importing blocks again, and once it is ~1000 blocks from the head of the chain it will switch from `FastImportBlockStep` to `FullImportBlockStep`.

**Comment by timbeiko** [comment]
@Louvivien I'll close this issue for now, but please re-open if you encounter any other problems. 

Cheers!
