### ISSUE TITLE
Investigate Blobdb with garbage collection

### ISSUE THREAD

**Issue by usmansaleem** [hyperledger/besu#6601]
Investigate Blobdb with garbage collection ... the garbage collection may be increasing over time. With garbage collection enabled, the garbage should be collected/move during compaction. 

- [ ] Check with RC on mainnet.

@siladu 
@fab-10 
@usmansaleem

**Comment by siladu** [comment]
Enabled on these nodes including mainnet so can monitor these... https://github.com/search?q=repo%3AConsensys%2Fprotocols-azure-inventories+bonsai-limit-trie-logs-enabled%3Dtrue&type=code

**Comment by Wetitpig** [comment]
> Enabled on these nodes including mainnet so can monitor these... https://github.com/search?q=repo%3AConsensys%2Fprotocols-azure-inventories+bonsai-limit-trie-logs-enabled%3Dtrue&type=code

Sorry, but the repository does not exist anymore and this link does not work.
Could anyone post the results of this test or a link to monitor these nodes if they are still running?
