### ISSUE TITLE
remove deprecated sync modes X_SNAP and X_CHECKPOINT

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6612]
First we need to get some external docs updated 

eg somer's guide

https://someresat.medium.com/guide-to-staking-on-ethereum-ubuntu-lighthouse-773f5d982e03

These sync modes are deprecated as of 24.2.0

**Comment by non-fungible-nelson** [comment]
@macfarla

**Comment by macfarla** [comment]
looks like somer's guide is updated - this would be a good first issue!
