### ISSUE TITLE
Startup info contains git sha, is aggregatable 

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#6637]
### Description
As a user, I want to know what source commit my build is running from, so that I can be aware of differences with finer granularity than what is provided by build numbers.  I also want this reported in such a way that it is available to any logging aggregation I may be doing, so I can search on it.

### Acceptance Criteria
git sha from build is accurate and available on startup. can be easily searched in any log aggregation tool.

**Comment by macfarla** [comment]
@jflo can we call this done?

**Comment by jflo** [comment]
No, the searchability in log aggregation tools isn't done yet.

**Comment by jflo** [comment]
Looks like the version of Besu isn't coming up in Loki since it is output in a multi-line format with a json appender, but promtail, the process that consumes it doesn't know to expect multi-line values in the json.  

I think we can mark this as complete, and open a new issue to make our log4j/promtail settings a bit more robust and useful.
