### ISSUE TITLE
[build] - Extract errorprone-checks as a separate library

### ISSUE THREAD

**Issue by usmansaleem** [hyperledger/besu#6690]
### Description
Besu code defines custom errorprone checks which is utilized by it's build file. Because the errorprone checks are hosted in the same repo, it adds complex build logic to maintain it. Extracting it out as a separate library will allow it to be easily applied and maintained and will reduce build definition complexity as well.

### Acceptance Criteria
* The errorprone-checks is extracted out in its own repo
* It is included as an external dependency
* It should catch the related code issues during compilation.

**Comment by macfarla** [comment]
completed

**Comment by usmansaleem** [comment]
Fixed via https://github.com/hyperledger/besu/pull/6692
