### ISSUE TITLE
RPC call parameters do not accept input and data field simultaneously

### ISSUE THREAD

**Issue by friedemannf** [hyperledger/besu#6697]
Hi!

https://github.com/hyperledger/besu/pull/6094 introduced the option to provide the calldata via the `input` field instead of the deprecated `data` field. To remain compatible with chains that have not yet implemented the updated spec, the Chainlink node will set both fields, which is working fine with all other chains so far but fails on Besu due to the strict check in the aforementioned PR:
```
    if (input != null && data != null) {
      throw new IllegalArgumentException("Only one of 'input' or 'data' should be provided");
    }
```

Is there a specific resons why this check is this strict, or could it be relaxed to the following:
```
    if (input != null && data != null && !input.equals(data)) {
      throw new IllegalArgumentException("Only one of 'input' or 'data' should be provided");
    }
```

**Comment by macfarla** [comment]
that seems reasonable @friedemannf - would you like to do a PR to make this change?

**Comment by friedemannf** [comment]
@macfarla thank you! Created a PR here: https://github.com/hyperledger/besu/pull/6702
