### ISSUE TITLE
Bump LTS Java Distribution to Java 21 & Update Docker Distributions 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6722]
### Description
As an Besu operator, I want Java 21 included in the images/binaries and supported in Besu, so I can take advantage of performance gains in the new version. 

Java 22 has reached GA, meaning we can signal support for a version bump to LTS 21 in Besu. 

### Acceptance Criteria
- [x] Besu docs page on "How to update Java" is created - @non-fungible-nelson to complete
    - https://github.com/hyperledger/besu-docs/pull/1539
- [x] Docker build updated to reduce number of images we produce, including 21 and GraalVM 
    - #6703
- [x] Besu is tested against Java 21 and minimum version in testing bumped
- [x] Gradle updated
- [x] Web3j dependency bump (minimum April 15th)
- [x] Upgrade jacoco version
- [x] Build system is updated to include Java 21 images @jflo

**Comment by non-fungible-nelson** [comment]
Reference #6703

**Comment by non-fungible-nelson** [comment]
[Teku targeting jdk 21 in latest update](https://github.com/Consensys/teku/releases/tag/24.3.0)

**Comment by non-fungible-nelson** [comment]
Does this fix the Gradle build errors on Java 21?

**Comment by shemnon** [comment]
No, this appears to just be docker, and running with Java 21, which has never really been an issue.

To build with Java 21 we need
* Newer version of Gradle
* New gradle plugin versions from Web3j (to ship next week)
* Upgrade to the jacoco version 
* Upgrade spotless to a newer version (already applied to `main` branch)
 
With these changes I was able to get a local `./gradlew build` to complete.

**Comment by non-fungible-nelson** [comment]
Thanks @shemnon - I'll open another ticket
