### ISSUE TITLE
Is it possible to deploy any Besu Network on a free tier EC2 AWS server ?

### ISSUE THREAD

**Issue by Louvivien** [hyperledger/besu#674]
Hello, 

Thank you for your work. 
I want to test a dApp and I have tried to deploy a Besu network on a free tier Ubuntu EC2 AWS server with Docker, it went well until I wanted to run `truffle migrate --reset --compile-all --network besu` 
Then I got an error message because I think it consumed too much memory. 

Do you know if it is possible to run any kind of Besu network on a free tier EC2 instance ? 

Thank you,

**Comment by timbeiko** [comment]
Hey @louvivien, 

You can see the minimum suggested requirements for a Besu network here: https://besu.hyperledger.org/en/latest/HowTo/Get-Started/System-Requirements/

If you are trying to run a named network (i.e. Mainnet, Ropsten, etc.) you will need 8GB of RAM for the JVM. I'm not sure if that is within the scope of the AWS free tier. Note that if you want to test on a smaller instance, you will be good to run a Besu private network using 4GB of RAM. 

I'll close this for now, but please re-open if you have any additional questions!
