### ISSUE TITLE
卡在这里几个小时了是什么原因已更新到最新版本

### ISSUE THREAD

**Issue by a5868519** [hyperledger/besu#6743]
![1710514534484](https://github.com/hyperledger/besu/assets/121847804/06260a25-9de1-4a9a-9d9d-850af84015b7)

**Comment by jframe** [comment]
Closing this as the issue was resolved on Discord. User upgraded to the latest version of Besu to fix the issue.

**Comment by macfarla** [comment]
fix was to update the CL (was not dencun ready)
