### ISSUE TITLE
bug(devp2p): unsolicited type 3 transactions broadcast

### ISSUE THREAD

**Issue by merklefruit** [hyperledger/besu#6777]
## Context

At @chainbound, we run a fleet of custom nodes that participate in the Ethereum p2p networks.
The software we use is not part of Besu. Our devp2p network implementation is based off Reth's.

## Issue

Since after the Dencun fork, we have noticed an unexpected behaviour from Besu peers on all of our nodes.
It looks like we are getting some type 3 transaction messages unsolicited from devp2p. The specific ETH wire message type is [`Transactions` (0x02)](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transactions-0x02) which according to [EIP-4844 specs](https://eips.ethereum.org/EIPS/eip-4844#networking) should not contain type 3 transactions:

> Nodes MUST NOT automatically broadcast blob transactions to their peers. Instead, those transactions are only announced using NewPooledTransactionHashes messages, and can then be manually requested via GetPooledTransactions.

From a first analysis, it looks like Besu has a check to enforce the correct behaviour in the transaction broadcaster here:

https://github.com/hyperledger/besu/blob/42b32d253142a599f9633e7332a8fe715094ab33/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionBroadcaster.java#L41

I am probably missing something as I'm not familiar with the Besu codebase, but happy to help debug this however I can!

**Comment by macfarla** [comment]
hey @merklefruit thanks a bunch for reporting this issue, it was a subtle one to track down actually and the fix will be in the next release! Let us know if you find anything else :)

**Comment by merklefruit** [comment]
Awesome, really happy to hear this has been useful. Have a great weekend :)
