### ISSUE TITLE
Migrate CheckSpdxHeader to spotlessApply

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#6785]
We currently have a groovy script inside a unique `buildSrc` gradle project. It fails the build if you miss the spdxHeader in any source file via the `checkSpdxHeader` gradle task

https://github.com/hyperledger/besu/blob/main/buildSrc/src/main/groovy/CheckSpdxHeader.groovy

We would like to remove this as it's an odd part of the gradle build and adds some groovy dependencies that make normal Java tasks harder (such as auto-building using java 17 even if you're running java 21).

Most devs have manually setup an IDE copyright profile when new files are created.

It would be better to make spotlessApply fix these issues then noone has to think about it in the future :)

**Comment by usmansaleem** [comment]
PRs list:
- https://github.com/hyperledger/besu/pull/7015
- https://github.com/hyperledger/besu/pull/7016
- https://github.com/hyperledger/besu/pull/7017
- https://github.com/hyperledger/besu/pull/7018
- https://github.com/hyperledger/besu/pull/7019
- https://github.com/hyperledger/besu/pull/7020
- https://github.com/hyperledger/besu/pull/7021
