### ISSUE TITLE
How do I build Besu from source on Mac? Instructions not working out the box

### ISSUE THREAD

**Issue by fwoodruff** [hyperledger/besu#6827]
### Description
As an aside I notice that the 'Have you done the following' default text in this box, links to https://besu.hyperledger.org/en/stable/HowTo/Monitor/Logging/ which 404s at time of writing.

I am trying to run Besu from source. I need to do this on Mac and Linux. I am getting similar errors on both, but I will describe the Mac workflow and errors for completeness.

### Acceptance Criteria
* I need to build Besu from source and run a node.
* I then need to run a private appchain, with mining and an RPC (context, out of scope for this question)

### Steps to Reproduce (Bug)
* Installed Gradle via: https://download.oracle.com/java/21/latest/jdk-21_macos-aarch64_bin.dmg
```
brew install libsodium nss java gradle
git clone --recursive https://github.com/hyperledger/besu
cd besu
./gradlew tasks --stacktrace
```

**Expected behavior:**

I expect this to show me a list of commands I can make, as documented here:
https://wiki.hyperledger.org/display/BESU/Building+from+source .

**Actual behavior:**
I get an error with Gradle, which I describe in the logs below.
I also tried with --no-daemon which didn't work either.

**Frequency:** [What percentage of the time does it occur?]
60% of the time it happens 100% of the time.

### Logs (if a bug)
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file '/Users/frederickwoodruff/besu/settings.gradle' (/Users/frederickwoodruff/.gradle/caches/7.6/scripts/3wmasx3mgaenci0me4kp1qvep).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.cache.CacheOpenException: Could not open cp_settings generic class cache for settings file '/Users/frederickwoodruff/besu/settings.gradle' (/Users/frederickwoodruff/.gradle/caches/7.6/scripts/3wmasx3mgaenci0me4kp1qvep).
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:91)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:43)
        at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:103)
        at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:68)
        at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.open(DefaultCacheRepository.java:117)
        at org.gradle.groovy.scripts.internal.FileCacheBackedScriptClassCompiler.compile(FileCacheBackedScriptClassCompiler.java:117)
```

### Versions (Add all that apply)
* Software version: [`besu --version`]
```
zsh: command not found: besu
```
* Java version: [`java -version`]
```
java version "22" 2024-03-19
Java(TM) SE Runtime Environment (build 22+36-2370)
Java HotSpot(TM) 64-Bit Server VM (build 22+36-2370, mixed mode, sharing)
```
Note I also have Java 21 installed on my machine.

* OS Name & Version: [`cat /etc/*release`]
```
MacOS Sonoma 14.2 (23C64)
```
* Kernel Version: [`uname -a`]
```
Darwin 192.168.1.104 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
```
* Virtual Machine software & version: [`vmware -v`]
N/A
* Docker Version: [`docker version`]
```
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.2 (124339)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

* Cloud VM, type, size: [Amazon Web Services I3-large]
Not using a VM (although I have tried the same on an Azure Debian machine with fairly similar results)

* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]
N/A

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
```
solc, the solidity compiler commandline interface
Version: 0.8.25+commit.b61c2a91.Darwin.appleclang
```
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
None yet, but I will later use the following besu.conf
```
rpc-http-enabled=true
rpc-http-host=127.0.0.1
rpc-http-port=8545
rpc-http-api=ETH,NET,WEB3,MINER
rpc-http-cors-origins=all

miner-enabled=true
miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73
```
* System info - memory, CPU
270.89GB available

**Comment by non-fungible-nelson** [comment]
Hi there - can you try again with Java 17 as your Java version? This error:
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66
points to a gardle versioning issue. We will support Java 21+ soon. 

If this does not work let me know. I may update that wiki page to mention only version 17.

**Comment by fwoodruff** [comment]
Java 17 worked. For reproducibility, I needed Gradle version 8.7, which involves a slightly manual installation on Linux:

```
wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
unzip gradle-8.7-bin.zip
```

I then appended `~/.bashrc` with
```
export PATH=/path/to/gradle-8.7/bin:$PATH
```
and then ran
```
source ~/.bashrc
```

**Comment by macfarla** [comment]
wiki page has been updated, instructions should work now https://wiki.hyperledger.org/display/BESU/Building+from+source .
