### ISSUE TITLE
How do I build Besu from source? I need to write a Dockerfile which achieves this.

### ISSUE THREAD

**Issue by fwoodruff** [hyperledger/besu#6839]
### Description

My goal is to create a Dockerfile that builds Besu from source and then runs Besu, initially with no command line arguments.

Docker happens to provide excellent reproducibility, and allows me to ask my question about building Besu from source in highly concrete terms.

### Acceptance Criteria
Build Besu from source inside a Docker container and run Besu.

### Steps to Reproduce (Bug)

Run `docker build -t besu . && docker run besu` on the following Dockerfile:
```
FROM openjdk:17-jdk-slim
ENV PATH="${PATH}:/opt/gradle-8.7/bin"
RUN apt-get update
RUN apt-get install -y wget unzip git
RUN wget https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle.zip
RUN unzip gradle.zip -d /opt
RUN rm gradle.zip
RUN git clone --recursive https://github.com/hyperledger/besu.git
WORKDIR /besu
RUN ./gradlew build
WORKDIR /besu/build/install/besu/bin
CMD ["besu"]
```

**Expected behavior:** [What you expect to happen]
I expect this to install and run Besu

**Actual behavior:** [What actually happens]
`./gradlew build` fails on the `ethereum:p2p:test` test, while building the image.

**Frequency:** [What percentage of the time does it occur?]
60% of the time, this happens 100% of the time

### Logs (if a bug)

```
3132.4 
3132.4 > Task :ethereum:p2p:compileTestJava
3132.4 Note: Some input files use or override a deprecated API.
3132.4 Note: Recompile with -Xlint:deprecation for details.
3132.5 
3132.5 > Task :ethereum:p2p:processTestResources
3132.5 > Task :ethereum:p2p:testClasses
3136.6 
3136.6 > Task :ethereum:p2p:test
3136.6 OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
3136.9 OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
3148.9 
3148.9 EnodeURLImplTest > toURI_WithHostnameShouldWorkWhenDnsEnabledAndUpdateEnabled() FAILED
3148.9     org.opentest4j.AssertionFailedError at EnodeURLImplTest.java:516
3150.1 
3150.1 TLSContextFactoryTest > testConnectionHardwareKeys(String, boolean, KeyStoreWrapper, KeyStoreWrapper, Optional, Optional) > org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.TLSContextFactoryTest.initializationError FAILED
3150.1     org.hyperledger.besu.pki.PkiException at TLSContextFactoryTest.java:229
3150.1         Caused by: org.hyperledger.besu.pki.PkiException at TLSContextFactoryTest.java:226
3150.1             Caused by: java.security.ProviderException at TLSContextFactoryTest.java:226
3150.1                 Caused by: java.io.IOException at TLSContextFactoryTest.java:226
3156.0 
3156.0 433 tests completed, 2 failed
3156.1 
3156.1 > Task :ethereum:p2p:test FAILED
3156.1 
3156.1 FAILURE: Build failed with an exception.
3156.1 
3156.1 * What went wrong:
3156.1 Execution failed for task ':ethereum:p2p:test'.
3156.1 > There were failing tests. See the report at: file:///besu/ethereum/p2p/build/reports/tests/test/index.html
3156.1 
3156.1 * Try:
3156.1 > Run with --stacktrace option to get the stack trace.
3156.1 > Run with --info or --debug option to get more log output.
3156.1 > Run with --scan to get full insights.
3156.1 
3156.1 * Get more help at https://help.gradle.org
3156.1 
3156.1 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
3156.1 
3156.1 You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
3156.1 
3156.1 See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings
3156.1 
3156.1 BUILD FAILED in 52m 35s
3156.1 590 actionable tasks: 590 executed
------
Dockerfile:10
--------------------
   8 |     RUN git clone --recursive https://github.com/hyperledger/besu.git
   9 |     WORKDIR /besu
  10 | >>> RUN ./gradlew build
  11 |     WORKDIR /besu/build/install/besu/bin
  12 |     CMD ["besu"]
--------------------
ERROR: failed to solve: process "/bin/sh -c ./gradlew build" did not complete successfully: exit code: 1
```

### Versions (Add all that apply)
* Software version: [`besu --version`]
N/A
* Java version: [`java -version`]
N/A or 17
* OS Name & Version: [`cat /etc/*release`]
N/A or Debian
* Kernel Version: [`uname -a`]
N/A
* Virtual Machine software & version: [`vmware -v`]
N/A
* Docker Version: [`docker version`]
```
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:18:01 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:18:01 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
* Cloud VM, type, size: [Amazon Web Services I3-large]
N/A
* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]
N/A

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)

* Solidity version [`solc --version`
N/A
* Repo with minimal set of deployable/reproducible contract code - please provide a link
N/A
* Please include specifics on how you are deploying/calling the contract 
N/A
* Have you reproduced the issue on other eth clients
N/A

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
no config file for now, just the raw Git repo.
* System info - memory, CPU
4 cores, 918G RAM remaining

**Comment by non-fungible-nelson** [comment]
Hi there - if this is just for development (and not to connect to a live network like Mainnet), you can skip the failing tests for now. You may only want to run them while you're developing. You can include the flag `-x test` on the line where you are running Gradle (a flag on the gradle command).

**Comment by non-fungible-nelson** [comment]
Reach out in discord for more support.
