### ISSUE TITLE
Please add sha256 sums for 24.3.1 and signatures?

### ISSUE THREAD

**Issue by dtto** [hyperledger/besu#6855]
### Description
Normally there is an sha256 sum on the releases page. There is no sha256 sum for 24.3.1
Also, it would be really great if you could also do a GPG signed list of sha256 sums.

### Steps to Reproduce (Bug)
1. Go to releases page
2. There is no sha256 sum
3. Be sad

**Expected behavior:** [What you expect to happen]
SHA256 sum should be created automatically, ideally with a gpg signature.

**Actual behavior:** [What actually happens]
No SHA256 sum.

**Frequency:** [What percentage of the time does it occur?]
For 24.3.1, all the time.

### Logs (if a bug)
Please post relevant logs from Besu (and the consensus client, if running proof of stake) from before and after the issue. 

### Versions (Add all that apply)

24.3.1

**Comment by siladu** [comment]
Note, this is a prerelease currently undergoing testing. We don't recommend using it at this stage

**Comment by dtto** [comment]
Ah, that's odd. It showed up as a release earlier but now I see it is a prerelease.
