### ISSUE TITLE
max trailing peers 0 - all syncing peers rejected

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6888]
besu disconnecting other besu's (even if not at max peers) with "useless peer" - I tried using admin_addPeer to add a fully synced besu holesky node as a peer to my syncing holesky node but was rejected. 

max trailing peers 0 rejects all peers that are not in sync - which seems harsh - does this flip over once we are in sync? is there a grace period?

From looking at logs on dev-elc-besu-teku-holesky-dev-sally-up-chain-ht-est-1 it seems like we still have max trailing peers 0 even once we're in sync 

`0x174d38ae9ae10a6b` is my still-syncing besu node that keeps trying to connect

`
{"@timestamp":"2024-04-05T05:27:42,416","level":"DEBUG","thread":"nioEventLoopGroup-3-5","class":"TrailingPeerLimiter","message":"Enforcing trailing peers limit (min height 1282349, max trailing peers 0) by disconnecting 0x174d38ae9ae10a6b...... with height 968066","throwable":""}
`

holesky
besu_sync_mode: CHECKPOINT
besu_data_storage_format: BONSAI

looking at this code in FastSyncDownloader (also used by snap and checkpoint)

  protected FastSyncState updateMaxTrailingPeers(final FastSyncState state) {
    if (state.getPivotBlockNumber().isPresent()) {
      trailingPeerRequirements =
          Optional.of(
              new TrailingPeerRequirements(
                  state.getPivotBlockNumber().getAsLong(), 0));
    } else {
      trailingPeerRequirements = Optional.empty();
    }
    return state;
  }

**Comment by macfarla** [comment]
also - the code in the TrailingPeerLimiter uses chain height estimate which is not strictly kept up to date (since we're not getting gossiped blocks, we only update chain state when we get headers from the peer which we're not doing here)

ie my peer is being rejected with chain height est 968,066 but its real chain height is much higher 1,284,172 - almost in sync!

```
      final EthPeer peerToDisconnect = trailingPeers.remove(0);
      LOG.atDebug()
          .setMessage(
              "Enforcing trailing peers limit (min height {}, max trailing peers {}) by disconnecting {} with height {}")
          .addArgument(minimumHeightToBeUpToDate)
          .addArgument(maxTrailingPeers)
          .addArgument(peerToDisconnect::getLoggableId)
          .addArgument(
              peerToDisconnect.chainState() == null
                  ? "(no chain state)"
                  : peerToDisconnect.chainState().getEstimatedHeight())
          .log();
```

**Comment by Beanow** [comment]
I thought this seemed harsh as well.
Especially a few occurrences where my besu had like 300k blocks and was just starting a sync, but the min height was already `128xxxx`, it dropped peers that were at `min height - 1`!

That's still 900k blocks better than us and they'd probably catch up very very soon :joy:

**Comment by macfarla** [comment]
Closing as various improvements in syncing and peering have been done since this
