### ISSUE TITLE
GHA: buildDocker (self-hosted, ARM64) step failing

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6929]
Last success was 2 weeks ago: https://github.com/hyperledger/besu/actions/runs/8487812388

Discovered during the 24.3.2 release process -
https://github.com/hyperledger/besu/actions/runs/8639188327/job/23686748688#step:9:478

It actually failed for 24.4.0-RC2 as well last week: https://github.com/hyperledger/besu/actions/runs/8500195660

```

INFO: Found goss_wait.yaml, waiting for it to pass before running tests
ERROR: goss_wait.yaml never passed
INFO: Deleting container

> Task :testDocker FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/_work/besu/besu/build.gradle' line: 798

* What went wrong:
Execution failed for task ':testDocker'.
> Process 'command '/bin/bash'' finished with non-zero exit value 1
```

**Comment by siladu** [comment]
This problem occurs for Docker server version 25.0.4+. It was triggered by the hyperledger self-hosted runner upgrading from 3.314.1 -> 3.315.0 which includes a docker upgrade https://github.com/actions/runner/releases

We have temporarily worked around this by using a non-hyperledger self-hosted runner with the downgraded docker version.

We still need to determine is this is just an issue with goss or whether users could run into it during normal operation.
