### ISSUE TITLE
Add Revert reason to Trace APIs

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#695]
The `debug_*` series trace operations record the revert reasons when a method call reverts.  However the `trace_*` series do not.  When a call fails I would like the reason to show up in the vmTrace at the operation that made the call and in the flat trace.  When a precompiled call returns a revert reason that also should be included as a trace, even though precompiled calls are not normally in the vmTrace.

**Comment by vmichalik** [comment]
@davemec is this closed by #1921?

**Comment by lucassaldanha** [comment]
I did a quick review of the PR and I believe it does. @shemnon you opened this ticket, are you happy to close it?
