### ISSUE TITLE
"Intrinsic gas exceeds gas limit" returned when calling `delete mapping[addr]` or `mapping[addr] = 0`

### ISSUE THREAD

**Issue by cianx** [hyperledger/besu#696]
### Description
As an developer, I want to be able to perfom solidity mapping delete and set operations successfully on hyperledger besu as I can on geth and ganache. 

Calling delete and set to 0 solidity mapping  in solidity fail on hyperledger besu. 

I have posted a simple reproducer of these issues here: https://github.com/cianx/besu-test

### Acceptance Criteria
* Calling delete and set to 0 solidity mapping succeed.

### Steps to Reproduce (Bug)
1. Start a besu node, (tested on kaleido network, private clique network, and docker dev node)
The simplest configuration is:
```
>   besu \
    --network=dev \
    --miner-enabled \
    --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73 \
    --rpc-http-cors-origins=all \
    --host-whitelist=* \
    --rpc-http-enabled=true \
    --rpc-http-host=0.0.0.0 \
    --rpc-http-port=4300 \
    --min-gas-price=0 
```
2. 
```
contract TestContract {
  mapping (address => uint256) balances;

  function setBalance(uint256 amt) public {
    balances[msg.sender] = amt;
  }

  function zeroBalance() public {
    balances[msg.sender] = 0;
  }

  function resetBalance() public {
    delete balances[msg.sender];
  }

  function getBalance(address addr) public view returns(uint256) {
    return balances[addr];
  }
}
```

3. Call contract contract functions resetBalance, zeroBalance 

**Expected behavior:** [What you expect to happen]
Success full transactions exection, mapping entry deleted or set to zero respectively.

**Actual behavior:** [What actually happens]
Transactions return a failure code 
```
test_1     |   statusCode: 400,
test_1     |   responseText: '{\n' +
test_1     |     '  "jsonrpc" : "2.0",\n' +
test_1     |     '  "id" : 94,\n' +
test_1     |     '  "error" : {\n' +
test_1     |     '    "code" : -32003,\n' +
test_1     |     '    "message" : "Intrinsic gas exceeds gas limit"\n' +
test_1     |     '  }\n' +
test_1     |     '}',
```
**Frequency:** [What percentage of the time does it occur?]
Always.

### Versions (Add all that apply)
* Software version: [`besu --version`]
1.4.3 
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel Version: [`uname -a`]
Linux sterling 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Docker Version: [`docker version`]
Docker version 19.03.6, build 369ce74a3c
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by matkt** [comment]
Hi @cianx the fix is ​​available on the master. Thank you for reporting this issue

**Comment by timbeiko** [comment]
Closing now, @cianx feel free to re-open if there is anything else :-)
