### ISSUE TITLE
EIP-7685: Implementation

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#6986]
https://eips.ethereum.org/EIPS/eip-7685

Provides a generalized way for new blocks to make requests of the CL. Should be implemented so that 6110 and 7002 implementations can be retrofitted to use it.

**Comment by jflo** [comment]
Currently failing 48/62 tests in the execution spec tests:

https://github.com/ethereum/execution-spec-tests/tree/main/tests/prague/eip7685_general_purpose_el_requests

**Comment by Gabriel-Trintinalia** [comment]
They fail because we need https://github.com/hyperledger/besu/pull/7266
