### ISSUE TITLE
Sonarqube runs with failed tests shouldn't be failed workflow runs

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#6987]
If you look at the history of Sonarqube actions, they don't always pass, despite having done their analysis and published it correctly. I suspect this is due to flaky tests, flaking during the course of the `build` target.

Can we setup this action to only fail if there was a problem with sonar analysis or publishing?

**Comment by joshuafernandes** [comment]
Hi @macfarla @jflo :) Just wanted to get some context on this mate, if these are flaky tests wouldn't we be better of fixing them so they aren't flaky? 
Or should we remove sonarqube - if we mute the results, is there much point in running it?

**Comment by jflo** [comment]
Definitely don't want to mute the results. Reporting on flaky tests helps us triage them to determine if they should be fixed or removed, so we want to include flaky tests in sonarqube reports.
