### ISSUE TITLE
consolidate pre-release workflow into a single release workflow

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6994]
As a release manager, I want a single action for releases so I don't need to do the extra step of creating a pre-release.

We don't need users to test pre-releases so there's no requirement to make it public until we are ready to do the official release.

**Comment by cdivitotawela** [comment]
Currently there are three GitHub workflows for the release
- release artifacts (trigger on pre-released)
- docker (trigger on pre-released)
- release besu (trigger on released)

All these workflows will be merged to single workflow and will be triggered on released.

**Comment by cdivitotawela** [comment]
Besu release workflow will be updated as follows. When a release is created both `artifacts` and `hadolint` jobs started and rest of the jobs will follow based on dependency.

<img width="691" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07a23d32ff5f165e6e6b6732169d1fa17f4d51c9/besu-release.jpg" alt="besu-release.jpg" />

**Comment by cdivitotawela** [comment]
PR [https://github.com/hyperledger/besu/pull/7152](https://github.com/hyperledger/besu/pull/7152) has been created.
