### ISSUE TITLE
EIP-7212: r1 curve precompile

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#6999]
NOTE: inclusion in Prague likely but not yet confirmed.

https://eips.ethereum.org/EIPS/eip-7212

This curve is already supported by besu-native, so it should just be a matter of wrapping a pre-compile around it. It's also already supported by ECRCPrecompiledContract, it just needs to be instantiated with the r1 curve, and bound to whatever opcode we decide on.

**Comment by ulerdogan** [comment]
Hello! Thanks for creating the issue and considering for the implementation.
Just to mention, EIP-7212 has been moved to RIP repository and the final specs are there, the progress will likely follow the proposal as an RIP. 
[RIP here](https://github.com/ethereum/RIPs/blob/master/RIPS/rip-7212.md)
