### ISSUE TITLE
Issue while connecting with peer node

### ISSUE THREAD

**Issue by Karthigasrini** [hyperledger/besu#7010]
Hi,
 When connecting with peer node getting this error,
 
![image](https://github.com/hyperledger/besu/assets/30004506/6014b67b-ef08-453c-be3a-f3857d7d4c7b)

![image](https://github.com/hyperledger/besu/assets/30004506/66858b6f-9a20-4296-9cce-6b0b0cf785cd)

 
  Running command:
   ../../besu/bin/besu --data-path=data --genesis-file=../genesis.json --bootnodes=enode://<enode>@127.0.0.1:30303 --p2p-port=30305 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT,WEB3,ADMIN,MINER,DEBUG,TRACE,TXPOOL --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8565 --rpc-http-host=0.0.0.0 --rpc-http-max-active-connections=1000000

**Comment by ahamlat** [comment]
Hi @Karthigasrini,
What is Besu -Xmx here ? You can share the the whole besu logs, it displays some configuration data at startup.
Also, what is the size of your genesis file ? and why do you need to have 1000000 rpc-http-max-active-connections ?

Your node had a memory issue at startup.

**Comment by non-fungible-nelson** [comment]
Closing - please re-open if you have more information to provide
