### ISSUE TITLE
Migrate from self-hosted hyp-ci-linux-arm64 to besu-arm64 runner

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#7026]
For arm docker builds we currently target the self-hosted `hyp-ci-linux-arm64` but now there is a github provided runner enabled

**Comment by ryjones** [comment]
The runner name is `besu-arm64`

**Comment by siladu** [comment]
https://github.com/hyperledger/besu/pull/7054 had to be reverted (in https://github.com/hyperledger/besu/pull/7087) so this issue still needs replaying.

@seanyoung latest comment:
> Actually it needed:

```
 sudo usermod -aG docker $USER
 sudo apt-get install acl
 sudo setfacl --modify user:$USER:rw /var/run/docker.sock
```

> However I take your point that it's hard to test.

> I understand that in June the arm64 runners will be public, so let's try again at that point.

> Also at point hopefully it should come with docker installed so with any luck it will be plain sailing.
