### ISSUE TITLE
Get requesttimeoutseconds current value on a node

### ISSUE THREAD

**Issue by cryptohazard** [hyperledger/besu#7032]
### Description
As I manage a private chain using BESU QBFT, I want to be able to get the current `requesttimeoutseconds`  of a node. 
We did some high availability/disaster recovery tests and it would be easier to troubleshoot issues if we could monitor that values from each node at all time. 

We are currently using a network of BESU 24.3.0 nodes.

**Comment by macfarla** [comment]
@cryptohazard to clarify - you're asking for a metric for this? you're welcome to do a PR :)

**Comment by cryptohazard** [comment]
yes a metric would be awesome. 
Right now I can only know that value after the blocks have been mined and I plot the timestamps.

I'm not that familiar with Besu's code to contribute (yet) and only look through it when I'm in trouble. Maybe soo I will be able to. Or I will manage to lobby my company to finally sign a contract with you guys for this type of service/request (I know there were some consulting in place but if things keep getting bigger they will have to sign something with you).
