### ISSUE TITLE
peers denylist in private chain

### ISSUE THREAD

**Issue by cryptohazard** [hyperledger/besu#7039]
### Description
Hello
I run into bug #7036 in my private QBFT chain of 4 nodes.  The troubled node then put the rest of the network on `denylist`. 
We used bootnodes to connect everyone and that node was actually one of the bootnodes.

Is there a way to reset that list on a node?
Because in a private chain, we typically have less than 10 peers so we should either avoid banning anyone or be able to reset.

### Versions 
* Software version: [`24.3.0`]

**Comment by macfarla** [comment]
the denylist is not saved across restarts so restarting all the nodes should reset it. Obviously this is not ideal. 

Maintained peers (from static-nodes.json, or added by admin_addPeer API) do not get added to the denylist so configuring all your bootnodes as static nodes would prevent this situation from happening again. 

There isn't an API to reset the denylist

**Comment by cryptohazard** [comment]
Thanks.
I think we are going to switch to static nodes then and mainly keep bootnodes for onbaording new nodes easily.
