### ISSUE TITLE
Optionally load jemalloc 

### ISSUE THREAD

**Issue by amsmota** [hyperledger/besu#7047]
### Description
As an Developer/Devops/Tester, I want to enable/disable the use of jemalloc when starting Besu so that I can easily test performance with/without jemalloc and be able to start without jemalloc if there is a memory issue on startup.

### Acceptance Criteria
* Besu will load jemalloc optionally based on a env var

### Versions
* All Linux based versions

### Implementation

I was able to implement and test this feature by reusing the `BESU_USING_JEMALLOC` env var, with changes in the initial _besu start script_ and a few lines in _ConfigurationOverviewBuilder_. 

If set, `BESU_USING_JEMALLOC=true` will load jemalloc, if set to anything else it won't. If `BESU_USING_JEMALLOC`  is not set at all it'll load it too (that is the existing behavior). 

If enough people think this is useful I am ready to create a PR.

**Comment by macfarla** [comment]
@amsmota I think it would be great if you could do a PR for this

**Comment by amsmota** [comment]
I will. Thanks... 👍 

> @amsmota I think it would be great if you could do a PR for this

**Comment by amsmota** [comment]
Opened the PR already, see below.

Thanks. 👍

**Comment by amsmota** [comment]
Hi @macfarla, @non-fungible-nelson, I merged the current main branch into  my branch, and it created a new PR (see below). Can youse please review it and hopefully approve it?

Many thanks.

Cheers.


https://github.com/hyperledger/besu/pull/7424
