### ISSUE TITLE
Transaction that is added to a node's pool may not be propagated to the pools of its peer nodes

### ISSUE THREAD

**Issue by nano-adhara** [hyperledger/besu#7081]
### Introduction

In certain situations, **a transaction that is added to a node's pool (of sequenced type) may not be propagated to the pools of its peer nodes,** resulting in the transaction being present only in the transaction receptor node's pool rather than being distributed across all nodes' pools.

### Summary

We are using the following five nodes setup for a private Besu network with QBFT protocol:
- A non-validator node that doesn’t participate in the consensus protocol.
- One node acting as a validator.

**Users connect to the non-validator node to send transactions**, and it propagates them to the validator so that they are included in new blocks.

**Starting from a scenario where all the nodes have a transaction** (let’s call it “tx_a”) in the pool, as shown in the first image.

![first image](https://github.com/hyperledger/besu/assets/50823157/bc8d8032-ef08-4189-93db-74fe42f1d5f2)

If the transaction is dropped from the pool of the nodes for any reason, **the pools of the nodes are empty** as we can see in the second image.

![second image](https://github.com/hyperledger/besu/assets/50823157/a6a64722-ec51-4bd1-a95c-abceae883fc3)

Then, if the transaction is sent again to the non-validator, it is added to its pool, **but it is not added to the validator pool** as we can see in the third image.

![third image](https://github.com/hyperledger/besu/assets/50823157/89477ecc-a416-4b93-a2de-1fb7376e7c13)

### Detailed description

We have observed 2 problematic scenarios related to how the nodes handle their caches:

1. When a client sends a transaction to the non-validator node, if this node dropped the transaction before, [the node doesn't propagate the transaction to the peers](https://github.com/hyperledger/besu/blob/main/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PeerTransactionTracker.java#L69-L71) in the network. If the transaction is not propagated to a validator, it will never be mined.
2. When a peer propagates a transaction to the validator node, if this node has already received the transaction from a peer, [the transaction is not promoted to the transactions pool](https://github.com/hyperledger/besu/blob/main/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageProcessor.java#L69-L70). If the transaction is not promoted to the transactions pool, it will never be mined.

Both scenarios are problematic if the transaction is valid but the node dropped it from the pool before mining the transaction for any reason, e.g. exceeding `tx-pool-retention-hours` limit.

**We were able to add that transaction again to the validator’s pool only by restarting all the nodes and sending the transaction again.**

It seems to be a bug by which internal caches are not updated properly when transactions are dropped/evicted from the pool, not allowing those transactions to be added into new blocks as they are not propagated by the non-validator node and they are rejected by the validator as well.

### Versions

This issue occurs in the latest version of the system, as of the time of this writing (v24.3.3). We believe that this occurs in previous versions as well.

### Steps to reproduce

This is an explanation of how we were able to reproduce the bug: 

1 . Set up at least one non-validator node and at least one validator node with a QBFT network configuration. 
3. Send a new transaction using a higher nonce than the expected one, so a nonce gap is created, and that transaction will remain in the pool of both the non-validator and validator nodes. 
4. Force the transaction to be dropped from the pool (for example waiting for the tx-pool-retention-hours to expire).
5. Resend the transaction to the non-validator node and you will be able to check that it won’t appear in the validator’s pool (as it does not get propagated by the non-validator nor accepted by the validator because it gets filtered due to be categorized as an already seen transaction).

### Expected behavior
:white_check_mark: = already happening
:x: = not happening

1. The user sends a transaction, which is received by the non-validator node and added to the pool :white_check_mark: 
2. The transaction is propagated to the validator nodes. :white_check_mark:
3. The validator nodes accept the transaction and add it to their pool. :white_check_mark:
4. Every node drops the transaction from its pool. :white_check_mark:
6. The user resends the transaction, which is received by the non-validator node and added to the pool. :white_check_mark:
7. The same as step 2. :x:
8. The same as step 3. :x:

### Nodes execution arguments

```
--tx-pool-max-size=5
--tx-pool=sequenced
--tx-pool-limit-by-account-percentage=1
```
### Nodes config

**Non-validator node**

```
# Network
p2p-host="127.0.0.1"
p2p-port=1232
max-peers=42

rpc-http-enabled=true
rpc-http-api=["ETH","NET","WEB3","IBFT","QBFT","TXPOOL","ADMIN"]

host-whitelist=["*"]
rpc-http-cors-origins=["all"]

rpc-http-host="0.0.0.0"
rpc-http-port=8545

rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=30303

# Mining
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

min-gas-price="0"
revert-reason-enabled=true

metrics-category=[ "ETHEREUM", "BLOCKCHAIN","EXECUTORS","JVM","NETWORK","PEERS","PROCESS","KVSTORE_ROCKSDB","KVSTORE_ROCKSDB_STATS","RPC","SYNCHRONIZER", "TRANSACTION_POOL" ]
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9095
```

**Validator node config**

```
# Network
p2p-host="127.0.0.1"
p2p-port=1234
max-peers=42

rpc-http-enabled=true
rpc-http-api=["ETH","NET","WEB3","IBFT","QBFT","TXPOOL"]

host-whitelist=["*"]
rpc-http-cors-origins=["all"]

rpc-http-host="0.0.0.0"
rpc-http-port=8585

rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=30305

# Mining
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

min-gas-price="0"
revert-reason-enabled=true

metrics-category=[ "ETHEREUM", "BLOCKCHAIN","EXECUTORS","JVM","NETWORK","PEERS","PROCESS","KVSTORE_ROCKSDB","KVSTORE_ROCKSDB_STATS","RPC","SYNCHRONIZER", "TRANSACTION_POOL" ]
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9097
```

**genesis.json**

```
{
 "config": {
   "muirGlacierBlock": 0,
   "chainId": 44844,
   "contractSizeLimit": 2147483647,
   "qbft": {
     "blockperiodseconds": 1,
     "epochlength": 30000,
     "requesttimeoutseconds": 10
   }
 },
 "nonce": "0x0",
 "timestamp": "0x58ee40ba",
 "gasLimit": "0x5F5E100",
 "difficulty": "0x1",
 "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
 "coinbase": "0x0000000000000000000000000000000000000000",
 "alloc": {
   "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
     "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
     "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
     "balance": "0xad78ebc5ac6200000"
   },
   "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
     "privateKey": "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
     "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
     "balance": "90000000000000000000000"
   },
   "f17f52151EbEF6C7334FAD080c5704D77216b732": {
     "privateKey": "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
     "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
     "balance": "90000000000000000000000"
   }
 },
 "extraData": "0xf87aa00000000000000000000000000000000000000000000000000000000000000000f85494792fc5093a85bd8fb52c781aefee7da96d2180cf9414275b2f4cefb4c72f12ca32ce0044578923e1b694fcbc96c1e8a673b7cdc333c6687f07fa2c28befe94b5ec93ab0a6ad8f8c0e404e3225b16cb2ea23a1ec080c0"
}
```

**Comment by nano-adhara** [comment]
I added the node execution arguments into the issue. This is using the sequenced node pool

**Comment by nano-adhara** [comment]
Hello @fab-10,

So as an answer to your last question, is not happening that much, once a month, but the real problem with that is that whenever happens, the only solution is to restart the besu clients. 

Sorry for the late answer.

Ill include Fernando [@chookly314](https://github.com/chookly314) and Coenie [@coeniebeyers](https://github.com/coeniebeyers) in the topic to move forward in the conversation.

**Comment by non-fungible-nelson** [comment]
Hi @nano-adhara - sorry this hasn't moved. I am wondering if this may be an issue that we could work with @matthew1001 as its in QBFT and the sequenced pool. Was there other context needed from the folks you tagged in your comment?

**Comment by matthew1001** [comment]
I'd be happy to look into this at some point if @fab-10 doesn't get there first. I'm a bit focused on bonsai archive and empty block period for the time being so might not be that soon for me to take a look

**Comment by nano-adhara** [comment]
No context from the other folks i tagged. Just did so they have all the context as well

**Comment by louisrushin** [comment]
@matthew1001 Hope you are doing well? I was wondering if you could advise when you would be able to look into the issue above? Kind regards

**Comment by fab-10** [comment]
sorry for being slow on this one, but I can start working on it, and hope to have something by the next week.

**Comment by louisrushin** [comment]
Hi @fab-10 , thank you very much, much appreciated! Regards

**Comment by louisrushin** [comment]
Hi @fab-10 hope you are doing well? Was just wondering if still possible for something this week? Kind regards, Louis

**Comment by fab-10** [comment]
Hi @louisrushin, still not done, definitely not for this week

**Comment by fab-10** [comment]
it is on main now, so you can start trying the develop version, before the next release is out

**Comment by louisrushin** [comment]
Thank you very much!

**Comment by petermunnings** [comment]
@fab-10 @matthew1001 what is the process now?  This ticket is closed, but the problem is not solved as demonstrated by @nano-adhara above.  Can you give us some guidance on how we should proceed.  We have a live environment with this problem in which is getting a lot of attention.

**Comment by fab-10** [comment]
@petermunnings I am reopening the ticket, and will take a look at your report to reproduce it and fix in the next days, if in the meantime if you already have in idea of the solution, you can propose a PR for review.

**Comment by coeniebeyers** [comment]
Hi @fab-10 just following up, any progress on this?

**Comment by fab-10** [comment]
thanks to @nano-adhara for the detailed steps to reproduce the issue, I was able to reproduce the issue and submit a fix in PR #7858.
Could you try out that branch and confirm that it works for you? 

One important note on an edge case: the eviction task is triggered every minute, so depending on the start time of each node, there could be 1 minute delay between the eviction of a tx between 2 nodes in the worst case, this means that if you try to resubmit the tx just after it has evicted on one node, it is possible that the same tx isn't still evicted on every node, so I suggest to wait 1 minute to resend the tx after it has been evicted.

**Comment by nano-adhara** [comment]
let me review the branch and let you know the outcome. thank you @fab-10

**Comment by nano-adhara** [comment]
hello @fab-10. I was able to test the scenario and now its working :+1:.

i was considering the edge case you provided. i was able to test it aswell and i have some doubts that id like to know the answer on how to proceed when we apply this besu patch.

- For long-living networks, i guess this should not be a problem as the eviction is a one time minute compared to default thirteen hours default retencion policy. Still, as this is something that can happen in a very edgy scenario. Is there something that can be done to force manually (or via API) an eviction check?
- In the scenario that transaction was evicted from client node, but not from validator node (because we are in that 1minute gap). If we provide the transaction again, there are two transactions that look like the same, but are different for each node. The client node will hold the new one, and the validator node is still holding the old one until evicted. Are they the same transaction?
  - Considering the scenario above. Imagine that i send another transaction in that 1 minute gap that fixes the nonce gap. What will happen is that the validator node inmediately mine both transactions from the pool. Is that right? what will happen with the transaction in the client node?
- Lastly, even for this edge cases, i can assume that for this patch, even with the time eviction gaps, the important thing is that if BOTH transactions ends up evicted in both pools, the moment we resend the transaction that will be shared again inthe two nodes, is this assumption right?

**Comment by fab-10** [comment]
> hello @fab-10. I was able to test the scenario and now its working 👍.

great, I will merge the PR then

>     * For long-living networks, i guess this should not be a problem as the eviction is a one time minute compared to default thirteen hours default retencion policy. Still, as this is something that can happen in a very edgy scenario. Is there something that can be done to force manually (or via API) an eviction check?

at the moment there is way to trigger the eviction manually.

> 
>     * In the scenario that transaction was evicted from client node, but not from validator node (because we are in that 1minute gap). If we provide the transaction again, there are two transactions that look like the same, but are different for each node. The client node will hold the new one, and the validator node is still holding the old one until evicted. Are they the same transaction?

yes it will be the same tx (same hash), otherwise in case any of the tx field has changed then it will be a different one, and it could replace the previous one, according to the transaction replacement rule.

>       
>       * Considering the scenario above. Imagine that i send another transaction in that 1 minute gap that fixes the nonce gap. What will happen is that the validator node inmediately mine both transactions from the pool. Is that right? what will happen with the transaction in the client node?

Yes the validator could mine both, and the one in the node will be removed as soon as the new block will be imported.

> 
>     * Lastly, even for this edge cases, i can assume that for this patch, even with the time eviction gaps, the important thing is that if BOTH transactions ends up evicted in both pools, the moment we resend the transaction that will be shared again inthe two nodes, is this assumption right? This is important as we are looking forward to a solution that **does not require to restart the full network**

Correct, with this fix, if the tx has been evicted by all pools, then after re-sending it will be added again to every pool

**Comment by fab-10** [comment]
FYI in this PR https://github.com/hyperledger/besu/pull/8537, I am changing the default behavior but only for the Layered txpool, so you are not affected since using the Sequenced txpool
