### ISSUE TITLE
Implement `eth_maxPriorityFeePerGas` RPC method

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#7112]
### Description

Implement the  `eth_maxPriorityFeePerGas` RPC method as defined by the official specification https://ethereum.github.io/execution-apis/api-documentation/

**Comment by macfarla** [comment]
some extra context in #5658

**Comment by fab-10** [comment]
this feature it is already implement in GraphQL, so should be simple to expose it as RPC methods as well

**Comment by macfarla** [comment]
closing as duplicate of #5658
