### ISSUE TITLE
Investigate different implementation of BLS12-381 precompiles

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#7114]
### Description
We want to investigate different implementation of  BLS12-381 precompiles and assess their performances.
The goal of this issue is to create a quick process to test and switch different implementation, with the explanation of each step.
We also want to be sure that all the execution-spec-tests are passing with Besu implementation.

**Comment by garyschulte** [comment]
This benchmarking work has been completed and results between matter-labs, gnark-crypto, and constantine are represented in these sheets:

[all-library comparison](https://docs.google.com/spreadsheets/d/1Iku1sNKB64zokN6oYT1qRmbXIytAv4_Knpjn654fFzw/edit?usp=sharing)
[MSM performance comparison](https://docs.google.com/spreadsheets/d/1lbKFRJ0tWg7fDRVeNRVk4ZtnZ_1w7SLizqHaz5QQAC4/edit?usp=sharing)

Net result is that gnark-crypto performs best on arm64 systems, and constantine performs best on x86 systems, and the acceptance criteria for this ticket should be updated to choose between these two implementations based on the host architecture.
