### ISSUE TITLE
Save the scalars of the children directly in the parents.

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#7118]
### Description

To optimize and reduce the number of disk accesses during the generation of proofs, it would be preferable to store the scalars of the children directly in the parents. Because for the proofs, it is necessary to have the scalars of each child, which could lead to a significant number of reads.

We must implement mechanisms to reduce the impact on the database size by not storing the scalars of NullNode, for example.

https://github.com/hyperledger/besu-verkle-trie/issues/60

**Comment by matkt** [comment]
is it ok if I assign this ticket to you ? @thomas-quadratic

**Comment by thomas-quadratic** [comment]
Ok with me

**Comment by matkt** [comment]
link the PR : https://github.com/hyperledger/besu-verkle-trie/pull/63
