### ISSUE TITLE
automate creation of homebrew release

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7132]
homebrew release gets created after besu release artifact is available. Think some more parts of this can be automated - maybe GHA

homebrew repo -
https://github.com/hyperledger/homebrew-besu

 instructions for how to create the release - 
git checkout the homebrew-besu repo
git checkout branch 24.5.2
sh updateBesu <24.5.2>

^ this updates besu.rb file
create a PR with this update
git add besu.rb
git commit
git push

**Comment by cdivitotawela** [comment]
It is possible to add a GitHub workflow to commit the changes but bypassing the DCO is the challenge. I could configure bot user and email address for the commit. What would be the Hyperledger requirement using a bot commit.

**Comment by cdivitotawela** [comment]
In order to fully automate the Homebrew release triggered at the end of the Besu release, it requires a GitHub app in Hyperledger GitHub org with permission to create PR. Not sure whether is it feasible to request a GitHub app with permission to enable this automation.

**Comment by cdivitotawela** [comment]
Will create a GitHub workflow which can trigger on-demand, that would create a new branch and update the version. Release manager be able to run the job to create the branch. Creating PR from GITHUB_TOKEN is not possible so user need to create the PR from the branch.

**Comment by cdivitotawela** [comment]
Pull request https://github.com/hyperledger/homebrew-besu/pull/126
