### ISSUE TITLE
Flaky test - org.hyperledger.besu.ethereum.eth.sync.backwardsync.BackwardSyncAlgSpec#shouldAwokeWhenConditionReachedAndReady

### ISSUE THREAD

**Issue by usmansaleem** [hyperledger/besu#7146]
Flaky test observed in one of the PRs workflow.
org.hyperledger.besu.ethereum.eth.sync.backwardsync.BackwardSyncAlgSpec#shouldAwokeWhenConditionReachedAndReady

https://github.com/hyperledger/besu/actions/runs/9262194300/job/25478793322?pr=7129
```
BackwardSyncAlgSpec > shouldAwokeWhenConditionReachedAndReady() FAILED
    java.util.concurrent.TimeoutException at BackwardSyncAlgSpec.java:192
```

**Comment by eenagy** [comment]
I'm also seeing this happening consistently.
