### ISSUE TITLE
GHA for DCO

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7175]
DCO bot is having issues and we should roll our own GHA to do the check.

**Comment by cdivitotawela** [comment]
It seems we have been using the GHA before for the DCO checks. We dropped this action in [commit](https://github.com/hyperledger/besu/commit/9cb6600456000c68aebec54670cb27ac017f6f61#diff-6d726f6fb9f8c8fc6941f7fbcddcb04a1bb5f96ba6c96dab274c2c1c7a95c221) when we migrated from CircleCI to GHA. May be this is when DCO App might have been used.

Now we have problems with the DCO App, we can introduce DCO GHA check as well. Required status check can be switched to either or else remove the DCO App completely and rely on the GHA.
