### ISSUE TITLE
automate the docker verification steps

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7176]
currently we run these checks manually after the release

we can automate these

**Comment by cdivitotawela** [comment]
New GitHub workflow will be added which can be triggered with workflow_dispatch. This workflow starts the containers and verify Besu application log "Ethereum main loop is up" present in started container. If the container log contains the string it will mark as the test pass. 

For the latest tag, workflow will verify whether version specified in the Besu log matches the version passed.
```
docker run hyperledger/besu:<version>
docker run hyperledger/besu:<version>-arm64
docker run --platform linux/amd64 hyperledger/besu:<version>-amd64
docker run --pull=always hyperledger/besu:latest (check version is )
```

During a release, above workflow will be triggered at the end of the docker image publish. Docker image testing is de-coupled from the release but triggered as part of the release process.
