### ISSUE TITLE
Exit after import

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#721]
In https://github.com/ethereum/hive/pull/261 , I implemented hive block import for Besu. 

However, when I do the `import` command (which fails, btw, but I don't know if it matters for this ticket), besu doesn't exit after the import is done. Is that a known/desired feature? Can you change it, so that besu exits after the block(s) have been imported?

**Comment by timbeiko** [comment]
Hey @holiman, 

We'll be looking into this in the next few weeks. 

As for the failures, do you have a link to some of the failed imports for Besu? 

Thanks

**Comment by holiman** [comment]
This is a sync - test: https://hivetests.ethdevops.io/?suite=1587974674-63bde328c122e5fc52af6b280106531c.json 
The sync server tries to import 10 blocks, and the tests then proceed trying to sync other clients from that source. 

Here's the log from when Besu is the sync source: https://hivetests.ethdevops.io/viewer.html?file=results/besu_latest/client-bb212852.log#L29

And here, the log shows that Besu _did_ exit properly after the import, and we started a second run with it in normal mode: 
https://hivetests.ethdevops.io/viewer.html?file=results/besu_latest/client-bb212852.log#L34

So this ticket seems to be in error!

**Comment by holiman** [comment]
( I might have mixed up besu and nethermind, and should have filed the exit-after-import ticket with them instead. Sorry!)

**Comment by timbeiko** [comment]
Thanks for the info!
