### ISSUE TITLE
Refactor EIP-7002 implementation to use contract

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#7259]
When EIP-7002 was designed, client teams had the option of calling an enshrined contract, or implementing it directly against state. When this was implemented, we chose the option of a direct implementation against the state. Since then, we've realized offering teams that choice opens up the potential for bugs, and [when EIP-7251 is implemented](https://github.com/hyperledger/besu/issues/7254) it should be via the enshrined contract.

For consistency purposes, we should go back over the EIP-7002 implementation and alter it to be more consistent with future "requests" that are implemented via enshrined contracts.

### Acceptance Criteria
* EIP-7002 depends on enshrined contract.

**Comment by Gabriel-Trintinalia** [comment]
[#7263 Implement System Calls](https://github.com/hyperledger/besu/pull/7263)
