### ISSUE TITLE
Withdrawal Requests Contract system tx update differs from Geth 

### ISSUE THREAD

**Issue by marioevz** [hyperledger/besu#7289]
### Description

EIP-7002 system tx execution at the end of the block's transaction processing differs from Geth, and causes a state root mismatch.

Issue can be reproduced on main branch with the the following script: https://gist.github.com/marioevz/3de5acdff946861722a1be41f15f1a2a

On geth's evm tool output, in the withdrawal requests contract address, we can see the extra two keys set as:
```
"0x0000000000000000000000000000000000000000000000000000000000000000": "0x000000000000000000000000000000000000000000000000000000000000001e",
"0x0000000000000000000000000000000000000000000000000000000000000002": "0x0000000000000000000000000000000000000000000000000000000000000010",
```

Whereas these keys are missing from besu's output.

**Comment by jframe** [comment]
@Gabriel-Trintinalia Is this fixed with the changes to use the system contract?

**Comment by Gabriel-Trintinalia** [comment]
yes, it should be

**Comment by non-fungible-nelson** [comment]
@Gabriel-Trintinalia - should we close? is the PR merged

**Comment by Gabriel-Trintinalia** [comment]
closed by https://github.com/hyperledger/besu/pull/7263
