### ISSUE TITLE
Privacy is not supported in Bonsai

### ISSUE THREAD

**Issue by gtebrean** [hyperledger/besu#7300]
### Description
Considering the new sunset plan for Besu, we are transitioning  from Forest to Bonsai state. Currently, the majority of enterprise customers use privacy features in Besu networks through existing plugins or custom plugins, both of which extend the Besu Privacy Plugin.

To ensure a smooth transition, these Privacy Plugins must also be supported with the new Bonsai state. The key question is whether Besu will continue to handle these plugins in the same way it has for privacy groups, privacy precompiled contract and private marker transactions. This is particularly important given the upcoming changes in Privacy. Additionally, privacy is not yet enabled on Bonsai. Will this functionality be available once the PoA tests are completed?

**Expected behavior:** [What you expect to happen]
Privacy plugin supported in Bonsai

**Actual behavior:** [What actually happens]
Privacy plugin is not supported in Bonsai

**Comment by jframe** [comment]
@non-fungible-nelson Can please elaborate the product strategy around this? Is the plan for Bonsai archive to allow for privacy on Bonsai?

**Comment by macfarla** [comment]
@gtebrean @NickSneo cc @jframe the Consensys besu team won't be implementing support for privacy + bonsai. If that's something you want to implement you're welcome to fork and maintain.
