### ISSUE TITLE
Remove Privacy ATs - have been disabled for some time

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7347]
Remove privacy AT classes and associated testing resources - look for AT classes that extend this base class -
java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyAcceptanceTestBase.java

**Comment by hudlerrr** [comment]
Heyy @macfarla could I get this issue assigned please :)

**Comment by pr9t** [comment]
Hey, I am interested in this issue. Please assign this to me.

**Comment by pr9t** [comment]
I have found these classes that extend the base class. Can I remove these classes and the base class?
1. acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/FlexiblePrivacyAcceptanceTestBase.java
2. acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/EnclaveErrorAcceptanceTest.java
3. acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/BftPrivacyClusterAcceptanceTest.java
4. acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PluginPrivacySigningAcceptanceTest.java
5. acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyClusterAcceptanceTest.java
6. acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyGroupAcceptanceTest.java
7. acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/ParameterizedEnclaveTestBase.java

**Comment by nettad** [comment]
I would like this issue assigned to me.

**Comment by macfarla** [comment]
Correct @pr9t those classes can all be removed. Assigned you and @nettad to the issue

**Comment by macfarla** [comment]
There are still some privacy related ATs that can be deleted. eg PrivacyGroupTest, MultiTenancyAcceptanceTest

2 ways to find them - run ./gradlew acceptanceTestPrivacy and see what tests get picked up 
OR
look for privacy folders under acceptance-tests dir- all tests within this dir can be deleted.

**Comment by macfarla** [comment]
fixed by #7569
