### ISSUE TITLE
Receipts root mismatch during Full Sync in QBFT

### ISSUE THREAD

**Issue by chenqping** [hyperledger/besu#7355]
### Description
As an [Actor], I want [feature] so that [why]. 

### Acceptance Criteria
* [sync successfully]

### Steps to Reproduce (Bug)
1. just resync from genesis

**Expected behavior:** [sync smoothly to the current block height]

**Actual behavior:** [Receipts root mismatch and disconnect the inbound peer]

**Frequency:** [every time sync to a certain height]

### Logs (if a bug)
Please post relevant logs from Besu (and the consensus client, if running proof of stake) from before and after the issue. 

### Versions (Add all that apply)
* Software version: [23.10.1]
* Java version: [jdk-17.0.6]
* OS Name & Version: [`Red Hat Enterprise Linux release 8.10 (Ootpa)`]
* Kernel Version: [`4.18.0-553.5.1.e18_10.x86_64`]
* Virtual Machine software & version: [N/A]
* Docker Version: [N/A]
* Cloud VM, type, size: [Amazon Web Services I3-large]
* Consensus Client & Version if using Proof of Stake: [QBFT]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - besu-23.10.1  jdk-17.0.6
* System info - memory 16GB, 4 CPUs

**Comment by non-fungible-nelson** [comment]
can you provide more logs and details about your configuration please?

**Comment by chenqping** [comment]
> can you provide more logs and details about your configuration please?

[besu.log](https://github.com/user-attachments/files/16345298/besu.log)
Hi upload the log file, the configuration and import procedure can be seen from the log

**Comment by chenqping** [comment]
This is a protocol upgrade issue, leading to the receipt root mismatch, so close it now
