### ISSUE TITLE
Besu uncaught exception in thread "EthScheduler-Services-" null

### ISSUE THREAD

**Issue by chenqping** [hyperledger/besu#7376]
### Description
I upgraded my Besu node from 23.10.1 to 24.7.0, but other nodes(validators) are still 23.10.1, and let the node resync from them, them the log always print "Uncaught exception in thread "EthScheduler-Services-158xxx" null " error messages, suspect the thread leaked? and the sync is also suspended now

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. start the node and run sync

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Logs (if a bug)
Please post relevant logs from Besu (and the consensus client, if running proof of stake) from before and after the issue. 

### Versions (Add all that apply)
* Software version: 24.7.0
* Java version: 22
* OS Name & Version: redhat
* Kernel Version: 4
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]
* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - qbft archive node
* System info - memory, CPU

**Comment by jflo** [comment]
Thanks for the report, please include your anonymized besu startup information.
