### ISSUE TITLE
Add network option for Ephemery Testnet

### ISSUE THREAD

**Issue by gconnect** [hyperledger/besu#7387]
- [x] Confirm anything outstanding for release with other maintainers on #besu-release in Discord
- [x] Update changelog if necessary, and merge a PR for it to main
  - [x] Notify maintainers about updating changelog for in-flight PRs 
- [x]  Optional: for hotfixes, create a release branch and cherry-pick, e.g. `release-<version>-hotfix`
- [x]  Optional: create a PR into main from the hotfix branch to see the CI checks pass
- [x]  On the appropriate branch/commit, create a calver tag for the release candidate, format example: `24.4.0-RC2`
- [x] Sign-off with team; confirm tag is correct in #besu-release in Discord
- [x] Consensys staff start burn-in using the proposed release <version-RCX> tag
- [x] Sign off burn-in; convey burn-in results in #besu-release in Discord
- [x] Using the same git sha, create a calver tag for the FULL RELEASE, example format `24.4.0`
- [x] Using the FULL RELEASE tag, create a release in github to trigger the workflows. Once published:
    - this is now public and notifies subscribed users
    - makes the release "latest" in github
    - publishes artefacts and version-specific docker tags
    - publishes the docker `latest` tag variants
- [x] Check binary SHAs are correct on the release page
- [x] Check "Container Verify" GitHub workflow has run successfully
- [x] Create homebrew release - run https://github.com/hyperledger/homebrew-besu/actions/workflows/update-version.yml
- [x] Create besu-docs release - https://github.com/hyperledger/besu-docs/releases/new
   - Copy release notes from besu
   - If publishing the release in github doesn't automatically trigger this workflow, then manually run https://github.com/hyperledger/besu-docs/actions/workflows/update-version.yml
- [x] Social announcements

There is currently no support for [Ephemery](https://ephemery.dev/) using the --network=ephemery flag.
In addition to adding the genesis flag the Ephemery implementation also requires a genesis reset function.

**Comment by jflo** [comment]
Please re-open using a plain issue template, this is for releases.

**Comment by gconnect** [comment]
Alright thanks will do that

**Comment by gconnect** [comment]
I just recreated the issue now on a plain template. 
https://github.com/hyperledger/besu/issues/7404
Please assign it to me. Thank you
