### ISSUE TITLE
Theoretical Issues with Clique

### ISSUE THREAD

**Issue by ckartik** [hyperledger/besu#7437]
## Background
It seems like clique was crafted as a concensus network for [Rinkeby testenet](https://github.com/ethereum/EIPs/issues/225). However, it came across a large swath of issues around halting and deadlock states. For geth it was the longest standing issue in the project, and was closed without resolution due to deprecation of clique support by the geth team. See [here](https://github.com/ethereum/go-ethereum/issues/18402)

### Question: Were you able to resolve the issues with clique that cause deadlocked states? 

To give some context, here's a visual:
![image](https://github.com/user-attachments/assets/212c1bf1-3447-4602-9ae8-3fa55695bab6)

In a situation of 3 signer nodes, due to network instability, you can arrive in a situation where each party has a split view of the world, such that all sealers/signers are too recent in their view of the chain to sign the next block, but the difficulty in each of their views is equivalent, resulting in no reorgs. Does Besu ever encounter similar issues of halting? If not, how did you resolve these theoretical shortcomings of Clique?

For more examples, here's a simulation script that can demonstrate such stuck states: [goerli/diff-simulation](https://github.com/goerli/diff-simulation)

**Comment by shemnon** [comment]
See https://eips.ethereum.org/EIPS/eip-3436, implemented in https://github.com/hyperledger/besu/pull/2084

**Comment by ckartik** [comment]
Thank you!
