### ISSUE TITLE
Flaky Test - TxPoolOptionsTest

### ISSUE THREAD

**Issue by Matilda-Clerke** [hyperledger/besu#7451]
txpoolForcePriceBumpToZeroWhenZeroBaseFeeMarket is failing consistently in CI, but not when run locally

**Comment by Matilda-Clerke** [comment]
Example failure:
`TxPoolOptionsTest > txpoolForcePriceBumpToZeroWhenZeroBaseFeeMarket() FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at TxPoolOptionsTest.java:104`

**Comment by fab-10** [comment]
Re-opening since the test is failing consistently in https://github.com/hyperledger/besu/pull/7510, see CI https://github.com/hyperledger/besu/actions/runs/10830553170/job/30055039117
