### ISSUE TITLE
ATs - not all are running in GHA

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7490]
I think there is something wrong with the AT test splitter script - if I'm reading this right -
I'm getting failures from this AT `ExecutionEngineShanghaiAcceptanceTest` running locally on main, and I can't see any evidence that this test is running in GHA - but actually no tests matching Execution* are running. And going by count of occurrence of `--tests` on eg this [page](https://github.com/hyperledger/besu/actions/runs/10463865639) (even when I expand all the sections), there's only 25 AT classes being picked up. When I run `acceptanceTestNotPrivacy` locally I get a report with 59 class files.

**Comment by macfarla** [comment]
maybe it's parameterized tests that are missing? eg BftBlockRewardPaymentAcceptanceTest and friends also missing
[currentTests.txt](https://github.com/user-attachments/files/16669111/currentTests.txt)

**Comment by fab-10** [comment]
Related to this https://github.com/hyperledger/besu/pull/7317, we need to add a dummy `@Test` to be sure they are selected, at least until https://github.com/gradle/gradle/issues/29895 is fixed
