### ISSUE TITLE
net-service information reading error for GraphQL

### ISSUE THREAD

**Issue by ITStarMan100** [hyperledger/besu#7513]
Description
Error to read host information about Graphql HTTP using curl "net_services" option.

Steps to Reproduce (Bug)
1. Run the BESU node as follows:

<path>/bin/besu \
  --network=holesky \
  --p2p-port=30303 \
  --rpc-http-port=8545 \
  --rpc-http-enabled=true \
  --rpc-http-cors-origins="*" \
  --engine-rpc-port=8551 \
  --max-peers=25 \
  --rpc-http-enabled=true \
  --sync-mode=SNAP \
  --logging=INFO \
  --data-storage-format=BONSAI \
  --Xbonsai-limit-trie-logs-enabled=true \
  --data-path="/var/lib/besu" \
  --graphql-http-enabled=true \
  --graphql-http-host="0.0.0.0" \
  --graphql-http-port=8549 \
  --engine-jwt-secret=/secrets/jwtsecret

2. Check the port using "netstat -tulnp".
Port for Graphql http to listen on 8549

tcp6       0      0 :::8549                 :::*                    LISTEN      2001774/java                                
tcp6       0      0 :::30303                :::*                    LISTEN      2001774/java                                
tcp6       0      0 127.0.0.1:8545          :::*                    LISTEN      2001774/java                                
tcp6       0      0 127.0.0.1:8551          :::*                    LISTEN      2001774/java 
udp6       0      0 :::30303                :::*                                2001774/java                                
udp6       0      0 :::48848                :::*                                2001774/java  

3. Run Net-Services command.

curl --location 'http://localhost:8545' \
--data '{
    "jsonrpc": "2.0",
    "method": "net_services",
    "params": [],
    "id": 1
}'

Actual behavior: Graphql Host information is not present.
{"jsonrpc":"2.0","id":1,"result":{"jsonrpc":{"host":"127.0.0.1","port":"8545"},"p2p":{"host":"127.0.0.1","port":"30303"}}}

Expected behavior: 
{"jsonrpc":"2.0","id":1,"result":{"jsonrpc":{"host":"127.0.0.1","port":"8545"},"p2p":{"host":"127.0.0.1","port":"30303"}, "graphql":{"host":"127.0.0.1","port":"8549"}}}

Frequency: 100%

Versions (Add all that apply)
Software version: 24.5.1
Java version: openjdk-java-17
OS Name & Version: Ubuntu 22, linux-x86_64

**Comment by pr9t** [comment]
Hey, I am interested in this issue. Could you please assign it to me and Lavender

**Comment by ITStarMan100** [comment]
Sorry.
I am modifying its source code.
________________________________

**Comment by ITStarMan100** [comment]
I have completed the code update for the above fix

Who should I contact after submitting a PR request?
