### ISSUE TITLE
Bug in `SimpleWorld.commit()` ?

### ISSUE THREAD

**Issue by DavePearce** [hyperledger/besu#7524]
### Description
Currently, `SimpleWorld.commit()` is defined as follows:

```java
@Override
  public void commit() {
    accounts.forEach(
        (address, account) -> {
          if (!account.updateParent()) {
            parent.accounts.put(address, account);
          }
        });
  }
```

However, this seems to be in conflict with this:

```java
  @Override
  public Collection<Address> getDeletedAccountAddresses() {
    return accounts.entrySet().stream()
        .filter(e -> e.getValue() == null)
        .map(Map.Entry::getKey)
        .toList();
  }
```

It seems to me that we want `account == null || !account.updateParent()` as the criteria in `commit()` above.

Thoughts?

**Comment by lu-pinto** [comment]
Yup that needs a null check as `deleteAccount` puts in `nulls` in the collection and `commit` can be called after `deleteAccount`: [AbstractMessageProcessor.java#L115-L116 ](https://github.com/hyperledger/besu/blob/c656ece8fca77bb0acb15f578de86aac98dec7d2/evm/src/main/java/org/hyperledger/besu/evm/processor/AbstractMessageProcessor.java#L115-L116). So definitely the collection is not null free
