### ISSUE TITLE
Export metrics for `finalized` and `safe` block number

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#7564]
### Description

Add the metrics for `finalized` and `safe` block number, likewise we have the one for the current chain head block number

**Comment by pr9t** [comment]
Hey, I am interested in this issue. Please assign this to me.

**Comment by AshuBoi** [comment]
Hey, can I have a look at it. I'm interested to help.

**Comment by julien-marchand** [comment]
Hey @pr9t and @AshuBoi, we (Linea) require this feature. I don't know if you have started working on this, but just FYI, we will probably start working on it from Monday 9th.

**Comment by AshuBoi** [comment]
Haven't started yet. but will get on it on Saturday 7th.

**Comment by jonesho** [comment]
Hey @AshuBoi, @pr9t, may I take this, if you guys still haven't made any progress on this issue yet? This issue is blocking the Linea team from a mainnet deployment and that's why we want it to be done soon cc @fab-10

**Comment by AshuBoi** [comment]
Hey @jonesho , the issue is not assigned to me. tried navigating on my own but need more info to contribute.
