### ISSUE TITLE
Update RocksDB version to 9.5.2

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#7573]
Besu is using currently RocksDB jar dependency version 8.3.2.
The latest version is 9.5.2, we need to update RocksDB dependency to this last release.

https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni/9.5.2
```
// https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni
implementation group: 'org.rocksdb', name: 'rocksdbjni', version: '9.5.2'
```

**Comment by joshuafernandes** [comment]
Hi @ahamlat could you ping me when this is complete please mate? I'll update the version of rocksdb in the k8s hooks container as well

**Comment by ahamlat** [comment]
@joshuafernandes : https://github.com/hyperledger/besu/pull/7817
