### ISSUE TITLE
After running nodes with all configs as per the docs, I cannot get ETH Balance in my local BESU Blockchain network

### ISSUE THREAD

**Issue by abdul745** [hyperledger/besu#7604]
I am developing a private Besu network with QBFT Consensus mechanism. I am following the docs exactly like [here](https://besu.hyperledger.org/development/private-networks/tutorials/qbft)
After running all 4 nodes when I import the wallet from QBFT_Config_File.js in my Metamask or any other wallet, I am unable to see any balance in the accounts. Where I should see 200 Eth or 9000 ETH in both accounts.
please help. I need to move on ASAP.

**Comment by Darrenpeaker** [comment]
> I am developing a private Besu network with QBFT Consensus mechanism. I am following the docs exactly like [here](https://besu.hyperledger.org/development/private-networks/tutorials/qbft) After running all 4 nodes when I import the wallet from QBFT_Config_File.js in my Metamask or any other wallet, I am unable to see any balance in the accounts. Where I should see 200 Eth or 9000 ETH in both accounts. please help. I need to move on ASAP.

@abdul745 Oh, it seems like you're facing an issue with the wallet balance not reflecting correctly in Metamask after setting up your private Besu network with QBFT consensus. “?

**Comment by Darrenpeaker** [comment]
@abdul745 

One possible reason for the balance not showing could be related to the genesis block configuration or the initial allocation of funds in the network setup. Let's review the QBFT_Config_File.js and ensure that the accounts are correctly initialized with the expected balances of 200 ETH and 9000 ETH.

**Comment by abdul745** [comment]
@Darrenpeaker I am using the exact same QBFTConfigFile as that in official docs. Still I am copying my QBFT & Genesis files here for your reference:
QBFTConfigFile:
{
  "genesis": {
    "config": {
      "chainId": 21000,
      "berlinBlock": 0,
      "qbft": {
        "blockperiodseconds": 2,
        "epochlength": 30000,
        "requesttimeoutseconds": 4
      }
    },
    "nonce": "0x0",
    "timestamp": "0x58ee40ba",
    "gasLimit": "0x47b760",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
      "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
        "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
        "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
        "balance": "0xad78ebc5ac6200000"
      },
      "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
        "privateKey": "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
        "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
        "balance": "90000000000000000000000"
      },
      "f17f52151EbEF6C7334FAD080c5704D77216b732": {
        "privateKey": "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
        "comment": "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
        "balance": "90000000000000000000000"
      }
    }
  },
  "blockchain": {
    "nodes": {
      "generate": true,
      "count": 4
    }
  }
}

Generated Genesis File:
{
  "config": {
    "chainId": 21000,
    "berlinBlock": 0,
    "qbft": {
      "blockperiodseconds": 2,
      "epochlength": 30000,
      "requesttimeoutseconds": 4
    }
  },

  "nonce": "0x0",
  "timestamp": "0x58ee40ba",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "extraData": "0xf87aa00000000000000000000000000000000000000000000000000000000000000000f85494a2c74fbe02e738dcf0d8e309d5a683050e2fd2fa948259fe1a84614ac728beb63a08ab578bcb18190094a649ec0e09e722b96e8728dccc5bcc7ef918ac4794d4438e71e3b05793298e59cc1d0e4b69e12f631bc080c0"
}
