### ISSUE TITLE
Improve block import time

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#7634]
Improve block import time in Besu to improve the syncing time in Besu. The final step in the chain syncing pipeline is an ImportBlocksStep which validates the block body, receipts and headers and inserts the data into the database. Any delay in inserting data into the database can impact the overall pipeline.

**Acceptance Criteria**
- Investigate and profile different approaches to importing the chain data into the database
- Measure syncing time improvements to ensure that chain download is improved with any changes

**Comment by jflo** [comment]
There is active work on more specific optimization techniques being done under the performance label. Closing this issue, but please re-open if you have something else in mind.
