### ISSUE TITLE
Shomei - metric for chain head (like ethereum_blockchain_height)

### ISSUE THREAD

**Issue by diana-borbe-consensys** [hyperledger/besu#7650]
### Description
As an Linea Operator, I want to be able to easily monitor shomei sync status. 

### Acceptance Criteria
* Explose shomei metric to follow head. 
* This metric will be similar to besu metric ethereum_blockchain_height

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Logs (if a bug)
Please post relevant logs from Besu (and the consensus client, if running proof of stake) from before and after the issue. 

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]
* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
* System info - memory, CPU

**Comment by non-fungible-nelson** [comment]
Estimation at about a day of work

**Comment by jflo** [comment]
issue moved to shomei repo https://github.com/Consensys/shomei/issues/99
