### ISSUE TITLE
Update Besu to match Pectra devnet-4 specs

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#7671]
Pectra devnet-4 brings some changes to the existing implementation of its EIPs.

The spec can be found here: https://notes.ethereum.org/@ethpandaops/pectra-devnet-4

The draft PR for the updated execution spec tests can be found here: https://github.com/ethereum/execution-spec-tests/pull/832

**Comment by jflo** [comment]
closed since devnet5 is approaching
