### ISSUE TITLE
DNSDaemonTest > Test DNS Daemon with a mock DNS server FAILED

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7690]
example failure https://github.com/hyperledger/besu/actions/runs/11097075828/job/30827764865?pr=7689

DNSDaemonTest > Test DNS Daemon with a mock DNS server FAILED
    java.lang.AssertionError at DNSDaemonTest.java:143

this is the test that's failing:

```
  @AfterEach
  @DisplayName("Check that the vertx worker verticle is still there")
  void lastChecks(final Vertx vertx) {
    assertThat(vertx.deploymentIDs()).isNotEmpty().hasSize(2);
  }
```
Stacktrace from test output:
```
java.lang.AssertionError: 
Expected size: 2 but was: 1 in:
["87a7db95-db8e-41d2-8672-d276f1e9a0c7", "6118ee6e-2393-4f27-a55d-b337030fb027"]
	at org.hyperledger.besu.ethereum.p2p.discovery.dns.DNSDaemonTest.lastChecks(DNSDaemonTest.java:143)
```

**Comment by jframe** [comment]
@usmansaleem Is this related to your changes with DNS?

**Comment by usmansaleem** [comment]
Yes, this is definitely related to the github runner environment, I'll try to change the assert conditions to be more resilient.

**Comment by usmansaleem** [comment]
looks like `hasSize` returned 1 even though there are indeed 2 elements. 
```
java.lang.AssertionError: 
Expected size: 2 but was: 1 in:
["87a7db95-db8e-41d2-8672-d276f1e9a0c7", "6118ee6e-2393-4f27-a55d-b337030fb027"]
```
We can safely remove this `lastChecks` method.
