### ISSUE TITLE
Remove junit 4 dependencies

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7742]
Confirm that all tests have been migrated to Junit5
Then can remove junit 4 dependencies
(follow on from #7348 )

**Comment by pr9t** [comment]
Hey, I am interested in this issue. Please assign this to me.

**Comment by macfarla** [comment]
@pr9t great, you'll need to make sure #7348 is finished first though

**Comment by macfarla** [comment]
Apologies @pr9t this is not blocked by #7348 (and I just inadvertently opened a PR that will fix this one) - but you can pick up #7348 !
