### ISSUE TITLE
Generalised request flat encoding changes

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#7744]
Update generalised request encoding for changes introduced in devnet4

- EIP-7251: change request to flat encoding https://github.com/ethereum/EIPs/pull/8857
- EIP-6110: change request to flat encoding https://github.com/ethereum/EIPs/pull/8856
- EIP-7002: change request to flat encoding https://github.com/ethereum/EIPs/pull/8855
- EIP-7685: change requests hash to flat hash https://github.com/ethereum/EIPs/pull/8854
- EIP-7685: group requests into request-data https://github.com/ethereum/EIPs/pull/8924
- Make execution requests a sidecar, take 2 https://github.com/ethereum/execution-apis/pull/591

**Comment by macfarla** [comment]
related to #7671
