### ISSUE TITLE
Contract size limit issue on Besu v24.8.0 – Unknown4 is above the contract size limit (29897 > 24576)

### ISSUE THREAD

**Issue by Manjeet-Nethermind** [hyperledger/besu#7756]
I am running a Besu node with version 24.8.0, and I encountered an issue while trying to deploy a contract. The error message is as follows:
![Screenshot 2024-10-07 at 9 15 08 AM (1)](https://github.com/user-attachments/assets/9be3cd42-c751-49fa-89c9-e3c5a16a72a5)

`Unknown4 is above the contract size limit (29897 > 24576).`

To resolve this, I tried increasing the contract size limit by adding the following to my genesis.json config file:
`"contractSizeLimit": 2147483647`

After adding this change, I restarted the node and even performed a full resync from scratch. However, the issue persists, and the same error continues to appear.

**Below is the genesis.json configuration I am using:**

```
{
  "config": {
    "chainId": 1337,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "contractSizeLimit": 2147483647,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirglacierblock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "zeroBaseFee": true,
    "qbft": {
      "blockperiodseconds": 2,
      "epochlength": 30000,
      "requesttimeoutseconds": 20
    }
  }
}
```

**Steps taken to resolve**:

- Increased the contractSizeLimit value to 2147483647 in the genesis file.
- Restarted the Besu node.
- Resynced the node from scratch.

**Expected Behavior**: The contract should be deployed successfully, and the contract size limit should reflect the updated configuration.

**Actual Behavior**: The same error continues to appear despite the configuration changes.

Environment:

- Besu version: 24.8.0
- Chain ID: 1337

Can someone help to resolve:

1. How to increase the contract size limit ?
2. How to verify the configuration worked (Deploying a large contract is the only way?)

**Comment by siladu** [comment]
On discord, user also sent this for how they are deploying the contract:

```
forge script src/deploymentAndConfiguration/scripts/DeployAndConfigureSystem.s.sol:DeployAndConfigureSystem --fork-url http://localhost:8545/ --broadcast --with-gas-price 0 --legacy
```

@Manjeet-Nethermind If you can share the `DeployAndConfigureSystem.s.sol` also, that will help us recreate this.

**Comment by siladu** [comment]
They also said:
>  I have updated the node to the v:24.9.1 and also synced it from scratch but the error remains same and when I proceed with the deployment a lot of txs get dropped from the mempool

![screenshot_2024-10-14_at_12](https://github.com/user-attachments/assets/c49e0026-a0e2-4817-acba-8929438e7d85)

**Comment by jflo** [comment]
@shemnon could this be a regression of #7557 ?

**Comment by shemnon** [comment]
I don't think it's Besu throwing the error, as "is above the contract size limit" is not an error string in any Besu code.  I think the toolchain is intercepting the large contract and not submitting it to Besu.

@Manjeet-Nethermind What toolchain are you using?

**Comment by siladu** [comment]
On discord they said

> The issue is resolved on upgrading all the nodes to the latest version the contract is successfully deployed.
