### ISSUE TITLE
Remove deprecated --host-whitelist option

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#7761]
The option `--host-whitelist` has been deprecated since 2020, and can be removed now.

-- host-allowlist already exists as an alias for this option, so it's only removing the name, not the functionality

Add to the upcoming changelog to indicate it will be removed soon.

**Comment by TC1211** [comment]
Could me and @janetmo take this issue?

**Comment by macfarla** [comment]
@janetMo you need to comment on here and then can assign you

**Comment by JanetMo** [comment]
Yes I would work with @TC1211 on the issue, thanks!

**Comment by jflo** [comment]
assigned to you two, enjoy.

**Comment by pr9t** [comment]
Hi @macfarla please assign this issue to me.
