### ISSUE TITLE
Add Besu samples for Caliper

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu#780]
see https://github.com/hyperledger/caliper-benchmarks/tree/master/benchmarks/samples

**Comment by benjamincburns** [comment]
Worth mentioning that there are some ethereum/besu benchmarks in the `caliper-benchmarks` repo here: https://github.com/hyperledger/caliper-benchmarks/tree/master/src

**Comment by vmichalik** [comment]
just following up on this since it's open - do we know why the samples are in two different places? can we put a PR to move them and close this? @benjamincburns @NicolasMassart

**Comment by NicolasMassart** [comment]
> do we know why the samples are in two different places?
No sorry I have no idea. I was provided this feedback from a user and created a ticket for it but I can't tell why there's multiple places for samples. I agree only one place would be nice.
