### ISSUE TITLE
Problem using truffle migrate

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#787]
This article helps truffle migrate.
https://besu.hyperledger.org/en/stable/HowTo/Develop-Dapps/Truffle/

But truffle test(web3 1.x send transaction) does not work in my environment.
Error: Transaction has been reverted by the EVM:
...

(The test code works well for Geth.)

I got the following error messages.
```
besu | 2020-04-24 00:00:00.000+00:00 | vert.x-worker-thread-10 | ERROR | JsonRpcHttpService | Error processing JSON-RPC requestBody
besu | java.util.NoSuchElementException: No value present
besu | at java.util.Optional.get(Optional.java:148) ~[?:?]
besu | at org.hyperledger.besu.ethereum.mainnet.ValidationResult.getInvalidReason(ValidationResult.java:40) ~[besu-core-1.4.3.jar:1.4.3]
besu | at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthEstimateGas.errorResponse(EthEstimateGas.java:103) ~[besu-api-1.4.3.jar:1.4.3]
…
```

**Comment by soyama-decurret** [comment]
@shemnon 
I specified the parameter `gas` for web3 send function, and it works fine.
(In the case of Geth, the send function worked well without specifying the `gas`.)

**Comment by Iffay3020** [comment]
I get "wrong chainId" as output when I try to migrate any smart contracts
Error:  *** Deployment Failed ***

"Migrations" -- Wrong chainId.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by vmichalik** [comment]
Hi @shemnon, have you tried this again recently? Can you confirm the bug still exists?

**Comment by shemnon** [comment]
I never used truffle, I was posing an error from chat to make sure it didn't get lost.  Someone else needs to own this as I don't have enough context to do it justice.

**Comment by vmichalik** [comment]
got it, thanks

**Comment by vmichalik** [comment]
closing and will create a new ticket if this resurfaces
