### ISSUE TITLE
EEA spec uses`maxCodeSize` in genesis.json to specify the largest size contract

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#789]
Besu currently uses `contractSizeLimit` to specify the same thing 

To increase EEA compliance, update Besu to use `maxCodeSize` as per the EEA spec.  

Backwards compatibility needs to be consider and if a breaking change, will need to be made in a minor (eg, 1.5) or major release and clearly communicated in the release notes. 

To solve backwards compatibility, @chaals has suggested that `maxCodeSize` should override `contractSizeLimit`. Otherwise, can use the `contractSizeLimit` value.

**Comment by chaals** [comment]
Note there is also an object syntax, to use if there are changes in the life of the blockchain, and thus to follow in order to sync properly.

See https://entethalliance.github.io/client-spec/chainspec.html#sec-maxcodesize for the specification (editors' draft).

**Comment by chaals** [comment]
It would be reasonable to test whether the value is an object and in that case throw as "not implemented yet" if there is such a concept.

The approach is "experimental" - EEA are looking for feedback from implementation experience, and that might lead to changes in the design.

**Comment by non-fungible-nelson** [comment]
@chaals - can we close this?
