### ISSUE TITLE
Besu vulnerable to being used for DDoS amplification

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#792]
Name

SpoofAmplification(v4014)
Description

v4014 amplification attack test: The test spoofs a ping from a different ip address('victim ip'),and later on sends a spoofed 'pong'.

The spoofed 'pong' will have an invalid reply-token (since the target will send the 'pong' to 'victim ip'), and should thus be ignored by the target. If the target fails to verify reply-token, it will believe to now be bonded with a node at 'victim ip'.

The test then sends a spoofed 'findnode' request. If the 'target' responds to the findnode-request, sending a large'neighbours'-packet to 'victim ip', it can be used for DoS attacks.

Details

test failed: unsolicited reply

ref: https://hivetests.ethdevops.io/?suite=1587975179-cc32c661175b2d4bb1660c698f313333.json 
https://github.com/NethermindEth/nethermind/issues/1778

**Comment by davemec** [comment]
@holiman are you able to run this test with debug on so that I can get more information from the besu logs?

**Comment by holiman** [comment]
Debug wasn't fruitful, but trace seems to contain some details. I ran it on a different machine not logged in to github, but pushed the log to the branch 'besu_bugfind' on my cloned project

**Comment by holiman** [comment]
While I was at it, I also ran the sync test on TRACE, using only besu. So one besu node with 10 blocks (source) serving another besu node (sink). They fail to sync with eachother.Pushed logs to the same branch.

**Comment by davemec** [comment]
Thanks @holiman I will take a look, appreciate your help.

**Comment by holiman** [comment]
For the records: https://github.com/holiman/hive/commit/6bb24f9f78f2319f1d85f7d1fddd3a2900c57a21
