### ISSUE TITLE
GraphQL problems

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#799]
See https://hivetests.ethdevops.io/?suite=1587575032-6a6d0e841290bc4726bb016a9a9ba43f.json

For example, `invalidAccount` (click to expand it): 

Test failed. Query:
```
query invalidAccount {
  block {
    account(address: "0xdeadbeef") {
      balance
    }
  }
}

expected:

{
  "errors": [
    {
      "message": "Invalid account address: \"0xdeadbeef\"",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ],
      "path": ["account"],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": null
}

got:

{
  "errors" : [ {
    "message" : "Validation error of type WrongType: argument 'address' with value 'StringValue{value='0xdeadbeef'}' is not a valid 'Address' @ 'block/account'",
    "locations" : [ {
      "line" : 3,
      "column" : 13
    } ],
    "extensions" : {
      "classification" : "ValidationError"
    }
  } ]
}
```
. HTTP response status: 400 Bad Request

So I'm curious, are the graphql tests that I use outdated? How come you don't get these errors yourselves when running your own testcases? Am I doing something wrong?

**Comment by holiman** [comment]
Well, I think they're all from Besu, but I'm not sure. Frank pulled them from Besu, but afaik the graphql hive tests never actually worked until now. 

I'll update them so they match what you have now, for starters. Better than nothing.
Re C), I'm aware of that, so I'll implement something less strict than what it does now (https://github.com/ethereum/hive/blob/master/simulators/ethereum/graphql/graphql.go#L172 ) -- comparing the json structs. 

It otherwise shouldn't fluctuate, all nodes are fed the same 10 bllocks, so they've all "seen" the same things.

**Comment by holiman** [comment]
Updated to the latest: https://hivetests.ethdevops.io/?suite=1588157943-bc222871de0abaa627e9ad880e66837c.json  . Now only 7 failures out of 49 cases

**Comment by holiman** [comment]
Here's a typical failure on geth: 
```
{block(number :"0x8") {number call (data : {from : "a94f5374fce5edbc8e2a8697c15331677e6ebf0b", to: "0x6295ee1b4f6dd65047762f924ecd367c17eabf8f", data :"0x12a7b914"}){data status}}}

Expected:

{
  "data": {
    "block": {
      "call": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "status": 1
      },
      "number": 8
    }
  }
}

Got:

{"errors":[{"message":"hex string without 0x prefix"}],"data":{"block":{"number":"0x8"}}}

HTTP response status: 200 OK
```
In essence, geth doesn't like hex-strings that are not prefixed. And I think that's a sane approach, unless the client can be 100% certain that it's indeed hex-data. If the client 'sniffs' the data-type, we wind up with quirky behaviour on e.g. `1000` -- is it `1000` or is it `0x1000` ? 

So.. .is there any spec for these inputs? Should geh be changed? Should I change the test to supply `0x` ? Thoughts?

**Comment by shemnon** [comment]
The header of the GraphQL EIP requires `0x` prefixes for Bytes32 data types. - https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1767.md#schema - so I think we should have tests where the 0x is not provided and it is a required failure.

**Comment by shemnon** [comment]
Opened #811 to cover the Besu failures for 0x prefixed graphql calls.
