### ISSUE TITLE
GraphQL endpoint should strictly require 0x prefix on bytes

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#811]
Per the GraphQL spec all `Bytes32`, `Bytes`, and `Address` values must be `0x` prefixed.  Current GraphQL parsing code accepts 0x prefixes but does not require them and silently adds them.

There should be at least 6 test cases in `ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql` to verify that each of the above field types produce an error response when provided with a non-prefixed value (3 cases) and each passes with a prefixed value (3 cases).

**Comment by MakMuftic** [comment]
@shemnon I would like to resolve this issue. I already looked up trough the code and have a pretty good idea of how to fix this.
