### ISSUE TITLE
epochlength to 0 in PoA network

### ISSUE THREAD

**Issue by arash009** [hyperledger/besu#836]
Accidentally setting epochlength to 0 in PoA network, flood the logs with Uncaught division by zero error.  Maybe it’s better idea to check for this value during startup or default it to sensible value if its 0.

**Comment by shemnon** [comment]
Rather than default i think we should fail with a sensible error.

**Comment by MadelineMurray** [comment]
@rain-on - @macfarla mentioned Groot might be doing a wider task around genesis file validation as part of the IBFT block rewards work.  Would that cover this?

**Comment by rain-on** [comment]
We didn't do any config validation - ultimately the numbers in the config file can't be validated "out of context" - i.e. where does the logic for "epoch = 0 is illegal" reside? It has to happen in the clique ProtocolScheduleBuilder - as the config file itself only manages validity in terms of field type - not literal content.

**Comment by MadelineMurray** [comment]
epochlength is relevant to IBFT 2.0 as well as Clique isn't it?  ie , the logic would need to be in ProtocolScheduleBuilder for Clique and IBFT 2.0 wouldn't it?

**Comment by rain-on** [comment]
Yes, epoch length is required for IBFT2 as well - so I would expect this change to have a knock on.
