### ISSUE TITLE
Support Color Output for log4j

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#838]
It would be great to have colors for different log levels. At least colorization that makes `WARN` and higher distinctive.

It would be great for debugging to quickly be able to see things that are going wrong in lots of output. It would also look super pretty.

**Comment by timbeiko** [comment]
@RatanRSur I'm pretty sure this is covered by these (old!) tickets:
* https://github.com/hyperledger/besu/issues/539
* https://github.com/hyperledger/besu/issues/540
* https://github.com/hyperledger/besu/issues/541
* https://github.com/hyperledger/besu/issues/542

I think it's probably best to leave comments on these specific issues vs. opening a new one.

**Comment by RatanRSur** [comment]
True! Didn't see those
