### ISSUE TITLE
Add current block number to eth_getWork response

### ISSUE THREAD

**Issue by ppratscher** [hyperledger/besu#849]
### Description
We are currently evaluating besu as mining backend client for our ethermine mining pool (second largest ethereum pool). Currently the eth_getWork response does not include the current block number as fourth return value. Currenty both geth & parity return the block number as last value. Access to the block number makes it easier to initialize the PoW validation engine.

### Steps to Reproduce (Bug)
`curl --data '{"method":"eth_getWork","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`

**Expected behavior:** Return hex encoded current block number in eth_getWork response

**Actual behavior:** Current block number is not included in the eth_getWork response

### Versions (Add all that apply)
* Software version: besu/v1.4.4/linux-x86_64/openjdk-java-11

**Comment by timbeiko** [comment]
@ppratscher it should be available off master now 😄Would love to get feedback on your use of Besu!
