### ISSUE TITLE
Try to migrate contract using .new() 

### ISSUE THREAD

**Issue by yehia67** [hyperledger/besu#855]
Hello,
I am trying to migrate a contract using pure Javascript.

```
static async deploy(contractName,args){  
    const filePath = path.resolve('build/contracts/'+contractName+'.json');
    let rawdata = fs.readFileSync(filePath);
    const  contractArtifacts = JSON.parse(rawdata); 
    const newContract = contract(contractArtifacts);
    newContract.setProvider(web3Provider)
    const newInstance = await newContract.new(...args,{from:"0x627306090abaB3A6e1400e9345bC60c78a8BEf57",gas:"0"});
   
    return newInstance;
  }
```
The expected output was a new instance but I got this error:
`    Returned error: The method eth_sendTransaction is not supported. Use eth_sendRawTransaction to send a signed transaction to Besu.
`
So I tried to uses web3 instead of .new()
```
const newInstance =  await new web3.eth.Contract(contractArtifacts.abi)
		.deploy({
      data:"0x016f9712d43c175150d9328712c41aa34cbc65815eda38f9aa7fc2abb3e5b2d3",
			arguments: args
		})
		.send({
			from: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57',
			gas: '0'
		});
    return newInstance;
```
But it gave me the same error. Could you please tell me what this error mean? and how to solve it?
Thanks in advance.

**Comment by timbeiko** [comment]
We do not support sending unsigned transactions in Besu. You can either send a signed transaction using [eth_sendRawTransaction](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_sendrawtransaction) or otherwise use a transaction signer, such as EthSigner, to send your transaction. For more information on how to do that, see this docs page:  https://docs.ethsigner.pegasys.tech/en/stable/HowTo/Transactions/Make-Transactions/#eth_sendtransaction

**Comment by timbeiko** [comment]
I'll close the issue for now, but please reopen if you have any additional questions. Thanks!

**Comment by yehia67** [comment]
Hello @timbeiko ,
I tried to make a raw transaction by following this [tutorial](https://besu.hyperledger.org/en/1.2.0/Using-Pantheon/Transactions/Transactions/) 
```
 static async deploy(contractName,args,private_key){  
    const filePath = path.resolve('build/contracts/'+contractName+'.json');
    let rawdata = fs.readFileSync(filePath);
    const  contractArtifacts = JSON.parse(rawdata); 
    const addressFrom = web3.eth.accounts.privateKeyToAccount(private_key).address;
    const contractData = contractArtifacts.bytecode;
    web3.eth.getTransactionCount(addressFrom, "pending").then((txnCount) => {
      // Create the contract creation transaction object
      var txObject = {
         arguments:args,
         nonce: web3.utils.toHex(txnCount),
         gasPrice: 0,
         gas: "0x1ffffffffffffe",
         data: contractData
      };
      var tx = new ethTx(txObject);
      const privateKey = Buffer.from(private_key,'hex');
      tx.sign(privateKey);
      var serializedTx = tx.serialize();
      var rawTxHex = '0x' + serializedTx.toString('hex');
      web3.eth.sendSignedTransaction(rawTxHex)
      .on('receipt', receipt => { console.log('Receipt: ', receipt); })
      .catch(error => { console.log('Error: ', error.message); });
    })
  }
```

and then test it
```
const test = async()=>{
    await contractClass.deploy('VirusToken',["yarab","yta",0],'7af1e61aa083d038474bdf1ec59620c6431d710858d7a8436389713f2adf3d8f');
}
```
It gave me this error
`Error:  Returned error: Invalid params`  
What am I doing wrong?  Thanks.

**Comment by yehia67** [comment]
Edit
I used  `const EthCrypto = require('eth-crypto');` to parse contract data like this
```
  const contractData = EthCrypto.txDataByCompiled(
      contractArtifacts.abi, // abi
      bytecode, // bytecode
      args // constructor-arguments
  );
```
But it still returns the same error to me.

**Comment by yehia67** [comment]
found the solution 
https://stackoverflow.com/questions/57350172/web3-web3-eth-sendsignedtransaction-invalid-params
 
I used pure web3js without ethTx
