### ISSUE TITLE
Remove unneeded `removeAllKeysUnless` method from key value storage interfaces

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#861]
We introduced this for pruning but we no longer need it. The API is marked as unstable and the one party implementing the interface doesn't use the method anyways.

**Comment by yehia67** [comment]
You want to remove 
` long removeAllKeysUnless(Predicate<byte[]> retainCondition) throws StorageException;`
From  
`plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java`
right?

**Comment by RatanRSur** [comment]
And also from `SegmentedKeyValueStorage` :)

Both of those interfaces have implementors as well, you'll need to remove those methods from the implementations.
