### ISSUE TITLE
datadir needs more than 3x disk space (compared to datadir of geth)

### ISSUE THREAD

**Issue by thorstenhirsch** [hyperledger/besu#867]
### Description
As a user I expect my ethereum client to have an efficient (size and time) storage layer. However when switching from geth (leveldb) to besu (rocksdb) the required disk space for ~6 million blocks (99% empty) increased from 2.2GB to 6.9GB. 

### Acceptance Criteria
* datadir size doesn't need more than 50% more than datadir of geth

### Steps to Reproduce (Bug)
1. start/join permissioned network with clique
2. wait until a decent amount of blocks has been built
3. compare datadir of besu with datadir of geth

**Expected behavior:**
Since rocksdb might need a bit more space in order to provide faster read/write, it's okay to see up to 50% increased disk space.

**Actual behavior:**
More than 3x disk space is required for besu.

**Frequency:** I guess always... but it might have to do with 99% empty blocks.

### Versions (Add all that apply)
* Software version: 1.4.4
* Java version: OpenJDK 11
* OS Name & Version: RHEL7
* Kernel Version: 3.10.0-1062.4.1.el7.x86_64

**Comment by thorstenhirsch** [comment]
hi tim, if you have some ideas where to look for the root cause or which knob to turn and check if it solves the issue - i'd be glad to help

**Comment by timbeiko** [comment]
Hey @thorstenhirsch, 

I self-assigned this to make sure one of our engineers has a look shortly. If this is mostly empty blocks, I suspect we may have some performance improvements to do deep in the client. If you are looking for potential configurations for Besu/RocksDB, I suggest heading to https://chat.hyperledger.org in the #besu channel and asking there. People may be able to give you optimal configs for your specific use case!
