### ISSUE TITLE
Create flag to inform services that need an assumption about potential reorg depth

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#869]
We have multiple services that are in part parameterized by the user's risk tolerance for reorgs.

`pruning-blocks-retained` and `Xsynchronizer-fast-sync-pivot-distance` for example.

I propose we create a new flag that will create a floor for these parameters, ensuring that those services are at least as wary of chain reorgs as the user would like them to be.

**Comment by non-fungible-nelson** [comment]
Closing as stale. @RatanRSur - can you review for re-open? Pruner and fast-sync not supported at this point.

**Comment by non-fungible-nelson** [comment]
@diega - any need for this feature on PoW side?

**Comment by diega** [comment]
not for the moment
