### ISSUE TITLE
Support using private logs when using onchain privacy groups with multi-tenancy 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#882]
When using priv_getLogs, priv_getFilterLogs, priv_getFilterChanges only logs up to the removal block are returned when the “to_block” is greater than the removal block.

Need to confirm and document behaviour if a member is removed and then re-added later.  Will those logs be available?  If not, ensure this is clearly doc'd. 

Two parts to this: 
**Hash** 
Check specific hash 

**Range**
Check last block in range.  If not a member at last block, don't return anything. The user must know when they were removed to access historical logs from a group they are no longer a member of.

**Comment by macfarla** [comment]
with getFilterLogs and getFilterChanges - assuming that any filters the user has created will be removed when the user is removed from the group - there is nothing to do here. We can recommend to use getLogs in the docs.
