### ISSUE TITLE
Known Issues doc: full sync or fast sync ?

### ISSUE THREAD

**Issue by nayuta-ueno** [hyperledger/besu#885]
https://github.com/hyperledger/besu/blob/135270605a7039f22f2da1360902c8dabb199643/KNOWN_ISSUES.md#error-full-syncing-with-pruning

> caused by the combination of full sync and pruning.

But, The workaround is written about fast sync:

> 1. Explicitly disable pruning using --pruning-enabled=false when using fast sync.

Does this issue occur in fast sync and not in full sync?

**Comment by RatanRSur** [comment]
Sorry for the confusion! It can affect both but pruning only needs to be explicitly disabled with fast sync because it's off by default with full sync. Thanks for pointing that out, I'm about to put up a PR with clarification.
