### ISSUE TITLE
Errors when creating privacy groups when using PostgreSQL

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#903]
Errors when creating privacy groups when using PostgreSQL

Besu1, Besu2, Orion is multi-tenancy configured.
Orion has 5 orion keys in it.

When creating a privacy group of more than 3 members, a NodePropagatingToAllPeers error occurs. But the a privacy group appears to have been created.

When creating a privacy group of 2 members, it succeeds.

LB1 ┬ Besu1(1.4.2) ┬ orion(1.5.0) 
└      Besu2(1.4.2) ┘ 
LB2 ┬ Besu3(1.4.2) 
└ Besu4(1.4.2)

Investigate and determine what conditions we can re-create this. 

Is it PostgreSQL and mutli-tenancy not working together?

**Comment by MadelineMurray** [comment]
This is to investigate.  Will raise new issues if stuff needs fixing.

**Comment by lucassaldanha** [comment]
This problem was fixed by: https://github.com/PegaSysEng/orion/pull/369

We'll release Orion 1.5.6 that contains the fix
