### ISSUE TITLE
Implement configuration for acceptance test node to retain p2p port number

### ISSUE THREAD

**Issue by mark-terry** [hyperledger/besu#907]
### Description
There's some use-cases (#528) where it is required that an acceptance testing node needs to retain its p2p port across restarts. In this case enode URLs are being compared for permissioning checks.

### Acceptance Criteria
Node p2p port persists across restart.

**Comment by ajsutton** [comment]
Note: Preserving the p2p port *will* lead to failures because of port conflicts.  You'd have to use something like docker to provide isolation between tests.
