### ISSUE TITLE
Check transaction types when replacing in the transaction pool.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [hyperledger/besu#923]
### Description
Add checks on the replacement of a transaction in the pool:
- reject EIP-1559 for pre-fork blocks
- accept both frontier and EIP-1559 transactions during phase 1
- reject frontier transactions after phase 2 is finalized

**Comment by RatanRSur** [comment]
I think we talked about this but I forgot, can you replace a frontier tx with an EIP-1559 tx?

**Comment by abdelhamidbakhta** [comment]
> I think we talked about this but I forgot, can you replace a frontier tx with an EIP-1559 tx?

Yes you can. But only during the transition phase. This is what this PR is about.
