### ISSUE TITLE
Support DNS discovery

### ISSUE THREAD

**Issue by atoulme** [hyperledger/besu#927]
# Description
As an operator of a Besu node, I want to be able to use DNS discovery to complement UDP-based discovery, using the mechanism defined with EIP-1459. 

### Acceptance Criteria
* An operator can define a host to start DNS discovery from (ex: example.com).
* In the absence of an explicit host, if the operator runs a named network (mainnet, ropsten), it uses the proper host name.
* DNS discovery may be explicitly disabled.

**Comment by timbeiko** [comment]
@atoulme are you aware of whether other clients use this and, if so, in what context? This sounds interesting, but it'd be great to have more context about the usage of EIP-1459 in the community and the benefits. Thanks!

**Comment by atoulme** [comment]
Geth supports DNS discovery.

**Comment by atoulme** [comment]
Also, Apache Tuweni implemented DNS discovery as a library, so it can be integrated into Besu.

**Comment by shemnon** [comment]
Are there any "in the wild" DNS entries that are being used?

**Comment by atoulme** [comment]
Not sure what you mean, sorry.

From what I have seen, the geth team keeps a tally of nodes it is connected to over time, and offloads the list to a github repository here: 
https://github.com/ethereum/discv4-dns-lists

This then gets parsed and sent to AWS Route 53 on a regular basis.

Note the node list has rating per node, but I don't know how the rating is computed.

**Comment by shemnon** [comment]
Would ENR support be required to make sense of the lookup?

**Comment by atoulme** [comment]
The DNS entries are ENRs. So, yes, you'd need something that reads ENRs. Which I implemented in that library I mentioned earlier ;)
