### ISSUE TITLE
EIP-2565

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#934]
Implement EIP-2565 (https://eips.ethereum.org/EIPS/eip-2565) using Option 1

> **Option (1): Change value of GQUADDIVISOR**
> GQUADDIVISOR is set to ‘20’ per EIP-198. We recommend changing the value of this parameter to ‘200’.

As per AllCoreDevs #87 (https://github.com/ethereum/pm/issues/169) it's unclear if this will be required for the Ephemeral Berlin testnet, so we should figure out what the consensus is across clients for this.

**Comment by RatanRSur** [comment]
I think the update from the last ACD was that it won't be this option.
