### ISSUE TITLE
Update guidance around --remote-connections-limit-enabled for private & public permissioned networks

### ISSUE THREAD

**Issue by benjamincburns** [hyperledger/besu#982]
### Description
Presently in the docs we have some guidance around how to use `--remote-connections-limit-enabled` and `--remote-connections-max-percentage` in the case of public networks. Unfortunately, there isn't any guidance at present for private or public-permissioned networks.

Recently while running a node on a public permissioned network we observed that we weren't able to maintain a full peer list, in spite of our `max-peers` being set to a number well below the size of the network. On checking the logs, we found a lot of connection thrashing. This appeared to be happening at least in part because we weren't accepting new remotely initiated peer connections.

I think that most users are likely willing to accept having a peer list that isn't always full in return for resilience to eclipse attacks, but this trade-off isn't immediately apparent, which causes the instability of the peer count to seem like a bug. Furthermore, in our case it might have been a better approach to raise the value of `--remote-connections-max-percentage` from 60 to 80. Higher values still might also be acceptable, provided that we quickly disconnect remotely-initiated peer connections that don't have permission to join the network (I don't know whether we do this or not, but I'd assume that we do).

### Acceptance Criteria
* Documentation is updated to give guidance for setting the values of `--remote-connections-limit-enabled` and `--remote-connections-max-percentage` in the context of private, and public/permissioned networks.
* Documentation sets users expectations for how these settings might impact their nodes' ability to fill their peer lists.
* Documentation should explain that the value chosen for `--remote-connections-max-percentage` will affect how densely connected the network is, depending on the number of nodes in the network and the max peer limit set.

### Versions (Add all that apply)
* Software version: 1.4.5

**Comment by MadelineMurray** [comment]
Moving this to `besu-docs` repo

**Comment by MadelineMurray** [comment]
Issue moved to [hyperledger/besu-docs #409](https://github.com/hyperledger/besu-docs/issues/409) via [**ZenHub**](https://www.zenhub.com/)
