### ISSUE TITLE
Besu Failing Hive Fast Sync Tests 

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#987]
Besu is failing on several of the [hive fast sync tests. ](https://hivetests.ethdevops.io/?suite=1590292715-4c4169b69788f07283ba1681d2f220d4.json). We should investigate those failures and ideally fix them so that Besu passes all tests.

**Comment by sambacha** [comment]
Here is our reference sheet if anyone is curious, contains links to the hive tests. 
[google.com/spreadsheets/ft-besu-hive-tests](https://docs.google.com/spreadsheets/d/e/2PACX-1vSBMZI-QoXSRIPmREbIF_tX7RDZ4BGD6kM0H-NSBSnRyyqtiLhPtL9_olIAgzBGJbMAnA8fMgUakTYR/pubhtml)


devp2p sticks out as its always  `Fail (5 / 13)`

**Comment by timbeiko** [comment]
@sambacha thanks! over the next few weeks/months we plan on trying to get everything passing on Hive 👍

**Comment by sambacha** [comment]
💯 thanks for your help and concern on this matter, appreciate the work the Besu team does!

**Comment by davemec** [comment]
Current failing fast sync tests
- fast-sync aleth_nightly -> besu_latest
- fast-sync besu_latest -> aleth_nightly
- fast-sync go-ethereum_latest -> besu_latest
- fast-sync nethermind_latest -> besu_latest
- fast-sync parity_latest -> besu_latest

**Comment by davemec** [comment]
Current failing fast sync tests

- fast-sync aleth_nightly -> besu_latest
- fast-sync besu_latest -> aleth_nightly
- fast-sync nethermind_latest -> besu_latest

All nethermind tests are currently failing.
