### ISSUE TITLE
How to start a Besu PoA blockchain and manage validators OUTSIDE OF AZURE

### ISSUE THREAD

**Issue by Tectract** [hyperledger/besu#989]
### Description
We are trying to set up a new PoA blockchain. Not in Azure.

### Acceptance Criteria
Node setup instructions need clarification

### Steps to Reproduce (Bug)
1. How is the genesis file generated? Any difference for Clique versus IBFT? Where does the data for each field required in the genesis file come from? Does there need to be a smart contract in the genesis file? If so, how is that smart-contract generated?

2. How are validators managed? We are not interested in opening up RPC or HTTP ports. Can it be done via commands to the Besu node? What are those commands? What commands are needed to add and remove validators? What will happen if the nodes need to restart? Will they forget this list and need to be manually fed a list of current approved validators again? Where is the validator set stored in each node?

3. Do any ports need to be open besides UDP and TCP on port 30303?

4. Once I start my node, what information do I need to give to the other validators (and other non-validators) in order to connect their nodes to mine? What information do I need from the other validators in order to add / propose them to the validator list?

**Actual behavior:** [What actually happens]

Docs are pretty unclear about all these things. I guess there is some GUI toolset for managing nodes in Azure, but we're NOT using Azure...

**Frequency:** [What percentage of the time does it occur?]

All the time until we get our blockchain started.

### Versions (Add all that apply)
* Software version: [`besu --version`]

besu/v1.4.1-dev-ad5bfecd/linux-x86_64/zulu-java-13

* Java version: [`java -version`]

openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment Zulu13.29+9-CA (build 13.0.2+6-MTS)
OpenJDK 64-Bit Server VM Zulu13.29+9-CA (build 13.0.2+6-MTS, mixed mode, sharing)

* OS Name & Version: [`cat /etc/*release`]

Linux Mint 17 Qiana

* Kernel Version: [`uname -a`]

based on Ubuntu 14.04

* Cloud VM, type, size: [Amazon Web Services I3-large]

standalone linux server, not in the cloud

**Comment by sambacha** [comment]
You can add validators using the command line, it's in the documentation
for Besu.

You can look at our GitHub.com/freight-chain/node for a tutorial on how to
do it on any cloud provider.

Let me know if you have any questions, happy to help.
